### ISSUE TITLE
Task type is no longer CSLCompliant

### ISSUE THREAD

**Issue by tmeschter** [Microsoft/msbuild#1005]
While updating another project that references the 15.1 binaries and has a few classes that derive from `Task` I started getting errors that those types were not CSLCompliant because the base `Task` type was not CLSCompliant.

If `Task` was previously CLSCompliant we probably want to keep it that way, if only so customers don't run into these sorts of errors when updating existing projects to use a newer version of MSBuild.

**Comment by AndyGerlicher** [comment]
This should be in #945. Hopefully the binaries you were using were stale and this is resolved?

**Comment by jeffkl** [comment]
This was fixed
