### ISSUE TITLE
Always produce satellites; sync xlf on demand

### ISSUE THREAD

**Issue by cdmihai** [Microsoft/msbuild#1011]
Right now we either do a full localized build (sync xlf files AND use satellite assemblies) or not (no satellites, no sync).

We should instead do a hybrid: always generate resource assemblies, but sync xlf on demand.

This would help with:
- create local debug nuget packages with satellites in them for testing purposes
- increase the dev usage of satellites (catch loc infra bugs earlier)
- xliff parser is not yet .net core compliant, so separating it out will enable us to do xplat localized builds

**Comment by rainersigwald** [comment]
This is more general than https://github.com/Microsoft/msbuild/issues/1050, closing that one and adding the label to this one.
