### ISSUE TITLE
Crossplat MSBuild and glob expansion

### ISSUE THREAD

**Issue by cdmihai** [microsoft/msbuild#1026]
When MSBuild expands globs, it currently 
- uses the file system's path separator to stitch together path fragments that are coming from the recursive directory walk
- uses the original string values for the path fragments already provided by the user

On windows there is the following behaviour:

`**` expands to `a\b\c\foo.cs`
`a/**` expands to `a/b\c\foo.cs`
`a\**` expands to `a\b\c\foo.cs`

However, on crossplat msbuild we should choose whether to keep the current behaviour or change to some other things:
- impose a standard slash indifferent of the OS: `a/**` expands to either `a\b\c\foo.cs` or to `a/b/c/foo.cs` (depending on which slash we choose as the standard one).
  - Pros:
    - Project files are crossplatform. The user knows what slashes MSBuild uses so it can directly use them in conditions and such
    - If we use `\` as the standard, legacy project files won't break
  - Cons:
    - Task consuming the paths may break if they are using slash agnostic System.IO libraries
- use the OS specific slashes
  - Pros
    - Task consuming the paths won't break if they are using slash agnostic System.IO libraries
  - Cons
    - Project files are not crossplatform. If the user has conditions based on paths, conditions might now evaluate differently on windows vs !windows
    - Follows from the previous one: legacy project files are not crossplat if the user has conditions based on paths

**Comment by jonpryor** [comment]
My two cents: this shouldn't matter, [if `\` and `/` are treated as the same character in string comparisons](https://github.com/Microsoft/msbuild/issues/1024#issuecomment-248669947).

You should thus use `\` in all project files, and when using glob expansion, it won't really matter what the result is, because `/` and `\` will be treated interchangeably.

**Comment by natemcmaster** [comment]
Another question: what about the ['?' wildcard](https://msdn.microsoft.com/en-us/library/ms171453.aspx#Anchor_3)? On Windows, '?' is an invalid filename character, but not on *nix/macOS.

**Comment by cdmihai** [comment]
You have to escape `?` with `%3F` to have it treated as a literal.

**Comment by dazinator** [comment]
Would be great if there was a standardised path seperator when writing paths to project files. For projects with collaborators on multiple platforms, adding and removing an item from the project shouldn't cause a path to be changed within the project file, from previoulsy using '/' to using '\' etc - as this will then show as a change, when really nothing has changed.

**Comment by livarcocc** [comment]
We have chosen to keep the current behavior. At this point, changing this would be a big breaking change for what does not look like a fantastic improvement.
