### ISSUE TITLE
ITaskItem could have a way to access all non-well-known metadata

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/msbuild#1028]
[`ITaskItem.MetadataNames`](https://github.com/rainersigwald/msbuild/blob/6fef01a8683f76a52d0a379bc12e5ee02d15b990/src/Framework/ITaskItem.cs#L31-L39) returns a list of all metadata defined on a given item--including the you-can't-get-rid-of-it computed [well-known metadata](https://msdn.microsoft.com/en-us/library/ms164313.aspx).

@blackdwarf thought it would be nice to be able to iterate over all of the custom metadata without the well-known stuff. That does seem reasonable (though it'd have to go into `ITaskItem3`, which is unfortunate).

**Comment by rainersigwald** [comment]
Workarounds:

* You can use only and explicitly metadata you expect on your inputs (this is the common case)
* You can manually filter out the well-known items by consulting that MSDN page and making your own set of properties to ignore.
* You can use [`ITaskItem.CloneCustomMetadata`](https://github.com/rainersigwald/msbuild/blob/6fef01a8683f76a52d0a379bc12e5ee02d15b990/src/Framework/ITaskItem.cs#L83-L92) to get an `IDictionary` that contains only the custom metadata. You can (in the [current implementation](https://github.com/rainersigwald/msbuild/blob/6fef01a8683f76a52d0a379bc12e5ee02d15b990/src/Shared/TaskParameter.cs#L676-L698)) cast that to `Dictionary<string, string>` and walk over _that_ instead.

**Comment by blackdwarf** [comment]
Thanks @rainersigwald! :)

**Comment by rainersigwald** [comment]
There could be a new method `ITaskItem3.CustomMetadataNames`, or we could do something like JavaScript's [`Object.prototype.hasOwnProperty`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty), which fulfills a similar need.

**Comment by cdmihai** [comment]
Is this a design time project item? Then you can use the subclass `ProjectItem.DirectMetadata` property: https://github.com/Microsoft/msbuild/blob/master/src/XMakeBuildEngine/Definition/ProjectItem.cs#L233-L236

That interface is quite disfunctional.

**Comment by livarcocc** [comment]
We haven't heard of a need for this since. Closing for now.
