### ISSUE TITLE
Update NuGet packages to contain XML documentation

### ISSUE THREAD

**Issue by jeffkl** [Microsoft/msbuild#1031]
Already done with [Microsoft.Build.Framework](https://github.com/Microsoft/msbuild/commit/235532d575796ad931338b18767576084cd82cf3) and [Microsoft.Build.Utilities](https://github.com/Microsoft/msbuild/commit/5b9e965b51fc639ad7d65a56f59965f7ebbae8da), still need to do Microsoft.Build.

@rainersigwald @AndyGerlicher @cdmihai I'll probably skip Microsoft.Build.Tasks because most people don't reference it or need intellisense from it right?

**Comment by rainersigwald** [comment]
Seems fine to deprioritize or skip Tasks, yeah.

**Comment by cdmihai** [comment]
Some tasks are meant to be subclassed right?

**Comment by jeffkl** [comment]
@cdmihai from my quick look at the classes in Tasks, most of them are subclasses for other tasks in the Tasks assembly.

The stuff that our general audience would consume are in Utilities (ie Task, ToolTask, etc).  Does that seem correct to you?

**Comment by cdmihai** [comment]
I was thinking of the case where people want to extend actual tasks like `Copy`. But I have no idea how prevalent that is in the MSBuild community :)
