### ISSUE TITLE
Exec task: unicode support

### ISSUE THREAD

**Issue by v-yadli** [Microsoft/msbuild#104]
Unicode characters cause Exec task to fail. Example error output:
```
------ Build started: Project: TSLProject1, Configuration: Debug x64 ------
	"C:\Users\中文用户\AppData\Local\Microsoft\VisualStudio\11.0\Extensions\qnci5dgg.btj\Binaries\Trinity.TSL.Compiler.exe" --BuildDataModelingProject --ProjectRoot "c:\users\中文用户\documents\visual studio 2012\Projects\TSLProject1\TSLProject1" --ScriptList "MyTSL.tsl" --OutputPath "bin\Debug\ " --AssemblyName Trinity.Extension.0.dll --RootNamespace Trinity.Extension --Clean --BuildDataModelingProjectWithDebugFeatures 
	The system cannot find the path specified.
```
See also:

http://stackoverflow.com/questions/14224496/

**Comment by akoeplinger** [comment]
See [XMakeTasks/Exec.cs#L280-L285](https://github.com/Microsoft/msbuild/blob/a9a35a87866417e383626519e96ffcde26d554ad/src/XMakeTasks/Exec.cs#L280-L285) for some background info.

**Comment by v-yadli** [comment]
@akoeplinger I've already read that. For my current task I'm attempting to derive from the Exec task. Will get back to report if it works.

**Comment by jasonwilliams200OK** [comment]
There are other issues with `Exec.cs` as well: https://github.com/dotnet/roslyn/pull/575#discussion_r30915354. The xplat branch is also having `cmd.exe`.

> For my current task I'm attempting to derive from the Exec task. Will get back to report if it works.

@jaredpar, @mmitche, I think probably the efforts can be converged here, either to make `class Exec` aware of environment and culture specifics or sub-class `Exec`/`ToolTaskExtension` to form `NetExec`?

**Comment by akoeplinger** [comment]
@jasonwilliams200OK That is just the toolname, the actual executable is retrieved as "sh" here: [Exec.cs#L582](https://github.com/Microsoft/msbuild/blob/b9d70b679e7b62d6007f85f4e2c82c2f1f45e3c0/src/XMakeTasks/Exec.cs#L582)

**Comment by v-yadli** [comment]
It's ugly...

```C#
        protected override int ExecuteTool(string pathToTool, string responseFileCommands, string commandLineCommands)
        {
            /* In ExecuteTool Exec will attempt to delete the 'script file'.
             * That would cause an exception for sure. However,
             * we could not derive from its base, nor can we invoke
             * base.base.ExecuteTool. So we make a dummy file for it
             * to delete. To do this, we invoke base's AddCommandLineCommands
             * so that it calls CreateTemporaryBatchFile. Since the base's base
             * already captured our correct parameters, it is safe to hack it.
             */
            this.Command = "TSLCompileTask"; // This will trick VS to display "The command 'TSLCompileTask' failed with code..." on error.
            Microsoft.Build.Tasks.CommandLineBuilderExtension commandLine = new CommandLineBuilderExtension();
            base.AddCommandLineCommands(commandLine);

            return base.ExecuteTool(pathToTool, responseFileCommands, commandLineCommands);
        }
```

But at least it works -____-"

**Comment by AndyGerlicher** [comment]
Marking as up-for-grabs as this is something we would like to have working correctly.

**Comment by akoeplinger** [comment]
@v-yadli Some work was done in https://github.com/Microsoft/msbuild/pull/143 to address this, can you check if that fixes your problem as well?

**Comment by rainersigwald** [comment]
I'm going to mark this as closed since the fix went in last year.
