### ISSUE TITLE
Ensure official build works in xplat

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#1049]
In order to fully switch to xplat, we'll need to be producing official builds using our (Microsoft-internal) build + signing system.

**Comment by rainersigwald** [comment]
@jeffkl Is this done? You've got it so that the microbuild builds both net46 and netcore, which should be all we need here, as long as they're both signed correctly as well.

**Comment by jeffkl** [comment]
Yeah it just doesn't build the `.vsix` as far as I know...

**Comment by rainersigwald** [comment]
Well, that's #1048. Awesome, thanks.
