### ISSUE TITLE
MSBuild child nodes do not inherit parent node's process priority

### ISSUE THREAD

**Issue by phkelley** [Microsoft/msbuild#1055]
This bug report refers specifically to MSBuild running on Windows.

If I start MSBuild.exe with process priority "below normal" (6) and the /m command line switch, and that MSBuild.exe starts child MSBuild.exe processes, then these child nodes still run with normal (8) process priority. It would be better for them to inherit the parent process' priority, because without such inheritance, it becomes impossible to effectively "nice" a multiprocessor build.

Thanks,
Philip
Visual Studio Team Services

**Comment by phkelley** [comment]
Looks like the bug is on line 368 of src/XMakeBuildEngine/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs. Instead of setting the value to NORMAL_PRIORITY_CLASS, just set it to zero.

**Comment by rainersigwald** [comment]
I just stumbled across #166, of which this is a duplicate.
