### ISSUE TITLE
Microsoft.Cpp.Default.props

### ISSUE THREAD

**Issue by svnpenn** [Microsoft/msbuild#106]
In the past I have found this file under the MSBuild folder, so I assumed it was
part of MSBuild.

~~~
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Default.props
~~~

However it appears to not be a part of this repository. I was excited when I
noticed that MSBuild was on GitHub, as a [7 MB download][1] is more tolerable
than [6.5 GB download][2].

[1]:http://packages.nuget.org/v1/Package/Download/MSBuild
[2]:http://microsoft.com/download/details.aspx?id=44914

**Comment by AndyGerlicher** [comment]
This is correct, C++ targets and tasks aren't included in this repo (not open sourced at this time).

**Comment by svnpenn** [comment]
![fuuuu](http://fc06.deviantart.net/fs71/f/2009/363/4/b/fuuuu_by_gamerdudexi.jpg)

**Comment by AndyGerlicher** [comment]
@svnpenn your comment was deleted due its rude / offensive nature. Please keep the discussion on this topic professional.

**Comment by svnpenn** [comment]
https://github.com/Microsoft/msbuild/issues/120

**Comment by svnpenn** [comment]
@AndyGerlicher please confirm why this was closed. Is this issue WONTFIX or WISH?

**Comment by AndyGerlicher** [comment]
@svnpenn I passed your feedback on to the C++ team. I don't think there is a plan to open source at this time though. There is a new Build Tools sku of Visual Studio "15" you can download here: https://blogs.msdn.microsoft.com/vcblog/2016/11/16/introducing-the-visual-studio-build-tools/

That will have the targets/tasks from C++.

**Comment by svnpenn** [comment]
https://github.com/Microsoft/msbuild/issues/103

**Comment by BuildMonkey** [comment]
Hello,

Many years have past since this ticket was closed. I was wondering if the stance on the C++ targets hasn't changed in recent years. For what I am doing, it would be great to have the C++ targets included in this project. 

Please let me know if there are plans to introduce C++ targets into this project.

Thanks!
