### ISSUE TITLE
Cross-targeting dispatch to inner builds should be parallelized

### ISSUE THREAD

**Issue by nguerrera** [Microsoft/msbuild#1064]
See https://github.com/Microsoft/msbuild/pull/1063#pullrequestreview-1059961

**Comment by rainersigwald** [comment]
Related to https://github.com/Microsoft/msbuild/issues/1276.

**Comment by Sarabeth-Jaffe-Microsoft** [comment]
We think this is completed. Re-open if not. Thanks!

**Comment by rainersigwald** [comment]
No, this isn't done.

**Comment by rainersigwald** [comment]
@borgdylan In https://github.com/Microsoft/msbuild/issues/1276#issuecomment-285766358 it sounded like you had a concern about this. If that's still the case can you expand on it please?

**Comment by borgdylan** [comment]
All I'd like is that I always get the option to not run the build in parallel by default. I am currently setting $(BuildInParallel) to false.

**Comment by borgdylan** [comment]
My compiler unlike Roslyn cannot handle more than one compile in the same process.

**Comment by rainersigwald** [comment]
Can you write the file to obj (that is, `$(IntermediateOutputPath)`)? That should be unique per TFM build.

**Comment by borgdylan** [comment]
The code includes the generated file via #include so I'd have to make the compiler read it automatically instead.
