### ISSUE TITLE
GetAllGlobs overload to restrict results for directory

### ISSUE THREAD

**Issue by cdmihai** [microsoft/msbuild#1066]
There should be a `GetAllGlobs(string parentDirectory)` overload to only return globs that may point inside a directory.

`GetAllGlobs("src")` should return the globs marked with `x`

```
x "**/*.cs
x src/**/*.cs
x sr?/**/*.cs
x a/src/**/*.cs
b/**/*.cs
```

This method signature is already taken, unfortunate, so maybe a new method name like `GetAllGlobsUnderDirectory`

**Comment by cdmihai** [comment]
@jviau

**Comment by livarcocc** [comment]
Closing as it does not really seem like there is a need for this at this point.
