### ISSUE TITLE
MSB3644 still has warning-like text

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/msbuild#1071]
In #450 to fix #173, MSB3644 was changed to a warning from an error. But its text [still says](https://github.com/Microsoft/msbuild/blob/e7019886b3fd520b547a7353d78d106d72a4b828/src/XMakeTasks/Resources/Strings.resx#L2101)

> Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in
> place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.

That's misleading now, because this is an error that will stop the build--the user's assembly will no longer be incorrectly targeted.

**Comment by livarcocc** [comment]
@KathleenDollard for a better error message here.

**Comment by KathleenDollard** [comment]
@rainersigwald Do you have proposed text here. I'm only 90% sure I know what's going on.

**Comment by rainersigwald** [comment]
Duplicate of #4202
