### ISSUE TITLE
Question: Will MSBuild be able to load tasks compiled against Mono's XBuild ?

### ISSUE THREAD

**Issue by borgdylan** [Microsoft/msbuild#108]
I have tasks compiled against Mono's version of Ms.Build.Utilities etc. Currently MSBuild fails to load these as the Task base class is not the same between XBuild and MSBuild. Will there be a way to have portable task assemblies under Mono?

**Comment by AndyGerlicher** [comment]
No this won't work. I wrote a wiki article about the [Microsoft.Build.Framework](https://github.com/Microsoft/msbuild/wiki/Microsoft.Build.Framework) dll and the issues with the OSS and shipping versions of MSBuild that are similar to this. Basically if the task is compiled against a particular assembly identity of Microsoft.Build.Framework it will only run in a version of MSBuild that also targets that same assembly identity (name and public key, version can be changed via binding redirects). This is something we hope to address in the future, ideally being able to swap out OSS and shipping versions for build and in Visual Studio.
