### ISSUE TITLE
Question: Are the 2015 MSBuild tools backwards compatible with previous versions?

### ISSUE THREAD

**Issue by JoshVarty** [Microsoft/msbuild#109]
For example, if I were to change the binding redirects in Visual Studio 2013's `devenv.exe.config` to use version 14.0.0 do you know what kinds of problems this might cause?

 I've tested out some basic WPF, Console, ASP .Net projects and haven't had any issues yet, but I was just wondering if there was anyone here who might know better.

FWIW I'd be modifying them to match VS 2015's redirects:

```
<dependentAssembly>
    <assemblyIdentity name="Microsoft.Build.Framework" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
    <bindingRedirect oldVersion="2.0.0.0-12.0.0.0" newVersion="14.0.0.0"/>
</dependentAssembly>
<dependentAssembly>
    <assemblyIdentity name="Microsoft.Build" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
    <bindingRedirect oldVersion="2.0.0.0-12.0.0.0" newVersion="14.0.0.0"/>
</dependentAssembly>
<dependentAssembly>
    <assemblyIdentity name="Microsoft.Build.Engine" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
    <bindingRedirect oldVersion="2.0.0.0-12.0.0.0" newVersion="14.0.0.0"/>
</dependentAssembly>
```

**Comment by AndyGerlicher** [comment]
This isn't something that we've tested, we would expect problems to occur.
