### ISSUE TITLE
Revisit satellite assemblies in NuGet packages

### ISSUE THREAD

**Issue by jeffkl** [Microsoft/msbuild#1092]
Need to port the changes made in #1009 to the new NuGet packages under build/NuGetPackages

Determine what the correct solution is:

1. Include all satellite assemblies in one package
2. Create a new satellite assembly package for each language

I prefer option 2 depending on what I find in my research.

**Comment by Sarabeth-Jaffe-Microsoft** [comment]
Closing this until it's needed.
