### ISSUE TITLE
MSbuild doesn't automatically link the path automatically to PATH pariables

### ISSUE THREAD

**Issue by sudheesh001** [Microsoft/msbuild#110]
After building the project for command line, a few issues I was facing was the conflict between the Powershell to figure out what `msbuild` was, Running `msbuild` says `Command 'msbuild.exe' cannot be found.` whereas `msbuild` is actually present, At the same time I have to run `msbuild.exe` for `msbuild` to be executed to execute the pre installed `MsBuild` from the installed `Framework/vXXXXXXX`. Executing `msbuild` from absolute path works fine.

Does building the solution automatically remove `msbuild` from the path ?

**Comment by AndyGerlicher** [comment]
I'm not completely sure I understand what you're asking.

MSBuild isn't in the path at all by default. The "Developer Command Prompt for VS2015" is what I would recommend (or the equivalent for VS2013) and that will have MSBuild in the path. But once you build, you will have to use the full path name to the built exe to use that, it is not added to your path.

**Comment by sudheesh001** [comment]
@AndyGerlicher I had added MSBuild to the path for the command prompt to run with elevated priviliges but once I build, it somehow seemed to unlink itself, using the full path exe works anyway. Sorry if this is not a bug, you could feel free to close it in that case :+1:

**Comment by Craig-Campbell-MS** [comment]
@sudheesh001 I don't completely follow but I don't see how MSBuild would alter the PATH environment variable. I'm closing the issue but please re-open the Issue if you think this is a bug. An example would help us troubleshoot this further.
