### ISSUE TITLE
Recursive scan of project references

### ISSUE THREAD

**Issue by kovalikp** [Microsoft/msbuild#112]
It would be great to have a way, how to get full closure of all project references (recursively) from a project. We need this to get information about NuGet packages those referenced projects use. At first we tried to use `BuiltProjectOutputGroupDependencies` metadata, but unfortunately metadata contains only name of last project in dependency chain.

Please, could you add a target, that would return a full list of referenced projects (recursively)? Or add a name of the project that produced a file to `*OutputGroup` and `*OutputGroupDependencies` metadata, but ensure that it does not get overwritten by subsequent projects.

Thanks.

**Comment by AArnott** [comment]
You can see [the target that NuProj has to add](https://github.com/nuproj/nuproj/blob/master/src/NuProj.Targets/Microsoft.Common.NuProj.targets) to fill in this gap.

**Comment by AArnott** [comment]
Could we get the resolution for this (and possibly a justification) added to this issue when it's closed?
