### ISSUE TITLE
Allow /nodeReuse command-line flag even when node reuse isn't supported

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#1135]
Node reuse is only supported on Desktop. Currently, we'll complain if you try to (redundantly) disable it with an error like

```
MSBUILD : error MSB1001: Unknown switch. Switch: /nr:false
```

But that requires a lot of hoop-jumping to make sure scripts disable it only in exactly the right places. MSBuild could just accept and ignore the switch to make script authoring easier (for example in dotnet/SDK#196).

**Comment by GeraldBauerImplan** [comment]
Any idea of when this will be enabled? We are experiencing error MSB3491 and from reading this switch should stop this error from occurring. (The error is accessing a file but cannot because it is being used by another process.)

**Comment by rainersigwald** [comment]
@GeraldBauerImplan This shouldn't have any effect on the behavior of MSBuild--the change desired in this issue is to allow (and ignore) the parameter in .NET Core MSBuild (`dotnet build` and friends).

If you are using .NET Core MSBuild, node reuse is disabled anyway, so MSBuild processes shouldn't be locking any files after the build is done (all of the MSBuild processes should have exited).

If you're using full framework `msbuild.exe`, `/nodeReuse:false` should work fine.

**Comment by GeraldBauerImplan** [comment]
Alright, thanks for the quick response. Back to the drawing board.
