### ISSUE TITLE
MSBuild should provide a helpful message if a project has not been restored

### ISSUE THREAD

**Issue by emgarten** [microsoft/msbuild#1139]
#### Problem

An unrestored project is difficult to work with and the errors caused by missing properties are cryptic.
#### Contributing factors
- Projects now reference the SDK through a NuGet package
- NuGet restore outputs now go into obj, when this folder is removed the reference to the SDK is removed.
#### Proposal

MSBuild should detect when a project has not been restored and warn or fail fast with a helpful message explaining that the project needs to be restored.
#### Problem example
1. `dotnet new -t msbuild`
2. `dotnet restore3` sdk is now referenced
3. `git clean -xdf` restore outputs are gone
4. Attempt to run an msbuild target on the project that requires the SDK properties

**Comment by rainersigwald** [comment]
Do you have any ideas about what this would look like? The MSBuild engine doesn't know anything about NuGet, so the only things we'll see are missing imports (and for NuGet-restored targets those are conditioned on existence so no error) and missing targets. How can we distinguish this situation from bad authoring or a corrupted MSBuild?

One idea: we could augment the errors for missing imports and missing targets to say something like `Or you may wish to restore this project if you use a package manager like NuGet.`.

**Comment by emgarten** [comment]
My thought here was that MSBuild would need to know some basic things about NuGet in order to improve this.

A generic error about restore seems like it would be confusing in the opposite way, users would keep restoring and thinking it didn't work when that wasn't the problem.

Would it be possible to allow NuGet to set a ``<IsRestored>true</IsRestored>`` property in the targets/props it creates and then somewhere in the project or common targets it could check for this? It would need to be before anything else failed due to missing imports that could have come from a package.

I would expect this only for NETCore projects, but the part triggering this can't come from the SDK or a package of course.

**Comment by rainersigwald** [comment]
As of today you get this error, which seems good enough:

```
error NETSDK1004: Assets file 'S:\repro\microsoft\msbuild\issues\1139\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
```
