### ISSUE TITLE
Question on building in Windows Containers

### ISSUE THREAD

**Issue by alexellis** [microsoft/msbuild#1140]
Hi,

Is there a Windows Feature or redist package for msbuild and nuget such that I could install both of these into a Windows Docker Container for building a project under CI?

In the past I've always had to install Visual Studio - but I'm sure there has to be a better way for this.

Thanks,

Alex

**Comment by alexellis** [comment]
Potential Dockerfile here:

https://github.com/alexellis/aspnet-voteservice/blob/master/src/Dockerfile.build

**Comment by livarcocc** [comment]
You need to install the build tools sku of visual studio if you just want msbuild (and companions).

If you are building .net core or new style csprojs, you can instead install the .NET Core SDK and build with that.

**Comment by rainersigwald** [comment]
Also see https://github.com/microsoft/dotnet-framework-docker.
