### ISSUE TITLE
Reading and parsing Visual Studio Solution file and project files

### ISSUE THREAD

**Issue by Dirkster99** [Microsoft/msbuild#115]
I am looking for a way to read and parse Visual Studio Solution file and project files in C#.

Is this possible in with MSBUILD project. Which part of the API is relevant for this? Is there a sample to get me started with this? I am primarily interested in finding all files that are referenced via solution/project files.

**Comment by aolszowka** [comment]
In the past I've modified Project files (csproj) using the Project Class (https://msdn.microsoft.com/en-us/library/microsoft.build.buildengine.project%28v=vs.110%29.aspx) although the latest on MSDN seems to mark this API as obsolete.

The API wasn't well documented when I looked at it in the past but is pretty straight forward. The example you're looking for can be extracted from this example https://msdn.microsoft.com/en-us/library/microsoft.build.buildengine.project.propertygroups%28v=vs.110%29.aspx
