### ISSUE TITLE
MSBuild does not transform web.config files when the build configuration contains "Release."

### ISSUE THREAD

**Issue by jnsn** [microsoft/msbuild#1151]
I recently stumbled upon an issue when transforming web.config files when running MSBuild from the command line. Depending on the name of the configuration, it does not always transform the files correctly.

I have attached two small project to demonstrate the issue. Both are made with VS2015 Update 3, and I'm running MSBuild 14.0.25420.1.

```
C:\Projects>msbuild -version
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

14.0.25420.1
```

`TransformExample1` demonstrates a non-working example, while `TransformExample2` demonstrates a working example.

Both sample project contain a simple WebApi project, with a controller method which reads a value from the appsettings, and return it to the user. Depending on the environment (debug, staging, release) the value is changed.

In `TransformExample1` I have three build configurations:
- Debug
- Release
- Release.Staging

When I publish from within VS2015, the config transformation is applied correctly. When I build using MSBuild from the command line, the config transformation is not applied:

```
msbuild TransformExample1.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=Staging
```

It seems the culprit is the `/p:Configuration=Release` parameter I pass along. When I pass `/p:Configuration=Release.Staging` the transform is applied correctly.

In `TransformExample2` I have the same three configurations, but the `Release.` part is omitted from the `Staging` configuration:
- Debug
- Release
- Staging

When I run the same command as before, the config transformation is now correctly applied:

```
msbuild TransformExample2.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=Staging
```

My guess is that the `Release.` part in the build configuration is somehow mixing up with the `/p:Configuration=Release` parameter.

In my opinion, the correct solution would be to pass the correct, full, build configuration name as a parameter, but either way, one of the two ways does something unexpected.

[TransformExample1.zip](https://github.com/Microsoft/msbuild/files/508033/TransformExample1.zip)
[TransformExample2.zip](https://github.com/Microsoft/msbuild/files/508034/TransformExample2.zip)

**Comment by rainersigwald** [comment]
Team triage: closing because of age. If you're still seeing this problem, please let us know so we can reactivate it.
