### ISSUE TITLE
Cannot consume nightly builds using NuGet wildcard syntax

### ISSUE THREAD

**Issue by natemcmaster** [Microsoft/msbuild#1156]
Problem: the versioning schema of MSBuild nightly builds breaks support for wildcards. The nightlies -- currently versioned as `15.1.$(BuildNumber)-preview5` -- cannot be referenced using `"15.1.*"` because the packages contain the "-preview5" preversion suffix. 

> Unable to resolve 'Microsoft.Build.Runtime (>= 15.1.0)'

This means we have to manually edit dependency versions for every pre-release build.

Suggestion:
Use the versioning format used by .NET Core. `15.1.0-preview5-$(BuildNumber)`. This would allow consumers to reference prerelease versions using wildcards `"15.1.0-*"`.

**Comment by jeffkl** [comment]
Related to #557

**Comment by natemcmaster** [comment]
> NuGet.targets(97,5): error : '15.1.*-*' is not a valid version string.

Yes, I'm sure.

> how do you feel about the fact that when these prerelease packages make a breaking change

We only use floating versions on our dev branch. When we branch for release, we pin to stable versions. We are okay with breaking changes on our dev feed because we want to be made aware of breaking changes ASAP. We use a very small amount of MSBuild API, and it is rarely broken by using floating versions.

Also, when we build, NuGet resolves the floating version and stamps the resolved version into the nuget package we produce. If we ever did need to reproduce an old build, we can look at the artifacts to find which version was used.

**Comment by AArnott** [comment]
Thanks for that info. Interesting. 

FWIW, I don't find the argument compelling. If MSBuild rarely breaks you, floating versions doesn't sound that important either.

**Comment by natemcmaster** [comment]
> If MSBuild rarely breaks you, floating versions doesn't sound that important either.

To clarify, API changes in MSBuild from build to build don't break us, but if we don't have the latest packages (which floating version helps us do automatically), then we end up with forced-package downgrades, and that's what break us. 

This may be a point-in-time thing though. Once we have stable RTM builds, we can pin to those versions.
