### ISSUE TITLE
MSBuild's ToolLocationHelper should support UAP SDKs with versioned content.

### ISSUE THREAD

**Issue by mirkomuggli** [Microsoft/msbuild#1162]
UAP Sdk's starting with RS2 will support side-by-side installation. ToolLocationHelper is used throughout the UAP pipeline to find SDK content and needs to be able to point at specific versions of said content.
This will be achieved via a flag in the platform.xml.

I've already completed this change, just creating the issue to track it :)

**Comment by rainersigwald** [comment]
Pretty sure this is long done--please correct me if I'm wrong @mirkomuggli.
