### ISSUE TITLE
Have better documentation for version support please

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/msbuild#1172]
Talked with @Sarabeth-Jaffe-Microsoft offline about this a little bit. It's quite difficult finding online which MSBuild versions correlate to which VS/.NET/etc. versions.

**Comment by rainersigwald** [comment]
Team triage: we're happy to take suggestions on https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild but we don't plan to dedicate time to this at the moment.
