### ISSUE TITLE
dotnet restore3 should not display "Build started" and "Build succeeded" in the restore log

### ISSUE THREAD

**Issue by balachir** [Microsoft/msbuild#1179]
**INSTALL STEPS**
WPT.25810.00 (includes CLI version 1.0.0-preview3-003748)
Add private MyGet feeds to Package Manager Settings

**REPRO STEPS**
1. New folder, type "dotnet new -t msbuild"
2. Type "dotnet restore3"

**ACTUAL**
Restore shows "Build started" and "Build succeeded" in the log. This might confuse end-users regarding why calling a 'restore' seems to invoke a 'build'. I initially thought it was the project getting built, then I realized that it's probably the standard output from MSBuild.

[From Rob - Nuget team] They should consider changing the normal output of msbuild … perhaps they could use the target name that is executed, instead of always saying "Build".  Pack and Publish and Test will have the same problems.

![image](https://cloud.githubusercontent.com/assets/8246794/19256187/59e87ba2-8f19-11e6-9110-7a7144ee14eb.png)

**Comment by AndyGerlicher** [comment]
This isn't something we would consider changing in MSBuild. It is a build engine after all, so the messages are appropriate.

If you want to match the output in VS you can add `/nologo /verbosity:minimal` and those messages will not appear. I think that is probably the best route. Only high importance messages will show in the console and the Build, Pack, etc. can write their own `Pack succeeded` message when appropriate (high importance).

The other option is to write a customer logger for CLI and always use that for console output. This is fairly easy to do and output could be customized any way it's needed.

**Comment by balachir** [comment]
CLI needs to either set verbosity to minimal or add a custom logger to change the output. This issue is now tracked by https://github.com/dotnet/cli/issues/4433
