### ISSUE TITLE
Produce VS ExternalAPIs package in xplat

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#1186]
Visual studio compiles against an "external APIs" package we provide, rather than our standard NuGet packages. We must continue to produce this in xplat.

**Comment by tmeschter** [comment]
More details:

The .nuspec file for the package is at setup\DevDivPackages\VS.ExternalAPIs.MSBuild.nuspec in the master branch.

The production of the .nupkg from the .nuspec isn’t currently integrated into our build process. Instead, there are extra steps in our official build to create the package and publish it to the proper package feeds. It would be better if the production of the package was fully integrated into the build, and then the package step could be dropped from the official build.
