### ISSUE TITLE
xplat package needs build number in version

### ISSUE THREAD

**Issue by JeremyKuhne** [Microsoft/msbuild#119]
We can't take a new drop without a new version. @ValMenn

**Comment by AndyGerlicher** [comment]
We merged this change. We're not clear if you're asking something other than that? Let us know.

**Comment by JeremyKuhne** [comment]
Basically we need a new package with the fix, but the version has to be different.

When we build a NuGet package it doesn't have any revision number. Rebuilding the package will give us the exact same id as a result.

**Comment by ValMenn** [comment]
Doesn't manually changing version in nuspec file work?

**Comment by JeremyKuhne** [comment]
You can, of course. Was looking for something that would facilitate getting drops from an automated build.

If everything is manual, that's fine. As long as we have a documented process to request new package drops. Ideally published in a known place (nuget.org?).
