### ISSUE TITLE
Telemetry in MSBuild

### ISSUE THREAD

**Issue by jeffkl** [Microsoft/msbuild#1191]
# Overview
Given the changes in .NET Core tooling that are happening with the move to MSBuild, there needs to be a plan on how to collect telemetry when the move is complete, as the CLI tools will not be the primary (and only) way to build .NET Core applications on all supported platforms.  

Therefore, MSBuild needs to develop a telemetry pipeline (keeping in mind existing CLI & Visual Studio telemetry pipelines) to gather necessary data to improve our product. 

# Design
We need to abstract away the telemetry pipeline in MSBuild so that build events can be logged to wherever we need at runtime. Therefore, our proposal is for consumers to receive telemetry as a build event so that MSBuild knows nothing about the actual implementation.  

Anyone can produce telemetry within MSBuild via our telemetry API.  We will have a method in the `LoggingService`, a method in the `TaskLoggingHelper` and a task for use within a target.  MSBuild will also add telemetry to interesting code paths.

MSBuild will log events to the pipeline and the pipeline will need to add additional properties such as session or user IDs.

# Proposal
For the first iteration, we'll plumb the telemetry events.  Consumers will need to implement a `Logger` class to receive the events so they can be uploaded.

The next iteration would be to sync up with Visual Studio about their telemetry pipeline, develop a logger for MSBuild, and then when using MSBuild under Visual Studio the telemetry will go to their pipeline.

## Using it as a task using properties
``` XML
<Project>

  <UsingTask
    TaskName="Telemetry"
    AssemblyFile="Microsoft.Build.Tasks.Core.dll"
     />
  
  <Target Name="MyTarget">
   
    <Telemetry EventName="MyEvent" EventData="a=semicolon;delimited=list;of=properties" />

  </Target>
  
  
</Project>
```

**Comment by jeffkl** [comment]
@Microsoft/msbuild-maintainers please review and comment

**Comment by rainersigwald** [comment]
Who are the intended producers and receivers of this telemetry? It sounds like this is focused on SDK authors, but I (selfishly) would like internal telemetry as well, for things like "average eval time per project".

We talked about session- and project-wrapping information; is that expressed here in any way?

I'd also like to see at least one example showing this information flowing through to an existing telemetry system to prove out the concept further.

**Comment by rainersigwald** [comment]
@blackdwarf will want to keep an eye on this

**Comment by jeffkl** [comment]
@rainersigwald 

> Who are the intended producers and receivers of this telemetry? It sounds like this is focused on SDK authors, but I (selfishly) would like internal telemetry as well, for things like "average eval time per project".

Anyone will be able to call a public static method that we'll create to trace telemetry.  That includes us, as well as any target or task library.  The "receivers" will be more limited and in this first iteration it the data will only be uploaded when running under `dotnet.exe` to the DotNet CLI back-end.  I've updated the design.

> We talked about session- and project-wrapping information; is that expressed here in any way?

Thanks for pointing that out, I've updated the design but we'll need to brainstorm with the dotnet CLI folks on how that data should be passed to us.  @blackdwarf thoughts?

> I'd also like to see at least one example showing this information flowing through to an existing telemetry system to prove out the concept further.

Do you mean like a code sample or a live demo?

**Comment by cdmihai** [comment]
The type with the static method would be in `Microsoft.Build.Framework`, so all of our code can reference it. It will probably make use of `BuildEnvironmentHelper` to find the telemetry adapters (if the telemetry dlls are dropped near the msbuild dlls).

**Comment by cdmihai** [comment]
Who would be responsible for adding the session ID to the events? The telemetry plugins, or MSBuild's end point?

**Comment by cdmihai** [comment]
What happens if the user does not want telemetry? How do the upstream event collects signal that to msbuild? Maybe the `ITelemetryPipeline` could also have an `IsOn` method.

**Comment by cdmihai** [comment]
Beyond the session ID (which identifies a build instance?), should there also be a user / machine ID, so we can see how often people build and such?

**Comment by jeffkl** [comment]
> Who would be responsible for adding the session ID to the events? The telemetry plugin adapters, or MSBuild's end point?

Now that I think about it, MSBuild won't really need to add the properties to the events.  It will just send the events upstream and the pipeline can add the properties!

> What happens if the user does not want telemetry?

Telemetry will be sent to the pipeline and the pipeline will determine if the telemetry should actually be uploaded.

**Comment by Sarabeth-Jaffe-Microsoft** [comment]
How extensible is this design for future telemetry work?

Estimates on performance hits with this change?

**Comment by cdmihai** [comment]
Some requirements / specs that might drive the extensibility design:
- we need to be able to emit telemetry events from anywhere in the code (evaluation time + build time)
- we may need to disambiguate events between projects (e.g., building a csproj with dependencies to other csprojes)
- telemetry events from a multi proc build need to be the same as the telemetry events of the same build but without multiproc
- some upstream callers might want telemetry turned off
- some tools might want to "taint" all the telemetry events coming from a certain build instance / solution / project with a set of event metadata (like Azure publishing)

**Comment by jeffkl** [comment]
> How extensible is this design for future telemetry work?

The design is pretty basic so I'm hoping it will cover most needs.  Do you have any specific examples of future telemetry needs that might not work with the design?

> Estimates on performance hits with this change?

Good question.  I know that the CLI uses async methods for telemetry so it shouldn't slow anything down.  I think it's going to depend on the shear volume of events and the pipeline itself.

**Comment by jeffkl** [comment]
Check out the PR for an early review...

**Comment by jeffkl** [comment]
To receive telemetry events, loggers can subscribe to the `IEventSource.TelemetryLogged` event.

**Comment by JohnTortugo** [comment]
Is there any documentation for this?
