### ISSUE TITLE
MSBuild should warn instead of silently ignoring global property overwrites

### ISSUE THREAD

**Issue by cdmihai** [Microsoft/msbuild#1196]
MSBuild silently ignores when global properties overwrite local ones: https://github.com/Microsoft/msbuild/blob/286b4d3ef59e9ab21992bba8815b50d025981eb8/src/XMakeBuildEngine/Evaluation/Evaluator.cs#L1540-L1546

This can be very confusing and lead to a lot of wasted time trying to figure out what happens and why property elements get seemingly ignored.
For a better developer experience, to help debugging, MSBuild could maybe issue a warning?

There is also an escape hatch which the warning could reference: the `Project` element supports a `TreatAsLocalProperty` attribute that contains property names that can be overridden if they're global: https://msdn.microsoft.com/en-us/library/bcxfsh87.aspx

**Comment by rainersigwald** [comment]
I think a warning might be a bit strong, because this is used deliberately. But I'm 💯% behind an info message!

**Comment by livarcocc** [comment]
I will take a stab on this issue.
