### ISSUE TITLE
[question] vcxproj indentation

### ISSUE THREAD

**Issue by frederich** [Microsoft/msbuild#1213]
Hello,

All vcxproj files written by MS Visual Studio are UTF-8 encoded and with two space indentation. Is it possible to change that? Visual Studio reformats all files on every save. For instance, we've some handwritten vcxproj files with one tab indentation and want to keep the tabs.

**Comment by rainersigwald** [comment]
With existing released versions: no, sorry. MSBuild unconditionally reformats.

In the future, we've exposed a way for a caller to ask us to not reformat the file: #707. I'm not sure whether the vcxproj folks are planning to adopt that for VS "15". @Sarabeth-Jaffe-Microsoft have we reached out to them about this?

**Comment by frederich** [comment]
Thanks @rainersigwald it sounds good. I'll look forward to VS "15".

**Comment by rainersigwald** [comment]
Closing as the MSBuild mechanism for this is complete--though I believe the C++ project system hasn't adopted it (yet?).
