### ISSUE TITLE
Search for ToolTask executable on path finds directories

### ISSUE THREAD

**Issue by nguerrera** [Microsoft/msbuild#1215]
The CLI repo has a tool task that [returns "git" from GenerateFullPathToTool](https://github.com/dotnet/cli/blob/b7ac730a7f0cf6013ed51bc45a299dec7efb8cfb/build_projects/dotnet-cli-build/GetCommitHash.cs#L27-L30)

On my machine, this attempts to execute C:\Program Files (x86)\Microsoft Visual Studio\VS15Preview\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\git, which is a directory. 

There's an actual "git.exe" on my path, but it appears to lose no matter how my path is ordered. I presume because the directory matches the filename exactly whereas the executable adds an extension.

**Comment by rainersigwald** [comment]
looks like a bug in [ToolTask](https://github.com/Microsoft/msbuild/blob/6cd2c4b3e94ef2fae38d6270a54d2948fb1d1ac2/src/Utilities/ToolTask.cs#L625):

```c#
// We have no toolpath, but we have been given an override
// for the tool exe, fix up the path, assuming that the tool is in the same location
if (pathToTool != null && !String.IsNullOrEmpty(_toolExe))
{
    string directory = Path.GetDirectoryName(pathToTool);
    pathToTool = Path.Combine(directory, ToolExe);
}
```

Based on comment, first check should be inverted.

**Comment by jeffkl** [comment]
I figured out the problem.  On Windows, we're calling [SearchPath](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365527(v=vs.85).aspx) which returns a directory if one is found.  I'm going to unify our [FindOnPath](https://github.com/Microsoft/msbuild/blob/cb8c727a898e4439a3cd18f329504e436b0b7c00/src/OrcasEngine/Shared/NativeMethodsShared.cs#L55) method to do remove the Windows specific stuff in favor of the cross-platform implementation.
