### ISSUE TITLE
Support Directory project path argument

### ISSUE THREAD

**Issue by piotrpMSFT** [Microsoft/msbuild#1225]
MSBuild today supports finding proj files by scanning CWD or through an unnamed argument which is the `path/to/a/*.proj`. It should also support `path/to/a/projectdirectory/`.

**Comment by rainersigwald** [comment]
We'd just need to change [this check](https://github.com/Microsoft/msbuild/blob/1a55490345b6882f8610a07f68671554b16d64b3/src/XMakeCommandLine/XMake.cs#L2053) to be if-no-project-file-OR-if-given-a-directory.

**Comment by jeffkl** [comment]
Also, we need to be careful on cross platform that `Directory.Exists()` works as expected if the path contains trailing slashes or something.
