### ISSUE TITLE
preserveFormatting is not being honored for DeepCloned projects.

### ISSUE THREAD

**Issue by livarcocc** [microsoft/msbuild#1228]
Run the application below passing to it the path to MSBuild.dll and a path to a csproj without the xml node and with an empty whitespace.

Because of the DeepClone below, when the project gets saved, a XML node is being added and the whitespace at the end of the csproj is being removed.

If we remove the call to DeepClone, this succeeds.

This is having an impact on Migrated projects though the CLI migrate command.

Program.cs

```
using System;
using System.IO;
using Microsoft.Build.Construction;
using Microsoft.Build.Evaluation;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Environment.SetEnvironmentVariable("MSBUILD_EXE_PATH", args[0]);

            var templateProjPath = args[1];

            var project = ProjectRootElement.Open(
                templateProjPath,
                ProjectCollection.GlobalProjectCollection,
                preserveFormatting: true).DeepClone();

            var outputProject = Path.Combine(AppContext.BaseDirectory, "output.csproj");

            project.Save(outputProject);
        }
    }
}
```

Project.json:

```
  {
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.Build": "15.1.319-preview5",
    "Microsoft.Build.Runtime": "15.1.319-preview5"
  },
  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.1"
        }
      },
      "imports": "dnxcore50"
    }
  }
}
```

**Comment by livarcocc** [comment]
cc @rainersigwald

**Comment by jeffkl** [comment]
This might be trickier than I thought.  In the first call `.Open()`, we're loading a file from disk and preserving the formatting.  In `DeepClone()`, we're recreating each element and attribute and copying it's value all in memory using typed objects.  The original XML is 

Think in order to clone a root element, we'll need to create a new `ProjectRootElement` instance by feeding the raw XML to the constructor wrapped by an `XmlReader`.  Does that sound correct @rainersigwald?

**Comment by rainersigwald** [comment]
Uh, that's kind of awful. I'm not sure you can rely on the raw XML being correct--what if someone loads a project, manipulates it without saving, DeepClones it, and then tries to save--the saved copy should have the changes from before the clone.

**Comment by jeffkl** [comment]
We've decided to hold off on fixing this for now and @livarcocc is going to investigate a workaround in `dotnet migrate`.  We will need to fix `DeepClone()` at some point though.

**Comment by jeffkl** [comment]
@livarcocc from my testing, you don't need to call `DeepClone()`.  Opening the project gives you an in-memory instance of it which you can modify and save.  To start over again, you can open the project again, which worked for me.

``` C#
static void Main(string[] args)
{
    Environment.SetEnvironmentVariable("MSBUILD_EXE_PATH", @"D:\MSBuild\bin\Bootstrap\15.0\Bin\MSBuild.exe");

    const string projectPath = @"D:\Temp\MSBuildTestApp\PreserveFormatting\test.proj";

    ProjectRootElement project1 = GetTemplate(projectPath);

    project1.PropertyGroups.Last().AddProperty("Something", "else");

    project1.Save("test-saved1.proj");

    Console.WriteLine($"Saved file to {project1.FullPath}");

    ProjectRootElement project2 = GetTemplate(projectPath);

    project2.PropertyGroups.Last().AddProperty("AnotherProperty", "asdf");

    project2.Save("test-saved2.proj");

    Console.WriteLine($"Saved file to {project2.FullPath}");
}

static ProjectRootElement GetTemplate(string path, bool preserveFormatting = true)
{
    return ProjectRootElement.Open(path, ProjectCollection.GlobalProjectCollection, preserveFormatting: preserveFormatting);
}
```

When I diff the projects, everything looks correct including the whitespace.

**Comment by livarcocc** [comment]
Yes. I already tried these changes. However, I hit this: https://github.com/Microsoft/msbuild/issues/1242

**Comment by livarcocc** [comment]
Closing this as not high pri.
