### ISSUE TITLE
Add ability to build projects that are in a zip / rar/ tar.gz file formats.

### ISSUE THREAD

**Issue by AraHaan** [Microsoft/msbuild#1235]
It would be nice to have MSBuild to be able to handle building projects that are in those formats and to loop for solution files inside of them before resorting to the project filese themselve weather a C++ project file or not. This would help make things a whole lot easier to clean after building and a lot easier to package changes that people can then download and build from that archive itself without needing to extract first.

**Comment by rainersigwald** [comment]
This is an interesting idea but I don't think it'll bubble up to the top of the MSBuild priority list any time soon, so I'm going to close this. If anyone would like to make a case for prioritizing it, please do.
