### ISSUE TITLE
GenerateResources does not support linked resources on .NET Core

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/msbuild#1247]
See discussion in https://github.com/Microsoft/msbuild/issues/1197#issuecomment-254564243 and dotnet/corefx#8200.

We don't have `ResXResourceReader` on .NET Core, so we can't crack a `.resx` file to find its linked resources. But that's ok because a .NET Core application couldn't consume them even if they were embedded.

At the moment, we will ignore linked resources when running in .NET Core.

**Comment by rainersigwald** [comment]
#4090 will improve this greatly for linked text files, but I'm leaving this open until it behaves correctly for incremental builds -- #1197 is long closed by #1251, but that doesn't consider linked resources.

**Comment by kirakosyan** [comment]
Having strange behavior, when running locally with with .net core 2.2 on local machine, it works fine. while hosted in azure I get 
RegistrationEmail.html;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8

**Comment by rainersigwald** [comment]
@kirakosyan You're hitting the difference between .NET Core MSBuild (`dotnet build`, evidently used by your Azure Pipelines CI) and full framework MSBuild (`msbuild.exe` and Visual Studio driven builds). Can you change your Azure DevOps build definition to use the "MSBuild" or "Visual Studio Build" tasks instead of "dotnet build"?
