### ISSUE TITLE
Copy task should gracefully handle long file path issues

### ISSUE THREAD

**Issue by TheRealPiotrP** [microsoft/msbuild#1267]
First, thanks @eerhardt for helping me track down the cause here.

I just ran into a problem whose symptom was this error message:

'error MSB3030: Could not copy the file "{a string just shy of the long file path limit}" because it was not found.'

I checked the file system and verified the file exists. The FullName of the file was quite close to the long file path limit, which was a clue, but did not cross that limit itself. However, the directory that contained this file also contained another file which had a name which put that file's path length over the long file path limit. The scenario is a bit convoluted, but also very difficult to root-cause.

It would be great if the Copy task was aware of long file paths and provided some additional guidance for developers on Windows who are running into similar issues.

It is not clear if the OS would provide sufficient data to determine that this particular long file path issue occurred since it was caused by a different file that happened to be in the same directory. At a minimum, I hope this issue helps others that run into mysterious MSB3030's :)

Here's an example of the problematic scenario:

```
cd SomePathJustShyOfTheOSLongFilePathLimit
dir
  FileWhoseTotalPathIsLessThanLimit.txt
  FileWhoseTotalPathIsGreaterThanLimit.txt
```

```
  ...
    <Copy Source="$(PathToFileWhoseTotalPathIsLessThanLimit.txt)" ... />
```

**Comment by rainersigwald** [comment]
Yikes! Thanks for chasing this down. My current hope is that this is a rare enough situation/problem that we can ignore it until we get real long-path support (#53), at which point it should go away entirely.

But if someone has free time I'd be interested to know why MSBuild is even aware of the other MAX_PATH-breaking file in the first place. (Assuming it wasn't in a wildcard: if we encounter any MAX_PATH errors while expanding a wildcard we don't expand any files thanks to #406).

**Comment by yolofy** [comment]
+1

**Comment by rainersigwald** [comment]
@yolofy Can you elaborate, please? What behavior are you seeing? Do you have long paths enabled at the OS level?

**Comment by livarcocc** [comment]
Closing this issue since we have added support to long paths in MSbuild and didn't get an answer to @rainersigwald's follow up question.

**Comment by hknielsen** [comment]
@livarcocc - Im hitting this as well, when(Version) was this fixed and by what PR?
