### ISSUE TITLE
Global optimizations for whitespace preservation

### ISSUE THREAD

**Issue by cdmihai** [microsoft/msbuild#1270]
Consider doing more intelligent whitespace analysis to infer the "average" formatting from the whole project when inserting a new element. The current code only looks locally at its nearest siblings.

For example:

``` xml
<ItemGroup>

  <Compile Include="A.cs" />

  <Compile Include="C.cs" />

  <Compile Include="Class1.cs" />
  <Compile Include="Class2.cs" />
  <Compile Include="Class3.cs" />
</ItemGroup>
```

Adding a new element here could look at the entire parent, and see that the most common formatting is a newline and two spaces (3 hits) and not two newlines and two space (2 hits).

``` xml
<ItemGroup>

  <Compile Include="A.cs" />

  <Compile Include="B.cs" />

  <Compile Include="C.cs" />

  <Compile Include="Class1.cs" />
  <Compile Include="Class2.cs" />
  <Compile Include="Class3.cs" />
</ItemGroup>
```

Here, adding a new element finds two equal clusters, and then it can either apply a heuristic (use last cluster, use first cluster, use random cluster), or compute whitespace clusters from all the elements of the same type from the entire project file.

``` xml
<ItemGroup>

  <Compile Include="Class1.cs" />

  <Compile Include="Class2.cs" />

  <Compile Include="Class3.cs" />
</ItemGroup>

<ItemGroup/>
```

Adding the first element in the second, empty itemgroup could compute whitespace clusters of siblings from other itemgroups. In the above case, it would find one cluster with "two newlines and two spaces"  and use that.

**Comment by dsplaisted** [comment]
How about just applying the following simpler logic: Try to match indentation, but don't match extra blank lines around other elements.

**Comment by cdmihai** [comment]
Are you referring to indentation as the entire leading whitespace of the referenceSibling, or as it's used in #1264 (the substring after the last newline in the referenceSibling's leading whitespace)?

**Comment by dsplaisted** [comment]
I mean a substring.  Depending on whether you're copying it from the previous or next sibling, it might be a substring coming from the beginning or the end of the whitespace you find.

**Comment by livarcocc** [comment]
Team triage: this is not something that we are likely to get to in the medium to long term. Closing this.
