### ISSUE TITLE
Solution targets need to be dynamic or at least extensible

### ISSUE THREAD

**Issue by nguerrera** [Microsoft/msbuild#1275]
There's currently a fixed set of targets emitted to the sln metaproj:

https://github.com/Microsoft/msbuild/blob/2db4d4b6821ff65987b2843d29cc5f02c4db59f5/src/XMakeBuildEngine/Construction/Solution/SolutionProjectGenerator.cs#L765-L769 (edited)

We will be needing other targets such as "pack" and "test" to work on solutions. 

@jeffkl suggested "It might be as simple as taking the target you specified at the command-line and injecting it into the generated project"

**Comment by jeffkl** [comment]
Should I formalize my prototype and get this ready for RTM?

https://github.com/jeffkl/msbuild/commit/b687fa6e528504171bf0959cfef08b3befe00016
