### ISSUE TITLE
.NET Core assemblies don't have precise version stamp

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#1283]
see https://github.com/Microsoft/msbuild/issues/1260#issuecomment-256971367

The git commit should be in the assembly info of assemblies packed into nuget packages.

**Comment by jeffkl** [comment]
This is fixed now, we weren't passing MSBuildRuntimeType in the xplat build def which is the build def that now publishes the packages to our feed.

So packages versioned `15.1.0-preview-000371-00` and up will have the correct values.
