### ISSUE TITLE
Retrieve value of dynamic items and properties via MSBuild APIs

### ISSUE THREAD

**Issue by jmecosta** [Microsoft/msbuild#1285]
Hi

i have this target:

```
    <Target Name="build">    
        <ItemGroup>
            <Part1 Include="$(SLN1);$(SLN2)">
              <Properties>Platform=Any CPU</Properties>
            </Part1>
            <Part1 Include="$(SLN3);$(SLN4);">
           </Part1>
        </ItemGroup>

        <MSBuild Projects="@(Part1)"
                 StopOnFirstFailure="true"
                 BuildInParallel="true" />
    </Target>
```

I am trying to get the evaluated value Part1 in a application: like this

```
let value = (msbuildproject.GetPropertyValue("Part1"))
```

This returns null, if i try let value = (msbuildproject.GetPropertyValue("SLN1")) it works

If i understand the documentation this is the effect of using dynamic property, that is only evaluated when the MSBuild task is run.

But is there a alternative to evaluate those before running the that target?

thanks in advance
jorge costa

**Comment by cdmihai** [comment]
In your snippet, `msbuildproject.GetPropertyValue("Part1")` you are passing an item name (`Part1`) to an API that expects the name of a property (`GetPropertyValue`).

You are correct, evaluation time state (obtained via `Microsoft.Build.Evaluation.Project`) does not execute targets, and therefore state operations from within targets (dynamic properties and dynamic items) are not seen.

If possible, you can try moving the dynamic items / properties outside of targets and then evaluation time state should be good.

If, however, you cannot move the items / properties outside of targets, then you can use something similar to the following snippet to get engine state after a full build:

```C#
            var projectInstance =
                new ProjectInstance(@"D:\tests\ConsoleApplication1.csproj");

            var result = BuildManager.DefaultBuildManager.Build(
                new BuildParameters(),
                new BuildRequestData(projectInstance, new string[0], new HostServices(),
                    BuildRequestDataFlags.ProvideProjectStateAfterBuild));

            Console.WriteLine(result.ProjectStateAfterBuild.GetPropertyValue("DynamicProperty"));
            Console.WriteLine(
                result.ProjectStateAfterBuild.Items.First(i => i.ItemType == "DynamicItem").EvaluatedInclude);

            Console.ReadKey();
```

The downside to the previous approach is that you also get the side effects of the build (dlls etc).

**Comment by jmecosta** [comment]
@cdmihai thanks a lot for the clarification, unfortunelly the tool im using needs to support dyn properties defined inside and outside a target. and building the target is not feasible since usually each target contains multiple solutions.

the workaround im using is to parse the file and retrive that missing information where the target is defined. but i think im doing this rather inneficiently.

is there a way to get the xml string for the target in question?

**Comment by cdmihai** [comment]
You can't access the raw xml, but you can retrieve just about everything via the the MSBuild 'xml construction model': `ProjectRootElement.Targets` gives you the targets, and then you can use `ProjectTargetElement.Items` or `ProjectTargetElement.Properties` to retrieve the items and properties defined in that target.

**Comment by rainersigwald** [comment]
I would caution you, that static analysis of MSBuild programs of this type can be extremely difficult. In the original example, you can't know what the value of `Part1` will be after a build without running a build, because a target may have run that changes the values of the properties `SLN1` and `SLN2` from what they were when the project was evaluated (but no target had been executed). Ensuring that nothing would modify those values is itself pretty difficult.

**Comment by jmecosta** [comment]
@cdmihai thanks for the hint, however i dont think the Items and Properties will hold Part1 on the example above since Part1 can exist and other target definitions. At least after i do let msbuildproject = new Microsoft.Build.Evaluation.Project(path) and look at those i dont see those defiitions. Or am my overlooking?

@rainersigwald thanks for the hint, so for that case i assume you suggest both check the evaluated value of SLN1 exists and look inside the target (so that i get the correct value for my example). However inside the target there might be a custom task changing those SLN1 that i would not be able to catch by statically looking at that. Luckly in our context that does not exit, and i supose i will need to live with that limitation.

**Comment by rainersigwald** [comment]
@jmecosta Any property or item read by the dynamic property or item that you're trying to compute could potentially have been changed by a task in the target that creates the new item _or_ in any target that runs before it. Plus you'll have to evaluate things "as MSBuild would"--which for simple things like your example is easy but for more complicated things like item transforms or property functions might be difficult.

You might be able to live with these limitations but you definitely should be aware of them.

**Comment by cdmihai** [comment]
How to query the target xml from a `Microsoft.Build.Evaluation.Project`.
```c#
var project = new Project(@"...\ConsoleApplication1.csproj");

foreach (var target in project.Xml.Targets)
{
    Console.WriteLine($"target:{target.Name}");

    foreach (var propertyGroup in target.PropertyGroups)
    {
        foreach (var property in propertyGroup.Properties)
        {
            Console.WriteLine($"\t{property.Name} = {property.Value}");
        }
    }

    foreach (var itemGroup in target.ItemGroups)
    {
        foreach (var item in itemGroup.Items)
        {
            Console.WriteLine($"\titem: {item.ItemType}, include={item.Include}, exclude={item.Exclude}, remove={item.Remove}");
        }
    }
}
```

As @rainersigwald said, trying to infer things correctly from the xml will be quite hard, since you'd have to write an msbuild interpreter, whose semantics are only documented in its code ...

**Comment by jmecosta** [comment]
@cdmihai thanks project.Xml.Targets was exactly what was was trying to find, i was looking at project.Targets :)

@cdmihai @rainersigwald yes i will keep in mind this limitation, for my use case it should be ok. Since i am maitaining the msbuild files. The purpose of this is to keep track of solutions that are called within msbuild file. In principle i would imagine no one in is right mind would hide the solution output of such properties inside a custom task. 

The other thing i done in past was to modify thet msbuild file, so that the target file is executed in isolation. DependsOn is removed, and in this case, remove anything from the target that does not use those properties. Than build the target and check the results as mentioned above. 

I am not totally sure whats the best approach, in my case (solution checking), i think just checking the nodes is ok.

Anyway thanks for the help, the hints above are very usefull for anywone trying to use msbuild automation.

best regards

jorge costa
