### ISSUE TITLE
<Exec> on Unix platforms requires a fully qualified path to the script it is running

### ISSUE THREAD

**Issue by blackdwarf** [microsoft/msbuild#1290]
## Repro

* Create a new csproj file in some way (e.g. use `dotnet new` from the latest rel/1.0.0 CLI)
* Create a sample script called `script.sh` in the same directory that just echoes something
* Add a target to the csoproj and an Exec task that sets Command to that script like `Command="script.sh"`
* Run the target

## Expected result
The script is ran, something is echoed and the build passes

## Actual result
MSBuild will return an error stating that the command wrapper in a temp location (`/var/....`) returned the exit code 127 and the build will fail.

This is a pretty important scenario in general, but for people who are migrating off of project.json it will be even more painful as they may have some scripts that they will most likely wish to reuse in their build process in the same way. 

/cc @jeffkl @rainersigwald

**Comment by rainersigwald** [comment]
@radical does xbuild do anything interesting here?

**Comment by Sarabeth-Jaffe-Microsoft** [comment]
We should also change the file extension of the script that we generate from .cmd to .sh.

**Comment by blackdwarf** [comment]
@Sarabeth-Jaffe-Microsoft yes, that too would be nice. :)

**Comment by radical** [comment]
Sorry for the late response, I keep missing GitHub notifications!

This is what we are doing in xbuild:
```
pinfo.WorkingDirectory = GetWorkingDirectory () ?? Environment.CurrentDirectory;
```

https://github.com/mono/mono/blob/master/mcs/class/Microsoft.Build.Utilities/Microsoft.Build.Utilities/ToolTask.cs#L341

**Comment by rainersigwald** [comment]
Team triage: seems to be working now.
