### ISSUE TITLE
Some tests fail on Linux

### ISSUE THREAD

**Issue by jeffkl** [Microsoft/msbuild#1297]
In PR #1296 I had to disable some tests that were failing on Linux but pass on OS X:

1. ResX2ResourcesWithReferences
2. ForceSomeOutOfDate
3. NothingOutOfDateExceptReference

We need to investigate why this is happening so we can enable these tests. 

Once this is completed, we should also update netci.groovy in master so that the tests run in the CI environment.

**Comment by jeffkl** [comment]
@rainersigwald The test [ResX2ResourcesWithReferences](https://github.com/Microsoft/msbuild/blob/a66daa999c298191ef307d10b5facca842644346/src/XMakeTasks/UnitTests/GenerateResource_Tests.cs#L162) is failing because it can't find `System.dll`.  This shouldn't work on non-Windows anyway right?  Any idea why this test [passes on OS X](https://ci.dot.net/job/Microsoft_msbuild/job/master/job/_OSX_CoreCLR_prtest/561/testReport/Microsoft.Build.UnitTests.GenerateResource_Tests.InProc/RequiredTransformations/ResX2ResourcesWithReferences/)?

Should this test just be disabled for non-Windows?

**Comment by rainersigwald** [comment]
I have no idea why that test passes on OS X. It sounds reasonable to disable it on non-windows but it's probably worth looking into why it's working first.

**Comment by jeffkl** [comment]
@rainersigwald this turned out to be a casing issue of `system.dll` vs `System.dll`.  On OS X the copy succeeds but for some reason on Linux it fails.  

So I can update the test to use "System.dll" or I can disable the test for non-Windows.  Preference?

**Comment by rainersigwald** [comment]
😆 Case-insensitive file systems 😠 

I'd say go with the capital letter.
