### ISSUE TITLE
In tests, use native paths or windows paths?

### ISSUE THREAD

**Issue by radical** [Microsoft/msbuild#130]
I have been fixing some of the tests to use native paths, like `/foo/bar` on
Unix and `c:\foo\bar` on Windows, so that they can work correctly on Unix. But
I am wondering whether the tests should be using native paths or windows paths
(except in the rooted case, of course).

In case of project files which get parsed by msbuild, it makes sense to always
use always windows paths and let msbuild correctly translate them to native
ones. But in the test cases, api/tasks/etc are used directly, which might not
be converting them.

Should they be changed to always translate? But then there would be a *lot* of
points at which we would need to do that (every public API?!).  Or should the
tests use native paths when using API directly, and use windows paths when
specifying them in text/project files that get parsed?

**Comment by akoeplinger** [comment]
> Or should the tests use native paths when using API directly, and use windows paths when
 specifying them in text/project files that get parsed?

I think that'd be closest to how I'd personally use these APIs, so I'd prefer that (e.g. it's quite likely I got the native path from some other place when working with the API directly, but in the project files I'd use the windows paths so they work on all platforms).
