### ISSUE TITLE
Property function for EnsureTrailingSlash()

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#1302]
There's a condition expression `HasTrailingSlash()` that is almost always used as if-not-has-trailing-slash, add slash.

This could be easier with something like

```xml
<PathProperty>$([MSBuild]::EnsureTrailingSlash('$(PathProperty)')</PathProperty>
```

(Which has the added bonus of being easily cross-platform.

**Comment by jeffkl** [comment]
We should replace [HasTrailingSlash](https://github.com/Microsoft/msbuild/blob/2db4d4b6821ff65987b2843d29cc5f02c4db59f5/src/OrcasEngine/Conditionals/FunctionCallExpressionNode.cs#L72) at the same time
