### ISSUE TITLE
Hiding node_modules containging Gulp takes over a minute

### ISSUE THREAD

**Issue by cdmihai** [microsoft/msbuild#1305]
Creating this issue from an internal one: https://devdiv.visualstudio.com/DevDiv/MSBuild/_workitems/index?id=267170&triage=true&_a=edit

Create an empty web project
Add a package.json
Add 'gulp' in package.json and wait for load.
Show all files and include node_modules in project.
Right-click on node_modules and select Exclude from Project
 
Expected Result
Folder is quickly hidden
 
Actual Result
Spinning circle cursor, UI thread is busy for so long you consider rebooting.
At least 60 seconds.

This issue is present in both dev14 and dev15

**Comment by livarcocc** [comment]
Closing as this should be addressed by lazy evaluation as suggested by andy.
