### ISSUE TITLE
Metadata of other items not available in ItemDefinitionGroup

### ISSUE THREAD

**Issue by rainers** [Microsoft/msbuild#1316]
I tried to use a feature documented here: https://msdn.microsoft.com/en-us/library/bb651788.aspx#Using%20Conditions%20in%20an%20ItemDefinitionGroup. This is a minimal test project
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemDefinitionGroup>
    <test>
      <yes>1</yes>
    </test>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup>
    <i>
      <m>m0</m>
      <m Condition="'%(test.yes)'=='1'">m1</m>
    </i>
  </ItemDefinitionGroup>

  <ItemGroup>
    <i Include="abc"></i>
  </ItemGroup>
  
  <Target Name="Build">
    <Message Importance="high" Text="i.m = %(i.m)" />
  </Target>
</Project>
```
It always prints `i.m = m0`, but I expect `i.m = m1`.

Is this a misunderstanding, an error in the documentation or an implementation bug?

Thanks.

**Comment by rainersigwald** [comment]
Well, this is a dark corner of the evaluator!

This is an error in the documentation, thanks for reporting it!

From that page,

>📝  Note
>Only local metadata references are supported in conditions.

> References to metadata defined in an earlier ItemDefinitionGroup are local to the item, not the definition group. That is, the scope of the references are item-specific. For example:
>```XML
<ItemDefinitionGroup>  
    <test>  
        <yes>1</yes>  
    </test>  
    <i>  
        <m Condition="'%(test.yes)'=='1'">m1</m>  
    </i>  
</ItemDefinitionGroup>  
```
>In this example, item "i" references item "test" in the Condition.

is missing important information:

>In this example, item "i" references item "test" in the Condition, **so this condition will never apply. MSBuild interprets a reference to another item's metadata in an ItemDefinitionGroup as the empty string.**

To tweak your example so it does work, you can:

```XML
<Project DefaultTargets="Build" ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemDefinitionGroup>
    <i>
      <m>m0</m>
      <yes>1</yes>
      <m Condition="'%(i.yes)'=='1'">m1</m>
    </i>
  </ItemDefinitionGroup>

  <ItemGroup>
    <i Include="abc"></i>
  </ItemGroup>
  
  <Target Name="Build">
    <Message Importance="high" Text="i.m = %(i.m)" />
  </Target>
</Project>
```

We're in the midst of overhauling the location and mechanisms for our documentation. @Sarabeth-Jaffe-Microsoft, perhaps we can make this the first edit in the new world once it's ready?

**Comment by Sarabeth-Jaffe-Microsoft** [comment]
Thanks so much for pointing this out, @rainers! This page has been moved over to docs.microsoft.com. Docs is linked up to GitHub so if you come across another documentation error, don't hesitate to click the "Edit" button, make your change, and send it as a PR.

This article's new home: https://docs.microsoft.com/en-us/visualstudio/msbuild/itemdefinitiongroup-element-msbuild 

PR for added clarity: https://github.com/Microsoft/visualstudio-docs/pull/2
