### ISSUE TITLE
ResolveAssemblyReference task generating warning instead of unifying and including assembly in SuggestedRedirects ouput parameter

### ISSUE THREAD

**Issue by dsplaisted** [microsoft/msbuild#1329]
Build the following project, using Dev15 RC, or .NET CLI 1.0.0-preview3-004056.  You'll also need a `Program.cs` file with an entry point.

```xml
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net461</TargetFramework>
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Net.Http" />
    <PackageReference Include="Microsoft.NET.Sdk">
      <Version>1.0.0-alpha-20161104-2</Version>
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="System.Net.Http">
      <Version>4.1.0</Version>
    </PackageReference>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

**EXPECTED:** No Errors or warnings generated
**ACTUAL:**

> C:\Program Files\dotnet\sdk\1.0.0-preview3-004056\Microsoft.Common.CurrentVersion.targets(1909,5): warning MSB3243: No way to resolve conflict between "System.Net.Http, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Choosing "System.Net.Http, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" arbitrarily.

The Microsoft.NET.Sdk targets set `AutoGenerateBindingRedirects` to true, so this warning shouldn't be generated.

The verbose log has messages referring to `System.Net.Http.dll` where it should be referring to other assemblies.  I'm not sure if that is related to this problem or is a separate issue just with the message logging.  For example:

>  Unified primary reference "**System.Security.Cryptography.X509Certificates**, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". (TaskId:10)
      Using this version instead of original version "4.0.0.0" in "C:\Users\daplaist\.nuget\packages\system.net.http\4.1.0\ref\net46\\**System.Net.Http.dll**" because AutoUnify is 'true'. (TaskId:10)

Also note that for simplicity the project file has a `Reference` for `System.Net.Http` and a `PackageReference` to the `System.Net.Http` package.  The more common scenario where this will be hit is for ASP.NET Core applications targeting .NET Framework, which will get the `PackageReference` transitively from their dependencies.

**Comment by dsplaisted** [comment]
@nguerrera @ericstj @eerhardt FYI.  This seems like a bug in the ResolveAssemblyReference task but it might actually be elsewhere.

**Comment by nguerrera** [comment]
@piotrpMSFT @krwq

**Comment by ericstj** [comment]
This is the behavior of RAR, but we want it to change.  This is the conflict resolution feature we've been discussing.  Today RAR never resolves conflicts between primary references but we want it to do so.

**Comment by ericstj** [comment]
Here is the task I am working on for doing this downlevel (where we also need support) https://github.com/dotnet/standard/blob/master/netstandard/tools/HandlePackageFileConflicts.cs.  This could be done much better (and with better perf, since assemblies are already opened) if it were part of RAR.  @AndyGerlicher, @cdmihai, @dsplaisted we talked about this in a meeting before the holidays.

**Comment by livarcocc** [comment]
@dsplaisted is this still needed?

**Comment by dsplaisted** [comment]
This doesn't repro anymore.  I don't think we made the change in RAR, but conflict resolution handles it in this case.

Here's the repro project converted to current sdk style, FWIW:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net461</TargetFramework>
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Net.Http" />
    <PackageReference Include="System.Net.Http">
      <Version>4.1.0</Version>
    </PackageReference>
  </ItemGroup>

</Project>

```
