### ISSUE TITLE
Preprocess output mangles filenames

### ISSUE THREAD

**Issue by dsplaisted** [Microsoft/msbuild#1334]
- Put an MSBuild project in a folder with three dashes (`---`) in the filename
- Call msbuild with the `/pp:filename.xml` option

EXPECTED: Filenames listed in preprocessed file are correct
ACTUAL: Filenames have `---` replaced with `__-`

I imagine that MSBuild does this in order to avoid a `-->` character sequence from ending the XML comment.  However, it doesn't seem like it should need to replace two dashes if they aren't followed by `>`.

**Comment by rainersigwald** [comment]
> it doesn't seem like it should need to replace two dashes if they aren't followed by `>`.

Unfortunately, that's incorrect. From http://www.w3.org/TR/REC-xml/#sec-comments:

> For compatibility, the string " -- " (double-hyphen) MUST NOT occur within comments.

I'm open to ideas about how we could do better but I can't think of anything . . .

**Comment by jeffkl** [comment]
We could escape the invalid characters but then it would look like
``` xml
<!-- C:\foo\&#45;&#45;&#45;bar.props -->
```
which isn't very readable either 👎

**Comment by dsplaisted** [comment]
> For compatibility, the string " -- " (double-hyphen) MUST NOT occur within comments.

OK, that makes sense.  To check whether it was valid, I had just tried putting a double hyphen inside an XML comment in VS code, and it didn't break anything.

**Comment by rainersigwald** [comment]
Ah, I knew we'd seen this semi-recently--it broke `XmlWriter` in #491, so this escaping was added in #494.
