### ISSUE TITLE
Reduce exceptions when executing intrinsic functions

### ISSUE THREAD

**Issue by cdmihai** [Microsoft/msbuild#1341]
Whenever MSBuild is trying to interpret an expression string like `$(Property.Substring(0, 2))` it will first try to reflect invoke `Substring` with string arguments `new []{"0", "2"}`, have the invoke throw a `MethodMissingException` because there is no String.Substring(string, string) method, and then try to eventually coerce the arguments into `new []{0, 2}` and invoke `Substring` again, which would now succeed.

This is slow, and makes it hard to debug VS or MSBuild.

We should redo the logic to avoid the exception. Maybe directly reflect into the receiver's type and match the method instead of first blindly calling it with strings.

The caveat here is the nature of data. If most of the time builds end up calling intrinsic functions which only take strings, then the current "exceptional" code would actually be faster than reflecting into the receiver to find the proper argument types. We should first build an empty console project and some real, big projects to get a sense of the landscape.

**Comment by rainersigwald** [comment]
It might also be interesting to build a cache, so the first time we see `Substring` we do the slow path but the next time we see it, we try the thing that worked last time first and fall back to the slow path.

We could also potentially build our knowledge of these functions--right now we don't know much about the functions we can call, which is nice from a layering perspective but we could probably have higher performance if we had more knowledge of common calls.

**Comment by davkean** [comment]
Going to dupe this against https://github.com/Microsoft/msbuild/issues/2217 which has more context.
