### ISSUE TITLE
When Text for message/warning/error are empty it doesn't use an empty line for the message

### ISSUE THREAD

**Issue by kingerja** [Microsoft/msbuild#1350]
Expected behavior is to have an empty line shown as the message, warning or error and in the case of warning and error for it to be incremented by 1.  

Repro project.

``` xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="Build">
    <PropertyGroup>
      <ReallyImportantMessage></ReallyImportantMessage>
    </PropertyGroup>
    <Message Text="Look no message or warning or error below this line.  But the build still failed..."/>
    <Message Text="$(ReallyImportantMessage)"/>
    <Warning Text="$(ReallyImportantMessage)"/>
    <Error Text="$(ReallyImportantMessage)"/>
  </Target>
</Project>
```

**Comment by jeffkl** [comment]
It looks like the the `<Error />` and `<Warning />` tasks don't log anything if the message is empty.  I think we should log something like "the message as empty" and ensure that the XML element location is there so people know where to look for these empty messages.

This will change existing behavior but I think it's an improvement.  If people want to keep the existing behavior, they can add a condition.

**Comment by rainersigwald** [comment]
We should probably build an environment-variable escape hatch here. I agree that our current behavior is confusing and wrong, but it's also longstanding (I just tried on MSBuild 2.0.50727.8007 and it's the same there).

**Comment by jeffkl** [comment]
@rainersigwald did the build still say failed?  I think if the build fails anyway, it's safe to log an error saying "(No message specified)" right?

The warning thing is a little trickier if people are expecting to use this functionality as a conditional way of not warning.  For instance:

``` xml
<Target Name="MyTarget">
  <PropertyGroup>
    <MyMessage Condition=" false ">Something has gone horribly wrong</MyMessage>
  </PropertyGroup>

  <Warning Text="$(MyMessage)" />
</Target>
```

This would be an overt way of not warning depending on the condition.  Or if the message came as an output from a task.

But it's still just a warning...  So fix this by logging something like "(The message was empty)" and have an environment variable which people can set to get back the old behavior?

**Comment by rainersigwald** [comment]
It did not fail:

```
S:\msbuild>type empty_warning.proj
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="MyTarget">
    <Warning Text="$(MyMessage)" />
  </Target>
</Project>

S:\msbuild>C:\Windows\Microsoft.NET\Framework\v2.0.50727\MSBuild.exe empty_warning.proj
Microsoft (R) Build Engine Version 2.0.50727.8745
[Microsoft .NET Framework, Version 2.0.50727.8745]
Copyright (C) Microsoft Corporation 2005. All rights reserved.

Build started 11/21/2016 10:06:38 AM.
__________________________________________________
Project "S:\msbuild\empty_warning.proj" (default targets):


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.06
```

I'm thinking change the default as you propose but have a revert-to-previous `MSBUILDALLOWEMPTYWARNINGSANDERRORS`.

**Comment by jeffkl** [comment]
My only opposition to the environment variable is the unit test burden.  Can I add it without a unit test? :grin:
