### ISSUE TITLE
GenerateResources task does not support non-string resources on .NET core

### ISSUE THREAD

**Issue by alexperovich** [Microsoft/msbuild#1352]
related: dotnet/corefx#12565

see: https://github.com/Microsoft/msbuild/blob/xplat/src/XMakeTasks/GenerateResource.cs#L2906
The GenerateResources task incorrectly assumes that all entries in a resx file are type string. On .NET core ResourceManager supports loading all types in ResourceTypeCode other than user defined types. The GenerateResources task should properly support adding resources of all types in the ResourceTypeCode enum.

**Comment by danmosemsft** [comment]
Clarification, this bug exists when using the no-ResxResourceReader fallback path. That path can never be as elaborate as the regular path, but it could be educated to understand more types such as ints.

**Comment by ericwj** [comment]
I run into this on VSTS because Visual Studio decided to make .md files Binary File resources after I told it to add a Text File and hence generating byte[] resources. Combined with VSTS Package Management breaking command line restore/build on my machine, this was time consuming.

**Comment by nguerrera** [comment]
Duped by #2221. This one has a more descriptive title and is older. That one has more discussion.

**Comment by maxrandolph** [comment]
I've run into this issue now with embedded schema files in a test project. A lot of time wasted with confusion of builds working fine in VS vs. not in CLI.

**Comment by nguerrera** [comment]
I went ahead and changed the title on #2221 and I'll close this one as a duplicate. More people are engaged on #2221 than here.
