### ISSUE TITLE
Linked files should support mapping wildcard file inclusions to a virtual path within the project

### ISSUE THREAD

**Issue by attilah** [Microsoft/msbuild#1353]
Today linked files can be mapped to any virtual folder within a project by specifying metadata for it.

```xml
<Compile Include="..\..\..\src\OrleansRuntime\**\*.cs" />
```

Ends up like this in VS:

![image](https://cloud.githubusercontent.com/assets/230432/20370728/0c7846fe-ac15-11e6-9b02-2ca39b8d0611.png)

With the new project system it would be easy to extend the Link node metadata support to make it possible to map included nodes into either a subfolder within the project or to the root.

So this link would definition should end up like the image below:

```xml
<Compile Include="..\..\..\src\OrleansRuntime\**\*.cs">
    <Link>\</Link>
</Compile>
```

![image](https://cloud.githubusercontent.com/assets/230432/20370811/93b3de3a-ac15-11e6-9ac0-a71beccc6113.png)

Visual Studio 2017 RC was used for the screenshots, so it only affects the new tooling.

**Comment by rainersigwald** [comment]
@davkean, do you know if this should go to Roslyn Project System or CPS?

(MSBuild itself doesn't control that tree view; we just provide a list of items to the UI--so I'm trying to figure out which layer of the UI would need to change to do this.)

**Comment by davkean** [comment]
Yeah, this is a CPS request.  @jviau @lifengl

**Comment by jviau** [comment]
This is on the CPS backlog, but it won't make RTM. We did the temporary fix of showing the ".." folders, but it also disables all commands on that directory and does not auto-refresh.

**Comment by rainersigwald** [comment]
Thanks, @jviau. I'm going to close this since we can't fix it in this repo--if you have any public mechanism of tracking your backlog can you link it here?

**Comment by jviau** [comment]
@rainersigwald, unfortunately no, we do not have any public backlog for CPS aside from our documentation github - which we do not use for tracking these types of items.
