### ISSUE TITLE
No TypeScript files in VS2017

### ISSUE THREAD

**Issue by tinchou** [Microsoft/msbuild#1354]
Just downloaded VS2017 and migrated my `project.json`-based project. This was created using the Angular 2 template that can be found in https://github.com/aspnet/JavaScriptServices.

Now my TypeScript files are not shown and there are many `.js` and `.map.js` files created automatically.

What would be the correct configuration to have what I had before this?

Thanks!

**Comment by rainersigwald** [comment]
@piotrpMSFT The right home for this kind of migration issue is https://github.com/dotnet/cli/issues, right?

**Comment by piotrpMSFT** [comment]
Yep, feel free to move it our way.

**Comment by tinchou** [comment]
Thanks!
