### ISSUE TITLE
AST for conditions in the OM

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/msbuild#1356]
When inspecting the object model, Condition attributes are returned as strings. But logically, they're an expression language. That language has [a set of AST objects](https://github.com/Microsoft/msbuild/tree/79618b926ec77e3eb5ca0a118d920570f3695a25/src/XMakeBuildEngine/Evaluation/Conditionals), and it could be interesting to inspect them logically--for example to compare semantic equivalence rather than string equivalence.

**Important caveat**: the AST is not very sophisticated. It can represent the different operations like AND, OR, >, <, <= and so on, but the really interesting bits--the things that are being compared--are still roughly opaque strings that can get expanded later outside the AST at operation time.

Idea from @piotrpMSFT in https://github.com/dotnet/cli/pull/4758#discussion_r88418549. Thanks!

**Comment by livarcocc** [comment]
Team Triage: We haven't needed this so far. Closing for now.
