### ISSUE TITLE
VS 2017 crashes when changing Assembly Information in .NET Core csproj

### ISSUE THREAD

**Issue by ChristopherHaws** [Microsoft/msbuild#1358]
Hello,

I am trying to update the Assembly Information (Title, Description, Company, etc) of a brand new .NET Core csproj, which is causing the entire Visual Studio 2017 RC IDE to crash with an unhandled exception. This happens when I try to update the values directly from the `Properties -> Application -> Assembly Information...` window as well as when I use the Properties pane when left clicking the csproj file in the Solution Explorer.

Thanks!

**Comment by dsplaisted** [comment]
Hi @ChristopherHaws,

Thanks for filing this issue.  This is a bug in the project system, and we have an issue tracking it over there: dotnet/roslyn-project-system#762.  So I'm going to close this issue in favor of the project system one.
