### ISSUE TITLE
Cannot target mono i.e. full framework on Linux

### ISSUE THREAD

**Issue by borgdylan** [microsoft/msbuild#1360]
While testing the new .NET CLI preview built on msbuild I noticed that I could not target net461 or other full framework profiles. Does msbuild try to look in the ```xbuild-frameworks``` directory installed by mono in order to find the assemblies to build against? This used to work with project.json so the prior .NET CLI code could be used to do the same in msbuild.

**Comment by dasMulli** [comment]
I've filed a similar issue on the SDK repo: https://github.com/dotnet/sdk/issues/335

**Comment by livarcocc** [comment]
Closing this one in favor of the SDK one.
