### ISSUE TITLE
Cross targeting targets do not specify DefaultTargets="Build"

### ISSUE THREAD

**Issue by nguerrera** [Microsoft/msbuild#1364]
Microsoft.Common.CrossTargeting.targets that replaces Microsoft.Common.CurrentVersion.targets for cross-targeting projects does not specify DefaultTargets="Build" as Microsoft.Common.CurrentVersion.targets does. This causes a plain `msbuild` of the project to build the first target it finds (which happens to be ResolvePackageDependenciesDesignTime at the moment, which runs quickly and silently). This was not found because VS does not invoke the default target nor does the CLI.

I believe the right fix is to simply add DefaultTargets="Build" to Microsoft.Common.CrossTargeting.targets to match Microsoft.Common.CurrentVersion.targets.

cc @rainersigwald @AArnott

--
(Moved from https://github.com/dotnet/sdk/issues/412)

(Moved from: https://github.com/dotnet/roslyn-project-system/issues/781)

After creating a "Console App (.NET Core)" project, edit it so it multi-targets:

```xml
<Project ToolsVersion="15.0">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
    <TargetFrameworks>netcoreapp1.0;net45</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.App" Version="1.0.1" Condition="'$(TargetFramework)' == 'netcoreapp1.0'"/>
    <PackageReference Include="Microsoft.NET.Sdk" Version="1.0.0-alpha-20161116-2">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

Now from the command line, build it once:

    msbuild /t:restore,rebuild

Now change program.cs (or the project file) and build again:

    msbuild

**Expected**
An incremental build will recompile the source file for each target framework.

**Actual**
No build occurs. It skips.

```
msbuild
Microsoft (R) Build Engine version 15.1.0.0
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 11/20/2016 1:23:04 PM.
Project "C:\Users\andarno\Documents\Visual Studio 2017\Projects\ConsoleApp4\ConsoleApp4.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|Any CPU".
Done Building Project "C:\Users\andarno\Documents\Visual Studio 2017\Projects\ConsoleApp4\ConsoleApp4.sln" (default targets).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.14
```

Dev15: d15prerel 25917.2

**Comment by rainersigwald** [comment]
Your root cause and proposed fix sound correct to me.
