### ISSUE TITLE
MSBuild on Mono on *nix incorrectly deals with '\' in VB -define

### ISSUE THREAD

**Issue by agocke** [Microsoft/msbuild#137]
VB by default inserts quotes for -define constants, which are escaped by using `\"`. MSBuild then seems to try to apply directory-separator fixing by turning those `\` into `/`.

**Comment by agocke** [comment]
See https://github.com/dotnet/roslyn/pull/4359 for examples.

**Comment by rainersigwald** [comment]
I'm going to attempt a scoped fix for this, since VB is lighting up in the SDK for 15.3.
