### ISSUE TITLE
Change the way to target multiple frameworks inside csproj

### ISSUE THREAD

**Issue by tugberkugurlu** [microsoft/msbuild#1372]
> from https://github.com/dotnet/cli/issues/4799 based on https://github.com/dotnet/cli/issues/4799#issuecomment-262077267.

Currently, this is the way to target multiple frameworks:

![image](https://cloud.githubusercontent.com/assets/328122/20498277/68a97b7e-b024-11e6-9970-bb235d371109.png)

In addition to what is proposed on #1371, it would be nice to have something similar to below:

```xml
<TargetFrameworks>
    <Framework name="net451" />
    <Framework name="netcoreapp1.0">
      <Dependencies>
          <PackageReference Include="Microsoft.NETCore.App" Version="1.1.0" />
      </Dependencies>
    </Framework>
</TargetFrameworks>
```

## Environment data
`dotnet --info` output:

```
Z:\>dotnet --info
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by livarcocc** [comment]
Team triage: We have no plans at making this change at this point. There is quite a lot of tooling built around TargetFrameworks now as well as different concepts that would break and would have to be adapted based on a change like this.

Closing this issue.
