### ISSUE TITLE
Fix mono build: Update msbuild used to bootstrap

### ISSUE THREAD

**Issue by radical** [Microsoft/msbuild#1382]
The current [build](https://github.com/Microsoft/msbuild/releases/download/mono-hosted-msbuild-v0.2/mono_msbuild_bootstrap_5e01f07.zip) being used to bootstrap does not support `$(MSBuildRuntimeType) == Mono`, which breaks mono builds.

I have an existing [build](https://github.com/radical/msbuild/releases/tag/v0.03) that works, but that is from April.

**Comment by Sarabeth-Jaffe-Microsoft** [comment]
@rainersigwald @AndyGerlicher

**Comment by cdmihai** [comment]
@radical Is the [build](https://github.com/radical/msbuild/releases/tag/v0.03) up to date? I can just upload that to our main repo release and change cibuild.cmd to point to the new address.

**Comment by radical** [comment]
@cdmihai No, it is an old build in fact. The current xplat does not build with mono, but I can build it locally with a hack. So, I will upload a new .zip with it.

**Comment by cdmihai** [comment]
As far as I knew, the xplat branch can build three msbuild flavors, and each flavor requires a different bootstrap msbuild:
- the Full Framework flavor requires VS MSBuild, discovereable via the VS developer command console
- the .Net Core msbuild brings down a .net core bootstrap msbuild via the [build tools](https://github.com/dotnet/buildtools/blob/72f7b5203c81b0cfb63d3fdc60b3351462d1a809/src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json#L5-L10) nuget package
- the Mono flavor requires a Mono bootstrapped MSBuild which we currently keep in a zip file in our Github repo

Are you saying that the Mono flavor no longer requires the Mono bootstrap msbuild?

**Comment by rainersigwald** [comment]
I think @radical is saying that the Mono flavor cannot currently be built with the old Mono bootstrapper. Plus I think there's another issue that was being chased down.

However, I can build the Mono flavor with desktop MSBuild--it'd be pretty great if we could get the bootstrap zip built that way and have it be less of a special snowflake! I have a patched private official build that builds Mono and copies the results to a share, but I haven't tried zipping it up and using it as the bootstrapper yet.

**Comment by radical** [comment]
Yeah, xplat cannot be built with the current Mono bootstrapper.

And the second issue is when referencing `System.Secuirty.Principal.Windows` in `src/XMakeTasks/UnitTests/project.json`, we end up with two references to the same "reference" assembly being passed to the compiler. And mcs seems to fail on that (https://bugzilla.xamarin.com/show_bug.cgi?id=49139), whereas csc works.

**Comment by radical** [comment]
Could we please use the build from my repo [here](https://github.com/radical/msbuild/releases/tag/v0.03) to releases here? This and the PR #1462, would fix the mono build and then we can enable the mono CI. This can be a temporary thing and whenever we have a official build, like Rainer [mentioned](https://github.com/Microsoft/msbuild/issues/1382#issuecomment-265056791), then we can change this.

**Comment by cdmihai** [comment]
Copied it: https://github.com/Microsoft/msbuild/releases/tag/mono-hosted-msbuild-v0.03

I think you have to update the download URL in the cibuild.sh script right?

**Comment by radical** [comment]
Awesome, thank you! Yes, I have opened PR #1480 to update cibuild.sh .
