### ISSUE TITLE
Create Microbuild tests

### ISSUE THREAD

**Issue by cdmihai** [microsoft/msbuild#1386]
We run through an internal build process to real sign the msbuild binaries and create nuget and vsix packges. From time to time that build breaks and we only find out about later. We should create some sort of testing scripts for the build output. Ideas of tests:

- assert that all dlls are real signed
- assert configuration was release?
- assert that satellite assemblies got created

**Comment by cdmihai** [comment]
@Microsoft/msbuild-maintainers please think about build health tests we could run for microbuild

**Comment by livarcocc** [comment]
We have these now as part of arcade.
