### ISSUE TITLE
Provide alternate way to specify the ReferringTargetFramework passed to referenced projects in _GetProjectReferenceTargetFrameworkProperties

### ISSUE THREAD

**Issue by dsplaisted** [Microsoft/msbuild#1390]
Right now, the `_GetProjectReferenceTargetFrameworkProperties` [passes the `TargetFrameworkMoniker`](https://github.com/Microsoft/msbuild/blob/fbba93c46c3603d4eef64cbfe5aaf86a8e6b2e88/src/XMakeTasks/Microsoft.Common.CurrentVersion.targets#L1518) property value as the `ReferringTargetFramework` property to referenced projects.  A deployment-type project might not be a traditional .NET project, so it doesn't make sense for it to have a `TargetFrameworkMoniker`.  However, there should still be a way for such a project to specify a value for `ReferringTargetFramework`, so that the best TargetFramework can be used if the referenced project is multi-targeted.

This could be as simple as having a `ReferringTargetFrameworkForProjectReferences` property that defaults to the `TargetFrameworkMoniker` if not otherwise specified and which is passed as the `ReferringTargetFramework` to referenced projects.

**Comment by rainersigwald** [comment]
This is fixed with #1621's introduction of `ReferringTargetFrameworkForProjectReferences`, right @nguerrera, @dsplaisted?

**Comment by nguerrera** [comment]
Yup.
