### ISSUE TITLE
Comments will be a problem for .NET Core apps with sections containing switches

### ISSUE THREAD

**Issue by GuardRex** [Microsoft/msbuild#1394]
I'm migrating a few projects over to .NET Core with MSBuild/`csproj`. It doesn't look like MSBuild is currently able to handle switches in comments. Perhaps, it's just very keen on the XML standard.

For example, here is a migrated `project.json > tools` section for `csproj` ...
```
<!--
<Target Name="PostpublishScript" AfterTargets="Publish" Condition=" '$(IsCrossTargetingBuild)' 
        != 'true' ">
    <Exec Command="dotnet razor-precompile --configuration $(Configuration) --framework 
        $(TargetFramework) --output-path $(TargetDir) $(MSBuildThisFileDirectory)" />
</Target>
-->
```
I wished to comment it temporarily simply because Razor View precompilation tooling doesn't currently work with MSBuild/`csproj`, so I'd wish to leave this in place and activate it in the future.

Note that MSBuild chokes on the double dashes (`--`) in the switches.
```
MSBUILD : error MSB4025: The project file could not be loaded. An XML comment cannot 
contain '--', and '-' cannot be the last character. Line 107, position 44.
```
If the XML spec doesn't allow double dashes in comments, and you're adhering to the spec, I get why this probably won't be addressed. If there is some wiggle-room wrt the spec, I'm not sure that breaking the standard in a way that would allow them to exist in this file would be all that bad.

Is is possible/feasable that MSBuild could be provided with the capability to ignore comment text all the way up to the end on the comment (`-->`)?

[EDIT] Reference: https://www.w3.org/TR/REC-xml/#sec-comments

> For compatibility, the string " -- " (double-hyphen) must not occur within comments.]

Reasoning:

> [To] ensure that XML remains compatible with SGML.

But I ask: For this configuration file (`csproj`), will you consider breaking the standard because switches, for example, are going to be a common holiday wish list item for devs using comments that have switches in them?

**Comment by rainersigwald** [comment]
Unfortunately, we're at the mercy of `System.Xml`, which enforces this part of the [XML standard](http://www.w3.org/TR/REC-xml/#sec-comments):

> For compatibility, the string " -- " (double-hyphen) MUST NOT occur within comments.
 
I agree that this is especially annoying now that nice double-dash-style arguments are more likely to appear in project files (hooray cross-platform MSBuild!), but I don't see any way of avoiding the problem. We definitely don't want to have to have our own non-standard-compliant XML parser.

Some editors will break double-hyphens on commenting--for example Emacs produces this on your example:

```xml
<!-- <Target Name="PostpublishScript" AfterTargets="Publish" Condition=" '$(IsCrossTargetingBuild)'  -->
<!--         != 'true' "> -->
<!--     <Exec Command="dotnet razor-precompile -\-configuration $(Configuration) -\-framework  -->
<!--         $(TargetFramework) -\-output-path $(TargetDir) $(MSBuildThisFileDirectory)" /> -->
<!-- </Target> -->
```

I know that's not a very satisfying answer. Sorry. 😞

**Comment by GuardRex** [comment]
Thanks @rainersigwald for getting back so fast. That's cool. I'm not a huge fan myself of breaking standards.

Your reply reminded me of something tho ...... single-dash switches will be fine, e.g., `--runtime win10-x64` is the same as `-r win10-x64`. IIRC and AFIAK all of the tooling has been built to support the short switches, so I think we're good here.

Thanks again for discussing it. :+1:

**Comment by rainersigwald** [comment]
That is a decent workaround, though it hurts me to encourage using short forms--I'm generally of the philosophy that long forms are for scripts and computers, and short forms are just for command lines you actually type.
