### ISSUE TITLE
VS2017: MSBuild fails when solution folder name contains space

### ISSUE THREAD

**Issue by wjk** [Microsoft/msbuild#1395]
Apologies if this is the wrong venue, I don’t know of a better place. Please redirect me if appropriate.

I have installed VS 2017 RC on my Windows laptop, loaded a moderately sized solution (18 projects), and have found that if the full path to a project in a solution folder contains a space, MSBuild will not build that project. Here is what happens:

1. I have a solution folder called "Native Components", and inside that solution folder, a C++ project called NTObjectViewer.Launcher. (A C# project inside a different solution folder also exhibits this bug, as long as the name of the solution folder contains a space.)
2. When I build the project (or press F5 to launch, which does the same thing), I get the following error:

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\native\NTObjectViewer\MSBUILD : error MSB1008 : Only one project can be specified.
  Switch: Components\NTObjectViewer_Launcher

  For switch syntax, type "MSBuild /help"
```

This error points to a number of bugs in how Visual Studio is (trying to) invoke MSBuild. First of all, the project name is not `NTObjectViewer_Launcher`, it is `NTObjectViewer.Launcher`. Second, Visual Studio is not properly quoting paths that contain spaces. Third, the path in the first line does not exist on my system. (It is a portmanteau of the path to `devenv.exe`, and the relative path to the offending C++ project from the solution file.) Fourth, as I understand it solution folders should have no effect on how MSBuild operates. It appears that Visual Studio is passing a path containing a solution folder to MSBuild on the command line. It should not do this.

To the extent of my knowledge, all of this worked under VS2015. (However, I cannot test under VS2015, because this solution contains a number of MSBuild-based .NET Core projects, which are not compatible with that version). Any pointers? This is seriously impeding development progress on my project. Thanks!

**Comment by AndyGerlicher** [comment]
My guess is this isn't an issue in MSBuild, but it sounds pretty serious. I tested just now with a space in a few project types and tried building / stepping into and it worked fine. Do you have an easy way to repro this? Steps or a minimal repro project. If so we can take a look and pass it on as appropriate.

**Comment by cdmihai** [comment]
Was not able to re-produce this issue. Please re-open with further instructions if you are still experiencing this issue.
