### ISSUE TITLE
init_tools fails to download file and makes installation fail

### ISSUE THREAD

**Issue by feliwir** [Microsoft/msbuild#1396]
Hello,

the installation on ubuntu 16.10 doesn't seem to work for me because curl can't download this file: https://dotnetcli.blob.core.windows.net/dotnet/Sdk/1.0.0-preview3-003686/dotnet-dev-ubuntu.16.10-x64.1.0.0-preview3-003686.tar.gz .Is there any reason for that?
Using the latest xplat branch

**Comment by jeffkl** [comment]
The dotnet CLI lists Ubuntu 16.10 in the public preview: https://www.microsoft.com/net/core#linuxubuntu

But not in the daily releases which we use: https://github.com/dotnet/cli#installers-and-binaries

@piotrpMSFT or @livarcocc Is our [init script](https://github.com/Microsoft/msbuild/blob/xplat/init-tools.sh) wrong for Ubuntu 16.10?

**Comment by feliwir** [comment]
will this get fixed at some point? I am still unable to test msbuild on Ubuntu 16.10

**Comment by borgdylan** [comment]
@jeffkl The tools that are downloaded are not available for 16.10 or even 17.04 for that matter. The only way to build is to treat 16.04+ as 16.04.

**Comment by cdmihai** [comment]
Tracked in #1702
