### ISSUE TITLE
Migrate MSBuild repo to use VS2017 .NET Core projects

### ISSUE THREAD

**Issue by AndyGerlicher** [Microsoft/msbuild#1399]
Creating an issue to track the overall migration.

Our repo should take advantage of the .NET Core project features / SDK in VS2017 and remove dependency on BuildTools as much as possible (i.e. remove `init-tools` in favor of `dotnet`).

This should include using globbing and as many features added for .NET Core projects as possible for dogfooding. We will need to adjust our source layout for all of this to work, but it should be the eventual goal.

**Comment by cdmihai** [comment]
A prerequisite for this would be redoing the file layout so we don't have nested projects. Otherwise the globs would glob too much.

**Comment by borgdylan** [comment]
What about building the mono variant of MSBuild in that case? I hope that all the current target frameworks will be retained.

**Comment by rainersigwald** [comment]
@borgdylan We don't plan to drop it but don't have a firm plan at the moment. Filed #1800 to track.

**Comment by aka-STInG** [comment]
Not sure if this is right place to ask, but in result will this allow to use roslyn MSBuildWorkspace to open and compile solutions in cross-platform environment at runtime?

**Comment by rainersigwald** [comment]
@aka-STInG that's orthogonal to this issue--you might be looking for something like #1469?

**Comment by rainersigwald** [comment]
Bulk of this is done with #2868. Remaining issues tracked in https://github.com/Microsoft/msbuild/milestone/14.
