### ISSUE TITLE
Import from SDKs

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#1400]
This is related to #1392, but not a prerequisite for it.

It's currently difficult to determine what the path of an `<Import>` should be, because it requires knowing how to locate the file to be imported, using properties and relative paths.

#1392 introduces the concept of an "SDK" in order to automatically import an `Sdk.props` before the user project and an `Sdk.targets` after it. But that's often not sufficiently granular: sometimes you need to override a target (so your definition must be ordered after the imported one), or set a property before importing an initial target.

# Design
```xml
<Project>
  <user prop here>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk/1.0.0.0" />
...
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk/1.0.0.0" />
  <user target here>
</Project>
```

Should be syntactic sugar for something like

```xml
<Project>
  <user prop here>
  <Import Project="$(MSBuildSDKsPath)\%(___MSBuildSDK.Name)\%(___MSBuildSDK.Version)\Sdk.props" />
...
  <Import Project="$(MSBuildSDKsPath)\%(___MSBuildSDK.Name)\%(___MSBuildSDK.Version)\Sdk.targets" />
  <user target here>
</Project>
```

This is a) easier to type than the existing mechanism requiring a rooted path and b) doesn't lose any generality, as #1392 does.

**Comment by rainersigwald** [comment]
Similar for `UsingTask`?

**Comment by gulbanana** [comment]
As a workaround, I'm currently using
`<Import Project="$(MSBuildSDKsPath)\Microsoft.NET.SDK\Sdk\Sdk.targets" />`
before my custom targets. This works, but emits a warning which sits in the visual studio error list forever :-(

**Comment by jeffkl** [comment]
@gulbanana this is addressed in the newer implementation which is in PR now: https://github.com/Microsoft/msbuild/pull/1492

**Comment by gulbanana** [comment]
Great, I'll try it again in a later build.

**Comment by codito** [comment]
Any idea if #1492 is available on dotnet-cli dev builds?

**Comment by rainersigwald** [comment]
@codito Yes, it should be. Note that sometimes the "latest" link on the CLI homepage isn't actually the very latest.

**Comment by codito** [comment]
I can confirm the fix is available on dotnet-cli `1.0.0-rc4-004527`. Thanks!

**Comment by rainersigwald** [comment]
Closing since this is implemented.

On further reflection, I don't think this is needed for `UsingTask`s. You can always have a .props file next to the task DLL that uses `$(MSBuildThisFileDirectory)` in its `UsingTask`.

**Comment by kzu** [comment]
It works great on VS2017 RTW without specifying an SDK version, like so:

```xml
<Project>
	<Import Project="SampleVsix.props" />
	<Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
	<PropertyGroup>
		<TargetFrameworks Condition="'$(TargetFrameworks)' == ''">net462;net461</TargetFrameworks>
	</PropertyGroup>
	<Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
	<Import Project="SampleVsix.targets" />
</Project>
```

**Comment by AArnott** [comment]
This works for me as well. And in fact I have exactly the same scenario: A VSIX project that must import the language targets before the VSSDK targets.
