### ISSUE TITLE
Multiple errors converting .net core to csproj

### ISSUE THREAD

**Issue by gilmishal** [Microsoft/msbuild#1410]
I have opened this [SO](http://stackoverflow.com/questions/40892034/multiple-errors-converting-net-core-to-csproj) question, and decided it might be worth asking here as well.

basically I have migrated an asp.net core project from xproj to csproj for using VS2017RC. Now everything went to hell... getting a lot of msbuild errors, Visual Studio 2015 can't load nuget packages. VS2017 manages to build the project - but Intellisense is going crazy..

**Comment by jeffkl** [comment]
Moved to https://github.com/dotnet/cli/issues/4871
