### ISSUE TITLE
MSbuild error

### ISSUE THREAD

**Issue by siddytopcoder** [Microsoft/msbuild#1417]
Error MSB3073: The command "mstest /testcontainer:"C:\Users\gautams\Documents\Visual Studio 2013\Projects\CounterStrike\SinglePlayerTest\SinglePlayerTest.dll"" exited with code 1.

**Comment by rainersigwald** [comment]
Closing because the simplest explanation in isolation for that message is that there's a test failure. If you still believe this is an MSBuild bug, please explain why and provide more context.
