### ISSUE TITLE
(Build Tools SKU) Can't find VS from non-dev command window

### ISSUE THREAD

**Issue by AndyGerlicher** [Microsoft/msbuild#1418]
When installing MSBuild from the [Build Tools for Visual Studio 2017 RC](https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017-rc) product, MSBuild is unable to find Visual Studio from a standard command prompt. 

There are a [few mechanisms](https://github.com/Microsoft/msbuild/blob/xplat/src/Shared/BuildEnvironmentHelper.cs#L238-L243) used to determine the location of Visual Studio, and if none of these are able to be resolved the value will be left blank. This manifests itself as certain properties being set incorrectly. `MSBuildExtensionsPath`, for example, will be `\MSBuild`. Both issues should be addressed:
1. [This code](https://github.com/Microsoft/msbuild/blob/xplat/src/Shared/BuildEnvironmentHelper.cs#L277) should be able to find the path to the Build Tools "Visual Studio" root via the setup API. This works on standard installs of Visual Studio, but apparently not the Build Tools install.
2. When Visual Studio can't be found, properties that are derived from that should have a better default (even empty would be better than `\MSBuild`).

**Comment by rainersigwald** [comment]
@AndyGerlicher  does c3f7f72 fix this entirely or is there more to be done? If so, what?

**Comment by rainersigwald** [comment]
This appears to work just fine with Build Tools 15.5.4. Closing as fixed.
