### ISSUE TITLE
Exec task fails with Unicode characters

### ISSUE THREAD

**Issue by AndyGerlicher** [Microsoft/msbuild#142]
Run Exec task with non-ANSI characters in the command:
```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Target Name="Build">
        <Exec Command="创建\test.cmd"/>
    </Target>
</Project>
```

This doesn't work. Exec creates a temp cmd file and executes it.

Cmd file looks like:
```
setlocal
set errorlevel=dummy
set errorlevel=
??\test.cmd
exit %errorlevel%
```
This was done on purpose a very long time ago (Windows XP doesn't support this scenario).

**Comment by akoeplinger** [comment]
Sounds like https://github.com/Microsoft/msbuild/issues/104 ?
