### ISSUE TITLE
Implicit import should use $(MSBuildSdksPath) property

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#1423]
(pointed out offline by @radical)

The generated `Import` element shouldn't be implemented [as it is](https://github.com/Microsoft/msbuild/commit/649022690e7d5864e2ce68af4e2a7eeebfc6280a#diff-a9d9d41d4ebe72ee0285850966f63d3fR211), but could inject a use of the MSBuildSdksPath property. It could be just

```C#
$"$(MSBuildSdksPath)\{sdkName}\sdk\Sdk.props"
```

That would allow a) import fallbacks and b) easier overriding of the property (wouldn't have to check for an environment variable in the [default setting](https://github.com/Microsoft/msbuild/commit/649022690e7d5864e2ce68af4e2a7eeebfc6280a#diff-32568b659f3471e9ecdeb620a363af3cR466)).

**Comment by rainersigwald** [comment]
Note that this might be irrelevant, depending on the nature of the SDK acquisition story once there is one.

**Comment by AndyGerlicher** [comment]
Agree with the 2nd comment. But I also don't think we should have a concept of fallback here. For instance, if we are asking a NuGet SDK resolver to get a package and give us the path, it should return the exact path to the SDK on disk. Adding support for fallback would only complicate the scenario. I strongly don't want this to turn into an `MSBuildExtensionsPath` scenario where things install stuff to the machine then we look in a few places until we find them or error.

**Comment by mhutch** [comment]
I don't think that scenario can be avoided. When someone adds an SDK then they have to install it to `MSBuildSdksPath` and that's basically `MSBuildExtensionsPath` again.

**Comment by rainersigwald** [comment]
@mhutch That is true today for the initial only-supports-.NET-and-Web implementation of Sdks.

The long term goal is to allow third-party Sdks, and have a mechanism that makes them available at import time--like NuGet restore does, but potentially distinct from it (to avoid polluting the project's package-closure with references needed by build-time processes).

**Comment by mhutch** [comment]
Ah, ok. How long term is that goal? :)

**Comment by AndyGerlicher** [comment]
@mhutch the currently solution is interim for this preview release only (hopefully). And the situation you described is actually exactly why I would not want to use `MSBuildExtensionsPath` or let anyone outside of MSBuild know where the `MSBuildSdksPath` points to. If someone is adding an SDK they have to install, they might as well just use `MSBuildExtensionsPath` and import it (and that has fallback for that reason). Ideally this new feature would include an acquisition story so the actual path on disk is an implementation detail/contract between the acquisition mechanism and the package resolver. This is still in progress so we can't yet answer all the questions, but this is some of our initial thoughts.

**Comment by mhutch** [comment]
Ok, makes sense!

**Comment by piotrpMSFT** [comment]
@rainersigwald is this getting fixed for RC2? CLI implementation around SDKs was based on the spec and therefore depends on the environment variable. Do we need to make a short-term adjustment?

**Comment by rainersigwald** [comment]
@piotrpMSFT No, it's not going to be changed for RC2. But this is just a more elegant way to implement the same behavior--if the CLI sets the environment variable current MSBuild will respect it.

**Comment by piotrpMSFT** [comment]
@rainersigwald I'm not seeing that. CLI is setting the environment variable but MSBuild is looking for the sdk in an `Sdks` directory next to itself. I don't have much time to dig into this today so I'm adjusting CLI to the error message...

**Comment by piotrpMSFT** [comment]
`Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "/Users/piotrp/code/github/piotrpMSFT/cli/artifacts/osx.10.11-x64/stage2/sdk/1.0.0-preview4-004184/Sdks/Microsoft.NET.Sdk/Sdk/Sdk.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.`

**Comment by piotrpMSFT** [comment]
FWIW, I ran a `/v:diag` build [though after changing the path] so we can see if there is something wrong with the env var casing, spelling, etc:

`MSBuildSDKsPath = /Users/piotrp/code/github/piotrpMSFT/cli/artifacts/osx.10.11-x64/stage2/sdk/1.0.0-preview4-004184/Sdks`

**Comment by rainersigwald** [comment]
That's reporting on the property, not the environment variable, so I'd expect that given your symptoms.

**Comment by piotrpMSFT** [comment]
@rainersigwald and I looked at this a bit and saw that the environment variable is being honored by MSBuild. Looks like a local issue on my machine. I'll report back if I find new symptoms.

**Comment by rainersigwald** [comment]
Yes, I think so.
