### ISSUE TITLE
mac msbuild can't find mac powershell when run in a post build step task

### ISSUE THREAD

**Issue by softlion** [microsoft/msbuild#1427]
I can run a powershell ps1 script from a terminal command line,
but the same ps1 script won't start when specified in a post build step task in Visual Studio Mac Preview.

In a csproj file the postbuild event is set to:

  <PropertyGroup>
    <PostBuildEvent>powershell -file $(ProjectDir)afterbuild.ps1 $(SolutionDir) $(TargetFileName)</PostBuildEvent>
  </PropertyGroup>

This works fine in VS2015 on Windows.
It does not work in Visual Studio Mac Preview, with the error "powershell command not found" (exit code 127).

Powershell is installed in /usr/local/microsoft/powershell/6.0.0-alpha.13/powershell
If the same command line is executed in a mac terminal, it works fine (the ps1 script does work on mac, and the command line to execute it does run too).

Error:

	/Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets: error : Command 'powershell -file (removed)/src/Client.Data/afterbuild.ps1 (removed)/ Client.Data.dll' exited with code: 127.

Is there a workaround ?

**Comment by rainersigwald** [comment]
Is powershell on your PATH? How was it put there?

**Comment by softlion** [comment]
By poweshell installer.
Is this project also used in vs mac ?
I suppose so as xbuild won't built my project.

**Comment by rainersigwald** [comment]
> By poweshell installer.

Do you know what that's actually doing? I'm wondering if there's a login-shell/interactive-shell config problem.

> Is this project also used in vs mac ?

Not entirely, but things are moving that direction. I'm not sure what the current state is in the VS Mac preview.

**Comment by softlion** [comment]
Well the installer just install power 
shell as of it was a standalone tool. But I don't know how it add it to the path. But is is available from anywhere so should be in the path.
It works fine and can be invoked fine from terminal.

You mean msbuild creates login shell to execute external commands, but poweshell is not in the path. I have already tried that by adding the path explicitly : It does work :)
So this is the problem.

I don't' know if mac preview uses xbuild. I suppose it does not. So it may use msbuild but don't know the version it uses.

**Comment by softlion** [comment]
I suppose I should move the issue to the powershell installer team ....

Btw is there a way to get the platform (OS X) in an msbuild property ? So I could work they around.

**Comment by softlion** [comment]
I've tryed to add powershell to the global path in /etc/paths.d and $HOME/.bash_profile but msbuild still does not find powershell.

So i suppose the problem is in msbuild not powershell.

**Comment by rainersigwald** [comment]
I installed powershell from their latest package and things seem to be ok with a just-built MSBuild:

```sh-session
sh-3.2$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1108
sh-3.2$ which powershell
/usr/local/bin/powershell
sh-3.2$ cat powershell.proj 
<Project>
  <Target Name="PS">
    <Exec Command="powershell write-host 'in ps'" />
  </Target>
</Project>
sh-3.2$ mono bin/Debug-MONO/OSX_Deployment/MSBuild.dll powershell.proj
Microsoft (R) Build Engine version 15.1.0.0
Copyright (C) Microsoft Corporation. All rights reserved.

env:  default: /Users/raines/src/msbuild/bin/Debug-MONO/OSX_Deployment/Sdks
Build started 12/3/2016 3:39:56 PM.
Project "/Users/raines/src/msbuild/powershell.proj" on node 1 (default targets).
PS:
  powershell write-host 'in ps'
  in ps
Done Building Project "/Users/raines/src/msbuild/powershell.proj" (default targets).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.49
```

So something else must be going on on your machine. Can you build from the command line?

**Comment by softlion** [comment]
It works fine from the command line.
So this is more a problem of Visual Studio Mac Preview.

```
sh-3.2$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1108

sh-3.2$ which powershell
/usr/local/bin/powershell

  <Target Name="AfterBuild">
   <Exec Command="powershell write-host 'in ps $(MSBuildBinPath)'" />
  </Target>

Built from Visual Studio for Mac Preview 1 (7.0 build 347), build engine set to MSBuild (but don't know the version)
Errors:
(AfterBuild target) ->
      /Users/me/Projects/myapp/myaoo.csproj: error : Command 'powershell write-host 'in ps /Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/xbuild/14.0/bin'' exited with code: 127.

Microsoft.Build.dll@ -> ../../../gac/Microsoft.Build/14.0.0.0

```

From command line:

```
mono /Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/xbuild/14.0/bin/xbuild.exe myapp.csproj

	Target AfterBuild:
		Executing: powershell write-host 'in ps /Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/xbuild/14.0/bin'
		in ps /Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/xbuild/14.0/bin
Done building project "/Users/iben/Projects/widescopemobility/widescopemobile.git/src/WSMClient.Data/WSMClient.Data.csproj".

Build succeeded.

```

**Comment by livarcocc** [comment]
If this is still an issue for you, I suggest filling a feedback ticket through VS for Mac itself. Given that this does not repro through the command line, it is likely something that VSM is doing.
