### ISSUE TITLE
MSBuild Construction APIs should allow interrogating and modifying SDKs [Implicit Imports]

### ISSUE THREAD

**Issue by piotrpMSFT** [Microsoft/msbuild#1429]
MSBuild Construction APIs should allow interrogating and modifying SDKs. E.g. there should be a way to learn about:

```
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
```

Perhaps something like:

```
class ProjectElement
{
...
   public string Sdk { get; set; }
...
}
```

**Comment by rainersigwald** [comment]
Fixed by #1492: https://github.com/Microsoft/msbuild/pull/1492/files#diff-8cb9562b0886694911efff69e5dc15ffR67.

Thanks for catching that, @vijayrkn!
