### ISSUE TITLE
Replace FxCop with Code Analysis in Visual Studio 2015

### ISSUE THREAD

**Issue by irfspy** [Microsoft/msbuild#1435]
Hi,

Currently I have fxcop file for eg: demo.fxcop

![image](https://cloud.githubusercontent.com/assets/16488496/20889687/f3235f76-bb29-11e6-9dac-4b9f101a236d.png)

where we have defined rules but now I need to remove this file and

wanted to use same set of rules in Code analysis.

Is there a way we can implement it.

Thanks

**Comment by AndyGerlicher** [comment]
@jaredpar Jared do you by chance know a contact @irfspy can ask for FxCop questions? Thanks!

**Comment by jaredpar** [comment]
@srivatsn should know the best FxCop contact.

**Comment by srivatsn** [comment]
Presumably you have a project producing Tests.dll? If so, you can add a ruleset to that project that has the rules you have in the .fxcop file. If you enable the CodeAnalysis on Build checkbox in the project properties->Code Analysis tab, these rules will get run on a regular build.

**Comment by irfspy** [comment]
Thank you!

Please correct me if I am wrong.

I have a fxcop file in a solution in which I have 2 projects. Also I have a rule set file.
So do I have to do the below process for both the projects?
goto project properties->Code Analysis tab and select that file.

Secondly, there are two check boxes in Code Analysis tab one related to enable build and other one is suppress result. So do I need to check both the boxes?

**Comment by srivatsn** [comment]
Yes you need to set the ruleset for both projects. You only need to the check the first checkbox about enabling analysis on build.

**Comment by irfspy** [comment]
Thank you for your help!
