### ISSUE TITLE
ProjectRootElement.RawXml Never contains updated comments

### ISSUE THREAD

**Issue by 333fred** [Microsoft/msbuild#1442]
As the title says, updated comments aren't reflected in the output of ProjectRootElement.RawXml. This causes https://github.com/dotnet/roslyn-project-system/issues/743. If there's a better api for getting what XML would be actually written out when saved, I'd be more than happy to use it, as RawXml seems to not be intended for that purpose.

**Comment by dsplaisted** [comment]
I think what you want to use is [`ProjectRootElement.Save(TextWriter)`](https://github.com/Microsoft/msbuild/blob/fa4c4f350617d20ad78c68e0a44d7be449e96260/src/XMakeBuildEngine/Construction/ProjectRootElement.cs#L1836).  The [whitespace preservation tests](https://github.com/Microsoft/msbuild/blob/fa4c4f350617d20ad78c68e0a44d7be449e96260/src/XMakeBuildEngine/UnitTestsPublicOM/Construction/WhiteSpacePreservation_Tests.cs), for example, call `Project.Save(TextWriter)`, which just forwards the call to the method on `ProjectRootElement`.

**Comment by 333fred** [comment]
`RawXml` actually calls Save under the hood with a StringWriter. I tried it anyway just to be sure, and it has the same behavior.

**Comment by rainersigwald** [comment]
I suspect the root of the problem here is that the MSBuild side of the object tree doesn't know anything about comments, so if we walk it to update we won't see comment nodes.

**Comment by dsplaisted** [comment]
Strange.  The whitespace preservation tests use the same APIs to save to validate that not only are comments preserved, but that the whitespace around them is preserved (if preserveWhitespace is enabled).  I suspect the difference lies in how the project is loaded.

**Comment by rainersigwald** [comment]
Could also be a post-clone problem.

**Comment by 333fred** [comment]
@dsplaisted , `RawXml`, and by extension `Save`, are also not showing the whitespace.

**Comment by cdmihai** [comment]
@333fred / @dsplaisted 

Can you please write out a minimal repro that, using MSBuild's APIs shows this issue? I'm asking because the MSBuild APIs do not expose the xml comments, so I am curious how you get into this state. I would expect the editor to tear down and recreate the `Project` / `ProjectRootElement` objects after the contents got changed. Otherwise the underlying XmlElement object model does not get updated, hence `Save` does not reflect the updated comments.

**Comment by jviau** [comment]
This is an issue with the way [project live reload](https://github.com/dotnet/roslyn-project-system/blob/e9c0f3c1d7e467e4b92309241ed71dec6b338ec2/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Reload/ReloadableProject.cs#L84) works. A new `ProjectRootElement` is created from the changed project on disk and then deep copied into the existing project. This is not an ideal solution as it is expensive and `DeepCopyFrom` doesn't seem to preserve a lot of the formatting (including comments). Also looks like it doesn't even update `RawXml`.

As @cdmihai has suggested in earlier discussions, we should swap the `ProjectRootElement` out with the newly loaded one. Unfortunately, the only way I have found to "swap" out the elements would be via `ProjectCollection.UnloadProject`, which means unloading all `Project` objects (one per CPS ConfiguredProject) that reference the `ProjectRootElement`. This is not feasible for CPS. Instead I think `ProjectCollection` should offer an API to swap out `ProjectRootElement`. It can then update all necessary `Project.Xml` to point to the new xml. This is fine to perform in CPS as it will happen within a write lock, so no one else should be holding references to these objects at the time. Another option is to have `ProjectRootElement` be able to re-build itself from new xml.
