### ISSUE TITLE
The UnloadProjectsOnCompletion property on MsBuild task doesn't do anything

### ISSUE THREAD

**Issue by pvandervelde** [microsoft/msbuild#1455]
This means that the following code may fail if any of the projects in the solution rely on NuGet packages which contain targets files (e.g. Microsoft.Bcl.Build).

``` xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0"
         DefaultTargets="ToolsBuild_Build_Prepare_Workspace_Run"
         xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

     <PropertyGroup>
        <Configuration>Release</Configuration>
        <Platform>Any CPU</Platform>
     </PropertyGroup>
     <Target Name="ToolsBuild_Build_Prepare_Workspace_Run"
        <MSBuild
            BuildInParallel="False"
            Projects="MySolution.sln"
            Properties="Configuration=$(Configuration);Platform=$(Platform)"
            RebaseOutputs="False"
            RemoveProperties=""
            RunEachTargetSeparately="True"
            SkipNonexistentProjects="False"
            StopOnFirstFailure="False"
            TargetAndPropertyListSeparators=""
            Targets="Clean"
            ToolsVersion="$(MSBuildToolsVersion)"
            UnloadProjectsOnCompletion="True"
            UseResultsCache="True">
        </MSBuild>
        
        <Exec Command="nuget restore mysolution.sln" />
        
        <MSBuild
            BuildInParallel="False"
            Projects="MySolution.sln"
            Properties="Configuration=$(Configuration);Platform=$(Platform)"
            RebaseOutputs="False"
            RemoveProperties=""
            RunEachTargetSeparately="True"
            SkipNonexistentProjects="False"
            StopOnFirstFailure="False"
            TargetAndPropertyListSeparators=""
            Targets=""
            ToolsVersion="$(MSBuildToolsVersion)"
            UnloadProjectsOnCompletion="True"
            UseResultsCache="True">
        </MSBuild>
    </Target>
 </Project>
```

The [documentation of the MsBuild task](https://msdn.microsoft.com/en-us/library/z7f65y0d.aspx) says that setting the property  to true means the projects are unloaded (and thus the solution should be unloaded in our test case). But the [documentation of the MsBuild.UnloadProjectsOnCompletion property](https://msdn.microsoft.com/en-us/library/microsoft.build.tasks.msbuild.unloadprojectsoncompletion.aspx) says that that the property isn't used (which seems to be confirmed by the [code](https://github.com/Microsoft/msbuild/blob/master/src/XMakeTasks/MSBuild.cs)).

Obviously the work around is to call MsBuild from the Exec task however that seems to defeat the purpose of having the MsBuild task which is supposed to be faster and easier to use (especially when it comes to passing in additional properties).

At the very least it would be nice if the documentation was updated to indicate that the property is useless, ideally the MsBuild task code would be updated to use the property and unload the projects once it is done so that we can run the code above.

**Comment by rainersigwald** [comment]
Team triage: the docs have been fixed to no longer mention this (ignored) parameter.

For the specific case of restoring before build, consider using `msbuild -restore` which runs NuGet restore before build.
