### ISSUE TITLE
SPEC: Visual Studio & Toolset Discovery

### ISSUE THREAD

**Issue by AndyGerlicher** [Microsoft/msbuild#1461]
Currently the logic to find out where MSBuild is located has grown in complexity and is not coupled to Visual Studio discovery. Unfortunately these two are more intermingled than we originally thought and must be revisited to fix some issues.

This discovery is required for MSBuild to operate because depending on environment (or mode) MSBuild behaves slightly different for things like extensions path and other items defined in the toolset.

I am proposing that we detect and operate in one of three modes: `VS`, `Standalone`, and `None`. The logic to discover the environment could be as follows:

```C#
Entry = Entry point process exe
DevConsole = Directory Exists (%VSINSTALLDIR%) && VisualStudioVersion == '15.0'

if (Entry == 'devenv.exe')
{ // Case #1
  Mode = 'VS'
  ToolsPath = Entry.Directory\..\..\MSBuild\15.0\Bin\
  ToolsPath64 = %ToolsPath%\Amd64
  MSBuildExtensionsPath = Entry.Directory\..\..\MSBuild
  VisualStudioDir = Entry.Directory\..\..\
}
if (Entry == 'MSBuild.exe')
{
  if (Entry.Directory like '%\MSBuild\15.0\Bin\%')
  { // Case #2
    Mode = 'VS'
    ToolsPath = Entry.Directory  // Note: We may be already in Amd64\MSBuild.exe. Must account for this.
    ToolsPath64 = %ToolsPath%\Amd64
    MSBuildExtensionsPath = Entry.Directory\..\..\
    VisualStudioPath = Entry.Directory\..\..\..\
  }
  else
  { // Case #3
    Mode = 'Standalone'
    ToolsPath = Entry.Directory
    ToolsPath64 = Entry.Directory  // 64 not supported
    MSBuildExtensionsPath = Entry.Directory
    VisualStudioPath = null
  }
}

if (Entry != MSBuild && Entry != VS)
{
    if (Entry.Directory like '%\MSBuild\15.0\Bin\%)
    {
      Mode = 'VS',  Case #2      
    }
    if (File Exists: Entry.Directory\'MSBuild.exe' )
    {
      Mode = 'Standalone', Case #3   // Even in DevConsole
    }
    if (NOT File Exists: Entry.Directory\'MSBuild.exe' )
    {
      if (DevConsole)
      { // Case #4
        Mode = 'VS
        ToolsPath = DevConsole.VSPath\MSBuild\15.0\Bin
        MSBuildExtensionsPath = DevConsole.VSPath\MSBuild
        VisualStudioPath = DevConsole.VSPath        
      }
      else if (VS Setup COM API)
      {
        Mode = 'VS', Case #4
        if (VSSetup.Count > 1) Warn
      }
      else if (Exists: AppContextBaseDir \ MSBuild.exe)
      {
        Mode = 'Standalone', Case #3
      }
      else
      {
        Mode = 'None'
      }
    }
}
```

Principles in each Mode:
`VS`: 
* Toolsets are read from the process called. If you call into MSBuild.exe it should use the toolset that ships with that instance of Visual Studio
* Extensions path set to `%VSINSTALLDIR%\MSBuild` path with fallback to `c:\Program Files (x86)\MSBuild`.

`Standalone`:
* Toolsets are read locally (or hard coded locally in .NET Core).
* Should never be aware of Visual Studio knowledge or SDKs.

`None`:
* This is the case where you reference (for example) Microsoft.Build.dll. Very few things should work.
* Toolsets not read locally, only fallback to registry

Action items:

- [x] Implement spec in `BuildEnvironmentHelper.cs`.
- [ ] Add warning when more than once instance of Visual Studio is found using the Setup COM API.
- [x] When in `None` mode, ensure that the toolset reader does not throw. Likely nothing will build successfully, but for example the construction API should function. No project evaluation or build will work. 
- [ ] Potential idea: Publish NuGet package to help a standalone app find MSBuild. This would check if we're in DevConsole or use the Setup COM API to find VS and add AssemblyLoad logic to the current AppDomain to find Microsoft.Build.*.dll.

**Comment by rainersigwald** [comment]
Looks good overall. Comments/questions:

Your pseudocode breaks my brain :)

VS version >= 15.0 for all checks there.

What's case 4?

What is the case-3 "even in devconsole" case?

Unify language around "disconnected" -> "none".

**Comment by rainersigwald** [comment]
@kirillosenkov -- you've asked questions related to our current confusing behavior in this area before. Does this sound reasonable to you?

**Comment by AndyGerlicher** [comment]
Sorry about the bad pseudocode, quick attempt to capture what we did on the whiteboard :)

I would say VS version == 15.0 (CurrentVisualStudioVersion). If VS version is 16 or 17 and MSBuild is built for 15 we should probably ignore it?

Case 4 is from the DevConsole, so we find VS by the environment variable.

The case-3 even in devconsole was a note because we had a discussion if we should do something different. But in that case you included an MSBuild.exe (or .dll) so you're intending to be in Standalone mode. So in that case we should not know about VS toolsets. So we would ignore VSINSTALLDIR, etc.

**Comment by rainersigwald** [comment]
Ok, sounds reasonable.

**Comment by jeffkl** [comment]
Related to https://github.com/Microsoft/msbuild/issues/114

**Comment by KirillOsenkov** [comment]
Quick question: is there an extensibility point (escape hatch) for the None mode? If I'm running MSBuild in a complete vacuum, I should be able to set some state or pass the path to my own toolset somehow.

Also, I remember that VS exe is not always 'devenv.exe', but I can't remember the case. Was it Blend, or Express? Or iso shell? Not sure now but worth checking.

**Comment by mletterle** [comment]
It's hard to tell from the pseudocode, but does this mean if an import isn't found in the DevEnv install location, it should/will fallback to the Program Files msbuild directory? 

Basically, shouldn't MSBuildExtensions be the aggregate of the DevEnv install and program files?

**Comment by rainersigwald** [comment]
@mletterle Yes, that's how it works: it'll be searched for in the VS instance install, then fall back to progfiles.

**Comment by rainersigwald** [comment]
Closing this because I think it's currently fully implemented. Please reopen if I'm wrong @AndyGerlicher.

**Comment by DustinCampbell** [comment]
> Potential idea: Publish NuGet package to help a standalone app find MSBuild. This would check if we're in DevConsole or use the Setup COM API to find VS and add AssemblyLoad logic to the current AppDomain to find Microsoft.Build.*.dll.

I would love to have this. In OmniSharp, we end up calling `TryFromSetupApi` via [reflection](https://github.com/OmniSharp/omnisharp-roslyn/blob/dev/src/OmniSharp.MSBuild/MSBuildHelpers.cs#L65-L78) in order to determine whether we should set environment variables to use MSBuild in Standalone mode. In VS Code, we only want to be standalone as a last resort.
