### ISSUE TITLE
Incorrect rendering code samples in docs

### ISSUE THREAD

**Issue by mfilippov** [Microsoft/msbuild#1470]
I found a problem in docs https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-items all code samples has incorrect style.
<img width="1740" alt="screen shot 2016-12-13 at 13 00 40" src="https://cloud.githubusercontent.com/assets/927432/21136069/32bddae2-c135-11e6-94b9-6b984b5345ee.png">
I check Github page by edit button all looks gook.

**Comment by rainersigwald** [comment]
I see the same in multiple browsers. @Sarabeth-Jaffe-Microsoft can you check with our doc colleagues about a) if this is something we're doing wrong and b) what the best place to report this sort of issue is?

**Comment by Sarabeth-Jaffe-Microsoft** [comment]
Thanks for letting us know, @mfilippov! The docs team is looking into the cause of this issue now.

**Comment by mfilippov** [comment]
Documentaion fixed, thank you.
