### ISSUE TITLE
Commenting out csproj elements moves them to top on save

### ISSUE THREAD

**Issue by 333fred** [Microsoft/msbuild#1472]
Related to #1442. Moved from https://github.com/dotnet/roslyn-project-system/issues/932.
@onotovy said:
> When I have a CSproj open for editing, if I comment-out a property group, when I hit save, it moves the commented area to the top of the file, right under project. That's startling and wrong as it moves items from where I want. Further, if it can change the meaning if they're uncommented and not restored to the correct location (which someone may not know where it belongs).

Again, I'm accessing the XML by going through the RawXml property: https://github.com/dotnet/roslyn-project-system/blob/dev15-rc2/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Utilities/IMsBuildAccessor.cs#L53.

FYI @AndyGerlicher @rainersigwald

**Comment by Sarabeth-Jaffe-Microsoft** [comment]
Thank you for letting is know about this bug, @333fred. This sounds like a very worrisome developer experience. @cdmihai please look into this.

**Comment by onovotny** [comment]
It's more than that...if you paste in an XML snippet that contains a comment and hit save, it appears to remove the comment from the editor. When you look on disk, it's really there.

**Comment by cdmihai** [comment]
Can you please write out a minimal repro in terms of MSBuild APIs that exposes this issue? That way I can debug and see what happens. See my comment from the related issue: https://github.com/Microsoft/msbuild/issues/1442#issuecomment-266917716

**Comment by cdmihai** [comment]
Should be fixed by #1507
