### ISSUE TITLE
P2P ref from UWP picks the win8 version instead of uap10.0 ver of cross-compiled lib

### ISSUE THREAD

**Issue by nguerrera** [Microsoft/msbuild#1474]
Moved from https://github.com/dotnet/roslyn-project-system/issues/937 on behalf of @onovotny:

> A UWP project isn't getting the correct output of a cross-compiled project. Instead it's getting the win8 version.
>
>Check out
>https://github.com/onovotny/Zeroconf/tree/847ef218c7f94a1dc0b0dfa35a4c11d954c97f98
>
>The ZeroconfTest.UWP project has a P2P ref to Zeroconf. Zeroconf has lots of targets. The product in the dll shows what TFM it was built for. When looking at what's in the UWP\bin\x86\Debug directory, I see the win8 version not the uap10.0 version and things break.
>

See https://github.com/dotnet/roslyn-project-system/issues/937#issuecomment-266874274 for the patch that fixed the issue. The problem is that it is $(NugetTargetMoniker) and not $(TargetFrameworkMoniker) that will result in nuget picking the correct "best" target for UAP.

**Comment by onovotny** [comment]
I'm seeing this now in a .NET 4.5 test project referencing a project that multi-targets to the following:
`netstandard1.2;netstandard1.3;net45;win81;wpa81;MonoAndroid70;Xamarin.iOS10`

It's using the `netstandard1.2` version (the first in the list?) instead of the `net45` ver.

**Comment by onovotny** [comment]
@nguerrera I'm seeing this across the board for "regular" projects referencing a multi-targeted one:

https://github.com/onovotny/microsoft-authentication-library-for-dotnet/tree/1336a410808341c5ab09efa04b096b82f476ade7

In there, every project seems to be choosing the `netstandard1.2` version based on the path I see in the properties window when I select the reference. Those should all be choosing "closer" platform-specific versions.

**Comment by nguerrera** [comment]
@onovotny That's different and bizarre. Can you log a separate SDK bug and share repro steps?

**Comment by onovotny** [comment]
@nguerrera done: https://github.com/dotnet/sdk/issues/535

**Comment by Sarabeth-Jaffe-Microsoft** [comment]
@nguerrera -- have you made any progress on this fix? This is currently targeted for RC3 release.

**Comment by nguerrera** [comment]
I will re-validate the fix tomorrow and send a PR.

**Comment by onovotny** [comment]
This is still happening with RC3 for me.

**Comment by nguerrera** [comment]
Yes. It's not fixed yet. PR coming shortly.
