### ISSUE TITLE
msbuild output on .NET Core is not localized even if its satellites are present

### ISSUE THREAD

**Issue by nguerrera** [Microsoft/msbuild#1476]
## Repro steps:
* Use machine where CultureInfo.CurrentUICulture would pick up resources from fr/ folder
* Install recent VS 2017 Enterprise RC2 with .NET Core and Docker (preview) workload
* Copy C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\fr to C:\Program Files\dotnet\sdk\1.0.0-preview4-[build]\fr to mimic what a future localized CLI installation would do
* `dotnet msbuild /?`

## Expected result
* msbuild help is shown in French

## Actual result
* msbuild help is shown in English

@cdmihai 

Related: https://github.com/dotnet/cli/issues/5007

**Comment by cdmihai** [comment]
Does it work if you `chcp 65001`?

**Comment by nguerrera** [comment]
@cdmihai It does not work on `chcp 65001`. I think that code is #if'ed out of .NET Core, but I'm not sure. 

The same repro steps give french output from csc, but not msbuild.

**Comment by nguerrera** [comment]
@cdmihai Did anyone look at this? I am further seeing that my tasks satellites are not used successfully on CoreCLR. Interestingly, CurrentUICulture is fr-CA. Something is preventing the load from happening. I highly suspect it is the same issue but I haven't proven it.

cc @piotrpMSFT @srivatsn This is going to block localization of msbuild and SDK output using `dotnet`, which in turn will block the VS tenet.

**Comment by cdmihai** [comment]
.net core msbuild is not localized. Since it does not ship with VS, I don't think it has to, right? 

Regarding task localization, the core CLR "should" find and use them, unless .net core satellite resolution is different. Does fuslogvw work with the core CLR, so you can see what paths it probes?

**Comment by nguerrera** [comment]
It ships with VS in CLI
