### ISSUE TITLE
msbuild does not register code pages provider on .NET Core, which will cause garbled non-English text on Windows

### ISSUE THREAD

**Issue by nguerrera** [Microsoft/msbuild#1477]
See https://github.com/dotnet/corefx/issues/10054. Once we get msbuild satellites in CLI, we'll get bad output for text outside the ASCII range unless the user has set their console code page to 65001, which is not common and may cause them other problems.

I've asked the corefx team to reconsider putting the burden on every localized command line tool for this in https://github.com/dotnet/corefx/issues/14496, but we'll not likely get that in a CoreCLR that the CLI can depend upon in VS 2017.

Related: https://github.com/dotnet/cli/issues/5007

@cdmihai

**Comment by nguerrera** [comment]
See #1476 for repro steps. If you manage to get the French text displayed, the diacritics will likely be garbled because of this.

**Comment by cdmihai** [comment]
This is the fix right? https://github.com/dotnet/roslyn/issues/10785#issuecomment-238940601

**Comment by nguerrera** [comment]
@cdmihai Yes. :)

**Comment by cdmihai** [comment]
Waiting for https://github.com/dotnet/corefx/issues/14496 to stabilize.
