### ISSUE TITLE
ReferenceAssemblyRoot as an MSBuild property

### ISSUE THREAD

**Issue by natemcmaster** [Microsoft/msbuild#1478]
On non-Windows platforms, MSBuild can compile for .NET Framework if users have reference assemblies installed. By convention, MSBuild looks for these reference assemblies installed via Mono, or if the environment variable 'ReferenceAssemblyRoot' has been set to their location. 

If we could set 'ReferenceAssemblyRoot' as an MSBuild property, this would enable scenarios such as https://github.com/dotnet/corefx/issues/3934, which would allow us to distribute the .NET Framework reference assemblies as a NuGet package.

**Comment by borgdylan** [comment]
Does ```ReferenceAssemblyRoot``` work with mono installed assemblies if MSBuild is running under .NET Core?

**Comment by natemcmaster** [comment]
It appears that usage of ReferenceAssemblyRoot overrides the search for mono's reference assemblies. 
See https://github.com/Microsoft/msbuild/blob/699f5c6c92e9372ef5677c31dbbac6fa64d1aad5/src/Shared/FrameworkLocationHelper.cs#L847-L868

**Comment by natemcmaster** [comment]
I've learned since opening that you can set FrameworkPathOverride to point to .NET Framework ref assemblies.

**Comment by mfilippov** [comment]
@natemcmaster If you have more then one TFM in solution you can use property: "TargetFrameworkRootPath" to set base directory for ReferenceAssemblies. See in my commit https://github.com/Microsoft/msbuild/commit/8a08831d9975cadcee4820247b6605eb2eac3124

**Comment by jaredpar** [comment]
@natemcmaster @mfilippov that's the approach we take in Roslyn. We essentially ship the framework reference assemblies in a NuGet package and then set our `TargetFrameworkRootPath` to point into that NuGet. Allows us to build our desktop assets on all platforms. 

https://github.com/dotnet/roslyn/blob/master/build/Targets/Settings.props#L68

**Comment by natemcmaster** [comment]
Thanks!
