### ISSUE TITLE
ProjectRootElement.FullPath does not support case-only changes.

### ISSUE THREAD

**Issue by jviau** [microsoft/msbuild#1484]
[ProjectRootElement.FullPath](https://github.com/Microsoft/msbuild/blob/xplat/src/XMakeBuildEngine/Construction/ProjectRootElement.cs#L555) does not support case-only changes. This is an issue for xplat and also when renaming in Visual Studio.

**Comment by jeffkl** [comment]
Ideally our string comparer would use the same case sensitivity of the file system.  I'm not sure if that's easy to detect though.  I'm not sure why there's an optimization around case, maybe @AndyGerlicher knows?

**Comment by jviau** [comment]
The string comparer is fine for determining what extra work should be done, but it should not prevent being able to actually set that property when it is a case-only change.

**Comment by jeffkl** [comment]
@AndyGerlicher can I remove the case check?  There might be a perf implication but if the user renames a project, we should rename it right?

**Comment by danmosemsft** [comment]
I thought VS itself doesn't let you change case. You have to change the name to somtehing else temporarily.

**Comment by livarcocc** [comment]
Team Triage: We haven't heard of a lot of need for this so far (or any). Closing for now. If we end up needing this change, we can take a deeper look.
