### ISSUE TITLE
AL task invocation in GenerateSatelliteAssemblies attempts full signing when PublicSign is specified

### ISSUE THREAD

**Issue by nguerrera** [Microsoft/msbuild#1490]
### Repro steps
* File -> New Project -> Console Application (.NET Framework)

* Add localized resource file (e.g. String.fr.resx).

* Properties -> Signature:
  * check sign assembly
  * add new snk (w/o password)
  * check delay signing option

* Edit project file and change DelaySign to PublicSign

* Drop to command line and strip the private key from the snk
  * sn -p file.snk file.public.snk
  * del file.snk
  * ren file.public.snk file.snk

* Build 

### Expected result

Build succeeds and my main assembly and satellite are both public-signed.

### Actual result
```
Erreur		Le fichier de clé '..\file.snk' ne comporte pas la clé privée nécessaire à la signature
```

(Translation: "The key file '...\file.snk' does not contain the private key necessary for signing.")

@jaredpar @agocke @cdmihai

**Comment by nguerrera** [comment]
The AL.exe based satellite generation is already problematic because it does not work on CoreCLR. For that, we had to roll our own based on Roslyn in the SDK. I think a better long-term solution would be to have one cross-platform task that compiles the satellite assembly with Csc instead of AL. That way, when a new feature like public signing that needs to work for satellites comes in to the compiler, it will be trivial.

**Comment by nguerrera** [comment]
Less than perfect workaround to *delay-sign* satellites while public-signing main assembly:

``` XML
<!-- 
    Workaround https://github.com/Microsoft/msbuild/issues/1490 (lack of support for public-signing satellites) by 
    delay-signing satellite assemblies when main assembly is public-signed.
-->
<Target Name="PrepareToDelaySignSatelliteAssemblies" BeforeTargets="GenerateSatelliteAssemblies">
  <PropertyGroup>
    <_DelaySignMainAssembly>$(DelaySign)</_DelaySignMainAssembly>
    <DelaySign Condition="'$(PublicSign)' == 'true'">true</DelaySign>
  </PropertyGroup>
</Target>
<Target Name="CleanupAfterDelaySigningSatelliteAssemblies" AfterTargets="GenerateSatelliteAssemblies">
  <PropertyGroup>
    <DelaySign>$(_DelaySignMainAssembly)</DelaySign>
  </PropertyGroup>
</Target>
```

**Comment by paulvanbrenk** [comment]
@nguerrera I assume this causes load failures when the main assembly tries to load the satellite assemblies?

**Comment by nguerrera** [comment]
@jaredpar

**Comment by nguerrera** [comment]
Closing against #350. If we move to csc in common targets for satellite generation, and copy the implementation from Microsoft.NET.Sdk, this will get fixed. AL is never getting fixed.
