### ISSUE TITLE
Issue with "msbuild /t:pack"

### ISSUE THREAD

**Issue by feliwir** [microsoft/msbuild#1494]
Hello everyone,
i am using Visual Studio 2017 with the latest updates (from december), I am trying to create a nuget package following this guide: https://docs.nuget.org/ndocs/guides/create-net-standard-packages-vs2017
The problem is that the command: "msbuild /t:pack /p:Configuration=Release" fails, saying that target "pack" doesn't exist. Shouldn't the target be available? My project file looks like this:
https://gist.github.com/feliwir/ac27a8f1420454d490bc73ad9e257da2

**Comment by feliwir** [comment]
Any updates on this?

**Comment by aL3891** [comment]
are you running `dotnet msbuild `or just `msbuild`?

**Comment by feliwir** [comment]
Just msbuild

**Comment by aL3891** [comment]
Do you get the same error with `dotnet msbuild /t:pack` (or `dotnet pack`)
This might be a documentation bug

**Comment by jeffkl** [comment]
The `Pack` target comes from the new .NET Core SDK.  From the command-line, are you building a project or solution?  If you're building a solution, this won't work until my PR #1497 is in.  If you're building a project, then maybe @nguerrera would know where to start narrowing down a problem?
