### ISSUE TITLE
Nuget dependencies content is not been added for dotnet core projects - VS2017

### ISSUE THREAD

**Issue by roysanchez** [Microsoft/msbuild#1496]
When importing a package that adds content to the project it completes without displaying any errors but doesn't add the files.

Steps to reproduce:
1. Create a project with any of the templates for dotnetcore (Console/Class Library/Web)
2. Add a nuget package with content, ex: _jQuery_ with ` Install-Package jQuery`.

The reference is added correctly but the content is no added to the project.

Note: It works correctly with the classic projects.

**Comment by jeffkl** [comment]
@nguerrera or @emgarten should know who would own this.

**Comment by nguerrera** [comment]
@natidea

**Comment by emgarten** [comment]
@roysanchez  Dotnet core does not support the ``Content/`` folder used in JQuery, this was previously installed directly into the project using Visual Studio and no longer works when restoring packages cross platform from the command line.  Packages must move to using ``ContentFiles/`` which is supported for both project.json and PackageReference projects.

**Comment by roysanchez** [comment]
@emgarten I used `jQuery` only as an example, I got this error trying to add an internal dependency to a new project and not seeing the files.

Is there a specific way that it needs to be handled, I tried the following configurations and none seem to work: [gist of the csproj and generated nuspec](https://gist.github.com/roysanchez/a3b8dd9b58eee26399be016520165f2e)

**Comment by emgarten** [comment]
ContentFiles support was recently added to NuGet but it isn't in the current dotnet CLI release. Once it is you will see items under contentFiles in the generates props file for the project.

**Comment by roysanchez** [comment]
@emgarten Nice, should I close this or wait for the release?

**Comment by emgarten** [comment]
@roysanchez I think this can be closed, and then watch for it in the next release. thanks!

**Comment by samcoga** [comment]
@roysanchez @emgarten Is this issue resolved? I'm including a nuget on my dotnet core project using VS2017 and I see the contentFiles inside the nuget, but I can't manage to copy them into my local project.
