### ISSUE TITLE
Support wildcard patterns matching folders starting with "." without matching items with relative paths outside of the project folder

### ISSUE THREAD

**Issue by dsplaisted** [microsoft/msbuild#1498]
In the .NET SDK, we'd like to automatically exclude folders such as `.vs` and `.git` from items such as `Compile` and `Content`.  I tried doing this by having the equivalent of the following in the .targets files:

```xml
<Compile Remove="**/.*/**" />
```

However, this ended up matching and thus removing items in relative folders outside the project root, for example `..\Shared\Shared.cs`.

It would be nice to have a way to express a wildcard that matches folder names starting with ".", but doesn't match the relative portions ("..") of paths.

Here's a simple repro project: [RelativeWildcard.zip](https://github.com/Microsoft/msbuild/files/662480/RelativeWildcard.zip)

```xml
<Project DefaultTargets="Build">
  <ItemGroup>
    <Compile Include="**\*.cs" />
    <Compile Include="..\Shared\**\*.cs" />
    <Compile Remove="**/.*/**" />
  </ItemGroup>
  <Target Name="Build">
    <Message Text="@(Compile)" />
  </Target>
</Project>
```

**Comment by am11** [comment]
The regex way is to escape the period: `**/\.*/**`.

In node-glob, there is an explicit option `dot` which to match dot at first position: https://github.com/isaacs/node-glob#dots

**Comment by miloush** [comment]
I doubt Regex is used for matching here. I think the match is working fine, the problem is that `.*` naturally matches `.` and `..`. Not sure how to get around this, maybe the `.` and `..` directories could be explicitly excluded from matches? Any solution is going to be a breaking change, but that's likely justifiable here.

**Comment by rainersigwald** [comment]
Team triage: this behavior is not great, but we're worried about breaking folks now that we've shipped with this behavior for a long time.
