### ISSUE TITLE
Update CI for CoreCLR Builds

### ISSUE THREAD

**Issue by AndyGerlicher** [Microsoft/msbuild#150]

**Comment by AndyGerlicher** [comment]
Moving to Sprint 90. This should happen after #6 so the CI should be updated to build and test.

**Comment by AndyGerlicher** [comment]
This is (nearly) done for xplat full framework. Need to run/test with coreclr.

**Comment by dsplaisted** [comment]
@rainersigwald Can we close this issue?  There's no description so I'm not sure exactly what it's supposed to cover.

**Comment by dsplaisted** [comment]
Given that the CI build is working for .NET Core in xplat, and #342 covers also running it for full framework, I think this issue can be closed.
