### ISSUE TITLE
Mono not installed on the OSX CI servers

### ISSUE THREAD

**Issue by radical** [Microsoft/msbuild#1501]
Mono is not available on the OSX CI servers. `which mono` returns `''`, causing build failures (https://ci2.dot.net/job/Microsoft_msbuild/job/master/job/_OSX_Mono_prtest/4/console).

**Comment by cdmihai** [comment]
@mmitche 
How can we install mono on the build machines (linux and osx)? Can we `sudo apt-get install` it ourselves as part of the build, or is there a process to get mono installed on everything?

A fallback plan would be for our build process to setup an app-local installation of mono (just unzipping stuff and moving it around). @radical how easy is it to do this?

**Comment by mmitche** [comment]
@cdmihai I thought msbuild was hosted on .NET Core now?  Changing this on the OSX machines is a bit more involved.  Changing it on linux is easier.

What kind of cadence would you need updates?  Faster cadences should install applocal (you may even be able to do this with brew/apt-get) so that updates are easy and can be checked by PR.

**Comment by radical** [comment]
We can install it from the package found [here](http://www.mono-project.com/download/) : https://download.mono-project.com/archive/4.6.2/macos-10-universal/MonoFramework-MDK-4.6.2.7.macos10.xamarin.universal.pkg .

On a usual OSX box, simply installing the pkg will be enough.

**Comment by radical** [comment]
re:app-local, that might need to be tested. The mono OSX pkg/installer actually does some more "work"(moving things around etc), which a plain source build might not. So, I would say that we should try to get the pkg installed.

**Comment by mmitche** [comment]
What about update cadence?  And timeframe for getting this on the boxes.

**Comment by cdmihai** [comment]
The timeframe would be as soon as possible, since our current mono CI jobs are failing.

@radical: how often would we need to update mono?

**Comment by radical** [comment]
re:cadence, we shouldn't need to update with every new mono release. Only, when there is some major change that msbuild's build depends on, would we require an update. OTOH, it would be good to not fall, like, 2 releases behind. Each stable release seems to be roughly 4-6months apart.

**Comment by radical** [comment]
Also, the `Ubuntu 16.04` boxes are missing mono too.

**Comment by mmitche** [comment]
@radical Gotcha.  I was under the impression that msbuild didn't have mono dependencies any longer (dependent on .NET Core now).  Is this something different?

**Comment by radical** [comment]
@mmitche we are using this for generating a build specifically for mono, using mono, which has some differences from a CoreCLR targeting build. For example, mono build has support for fallback search paths for certain properties like `MSBuildExtensionsPath*`, which is configured via app.config . Mono builds support app.config, but CoreCLR builds do not.

**Comment by mmitche** [comment]
@radical Thanks for the info.  File an issue to get this done.  Shouldn't be much work.  The only thing is that we do want to avoid cases where could accidentally pollute a core environment with mono installed (and on the pathn).  Any risk there?  Colliding binary names, etc?

**Comment by radical** [comment]
Where should I file an issue?

So, in the OSX case, it will install mono to `/Library/Frameworks/Mono.framework/Versions/4.6.2` and it will probably update `/Library/Frameworks/Mono.framework/Versions/Current`. But AFAICS, there is no mono installed (nothing in `$PATH` at least) at all, so, it should not pollute anything.

For the Ubuntu 16.04 case, again, mono doesn't seem to be installed, so it should not be polluting anything.

(I'm still trying to look at the Ubuntu 14.04 case, which was working and then a few hours later started behaving as if the installation was, maybe, corrupted.)

**Comment by mmitche** [comment]
It's likely the 14.04 mono installation is very old.  I filed an issue on our internal engineering tracking.  THanks!

**Comment by radical** [comment]
@mmitche awesome, thank you! Could the 14.04 mono installation be updated too? :)

**Comment by mmitche** [comment]
@radical Mono now available on the macs

**Comment by jeffkl** [comment]
Thanks @mmitche.  

@radical I've started a build and it appears to be working: https://ci2.dot.net/job/Microsoft_msbuild/job/master/job/_OSX_Mono_prtest/26/console

Can you verify?

**Comment by radical** [comment]
Thanks @mmitche !
@jeffkl I'll be back at work on Monday and should be able to verify and fix any issues then.

**Comment by akoeplinger** [comment]
@mmitche that's using Mono 4.4 which is our previous stable release, where did you get this from? http://www.mono-project.com/download/ should have the latest version.

**Comment by mmitche** [comment]
On OSX that was the latest homebrew version, which is what was indicated above.  Well, crap....I guess that was wasted.

**Comment by akoeplinger** [comment]
@mmitche https://github.com/Microsoft/msbuild/issues/1501#issuecomment-268363205 indicated we'd prefer the official pkg installer 😄 

We don't maintain the homebrew version, it is done by some community member afaik though that one seems to be at the correct Mono 4.6 version too according to `brew info mono` here. Maybe your homebrew was outdated?

I suppose the homebrew version should work too so if it's easier to upgrade the existing instead of using the .pkg that'd be awesome 👍

**Comment by mfilippov** [comment]
@akoeplinger Current mono version in homebrew 4.6.2.7 I try to update version as soon as Xamarin deploy tarball archive to download.mono-project.com

**Comment by akoeplinger** [comment]
@mfilippov cool, thanks :) The tarballs are uploaded whenever the Linux packages are uploaded, e.g. tarballs for 4.6.2.16 which was released a few days ago are here: https://download.mono-project.com/sources/mono/mono-4.6.2.16.tar.bz2

**Comment by mfilippov** [comment]
@akoeplinger Brew package already updated thanks.

**Comment by mmitche** [comment]
Alright should be updated (needed a brew update and brew upgrade mono).  Try now.

**Comment by jeffkl** [comment]
Running here: https://ci2.dot.net/job/Microsoft_msbuild/job/master/job/_OSX_Mono_prtest/39/

**Comment by jeffkl** [comment]
Okay the build failed because some unit tests but I'm closing this issue for now since Mono is now installed.

Thanks @mmitche!
