### ISSUE TITLE
Build is broken for building .NET Core on a Mac

### ISSUE THREAD

**Issue by chris1248** [Microsoft/msbuild#1505]
Having loved using msbuild on windows, I wanted to give it a go on my Mac this morning. So I thought I'd try it on .NET Core.

So attempting to run this:

`./cibuild.sh --host CoreCLR`

gave me some cryptic (pun) errors:

> Installing dotnet cli...
> Restoring BuildTools version 1.0.27-prerelease-00927-05...
> The type initializer for 'Crypto' threw an exception.
> ERROR: Could not restore build tools correctly. See '/Users/cjohnson/code/msbuild/init-tools.log' for more details.1
> Initializing BuildTools...
> /Users/cjohnson/code/msbuild/init-tools.sh: line 122: /Users/cjohnson/code/msbuild/packages/Microsoft.DotNet.BuildTools/1.0.27-prerelease-00927-05/lib/init-tools.sh: No such file or directory
> ERROR: An error occured when trying to initialize the tools. Please check '/Users/cjohnson/code/msbuild/init-tools.log' for more details.1

The log file was pretty minimal in it's output:

> Running: /Users/cjohnson/code/msbuild/init-tools.sh
> Installing 'https://dotnetcli.blob.core.windows.net/dotnet/Sdk/1.0.0-preview3-003686/dotnet-dev-osx-x64.1.0.0-preview3-003686.tar.gz' to '/Users/cjohnson/code/msbuild/Tools/dotnetcli/dotnet.tar'
> Running: /Users/cjohnson/code/msbuild/Tools/dotnetcli/dotnet restore "/Users/cjohnson/code/msbuild/Tools/1.0.27-prerelease-00927-05/project.json" --no-cache --packages /Users/cjohnson/code/msbuild/packages --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json --legacy-packages-directory
> Running: /Users/cjohnson/code/msbuild/packages/Microsoft.DotNet.BuildTools/1.0.27-prerelease-00927-05/lib/init-tools.sh /Users/cjohnson/code/msbuild /Users/cjohnson/code/msbuild/Tools/dotnetcli/dotnet /Users/cjohnson/code/msbuild/Tools

Am I missing something?

**Comment by RichiCoder1** [comment]
Random person here, but did you make sure to follow the pre-reqs [listed here](https://github.com/Microsoft/msbuild/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild#unix)?

**Comment by chris1248** [comment]
yeah, makes no difference. Still get the same crypto error.

**Comment by chris1248** [comment]
Those instructors were not complete:
These are much better:
```brew update
brew install openssl
mkdir -p /usr/local/lib
ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/
ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/```
