### ISSUE TITLE
Do not crash when a TaskFactory returns a null TaskType

### ISSUE THREAD

**Issue by ulrichb** [Microsoft/msbuild#1508]
When inspecting the MSBuild error reported in [this issue](https://youtrack.jetbrains.com/issue/RSRP-462378), the most exhausting part was to identify which value in `TaskExecutionHost.FindTaskInRegistry` was actually `null`. 

It was `TaskFactory.TaskType`, and the `.FullName`-access threw the `NullReferenceException` (see  [TaskExecutionHost.cs, line 987](https://github.com/Microsoft/msbuild/blob/cb8c727a898e4439a3cd18f329504e436b0b7c00/src/XMakeBuildEngine/BackEnd/TaskExecutionHost/TaskExecutionHost.cs#L987)), which crashed MSBuild with _"error MSB1025: An internal failure occurred while running MSBuild"_.

Please add a null-check before the `.FullName`-access to improve debuggging when a `TaskFactory` behaves wrong.

**Comment by danmosemsft** [comment]
The title should be "Do not crash when a TaskFactory returns a null TaskType"
