### ISSUE TITLE
When BaseIntermediateOutputPath is overridden in a project after importing common props, build in VS displays the error  error: "BaseIntermediateOutputPath must end with a trailing slash."

### ISSUE THREAD

**Issue by srdjanjovcic** [Microsoft/msbuild#1509]
1. Create a C# UWP project;
2. Edit project and add <BaseIntermediateOutputPath>obj\x86\Debug</BaseIntermediateOutputPath> under <PropertyGroup> for currently selected configuration/platform;
3. Rebuild the project.

EXPECTED: 

4. Builds fine.

ACTUAL:

4. Fails with error: "BaseIntermediateOutputPath must end with a trailing slash."

It seems that is introduced with commit [862ce61](https://github.com/Microsoft/msbuild/commit/862ce619a23877cbfad54fd4acd547ef92f499b3)

**Comment by jeffkl** [comment]
I have confirmed that this is a bug.  This project:

``` xml
Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildToolsPath)\Microsoft.Common.props" />

  <PropertyGroup>
    <BaseIntermediateOutputPath>obj\x86\Debug</BaseIntermediateOutputPath>
  </PropertyGroup>

  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

Results in an error:
```
Microsoft.Common.CurrentVersion.targets(743,5): error : The BaseIntermediateOutputPath must end with a trailing slash.
```
We should probably add this back to Microsoft.Common.CurrentVersion.targets:
```xml
<BaseIntermediateOutputPath Condition="!HasTrailingSlash('$(BaseIntermediateOutputPath)')">$(BaseIntermediateOutputPath)\</BaseIntermediateOutputPath>
```

We should also add a unit test to ensure this doesn't regress again.

**Comment by jbevain** [comment]
It would be worth auditing all impacted properties, not only BaseIntermadiateOutputPath might be affected. UWP projects generated by a previous version of Unity also fail to build due to OutputPath missing a trailing backslash with 2017.
