### ISSUE TITLE
dotnet.glob

### ISSUE THREAD

**Issue by dazinator** [Microsoft/msbuild#1521]
Hello,

Just wondered if you would perhaps consider using [dotnet.glob](https://github.com/dazinator/DotNet.Glob) for your globbing needs. It doesn't use Regex, and has been written for high performance glob matching. 
So many different projects and cli tools are now requiring a decent glob matching solution, I thought it might be good to consolidate this effort in a seperate open source library.

**Comment by rainersigwald** [comment]
I like the idea of using a common globbing library, and I'd definitely want to use one if we were starting from scratch today.

But MSBuild has 15 years of backward compat to consider, so we probably can't switch away from our current, custom implementation. And a common library probably doesn't want our specific behavior. So I don't think this is achievable in the foreseeable future.
