### ISSUE TITLE
Compat: BaseIntermediateOutputPath might not be respected in some cases

### ISSUE THREAD

**Issue by davkean** [Microsoft/msbuild#1525]
Thought you might want to be aware of this, but in Roslyn/ProjectSystem's settings.targets (which occurs *before* common.targets), we have the following:

``` XML
  <PropertyGroup>
    <BaseIntermediateOutputPath Condition="'$(BaseIntermediateOutputPath)' == ''">$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)\..\..\bin\obj\$(MSBuildProjectName)'))\</BaseIntermediateOutputPath>
  </PropertyGroup>
```

This used to set the base intermediate directory, unless an individual project overwrote it. 

In recent builds of MSBuild, however, we now respect the base intermediate directory ("obj\") that comes from Microsoft.Common.props. This means that by upgrading to MSBuild 15, our build output has now changed.

**Comment by jeffkl** [comment]
@AndyGerlicher We'll need to put this in release notes, it should probably be considered a "breaking change"

**Comment by tomasr** [comment]
Just ran into this bug with https://github.com/Microsoft/ApplicationInsights-SDK-Labs/tree/master/WCF. Not only did it break the build, it causes VS2017 to modify the project files (.csproj) when the solution is opened to add settings for `<IntermediateOutputPath>` to the user's temp folder.

**Comment by SergeyKanzhelev** [comment]
What would be the suggested fix for this breaking change?

**Comment by jeffkl** [comment]
We added a warning in 15.8 to tell users that they should set this property in an early import like Directory.Build.props

https://github.com/Microsoft/msbuild/pull/3059
