### ISSUE TITLE
Builds randomly fail with no errors

### ISSUE THREAD

**Issue by davkean** [microsoft/msbuild#1526]
Build: 26107.1.d15prerel.

Due to broken NuGet restore in 26107.1.d15prerel, I've been running a lot of command-line builds today. Now, about 10 occasions of running 10s of builds, I've had them fail for a reason that I cannot understand. 
If they fail, and then I rerun, it immediately succeeds.

Here's an example of a build that failed:
https://gist.github.com/davkean/4b8973e083683d6d614cde527f79c41b

Here's an example of the subsequent build that succeeded:

TBD - this ended up being too big, see below for another successful build.

In this case there were warnings during the build, but I've seen cases were its also failed with zero warnings/errors:

```
Build FAILED.

                   "E:\project-system2\build\build.proj" (Build target) (1) ->
                   (RestorePackages target) -> 
                     E:\project-system2\build\Targets\VSL.Imports.targets(11,5): warning MSB4011: "C:\Users\davkean\.nuget\packages\MicroBuild.Core\0.2.0\build\MicroBuild.Core.props" cannot be imported again. It was already imported at "E:\project-system2\src\Dependencies\Toolset\Toolset.nuget.props (7,5)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\project-system2\src\Dependencies\Toolset\Toolset.csproj] [E:\project-system2\build\build.proj]
                     E:\project-system2\src\Dependencies\Toolset\Toolset.nuget.targets(7,5): warning MSB4011: "C:\Users\davkean\.nuget\packages\microbuild.core\0.2.0\build\MicroBuild.Core.targets" cannot be imported again. It was already imported at "E:\project-system2\build\Targets\VSL.Imports.targets (12,5)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\project-system2\src\Dependencies\Toolset\Toolset.csproj] [E:\project-system2\build\build.proj]


                     E:\project-system2\build\Targets\VSL.Imports.targets(11,5): warning MSB4011: "C:\Users\davkean\.nuget\packages\MicroBuild.Core\0.2.0\build\MicroBuild.Core.props" cannot be imported again. It was already imported at "E:\project-system2\src\Dependencies\Toolset\Toolset.nuget.props (7,5)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\project-system2\src\Dependencies\Toolset\Toolset.csproj]
                     E:\project-system2\src\Dependencies\Toolset\Toolset.nuget.targets(7,5): warning MSB4011: "C:\Users\davkean\.nuget\packages\microbuild.core\0.2.0\build\MicroBuild.Core.targets" cannot be imported again. It was already imported at "E:\project-system2\build\Targets\VSL.Imports.targets (12,5)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\project-system2\src\Dependencies\Toolset\Toolset.csproj]

    4 Warning(s)
    0 Error(s)
```

**Comment by davkean** [comment]
This looks similar to what I ran into: https://github.com/Microsoft/msbuild/issues/952 but this time with a "after" build log.

**Comment by davkean** [comment]
I found out more information, I hit this again:

1. It didn't appear to be random that it was failing, it appears to be after switching between branches that had msbuild changes
2. This time, it failed pretty consistently 5 times in a row but in different places (probably due to multi-proc builds):

Failure 1:
https://gist.github.com/davkean/3b29fb2b6f97d585af46ccf49003d9c2

Failure 2:
https://gist.github.com/davkean/87a14f8af688c86eb78ecafe6f3e61c9

Successful build
[Successful.zip](https://github.com/Microsoft/msbuild/files/692805/Successful.zip)

3. As *soon as* I passed "nodeReuse=false" it succeeded.

Spending some time trying to see if I can a consistent repro

**Comment by davkean** [comment]
I think I have a repro for this:

1. From a VS command prompt: `git clone https://github.com/davkean/roslyn-project-system.git`
2. `git checkout ba8d792`
3. `build.cmd`
4. In VS, open src\ProjectSystem.sln
5. In VS, build the solution
6. `git checkout 8ef0f8780f806c36b8e79d3e7bcfe4fc7467ccc3`
7. `build.cmd`

- Build fails with results similar to above -

**Comment by rainersigwald** [comment]
I can't get this to repro using your steps @davkean. Maybe something like "do something in VS that results in another build with changed projects" is missing?

**Comment by davkean** [comment]
Okay, let me spend five minutes repro'ing this, I just hit half an hour ago.

**Comment by livarcocc** [comment]
Given we could not repro it and it has been more than two years, I am going to close this. if you have updated repro steps, we can re-activate.
