### ISSUE TITLE
Recent changes to MSBuildExtensionsPath32 on Linux

### ISSUE THREAD

**Issue by jaredpar** [Microsoft/msbuild#1533]
I'm attempting to upgrade Roslyn to a new version of MSBuild:

- old: 15.1.0-preview-000370-00
- new: 15.1.0-preview-000458-02

Between these two versions it appears there was a change to `$(MSBuildExtensionsPath32)` on Linux.  Previously when the MSBuild NuGet packages were laid out on disk post publish and run under coreclr the property would have the value `<path-to-publish>/Extensions`.  In the new packages though the property is simply `<path-to-publish>`.

Is this a deliberate change from MSBuild?  

Relevant changes demonstrating this problem:

- Changing the NuGet package references: https://github.com/dotnet/roslyn/pull/16305/files#diff-1a76680faf56bc4e70addc531a86cafa
- Work around the property change : https://github.com/jaredpar/roslyn/commit/ee85b65eff117cfffd64508e36f910ba2faad075
- Suites passing after work around: https://ci.dot.net/job/dotnet_roslyn/job/master/job/linux_debug_prtest/1741/console

**Comment by akoeplinger** [comment]
Looks like https://github.com/Microsoft/msbuild/pull/1336

**Comment by jaredpar** [comment]
Yes that looks like the PR.  Good catch.

**Comment by jeffkl** [comment]
We think this was an issue with the package `Microsoft.Portable.Targets` which was placing files in an Extensions folder.  I've published a new version of the package, `0.1.2-dev` with the Extensions folder removed.  This should fix the issue but there might be other packages which expand with an Extensions folder.  Let me know if something else is broken.

CC @agocke

**Comment by jeffkl** [comment]
@agocke If possible, can this be verified soon?  I'd like to close this issue out...

**Comment by jaredpar** [comment]
@jeffkl will try and verify tomorrow.  Was bogged down in our Dev15 switch until now (how I found this bug).

**Comment by jaredpar** [comment]
@jeffkl my local verification seems to be panning oout.  Going to submit a PR shortly.  Thanks for turning that around fast.

**Comment by jeffkl** [comment]
Awesome, great to hear @jaredpar.  Sorry we broke you!

**Comment by jaredpar** [comment]
No worries.  It happens :)
