### ISSUE TITLE
Reload post condition should enforce HasUnsavedChanged = false

### ISSUE THREAD

**Issue by cdmihai** [Microsoft/msbuild#1554]
The two Reload overloads that load from a file should make HasUnsavedChanged = false. This means incrementing the in-memory Version and then making _versionOnDisk = Version. This makes more sense because after a reload, all the evaluated Project objects depending on the PRE should be dirtied, but the actual PRE should have HasUnsavedChanged=false because it is up to date to the file system.

The Reload overload form an XmlReader should leave HasUnsavedChanges=true

**Comment by AndyGerlicher** [comment]
Team Triage:
Closing until this becomes a known issue.
