### ISSUE TITLE
Bad error when missing “include” attribute on item

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#1555]
[Public copy of internal bug [https://devdiv.visualstudio.com/DevDiv/MSBuild/_workitems?_a=edit&id=270144](270144)]

Step to reproduce:
1.       Create “x.proj” file(add this file in attachment)
2.       Copy it to “C:\aardvark\aardvark”
3.       Build “x.proj” using command “msbuild C:\aardvark\aardvark\x.proj”
 
Expected result: 
Build failed. The expected console message should be MSB4035: The required attribute "Include" is empty or missing from the element <type>.
 
Actual result:
Build failed, the console message is unexpected.

![image](https://cloud.githubusercontent.com/assets/3347530/21912249/57754a38-d8ea-11e6-824e-cef4abc031d3.png)

**Comment by rainersigwald** [comment]
From @jeffkl:

Create a new message in src\XMakeBuildEngine\Resources\Strings.resx

A required attribute Include, Exclude, or Remove is required.

Then update src\XMakeBuildEngine\Evaluation\ProjectParser.cs:346 to use th e new message.

**Comment by davkean** [comment]
> "A required attribute Include, Exclude, or Remove is required." 

That looks wrong, as this isn't valid syntax [yet](https://github.com/Microsoft/msbuild/issues/988) `<Compile Exclude="[pattern]"/>`
