### ISSUE TITLE
When trying to make hardlinks, Copy task emits lot of unnecessary high importance messages when hardlink creation fails.

### ISSUE THREAD

**Issue by srdjanjovcic** [Microsoft/msbuild#1564]
In latest released Visual Studio (2015), if you create UWP app packages for the store, Build output window is filled in with bunch of messages about failing to create hardlinks (expected, because those files are originating in Windows Installer-protected folders). Those are neither errors or warnings (because Copy falls back to regular copy, and everything is fine).

Repro:

1) Create a UWP C# app;
2) Project > Store > Create app packages for the store.
 
EXPECTED: 

3) Build succeeds without confusing messages in output window.

ACTUAL:

3) Build succeeds without errors or warnings in error list, but output window contains several messages about inability to use hardlinks:

 1>  Could not use a link to copy "C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.NET.CoreRuntime\1.1\.\AppX\ARM\Microsoft.NET.CoreRuntime.1.1.appx" to "C:\Projects\App1\AppPackages\App1_1.0.1.0_Debug_Test\Dependencies\ARM\Microsoft.NET.CoreRuntime.1.1.appx". Copying the file instead. Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

I have found that this is a regression from September, from commit [Merge copy task support for symlinks into xplat](https://github.com/Microsoft/msbuild/commit/5fda85e683b1ef93b867716395890eb8bab268c0), which changed verbosity of those messages from Normal to HighImportance.

I will submit a PR to revert those back to Normal importance.

**Comment by rainersigwald** [comment]
Sounds good, I can't think of a reason those should move to High. My guess is it was nice while debugging that change and never got changed back.

**Comment by srdjanjovcic** [comment]
@rainersigwald -- which branch I should submit PR against?

**Comment by rainersigwald** [comment]
@srdjanjovcic `xplat`, please.

**Comment by rainersigwald** [comment]
Leaving this open until we figure out what the process is for merging/porting the fix to the rtw branch.

**Comment by rainersigwald** [comment]
Merged to rtw branch.
