### ISSUE TITLE
ProjectRootElement.Save creates a file with a utf-16 header

### ISSUE THREAD

**Issue by 333fred** [Microsoft/msbuild#1573]
When we call `ProjectRootElement.Save(new StringWriter())`, the written output contains a UTF-16 header, even if the project file was loaded with UTF-8.

**Comment by AndyGerlicher** [comment]
StringWriter is UTF16 and there's no way to override. This is what I did this to get around it:
https://github.com/Microsoft/msbuild/blob/cb8c727a898e4439a3cd18f329504e436b0b7c00/src/Shared/EncodingStringWriter.cs#L15

**Comment by krwq** [comment]
@AndyGerlicher I believe StringWriter is meant to be used to write strings into the memory not to a file. The Encoding seems to be just "FYI - here is what we internally use" - in case we change underlying documentation. I believe you should be using StreamWriter instead.

For reference:
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System/IO/StringWriter.cs

**Comment by 333fred** [comment]
Thanks @AndyGerlicher, that appears to work for us. Closing this issue.
