### ISSUE TITLE
Put MSBuild sources on Index during microbuild

### ISSUE THREAD

**Issue by cdmihai** [microsoft/msbuild#1592]
MSBuild's sources on Index are stale. I don't think they have been updated since MSBuild moved to Github. To not confuse the rest of the organization that uses Index, we should update our microbuild to upload sources on Index.

**Comment by cdmihai** [comment]
Or maybe there's a web service we can call when a Pull Requests goes into the main branch.

**Comment by KirillOsenkov** [comment]
I can look into this in a couple of weeks.

**Comment by KirillOsenkov** [comment]
Here's another question: which branch should be uploaded? Which is the most useful branch to have on index? Unfortunately we can only have one.

**Comment by cdmihai** [comment]
Thanks!
Out current main branch is xplat. Post RTM though, we plan on making xplat the new master.

**Comment by jeffkl** [comment]
I had our sources put on http://source.dot.net, is that good enough?  Our current branch is xplat.

**Comment by cdmihai** [comment]
@jeffkl The problem is that most people search on Index, so we should keep all source sites up to date. Or remove sources entirely from the ones we don't want to support anymore, otherwise people will make wrong assumptions about the code.

**Comment by KirillOsenkov** [comment]
So I've excluded the old MSBuild sources from DevDiv and added the new sources from the xplat branch.

The remaining work is to automate updating the sources as part of the CI build, I can take care of this a bit later.

**Comment by rainersigwald** [comment]
That's awesome, @KirillOsenkov. `xplat` is probably the best branch for the long term. We may rename it at some point but not in the near future.

**Comment by KirillOsenkov** [comment]
This is now fixed
