### ISSUE TITLE
Import Project path when evaluated to more than 256 chars fails rather than skipping to import

### ISSUE THREAD

**Issue by shahabhijeet** [microsoft/msbuild#1613]
For e.g. let's assume here is an import as below

```xml
<PackageName>ReallyLongString</PackageName>
<Scope>Foo</Scope>
<Import Project="$(LibrarySourceFolder)\$(Scope)\**\*$(PackageName).nuget.proj" Condition=" '$(Scope)' != 'all' " />
```

If the entire path is less than 256 and unable to evaluate to a valid path, it skips to import.
But if the entire path exceeds 256, it errors out saying, cannot import and prints the unevaluated literal path.

Actual: Errors out and prints literal unevaluated path
Expected: Skip importing project even if the path exceeds 256
Have consistent behavior in both cases.

**Comment by rainersigwald** [comment]
This is a combination of #53 ("`MAX_PATH` exists") and #406 ("wildcard expansion returns the input when a recursive glob exceeds `MAX_PATH`").

**Comment by rainersigwald** [comment]
Closing since we have those other two issues.
