### ISSUE TITLE
Update construct seems to update all items regardless of match when run in target

### ISSUE THREAD

**Issue by nguerrera** [Microsoft/msbuild#1618]
``` XML
<Project>
  <ItemGroup>
     <X Include="A;B;C" />
     <X Update="B" Metadata="Just on B" />
     <X Update="NonExistent" Metadata="Useless" />
  </ItemGroup>

  <Target Name="Build">
    <Warning Text="Before in-target update: %(X.Identity) %(X.Metadata)" />
    
   <ItemGroup>
      <X Update="A" Metadata="Just on A" />
      <X Update="NonExistent" Metadata="Huh" />
   </ItemGroup>
      
   <Warning Text="After in-target update: %(X.Identity) %(X.Metadata)" />
 </Target>
</Project>
```

Expected after target runs:
* A has Metadata= "Just on A" and B has Metadata "Just on B", C has no Metadata=""

Actual:
* They all have Metadata="Huh"

```
C:\temp\test.proj(10,5): warning : Before in-target update: A
C:\temp\test.proj(10,5): warning : Before in-target update: B Just on B
C:\temp\test.proj(10,5): warning : Before in-target update: C
C:\temp\test.proj(17,4): warning : After in-target update: A Huh
C:\temp\test.proj(17,4): warning : After in-target update: B Huh
C:\temp\test.proj(17,4): warning : After in-target update: C Huh
```

@AndyGerlicher @rainersigwald

**Comment by davkean** [comment]
tag @cdmihai

**Comment by rainersigwald** [comment]
I think this is a bad interaction between metadata-as-attributes and the fact that items are handled differently in targets.

Update was possible before the `Update` attribute, but only in targets. Inside a target you can use the old form (set metadata as though in an `ItemDefinitionGroup`, batching over the items with conditions).

```xml
      <X Metadata="Just on A" Condition="'%(X.Identity)' == 'A'" />
      <X Metadata="Huh" Condition="'%(X.Identity)' == 'NonExistent'" />
```

That's the best workaround for this.

Surprising things:
* This isn't an error. We didn't implement Update attributes inside targets, and I would have expected this to report "invalid syntax". I suspect it's not because of metadata-as-attributes, but
* Update doesn't appear to actually be getting set as metadata. Maybe we're correctly rejecting it as a reserved not-eligible-for-as-attribute metadata name, but not pushing up an error?

**Comment by nguerrera** [comment]
This needs to at least be an error for RTW.

I have a case (investigating perf issue with GetTargetFrameworkProperties) where it is very difficult to express as a condition.

Basically, I get a item group back from `<MSBuild>` task where the items have OriginalItemSpec pointing back to the project items and I want to update the project items passed in with metadata returned.

I imagined something like this would work and read nicely:

``` XML
<MSBuild Projects="@(Projects)>
   <Output TaskParameter="TargetOutputs" ItemName="Y" />
</MSBuild>
<ItemGroup>
    <X Update="%(Y.OriginalItemSpec)">
        <Metadata>%(Y.Metadata)</Metadata>
   </X>
</ItemGroup>
```

Variants using conditions did not work out either:

``` XML
<X  Metadata="%(Y.Metadata)" Condition="%(X.Identity) == %(Y.OriginalItemSpec)" />
```

I'm still trying to wrap my head around https://github.com/Microsoft/msbuild/pull/1018#r78638528 and I can't get it to work. I'd love to find a readable expression of this pattern.

**Comment by nguerrera** [comment]
Btw, it does error out if I use Update="" saying Update can't be empty so it partially knows this is special and not metadata.

**Comment by rainersigwald** [comment]
Beat my head against this for quite a while. I think you should just write a Task to do this. The syntax you want wouldn't do what you expect either due to the vagaries of batching rules.

**Comment by nguerrera** [comment]
OK. I'll write a task. :) Still pushing for that error in RTW.

**Comment by cdmihai** [comment]
Included in  #1124

**Comment by nguerrera** [comment]
NOTE: This was closed because it's a subset of #1124, not because it was fixed.

**Comment by jimitndiaye** [comment]
> This needs to at least be an error for RTW.
> 
> I have a case (investigating perf issue with GetTargetFrameworkProperties) where it is very difficult to express as a condition.
> 
> Basically, I get a item group back from `<MSBuild>` task where the items have OriginalItemSpec pointing back to the project items and I want to update the project items passed in with metadata returned.
> 
> I imagined something like this would work and read nicely:
> 
> ```
> <MSBuild Projects="@(X)">
>    <Output TaskParameter="TargetOutputs" ItemName="Y" />
> </MSBuild>
> <ItemGroup>
>     <X Update="%(Y.OriginalItemSpec)">
>         <Metadata>%(Y.Metadata)</Metadata>
>    </X>
> </ItemGroup>
> ```
> 
> Variants using conditions did not work out either:
> 
> ```
> <X  Metadata="%(Y.Metadata)" Condition="%(X.Identity) == %(Y.OriginalItemSpec)" />
> ```
> 
> I'm still trying to wrap my head around [#1018 (comment)](https://github.com/Microsoft/msbuild/pull/1018#r78638528) and I can't get it to work. I'd love to find a readable expression of this pattern.

I'm trying to do exactly what @nguerrera is trying to do here with similar results.

**Comment by TFTomSun** [comment]
@jimitndiaye 
Here's an example:
```xml

 <Target Name="AddCustomAliases" BeforeTargets="ResolveAssemblyReferences">
    <Message Importance="high" Text="AddCustomAliases invoked"/>
    <Message Importance="high" Text="Reference.Identity: %(Reference.Identity)"/>
    <ItemGroup>
      <PackageReferenceWithoutAliases Include="@(PackageReference -> WithMetadataValue('Aliases','') )"/>
      <PackageReferenceWithAliases Include="@(PackageReference)" Exclude="@(PackageReferenceWithoutAliases)"/>
    </ItemGroup>
    <Message Importance="high" Text="PackageReferenceWithAliases.Identity: %(PackageReferenceWithAliases.Identity), Aliases: %(PackageReferenceWithAliases.Aliases)"/>
    <PropertyGroup>
      <PackageReferencesWithAliases>@(PackageReferenceWithAliases);</PackageReferencesWithAliases>
    </PropertyGroup>
    <ItemGroup>
      <NonPackageAssemblyReference Include="@(Reference -> WithMetadataValue('NuGetPackageId', ''))"/>
      <PackageAssemblyReference Include="@(Reference)" Exclude="@(NonPackageAssemblyReference)">
      </PackageAssemblyReference>
      <PackageAssemblyReferenceWithInfo Include="@(PackageAssemblyReference)">
        <NeedsAlias>$(PackageReferencesWithAliases.Contains('%(NuGetPackageId);'))</NeedsAlias>
      </PackageAssemblyReferenceWithInfo>
      <PackageAssemblyReferenceWithAliases Include="@(PackageAssemblyReferenceWithInfo -> WithMetadataValue('NeedsAlias', 'true'))">
      </PackageAssemblyReferenceWithAliases>
      <Reference Remove="@(PackageAssemblyReferenceWithAliases)"/>
      <Reference Include="@(PackageAssemblyReferenceWithAliases)">
        <Aliases>nonglobal</Aliases>
      </Reference>
    </ItemGroup>
  </Target>
```

**Comment by gulbanana** [comment]
I've just run across this and it was _extremely_ confusing.
