### ISSUE TITLE
.NET Core project reference debugger locking issue

### ISSUE THREAD

**Issue by maloo** [microsoft/msbuild#1625]
I have a solution w/ 3 projects. One asp.net core app, one library and one console app to test the asp.net app. Both apps share the library via project reference. When I start debugger on asp.net core server app it will compile the library dll and also LOCK it. When then starting debugger on the console app (same debugger session), the console app tries to build the library again (should this really be needed?).
1) Why is msbuild rebuilding the library that was just built successfully seconds ago?
2) Why are csproj project references pointing VS to files in obj\ folder so VS locks them during debugging of app referencing it?
Hard to say if this is a VS, msbuild or .net core issue ... or a combo.

Running VS2017RC from 26th of Jan

**Comment by rainersigwald** [comment]
Team triage: closing due to age. If you're still seeing this problem, please let us know and we can reactivate it.
