### ISSUE TITLE
.NET Core project reference from .NET app fails at runtime

### ISSUE THREAD

**Issue by maloo** [Microsoft/msbuild#1626]
Repro:
Create a .NET console app and a .NET core library targetting .net standard. (I also had to change to .NET 4.6.2 and .net standard 1.5) Add reference to library project in .net console app and run the app. This will fail with System.Runtime 4.1 load failure.

Workaround:
Manually add Netstandard.Library package to console app

Expected behavior:
If I add a project reference to a .net standard dll project I expect the package dependencies of that project to be picked up by msbuild. Having to pack/deploy a library as a nuget and reference the package is NOT the way to go for project references.

Version:
VS2017RC, 26th Jan

**Comment by cdmihai** [comment]
@davkean @srivatsn 

This sounds more like an SDK or project system issue. If that is the case, can you please re-open it on the better suited repo page?

**Comment by srivatsn** [comment]
This issue was moved to dotnet/sdk#757
