### ISSUE TITLE
AdditionalFiles are not listed in EvaluatedInclude for .NET core projects

### ISSUE THREAD

**Issue by aakash-johari** [Microsoft/msbuild#1628]
**Repro Steps:**

1. Create a .NET core project. [Content](https://gist.github.com/aakash-johari/e9ae3df712202fa58efd48e7ae8ac9c6) 
2. We're essentially doing the following in our code -
```
var project = new Microsoft.Build.Evaluation.Project(projectName);
var evaluatedIncludes = project.Items.Select(x => x.EvaluatedInclude);
```
We're doing this to find the additional files in the project. The reason to choose MSBuild over other possible solutions was that the additional files added to project have <Visible>False</Visible> attribute and other solutions cannot enumerate these files. This works perfectly fine with other .NET framework projects.

**Comment by jeffkl** [comment]
I was not able to repro this using a quick test app: https://github.com/jeffkl/MSBuild-NetCore/tree/master/src/Repro-1628

Can you share more details?

**Comment by aakash-johari** [comment]
Sorry. There was a confusion here. I debugged the issue further and found that the problem is with the Nuget package discovery. Will close this issue and open a bug on nuget.
