### ISSUE TITLE
Mark everything in legacy-compat-shim assemblies as [Obsolete]

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#1651]
`Microsoft.Build.Engine` ("OrcasEngine") and `Microsoft.Build.Conversion` have been deprecated compat-shim layers for many releases ("Orcas" was a codename for Visual Studio 2008, so they've been deprecated since ~2010), but they haven't been marked as such. We should mark everything as obsolete for v16 so that we can just delete all of that code for v17.

**Comment by cdmihai** [comment]
This looks like a fun over-the-weekend project with Roslyn :)
