### ISSUE TITLE
Tracking issues with new SDK

### ISSUE THREAD

**Issue by jeffkl** [Microsoft/msbuild#1660]
Tracking things found when dogfooding the new SDK

# Blocking Issues

# Non-block issues
1. Restore error when specifying two or more target frameworks (https://github.com/NuGet/Home/issues/4307)
  `Error occurred while restoring NuGet packages: The operation failed as details for project X could not be loaded.`
2. Can't override properties like OutputType in a .props file (https://github.com/dotnet/sdk/issues/850)
# Workarounds
A list of things we had to work around that we can undo after bugs are fixed

# Hacks
Hacks put in place to make progress that we should undo as we get a little further
1. Using BuildTools for signing and had to set `ToolsDir` and `BuildToolsTaskDir` and import `sign.targets`.

# Open Questions
A list of things we need to solve to make progress.

- [ ] How do we want to do signing?  Prefer not to use BuildTools anymore?
- [x] How to determine if we're building .NET Framework or .NET Core during the outer build.  Only seems to be set in `.targets`.
  This was solved by keying off of the property `TargetFramework` instead of `TargetFrameworkIdentifier`.  `TargetFramework` is something like `net46` so we'll need to be careful with conditions.  

# Needs Investigation
## Mono support 
Need to determine how/if this can support Mono.

Related to #1638 and #1639.

**Comment by rainersigwald** [comment]
For signing, using the SDK implies using Roslyn 2.0, which has `/publicsign+`. We should use that. We shouldn't need BuildTools for anything when we're all in on the SDK.
