### ISSUE TITLE
Almost empty Strings.resx fails GenerateResources in .NET Core MSBuild

### ISSUE THREAD

**Issue by tinchou** [Microsoft/msbuild#1661]
Copy from https://github.com/dotnet/buildtools/issues/1315

I'm writing [this PR](https://github.com/dotnet/corefx/pull/15646), and if you look at the OSX and Linux CI builds they fail with the following error, but the Windows build doesn't:

```
..../tools/Microsoft.Common.CurrentVersion.targets(2718,5): error MSB3554: Cannot write to the output file "..../bin/obj/Unix.AnyCPU.Debug/System.Data.Odbc/netcoreapp/Resources.Strings.resources". Positive number required. [..../src/System.Data.Odbc/src/System.Data.Odbc.csproj]
..../tools/Microsoft.Common.CurrentVersion.targets(2718,5): error MSB3554: Parameter name: bufferSize [.../src/System.Data.Odbc/src/System.Data.Odbc.csproj]
```

For it to work, I just have to add at the very end of the Strings.resx file one `<data>` element as:

```xml
  <data name="something" xml:space="preserve"><value>something.</value></data>
```

Having different behavior makes writing cross-platform code more difficult.

Thanks!

**Comment by Petermarcu** [comment]
This happens to me on Windows as well when doing things from the command-line. So the MSBuild that is part of the CLI has this bug, regardless of OS.

**Comment by Petermarcu** [comment]
This will be an issue for anyone trying to do CI for their projects using the CLI.

**Comment by rainersigwald** [comment]
Per .NET Core Tooling standup (JoC and @MattGertz), since there's a workaround this doesn't meet the RTW bar.

**Comment by Petermarcu** [comment]
I updated the title to make sure people know this is on all OS's from the command line.

**Comment by tinchou** [comment]
NP. I got confused because of our own CI setup.

**Comment by tannergooding** [comment]
Also being hit in Roslyn. For example: https://github.com/dotnet/roslyn/pull/18285 failed with it on this job: https://ci.dot.net/job/dotnet_roslyn/job/master/job/ubuntu_16_debug_prtest/1057/

**Comment by rainersigwald** [comment]
Using [AlmostEmptyResx.zip](https://github.com/Microsoft/msbuild/files/1099121/AlmostEmptyResx.zip), I can reproduce this on my machine with .NET Core SDK 1.0.4 (MSBuild 15.1.1012.6693), but not with .NET Core SDK 2.0.0-preview2-006479 (MSBuild 15.3.388.41745).

MSBuild didn't change, so I bet this is because the new SDK ships with the fix for https://github.com/dotnet/corefx/pull/19190.

Please comment here if you see this on a 2.0 `dotnet` and we can reopen and investigate.
