### ISSUE TITLE
Cross-Targeting "rebuild" doesn't cause Build target to run

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#1663]
In most projects, the Rebuild target is just

```xml
<Target Name="Rebuild"
        DependsOnTargets="Clean;Build" />
```

Or very similar.

In the "outer" build of a crosstargeting build, however, it's [defined differently](https://github.com/Microsoft/msbuild/blob/754c9d1da0380849dd74794b1cdc2f4a4a690f63/src/XMakeTasks/Microsoft.Common.CrossTargeting.targets#L99)

```xml
  <Target Name="Rebuild" DependsOnTargets="_SetRebuildInnerTarget;DispatchToInnerBuilds" />
  <Target Name="_SetRebuildInnerTarget">
    <PropertyGroup>
      <InnerTargets>Rebuild</InnerTargets>
    </PropertyGroup>
  </Target>
```

This forwards the "rebuild" command to each of the inner builds. That works fine, but it means that it's hard for a build extension to hook onto the outer build, because it's not guaranteed that the `Build` target will run. That caused problems like https://github.com/NuGet/Home/issues/4475, where an `AfterTargets="Build"` was (confusingly) not firing on rebuild.

**Comment by rainersigwald** [comment]
cc @nguerrera

**Comment by nguerrera** [comment]
This needs to be fixed at the same time as https://github.com/Microsoft/msbuild/issues/1065. Should we just have one issue noting both things that need to be addressed.

**Comment by rainersigwald** [comment]
Yes, definitely. Closing this as a dupe.
