### ISSUE TITLE
Add MessageImportance option to Touch Task

### ISSUE THREAD

**Issue by yuehuang010** [microsoft/msbuild#1668]
Hello, small feature request.
Touch task has no control of the importance level of the messages.  It is always set to "MessageImportance.Normal".  Please consider adding a property to change it.

msbuild/src/XMakeTasks/Touch.cs
Log.LogMessageFromResources(MessageImportance.Normal, "Touch.CreatingFile", file, "AlwaysCreate");
og.LogMessageFromResources(MessageImportance.Normal, "Touch.Touching", file);

Consider StandardOutputImportance property of Microsoft.Build.Tasks.ToolTaskExtension as an example.

**Comment by rainersigwald** [comment]
Team triage: this hasn't gotten any traction over the last 3 years so closing as won't-fix.
