### ISSUE TITLE
PROCESSOR_ARCHITECTURE is incorrectly set to "x86"

### ISSUE THREAD

**Issue by DJDoena** [microsoft/msbuild#1670]
Using MSBuild delivered with VS2015

My environment variable is set to

`PROCESSOR_ARCHITECTURE=AMD64`

My platform is set to "x64"

And yet `C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Common.props`

insists that `$(PROCESSOR_ARCHITECTURE)` is "x86" in line 118

`<PreferredToolArchitecture Condition="'$(PreferredToolArchitecture)' == '' and ('$(PROCESSOR_ARCHITECTURE)' == 'AMD64' and '$(Platform)' == 'x64')">x64</PreferredToolArchitecture>`

I know that `$(Platform)` is correct because if I do this in my project file it works:

`  <PropertyGroup  Condition="'$(Platform)'=='x64'">`
`    <PROCESSOR_ARCHITECTURE>AMD64</PROCESSOR_ARCHITECTURE>`
`  </PropertyGroup>`

**Comment by rainersigwald** [comment]
How are you launching the build? What does a diagnostic log say for `Environment at start of build:` in that environment?

Are you perhaps running an x86 instance of cmd.exe?

```
C:\Users\raines>set PROCESSOR_ARCHITECTURE
PROCESSOR_ARCHITECTURE=AMD64

C:\Users\raines>c:\Windows\SysWOW64\cmd.exe /c set PROCESSOR_ARCHITECTURE
PROCESSOR_ARCHITECTURE=x86
```

**Comment by DJDoena** [comment]
I run the "rebuild all" from a VS2015. My main problem is that the build includes the wrong set of SDK include directories (x86 instead of x64) and it took me a while debugging the variable settings within the msbuild props files to even find this.

**Comment by GitHubror** [comment]
Hi I am the originator of this issue.
As DJDoena reported the main problem is the calculation of the macro $(WindowsSDK_ExecutablePath) using the environment macro $(PROCESSOR_ARCHITECTURE). I guess that the platform of the current build should be used only to lead the loader for the executable into the correct folder. I have attached my project which is a assistant generated console project modified with a task to report macros related to this issue.
This project reports me the content of $(WindowsSDK_ExecutablePath):
```PROCESSOR_ARCHITECTURE = 'x86'
Platform = 'Win32' 
WindowsSDKToolArchitecture = 'Native32Bit'
WindowsSDK_ExecutablePath = 'C:\Program Files (x86)\Windows Kits\8.1\bin\x86;;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools'
```
This is the expected result for Win32. Now try to switch to x64 platform:
```PROCESSOR_ARCHITECTURE = 'x86'
Platform = 'x64' 
WindowsSDKToolArchitecture = 'Native32Bit'
WindowsSDK_ExecutablePath = 'C:\Program Files (x86)\Windows Kits\8.1\bin\x86;;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools'
```
As we can see the result of $(WindowsSDK_ExecutablePath) is the same.
@rainersigwald: Thanks for your explanation. It looks like VS uses the SysWOW64 environment running the MSBuild task.

[CheckEnvVariable.zip](https://github.com/Microsoft/msbuild/files/776420/CheckEnvVariable.zip)

**Comment by rainersigwald** [comment]
[extremely belatedly, sorry]

That's correct; Visual Studio and default MSBuild.exe are 32-bit applications subject to the WOW environment.
