### ISSUE TITLE
Self contained NET core app does not have execute permission set

### ISSUE THREAD

**Issue by MichaelSimons** [Microsoft/msbuild#1676]
1. `dotnet new`
1. `dotnet restore -r debian.8-x64`
1. `dotnet publish -r debian.8-x64 -o out`
1. `./out/app`

**Expected Results**
Application would run.  I would expect the executable placed in the out directory to have owner execute permission.

**Actual Results**
```
bash: ./out/app: Permission denied
```

**dotnet --info**
```
.NET Command Line Tools (2.0.0-alpha-004782)

Product Information:
 Version:            2.0.0-alpha-004782
 Commit SHA-1 hash:  da15d5435f

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0-alpha-004782/
```

**dotnet msbuild /version**
```
Microsoft (R) Build Engine version 15.2.2.21747
```

This appears to be a regression since msbuild 15.1.545.13942.

**Comment by rainersigwald** [comment]
@eerhardt Looks like something's funky in the 2.0 cli you started putting together. Have you changed the SDK at all, or does this seem more likely to be a CLI change?

**Comment by eerhardt** [comment]
See 

https://github.com/dotnet/corefx/issues/15516
https://github.com/NuGet/Home/issues/4424

Also the "note #2" of https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md#option-2-self-contained

This isn't an 'msbuild' bug.  It is a breaking change in corefx that needs to be fixed either in corefx, NuGet, or worked around in the dotnet/sdk (and everywhere else that consumes executables from NuGet packages on non-Windows machines).

**Comment by eerhardt** [comment]
FYI - this only happens when using "2.0" versions of the CLI (since it runs on .NET Core 2.0).
