### ISSUE TITLE
Question: What is the recommended install location for Mono MSBuild?

### ISSUE THREAD

**Issue by borgdylan** [Microsoft/msbuild#1693]
I need to build the Mono variant of MSBuild so I could target the ```netXY``` TFMs. Under which prefix should I install it, if it matters? Also, are there any Unix install scripts for MSBuild or will a manual xcopy be needed?

**Comment by borgdylan** [comment]
Also, the Mono build fails due to the dotnet.tar blob not being present on the blob storage account. Extraction fails since the document returned in an XML file with a warning rather than an actual archive.

**Comment by radical** [comment]
@borgdylan Try the branch at https://github.com/mono/msbuild/tree/xplat-c9 for now. This has some extra changes for Mono, which are not upstream yet. You can use the `install-mono-prefix.sh` script to install to a prefix. Install it in the same prefix as the Mono that you want to use it with.

**Comment by borgdylan** [comment]
@radical Thanks a lot! It will be going in ```/usr/local``` along with my build of mono.

**Comment by borgdylan** [comment]
One last question, is it safe to override the msbuild command that comes with .NET CLI to point to the MSBuild built from that branch so that I could use the new csproj stuff but also target mono?

**Comment by borgdylan** [comment]
The blob download issue also plagues the xplat-c9 branch. The msbuild bootstrap package downloads, but the CLI one does not.

**Comment by borgdylan** [comment]
I hope that the build is not using some blob storage that only the CI can access. That makes independent builds almost impossible without some sort of hackish fix.

**Comment by borgdylan** [comment]
Ping, does anyone have a way to fix the CLI download link? It's breaking all msbuild builds.

**Comment by borgdylan** [comment]
@radical I cannot build msbuild from that branch. I tried overriding the CLI used with the one I have installed to no success. Has anyone else tried to build it on his own machine from scratch?

**Comment by borgdylan** [comment]
Also, the mono CI links are dead :/ .
