### ISSUE TITLE
Add more flexibility for msbuild.rsp

### ISSUE THREAD

**Issue by danmosemsft** [microsoft/msbuild#1701]
## Motivation

It's a common scenario (maybe the most common) to build by just typing `msbuild.exe`. For example, in the various .NET repos, one builds from the root by typing `build.cmd` and then subsequently by typing `msbuild` in individual subfolders. 

That's quick and easy but means there's no opportunity to have default flags, such as a particular set of default loggers. Example: a logger that puts errors in msbuild.err, and another that puts errors in msbuild.wrn. Nobody wants to type those out each time.

MSBuild supports response files, but if you don't want to pass them explicitly (which would defeat the point) your only options are to (1) edit the official msbuild.rsp, which is typically locked down to admins and global to the machine or (2) put an msbuild.rsp next to the entrypoint project. The latter option means one next to every project, so you end up with hundreds of new files.

In each of those file you can put `@..\..\..\global.rsp`, so the actual settings were at least in one place, but it would be nice to eliminate those hundreds of msbuild.rsp files.

## Proposal
Analogous to the msbuild function `GetDirectoryNameOfFileAbove`, msbuild.exe should look for any file named msbuild.rsp not just in the folder of the first project, but in all the folders above up to the root. It would load the first found, if any.

If there's a concern this could cause surprising new behavior, it could simply be named `msbuild.local.rsp` or similar.

If we had such behavior, we would certainly use it in the .NET repos.

## Alternative
MSBuild could support an environment variable like MSBUILDEXTRARESPONSEFILE that would take a path. But this is clunky and requires ome kind of setup proces to set the envronment variable.

**Comment by rainersigwald** [comment]
microsoft/msbuild#2627 added support for an upward search for `Directory.Build.rsp`.
