### ISSUE TITLE
Can't build on Ubuntu 16.10

### ISSUE THREAD

**Issue by borgdylan** [Microsoft/msbuild#1702]
I couldn't manage a build on my Linux machine. Tools init always fails due to a bad blob url for dotnet.tar.

**Comment by radical** [comment]
Could you share the full log?

**Comment by borgdylan** [comment]
The init-tools log:
```
Running: /home/dylan/Desktop/git/mono-git/msbuild/init-tools.sh
Installing 'https://dotnetcli.blob.core.windows.net/dotnet/Sdk/1.0.0-preview3-003686/dotnet-dev-ubuntu.16.10-x64.1.0.0-preview3-003686.tar.gz' to '/home/dylan/Desktop/git/mono-git/msbuild/Tools/dotnetcli/dotnet.tar'
Running: /home/dylan/Desktop/git/mono-git/msbuild/Tools/dotnetcli/dotnet restore "/home/dylan/Desktop/git/mono-git/msbuild/Tools/1.0.27-prerelease-00927-05/project.json" --no-cache --packages /home/dylan/Desktop/git/mono-git/msbuild/packages --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json --legacy-packages-directory
Running: /home/dylan/Desktop/git/mono-git/msbuild/packages/Microsoft.DotNet.BuildTools/1.0.27-prerelease-00927-05/lib/init-tools.sh /home/dylan/Desktop/git/mono-git/msbuild /home/dylan/Desktop/git/mono-git/msbuild/Tools/dotnetcli/dotnet /home/dylan/Desktop/git/mono-git/msbuild/Tools
```

**Comment by borgdylan** [comment]
The console:
```
$ ./cibuild.sh --target Mono
** Using mono from /usr/local/bin/mono
Mono JIT compiler version 4.9.1 (master/7bfb9bc Mon 13 Feb 21:30:47 CET 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)
Installing dotnet cli...
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
Restoring BuildTools version 1.0.27-prerelease-00927-05...
/home/dylan/Desktop/git/mono-git/msbuild/init-tools.sh: line 116: /home/dylan/Desktop/git/mono-git/msbuild/Tools/dotnetcli/dotnet: No such file or directory
ERROR: Could not restore build tools correctly. See '/home/dylan/Desktop/git/mono-git/msbuild/init-tools.log' for more details.
============= /home/dylan/Desktop/git/mono-git/msbuild/init-tools.log ===========
Running: /home/dylan/Desktop/git/mono-git/msbuild/init-tools.sh
Installing 'https://dotnetcli.blob.core.windows.net/dotnet/Sdk/1.0.0-preview3-003686/dotnet-dev-ubuntu.16.10-x64.1.0.0-preview3-003686.tar.gz' to '/home/dylan/Desktop/git/mono-git/msbuild/Tools/dotnetcli/dotnet.tar'
Running: /home/dylan/Desktop/git/mono-git/msbuild/Tools/dotnetcli/dotnet restore "/home/dylan/Desktop/git/mono-git/msbuild/Tools/1.0.27-prerelease-00927-05/project.json" --no-cache --packages /home/dylan/Desktop/git/mono-git/msbuild/packages --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json --legacy-packages-directory
============= end of /home/dylan/Desktop/git/mono-git/msbuild/init-tools.log ===========
Initializing BuildTools...
/home/dylan/Desktop/git/mono-git/msbuild/init-tools.sh: line 127: /home/dylan/Desktop/git/mono-git/msbuild/packages/Microsoft.DotNet.BuildTools/1.0.27-prerelease-00927-05/lib/init-tools.sh: No such file or directory
ERROR: An error occured when trying to initialize the tools. Please check '/home/dylan/Desktop/git/mono-git/msbuild/init-tools.log' for more details.1
```

**Comment by borgdylan** [comment]
dotnet.tar is a blob storage error response and not an archive:
```
$ cat dotnet.tar
<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:f99ae65c-0001-0017-73f8-86a6e6000000
Time:2017-02-14T19:28:41.8037363Z</Message></Error>
```

**Comment by borgdylan** [comment]
Also, the CI may be caching the tools, that's why it is passing. It gave me a false outlook on the actual state of the build.

**Comment by radical** [comment]
https://dotnetcli.blob.core.windows.net/dotnet/Sdk/1.0.0-preview3-003686/dotnet-dev-ubuntu.16.10-x64.1.0.0-preview3-003686.tar.gz - this seems to be missing now. Though the corresponding copy for OSX does exist. `1.0.0-rc4*` is available now. Maybe we can move to that now. Hopefully it shouldn't affect any other builds! @rainersigwald ?

**Comment by rainersigwald** [comment]
I don't think we can move to latest, due to the project.json/MSBuild switchover and some other factors. I hoped we could move to the released version of preview3, 004056, but it is post-MSBuild-switchover and failed during our restore step.

@blackdwarf Is there a build of cli between `preview3-003686` (our current, evidently deleted) and `preview3-004056` (the first? MSBuild-only build) that's still available for all OSes? Is there a way for me to tell that on my own?

cc @jeffkl 

The error I get on moving to a more recent build is:
```
MSBUILD : error MSB1001: Unknown switch. [C:\src\msbuild\build.proj]
  Switch: --legacy-packages-directory

  For switch syntax, type "MSBuild /help"
C:\src\msbuild\src\.nuget\packageLoad.targets(41,5): error MSB3073: The command ""C:\src\msbuild\Tools\dotnetcli/dotnet
.exe" restore --legacy-packages-directory --packages C:\src\msbuild\packages\ "C:\src\msbuild\src\.nuget\project.json""
 exited with code 1. [C:\src\msbuild\build.proj]
```

**Comment by piotrpMSFT** [comment]
@rainersigwald 3686 is alive and well. CLI didn't, and still doesn't, produce Ubuntu 16.10 builds thus far [closest is 16.04]. These builds will be coming soon [by 1.0.0 RTM I hope].

**Comment by borgdylan** [comment]
So I can hack my way to a build by tricking the build into think that I have 16.04 instead of 16.10?

**Comment by borgdylan** [comment]
Seems to be working so far. Thanks @piotrpMSFT for the insight.

**Comment by piotrpMSFT** [comment]
:shipit: haha

**Comment by borgdylan** [comment]
The patch simply is:
```
diff --git a/init-tools.sh b/init-tools.sh
index 3dea1da..4f760bb 100755
--- a/init-tools.sh
+++ b/init-tools.sh
@@ -25,7 +25,7 @@ get_current_linux_name() {
             return 0
         fi
         if [ "$(cat /etc/*-release | grep -cim1 16.10)" -eq 1 ]; then
-            echo "ubuntu.16.10"
+            echo "ubuntu.16.04"
             return 0
         fi

```

**Comment by borgdylan** [comment]
I got a failure for a project named ```Dependency```. I assume that this is a sample project and that MSBuild itself has been compiled. The failure was due to non-support for 16.10 in the project file.

**Comment by borgdylan** [comment]
Using a similar patch on cibuild.sh got me as a far as I needed. @radical How do I revert the switch to mcs and use csc instead? I am using mono master which bundles a working csc.

**Comment by radical** [comment]
@borgdylan Use the `xplat-master` branch for working with mono/master. That uses mono's bundled csc.

**Comment by borgdylan** [comment]
Will the Sdks/NuGet targets ever be integrated into MSBuild for mono or will the CLI have to add a way to use the mono version of MSBuild when it exists on the machine?

**Comment by radical** [comment]
Eventually, projects using SDKs will work out of the box with msbuild/mono.

**Comment by borgdylan** [comment]
I managed to build by symlinking the Sdks folder. I couldn't use nuget pack support however.

**Comment by feliwir** [comment]
Related to this i think: https://github.com/Microsoft/msbuild/issues/1396

**Comment by rainersigwald** [comment]
Initialization has been overhauled in #2868. I'm going to close this--if anyone is still seeing failures building on Ubuntu, please open a new issue.
