### ISSUE TITLE
Could not load file or assembly 'Microsoft.Diagnostics.Tracing.EventSource, Version=1.1.28.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by shilpi1922** [Microsoft/msbuild#1704]
I am trying to run my existing application in recently installed Visual Studio 2015, but i am getting error "Could not load file or assembly 'Microsoft.Diagnostics.Tracing.EventSource, Version=1.1.28.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified."

Same application is working fine for rest of my team member.

**Comment by AndyGerlicher** [comment]
You'll need to be more specific for us to be able to help you. Ideally a minimal repro sample project with steps. You'll also want to turn on [fusion logging](https://msdn.microsoft.com/en-us/library/e74a18c4(v=vs.110).aspx) and determine which DLL is not found and where it looked.

**Comment by rainersigwald** [comment]
Closing due to lack of response. Please re-open with the requested details if you are still having this problem.
