### ISSUE TITLE
SerialConsoleLogger and ParallelConsoleLogger have different code for printing properties

### ISSUE THREAD

**Issue by KirillOsenkov** [microsoft/msbuild#1707]
ParallelConsoleLogger and SerialConsoleLogger both inherit from BaseConsoleLogger.

In BaseConsoleLogger, there's this default implementation of OutputProperties:
http://source.dot.net/#Microsoft.Build/Logging/BaseConsoleLogger.cs,bab9b832414327cb

In ParallelConsoleLogger, it is overridden like this:
http://source.dot.net/#Microsoft.Build/Logging/ParallelLogger/ParallelConsoleLogger.cs,d092c8ee77e2800f

Difference is in this line:
```
WritePretty(String.Format(CultureInfo.CurrentCulture, "{0,-30} = ", prop.Key));
```

Because of this difference if you use a logger that doesn't use `ENABLEMPLOGGING`, name values will be aligned at 30 char column. For a parallel logger the properties are not aligned:

![image](https://cloud.githubusercontent.com/assets/679326/22996593/30112bba-f384-11e6-82b3-3b263d19a872.png)

We should decide which behavior is better and unify to use that. I think not aligning is better since 30 chars is arbitrary and since mostly everyone uses the Parallel logger we'll preserve this behavior and won't break the majority. Also the non-aligned format is easier to parse.

**Comment by davkean** [comment]
Non-aligned format is easier to parse for a computer - for a human the aligned/table format is so much easier to read.

**Comment by rainersigwald** [comment]
This is annoying but I don't think we'll ever get around to rectifying it, given all the other stuff we could be doing.
