### ISSUE TITLE
Failed build leaves MSBuild processes lying around

### ISSUE THREAD

**Issue by wjk** [Microsoft/msbuild#1709]
I have a (closed-source) .NET Core project that uses some custom MSBuild tasks. The tasks are cross-built for both `netcoreapp1.1` and .NET Framework 4.6, so that they will work properly in both `dotnet build` and Visual Studio.

However, when I run the build from within VS and it fails, three or four `MSBuild.exe` processes remain lying around, holding the DLL containing the tasks open, requiring me to `taskkill` them before I can replace the DLL with a version containing fixes for debugging. `dotnet build` does not appear to do this. I am using VS 2017 RC4 build 26206. As far as I can recall, this did not occur on previous builds of VS2017.

**Comment by AndyGerlicher** [comment]
This feature is called node reuse. You can turn it off on the command-line by running `MSBuild.exe /nodeReuse:false` (or just `/nr:false`). If you want it to not happen in Visual Studio you can set environment variable `MSBUILDDISABLENODEREUSE=1`. This features (for various reasons) is not supported in the .NET Core version of MSBuild so it will never happen.

That being said, the feature is there for performance. Your builds will be quite a bit slower with this turned off. It was added to avoid the overhead of process creation (with many projects and many cores it can be significant) and JIT.

I'm going to close this since it's by design. Hopefully this answers your question though? If you think there's really a behavior change between VS2015 and VS2017 feel free to re-open with repro steps. There should be no change.

**Comment by mpseidel** [comment]
> three or four MSBuild.exe processes remain lying around, holding the DLL containing the tasks open, requiring me to taskkill them

I am running into this at the moment with VS 15.2 (26430.16). In a small solution after debugging a WPF application a couple of times.

@AndyGerlicher are you aware of a recent issue in VS that might couse this? One thing that should be mentioned probably is I use https://github.com/Fody/PropertyChanged that hooks into the build process.

**Comment by gabrielpra1** [comment]
@mpseidel Have you figured out how to fix this problem?

I'm also using *FodyPropertyChanged* and VS2017.

**Comment by mpseidel** [comment]
@gabrielpra1 hey - I've set the environment variable

MSBUILDDISABLENODEREUSE = 1

That had solved the issue for me back then - haven't worked on that project for a while now.

**Comment by fedeazzato** [comment]
This is also happening to me, in any build, no matter if it succeeds or fails. Disable node reuse didn't help.
Any idea what else can I try?

**Comment by dojo90** [comment]
I have the same Problem as @fedeazzato . The **MSBuild.exe** is still running after a build.

---

If running msbuild from command line with: **/nodeReuse:false** everything works as expected, but using

```XML
<Project TreatAsLocalProperty="NodeReuse" ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <MSBUILDDISABLENODEREUSE>True</MSBUILDDISABLENODEREUSE> or <MSBUILDDISABLENODEREUSE>1</MSBUILDDISABLENODEREUSE>
    <NodeReuse>False</NodeReuse>
```
and compiling from **visualStudio** the **MSBuild.exe** is still running afterwards!

**Comment by gabrielpra1** [comment]
@dojo90 Have you tried setting the `MSBUILDDISABLENODEREUSE` globally (Option 1 [here](https://github.com/Microsoft/msbuild/wiki/MSBuild-Tips-&-Tricks#msbuildexe-nrfalse))? That worked for me.

**Comment by kjkrum** [comment]
Also running into this in VS despite setting `MSBUILDDISABLENODEREUSE=1` globally. Specifically, a `UsingTask` is unable to copy its `AssemblyFile` because the target is locked by a previous invocation of MSBuild.

**Comment by kjkrum** [comment]
I think it goes back to this old Q&A: [Visual Studio 2008 locks custom MSBuild Task assemblies
](https://stackoverflow.com/questions/3371545/visual-studio-2008-locks-custom-msbuild-task-assemblies). The fundamental issue seems to be that there's no way to tell `UsingTask` to load the task in a disposable `AppContext`, so the assembly ends up being loaded by the `AppContext` that VS keeps around... or something like that. After banging on this for a couple days, I'm coming to the conclusion that there is no way to use custom MSBuild tasks in a VS project without resorting to weird hacks like launching them from an inline task.

**Comment by francisrohner** [comment]
> @gabrielpra1 hey - I've set the environment variable
> 
> MSBUILDDISABLENODEREUSE = 1
> 
> That had solved the issue for me back then - haven't worked on that project for a while now.
> 
> https://github.com/Microsoft/msbuild/wiki/MSBuild-Tips-&-Tricks#msbuildexe-nrfalse

$env:MSBUILDDISABLENODEREUSE = 1
This worked great in a Powershell solution build script, thank you!
MSBuild processes are gone after the build script has completed now.

**Comment by danmosemsft** [comment]
There is also a command line flag `/nr:false`

**Comment by astrohart** [comment]
> This feature is called node reuse. You can turn it off on the command-line by running `MSBuild.exe /nodeReuse:false` (or just `/nr:false`). If you want it to not happen in Visual Studio you can set environment variable `MSBUILDDISABLENODEREUSE=1`. This features (for various reasons) is not supported in the .NET Core version of MSBuild so it will never happen.
> 
> That being said, the feature is there for performance. Your builds will be quite a bit slower with this turned off. It was added to avoid the overhead of process creation (with many projects and many cores it can be significant) and JIT.
> 
> I'm going to close this since it's by design. Hopefully this answers your question though? If you think there's really a behavior change between VS2015 and VS2017 feel free to re-open with repro steps. There should be no change.

OK, I understand that node-reuse can help speed up design.  However, is there a chance that MSBuild can periodically unload dll
s and libraries it no longer needs (such as if it's not presently in the 'Building' state?)

This "feature" causes massive problems for CI.  A little tweak to "periodically unload unused dll's" would be a great improvement.  You are correct, node reuse is a massive overhead saver.  However, it does not need to hang on to DLLs, e.g., for NuGet packages, when not in the `Building` state.

**Comment by danmoseley** [comment]
Just to be clear, the perf effect is only to save a few 100ms at the build start. As such it is not relevant in CI at all and IMO should always be disabled there. Perhaps in retrospect it would have been better to be opt-in and VS could opt in.

**Comment by astrohart** [comment]
Maybe make it a Tools -> Options check box?
  
  
   
  
  
   -Brian
  
  
   
    On 03/01/2021 11:43 AM Dan Moseley <notifications@github.com> wrote:
   
   
    
   
   
    
   
   
   Just to be clear, the perf effect is only to save a few 100ms at the build start. As such it is not relevant in CI at all and IMO should always be disabled there. Perhaps in retrospect it would have been better to be opt-in and VS could opt in.

**Comment by AndyGerlicher** [comment]
Just FYI another option is to disable it in `Directory.Build.rsp`. See an example here: https://github.com/microsoft/MSBuildSdks/blob/50c49ad46b29f017626510061ef51a1c194f4874/Directory.Build.rsp#L4

This will affect all command-line only builds and not VS.

**Comment by Algorithman** [comment]
When will this be fixed on a per project level? This issue is known and was called out since VS2008 every year.

It can't really be that hard. The MSBuild processes started by Visual Studio are explicitly called *WITH* then /nodeReuse:true argument.

I'm quite sick and tired of this issue. Had it a few times over the years and every time i look for a solution which doesn't require me to set a global environment variable does work only for MSBuild from the commandline but not in VS.

Bad, Microsoft, very bad. No, really, very bad.

**Comment by dkogithub** [comment]
It strikes again, now with .Net 10 RC2, please reopen the ticket,
the workaround based on MSBUILDDISABLENODEREUSE not working anymore. It's set to 1 and it still fails.
env:
  MSBUILDDISABLENODEREUSE: 1

2025-10-31T12:10:42.4821057Z [38;5;247m0>MSBUILD : 
**error MSB4166: Child node "5" exited prematurely. Shutting down. Diagnostic information may be found in files in "/tmp/msbuild-debug" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.[0m
2025-10-31T12:10:42.4821520Z [38;5;247m1>
Done executing task "MSBuild" -- FAILED.[0m**

Linux build via GitHub workflow:
.NET SDK:
 Version:           10.0.100-rc.2.25502.107
 Commit:            89c8f6a112
 Workload version:  10.0.100-manifests.8798a653
 MSBuild version:   18.0.0-preview-25502-107+89c8f6a11

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  24.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/10.0.100-rc.2.25502.107/

.NET workloads installed:
There are no installed workloads to display.
Configured to use workload sets when installing new manifests.
No workload sets are installed. Run "dotnet workload restore" to install a workload set.

Host:
  Version:      10.0.0-rc.2.25502.107
  Architecture: x64
  Commit:       89c8f6a112

.NET SDKs installed:
  8.0.120 [/usr/share/dotnet/sdk]
  8.0.206 [/usr/share/dotnet/sdk]
  8.0.317 [/usr/share/dotnet/sdk]
  8.0.414 [/usr/share/dotnet/sdk]
  8.0.415 [/usr/share/dotnet/sdk]
  9.0.110 [/usr/share/dotnet/sdk]
  9.0.205 [/usr/share/dotnet/sdk]
  9.0.305 [/usr/share/dotnet/sdk]
  10.0.100-rc.2.25502.107 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.20 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.21 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 10.0.0-rc.2.25502.107 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.20 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.21 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 10.0.0-rc.2.25502.107 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_MULTILEVEL_LOOKUP                 [0]
  DOTNET_NOLOGO                            [1]
  DOTNET_ROOT                              [/usr/share/dotnet]
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE        [1]
  DOTNET_VERSION                           [10.0.x]
  DOTNET_VERSION_RAVEN                     [8.0.x]
