### ISSUE TITLE
Mono builds cannot be found

### ISSUE THREAD

**Issue by davkean** [Microsoft/msbuild#1713]
![image](https://cloud.githubusercontent.com/assets/1103906/23016468/b8fca588-f48a-11e6-95d8-0e8e6239663d.png)

Clicking one states:

![image](https://cloud.githubusercontent.com/assets/1103906/23016490/c7072022-f48a-11e6-82dd-e0d58340a8d5.png)

**Comment by borgdylan** [comment]
All of the links state that. I had to do a manual build which does not give me anything near what the CLI gives.

**Comment by rainersigwald** [comment]
I disabled the builds for the RTW timeframe since they weren't passing, but didn't remember to remove the links from the front page. Maybe we should bring them back except for PRs to fix the xplat branch badges, then after we're done with RTW turn them back on for PRs.

**Comment by radical** [comment]
Whenever you want to turn it on, I am available to fix the issues now. I was out sick earlier and couldn't actively fix the mono issues.
