### ISSUE TITLE
Fail the out of proc node creation if there's no msbuild.exe/dll next to the Microsoft.Build.dll

### ISSUE THREAD

**Issue by cdmihai** [microsoft/msbuild#1715]
Right now if MSBuild is in detached mode, it will use the VS APIs to find an instance (#1461) and use that VS instance's msbuild.exe to launch nodes. This will most likely cause the handshake to fail and cause the parent node to spawn child nodes until the memory fills up. 

Another similar case is where the `MSBUILD_EXE_PATH` environment path is used. Though this is by design, in case users really know what they're doing and how they are composing msbuild.

When out of proc nodes are spawned, we should probably only bind to the msbuild.exe next to the Microsoft.Build.dll, and fail the build if it does not exist. Binding to any other msbuild.exe is probably wrong.

**Comment by rainersigwald** [comment]
This doesn't appear to cause a lot of problems in practice, especially after MSBuildLocator, so closing won't-fix.
