### ISSUE TITLE
msbuild will not build sln file on macOS that does build in Visual Studio for Mac

### ISSUE THREAD

**Issue by joelpresence** [Microsoft/msbuild#1720]
Hi,

We are building a socket server as a .NET console app.  It just uses basic .net core stuff, but is being developed on a Windows machine using Visual Studio.  The project is in a MyServer.sln file.

On macOS, when I try to build I get:

```
bash> dotnet msbuild MyServer.sln /ds
Microsoft (R) Build Engine version 15.1.545.13942
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/local/share/dotnet/sdk/1.0.0-rc4-004771/Microsoft.Common.CurrentVersion.targets(1111,5): 
error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.6.1" were not 
found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your 
application to a version of the framework for which you have the SDK or Targeting Pack installed. 
Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in 
place of reference assemblies. Therefore your assembly may not be correctly targeted for the 
framework you intend. 
[/Users/joel/src/MyPlatform/PresenceLabs/Platform/PresenceLabs.Platform.csproj]
```

What does this mean and how can we fix this?

To repeat, MyServer.sln builds and runs just fine on the same macOS.  It's just that we can't build with msbuild.

This should work!  Any ideas?

Thanks.

**Comment by rainersigwald** [comment]
The Core version of MSBuild that you're invoking though `dotnet MSBuild` does not currently support targeting Full Framework on OSes other than Windows. You can use a Mono-hosted MSBuild, as VSMac is doing--there should be one in the VSMac installation but I don't know the default path.

https://github.com/dotnet/sdk/issues/335 is the main issue tracking building for full .NET frameworks on non-Windows (it'll probably result in changes in this repo but that's the whole scenario so the best place to track).
