### ISSUE TITLE
Add ability to ignore imports that are empty files

### ISSUE THREAD

**Issue by jeffkl** [Microsoft/msbuild#1727]
In certain cases when creating new imports within a UI, a file might not have any content yet.  For instance, if you create a new `Directory.Build.props` within a project, Visual Studio will immediately re-evaluate the project and since the newly created file is empty, the evaluation will fail and the project will unload.

I propose a new `ProjectLoadSetting` like `IgnoreEmptyImports` that treats an empty file as an empty project.  It would also treat empty XML files as empty if they only contained the XML declaration like:

```xml
<? xml version="1.0" encoding="utf-8" ?>
```

Since its a new project load setting, it would be opt-in and probably only used by UIs.  I've taken a first stab at this here:

https://github.com/Microsoft/msbuild/compare/xplat...jeffkl:IgnoreEmptyImports?expand=1

**Comment by danmosemsft** [comment]
It's not a breaking change (such a build would break today), why not make it the default behavior and not both with the setting?

**Comment by jeffkl** [comment]
@danmosemsft we've decided to have it off by default in MSBuild but are going to have it turned on by default when Visual Studio evaluates the project.  This way you'll still get build errors if you have empty files but the project won't fail to load in VS.
