### ISSUE TITLE
msbuild of VS2017 RC csproj ASP.NET Core API targeting .NET 4.6.1 Fails

### ISSUE THREAD

**Issue by natificent** [Microsoft/msbuild#1738]
Created an empty ASP.NET Core project targeting .NET 4.6.1. Project builds and runs correctly from within VS2017 RC. Run msbuild from the command line and get:

Controllers\ValuesController.cs(5,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the name
space 'Microsoft' (are you missing an assembly reference?) [C:\dev\projects\build-sample\MSBuild.Sample.Api\MSBuild.Sam
ple.Api.csproj]

Sample project is available at:
git@github.com:natificent/build-sample.git

**Comment by rainersigwald** [comment]
Have you run `dotnet restore` or `msbuild /t:Restore` before attempting to build?

**Comment by natificent** [comment]
If I run msbuild /t:Restore, the subsequent msbuild command gets further before failing:
CSC : error CS0006: Metadata file 'C:\Windows\system32\config\systemprofile\.nuget\packages\microsoft.applicationinsights.agent.intercept\2.0.6\lib\net45\Microsoft.AI.Agent.Intercept.dll' could not be found

**Comment by rainersigwald** [comment]
That's an interesting error. Are you running as a normal user or as something like SYSTEM? Do you have any environment variables set to redirect the NuGet cache location?

I would normally expect to see that type of path under `%HOMEDRIVE%%HOMEPATH%\.nuget`, not under `system32`.

**Comment by natificent** [comment]
Thanks for your help. You were correct that I was running that under system, when I switched to a regular user account it worked like a charm.
