### ISSUE TITLE
MSBuild 15.0 is case sensitive for item transforms (regression).

### ISSUE THREAD

**Issue by ericstj** [Microsoft/msbuild#1751]
Repro:
build https://gist.github.com/ericstj/bf0c3191800a2dd5a61d418eca4fffb9 with desktop Msbuild
`msbuild.exe test-casing-transforms.proj`
Output:
```
  ABC
  foo.ABC
  bar.ABC
```

Do the same with core msbuild
`dotnet build test-casing-transforms.proj`
Output:
```
  ABC
  bar.ABC
```

It would seem that MSBuild ignores the casing when doing an item reference, but uses strict casing when doing a transform.  Desktop MSBuild ignored the casing in both places.

**Comment by rainersigwald** [comment]
Distressing. I don't observe a difference between .NET Core and full MSBuild, but I do see a difference between MSBuild 14 and MSBuild 15.1 . . .

```
S:\work\msb1751>msbuild /v:m
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

  ABC
  bar.ABC

S:\work\msb1751>dotnet msbuild /v:m
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

  ABC
  bar.ABC

S:\work\msb1751>"c:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" /v:m
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

  ABC
  foo.ABC
  bar.ABC

S:\work\msb1751>c:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe /v:m
Microsoft (R) Build Engine version 4.6.1586.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

  ABC
  foo.ABC
  bar.ABC
```

Case insensitivity is the correct behavior. I suspect this is a regression from lazy evaluation. Continuing to debug.

**Comment by ericstj** [comment]
That could be too.  I was using MSBuild 14 when doing the desktop test.

**Comment by ericstj** [comment]
Should [this](https://github.com/Microsoft/msbuild/blob/xplat/src/Build/Evaluation/LazyItemEvaluator.cs#L52) be passing in StringComparer.OrdinalIgnoreCase, as was done [here](https://github.com/Microsoft/msbuild/blob/xplat/src/Deprecated/Engine/Engine/Project.cs#L387)?

**Comment by rainersigwald** [comment]
@ericstj almost. PR coming as soon as I write a unit test.
