### ISSUE TITLE
Incremental build of certain projects are broken when Microsoft.Net.Compilers is installed

### ISSUE THREAD

**Issue by davkean** [microsoft/msbuild#1757]
Note sure if this is a Roslyn bug or a MSBuild bug, but when Microsoft.Net.Compilers is installed - incremental build of certain projects are broken due to CoreCompilerInputs.cache being regenerated.

1. Clone https://github.com/davkean/roslyn-project-system.git
2. Checkout 164325c88060f320947dcc59e06b28a78e334328
3. From a Visual Studio Command Prompt, run build.cmd
4. Run build.cmd

Look at the build log.

Expected: All projects considered up-to-date
Actual: Microsoft.VisualStudio.Editors and Microsoft.VisualStudio.ProjectSystem.Managed are out of date due to CoreCompileInputs.cache being regenerated

6. checkout 64f6bf110f3f271695dbdc88b46bef2fcf8e3e3e (which removes Microsoft.Net.Compilers packages)
7. Build twice again

Notice those projects are not out of date.

**Comment by davkean** [comment]
~Looks like the generated assembly info is always being regenerated:~

```
20:02:06.171  9:25>CoreGenerateAssemblyInfo: (TargetId:235)
                   Added Item(s): 
                       AssemblyAttribute=
                           System.Reflection.AssemblyFileVersionAttribute
                                   _Parameter1=42.42.42.42
                   Added Item(s): 
                       AssemblyAttribute=
                           System.Reflection.AssemblyInformationalVersionAttribute
                                   _Parameter1=1.0.0
                   Added Item(s): 
                       AssemblyAttribute=
                           System.Reflection.AssemblyProductAttribute
                                   _Parameter1=Metadata
                   Added Item(s): 
                       AssemblyAttribute=
                           System.Reflection.AssemblyTitleAttribute
                                   _Parameter1=Metadata
                   Added Item(s): 
                       AssemblyAttribute=
                           System.Reflection.AssemblyVersionAttribute
                                   _Parameter1=42.42.42.42
                   Removed Item(s): Compile=E:\project-system\bin\obj\Metadata\Release\GeneratedAssemblyInfo_42.42.42.42.cs
20:02:06.173  9:25>Done building target "CoreGenerateAssemblyInfo" in project "Metadata.csproj".: (TargetId:235)
20:02:06.173  9:25>Target "GenerateAssemblyInfo: (TargetId:236)" in file "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.GenerateAssemblyInfo.targets" from project "E:\project-system\src\Dependencies\Metadata\Metadata.csproj" (target "CoreCompile" depends on it):
20:02:06.173  9:25>Done building target "GenerateAssemblyInfo" in project "Metadata.csproj".: (TargetId:236)
20:02:06.173  9:25>Target "CoreCompile: (TargetId:237)" in file "C:\Users\davkean\.nuget\packages\Microsoft.Net.Compilers\2.0.0-rc2-61102-09\tools\Microsoft.CSharp.Core.targets" from project "E:\project-system\src\Dependencies\Metadata\Metadata.csproj" (target "Compile" depends on it):
                   Building target "CoreCompile" completely.
                   Input file "E:\project-system\bin\obj\Metadata\Release\GeneratedAssemblyInfo_42.42.42.42.cs" is newer than output file "E:\project-system\bin\obj\Unused\Release\Metadata.xml".
```

**Comment by davkean** [comment]
Maybe that's a red herring, looks like Editors is a big cause of it:

```
Target "CoreCompile: (TargetId:1606)" in file "C:\Users\davkean\.nuget\packages\Microsoft.Net.Compilers\2.0.0-rc2-61102-09\tools\Microsoft.VisualBasic.Core.targets" from project "E:\project-system\src\Microsoft.VisualStudio.Editors\Microsoft.VisualStudio.Editors.vbproj" (target "Compile" depends on it):
Building target "CoreCompile" completely.
Input file "E:\project-system\bin\obj\Microsoft.VisualStudio.Editors\Release\CoreCompileInputs.cache" is newer than output file "E:\project-system\bin\obj\Microsoft.VisualStudio.Editors\Release\Microsoft.VisualStudio.Editors.xml".
Added Item(s): AdditionalFileItems=PublicAPI
Using "Vbc" task from assembly "C:\Users\davkean\.nuget\packages\Microsoft.Net.Compilers\2.0.0-rc2-61102-09\build\..\tools\Microsoft.Build.Tasks.CodeAnalysis.dll".
Task "Vbc" (TaskId:863)
```

**Comment by davkean** [comment]
E:\project-system\bin\obj\Microsoft.VisualStudio.Editors\Release\CoreCompileInputs.cache doesn't exist on disk after the build, and looks like Editors is building over and over again.

**Comment by davkean** [comment]
Looks like both Editors and Managed always have their compile cache regenerated:

![image](https://cloud.githubusercontent.com/assets/1103906/23356824/719cd584-fd2f-11e6-9701-30e6fbfab787.png)

**Comment by davkean** [comment]
And then at the end of the build these are deleted, I cannot see any deletes for this file in the log. :(

**Comment by davkean** [comment]
Looking at the log no idea what's going on.

@rainersigwald What's the best way to figure out why a CoreCompileCache is being regenerated, and then deleted at the end of a build?

**Comment by davkean** [comment]
This is related to the fact we're pulling in Microsoft.Net.Compilers - removing it prevents these cache files from being regenerated.

**Comment by rainersigwald** [comment]
@davkean I don't repro on d15rel 26226.0. I get restore failures at that commit, and after working around that (commenting out the restore step in `build/build.proj`), I don't see `CoreCompileInputs.cache" is newer than output file ` in the log at all.

```
13:45:21.877    28>Target "CoreCompile: (TargetId:86)" in file "C:\Users\raines\.nuget\packages\Microsoft.Net.Compilers\2.0.0-rc2-61102-09\tools\Microsoft.VisualBasic.Core.targets" from project "S:\roslyn-project-system\src\Microsoft.VisualStudio.Editors\Microsoft.VisualStudio.Editors.vbproj" (target "Compile" depends on it):
13:45:21.902    28>Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
```
 In addition, after the build, `S:\roslyn-project-system\bin\obj\Microsoft.VisualStudio.Editors\Debug` still has a `CoreCompileInputs.cache` with the same rough timestamp as all the others.

Would be interesting to see a diag log of the second build when this repros. I'd start by poking around near instances of the string `bin\obj\Microsoft.VisualStudio.Editors\Release\CoreCompileInputs.cache`.

**Comment by rainersigwald** [comment]
dotnet/project-system#4736 is likely related (though based on timing wasn't the cause of whatever this was).
