### ISSUE TITLE
Question: How do I include native assemblies as a NuGet runtime with .NET Core projects?

### ISSUE THREAD

**Issue by pauldotknopf** [microsoft/msbuild#1758]
For example, ```runtime/debian``` and ```runtime/win-64```, etc.

Similar to how the libuv packages are delivered through NuGet [here](https://github.com/aspnet/libuv-package/blob/164eb56/src/Libuv/project.json#L19).

**Comment by dasMulli** [comment]
The pack targets look for metadata on a few known item types, I've been able to include msbuild files using the following inside an `<ItemGroup>`:
```
<None Update="build\**\*" Pack="true" PackagePath="\build" />
```
So I suppose you could do something like:
```
<None Update="runtime\**\*" Pack="true" PackagePath="\runtime" />
```
which will pack all

**Comment by pauldotknopf** [comment]
Great.

I got it working.

```xml
    <Content Include="../../native/medxdcmtk/lib/libmedxdcmtk.so">
      <PackagePath>runtimes/debian-x64/native/libmedxdcmtk.so</PackagePath>
      <Pack>true</Pack>
    </Content>
    <Content Include="../../native/dcmtk/lib/libdcmtk.so.10">
      <PackagePath>runtimes/debian-x64/native/libdcmtk.so.10</PackagePath>
      <Pack>true</Pack>
    </Content>
```

However, when I run this, I can't pinvoke. I get "System.DllNotFoundException : Unable to load DLL 'libmedxdcmtk': The specified module could not be found.".

If I copy the two libs directly into /usr/lib, it works, so I know it isn't an issue with the binaries. It is an issue with the dotnet runtime not loading the native packages correctly.

I am using dotnet cli "1.0.0-rc4-004771".

**Comment by rainersigwald** [comment]
A straightforward solution for this moving forward should come with #5037.
