### ISSUE TITLE
MSBuild started giving Nuget Package Restore errors when building

### ISSUE THREAD

**Issue by natificent** [Microsoft/msbuild#1759]
Last Friday msbuld started failing with the following exception:

error : Invalid restore input. Invalid input 'ProjectPath'. XProj support has been removed. Support for XProj and standalone project.json files has been removed, to continue working with legacy projects use NuGet 3.5.x from https://nuget.org/downloads 

Is there a way to have MSBuild use a different version of Nuget than the one that comes with msbuild?

**Comment by rainersigwald** [comment]
What CI system are you using? What command is your CI server running when it experiences this issue? Did something recently change in your CI configuration? I suspect this is an issue with CI or machine configuration, rather than MSBuild.

**Comment by natificent** [comment]
Rainer, thanks again for your quick response. I apologize for not digging further before opening an issue. Someone changed the CI to build the old project branch, not our VS2017 branch we're using for testing the new build tools.
