### ISSUE TITLE
Modifying a project adds BOM at the start of the project

### ISSUE THREAD

**Issue by 333fred** [Microsoft/msbuild#1768]
_From @davkean on February 28, 2017 11:38_

1. File -> New Project
2. Check Create new Git repository
3. Right-click on project and choose Edit
4. CTRL+S

Expected: For no changes to the project
Actual: The project has changes if you run git diff you see:

``` XML
-<Project Sdk="Microsoft.NET.Sdk">
+<EF><BB><BF><Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
     <OutputType>Exe</OutputType>
```

_Copied from original issue: dotnet/roslyn-project-system#1651_

**Comment by 333fred** [comment]
_From @davkean on February 28, 2017 11:38_

No idea who's bug this is @333fred.

**Comment by 333fred** [comment]
This is an msbuild issue, I'll move it over there. The issue is that we assume, in the absence of a utf header, that the default encoding of a file is UTF-8 w/ BOM, even if the file's original encoding was UTF-8 w/o BOM.

**Comment by davkean** [comment]
Talking to @333fred he pointed me to this: https://github.com/Microsoft/msbuild/blob/xplat/src/Build/Construction/ProjectRootElement.cs#L603. This looks wrong - it doesn't using the encoding coming from the file, in this case UTF-8 (no BOM). 

Look at the XML specification for what to do in case where the encoding is not specified in the XML declaration: https://www.w3.org/TR/xml/#sec-guessing. Hint, StreamReader will already do the right think here - so just read the encoding it sniff'd.

**Comment by rainersigwald** [comment]
> Hint, StreamReader will already do the right think here - so just read the encoding it sniff'd.

I'm pretty sure that's not true for us. @AndyGerlicher will probably remember more.

We could maybe just change `s_defaultEncoding` to the no-BOM variant.

**Comment by davkean** [comment]
But that will have the reverse impact, it will remove the BOM.
