### ISSUE TITLE
Add support for .NET 4.61 Framework SDK

### ISSUE THREAD

**Issue by AndyGerlicher** [Microsoft/msbuild#177]
The change needs to ship in Dev 14 Update 1

New Path for registry: `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Microsoft SDKs\NETFXSDK\4.6.1`
New Path for Tools: `C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools`
New Path for Kits: `C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1`

We also want to include an overload for `ToolLocationHelper.GetPathToDotNetFrameworkSdkFile` to always use the latest (currently it takes an enum and Latest will only update if you recompile both sides).

**Comment by weltkante** [comment]
@AndyGerlicher is this supposed to work automatically or do I need to set something on my project? I'm on VS 2015 Update 3 and only getting C++ headers pulled from NETFXSDK 4.6 even though the 4.6.1 folder exists on disk.
