### ISSUE TITLE
TransformedAppxPackagePayload not working appropriately

### ISSUE THREAD

**Issue by Gijsreyn** [microsoft/msbuild#1771]
When building an UWP project from the Xamarin template from VS 2015 (update 3), I stumbled on a weird error: 

"c:\users\%username%\documents\visual studio 2015\Projects\App5\App5\App5.UWP\obj\x86\Debug\PackageLayout\entrypoint\App5.UWP.exe 0x80070003 - The system cannot find the path specified.

Looking into more depth, I looked into the Microsoft.Net.CoreRuntime.Targets and found out that the AppxPackagePayload is removing the items correctly, but that the transformedAppxPackagePayload is not doing anything what eventually leads up to this error. 

Working case:

      _TransformedAppxPackagePayload=
         c:\users\%username%\documents\visual studio 2015\Projects\App5\App5\App5.UWP\obj\x86\Debug\App5.UWP.exe
                  OutputGroup=BuiltProjectOutputGroup
                  ProjectName=App5
                  TargetPath=entrypoint\App5.UWP.exe

When /t:Rebuild is applied, it seems to work fine, because in this case everything is deleted in the first place.

I hope I took the right conclusion here as it is pretty dificult without /debug switch on the 2015 version. Really like to see this comeback(https://github.com/Microsoft/msbuild/issues/291). Especially in environments were it shouldn't be necessary to install VS.

**Comment by rainersigwald** [comment]
Team triage: closing as this hasn't gotten any traffic in two years. If you're still seeing the problem, please comment and we can reactivate.
