### ISSUE TITLE
Metadata references in item creation differ inside a target

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#1778]
_From @ericstj, originally at https://github.com/dotnet/corefx/pull/16573#issuecomment-283474053_

See https://gist.github.com/ericstj/f5f88c8fbb78030663fd378d263e615d

It looks like MSBuild has different behavior when in a target vs static.

When you apply meta-data while doing a transform in static evaluation it uses the post-transformed item, however when you do it in a target it uses the pre-transformed item. That feels like a bug to me, but likely a hard one to fix since folks will depend on it...

**Comment by rainersigwald** [comment]
I suspect that the difference is that inside a target, the metadata reference causes batching, so the actual item-creation code sees a literal string that's the expansion of `%(Identity)` for the item being batched over (`@(Test)`).

That's extremely confusing and it's not good that the behavior changes in this way. But I suspect you're right that it'll be hard or impossible to fix this. I confirmed that this behavior is the same in MSBuild  4.6.1586.0 (pre-MSBuild 12).

**Comment by AndyGerlicher** [comment]
Closing this at this time. This seems very complicated to fix and likely to regress any dependency on the current behavior.

**Comment by ericstj** [comment]
Agreed on not fixing this.  Do you think that this could be documented?
