### ISSUE TITLE
Create a task to zip / unzip files

### ISSUE THREAD

**Issue by natemcmaster** [Microsoft/msbuild#1781]
Producing zip archives is a very common build step. Would be nice to have a built-in msbuild task that does this.

**Comment by moozzyk** [comment]
There is a reaoson why the task is in the file called "common.tasks": https://github.com/moozzyk/MSBuild-Tasks/blob/master/common.tasks

**Comment by AndyGerlicher** [comment]
Setting this up-for-grabs. This is something we would accept but not prioritizing right now.

**Comment by patros** [comment]
I'll have a look at this over the next few days.

**Comment by natemcmaster** [comment]
FYI - we needed zip/unzip tasks to build ASP.NET Core so we wrote our own tasks. They're good enough for us. They need more thorough testing, but you might be able to use these as a springboard for an official MSbuild version.

https://github.com/aspnet/BuildTools/blob/dev/src/Internal.AspNetCore.BuildTools.Tasks/UnzipArchive.cs
https://github.com/aspnet/BuildTools/blob/dev/src/Internal.AspNetCore.BuildTools.Tasks/ZipArchive.cs

**Comment by patros** [comment]
Thanks @natemcmaster 

I'm going to hold off looking at this until I get more familiar with the code base and just keep chipping away at little things.

**Comment by natemcmaster** [comment]
Awesome, thanks @jeffkl !

**Comment by GF-Huang** [comment]
VS2022 only remains `ZipDirectory`, where is the `Zip`/`ZipFiles` task? I need exclude some files but `ZipDirectory` not supports.
