### ISSUE TITLE
MSBuild doesn't fail a multi-proc build when a warning is promoted as an error

### ISSUE THREAD

**Issue by davkean** [Microsoft/msbuild#1791]
```
> msbuild /warnaserror project.proj /m
```

``` XML
<!-- project.proj -->
<Project>

  <Target Name="Build">
	    <Warning Text="This should block the build." />
   </Target>

</Project>
```

**Expected:** %ERRORLEVEL% to be 1
**Actual:** %ERRORLEVEL% is 0

If I remove the /m ~or the file logger~, then the error level is set to 1 as expected.

```
> msbuild /warnaserror project.proj
```

**Comment by jeffkl** [comment]
The "overall" result is overridden [here](https://github.com/Microsoft/msbuild/blob/e5bc7994348dba88d1f6fe2ebd6aa354355f0063/src/Build/BackEnd/BuildManager/BuildManager.cs#L1592) if there were warnings treated as errors.  I swear I tested multi-proc when I implemented.  I'll try and debug this to figure out why the exit code is zero.  @davkean does the build still fail?

**Comment by davkean** [comment]
I originally thought this was a the file logger that was a problem, but I'm pretty sure it's just the multi-proc build:

With multiproc

```
D:\>msbuild /warnaserror project.proj /m
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 03/06/17 11:46:39 AM.
     1>Project "D:\project.proj" on node 1 (default targets).
     1>D:\project.proj(6,6): error : This should block the build.
     1>Done Building Project "D:\project.proj" (default targets).

Build succeeded.

       "D:\project.proj" (default target) (1) ->
       (Build target) ->
         D:\project.proj(6,6): error : This should block the build.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.02```

Without '/m':

```
D:\>msbuild /warnaserror project.proj
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 03/06/17 11:46:58 AM.
Project "D:\project.proj" on node 1 (default targets).
D:\project.proj(6,6): error : This should block the build.
Done Building Project "D:\project.proj" (default targets).


Build FAILED.

"D:\project.proj" (default target) (1) ->
(Build target) ->
  D:\project.proj(6,6): error : This should block the build.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.02
```

**Comment by jeffkl** [comment]
This turned out to be a lot tougher to track down because it only repro'd when using an official Visual Studio installation.  Our local builds did not have the problem unless I built Release and ngen'd the binaries.  But I have finally fixed the issue.

**Comment by davkean** [comment]
Thanks!
