### ISSUE TITLE
Expose MSBuild globbing APIs

### ISSUE THREAD

**Issue by cdmihai** [Microsoft/msbuild#1794]
So API users can expand msbuild globs or regex match them just like the engine does.

API reqs and specs:
- [x] Globs should match against strings (matching is what CPS actually needs, and what triggered the creation of these APIs)
- [ ] Globs should be able to expand files on disk. Issue tracked separately: #1908
- [x] Globs should be composites
- [x] Glob matching should be path aware ("../a.cs" should not match a against "**/*.cs")

**Comment by am11** [comment]
Can it be extended to support negative glob patterns? For example, `.gitignore` supports it: https://git-scm.com/docs/gitignore#_pattern_format

```xml
<ItemGroup>
  <None Remove="!**/*.cs" /> <!-- remove all but the CS files -->
  <None Include="!**/*Actors*" /> <!-- include all but the paths with `Actors` in the name -->
</ItemGroup>
```

**Comment by cdmihai** [comment]
@am11 this issue is for exposing whatever the MSBuild engine does now secretively in a public API. I have opened a separate issue with your idea: #1876 

Regarding negative globs, you can still express their intent via Exclude attributes and Remove elements. Though negative globs would indeed be shorter to express.

**Comment by cdmihai** [comment]
First version of the APIs is out: https://github.com/Microsoft/msbuild/tree/master/src/Build/Globbing
