### ISSUE TITLE
Create NuGet package for CoreCLR binaries.

### ISSUE THREAD

**Issue by AndyGerlicher** [Microsoft/msbuild#181]

**Comment by jaredpar** [comment]
:+1: Would love to have this.

**Comment by dsplaisted** [comment]
I've got an initial stab at a nuspec for a package [here](https://github.com/dsplaisted/msbuild/blob/3345c27cc8ac47d3c14a3491cf2e24e5d6a248de/src/nuget/Microsoft.Build.NetCore.nuspec).  It includes the Microsoft.Build.Framework, Microsoft.Build.Utilities.Core, and Microsoft.Build.Tasks.Core assemblies, which is what the Roslyn tasks need to reference.  I've also made changes to [a fork of Roslyn](https://github.com/dsplaisted/roslyn/tree/netcore-buildtask) to build against this package.

Here are some outstanding questions:

- [ ] Do we create one package for all the assemblies or a separate package per assembly?
  - I propose we create a separate package per assembly.  That's what we've been doing with for .NET Core.
- [ ] Should the package(s) be exclusive to .NET Core, or should it also be reference-able from projects targeting .NET Framework?
  - I propose making it work for both.  We can either add metadata that will cause the assemblies to be referenced from the GAC when targeting .NET Framework, or we can add the assemblies to the package itself if we think they won't always be in the GAC.
- [ ] What name should we use for the package id(s)?
  - If we go with my proposals for the first two items, then we can simply use the assembly name as the NuGet package ID
- [ ] What should the other package metadata be (title, summary, description, license)?
- [ ] How do we make sure that the dependencies listed are correct?
  - @onovotny has written a [NuSpec Reference Generator](https://github.com/onovotny/ReferenceGenerator/blob/master/readme.md) which looks like it can do this automatically.  Let's see if we can use that.
- [ ] How do we set up a process for publishing this to MyGet, and eventually shipping packages with fully signed binaries?

Any comments?

**Comment by onovotny** [comment]
W.r.t. the Reference generator, I'm happy to make changes if there are any issues/requirements that it doesn't do yet.
