### ISSUE TITLE
Typo in `VersionSufix`

### ISSUE THREAD

**Issue by ctolkien** [Microsoft/msbuild#1812]
Intellisene completes on `VersionSufix` but the correct spelling should be `VersionSuffix` (which is what is respected by the CLI tooling).

Impacted line of code:
https://github.com/Microsoft/msbuild/blob/487db4a80806347f2f5ec8e41c7cf428dab06c92/src/MSBuild/Microsoft.Build.CommonTypes.xsd#L1802

![image](https://cloud.githubusercontent.com/assets/515955/23686074/9d44e7a8-03fb-11e7-8530-cbef2221e584.png)

Help text seems to be spelt correctly.

![image](https://cloud.githubusercontent.com/assets/515955/23686080/a5172d92-03fb-11e7-9d6f-c8b3e0e7eb50.png)

**Comment by rainersigwald** [comment]
The shame, the shame! Thanks for the report.

**Comment by rainersigwald** [comment]
Actually, I'm going to leave this open since we'll need to migrate the fix to the XSD that lives in the internal VS repo, since XSD localization isn't done here yet.

**Comment by rainersigwald** [comment]
@AndyGerlicher We never got this ported over to VS. What branch should I target? `vsuwpt`?

**Comment by AndyGerlicher** [comment]
This was ported already and will go out with VS Update 3.
