### ISSUE TITLE
Build Tools for Visual Studio 2017 and NuGet

### ISSUE THREAD

**Issue by vadimi** [Microsoft/msbuild#1814]
I installed Build Tools for Visual Studio 2017 to our build server and noticed that it doesn't include `NuGet` targets, so I cannot do `msbuild /t:restore`. Is it by design or I am missing something?

**Comment by rainersigwald** [comment]
It also doesn't include the .NET Core Sdk. This is intentional for the current release--we didn't have time to add everything someone might want as optional components of Build Tools.

#1697 is our public tracking issue for this.

**Comment by rainersigwald** [comment]
This issue is actually canonically tracked in the NuGet repo: NuGet/Home#3660.
