### ISSUE TITLE
Build & Run - only one TFM in multi-target project

### ISSUE THREAD

**Issue by onovotny** [Microsoft/msbuild#1818]
When making changes to multi-targeted libraries, the project system/MSBuild has to rebuild all TFM's as part of the build graph. This is not necessary if I want to run an app on a particular TFM. The build system should only build the necessary closest TFM.

Concrete example:
- .NET 4.6 exe references multi-targeted library with net45 and netstandard1.4 outputs (there may be many more).
- Change is made in the library
- User hits F5 to debug/run the app. 

**Actual results**
The library is built twice, once per TFM

**Expected results**
Library is built once

Note, if I just build the library or the sln, it should build all. This is an optimization for when I build a specific library/app/output that depends on another one and it knows which one it needs.

**Comment by rainersigwald** [comment]
Migrating this issue to https://github.com/dotnet/roslyn-project-system/issues/1699.

MSBuild and the Sdk do the right thing here--a command line build of the app builds only the `net45` version of the lib in this example.

Visual Studio, though, sees that the project is out of date and invokes "Build" on the "outer" instance of the project, which in turn builds all TFMs.
