### ISSUE TITLE
Standalone download link is not a real link... 

### ISSUE THREAD

**Issue by matt-richardson** [microsoft/msbuild#1822]
The download link for "Build Tools for Visual Studio 2017" on https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017 isn't a real link, its some weird `blob` link: `blob:https://www.visualstudio.com/d0c0b53b-9358-449e-ac2e-f4dd0782f590`. This makes it hard to download from an automated script.

(I would have used the chocolatey package, but that only has 2015 in it).

Can you please look into it?

**Comment by matt-richardson** [comment]
Ahh. The issue sits there for nearly 3 years with no response, and then gets closed without a response.

Can you at least provide some info?

**Comment by rainersigwald** [comment]
@matt-richardson The site you link to no longer has the behavior you described; it now has a link to https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16

You may wish to see the docs the VS setup team provides: https://docs.microsoft.com/visualstudio/install/create-a-network-installation-of-visual-studio
