### ISSUE TITLE
Build for CoreCLR on Linux

### ISSUE THREAD

**Issue by AndyGerlicher** [Microsoft/msbuild#183]
We need this in order to start testing PInvoke replacements.

**Comment by jasonwilliams200OK** [comment]
CoreCLR builds on FreeBSD, Linux and Mac, is this issues going to only target Linux or all Unices (Mac and FreeBSD)? In which case, the title can be changed to "Build for CoreCLR on Unix", a convention follows on dotnet/CoreFX repo.

**Comment by rainersigwald** [comment]
@jasonwilliams200OK Our intention is to support Mac and FreeBSD as well (and long-term to follow what CoreCLR itself does/needs).  This issue is for the first step, which will be Linux.

I filed #188 to keep track of the longer-term goal. Thanks for getting us to clarify.

**Comment by rainersigwald** [comment]
This has worked for quite a while.
