### ISSUE TITLE
Binding redirect for Microsoft.Build.Framework 4.0 -> 15.1 fails

### ISSUE THREAD

**Issue by roy-t** [Microsoft/msbuild#1831]
I'm getting an error when compiling an XNA Content Project using MSBuild 15. I have no problems when using MSBuild 14.

The error message is:

`Error loading pipeline assembly "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Microsoft.Build.Framework.dll".	XNAVS2017	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\XNA Game Studio\v4.0\Microsoft.Xna.GameStudio.ContentPipeline.targets	78	
`

This is strange since the file Microsoft.Build.Framework.dll is present in that directory and the MSBuild log seems to indicate the file was located succesfully. So I'm not sure why it won't load.

The fusion log seems to indicate a problem under MSBuild 15, but not under MSBuild 14.
[fusion_msbuild14.txt](https://github.com/Microsoft/msbuild/files/831643/fusion_msbuild14.txt)
[fusion_msbuild15.txt](https://github.com/Microsoft/msbuild/files/831645/fusion_msbuild15.txt)

To reproduce this problem create an empty XNA Windows Game project and add an existing bitmap file to the content project. (Just to make sure the content project isn't skipped). Then build it using the following parameters:

`& 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe' .\MyXnaProject.sln /p:platform=x86 /p:configuration=Debug 
`
The version of MSBuild that I'm using is

`Microsoft (R) Build Engine version 15.1.548.43366`

I've attached a log with full diagnostics and a small reproduction project

[msbuild.txt](https://github.com/Microsoft/msbuild/files/831607/msbuild.txt)
[Repo.zip](https://github.com/Microsoft/msbuild/files/831661/Repo.zip)

**Comment by roy-t** [comment]
I tried to make sense of the fusion logs and I think I've narrowed down the problem.

Version 4.0 of Microsoft.Build.Framework.dll is loaded succesfully

```
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Reference Assemblies/Microsoft/Framework/.NETFramework/v4.0/Microsoft.Build.Framework.dll.
LOG: Assembly download was successful. Attempting setup of file: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Microsoft.Build.Framework.dll
```

But then an Assembly Redirect is found:
```
LOG: Redirect found in application configuration file: 4.0.0.0 redirected to 15.1.0.0.
LOG: Post-policy reference: Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
```

Finding this new version fails:

```
Bind result: hr = 0x80070002. The system cannot find the file specified.
```

The Assembly Redirect is defined in 
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe.config

<dependentAssembly>
          <assemblyIdentity name="Microsoft.Build.Framework" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" />
          <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="15.1.0.0" />
        </dependentAssembly>
```

So I guess the question now is. Where is v 15.1 of Microsoft.Build.Framework.dll and how do I make sure that it can be found?

**Comment by roy-t** [comment]
I've created a **workaround**. But I'm not sure if this is the proper way to go.

Open the Developer Command Prompt for VS 2017 as administrator and execute the following commands:

```
cd C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin
gacutil /i Microsoft.Build.Framework.dll
```

This adds the newest version of Microsoft.Build.Framework to the Global Assembly Cache, which allows the correct version of the DLL to be found after the Binding Redirect happens.  After this I can build an XNA content project without problems. But I'm pretty sure this is not the ideal way to make this work and I'm not sure if there are any negative implications.

**Comment by rainersigwald** [comment]
I agree that that's the proximate cause of the issue.

GACing the Framework assembly will indeed work around the issue, but it scares me for a few reasons. The biggest negative implications I anticipate are around updates to MSBuild/Visual Studio (the version you've GACed will be used, instead of the updated version, so you'll have to manually re-GAC after any update) and around multiple installs of Visual Studio (the GACed version will always be used instead of the right local version).

MSBuild 15 is intentionally not GACed. This is part of the new VS installation process and isolation model that enables faster installation and update and side-by-side installations. This doesn't affect everything that refers to an older version of Framework, because generally the assembly loader will see that the assembly is already loaded and use that. I suspect that the XNA pipeline is using an isolated AppDomain that doesn't set up the right load policy.

**Comment by Sarabeth-Jaffe-Microsoft** [comment]
@roy-t We're glad you were able to create a work around to fix your issue. 

However, please be advised that XNA hasn’t been officially supported in years. The open-source effort, MonoGames, recreates most of what XNA was doing, but the XNA team was disbanded before Xbox One launched.

Also, for reasons @rainersigwald laid out, we do not officially "support" or recommend this workaround.

Thanks,
MSBuild team

**Comment by wldevries** [comment]
You point out the danger of putting the Microsoft.Build.Framework.dll file in the GAC, because it could break VS when it is updated. Wouldn't this only cause a problem if the version of the dll stays exactly the same? I'm assuming the version of the dll will increase when VS2017 SP1 is released.

**Comment by vpenades** [comment]
@Sarabeth-Jaffe-Microsoft We are well aware that XNA has been dropped for some years, but there's several big projects around that do require support. We're in the process to move on, but there's clients that refuse to move but they still want updates and patches, so we have no option than to keep working with the old XNA.

**Comment by wldevries** [comment]
We are in the exact same situation, MonoGame is fine for multiplatform development but doesn't come close to XNA in terms of features and stability.

@rainersigwald could you explain the dangers of placing Microsoft.Build.Framework.dll in the GAC and is there a blog post that explains the reasoning behind the change in the build tooling?

**Comment by DDReaper** [comment]
Any update on this @rainersigwald @roy-t ?  Seems to have been closed with no solution?

**Comment by wldevries** [comment]
silently ignored..

**Comment by roy-t** [comment]
@DDReaper (Hey Simon ;) ) did you see the workaround posted in this thread? Here is a full explanation: https://gist.github.com/roy-t/2f089414078bf7218350e8c847951255

**Comment by DDReaper** [comment]
Will check it out.  
Seems the VS2017 plugin for MSXNA seems to have stalled at the mo.  With the demise of CodePlex, this is a slight worry :S

**Comment by roy-t** [comment]
Hmm my fix relies on the 2015 version of MSXNA, the VS2017 version doesn't seem to do anything useful. Oh well, luckily I've switched to Monogame for my personal projects. At work though we rely on XNA with 20+ projects.. I'll make sure we have a backed up copy of MSXNA2015 there before codeplex goes down. :/

**Comment by DDReaper** [comment]
Same here, if it does go. Sure enough I'll be creating another new repository to keep it in the running.
I use it as a huge source of reference, given how close MonoGame and XNA are.

I'm all MonoGame for new projects but a huge amount of XNA content still exists which can be utilised for MG.

I've already archived the entire XNAGameStudio educational library (https://github.com/DDReaper/XNAGameStudio) and in the process of MonoGame'fying it all.  Also now 20% through archiving all of Ziggywares content to the site and there are some real gems there.
