### ISSUE TITLE
MsBuild 15 will ignore ToolsVersion="14.0"

### ISSUE THREAD

**Issue by feherzsolt** [microsoft/msbuild#1838]
Hi,
I found the following, which make migrating to MsBuild 2015 hard.

Thank you,
Zsolt

Reproduce:

- Install VS 2015 (Enterprise)
- Install VS 2017 (Enterprise)
- Create a toolsversion.proj file with the following content:
`<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" DefaultTargets="Build" ToolsVersion="14.0">
    <Target Name="Build">
    </Target>
</Project>`
- Open Developer Command Prompt for VS 2015
- Run `msbuild toolsversion.proj /v:d`
- Examine that tools version 14.0 being used
- Open Developer Command Prompt for VS 2017
- Run `msbuild toolsversion.proj /v:d`
- Examine that tools version 14.0 reported as unknown

**Comment by rainersigwald** [comment]
Team triage: closing due to age. If you're still seeing this problem, please let us know and we can reactivate it.

In general, it's expected that MSBuild now ignores `ToolsVersion` in projects. To select a different toolchain, use a different Visual Studio instance to build.
