### ISSUE TITLE
Suggestion: Define property "if not defined" shortcut

### ISSUE THREAD

**Issue by MarkPflug** [microsoft/msbuild#1852]
In writing custom build scripts I often find myself writing "default" property values in shared files using the following pattern:
`<MyProperty Condition="'$(MyProperty)' == ''">TheDefaultValue</MyProperty>`

The intent being that other scripts can override the default by defining their own `<MyProperty>`.

It would be nice if MSBuild provided a built-in shortcut for this pattern, that was easier to read and write, there is a lot of syntax crammed into that Condition.

Perhaps it would be possible to repurpose the "Exists" condition so you could write:
`<MyProperty Condition="!Exists">`

Where "Exists" has special meaning when provided no argument, that it will check if the current Property is already defined.

Or  maybe a new condition altogether that worked for properties.
`<MyProperty Condition="!Defined">TheDefaultValue</MyProperty>`

In this case, you could have Defined without arguments indicate if the _current_ property was defined. Or you could pass an argument to check if a different property was defined.

I admit that this is a minor gripe, but it would make scripts a bit easier to maintain.

**Comment by rainersigwald** [comment]
Related idea (we probably only need one): https://github.com/Microsoft/msbuild/issues/821.
