### ISSUE TITLE
<PackageReference> doesn't build on command line

### ISSUE THREAD

**Issue by terrajobst** [Microsoft/msbuild#1855]
I've two projects:

* `ClassLibrary`. A .NET Framework 4.6.1 class library (using the SDK-style project type). This library depends on JSON.NET.

* `WpfApp1`. A .NET Framework 4.6.1 WPF app (using the regular MSBuild). The app depends on  `ClassLibrary`.

Here is the issue: when I'm using `<PackagReference>` from both projects to JSON.NET, I can build and run in the IDE, but when I build on the command line, I get the following error:

> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets(197,5):
> error : The project.json is referencing the project 'ClassLibrary\ClassLibrary.csproj',
> but an output path was not specified on an item in the ProjectReferencesCreatingPackages property. [WpfApp1\WpfApp1.csproj]

However, when I'm converting the WPF app's `<PackagReference>` to `packages.config`, the project builds on both command line and IDE. I can also build in both environments if I remove the WPF app's dependency on JSON .NET entirely. So the root cause seems to be presence of the `<PackagReference>`.

I've uploaded the repro project [here](https://github.com/terrajobst/Repro_MSBuild_PackagReference).

**Comment by mwbowers** [comment]
I too cannot build projects with <PackageReference> from the command line.

I am referencing
<PackageReference Include="Microsoft.VisualStudio.Setup.Configuration.Interop" Version="1.8.24" />
in a class library project.

It builds correctly in the IDE and copies the referenced library to the bin; however, when I go to build from the command line, it fails with the following errors which are all included in the referenced package:

error CS0234: The type or namespace name 'VisualStudio' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
error CS0246: The type or namespace name 'ISetupConfiguration' could not be found (are you missing a using directive or an assembly reference?)
error CS0246: The type or namespace name 'ISetupInstance' could not be found (are you missing a using directive or an assembly reference?)
error CS0246: The type or namespace name 'ISetupHelper' could not be found (are you missing a using directive or an assembly reference?)
error CS0246: The type or namespace name 'ISetupConfiguration' could not be found (are you missing a using directive or an assembly reference?)

**Comment by rainersigwald** [comment]
I think this is a problem with NuGet rather than core MSBuild, so I've moved it to https://github.com/NuGet/Home/issues/4804.
