### ISSUE TITLE
MsBuild ignores build directory with .targets

### ISSUE THREAD

**Issue by kukjevov** [Microsoft/msbuild#1856]
I have nuget package which contains only .targets file. 

sample.targets file looks like:
```xml
<?xml version="1.0"?>
<Project>
    <Target Name="TestTarget" AfterTargets="build">
        <Error Text="ok fungujem super" />
    </Target>
</Project>
```
This only shows error after build, which works perfectly if included directly using `<import>` tag.

But if i want to use my nuget package which looks like:
<img src="https://rdryga-sn3301.files.1drv.com/y3mGyy-hsHbUtSzSwe4GHAFO90a7a098fViVZg1cfHNs1KaPGwp17wx2jqFN40FrIc8KLDL3a64_luEcrIiGIX6DlKXviJ8i20PXvQMD88OMYyB0HCJu-cChRaf07kHELCOxo0YyuPm_wSkeATc2hyJyUZp7kSs6wLVGybfYqnDfhg?width=722&height=280&cropmode=none" width="722" height="280" />
with .nuspec file looking like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>SampleLibTargets</id>
    <version>1.0.2</version>
    <authors>SampleLibTargets</authors>
    <owners>SampleLibTargets</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Package Description</description>
  </metadata>
    <files>
        <file src="build\**" target="build" />
    </files>
</package>
```

If i target this nuget package from csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SampleLibTargets" Version="1.0.2" IncludeAssets="Build" />
  </ItemGroup>

</Project>
```
or from:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{A202C200-E7BD-44EB-BBFF-DCFCA8CBCF9A}</ProjectGuid>
    <OutputType>Library</OutputType>
    <RootNamespace>TestConsumeNetLib</RootNamespace>
    <AssemblyName>TestConsumeNetLib</AssemblyName>
    <TargetFrameworkVersion>v4.6</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup>
    <StartupObject />
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="App.config" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SampleLibTargets" PrivateAssets="All">
      <Version>1.0.2</Version>
    </PackageReference>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

Project compiles without any error. That means that referenced nuget with build .targets is never used.

There is no documentation for using build assets, but this should be correct setup i hope. Can you help me?

**Comment by jeffkl** [comment]
Here is some documentation on how to create your packages:  https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#including-msbuild-props-and-targets-in-a-package

Your `.props` and `.targets` files must have a file name that matches your package ID.  So in this case, the file `build\sample.targets should be named `build\SampleLibTargets.targets`.

If you're using the new MSBuild 15.0 with the `<PackageReference />` in your project, NuGet should generate the files `$(IntermediateOutputPath)\$(MSBuildProjectFile).g.props` and `$(IntermediateOutputPath)\$(MSBuildProjectFile).g.targets` which contain imports to the `.props` and `.targets` in your NuGet package.  MSBuild then imports the file that NuGet generated and you should see it in the import graph.  All of this depends on MSBuild importing the file that NuGet generated so I suspect that if you rename `sample.targets` then everything should work as expected.

**Comment by kukjevov** [comment]
Sorry i forgot about that the .targets and .props must have same name as package ID :). I already had this bug once when i first created this type of nuget package, but it was long time ago.

I am going to try it and if it will work i will close this one :)

Thank you for help.

**Comment by kukjevov** [comment]
Great i just test it and it works :).

I`m closing this one since you helped me :).

Thank you
