### ISSUE TITLE
Log all imported projects at /v:diag

### ISSUE THREAD

**Issue by borgdylan** [Microsoft/msbuild#1858]
It would help MSBuild script writers to see what project files get imported and when as part of the logger output.

**Comment by rainersigwald** [comment]
Somewhat related: https://github.com/Microsoft/msbuild/issues/1299

**Comment by rainersigwald** [comment]
This is now available (https://github.com/Microsoft/msbuild/pull/2142), though it's behind an environment variable (`MSBUILDLOGIMPORTS`, see https://github.com/Microsoft/msbuild/pull/2225) for performance reasons. It's turned on by default if you use the binary logger (which also has an option to include compressed copies of all MSBuild files used during a build: https://github.com/Microsoft/msbuild/pull/2154).
