### ISSUE TITLE
Custom globalPackagesFolder in NuGet.config is not used by msbuild

### ISSUE THREAD

**Issue by robpex** [Microsoft/msbuild#1861]
I found this question on StackOverflow which describes, more or less, the same problem I'm experiencing.

http://stackoverflow.com/questions/35307155/use-solution-relative-packages-folder-with-nuget-and-project-json  

Basically, if you're using a custom globalPackagesFolder in your NuGet.config, msbuild is not looking in that directory.  My workaround is adding "/p:NuGetPackagesDirectory=$(Build.SourcesDirectory)\Packages" to the msbuild arguments.

I couldn't find this anywhere on GitHub and it took me a while to see the suggestion of adding that argument on StackOverflow, so I thought I would go ahead and create a ticket here.

**Comment by rainersigwald** [comment]
I think the best home for this issue is in the NuGet repo, since it's NuGet tasks and targets that find and point to these packages.

I copied the issue to https://github.com/NuGet/Home/issues/4810.
