### ISSUE TITLE
Reduce JIT cost for AppDomain-creating MSBuild Tasks

### ISSUE THREAD

**Issue by AArnott** [Microsoft/msbuild#1863]
[MSBuild.exe's entrypoint method](https://github.com/Microsoft/msbuild/blob/master/src/MSBuild/XMake.cs#L202) should have this attribute affixed to it:

```csharp
[LoaderOptimization(LoaderOptimization.MultiDomain)]
```

That way, MSBuild Tasks that run in that process can be optimized to share JIT results or ngen images across AppDomains (for those tasks that require their own AppDomain). 

This should help alleviate the high JIT cost observed for AArnott/CodeGeneration.Roslyn#19

**Comment by AndyGerlicher** [comment]
Team Triage:
None of us have used this, we'll take a look. Do you have an easy way to verify reduction in JIT you observed? And do you know if this has any negative perf when you only have a single app-domain?

**Comment by AArnott** [comment]
@ilyabirykov may know of any negative perf impact. How to measure? Sure: take an ETL trace of a build of my PInvoke solution, which uses the codegeneration.roslyn package that internally builds with tasks that create sub-appdomains. I'd be happy to test a private build and report on the perf improvement.

**Comment by IlyaBiryukov** [comment]
As far as I know, there  is no negative impact on the single domain environment. 
The downside of this optimization is that assemblies loaded into the shares app domain cannot be unloaded.

Also, apart from the main entry point attribution that Andrew proposed, the app domains should be created with ```AppDomainSetup.LoaderOptimization = LoaderOptimization.MultiDomain``` to be able to share ngen-ed assemblies cross app domains.

**Comment by AArnott** [comment]
@IlyaBiryukov what is "the shared app domain"? If it's the default appdomain, how is that different from the normal policy because AFAIK one cannot unload an assembly anyway. One can only unload AppDomains, and the default appdomain cannot be unloaded.

**Comment by IlyaBiryukov** [comment]
This [blog entry](https://blogs.msdn.microsoft.com/junfeng/2004/08/05/domain-neutral-assemblies/) explains that a little bit.

**Comment by AArnott** [comment]
dang. Well that defeats a major point of hosting an AppDomain (being able to unload the DLL so MSBuild.exe resident nodes don't lock files). It looks like `MultiDomainHost` would be a more appropriate parameter here, except since Roslyn doesn't GAC their assemblies, they wouldn't be domain neutral.
Grrr...

I think I can use IBuildEngine's object sharing for the life of a build though to retain an AppDomain for a full build and thus save on JIT costs without losing the ability to unload an AppDomain -- well, so long as "GC" for an AppDomain works as I might not be able to call Unload on it.
