### ISSUE TITLE
Evaluating projects to determine OutputPath

### ISSUE THREAD

**Issue by jnm2** [Microsoft/msbuild#1875]
Our CI script was using `$"**/bin/{configuration}/**/*test*.dll"` and `$"../../Common/**/bin/{configuration}/**/*test*.dll"` to search for test assemblies for VSTest, but it's very messy. It picks up things like Microsoft's TestFramework dll many times which clutters the log with warnings, and it picks up the same dll more than once because some projects reference a core test dll which gets copied to the output folder of multiple other test projects.

So, I thought, I can solve the entire glob matching mess with something more 1:1 with our actual intention, which is to run each output test assembly in the solution.

So I referenced `Microsoft.Build` and `Microsoft.Build.Runtime`, and tried this as a test:
```c#
foreach (var slnProject in SolutionFile.Parse(solutionPath).ProjectsInOrder)
{
    var project = new Project(slnProject.AbsolutePath);
    var outputPath = project.GetPropertyValue("OutputPath");
}
```

Of course the `new Project` line crashes because it tries to import the SDK relative to Microsoft.Build.dll which came from NuGet without any SDKs. I know we are waiting for SDKs to be published on NuGet, so is this a dead end?

Is there currently any way to succeed at my objective of locating all assemblies compiled by a solution? If so, what's the lightest weight recommended solution?

**Comment by rainersigwald** [comment]
Are you doing this from MSBuild on the full .NET Framework or the .NET Core MSBuild?

The former should automagically handle this for you; the latter is unfortunately a bit harder. A possible but brittle solution would be to set the environment variable `MSBuildSdksPath` to the path within your `dotnet` CLI location--maybe by finding the cli executable and constructing a relative path? I don't think it's exposed in a nicer way at the moment.

Related: https://github.com/dotnet/cli/issues/5650.

**Comment by jnm2** [comment]
> Are you doing this from MSBuild on the full .NET Framework or the .NET Core MSBuild?

I'm doing this from a Cake build script on the full .NET Framework, so pretty much the same as a net462 console app. Cake has the ability to locate MSBuild 15 but this code is running outside MSBuild, in preparation for calling VSTest.console.exe.

**Comment by cdmihai** [comment]
@jnm2  Can you check what msbuild dlls get loaded in your repro? Are they the ones under Visual Studio?

**Comment by jnm2** [comment]
@cdmihai Debug > Modules shows Microsoft.Build.dll and Microsoft.Build.Framework.dll both loaded from the console project's output folder. This is the repro:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build" Version="15.1.548" />
    <PackageReference Include="Microsoft.Build.Runtime" Version="15.1.548" />
  </ItemGroup>

</Project>
```

```c#
using Microsoft.Build.Construction;
using Microsoft.Build.Evaluation;

public static class Program
{
    public static void Main()
    {
        const string solutionPath = @"C:\Users\jmusser\Source\TFS\HeritagePMS\Heritage-dev\HeritagePMS.sln";

        foreach (var slnProject in SolutionFile.Parse(solutionPath).ProjectsInOrder)
        {
            var project = new Project(slnProject.AbsolutePath);
            var outputPath = project.GetPropertyValue("OutputPath");
        }
    }
}
```

**Comment by dasMulli** [comment]
Since setting up build evaluation is really hard at the moment, you could do sth like the EF team is doing for `dotnet ef`: Drop an extension targets file and make it generate parseable output or write a file with all the properties you need. Then call it using `dotnet msbuild your.csproj /t:WriteConfigToFile`. @natemcmaster has written a great blog post about it: http://www.natemcmaster.com/blog/2016/12/26/project-evalutation-cli-tool/

Setting up the right properties (and unsetting some during execution!) is tricky. There is [some code](https://github.com/OmniSharp/omnisharp-roslyn/blob/dev/src/OmniSharp.MSBuild/MSBuildEnvironment.cs) in omnisharp-roslyn that sets it up but it is hard to do. I've even tried using msbuild targets that generate C# files with constants set to the msbuild variables used during build, but it was flaky at best.

**Comment by natemcmaster** [comment]
See also https://github.com/dotnet/cli/issues/5300

**Comment by AndyGerlicher** [comment]
Team Triage:
Closing this as duplicate. See #1096 in our repo and also https://github.com/dotnet/sdk/issues/300. We don't really have a good solution to this at this time. Creating a full usable distribution of MSBuild is difficult.
