### ISSUE TITLE
Support negative glob patterns

### ISSUE THREAD

**Issue by cdmihai** [Microsoft/msbuild#1876]
Upgrading  a comment by @am11 to an issue: https://github.com/Microsoft/msbuild/issues/1794#issuecomment-286972038

```xml
<ItemGroup>
  <None Remove="!**/*.cs" /> <!-- remove all but the CS files -->
  <None Include="!**/*Actors*" /> <!-- include all but the paths with `Actors` in the name -->
</ItemGroup>
```

.gitignore example: https://git-scm.com/docs/gitignore#_pattern_format

**Comment by cdmihai** [comment]
A downside: this would make it much harder to do "static analysis" on msbuild code, since it would make it much harder to find the places where items are excluded. Right now you just have to scan for Excludes and Removes. With a negative pattern, it becomes a bit impossible to do statically: ` <None Include="$(MayOrMayNotBeAnExclamationMark)**/*Actors*" />`

**Comment by AndyGerlicher** [comment]
This seems like it would be too complicated for the engine to support and implement for what we would get out of it. Closing.
