### ISSUE TITLE
VS2017 Not Copying Satellite Assemblies to Proper Output Location

### ISSUE THREAD

**Issue by thefringeninja** [Microsoft/msbuild#1877]
I've been porting a project over to the new .csproj format. This project has a dependency on `FluentValidation`, which uses satellite assemblies. In VS2015, on compilation, these would be placed in their correct subfolders. VS2017 places all the satellite assemblies in the root build output folder. Since they all have the same filename, only one remains.

Minimal repro project file:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net46</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="5.5.0" />
  </ItemGroup>

</Project>
```

**Comment by cdmihai** [comment]
@srivatsn This looks like an SDK issue, right?

**Comment by thefringeninja** [comment]
Never mind. The issue was that I was running `dotnet build` not `dotnet publish`.

**Comment by thefringeninja** [comment]
Spoke too soon! VS2017 and Rider will use `dotnet build`. Why does it behave differently than `dotnet publish`?

**Comment by AndyGerlicher** [comment]
@livarcocc can  you comment on this please?

**Comment by livarcocc** [comment]
@dsplaisted @nguerrera can you guys comment?

**Comment by nguerrera** [comment]
Looks like a bug in CopyLocalLockFileAssemblies handling of satellites. I'll move this to SDK and investigate. 

@thefringeninja Thanks for the report.

**Comment by nguerrera** [comment]
This issue was moved to dotnet/sdk#1006
