### ISSUE TITLE
PackageReference is missing copy files to output feature

### ISSUE THREAD

**Issue by Ciantic** [Microsoft/msbuild#1880]
I'm trying to use [PhantomJS NuGET package](https://www.nuget.org/packages/PhantomJS/), but it's not possible with `PackageReference`:

```xml
<PackageReference Include="PhantomJS" Version="2.1.1">
      <IncludeAssets>all</IncludeAssets>
</PackageReference>
```

It does not do anything. I'd expect it to copy the files inside PhantomJS package to the output directory so I could use the binary file inside the package.

I think `PackageReference` does not have support using packages such as PhantomJS which have no .NET code in it, just random files.

I suggest a feature to be able to copy files from a NuGET package to output directory

```xml
<PackageReference Include="PhantomJS" Version="2.1.1">
      <CopyToOutputDirectory>tools/*</CopyToOutputDirectory> <!-- new feature here -->
</PackageReference>
```

Note that the PhantomJS has folder called "tools" inside, that needs to be copied to output directory to make it usable in the app.

**Comment by rainersigwald** [comment]
Moved to https://github.com/NuGet/Home/issues/4837, since this is a feature request for NuGet's handling of the `PackageReference` item and shouldn't require core MSBuild engine or target changes.
