### ISSUE TITLE
ProjectReference XSD Missing Attributes

### ISSUE THREAD

**Issue by AndyGerlicher** [microsoft/msbuild#1895]
We received user reported feedback that our `PackageReference` is missing intellisense for some fields. Our XSD currently supports `Version` and the name (`Include`), but not `Title`.

**Comment by rainersigwald** [comment]
My understanding was that it's not metadata on `PackageReference` but a property that's respected by the NuGet pack targets [here](https://github.com/NuGet/NuGet.Client/blob/871a79fb0d802c7b1f81232574626dcb8877e3d1/src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/Pack.targets#L137).

It should go in with the other pack properties: https://github.com/Microsoft/msbuild/blob/c698d39bb389177224b2b3ff69155b51f3bd8d66/src/MSBuild/Microsoft.Build.CommonTypes.xsd#L1701

**Comment by rainersigwald** [comment]
We've made a lot of XSD changes since this time, hopefully including this! If not, please file a specific new issue.
