### ISSUE TITLE
WarningsAsErrors as a property

### ISSUE THREAD

**Issue by jaredpar** [Microsoft/msbuild#1907]
Been looking to add `/warnaserror` to Roslyn and one suggestion was to just set it globally using the MSBuild property `<WarningsAsErrors>`.  The [documentation](https://msdn.microsoft.com/en-us/library/bb629394.aspx) for that property seems incomplete:

> Specifies a list of warnings to treat as errors. This parameter is equivalent to the /warnaserror compiler switch.

The behavior of `/warnaserror` without any other argument is to create an error for every warning.  Setting an empty property would not have the same effect, same as not having one.  

How can I use `<WarningsAsErrors>` property version to create an error for every warning?

**Comment by jeffkl** [comment]
The existing `WarningsAsErrors` is only a list of warning codes to pass to the compiler.  MSBuild itself knows nothing about this property and the `/warnaserror` command-line argument is a different beast.

See https://github.com/Microsoft/msbuild/issues/1886 for the issues around setting the MSBuild warnings-as-errors.

**Comment by jaredpar** [comment]
Okay.  Sounds like there is no way to do this at the moment.  Will push on #1886.
