### ISSUE TITLE
.Net 4.6.2 Console project referencing a .Net 4.6.2 ASP.Net Core app not getting all of its DLLs

### ISSUE THREAD

**Issue by BennieCopeland** [microsoft/msbuild#1911]
I have a .Net 4.6.2 ASP.Net Core main application that is referenced by a .Net 4.6.2 Console application using NSpec for testing. When compiling and executing the test project, not all DLLs from the main project make it to the test's `bin` folder. It appears that the DLLs in sub dependencies are not copied. In this particular case I noticed, I have `SimpleInjector.Integration.AspNetCore.Mvc` package installed which is listed in the ASP.Net Core's csproj file. It has a dependency on `SimpleInjector.Extensions.ExecutionContextScoping`. In the ASP.Net Core's `references` list and `bin` folder, I see the nested dependency and DLL. But in the Console project's `bin` folder, this DLL is missing unless I explicitly add the package to the test project. More details on the projects setup can be found on [this issue with NSpec](https://github.com/nspec/NSpec/issues/173)

**Comment by rainersigwald** [comment]
This should be solved/solvable in newer SDKs.
