### ISSUE TITLE
Better debuggability for GenerateTemporaryTargetAssembly

### ISSUE THREAD

**Issue by KirillOsenkov** [Microsoft/msbuild#1914]
The GenerateTemporaryTargetAssembly task (defined in PresentationBuildTasks.dll) writes a .tmp_proj project to disk, builds it, and then deletes the .tmp_proj.

There should be a task parameter such as $(PreserveGeneratedTemporaryProject) that, if set, would skip deleting the .tmp_proj so we can investigate the build issue that happens when building it.

**Comment by ericstj** [comment]
It looks like WPF did this recently : https://referencesource.microsoft.com/#PresentationBuildTasks/BuildTasks/Microsoft/Build/Tasks/Windows/GenerateTemporaryTargetAssembly.cs,331

/cc @vatsan-madhavan-msft

**Comment by KirillOsenkov** [comment]
Added to the Wiki here:
https://github.com/Microsoft/msbuild/wiki/MSBuild-Tips-&-Tricks#diagnose-wpf-temporary-assembly-compilation-issues

**Comment by KirillOsenkov** [comment]
I'm going to close this one then!
