### ISSUE TITLE
MSBuild 15 creates an assembly info file and fails to compile it..

### ISSUE THREAD

**Issue by rvuistin** [Microsoft/msbuild#1919]
## Steps to reproduce the problem:

- create an empty .NET Standard (1.3) library
- delete the`obj` and `bin` sub-folders
- at the command line, type :  `msbuild <project-name>.csproj`
- MSBuild creates the following file at `obj\Debug\netstandard1.3\<project-name>.AssemblyInfo.cs`:

```
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("xxx")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("Package Description")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0")]
[assembly: System.Reflection.AssemblyProductAttribute("xxx")]
[assembly: System.Reflection.AssemblyTitleAttribute("xxx")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]

// Generated by the MSBuild WriteCodeFragment class.
```

- as these attributes are no longer supported in .NET Standard projects the compilation fails.

> The problem does not appear when the folder `obj\Debug\netstandard1.3` exists.

**Comment by epsitec** [comment]
@jeffkl any idea why this is happening?

**Comment by dasMulli** [comment]
Did you restore after deleting the obj folder? Deleting that folder is pretty much undoing restore as well so there won't be any compilation references that define all the attributes..

**Comment by rvuistin** [comment]
No I didn't restore, I know I should, but don't you think it's odd that msbuild creates a file containing non-compilable attributes. And don't you think that the msbuild script code that generates the file should be deleted or at least modified...

**Comment by dasMulli** [comment]
>And don't you think that the msbuild script code that generates the file should be deleted or at least modified...

I'm not sure this would make the situation any better.. If the `obj/project.assets.json` file is missing, not even `System.Object` is valid and no code will be able to compile. Even if you turn off assembly info generation via `<GenerateAssemblyInfo>false</GenerateAssemblyInfo>`, none of the other code in the library would be able to compile successfully.

I believe that it would be better to invest more into a meaningful error message saying that the project has not been restored which is tracked by https://github.com/Microsoft/msbuild/issues/1139.

(Note: i'm not affiliated with MS).

**Comment by rvuistin** [comment]
Thank you very much for your explanations. You are right, I tried to turn off assembly info generation and I get an error saying : `project.assets.json` not found.

Still good to know that assembly info generation code should be disabled when building .NET standard / Core projects...

**Comment by dasMulli** [comment]
Just to be clear, the ability to disable generation of those attributes is helpful in cases where you already have an AssemblyInfo.cs file in your project (and maybe have tooling for it - e.g. GitFlow) or don't want one of the generated attributes to be generated (each one can be controlled via properties like `GenerateAssemblyCompanyAttribute`).
Every attribute is valid on and can be used for .net standard and .net core projects.

**Comment by rvuistin** [comment]
👍 Thank you again... I should have looked at the error message of the compiler saying:

`error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute`

**Comment by rvuistin** [comment]
Hope the documentation will explain this type of things...

**Comment by moh-hassan** [comment]
If you keep AssemplyAttributes in AssemblyInfo.cs, you can turn off auto-generated assembly attributes.
in csproj:

         <PropertyGroup>
              <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        </PropertyGroup> 

No, no file is generated and sucess compilation

**Comment by rainersigwald** [comment]
Sounds like this had a better error than it seemed at first glance and was resolved by restoring.
