### ISSUE TITLE
Sdk attribute is not showing up for Project or Import in Project Schema

### ISSUE THREAD

**Issue by davkean** [Microsoft/msbuild#1923]
The `Sdk` attribute is missing from the schema for `<Project/>` and `<Import/>` elements so you do not get IntelliSense for them.

**Comment by rainersigwald** [comment]
https://github.com/Microsoft/msbuild/pull/2038/files#diff-49aefd83a73e9253b89c51d2a721ff5b addresses this for `<Import>` elements, but `Project` still needs it.

**Comment by rainersigwald** [comment]
Internal PR to pick this up is https://devdiv.visualstudio.com/DevDiv/MSBuild/_git/VS/pullrequest/66821.
