### ISSUE TITLE
WriteCodeFragment should add <auto-generated/> element in comment

### ISSUE THREAD

**Issue by hubuk** [Microsoft/msbuild#1925]
Currently `$(AssemblyName).AssemblyInfo.cs` files produced by dotnet Sdk are analyzed by Roslyn. Adding `<auto-generated />` element to the file comment will prevent this.

**Comment by sharwell** [comment]
We're getting reports of this in StyleCop Analyzers (DotNetAnalyzers/StyleCopAnalyzers#2314) as well. The source of the problematic string is [here](https://github.com/Microsoft/msbuild/blob/355707088fe927563c327687cb3e09434253b977/src/Tasks/Resources/xlf/Strings.xlf#L2103), and it's actually written to the output [here](https://github.com/Microsoft/msbuild/blob/6851538897f5d7b08024a6d8435bc44be5869e53/src/Tasks/WriteCodeFragment.cs#L298).

**Comment by mariotacke** [comment]
Running into this right now with my team. We are using StyleCop Analyzers. Building through Visual Studio works fine, using dotnet publish (v1.0.4) creates this issue.

**Comment by rainersigwald** [comment]
This was fixed by #2207. Thanks @dasMulli! The fix will be available with VS 15.3 Preview 4 (and higher) and .NET Core SDK 2.0.0.
