### ISSUE TITLE
Enable SourceLink on MSBuild repo

### ISSUE THREAD

**Issue by KirillOsenkov** [microsoft/msbuild#1945]
It would be super awesome to enable GitLink on the MSBuild repo if possible:
https://github.com/GitTools/GitLink

It would greatly simplify automatically downloading and opening the right MSBuild source file during debugging.

**Comment by MeikTranel** [comment]
By now the feature request should be dotnet/sourcelink not gitlink, right @kirillosenkov?

**Comment by KirillOsenkov** [comment]
Yup!

**Comment by MeikTranel** [comment]
You should probably update the issue. When i investigated the use of sourcelink for my employer, documentation and mentions were really quite all over the place.

**Comment by rainersigwald** [comment]
This is supposed to be happening for us automatically via repo-toolset but I don't think it works. Unfortunately, I think the problems are all internal, so it'd be hard for someone outside Microsoft to fix it.

**Comment by MeikTranel** [comment]
Wait, repo-toolset is supposed update the issue when the name and location of a requested feature is changed? For real?

**Comment by rainersigwald** [comment]
No, repo-toolset is supposed to give us SourceLink in its default configuration.

**Comment by KirillOsenkov** [comment]
This is now fixed.
