### ISSUE TITLE
Add auto-imported Directory.build.props/targets to $(MSBuildAllProjects) automatically

### ISSUE THREAD

**Issue by dasMulli** [Microsoft/msbuild#1949]
`Directory.build.props`/`.targets` is a great feature, but when you start to add configuration properties in there and don't really know much about how incremental build works in msbuild, you're going to hit "weird issues".
I'd like the auto-imported files to be automatically added to `$(MSBuildAllProjects)` so that targets using it as inputs will pick up changes automatically. It's easy to forget the [necessary preamble](https://github.com/dasMulli/dotnet-win32-service/blob/e93e0f7b42c056bbb81db84a7d87d7d65f3579ae/Directory.build.props#L3-L5) when you start out with an empty msbuild file.. Also, this helps reducing your project build files to the absolute minimum.

**Comment by rainersigwald** [comment]
Great idea, tracked by #1299. Closing this as a duplicate.

**Comment by dasMulli** [comment]
#1299 is probably a little more invasive (but I'd like to see it).
For these special project files, I was thinking about adding it directly in `Microsoft.Common.props`/`.targets`.

**Comment by rainersigwald** [comment]
Oh, adding it next to the import with the same conditions? That's clever! And it should be fairly low-impact. Want to submit a PR?

**Comment by dasMulli** [comment]
Love to. will do so over the next days/weekend.
