### ISSUE TITLE
EmbeddedResource with * are not included in .NET Core (1.1.0)

### ISSUE THREAD

**Issue by damtur** [microsoft/msbuild#1953]
After migrating from `proj.json` to `*.csproj` Resources were not included.
Migration tool added:
```
<EmbeddedResource Include="compiler\resources\*" />
```
which was not working. Adding all files individually works:
```
<EmbeddedResource Include="compiler\resources\ErrorPages\404.html" />
<EmbeddedResource Include="compiler\resources\ErrorPages\500.html" />
```

Please allow for * EmbeddedResource.

**Comment by dasMulli** [comment]
try `<EmbeddedResource Include="compiler\resources\**\*" />`

**Comment by damtur** [comment]
`<EmbeddedResource Include="compiler\**\*" />` works just fine (as well as your line).
Should we:
a) change `dotnet migrate` to put `**\*`
b) change MSBuild to accept `*`
?

**Comment by rainersigwald** [comment]
MSBuild wildcards differentiate between recursive and non-recursive expansion, so the `**\*` is correct. `dotnet migrate` is fortunately no longer needed so I'm just going to close this.
