### ISSUE TITLE
Speedup Compiling by making partial assembly .dlls

### ISSUE THREAD

**Issue by reader-man** [Microsoft/msbuild#1963]
Hi,
Maybe as an idea to speed the inner cycle for developers [run/fix code/compile/run/...], and because some projects have tens/hundreds of files, and the developer might be just changing one or two of in several projects in the same time, to fix an issue or add new feature, and all the other source code are not touched.

so if the compiler, compiles the hole assembly, it will take time, but if compiling per project folder [main folders/sub folders], it would speed things a lot.

So, lets say you have the following Solution structure:
**Solution SolABC**
----   **Project PrjA**
------------  Folder A
-------------------- SubFolder A1
-------------------- SubFolder A2
-------------------- SubFolder A3
------------  Folder B
-------------------- SubFolder B1
-------------------- SubFolder B2
-------------------- SubFolder B3
------------  Folder C
------------  Folder D
----   **Project PrjB**
------------  Folder A
-------------------- SubFolder A1
-------------------- SubFolder A2
------------  Folder B
-------------------- SubFolder B1

**then instead of emitting two dll files:**
PrjA.dll
PrjB.dll

**the compiler in debug mode will emit:**
**for Project PrjA:**
----PrjA.Folder A.SubFolder A1.dll
----PrjA.Folder A.SubFolder A2.dll
----PrjA.Folder A.SubFolder A3.dll
----PrjA.Folder B
----PrjA.Folder B.SubFolder B1.dll
----PrjA.Folder B.SubFolder B2.dll
----PrjA.Folder B.SubFolder B3.dll
----PrjA.Folder C.dll
----PrjA.Folder D.dll
**Project PrjB**
----PrjB.Folder A.SubFolder A1
----PrjB.Folder A.SubFolder A2
----PrjB.Folder A.SubFolder B1

and maybe adding an option in the VS options, to specify how many files[threshold] in a folder/subfolder, that if exceeded it make the folder susceptible to being emitted to its own .dll, and have a way to make the reference system see them as one .dll, even that its separated into multiple partial .dlls.

its exactly like partial classes, that the developer can make multiple partial files, but the system looks at them as one class, making partial .dlls for one assembly/project, but the system looks at them as one .dll.

but when compiling for release, the compiler compiles each project as one .dll, as before.
this i think might speed things a lot.

**Comment by rainersigwald** [comment]
This is an interesting idea, similar to the way static libraries work in C++. However, it's not something MSBuild can do alone--the C# compiler would have to support it, and then the build system would need to use that support. I think the best place for this suggestion would be to the C# compiler team at https://github.com/dotnet/roslyn/issues. I'm going to close this since it's currently unactionable, but we can reopen to track the build-system part of the work if the compiler team implements it.
