### ISSUE TITLE
Included Compile items outside of project root directory not visible in SolutionExplorer

### ISSUE THREAD

**Issue by Rurouni** [Microsoft/msbuild#1965]
Hi,
I am trying to include folder one level above project root into dotnet core msbuild based project using new glob patterns:
```
<ItemGroup>
    <Compile Include="..\Shared\**\*.cs" />
</ItemGroup>
```
and whilst it work on the build level I can't find any way to make VS2017 to show those files as part of the project in SolutionExplorer. I have tried setting Visible(no difference) and Link(either links just one file or fails project loading) to no avail.  I need it as part of sharing code between .net core and .net 2.0 project.
Is it even possible or Shared projects are the only alternative?

Thank you

**Comment by rainersigwald** [comment]
This issue was moved to dotnet/project-system#1970
