### ISSUE TITLE
Msbuild ignores NoSummary parametr for filelog

### ISSUE THREAD

**Issue by sedlacl** [Microsoft/msbuild#1968]
If you use `/flp:LogFile=Test.log;NoSummary;ErrorsOnly` parameter, log should be empty (size = 0) unless there is no error in solution.

In msbuild 15.x there is always summary information:
```
Build succeeded.

Time Elapsed 00:00:03.34
```

See test - [MsbuildBug.zip](https://github.com/Microsoft/msbuild/files/915901/MsbuildBug.zip)

**Comment by rainersigwald** [comment]
Related to #1513.

@AndyGerlicher figured out a workaround:

```
msbuild /flp:verbosity=normal;logfile=msbuild.log /flp1:warningsonly;logfile=msbuild.wrn;nosummary;verbosity=minimal /flp2:errorsonly;logfile=msbuild.err;verbosity=minimal;nosummary test.proj
```
