### ISSUE TITLE
Support simpler semantics for using property functions on item metadata

### ISSUE THREAD

**Issue by ericstj** [Microsoft/msbuild#1973]
Today if you want to run a property function on item metadata you need to do something like the following:
```
$([System.String]::new('%(RecursiveDir)').TrimEnd('\'))
```
https://msdn.microsoft.com/en-us/library/ms171473.aspx mentions
> Property functions may not appear within metadata values. For example,
%(Compile.FullPath.Substring(0,3))
is not allowed.

Seems artificial.  Can we fix it?

**Comment by rainersigwald** [comment]
This is tracked by #1155. Definitely annoying.

**Comment by ericstj** [comment]
Thanks 👍
