### ISSUE TITLE
MSBuild in VS2017 & Dotnet CLI seems to rebuild everything every time

### ISSUE THREAD

**Issue by danwalmsley** [Microsoft/msbuild#1979]
Maybe everything is working as it should, however I am finding that if  I change a single csharp file in my main project, msbuild when I press f5 in visual studio or `dotnet build` it seems to go through building every single project in the solution, surely it should be checking that no source file was changed and skipping past them very quickly, In large projects with 30-40 projects, this gets very slow to build.

**Comment by rainersigwald** [comment]
Is the compiler actually running for every project, or do you just see that every project has MSBuild run on it?

In Visual Studio, there are two layers of up-to-date checks. MSBuild itself has a check per-target (assuming the target specifies `Inputs` and `Outputs`), which can't be disabled, and which also runs on the command line. However, the logged output of a build that is up-to-date can look very similar to a build that wasn't (the idea being that incrementality is an optimization and you shouldn't really care, so low-verbosity logging doesn't need to say anything).

Inside Visual Studio, there are "fast up-to-date checks" that avoid invoking MSBuild at all when nothing has been modified. However, for new-style SDK projects that use the [new project system](https://github.com/dotnet/project-system), that hasn't yet been implemented. That's tracked by https://github.com/dotnet/project-system/issues/62.

I'm going to close this bug assuming that you're seeing the lack of a fast-up-to-date check in VS. If you look at a `/verbosity:diagnostic` log of a build that you think should be incremental and see that work is happening, there may be an incrementality bug in either the SDK targets or your projects. If that's what you're seeing, please follow up with details and we can reopen this issue to investigate.

**Comment by ebonato** [comment]
Just Tracking back this URL.
https://developercommunity.visualstudio.com/content/problem/46717/disablefastuptodatecheck-in-project-file-no-longer.html
Thanks fou your findings @rainersigwald

**Comment by rainersigwald** [comment]
@ebonato That question sounds unrelated--the lack of a fast up to date check should mean that a build runs every time, regardless of the setting of `DisableFastUpToDateCheck`.

What type of project are you seeing the bad behavior in?
