### ISSUE TITLE
`dotnet build` hides build errors in P2P references

### ISSUE THREAD

**Issue by AArnott** [Microsoft/msbuild#1980]
As [this build on Travis](https://travis-ci.org/AArnott/TravisCINetSDK/builds/222434420#L435) demonstrates, when a P2P ref fails to build, the build failure is entirely hidden and only this red herring appears later:

> error : Cannot find project info for '/home/travis/build/AArnott/TravisCINetSDK/lib/lib.csproj'. This can indicate a missing project reference. 

When forcing detailed logs with `dotnet build /v:detailed` [the original error is finally visible](https://travis-ci.org/AArnott/TravisCINetSDK/builds/222406062#L1193-L1194):

>   Version for package `dotnet-codegen` could not be resolved.
>   2:2>/home/travis/build/AArnott/TravisCINetSDK/lib/lib.csproj(18,5): error MSB6006: "dotnet" exited with code 1.

This hiding of the original build failure cost several days in investigations and filing [the wrong issue](https://github.com/dotnet/sdk/issues/1123) originally.

Please get `dotnet build` to emit errors in P2P references.

```
dotnet --info
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.1
```

**Comment by rainersigwald** [comment]
I reproduced the problem from your example in the SDK bug: https://github.com/aarnott/traviscinetsdk/tree/workaround2

The target that fails is `GenerateCodeFromAttributes`, which runs the task `GenerateCodeFromAttributes`, which fails without logging an error. The first logged error is `ToolTask`'s generic "the launched tool did not exit `0`" message, which [is logged](https://travis-ci.org/AArnott/TravisCINetSDK/builds/222434420#L434):

```
/home/travis/build/AArnott/TravisCINetSDK/lib/lib.csproj(17,5): error MSB3073: The command "dotnet codegen" exited with code 1.
```

There's nothing MSBuild can do to make this better. The task could be changed to pay attention to the message that was written to stdout, promoting it as an error. Or the CLI could emit that message to stderr, which `ToolTask` by default logs as error.
