### ISSUE TITLE
Feature Request - Ability to read build-time environment variables from runSettings.json file

### ISSUE THREAD

**Issue by am11** [Microsoft/msbuild#1985]
Consider a `runSettings.json` file, that is added by ASP.NET Core template:

```json
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:23045/",
      "sslPort": 0
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ContextID": "CX1",
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "ProfileCX1": {
      "commandName": "Project",
      "commandLineArgs": "--port=3000",
      "launchBrowser": true,
      "launchUrl": "http://localhost:3000",
      "environmentVariables": {
        "ContextID": "CX1",
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "ProfileCX2": {
      "commandName": "Project",
      "commandLineArgs": "--port=3000",
      "launchBrowser": true,
      "launchUrl": "http://localhost:3000",
      "environmentVariables": {
        "ContextID": "CX2",
        "ASPNETCORE_ENVIRONMENT": "Staging"
      }
    }
  }
}
```

When this MVC project is set as a StartUp project in VS, it adds ProfileCX1 and ProfileCX2, along with IIS Express in run configurations. In the application code, we can access the environment variables, such as `ContextID` defined in the runSettings.json per Run configuration selection.

It would be very useful if the environment variables defined in this file are propagated to the build engine, so we can consume some globbing in csproj like:

```xml
    <ItemGroup>
        <Compile Remove="**\*" />
        <Compile Include="**\*.cs" />
        <Compile Remove="**\*.C*.cs" />
        <Compile Include="**\*.$(ContextID).cs" />
        <None Update="Views\**\*;wwwroot\**\*">
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        </None>
    </ItemGroup>
```

to potentially conditional compile all `<fileName>.<ContextID>.cs` files and exclude the other ContextIDs just by the change of run configuration selection in Visual Studio.

#### Known workarounds to pass external environment variable to affect the build-time

1. Modifying or setting environment variable before opening the solution. It's a hassle and requires us to open/close solution to build for other (elaborate) configurations.

2. Using multiple `.SLN` files per contextID, which include single set of `<projectName>.<ContextID>.csproj`s where ContextID is defined as a property `<ContextID>CX1</ContextID>` in each project file followed by the aforementioned `ItemGroup`. There is a lot of duplication in this topology.

3. Having a `.proj` file with an MSBuild task for SLN and passing the ContextID as property. This is an additional overhead and we cannot reliably just open the SLN in VS and build for certain configuration.

**Comment by rainersigwald** [comment]
MSBuild Triage: we don't think it's appropriate to build knowledge of this ASP.NET-specific file format into MSBuild.

@mlorbetske can you help route this feedback?

**Comment by mlorbetske** [comment]
@billhiebert any thoughts on this?
