### ISSUE TITLE
Parallel build warning is displayed when using /m on a single-proc machine

### ISSUE THREAD

**Issue by Mertsch** [microsoft/msbuild#2005]
As you can see in the following log, the `/m` switch is clearly used, yet there is a message about using `/m`.

```
>"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\msbuild.exe" "C:\Build\_work\1\s\x.sln" /m
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 24.04.2017 14:35:45.
```

**Comment by rainersigwald** [comment]
That's . . . very odd. I do not reproduce the issue on my machine, using the same version of MSBuild:

```
s:\msbuild2>"C:\Program Files (x86)\Microsoft Visual Studio\Preview\EntInt\MSBuild\15.0\Bin\MSBuild.exe" "s:\msbuild2\src\MSBuild.sln" /m
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 4/24/2017 11:19:29 AM.
```

Are you seeing this consistently on multiple machines?

**Comment by Mertsch** [comment]
@rainersigwald No, on my dev machine it does not happen. May be an issue with moving from VS2017 Preview to RTW.

Will do a repair on the build server and report back.

**Comment by Mertsch** [comment]
@rainersigwald Still happens on my build server even after a "Repair" installation, any suggestion on how to proceed?

**Comment by rainersigwald** [comment]
@Mertsch Unfortunately, no. The [code that emits that message](https://github.com/Microsoft/msbuild/blob/1b91be584e400d5b9ffb8711bbb926beedb25407/src/MSBuild/XMake.cs#L588-L591) looks pretty straightforward, as does the [code that interprets the command-line switch](https://github.com/Microsoft/msbuild/blob/1b91be584e400d5b9ffb8711bbb926beedb25407/src/MSBuild/XMake.cs#L2259-L2282) itself.

You could try uninstall + reinstall (I feel bad even suggesting this), diffing the MSBuild directory and assemblies against your working install, or potentially debugging into MSBuild.exe to see what's going wrong.

**Comment by Mertsch** [comment]
@rainersigwald A complete uninstall / reinstall did not help.
Then I had the idea. I guess it is in fact a bug. What I can see from the code you posted `if (cpuCount == 1 && FileUtilities.IsSolutionFilename(projectFile) && verbosity > LoggerVerbosity.Minimal)` is checks if `cpuCount` is one, which should be the case, as the build server is a single core VM and the cpuCount should be 1 no matter how many cores you specify.

Maybe the code should also check whether the the system does in fact have more then one CPU to actually benefit from `/m`

**Comment by rainersigwald** [comment]
Aha! I hadn't thought of that. You're right, a special case would be reasonable there. Thanks for following up.

**Comment by Mertsch** [comment]
@rainersigwald Glad to be of help, thank you for your support.
Very refreshing to have such a constructive conversation on the net :-)
