### ISSUE TITLE
Missing spelling 'Version' attribute in csproj doesn't throw error

### ISSUE THREAD

**Issue by eByte23** [Microsoft/msbuild#2017]
I missed spelt 'Version' as  'Verison' however it did not throw errors

This was rather frustrating even in visual studio.

Thanks

**Comment by rainersigwald** [comment]
This is an unfortunate consequence of MSBuild's "define a new variable simply by assigning to it" model--it's perfectly legitimate to define metadata named `Verison`, it's just that nothing pays attention to that.

When editing with Visual Studio, IntelliSense should complete the correctly-spelled form for you, which helps somewhat. If we had a language service (https://github.com/Microsoft/msbuild/issues/1774), we could potentially warn on low-edit-distance errors from known names.

Unfortunately, I don't think there's much that we can do to cause an actual error here.
