### ISSUE TITLE
Expose the Evaluator depth first walk as a visitor

### ISSUE THREAD

**Issue by cdmihai** [microsoft/msbuild#2021]
Multiple users expressed interest in walking over the logical project elements (via walking over all the imports). Currently, this walk is [hidden deep inside the Evaluator](https://github.com/Microsoft/msbuild/blob/master/src/Build/Evaluation/Evaluator.cs#L951)

Example visitor queries:
- GetItemProvenance would want all the ProjectItemElements
- CPS and internal team would want all the Imports, including the ones evaluating to false

**Comment by rainersigwald** [comment]
[`GetLogicalProject`](https://github.com/Microsoft/msbuild/blob/9e2254833ced58fd3bb55715e8d3bec8b89addc9/src/Build/Definition/Project.cs#L1579-L1584) is related.

**Comment by rainersigwald** [comment]
Team triage: maybe if there's a high-pri motivating factor. But doesn't seem worth it right now.
