### ISSUE TITLE
Improper handling of slashes in solution files

### ISSUE THREAD

**Issue by Sumo-MBryant** [Microsoft/msbuild#2022]
If a solution file contains a relative path to a project with a backslash (which Visual Studio and `dotnet sln add` both emit), and the project uses a project type GUID that is not recognised by MSBuild, any attempts to build the solution on Linux fail with the error:

```
{path_to_project}.metaproj : error MSB4025: The project file could not be loaded. Could not find file '{path_to_project}.metaproj'.
```

It appears that the code in `Microsoft.Build.Construction.ProjectInSolution.CanBeMSBuildProjectFile()` is failing on Linux.

# Reproduction Steps:

1. Create a solution file named *solution.sln* with the following contents:

```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 15
VisualStudioVersion = 15.0.26403.7
MinimumVisualStudioVersion = 10.0.40219.1
Project("AAAAAAAA-1760-4266-BCC7-CA923CBCF16C") = "project", "directory\project.proj", "{1FD5F8F7-D4D3-4760-B503-03883D7CDFD7}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{1FD5F8F7-D4D3-4760-B503-03883D7CDFD7}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{1FD5F8F7-D4D3-4760-B503-03883D7CDFD7}.Debug|Any CPU.Build.0 = Debug|Any CPU
	EndGlobalSection
EndGlobal
```

2. Create a project file *project.proj* in a sub directory named *directory* with the following contents:

```xml
<Project>
  <PropertyGroup>
    <DefaultProjectTypeGuid>AAAAAAAA-1760-4266-BCC7-CA923CBCF16C</DefaultProjectTypeGuid>
  </PropertyGroup>

  <Target Name="Build">
    <Message Text="Build target for $(MSBuildProjectFile)" Importance="high" />
  </Target>
</Project>
```

3. On Linux, run `dotnet msbuild solution.sln`

## Expected Output:

```
  Build target for project.proj
```

## Actual Output:

```
project.proj.metaproj : error MSB4025: The project file could not be loaded. Could not find file '/homeproject.proj.metaproj'.
```

# Workaround

Replace all backslashes in the solution file with forward slashes in the solution file.

**Comment by rainersigwald** [comment]
At a quick glance, I bet we we need a `MaybeAdjustFilePath()` about [here](https://github.com/Microsoft/msbuild/blob/6851538897f5d7b08024a6d8435bc44be5869e53/src/Build/Construction/Solution/ProjectInSolution.cs#L167).

**Comment by radical** [comment]
I get the same error on mac, with `dotnet 1.0.3`: `dotnet build foo.sln`.
But with msbuild/mono (even few months old 4.8.0) it works fine. 

```
$ dotnet build -version
Microsoft (R) Build Engine version 15.1.1012.6693
```

**Comment by radical** [comment]
I have https://github.com/mono/msbuild/commit/28dc2d47dff389c8c4ee9f4b2e6921a85fd515bb and https://github.com/mono/msbuild/commit/86adc961fedefef300b6273b22611410ac87270b . I'll open a PR.

**Comment by radical** [comment]
Ah, the base patch is already in, so only the actual fix is required.

**Comment by dmitriyse** [comment]
Linux, dotnet-sdk-2.0.3
Command:
```
dotnet msbuild /t:MyProject:build MySolution.sln
```
do nothing

But on windows it works. This command builds only MyProject project from the MySolution.sln
