### ISSUE TITLE
Redirecting MsBuildExtensionsPath causes incorrect double-load warnings

### ISSUE THREAD

**Issue by zjrunner** [Microsoft/msbuild#2023]
We have an isolation system in place that doesn't depend on MsBuild installation.  As such, we alter $(MsBuildExtensionsPath) early in our project load order.  This has worked fine since MsBuild 4 and earlier, but as of v15 we get load warnings in VisualStudio.  Unclear if this is an MsBuild fault or a VisualStudio fault.

VS gives this warning
`	"D:\CorextCache\.A\MsBuild.Corext.sE2FwIuT0zUvdE9g6wU5UA\Extensions\Plugin\Props\MsBuild.Tasks.Corext.props" cannot be imported again. It was already imported at "D:\CorextCache\.A\MsBuild.Corext.sE2FwIuT0zUvdE9g6wU5UA\Environment.props (36,3)". This is most likely a build authoring error. This subsequent import will be ignored. [D:\code\CorextExe\src\Common\Common.csproj]	Common	D:\CorextCache\.A\MsBuild.Corext.sE2FwIuT0zUvdE9g6wU5UA\Environment.props	36	
`
Where the code loading that task is essentially:
`  <Import Project="$(MsBuildExtensionsPath)\Plugin\Props\*" />`

There is only one file in the Props folder, and if I remove the wildcard and import only that file it works fine.  More interesting is that changing the property used to root it to something else, or using a hardcoded path at the beginning lets it work fine with wildcards.  For instance

`  <Import Project="$(AnyOtherProperty)\Extensions\Plugin\Props\*" />`

It seems there is special logic around the variable MsBuildExtensionsPath causing msbuild/VS to get confused over wildcard imports such that it thinks it has to import twice from this specific line.

**Comment by rainersigwald** [comment]
I suspect this is related to extension path fallback (https://github.com/Microsoft/msbuild/pull/586 among others). @AndyGerlicher anything spring to mind?

**Comment by AndyGerlicher** [comment]
This is likely because the import with the fallback are unioned together. The fallback paths should be removed from the app.config in CoreXT distribution.
