### ISSUE TITLE
NuGet package to locate VS MSBuild

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#2030]
Proposed in #1461 but not implemented.

> Potential idea: Publish NuGet package to help a standalone app find MSBuild. This would check if we're in DevConsole or use the Setup COM API to find VS and add AssemblyLoad logic to the current AppDomain to find Microsoft.Build.*.dll.

**Comment by rainersigwald** [comment]
_From @DustinCampbell in https://github.com/Microsoft/msbuild/issues/1461#issuecomment-298076900:_

I would love to have this. In OmniSharp, we end up calling `TryFromSetupApi` via [reflection](https://github.com/OmniSharp/omnisharp-roslyn/blob/ba90f476d80f333c052f59627444cc157416d169/src/OmniSharp.MSBuild/MSBuildHelpers.cs#L65-L78) in order to determine whether we should set environment variables to use MSBuild in Standalone mode. In VS Code, we only want to be standalone as a last resort.

**Comment by DustinCampbell** [comment]
Thanks for filing this @rainersigwald.

**Comment by rainersigwald** [comment]
Related (steps toward an implementation of this): https://github.com/Microsoft/msbuild/issues/1784#issuecomment-293402946.

**Comment by rainersigwald** [comment]
This now lives at https://github.com/Microsoft/MSBuildLocator.

@AndyGerlicher Is the package not yet published to nuget.org? I only see it on our myget (https://dotnet.myget.org/feed/msbuild/package/nuget/Microsoft.Build.MSBuildLocator).
