### ISSUE TITLE
Ability to log events from project evaluation

### ISSUE THREAD

**Issue by cdmihai** [Microsoft/msbuild#2032]
Need to
- get evaluation events per Project / ProjectInstance object
- know when evaluation starts and finishes

Implementation possibilities:
- add overloads to Project evaluation to pass in additional loggers. The ones inherited from the `ProjectCollection` are not good because those are shared across all projects built within that collection. Also, the events themselves do not link back to the project object under evaluation / build.
- add 2 new evaluation events, `BeginEvaluation` and `EndEvaluation`. Custom logger implementations can then trigger events, etc

Changes request by CPS.

**Comment by KirillOsenkov** [comment]
Ooh, this is great. The problem I'm running into is a lot of messages stemming from evaluation logged with the default BuildEventContext, and so it's impossible to attribute the message to evaluation of a particular project. So the structured log has a lot of messages at the root level.

Ideally for all messages logged during evaluation we should know 1) it's evaluation and 2) which project is being evaluated.

**Comment by KirillOsenkov** [comment]
P.S. Here's what I've added:
https://source.dot.net/#Microsoft.Build/Evaluation/Evaluator.cs,780
https://source.dot.net/#Microsoft.Build/Evaluation/Evaluator.cs,934

But this is not enough of course. We need something proper here.
