### ISSUE TITLE
Avoid first-chance MissingMethodException in Expander

### ISSUE THREAD

**Issue by KirillOsenkov** [Microsoft/msbuild#2040]
When debugging MSBuild evaluations we see tons and tons of first-chance MissingMethodExceptions:
http://source.dot.net/#Microsoft.Build/Evaluation/Expander.cs,3143

Looking at the code there can be relatively straightforward fixes that would avoid the first-chance exception and also make evaluation faster.

**Comment by davkean** [comment]
Dup'ing this against https://github.com/Microsoft/msbuild/issues/2217 which has much more context. I'm working on a prototype.

**Comment by KirillOsenkov** [comment]
Ha ha, so you saw that I filed this independently! I've been meaning to fix this eventually but life got in the way. Glad you're looking into this.
