### ISSUE TITLE
Restoring and Building in same run fails to compile if project includes sources from NuGet packages

### ISSUE THREAD

**Issue by prochnowc** [Microsoft/msbuild#2042]
I have simple helper build file:

```
   <Target Name="Build" DependsOnTargets="UpdateVersion">
    <MSBuild Targets="Restore" Projects="@(ProjectsToBuild)" />
    <MSBuild Targets="Build" Projects="@(ProjectsToBuild)" />
   </Target>
```

However this fails to build if some project uses sources included from NuGet packages (contentFiles).

It seems that the `ProjectName.csproj.nuget.g.props` generated by the Restore target does not get read in when the Build target is called in the same run.

What could be the problem?

Note that when i use "msbuild MySolution.sln /t:restore;build" everything works OK.
I tried to change `<MSBuild Targets="Build" Projects="@(ProjectsToBuild)" />` to `<MSBuild Targets="Restore;Build" Projects="@(ProjectsToBuild)" />` but same behavior.

**Comment by dasMulli** [comment]
FWIW I've had success using `UnloadProjectsOnCompletion="true" UseResultsCache="false"` (dunno if the `UseResultsCache` is necessary here) on the call to `Restore` (see https://gist.github.com/dasMulli/69f5303aa79a8cd4060e44891c90fd2d), but @rainersigwald said that it might not be guaranteed to work

**Comment by prochnowc** [comment]
I already tried to put `UnloadProjectsOnCompletion="true" UseResultsCache="false"` but no luck.

**Comment by dasMulli** [comment]
My bad, I've been running restore on the solution in that script; that's why it works (I think)

**Comment by prochnowc** [comment]
@dasMulli if you have clean checkout (target clean does not delete nuget generated targets!) i'm sure it will not work in your case either.

**Comment by jeffkl** [comment]
I think this has been reported before but I can't find the issue.  You should be able to work around this by using a dummy property to have MSBuild re-evaluate the projects during build.

Please try:
```xml
<Target Name="Build" DependsOnTargets="UpdateVersion">
  <MSBuild Targets="Restore" Projects="@(ProjectsToBuild)" />
  <MSBuild Targets="Build" Projects="@(ProjectsToBuild)" Properties="AnyProperty=AnyValue" />
</Target>
```

**Comment by prochnowc** [comment]
@jeffkl Many thanks! It works...
