### ISSUE TITLE
MSBuild 15.3 broke <Import Sdk="" Project="" /> tags

### ISSUE THREAD

**Issue by AArnott** [Microsoft/msbuild#2043]
The following project can build (`/t:restore`) just find in MSBuild 15.1. 

```xml
<Project>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <TargetFramework>netstandard1.3</TargetFramework>
  </PropertyGroup>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>
```

But MSBuild 15.3.111.8862 fails with:

> error MSB4019: The imported project "C:\temp\bug\Sdk.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

**Comment by rainersigwald** [comment]
Duplicate of #2034, fixed by #2038, coming soon to a VS near you (https://devdiv.visualstudio.com/DevDiv/_workitems/edit/428329 if you want to follow along internally).
