### ISSUE TITLE
When using 64bit version of MSBuild 15.0, $(SDK40ToolsPath) is not set

### ISSUE THREAD

**Issue by gimpf** [Microsoft/msbuild#2047]
There's an unexpected difference between using MSBuild 15.0 from the base installation folder vs. calling it from the amd64/ subfolder: $(SDK40ToolsPath) is set only for the x86 version, the amd64 version does not set the variable. As a result, calling tools like `gacutil.exe` from those paths fails.

# Steps to reproduce

**1. Create a MSBuild project file 'test.proj':**
```
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <GacUtilPath Condition="'$(GacUtilPath)' == ''">$(SDK40ToolsPath)gacutil.exe</GacUtilPath>
    </PropertyGroup>
    <Target Name="Build">
        <Exec Command="&quot;$(GacUtilPath)&quot; /?" />
    </Target>
</Project>
```

Specifying ToolsVersion="15.0" explicitly does not change the outcome.

**2. Good case: Start with 32bit MSBuild:**
```
& 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe' test.proj
```

**3. Bad Kitty Case: Start with 64bit MSBuild:**
```
& 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\amd64\MSBuild.exe' test.proj
```

**Maybe related**: Issue #1920 "MSBuild v15.0 & Registry". The folder registration has changed for MSBuild 15.0, but I'm somewhat confused by the entries of the application configuration. (They are the same for both MSBuild versions, so why's there a difference?)

**Remarks**: I (seemingly incorrectly) reported this at [Connect](https://connect.microsoft.com/VisualStudio/feedback/details/3133352). Also since this is command-line only, it, unlike the comment there, is unlikely to be related to Visual Studio.

**Comment by rainersigwald** [comment]
Amusingly, the Connect issue got routed to the MSBuild team last night about 5 hours before you filed this. That wasn't incorrect, but it would have just gotten transferred here, so filing this here was a good idea.

`$(SDK40ToolsPath)` is defined in the toolset as

```xml
<property name="SDK40ToolsPath" value="$(Registry:HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.6.1\WinSDK-NetFx40Tools-x86@InstallationFolder)" />

```

As you point out, this is the same for both `msbuild.exe.config` toolset definitions. But there's a difference: 32-bit processes are subject to the [Registry Redirector](https://msdn.microsoft.com/en-us/library/windows/desktop/aa384232(v=vs.85).aspx), which points 32-bit process queries to a different part of the registry than 64-bit queries. That key isn't set in both hives (top is 32-bit, bottom 64-):

```
S:\work>C:\Windows\Syswow64\reg.exe query "HKLM\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.6.1\WinSDK-NetFx40Tools-x86"

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.6.1\WinSDK-NetFx40Tools-x86
    ProductVersion    REG_SZ    4.6.01055
    ComponentName    REG_SZ    Microsoft .NET Framework 4.6.1 SDK
    InstallationFolder    REG_SZ    C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\


S:\work>C:\Windows\System32\reg.exe query "HKLM\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.6.1\WinSDK-NetFx40Tools-x86"
ERROR: The system was unable to find the specified registry key or value.
```

So it's only set in the 32-bit WOW registry.

MSBuild has a property function to peek into the 32-bit registry regardless of the current process architecture, and using it appears to resolve your problem:

```diff
diff --git a/MSBuild/15.0/Bin/amd64/MSBuild.exe.config b/MSBuild/15.0/Bin/amd64/MSBuild.exe.config
index a1c659a..c26ab82 100644
--- a/MSBuild/15.0/Bin/amd64/MSBuild.exe.config
+++ b/MSBuild/15.0/Bin/amd64/MSBuild.exe.config
@@ -81,8 +81,8 @@
         <property name="MSBuildFrameworkToolsPath32" value="$(SystemRoot)\Microsoft.NET\Framework\v$(MSBuildRuntimeVersion)\" />
         <property name="MSBuildFrameworkToolsPath64" value="$(SystemRoot)\Microsoft.NET\Framework64\v$(MSBuildRuntimeVersion)\" />
         <property name="MSBuildFrameworkToolsRoot" value="$(SystemRoot)\Microsoft.NET\Framework\" />
-        <property name="SDK35ToolsPath" value="$(Registry:HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v8.0A\WinSDK-NetFx35Tools-x86@InstallationFolder)" />
-        <property name="SDK40ToolsPath" value="$(Registry:HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.6.1\WinSDK-NetFx40Tools-x86@InstallationFolder)" />
+        <property name="SDK35ToolsPath" value="$([MSBuild]::GetRegistryValueFromView('HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v8.0A\WinSDK-NetFx35Tools-x86', 'InstallationFolder', null, RegistryView.Default, RegistryView.Registry32))" />
+        <property name="SDK40ToolsPath" value="$([MSBuild]::GetRegistryValueFromView('HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.6.1\WinSDK-NetFx40Tools-x86', 'InstallationFolder', null, RegistryView.Default, RegistryView.Registry32))" />
         <property name="WindowsSDK80Path" value="$(Registry:HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v8.1@InstallationFolder)" />
         <property name="VsInstallRoot" value="$([MSBuild]::GetVsInstallRoot())" />
         <property name="MSBuildToolsRoot" value="$(VsInstallRoot)\MSBuild" />
```

@AndyGerlicher do you think that's a reasonable fix?

**Comment by gimpf** [comment]
Thanks!

**Comment by rainersigwald** [comment]
Thanks for the report!
