### ISSUE TITLE
wrong link to VS2015 ultimate download

### ISSUE THREAD

**Issue by chipitsine** [Microsoft/msbuild#205]
compiling documentation https://github.com/Microsoft/msbuild/wiki/Building%20Testing%20and%20Debugging says that "VS2015 Ultimate CTP6 might be downloaded from http://www.visualstudio.com/downloads/visual-studio-2015-ctp-vs", however, there's no such edition available for download

please provide correct download instruction/link

**Comment by akoeplinger** [comment]
Now that Visual Studio 2015 is released you can download the Community Edition  (the CTPs were preview releases).

**Comment by chipitsine** [comment]
anyway, link provided is wrong and must be fixed.
also, Community Edition is not capable of running "visual studio command prompt", tell me how did you manage to get it working, please ?

**Comment by akoeplinger** [comment]
I don't have Community edition here, but I assumed it also created a link in Start Menu > Visual Studio 2015 > Visual Studio Tools > Developer Command Prompt for VS2015.

If it's not there, you can try launching it with `cmd.exe /k "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\VsDevCmd.bat"`

**Comment by chipitsine** [comment]
acually, there's VsDev.Cmd.bat installed with VS2015 Community edition (while stackoverflow.com says that Community edition is not provided with command prompt thing).

VsDevCmd.bat does not work for me (it just closes without going to command prompt), so if you are going to rewrite compile guide for Community edition (instead of Ultimate edition CTP), it would be better to provide developers with complete step by step guide how to compile.

current guide is wrong anyway

**Comment by akoeplinger** [comment]
You can't double click the VsDev.Cmd.bat (it just sets some variables), you need to launch it from an new cmd instance, that's why I posted the cmd.exe /k command above.

I agree that there should be a more detailed guide if Community edition doesn't have the shortcut in start menu.

**Comment by AndyGerlicher** [comment]
I updated the link to point to RTM. Odd, I had no idea that the Community edition didn't create a command line link. I think I'll just update the build.cmd to call it for you, other repos do that now as well.

**Comment by dhusemann** [comment]
Odd I have a link for community edition on my install. not sure if there was something that had to be checked in setup to get it or not at this point.
