### ISSUE TITLE
Suggestion: add git hash to msbuild version output

### ISSUE THREAD

**Issue by jcouv** [Microsoft/msbuild#2060]
The suggestion is to include part of the git commit hash into the output of the command-line tool: `Microsoft (R) Build Engine version <version> (<hash>)`

This is a feature we added to Roslyn (`csc.exe` and `vbc.exe`) [recently](https://github.com/dotnet/roslyn/pull/17537). It is pretty handy for us. I think it may be useful on `msbuild.exe` as well.

```
>msbuild
Microsoft (R) Build Engine version 15.3.124.61808

>csc
Microsoft (R) Visual C# Compiler version 2.3.0.61703 (a255d491)
```

FYI @rainersigwald

**Comment by rainersigwald** [comment]
An excellent idea, tracked by https://github.com/Microsoft/msbuild/issues/918. Note that you can get a commit from just our version, though, using a script in one of the NuGet packages we use:

```
s:\msbuild>powershell packages\nerdbank.gitversioning\1.5.46\tools\Get-CommitId.ps1 15.3.124.61808
70f1aaadd4eb5cb4cdf123f7b735c9ffe11ed206
```
