### ISSUE TITLE
The "CheckFileSystemCaseSensitive" task failed unexpectedly, Could not load file or assembly 'System.IO.FileSystem

### ISSUE THREAD

**Issue by dkent600** [Microsoft/msbuild#2061]
To my Visual Studio 2017, ASP.NET Core, MVC web project I just added the Microsoft.TypeScript.MSBuild NuGet package v2.3.1, and simultaneously updated my ASP.NET Core assemblies from 1.0.* to 1.1.1.  Now suddenly when I build my project I get the following exception:

    Severity	Code	Description	Project	File	Line	Suppression State
    Error	MSB4018	The "CheckFileSystemCaseSensitive" task failed unexpectedly.
    System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
    File name: 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
       at TypeScript.Tasks.CheckFileSystemCaseSensitive.Execute()
       at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
       at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

Double-clicking on the exception message takes one to these lines in the file Microsoft.TypeScript.targets:

    <Target Name="CheckFileSystemCaseSensitive">
        <CheckFileSystemCaseSensitive
           MSBuildThisFileFullPath="$(MSBuildThisFileFullPath)" >
          <Output TaskParameter="IsFileSystemCaseSensitive"  PropertyName="IsFileSystemCaseSensitive" />
        </CheckFileSystemCaseSensitive>
    </Target>

where it says that "MSBuildThisFileFullPath is not defined".

I've tried adding references to `NETStandard.Library`, as suggested here:  https://github.com/dotnet/corefx/issues/16206, but that doesn't make any difference.

The diagnostic MSBuild output looks like this:

    1>Target "CheckFileSystemCaseSensitive" in file "C:\Users\dkent\.nuget\packages\microsoft.typescript.msbuild\2.3.1\tools\netstandard1.3\Microsoft.TypeScript.targets":
    1>  Using "CheckFileSystemCaseSensitive" task from assembly "C:\Users\dkent\.nuget\packages\microsoft.typescript.msbuild\2.3.1\tools\netstandard1.3\TypeScript.Tasks.dll".
    1>  Task "CheckFileSystemCaseSensitive"
    1>    Task Parameter:MSBuildThisFileFullPath=C:\Users\dkent\.nuget\packages\microsoft.typescript.msbuild\2.3.1\tools\netstandard1.3\Microsoft.TypeScript.targets
    1>    [...]\.nuget\packages\microsoft.typescript.msbuild\2.3.1\tools\netstandard1.3\Microsoft.TypeScript.targets(172,5): error MSB4018: The "CheckFileSystemCaseSensitive" task failed unexpectedly.
    1>    [...]\.nuget\packages\microsoft.typescript.msbuild\2.3.1\tools\netstandard1.3\Microsoft.TypeScript.targets(172,5): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
    1>    [...]\.nuget\packages\microsoft.typescript.msbuild\2.3.1\tools\netstandard1.3\Microsoft.TypeScript.targets(172,5): error MSB4018: File name: 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
    1>    [...]\.nuget\packages\microsoft.typescript.msbuild\2.3.1\tools\netstandard1.3\Microsoft.TypeScript.targets(172,5): error MSB4018:    at TypeScript.Tasks.CheckFileSystemCaseSensitive.Execute()
    1>    [...]\.nuget\packages\microsoft.typescript.msbuild\2.3.1\tools\netstandard1.3\Microsoft.TypeScript.targets(172,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
    1>    [...]\.nuget\packages\microsoft.typescript.msbuild\2.3.1\tools\netstandard1.3\Microsoft.TypeScript.targets(172,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
    1>  Done executing task "CheckFileSystemCaseSensitive" -- FAILED.

**Comment by dkent600** [comment]
Is there at least a work-around for this?

**Comment by dkent600** [comment]
More info:

If I delete the "obj" folder in the root of the project, then the build succeeds until I close and restart Visual Studio.  Rebuilding after restarting Visual Studio then again hits the error.  I can delete the obj folder and again the error disappears.

Rebuild Solution makes no difference, nor does closing and reopening either the project or the solution.

**Comment by AnsonWooBizCloud** [comment]
I hit this error too, and you workaround works for me (delete the obj folder), thank you!
I hope Microsoft will fixed it soon, quite annoying

**Comment by rainersigwald** [comment]
This is a bug in the `CheckFileSystemCaseSensitive` task, which is distributed by TypeScript. Because it doesn't ship its dependency `System.IO.FileSystem.dll`, it only works if another task has loaded `System.IO.FileSystem` earlier in the build. On an incremental build, that's not happening (I suspect that the compiler task is what loads it when it works).

One possible workaround would be to define a property to disable incremental builds in your project. This will cause build times to increase (because the compiler will run all the time), but will force the compiler to run. If I'm right that the compiler is what's forcing the load, this should work around the problem.

You can try that by setting the property

```csproj
<NonExistentFile>WorkaroundForTypescriptBuildTask</NonExistentFile>
```

in your project file.

This class of bug could be alleviated by #1542.

**Comment by rainersigwald** [comment]
This issue was moved to Microsoft/TypeScript#15664
