### ISSUE TITLE
Compile Remove with a wildcard removes more files than it should

### ISSUE THREAD

**Issue by davkean** [Microsoft/msbuild#2069]
_From @bording on May 5, 2017 23:20_

I'm not entirely sure where this bug is best filed, but since I'm using the new project system to reproduce it, I figured I'd start here.

I've got a NuGet package that brings in source files via the contentFiles mechanism. I need to be able to exclude certain files, so I added a `Compile` item with a wildcard pattern to remove them. That works correctly, however it seems to also remove files that aren't part of the pattern as well.

I've pushed up a repo that demonstrates the problem here: https://github.com/bording/GlobbingProblem

If you look at the project file, you can see the following:

```
 <ItemGroup>
    <Compile Remove="$(NuGetPackageRoot)**\Audit\*.cs" />
  </ItemGroup>
```

That removes the 5 files in the Audit folder as expected, but it also removes `ConfigureEndpointLearningTransport.cs`, which doesn't match the pattern at all.

Before remove:
![before](https://cloud.githubusercontent.com/assets/753669/25767110/c2ca36f8-31c4-11e7-96ae-57e4cf920ddd.png)

After remove:
![after](https://cloud.githubusercontent.com/assets/753669/25767113/c72633b4-31c4-11e7-8113-8e3056baaa79.png)

I've experimented with different wildcard patterns, and I can't see any discernible pattern to explain the behavior.

For example:
```
  <ItemGroup>
    <Compile Remove="$(NuGetPackageRoot)**\EndpointTemplates\*.cs" />
  </ItemGroup>
```
Removes files from the Pipeline and Recoverability folders as well.

_Copied from original issue: dotnet/project-system#2134_

**Comment by thomaslevesque** [comment]
See also https://github.com/FakeItEasy/FakeItEasy/pull/1103 for another example. This is really weird. Looks like a serious bug in the globbing algorithm.

**Comment by davkean** [comment]
@AndyGerlicher Can you please triage this?

**Comment by cdmihai** [comment]
This may be a bug in `ImmutableList<T>.Builder`. If I do the following replacement, everything works:

```c#
                //listBuilder.RemoveAll(itemData => items.Contains(itemData.Item));

                var itemDatasToRemove = listBuilder.Where(itemData => items.Contains(itemData.Item)).ToList();

                foreach (var itemToRemove in itemDatasToRemove)
                {
                    listBuilder.Remove(itemToRemove);
                }
```

It's quite hard to write a unit test for this. I'll try and reduce the repro and open a bug against corefx, and then go ahead and check this fix in.

**Comment by cdmihai** [comment]
Worked around in #2162
