### ISSUE TITLE
Properties set in targets from referenced packages not always propagated

### ISSUE THREAD

**Issue by jhickson** [Microsoft/msbuild#2080]
I've found that if I have a project that references a package with build targets or prop files then if those files contain versioning-related properties then the values set are not available in the importing project.

For instance if I have a package called Versioner that contains this Versioning.props file:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <VersionPrefix>1.2.3</VersionPrefix>
    <VersionSuffix>alpha-7</VersionSuffix>
  </PropertyGroup>
</Project>
```
then I package this up into Versioner-0.1.0-alpha1.nupkg and reference it in a project called Versionee.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Versioner" Version="0.1.0-alpha1" />
  </ItemGroup>
</Project>
```
then the assembly produced for this project by `dotnet build` is versioned as `1.0.0` as is the package produced by `dotnet pack`. If, however, I directly import the props file using
```xml
<Import Project="C:\Users\j.hickson\.nuget\packages\versioner\0.1.0-alpha1\build\Versioning.props" />
```
then the versioning is as expected - i.e. the assembly is `0.1.0` and the package `0.1.0-alpha1`.

This is not a problem for all properties: for instance, setting `GenerateAssemblyVersionAttribute` in the props file is propagated to the referencing project.

I've attached zipped solutions for Versioner and Versionee. Unfortunately I can't attach the nupkg for Versioner.
[Versionee.zip](https://github.com/Microsoft/msbuild/files/987257/Versionee.zip)

[Versioner.zip](https://github.com/Microsoft/msbuild/files/987258/Versioner.zip)

```bash
$ dotnet --info
.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.3
```

```bash
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise>msbuild /version
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

15.1.1012.6693
```

**Comment by rainersigwald** [comment]
After restoring using your package, can you run

```
dotnet msbuild /pp:preprocessed.xml
```

To get the full, expanded version of the project file as MSBuild sees it, and share that?

**Comment by jhickson** [comment]
I've attached it as a text file:

[preprocessed.txt](https://github.com/Microsoft/msbuild/files/987317/preprocessed.txt)

**Comment by dsplaisted** [comment]
I think this is a NuGet issue where by default it excluded build assets on dependencies when you create a package. @emgarten

**Comment by jhickson** [comment]
@rainersigwald I wasn't aware that was necessary but in the fuller version of this where I am also getting the issue the props file name does match the package id.

@dsplaisted The package does contain the props file and is referenced. The fact that I can manually add an import line referencing the props file in its nuget cache location shows that.

In the fuller version I have mentioned I also set various properties (to False) such as `GenerateAssemblyVersionAttribute` and those are honoured. So I believe that it is being imported.

**Comment by emgarten** [comment]
Pack uses the output from restore to create the nupkg. This ensures that package created will work the same as the project if they are swapped. Restore excludes package imports to ensure that the 1st and 2nd restores give the same result.

We're looking at improving this on the NuGet side since this is a common scenario, but the current behavior is that packages cannot contribute to the identity of a project or package.

You can work around this by generating a props file outside of the package and importing that into your projects.

**Comment by jhickson** [comment]
OK, so the version settings are ignored because they would contribute to the importing project's identity but other settings such as the Generate*Attribute ones are not? That would explain it.

I'm already doing what you mention but was hoping to reduce what the consumer needed to do. 

Thanks. Q

**Comment by jhickson** [comment]
Please ignore the trailing Q!

**Comment by emgarten** [comment]
GenerateAttribute would be applied during the build, which is after restore.

**Comment by jhickson** [comment]
OK. By the way, are there any docs for this?

**Comment by rainersigwald** [comment]
Closing MSBuild issue--but links to docs and the NuGet issues you mentioned would be awesome @emgarten.

**Comment by emgarten** [comment]
Related to nuget issue: https://github.com/NuGet/Home/issues/4790
