### ISSUE TITLE
Add /p:EnableCppCoreCheck support

### ISSUE THREAD

**Issue by mloskot** [Microsoft/msbuild#2086]
TL;TR: Allow to specify [CppCoreCheck](https://github.com/Microsoft/GSL) analysis in `msbuild.exe` command line

Currently, in VS 2017 (including Preview) , `EnableCppCoreCheck` can only be set via the VS IDE user interface, in project _Properties > Code Analysis > Extensions > Enable C++ Core Check_

There is no way to set `EnableCppCoreCheck` via the command line with `/p` parameter.

`RunCodeAnalysis` property is settable via command line `/p` parameter:
```
msbuild /p:Configuration=Debug /p:RunCodeAnalysis=true test.vcxproj
```

It seems desired to add `EnableCppCoreCheck` to the set of properties overridable via command line.

**Comment by mloskot** [comment]
I'm running MSBuild *15.3.118.39484* from the latest VS2017 Preview and it looks like passing `/p:EnableCppCoreCheck=true` is effective and `EspXEngine.dll` is added as `/analyze:plugin`"

```
F:\workshop\LibStringTest>msbuild LibStringTest.vcxproj /p:RunCodeAnalysis=true /p:EnableCppCoreCheck=true
Microsoft (R) Build Engine version 15.3.118.39484
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2017-05-16 13:56:33.
Project "F:\workshop\LibStringTest\LibStringTest.vcxproj" on node 1 (default targets).
InitializeBuildStatus:
  Creating "x64\Debug\LibStringTest.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  All outputs are up-to-date.
  C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\VC\Tools\MSVC\14.11.25301\bin\HostX86\x64\CL.exe /c /ZI /nologo /W4 /WX- /diagnostics:classic /Od /D CODE_ANALYSIS /D _DEBUG /D _CONSOLE /D _UNICODE /D UNICODE /Gm /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"x64\Debug\\" /Fd"x64\Debug\vc141.pdb" /Gd /TP /analyze /analyze:plugin"C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\VC\Tools\MSVC\14.11.25301\\bin\HostX86\x86\EspXEngine.dll" /analyze:plugin"C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\VC\Tools\MSVC\14.11.25301\\bin\HostX86\x86\localespc.dll" /errorReport:queue   /analyze:quiet LibStringTest.cpp
```

Could anyone confirm this is indeed expected and `/p:EnableCppCoreCheck=true` is supported?

AFAICT, I have none of these properties added to my `.vcxproj` 

```
<RunCodeAnalysis>true</RunCodeAnalysis>
<EnableCppCoreCheck>true</EnableCppCoreCheck>
```

**Comment by mloskot** [comment]
I've confirmed `/p:EnableCppCoreCheck=true` works also with **15.1.1012.6693**. All good. Sorry for false alarm.

**Comment by neilmacintosh** [comment]
Hahahah. You beat me to it @mloskot :-). Yes, EnableCppCoreCheck is supported and should work for you.

**Comment by mloskot** [comment]
@neilmacintosh No idea why it did not work for me before. Must be CMake interference or something. Great it's working
