### ISSUE TITLE
MSBuild build output directory should be able to be used as a valid toolset

### ISSUE THREAD

**Issue by KirillOsenkov** [microsoft/msbuild#2108]
Currently when you open the MSBuild.sln solution, set MSBuild project as startup and F5 it can only build the most rudimentary projects, because the layout of the output directory is different than the retail toolset layout.

We should strive towards a future where the build output of the MSBuild solution approaches the retail toolset layout as closely as possible, so that it's possible to simply debug using F5.

I understand that this is a difficult item and longer term, but it'd be nice to track towards it as it would improve our own productivity and empower the contributors.

Additionally, if we keep working from the other end - by simplifying the toolset and moving things out to NuGet packages instead of hardcoding in the toolset, we move the goal closer as well.

**Comment by AndyGerlicher** [comment]
Agreed. Also FYI if you run `cibuild.cmd --bootstrap-only` it produces a `bin\Bootstrap` output that is mostly usable.

**Comment by KirillOsenkov** [comment]
I've tried `build -configuration Release /p:CreateBootstrap=true` and it works very nicely. The resulting toolset is almost identical to the actual layout in VS. I was able to successfully build using it on a pristine Azure VM.

Closing this.
