### ISSUE TITLE
MSBuild Task support "launch and resume" [Feature Request]

### ISSUE THREAD

**Issue by yuehuang010** [microsoft/msbuild#2120]
In current model, the MSBuild Task executes and waits for all child project to complete before resuming.  This is great for considering when waiting for Outputs.  However, to maximize Parallelism, references sometimes logic doesn't need the output right away.  In this regard, add an option to start building the child projects and resuming running current project.

When the current project needs the output of the child project, it may invoke a blocking call for the result.

Task Outputs may not be available and should probably warn if queuing for it.

Thanks

**Comment by rainersigwald** [comment]
So the idea is to provide a hint that some p2p _will_ be desired, so it can be preemptively built?

Can you explain a bit more about how you would use this feature in targets? And what scenarios it benefits?

**Comment by rainersigwald** [comment]
Team triage: closing due to age. If this comes up again, please let us know and we can reactivate.
