### ISSUE TITLE
MSBuild always reports "Build succeeded" even for non-"build" targets (e.g. clean)

### ISSUE THREAD

**Issue by abock** [Microsoft/msbuild#2126]
The status messages could use some improvement in MSBuild. Instead of hard-coding "Build succeeded", MSBuild should report "$(Target) succeeded " or "$(Target) failed" for example.

I believe this is a bit of a functional difference between Mono's `xbuild` and `msbuild`. In 15.2 we switched to `msbuild` by default, deprecating `xbuild`. As such, we had a Xamarin platform bug filed for this issue.

* [Original Xamarin bug](https://bugzilla.xamarin.com/show_bug.cgi?id=56753)
* [Screencast of issue](https://www.screencast.com/t/gpcdoMnZ)

**Comment by rainersigwald** [comment]
@radical is this really something where `xbuild` logged differently? That's surprising.

Team triage: This is not something we expect to change. An invocation of MSBuild is a "build", even if you specify targets that do something that you don't think of as a build. See related https://github.com/Microsoft/msbuild/issues/1179.

There is possibly some room to change the log message for clarity, but I can't come up with a particularly good phrasing. In Slack there was a suggestion of `Build ({specified_target}) completed`. I don't like changing the string out of fear of breaking people grepping for `Build succeeded` . . .

**Comment by radical** [comment]
`xbuild` does the same thing as `msbuild`, because of what @rainersigwald - any invocation is a "build". I agree that we shouldn't be changing this in `msbuild`. But VSMac (and VS, I assume) uses it's own logger, which has enough context to give better info as status messages, if needed.

**Comment by radical** [comment]
@abock are you seeing a changed behavior? I couldn't see any difference on VSMac at least. And the original bug doesn't really say that this is a regression.
