### ISSUE TITLE
Add build version information to assembly attributes for .NET Core build

### ISSUE THREAD

**Issue by dsplaisted** [Microsoft/msbuild#214]
The assemblies we build for .NET Core should have attributes in them (AssemblyFileVersionAttribute, for example) with a version that matches the NuGet package version they are part of.

**Comment by rainersigwald** [comment]
It might be nice to tie this in with #256 so all our versions come from the same place.

**Comment by AArnott** [comment]
These assembly attributes are generated by nerdbank.gitversioning, which is already used by this project, I believe. I guess it doesn't work on the .NET Core build because LibGit2Sharp hasn't been ported to .NET Core yet. But I'm really close to just publishing a package of my fork to add that.

**Comment by rainersigwald** [comment]
Whoops, didn't see this bug when I fixed this for all full-framework-hosted builds (like the "official" nuget-package-producing ones) in a14c1688e622af059b18ab31966bd87bc90a52a7. As soon as there's a netcore-compatible Nerdbank.GitVersioning, it should work for all of our builds.

**Comment by jeffkl** [comment]
I'm going to close this as our official builds are on Windows and are stamped correctly.  As soon as NerdBank.GitVersioning/LibGit2Sharp support .NET Core it will happen for local dev builds as well.
