### ISSUE TITLE
xmlpeek does not allow DTD

### ISSUE THREAD

**Issue by ellie2013** [Microsoft/msbuild#2141]
We are trying to use the external entity in XML. When we run msbuild, it calls the xmlpeek task, which seems does not allow DTD by default according to the error from xmlpeek task attached below.

error MSB3733: Input file "..." cannot be opened. For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.

Is there anyway to change the property of DtdProcessing for the xmlpeek task.

**Comment by AndyGerlicher** [comment]
Team Triage:
This seems reasonable. The security settings should be OK to turn off since you should only open project files from a trusted source anyway. This would need to be turned off be default but could be opt-in. Marking as up-for-grabs.

**Comment by lassana** [comment]
Any progress on this? This behavior makes impossible to read values from Apple plist files. Thus, if the file starts with:

    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    ...

it can be read by XmlPeek task.

**Comment by fonix232** [comment]
I'd like to second this issue. Using latest Visual Studio For Mac, which in theory uses the latest release of MSBuild, fails on the XmlPeek task for iOS `.plist` files. However XmlPoke works just fine.
