### ISSUE TITLE
Switch CodeTaskFactory to use Roslyn

### ISSUE THREAD

**Issue by KirillOsenkov** [Microsoft/msbuild#2158]
I think CodeTaskFactory uses CodeDOM. Since we already have Roslyn in the toolset everywhere, switch the CodeTaskFactory to use it for compilation.

**Comment by rainersigwald** [comment]
This is tracked by https://github.com/Microsoft/msbuild/issues/304.

**Comment by jeffkl** [comment]
Try out https://www.nuget.org/packages/RoslynCodeTaskFactory
