### ISSUE TITLE
$(MSBuildThisFileDirectory) is empty string when using ProjectRoomElement.ReloadFrom(XmlReader)

### ISSUE THREAD

**Issue by jviau** [Microsoft/msbuild#2159]
When a project file is first loaded from disk but then reloaded using `ProjectRootElement.ReloadFrom(XmlReader)` (with its current XML), the property `$(MSBuildThisFileDirectory)` is an empty string, yet `Project.FullPath` and `$(MSBuildProjectDirectory)` still retain their old values.

Project file Project.proj:

``` xml
<Project>
  <PropertyGroup>
    <ProjectDirectory>$(MSBuildThisFileDirectory)</ProjectDirectory>
  </PropertyGroup>
</Project>
```

Code:
``` Csharp
var project = new Project("Project.proj");
project.Xml.ReloadFrom(System.Xml.XmlReader.Create(new StringReader(project.Xml.RawXml)));
project.Xml.Save(new StringWriter());
project.ReevaluateIfNecessary();

// outputs ""
Console.WriteLine($"MSBuildThisFileDirectory property: {project.GetPropertyValue("ProjectDirectory")}");

// outputs the project directory
Console.WriteLine($"MSBuildProjectDirectory property: {project.GetPropertyValue("MSBuildProjectDirectory")}");

// FullPath has not changed from initial load
Console.WriteLine($"Project.proj FullPath: {project.FullPath}");
```

Is this intended behavior? I would assume that since `$(MSBuildProjectDirectory)` has not changed, then `$(MSBuildThisFileDirectory)` would not have changed either.

**Comment by cdmihai** [comment]
As discussed with @jviau, reloading from memory should preserve the initial project path.
