### ISSUE TITLE
The default XML namespace of the project must be the MSBuild XML namespace

### ISSUE THREAD

**Issue by avikenjale** [Microsoft/msbuild#2163]
I have following scenario about this issue:
1. I have developed my .net core webApi with Visual studio 2017 
2. Locally it builds and runs as expected.
3. We use Bamboo for build and deployment.
4. When I configure build plan under bamboo I'm getting error for one of project under solution as `error MSB4041: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.`.

I have following setting for MSBuild:
![image](https://cloud.githubusercontent.com/assets/6217482/26735145/a995b9e8-478e-11e7-953a-1888445a4922.png)

**Comment by rainersigwald** [comment]
To build a .NET Core project (using the new, more compact XML), you must use MSBuild 15 or higher. This is the error you get when using an older MSBuild, and I see that you're specifying `MSBuild v14.0 (32bit)` in the configuration you posted.

You'll need to select whatever Bamboo calls MSBuild v15 (or Visual Studio 2017).

**Comment by avikenjale** [comment]
@rainersigwald, I installed MSBuild 15.0 on my Bamboo server, however now I am running with following error:
>error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

Following is my one of BuinessLibrary.csproj file:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RuntimeFrameworkVersion>1.0.4</RuntimeFrameworkVersion>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>netstandard1.6</TargetFramework>
  </PropertyGroup>
</Project>
```

WebApi.csproj
```
<Project Sdk="Microsoft.NET.Sdk.Web">
<PropertyGroup>
  <RuntimeFrameworkVersion>1.0.4</RuntimeFrameworkVersion>
</PropertyGroup>
<PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Controllers\" />
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Formatters.Xml" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.2" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.2" />
    <PackageReference Include="System.Linq" Version="4.3.0" />
    <PackageReference Include="System.Threading" Version="4.3.0" />
  </ItemGroup>
<ItemGroup>
    <ProjectReference Include="..\BusinessLibrary\BusinessLibrary.csproj" />
 </ItemGroup>
</Project>
```

**Comment by rainersigwald** [comment]
@avikenjale How did you install MSBuild 15? To build SDK projects, you must install Visual Studio with the ".NET Core cross-platform development" workload selected.

**Comment by avikenjale** [comment]
@rainersigwald , I followed these steps:

1. On the Visual Studio download page, expand Other Tools and Frameworks at the bottom of the page
Download the Visual Studio build tools
2. You can then use the GUI to do the installation, or you can script the installation of msbuild:

`vs_buildtools.exe --add Microsoft.VisualStudio.Workload.MSBuildTools --quiet`

**Comment by rainersigwald** [comment]
@avikenjale As of today, that won't work to build this type of project--see #1697 for details.

**Comment by avikenjale** [comment]
@rainersigwald , so what is workaround for this? I need to get it done as need to provide WebAPI for testing.

**Comment by avikenjale** [comment]
@ravipal, any idea?

**Comment by rainersigwald** [comment]
@avikenjale Install Visual Studio 2017 (not Build Tools but the full VS) on your build server.

**Comment by avikenjale** [comment]
@rainersigwald , you mean just installing msbuild tool 15.0 will not work? this is strange? then for my information, what is the purpose of msbuild 15.0 to install on build server? I mean, for which type of project this will support?

**Comment by rainersigwald** [comment]
@avikenjale Correct. This is discussed in detail in the bug I linked you to #1697, and the right place to ask further clarifying questions is there.
