### ISSUE TITLE
VS2017 publish: project.assets.json doesn't have a target for .NETCoreApp,Version=v1.1

### ISSUE THREAD

**Issue by kosa-gyula-77** [Microsoft/msbuild#2196]
Publishing the _xunitCore1.0_ project in the solution attached from Visual Studio 2017 fails with the following error:

_Assets file 'C:\Users\xxx\Documents\Visual Studio 2017\Projects\xunitCore1.0\xunitCore1.0\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v1.1'. Ensure you have restored this project for TargetFramework='netcoreapp1.1' and RuntimeIdentifier=''._

Could you please help in identifying why I'm getting this error? xunitCore1.0 targets netcoreapp1.0.

[xunitCore1.0.zip](https://github.com/Microsoft/msbuild/files/1061297/xunitCore1.0.zip)

Thanks.

**Comment by rainersigwald** [comment]
This issue was moved to dotnet/sdk#1321
