### ISSUE TITLE
Git clone of MSBuild source won't build using Visual Studio 2017 Community Edition

### ISSUE THREAD

**Issue by nikkilocke** [Microsoft/msbuild#2211]
I cloned the repository, and loaded src/MSBuild.sln into Visual Studio 2017 Community Edition.

Microsoft.Build, Microsoft,Build.Framework, Microsoft.Build.Tasks, Microsoft.Build.Utilities, MSBuild and MSBuildTaskHost all failed to load with the error: 
The imported project "E:\TEMP\msbuild\packages\Nerdbank.GitVersioning\1.5.46\build\dotnet\Nerdbank.GitVersioning.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  E:\TEMP\msbuild\src\dir.targets

**Comment by jeffkl** [comment]
@nikkilocke I think you missed a step from our build instructions: https://github.com/Microsoft/msbuild#building-msbuild-with-visual-studio-2017

Please run `cibuild.cmd` first before loading MSBuild.sln.  We are working on removing this requirement but other work has taken priority.

**Comment by nikkilocke** [comment]
cibuild failed with a similar error. On 12 Jun 2017 6:33 pm, Jeff Kluge <notifications@github.com> wrote:@nikkilocke I think you missed a step from our build instructions: https://github.com/Microsoft/msbuild#building-msbuild-with-visual-studio-2017
Please run cibuild.cmd first before loading MSBuild.sln.  We are working on removing this requirement but other work has taken priority.

**Comment by rainersigwald** [comment]
@nikkilocke Can you post the exact error?

**Comment by nikkilocke** [comment]
E:\>cd temp\msbuild

E:\TEMP\msbuild>cibuild
Using Configuration: Debug
Tools are already initialized.

** Rebuilding MSBuild with downloaded binaries

** Using the MSBuild in path: MSBuild.exe
** Using runtime host in path:
** "MSBuild.exe" /nodeReuse:false "E:\TEMP\msbuild\build.proj" /m 
/verbosity:minimal /t:Rebuild /p:Configuration=Debug /p:"SkipBuildPackages=true" 
/fileloggerparameters:Verbosity=diag;LogFile="E:\TEMP\msbuild
\msbuild_bootstrap_build-Full.log"
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring build tools...
  log  : Restoring packages for E:\TEMP\msbuild\src\.nuget\project.json...
EXEC : error : Unable to resolve 'Nerdbank.GitVersioning (>= 1.6.46)' for '.NET
Framework,Version=v4.6'. [E:\TEMP\msbuild\build.proj]
  log  : Writing lock file to disk. Path: E:\TEMP\msbuild\src\.nuget\project.lo
  ck.json
  log  : Generating MSBuild file E:\TEMP\msbuild\src\.nuget\.nuget.nuget.target
  s.
  log  : Generating MSBuild file E:\TEMP\msbuild\src\.nuget\.nuget.nuget.props.
  log  : Restore failed in 9030ms for E:\TEMP\msbuild\src\.nuget\project.json.

  Errors in E:\TEMP\msbuild\src\.nuget\project.json
      Unable to resolve 'Nerdbank.GitVersioning (>= 1.6.46)' for '.NETFramework
  ,Version=v4.6'.
E:\TEMP\msbuild\src\.nuget\packageLoad.targets(41,5): error MSB3073: The comman
d ""E:\TEMP\msbuild\Tools\dotnetcli/dotnet.exe" restore --legacy-packages-direc
tory --packages E:\TEMP\msbuild\packages\ "E:\TEMP\msbuild\src\.nuget\project.j
son"" exited with code 1. [E:\TEMP\msbuild\build.proj]

    0 Warning(s)
    2 Error(s)
Time Elapsed 00:00:13.24

** Build completed. Exit code: 1

Bootstrap build failed with errorlevel 1

---------------------------------------
- cibuild.cmd FAILED. -
---------------------------------------

E:\TEMP\msbuild>

Rainer Sigwald wrote:
> @nikkilocke Can you post the exact error?
> 
> �
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Nikki Locke, Trumphurst Ltd.  PC & Unix consultancy & programming
http://www.trumphurst.com/

**Comment by rainersigwald** [comment]
@nikkilocke And there are no local changes? This

```
Unable to resolve 'Nerdbank.GitVersioning (>= 1.6.46)' for '.NETFramework,Version=v4.6'. 
```

looks fishy: our [reference to that package](https://github.com/Microsoft/msbuild/blob/daddbee97e937a87f3cda7bb3be3405df742c57d/src/.nuget/project.json#L4) is version 1.**5**.46.

**Comment by rainersigwald** [comment]
Closing due to lack of response--if anyone's still seeing this, I'm happy to reopen and investigate with you.
