### ISSUE TITLE
CSC : error CS2001: Source file 'C:\Windows\system32\config\systemprofile\AppData\Local\Temp\.NETPortable,Version=v4.5,Profile=Profile78.AssemblyAttributes.cs' could not be found

### ISSUE THREAD

**Issue by avikenjale** [Microsoft/msbuild#2212]
I am trying to build my project on `Bamboo` server, however receiving following error when building .NET core class library.

>Using shared compilation with compiler from directory: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Roslyn CSC : error CS2001: Source file 'C:\Windows\system32\config\systemprofile\AppData\Local\Temp.NETPortable,Version=v4.5,Profile=Profile78.AssemblyAttributes.cs' could not be found. [E:\bamboo-agent-home\xml-data\build-dir\Domain\Domain.csproj] Done Building Project "E:\bamboo-agent-home\xml-data\build-dir\Business\Business.csproj" (default targets) -- FAILED.

Unable to understand this error. On Local this works perfect even on command line - `MSBuild` command.

**Comment by davkean** [comment]
Can you dump your environment variables and paste them?

**Comment by rainersigwald** [comment]
This sounds like it might be related to https://github.com/Microsoft/msbuild/issues/1830 -- on the server, is the build running under the Local System account, or a "normal" user?

**Comment by dasMulli** [comment]
Seems like you also posted this question on SO: https://stackoverflow.com/questions/44507990/csc-error-cs2001-source-file-netportable-version-v4-5-profile-profile78-ass

Afaik Bamboo installs a windows service with the local system account by default

@avikenjale Did you try the suggestion to run Bamboo as a different user following [Atlassian's documentation](https://confluence.atlassian.com/bamboo/running-bamboo-as-a-windows-service-as-the-local-user-416580754.html)?

**Comment by rainersigwald** [comment]
Closing due to lack of response.
