### ISSUE TITLE
Clear error when Windows SDK is not installed (which causes NuGet to silently fail)

### ISSUE THREAD

**Issue by nateglims** [Microsoft/msbuild#224]
On a Windows 7 and 8 PC with a recent install of Visual Studio Community, there are a number of build errors. Nearly all of them are related to being unable to find xunit or dataflow packages.

I have tried manually install microsoft.tpl.dataflow, xunit, and the xunit runner through nuget, but it did not affect the issue.

Is there another dependency not described in the build steps? I didn't see anything obviously different in the logs on the CI server.

Build output:

C:\Program Files (x86)\Microsoft Visual Studio 14.0>cd \Projects\msbuild

C:\Projects\msbuild>build.cmd
** MSBuild Path: MSBuild.exe
** Building all sources
** "MSBuild.exe" "C:\Projects\msbuild\build.proj" /verbosity:minimal /nodeReuse:
false /fileloggerparameters:Verbosity=diag;LogFile="C:\Projects\msbuild\msbuild.
log"
Microsoft (R) Build Engine version 14.0.23107.0
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring NuGet packages...
  Microsoft.Build.Framework -> C:\Projects\msbuild\bin\Windows_NT\Debug\Microso
  ft.Build.Framework.dll
  Microsoft.Build.Utilities -> C:\Projects\msbuild\bin\Windows_NT\Debug\Microso
  ft.Build.Utilities.Core.dll
BackEnd\BuildManager\BuildManager.cs(18,30): error CS0234: The type or namespac
e name 'Dataflow' does not exist in the namespace 'System.Threading.Tasks' (are
 you missing an assembly reference?) [C:\Projects\msbuild\src\XMakeBuildEngine\
Microsoft.Build.csproj]
BackEnd\Components\Logging\LoggingService.cs(15,30): error CS0234: The type or
namespace name 'Dataflow' does not exist in the namespace 'System.Threading.Tas
ks' (are you missing an assembly reference?) [C:\Projects\msbuild\src\XMakeBuil
dEngine\Microsoft.Build.csproj]
BackEnd\Components\BuildRequestEngine\BuildRequestEngine.cs(16,30): error CS023
4: The type or namespace name 'Dataflow' does not exist in the namespace 'Syste
m.Threading.Tasks' (are you missing an assembly reference?) [C:\Projects\msbuil
d\src\XMakeBuildEngine\Microsoft.Build.csproj]
BackEnd\BuildManager\BuildManager.cs(208,17): error CS0246: The type or namespa
ce name 'ActionBlock<Action>' could not be found (are you missing a using direc
tive or an assembly reference?) [C:\Projects\msbuild\src\XMakeBuildEngine\Micro
soft.Build.csproj]
BackEnd\Components\BuildRequestEngine\BuildRequestEngine.cs(61,17): error CS024
6: The type or namespace name 'ActionBlock<Action>' could not be found (are you
 missing a using directive or an assembly reference?) [C:\Projects\msbuild\src\
XMakeBuildEngine\Microsoft.Build.csproj]
BackEnd\Components\Logging\LoggingService.cs(197,17): error CS0246: The type or
 namespace name 'BufferBlock<object>' could not be found (are you missing a usi
ng directive or an assembly reference?) [C:\Projects\msbuild\src\XMakeBuildEngi
ne\Microsoft.Build.csproj]
BackEnd\Components\Logging\LoggingService.cs(202,17): error CS0246: The type or
 namespace name 'ActionBlock<object>' could not be found (are you missing a usi
ng directive or an assembly reference?) [C:\Projects\msbuild\src\XMakeBuildEngi
ne\Microsoft.Build.csproj]
  Microsoft.Build.Tasks -> C:\Projects\msbuild\bin\Windows_NT\Debug\Microsoft.B
  uild.Tasks.Core.dll
Attribute_Tests.cs(12,7): error CS0246: The type or namespace name 'Xunit' coul
d not be found (are you missing a using directive or an assembly reference?) [C
:\Projects\msbuild\src\Framework\UnitTests\Microsoft.Build.Framework.UnitTests.
csproj]
BuildErrorEventArgs_Tests.cs(11,7): error CS0246: The type or namespace name 'X
unit' could not be found (are you missing a using directive or an assembly refe
rence?) [C:\Projects\msbuild\src\Framework\UnitTests\Microsoft.Build.Framework.
UnitTests.csproj]

    ... Removed some errors, but all of them are about Xunit and Fact...

EventArgs_Tests.cs(86,10): error CS0246: The type or namespace name 'Fact' coul
d not be found (are you missing a using directive or an assembly reference?) [C
:\Projects\msbuild\src\Framework\UnitTests\Microsoft.Build.Framework.UnitTests.
csproj]
  XmlFileLogger -> C:\Projects\msbuild\bin\Samples\Debug\XmlFileLogger\XmlFileL
  ogger.dll

    0 Warning(s)
    68 Error(s)
Time Elapsed 00:00:13.36
** Build completed. Exit code: 1

**Comment by rainersigwald** [comment]
That's interesting, thanks for the report.  Can you successfully build within Visual Studio?

I have a hunch; I'll set up a clean VM to test it out.

**Comment by nateglims** [comment]
No, I am unable to build in Visual Studio either.

**Comment by rainersigwald** [comment]
(My VM is still spinning up . . .)

Can you restore manually?  From the root of the repo
```cmd
packages\NuGet.exe restore src\MSBuild.sln

build.cmd
```

**Comment by nateglims** [comment]
It just says all the packages in packages.config are installed, and compatible. build.cmd still fails.

C:\Projects\msbuild>packages\NuGet.exe restore src\MSBuild.sln
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86
)\MSBuild\14.0\bin'.
All packages listed in packages.config are already installed.
Restoring packages for C:\Projects\msbuild\src\XMakeBuildEngine\project.json...
All packages are compatible with .NETFramework,Version=v4.5.1.
All packages are compatible with .NETFramework,Version=v4.6.
Generating MSBuild file Microsoft.Build.nuget.targets.
Restoring packages for C:\Projects\msbuild\src\Framework\UnitTests\project.json.
..
All packages are compatible with .NETFramework,Version=v4.5.1.
All packages are compatible with .NETFramework,Version=v4.6.
All packages are compatible with .NETFramework,Version=v4.5.1 (win-).
All packages are compatible with .NETFramework,Version=v4.6 (win-).
Generating MSBuild file Microsoft.Build.Framework.UnitTests.nuget.targets.
Restoring packages for C:\Projects\msbuild\src\XMakeCommandLine\UnitTests\projec
t.json...
All packages are compatible with .NETFramework,Version=v4.5.1.
All packages are compatible with .NETFramework,Version=v4.6.
All packages are compatible with .NETFramework,Version=v4.5.1 (win-).
All packages are compatible with .NETFramework,Version=v4.6 (win-).
Generating MSBuild file Microsoft.Build.CommandLine.UnitTests.nuget.targets.
Restoring packages for C:\Projects\msbuild\src\Utilities\UnitTests\project.json.
..
All packages are compatible with .NETFramework,Version=v4.5.1.
All packages are compatible with .NETFramework,Version=v4.6.
All packages are compatible with .NETFramework,Version=v4.5.1 (win-).
All packages are compatible with .NETFramework,Version=v4.6 (win-).
Generating MSBuild file Microsoft.Build.Utilities.UnitTests.nuget.targets.
Restoring packages for C:\Projects\msbuild\src\XMakeTasks\UnitTests\project.json
...
All packages are compatible with .NETFramework,Version=v4.5.1.
All packages are compatible with .NETFramework,Version=v4.6.
All packages are compatible with .NETFramework,Version=v4.5.1 (win-).
All packages are compatible with .NETFramework,Version=v4.6 (win-).
Generating MSBuild file Microsoft.Build.Tasks.UnitTests.nuget.targets.
Restoring packages for C:\Projects\msbuild\src\XMakeBuildEngine\UnitTests\projec
t.json...
All packages are compatible with .NETFramework,Version=v4.5.1.
All packages are compatible with .NETFramework,Version=v4.6.
All packages are compatible with .NETFramework,Version=v4.5.1 (win-).
All packages are compatible with .NETFramework,Version=v4.6 (win-).
Generating MSBuild file Microsoft.Build.Engine.UnitTests.nuget.targets.

**Comment by rainersigwald** [comment]
Hmm.  I still don't repro.  I set up a Win8.1 VM with VS2015 Community and was able to clone and run build.cmd from a "Developer Command Prompt for Visual Studio 2015", including tests.

I used some internal tooling to manage the OS + VS installation, which conceivably set something sneakily.

Can you put the (gigantic) MSBuild.log file on a gist and link it here?  It sounds like a problem with NuGet package resolution at build time (rather than restore time).

**Comment by rainersigwald** [comment]
Oh, and what commit are you trying to build?

**Comment by LordJZ** [comment]
Same thing, Windows 10, VS 2015 Pro. MSBuild.log: https://gist.github.com/LordJZ/cdf60e1a54a86bfd6ee6

**Comment by rainersigwald** [comment]
Thanks to @dsplaisted, I think we've narrowed down the problem.  Can you make sure you have the "Universal Windows App Development Tools and Windows SDK" installed?

![image](https://cloud.githubusercontent.com/assets/3347530/10229970/69396342-6840-11e5-8ef6-1f4434c4b36f.png)

That's the VS install option that installs the NuGet targets that read the project.json files and injects references.

@LordJZ, @nateglims -- can you please let me know whether installing that component resolves your problems?  If it does, I'll find a home for an FAQ or something about this.

**Comment by LordJZ** [comment]
Can confirm this works, thanks :+1:

**Comment by nateglims** [comment]
Worked for me also.

**Comment by rainersigwald** [comment]
Great, thanks folks.  I'll leave this issue open--we should detect and give a nice error for this condition.
