### ISSUE TITLE
Libraries from ExcludeAssets="Compile" package still get copied to the output

### ISSUE THREAD

**Issue by borgdylan** [Microsoft/msbuild#2243]
In a project where I only used the targets/props from a package I used the ```ExcludeAssets="Compile"``` metadata on the package reference. This correctly excluded those libraries from the compilation closure yet those assemblies still got copied to the output folder.

Is this an MSBuild or a NuGet issue? Please direct me in case I need to file this somewhere else.

**Comment by rainersigwald** [comment]
This issue was moved to NuGet/Home#5498
