### ISSUE TITLE
High allocation rates in Environment.GetEnvironmentVariable

### ISSUE THREAD

**Issue by sharwell** [Microsoft/msbuild#2247]
During a profiling pass on loading Roslyn.sln with Visual Studio 15.3 Preview 3, 6.2% of the overall GC allocations were caused by the call to `Environment.GetEnvironmentVariable("MSBUILDUSECASESENSITIVEITEMNAMES")` in ``LazyItemEvaluator`4+OperationBuilder``. Another 0.2% was caused by the call to `Environment.GetEnvironmentVariable("MSBUILDENABLEALLPROPERTYFUNCTIONS")` in ``Expander`2+Function`1.IsStaticMethodAvailable``. It appears that both of these cases can be cached for a substantial reduction in GC pressure.

**Comment by rainersigwald** [comment]
This is fixed by a change in #2246.
