### ISSUE TITLE
building msbuild xplat on osx

### ISSUE THREAD

**Issue by mat-mcloughlin** [Microsoft/msbuild#225]
I'm trying to use `build.pl` to build msbuild on osx (I'm assuming this is correct ?) but its throwing the following error:

```
/msbuild/src/Framework/Microsoft.Build.Framework.csproj: error : /msbuild/src/Framework/Microsoft.Build.Framework.csproj: ../dir.targets: Project file could not be imported, it was being imported by /msbuild/src/Framework/Microsoft.Build.Framework.csproj: /msbuild/src/dir.targets could not import "$(ToolsDir)\sign.targets"
```

I was wondering if you could offer some guidance as to what the problem may be?

**Comment by rainersigwald** [comment]
Unfortunately, the core team hasn't been focused on OS X builds recently.  I wouldn't be shocked if it's just broken at the moment.  @ValMenn, any chance that your Linux changes will also fix this?

**Comment by wjk** [comment]
I’m getting a similar error on my OS X machine.

    /Volumes/Development/GitHub/Microsoft/msbuild/build.proj: error : /Volumes/Development/GitHub/Microsoft/msbuild/build.proj: Invalid static method invocation syntax ''

**Comment by cdmihai** [comment]
We are currently working on getting MSBuild to build on OSX and Linux.

**Comment by JunielKatarn** [comment]
@cdmihai I'm interested in contributing to the xplat efforts for OSX and Linux.
Can you pleas point me in the right direction?

**Comment by cdmihai** [comment]
Sure!

PR #374 makes OSX compile (but not run). Most likely it will get merged into xplat tomorrow.
PR #377 is work in progress to get a CI build for OSX that currently just compiles, without running the tests.

I'm currently using an old mono msbuild build to build on OSX. It would be awesome if you could change cibuild.sh to use XBuild instead of the mono build. By doing that, all machine specific dependencies will be gone and everyone would be able to compile msbuild on OSX (not just my machine).

XBuild didn't work for me, but I did not investigate it in depth. My plan was to just dump a zip of my mono build into azure and download it in cibuild.sh, before building. But if you can get xbuild going, that would be great! Edit lines 73 and 17 to make it build with XBuild (https://github.com/cdmihai/msbuild/blob/ciscript/cibuild.sh).

**Comment by JunielKatarn** [comment]
> It would be awesome if you could change cibuild.sh to use XBuild instead of the mono build.

Need a little more context. You mean cibuil.sh uses `mono` as a command to build, where it should now be using `xbuild`?
I guess it should also update the appropriate command arguments, right?

**Comment by JunielKatarn** [comment]
@cdmihai I was able to update the script to use `xbuild`, but I couldn't find a way to make a pull request to your fork.
Anyway, here is the commit. Please let me know where to PR/submit it.

https://github.com/JunielKatarn/msbuild/commit/ddcd23f64587573e123f41d6fe435bf447429214

**Comment by cdmihai** [comment]
@JunielKatarn 

Thanks for upgrading the script. Did you try and build MSBuild with XBuild? Did it work?

In the meantime I went ahead and edited the PR #377 so the ci script downloads a mono host of msbuild and uses that instead of XBuild.

So, here are some next action items:
- do a quick investigation on whether XBuild can actually build OSX. If it doesn't, just report here why (to have it documented) and proceed to other tasks. XBuild was a nice to have, but not mandatory since we can build using the mono host build.
- after you manage to build MSBuild with either XBuild or the mono build, use the newly built MSBuild to build a hello world project (a simple script with one target that prints hello world).
- - this will fail because there is no `corerun` host on OSX with our current dependency on `Microsoft.NETCore.TestHost`. Update the dependency in https://github.com/Microsoft/msbuild/blob/xplat/targets/runtime.project.json with the lowest dependency that works (bumping it higher will force you to update all the other dependencies)
- - after you have corerun available, try to build the hello world build script. You will notice that it fails with a null pointer exception. Investigate and fix the NPE. :)

**Comment by JunielKatarn** [comment]
> Thanks for upgrading the script. Did you try and build MSBuild with XBuild? Did it work?

Short answer: no.
It does run the PROJ file and starts trying to fetch NuGet assets, but it ultimately fails.
Good news is, at leas it passes arguments correctly to `xbuild`.

I'll post the command output when I'm back on my Mac.

**Comment by JunielKatarn** [comment]
Hi again. Here is the error I get with my version of the script:
```
Build Command: xbuild ./build.proj /t:Build /p:OS=OSX /p:Configuration=Debug-Netcore /verbosity:minimal /fileloggerparameters:Verbosity=diag;LogFile=./msbuild.log
XBuild Engine Version 12.0
Mono, Version 4.0.4.0
Copyright (C) 2005-2013 Various Mono authors
/Users/julio/Desktop/msbuild/osx/build.proj:  warning : Target '_RestoreBuildToolsWrapper and 'OSX'=='Windows_NT'', not found in the project
/Users/julio/Desktop/msbuild/osx/build.proj:  warning : Target '_RestoreBuildToolsWrapper1', not found in the project
	Build 'build.proj' into binary directory '/Users/julio/Desktop/msbuild/osx/bin/Debug-Netcore/'
Restoring build tools...
find: /!: unknown primary or operator
Restoring in %(ProjectJsonFile.RootDir)%(ProjectJsonFile.Directory)
/var/folders/6m/cft82bmn5v34ylhh1_s9_23c0000gn/T/tmp1f75374e.tmp: line 1: /Users/julio/Desktop/msbuild/osx/packages/dnx-coreclr-darwin-x64.1.0.0-rc2-16177/bin/dnu: Permission denied
/Users/julio/Desktop/msbuild/osx/src/.nuget/packageLoad.targets: error : Command 'export DNX_PACKAGES=/Users/julio/.nuget/packages ; /Users/julio/Desktop/msbuild/osx/packages/dnx-coreclr-darwin-x64.1.0.0-rc2-16177/bin/dnu restore  --parallel  "/Users/julio/Desktop/msbuild/osx/src/Framework/UnitTests/project.json;/Users/julio/Desktop/msbuild/osx/src/Framework/UnitTests/project.json;/Users/julio/Desktop/msbuild/osx/src/Framework/UnitTests/project.json"' exited with code: 126.
warning: LF will be replaced by CRLF in cibuild.sh.
The file will have its original line endings in your working directory.
```

Command `dnu` returns some permissions error, which is not related to administrative privileges (I tried running `sudo`).

I'll go ahead and test your updated version of the script.

**Comment by JunielKatarn** [comment]
@cdmihai Oh, on another note, the script won't even run as is in Mac OS X because it contains `CR` characters.

I need to locally disable the `eol=crlf` attribute.
This might be an issue going forward when porting MSBuild to UNIX platforms.

**Comment by JunielKatarn** [comment]
@cdmihai OK, I'm now researching the issue you mentioned

In the meantime, can you integrate this change? https://github.com/JunielKatarn/msbuild/commit/7c12ee5d65ade3d66784e38564584536b5425176
Fixes a minor issue that makes the script fail if the 'packages' directory has not been created yet.

Again, do you know why I can't create pull requests targeting your fork? It does work for all other MSBuild forks, and the main repo.

**Comment by JunielKatarn** [comment]
After running the MSBuild.exe generated by the script, I get this error:
```
$ mono bin/Debug-Netcore/Output/MSBuild.exe dummy.csproj

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections.NonGeneric, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'System.Collections.NonGeneric, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections.NonGeneric, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'System.Collections.NonGeneric, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

Note, this happens regardless of what arguments I add.
Is this the `corerun` expected error?

**Comment by cdmihai** [comment]
@JunielKatarn 

I integrated your commit into the ciscript branch

Concerning the line endings: embarrassingly, I could not force git to commit LF line endings for that file. So, as a temporary solution I forced LF for cibuild.sh in .gitattributes. This seems to solve the issue on my end. Can you please confirm this?

Concerning your last message, try building a more simple hello world:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" DefaultTargets="HelloWorld"  xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Target Name="HelloWorld">
	  <Message Text="Hello"></Message>  <Message Text="World"></Message>
	</Target>
</Project>
```

**Comment by JunielKatarn** [comment]
@cdmihai 

I tried the simplified project you suggested, but it didn't work. Here is what I did:

* Updated to your latest sources
* Ran the cibuild.sh script
* Executed `mono bin/Debug-Netcore/Output/MSBuild.exe dummy.csproj`
Output:
```
Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections.NonGeneric, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'System.Collections.NonGeneric, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections.NonGeneric, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'System.Collections.NonGeneric, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

While the build script succeeded, I did get this warning:
```
packages/mono-msbuild/bin/Unix/Debug-MONO/Microsoft.Common.CurrentVersion.targets(1090,5): warning MSB3644: The reference assemblies for framework "DNXCore,Version=v5.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [Samples/PortableTask/PortableTask.csproj]
```

**Comment by rainersigwald** [comment]
@JunielKatarn It looks like you're trying to run the .NET Core version of msbuild (based on the output path) with the `mono` runtime.  That version should be run with the `corerun` executable that's part of .NET Core.  IIRC, @cdmihai was having some trouble getting that copied to the output directory on OS X (because of .NET Core package versions), so you may have to copy it from a NuGet package manually until that can be sorted out.

**Comment by JunielKatarn** [comment]
> so you may have to copy it from a NuGet package manually 

Do you mean copying the .NET Core from a NuGet package?
I'm not too familiar wit the open-source implementation. Could you explain a little further, please? (i.e. where should I place this correct .NET Core version? How should I use this `corerun`? Do I just replace `mono` calls with `corerun` calls?...)

**Comment by rainersigwald** [comment]
Yes, the short version is that for our .NET Core binaries, you'll just replace `mono` calls with `corerun`.  Unfortunately, I can't seem to find any good documentation to link you to.  You should be able to use `corerun` from any folder, and specify the full path to `MSBuild.exe` as its first argument.  Finding an appropriate version might be tricky, though.

(I'm told that a Mac has been ordered for me, so hopefully I'll be able to be more helpful on this soon.  Sorry for being vague; I don't yet know all of the issues.)

**Comment by cdmihai** [comment]
@JunielKatarn 
You can get the corerun host from this package: https://www.myget.org/feed/dotnet-core/package/nuget/runtime.osx.10.10-x64.Microsoft.NETCore.TestHost

As far as I remember, this branch worked for me: https://github.com/cdmihai/msbuild/tree/osxBuild
However, I had to revert the version upgrades to get a clean CI build on osx and win, so that branch is not used anymore.
I'll try it later on tonight and tell you if it's the right. Then, you can use it as a base to explore the NPE.

**Comment by JunielKatarn** [comment]
Hi. I've been away for a while but allocated more time to help with testing in OS X.

@cdmihai, I tracked this build from yesterday: http://dotnet-ci.cloudapp.net/job/Microsoft_msbuild/job/innerloop_xplat_OSX/30/

OS X build seems to pass. Is this issue effectively solved?
If so, is there any documentation for building the artifacts manually?

**Comment by rainersigwald** [comment]
Thanks for the reminder about this issue, @JunielKatarn. We can now build MSBuild on OS X using Mono. We haven't yet got all the packages needed to build ourselves on OS X using our .NET Core package.

We need to update documentation, but you should be able to just run `cibuild.sh` from the root of the repo. That's what the CI server does, and should produce all the needed .NET Core binaries (or at least it does on my machine).

**Comment by JunielKatarn** [comment]
@rainersigwald
I was not able to successfully build locally.

Using either the latest commit (tag 0015) at the xplat branch (59fcc7b24631c28d566bbea9246ff470146950fd), or the latest successful commit at (4253e2f5fe7e40a3884b975fedc4d3ff65b84911), executing `./cibuild.sh --target Mono`, got the following error:
```
...
 Restoring NuGet package dnx-coreclr-darwin-x64.1.0.0-rc2-16177.
EXEC : warning : Unable to find version '1.0.0-rc2-16177' of package 'dnx-coreclr-darwin-x64'. [/Volumes/DATA/Build/msb/buildme/build.proj]
  find: /Volumes/DATA/Build/msb/buildme/packages/dnx-coreclr-darwin-x64.1.0.0-rc2-16177: No such file or directory
  Restoring in /Volumes/DATA/Build/msb/buildme/src/Framework/
  /var/folders/xn/1jl92nys3gs6gml3ck9hj36h0000gn/T/tmp2c72825b03f548c9a30ff62b1de670d4.exec.cmd: line 3: /Volumes/DATA/Build/msb/buildme/packages/dnx-coreclr-darwin-x64.1.0.0-rc2-16177/bin/dnu: No such file or directory
/Volumes/DATA/Build/msb/buildme/src/.nuget/packageLoad.targets(138,5): error MSB3073: The command "export DNX_PACKAGES=/Users/julio/.nuget/packages ; /Volumes/DATA/Build/msb/buildme/packages/dnx-coreclr-darwin-x64.1.0.0-rc2-16177/bin/dnu restore  --parallel  "/Volumes/DATA/Build/msb/buildme/src/Framework/project.json"" exited with code 127. [/Volumes/DATA/Build/msb/buildme/build.proj]
```

In short, version `1.0.0-rc2-16177` was not being fetched correctly.
After looking at https://www.nuget.org/packages/dnx-coreclr-darwin-x64, it looks like the "advertised" version is `1.0.0-rc1-update1 `. I updated to that verison in two files: `dir.props` and `src/.nuget/packages.OSX.config`. (See also latest failed build http://dotnet-ci.cloudapp.net/job/Microsoft_msbuild/job/innerloop_xplat_OSX/31/).

Then, `dnu` succeeded, but some packages could not be obtained:
```
  Warning: FindPackagesById: System.Runtime.InteropServices.RuntimeInformation
    Response status code does not indicate success: 404 (Not Found).
    GET https://www.myget.org/F/dotnet-corefx/FindPackagesById()?id='System.Runtime.InteropServices.RuntimeInformation'
  Warning: FindPackagesById: System.Reflection.Metadata
    Response status code does not indicate success: 404 (Not Found).
    GET https://www.myget.org/F/dotnet-corefx/FindPackagesById()?id='System.Reflection.Metadata'
  Warning: FindPackagesById: System.Runtime.InteropServices
    Response status code does not indicate success: 404 (Not Found).
    GET https://www.myget.org/F/dotnet-corefx/FindPackagesById()?id='System.Runtime.InteropServices'
  Warning: FindPackagesById: System.Text.Encoding.Extensions
    Response status code does not indicate success: 404 (Not Found).
    GET https://www.myget.org/F/dotnet-corefx/FindPackagesById()?id='System.Text.Encoding.Extensions'
  Warning: FindPackagesById: xunit.netcore.extensions
    Response status code does not indicate success: 404 (Not Found).
    GET https://www.myget.org/F/dotnet-corefx/FindPackagesById()?id='xunit.netcore.extensions'
  Warning: FindPackagesById: System.Reflection.Metadata
    Response status code does not indicate success: 404 (Not Found).
    GET https://www.myget.org/F/dotnet-corefx/FindPackagesById()?id='System.Reflection.Metadata'
  Warning: FindPackagesById: System.Collections.Immutable
    Response status code does not indicate success: 404 (Not Found).
    GET https://www.myget.org/F/dotnet-corefx/FindPackagesById()?id='System.Collections.Immutable'
  Warning: FindPackagesById: System.Runtime.InteropServices.RuntimeInformation
    Response status code does not indicate success: 404 (Not Found).
    GET https://www.myget.org/F/dotnet-corefx/FindPackagesById()?id='System.Runtime.InteropServices.RuntimeInformation'
  Warning: FindPackagesById: System.Runtime.InteropServices
    Response status code does not indicate success: 404 (Not Found).
    GET https://www.myget.org/F/dotnet-corefx/FindPackagesById()?id='System.Runtime.InteropServices'
  Warning: FindPackagesById: System.Text.Encoding.Extensions
    Response status code does not indicate success: 404 (Not Found).
    GET https://www.myget.org/F/dotnet-corefx/FindPackagesById()?id='System.Text.Encoding.Extensions'
  Error: FindPackagesById: System.Runtime.InteropServices.RuntimeInformation
    Response status code does not indicate success: 404 (Not Found).
  ----------
  Warning: FindPackagesById: System.Collections.Immutable
    Response status code does not indicate success: 404 (Not Found).

...
/Volumes/DATA/Build/msb/buildme/src/.nuget/packageLoad.targets(138,5): error MSB3073: The command "export DNX_PACKAGES=/Users/julio/.nuget/packages ; /Volumes/DATA/Build/msb/buildme/packages/dnx-coreclr-darwin-x64.1.0.0-rc1-update1/bin/dnu restore  --parallel  "/Volumes/DATA/Build/msb/buildme/src/Utilities/UnitTests/project.json"" exited with code 1. [/Volumes/DATA/Build/msb/buildme/build.proj]
```

Do you make any setup or customizations before the Hudson build?
Should I tweak the dependency files for those missing artifacts (404)?
If so, what file should be modified?

**Comment by rainersigwald** [comment]
@JunielKatarn I've observed NuGet restore being flaky both on OS X and on Windows. On my Mac (and my Windows machines), I can just run the build a few times in a row and it will eventually get all packages and start building. Can you try that and let me know if you observe the same?

This is really annoying, but I don't know where in the stack the flakiness resides (is it MyGet? `dnu`? Inherent to NuGet?). Identifying the problem would be a big step forward, I think.

**Comment by JunielKatarn** [comment]
OK, I tried the latest source in the branch (81be1e57f33e54bc2ee0b4b2d2f4333567c8d354). It builds successfully running `sh cibuild.sh --target Mono --scope Compile`.

**Comment by JunielKatarn** [comment]
Hi again. Tried to run a trivial SLN file, but failed. (Source version 81be1e57f33e54bc2ee0b4b2d2f4333567c8d354)
solution.sln:
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" DefaultTargets="HelloWorld" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Target Name="HelloWorld">
      <Message Text="HelloWorld"></Message>
    </Target>
</Project>
```

Command:
```
mono /workspace/bin/Debug-MONO/Output/MSBuild.exe
```

Output:
```
Microsoft (R) Build Engine version 14.1.0.0
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Invalid type Microsoft.Build.Execution.BuildManager for instance field Microsoft.Build.Execution.BuildSubmission:<BuildManager>k__BackingField
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.TypeLoadException: Failure has occurred while loading a type.
  at Microsoft.Build.CommandLine.MSBuildApp.Execute (System.String commandLine) <0x77d290 + 0x0059f> in <filename unknown>:0
This is an unhandled exception in MSBuild Engine -- PLEASE OPEN A BUG AGAINST THE MSBUILD TEAM.
System.TypeLoadException: Failure has occurred while loading a type.
  at Microsoft.Build.CommandLine.MSBuildApp.Execute (System.String commandLine) <0x77d290 + 0x0059f> in <filename unknown>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Failure has occurred while loading a type.
  at Microsoft.Build.CommandLine.MSBuildApp.Execute (System.String commandLine) <0x77d290 + 0x0059f> in <filename unknown>:0
```

**Comment by radical** [comment]
Try running  `bin/Debug-MONO/OSX_Deployment/MSBuild.exe` instead.

**Comment by cdmihai** [comment]
@JunielKatarn 

On OSX try runing through corerun, not mono:

bin/Debug-NetCore/OSX_Deployment/corerun bin/Debug-NetCore/OSX_Deployment/MSBuild.exe ../<some path>/solution.csproj

**Comment by JunielKatarn** [comment]
Thanks, @cdmihai. I ended up using the corerun build. It works as expected (aside from the issue found in #469).

Please let me know if I can collaborate with more test scenarios for OS X.

**Comment by cdmihai** [comment]
@JunielKatarn 
Thanks a lot for your interest in making .net core msbuild work on OSX!

Currently, .net core msbuild builds on osx but tests are failing. It would be really helpful to us if you could fix them :)

Here's how you might do that:
- there will be many failing tests, and most likely there are classes of tests that fail for specific reasons.
- since it is too much too fix them all at once, you first have to disable all failing tests on osx (by applying `[Trait("Category", "nonosxtests")]` on each test that fails on osx). This will get us in a state where we can have CI tests for OSX, which is really helpful.
- start by fixing a failing class of tests:
 - identify a reason of failure and open an issue describing why it fails; assign yourself to it
 - fix test failure cause
 - remove the `[Trait("Category", "nonosxtests")]` for the tests you just fixed
 - send PR

**Comment by JunielKatarn** [comment]
@cdmihai Sounds great but, how do I actually run the tests?

**Comment by rainersigwald** [comment]
@JunielKatarn They're opt-in on OS X, so you should see failures if you invoke
```sh
./cibuild.sh --scope Test
```

(I just created https://github.com/Microsoft/msbuild/wiki/Building-on-OS-X-and-Linux to document this.)

**Comment by JunielKatarn** [comment]
@mat-mcloughlin MSBuild now builds consistently on OS X. I believe this issue can be closed.

**Comment by cdmihai** [comment]
Agreed, closing the issue. Right now people can build msbuild for .net core using the cibuild.sh script.

When #501 is merged, there will be 2 options: `cibuild.sh --host CoreCLR` will build using corerun, and `cibuild.sh --host Mono` will build using mono.
