### ISSUE TITLE
MSBuild is instantiating 52 MB of Contains delegates

### ISSUE THREAD

**Issue by davkean** [Microsoft/msbuild#2266]
Same scenario as: https://github.com/Microsoft/msbuild/issues/2265.

MSBuild is ~boxing~allocating 52 MB of Contains delegates:

![image](https://user-images.githubusercontent.com/1103906/27899193-8dc70ade-626c-11e7-9e48-0a68a10b69e6.png)

\\scratch2\scratch\asja\AddReference Perf ETL logs

Looks like all the allocations are coming from this call: https://github.com/Microsoft/msbuild/blob/master/src/Build/Collections/RetrievableEntryHashSet/HashSet.cs#L232.

**Comment by rainersigwald** [comment]
Looked at the trace; this comes 100% from:

```
Type Microsoft.Build.Collections.Contains`1[System.String]
+ microsoft.build.ni!Microsoft.Build.Collections.RetrievableEntryHashSet`1[System.__Canon].get_Keys()
+ microsoft.build.ni!Microsoft.Build.Collections.PropertyDictionary`1[System.__Canon].get_PropertyNames()
+ microsoft.build.ni!Microsoft.Build.Collections.PropertyDictionary`1[System.__Canon].System.Collections.Generic.IDictionary.ContainsKey(System.String)
+ microsoft.build.ni!Microsoft.Build.Evaluation.Evaluator`4[System.__Canon,System.__Canon,System.__Canon,System.__Canon].EvaluatePropertyElement(Microsoft.Build.Construction.ProjectPropertyElement)
+ microsoft.build.ni!Microsoft.Build.Evaluation.Evaluator`4[System.__Canon,System.__Canon,System.__Canon,System.__Canon].EvaluatePropertyGroupElement(Microsoft.Build.Construction.ProjectPropertyGroupElement)
```

That looks entirely avoidable. Will send a PR after I clean it up.

**Comment by davkean** [comment]
thanks!
