### ISSUE TITLE
Removing metadata to avoid slow ITaskItem[] parameter handling

### ISSUE THREAD

**Issue by jnm2** [Microsoft/msbuild#2270]
I've tracked it down to about 100ms ~ 115ms per `ITaskItem[]` parameter, both input and output. 
The items being sent are the `ReferenceCopyLocalPaths` items, which together with metadata take 982 lines when printed by `/v:diag` in this particular project.

I was quite surprised that it takes nearly that long to serialize the items and metadata, since I'm in-proc, but that aside... the clear solution is to not be sending that amount of metadata back and forth which the custom task doesn't need in the first place. I got the target down from 450ms to 110ms by changing the semantics of the output parameter and making it a `string[]`.

The part I'm having trouble with is that at minimum I need to send a tuple of (Identity, FullPath) for each item in `ReferenceCopyLocalPaths`. I can't figure out a way to do this. Any time I create a new group of items from `ReferenceCopyLocalPaths`, all the metadata comes along. There's got to be a way to create a new group with the same identity for each item and only `FullPath` metadata, right? I couldn't find a way to clear or reset metadata in the documentation.

**Comment by jnm2** [comment]
(And why do I care about 110ms? Multiply that by 23 projects in the solution, and that's over two and a half seconds of waiting to run or debug.)

**Comment by jnm2** [comment]
I must have been wrong somewhere- I'm currently getting 220±2ms. All the more reason.

**Comment by jnm2** [comment]
Oh right, 110ms of that is my actual task running. Optimizing that is a separate effort.

**Comment by rainersigwald** [comment]
I feel like I'm missing some context here, based on the first couple of paragraphs of this issue. If this doesn't answer your question, can you be more explicit about what you're doing and what problem you're trying to solve?

To answer this:

> Any time I create a new group of items from `ReferenceCopyLocalPaths`, all the metadata comes along. There's got to be a way to create a new group with the same identity for each item and only `FullPath` metadata, right? I couldn't find a way to clear or reset metadata in the documentation.

Have you explored `KeepMetadata` or `RemoveMetadata` when creating a new item? They're documented [in the syntax documentation for Items](https://docs.microsoft.com/en-us/visualstudio/msbuild/item-element-msbuild) and in the [Item "concepts" page](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-items#BKMK_KeepMetadata). Feedback on what you were looking for to improve discoverability of those docs is welcome!

Note that `FullPath` is [well-known Item metadata](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-well-known-item-metadata), and you can't prevent the output item having it. But I think listing it in `KeepMetadata` should be harmless and accomplish the stripping of all custom metadata that you want.

**Comment by jnm2** [comment]
> Have you explored KeepMetadata or RemoveMetadata when creating a new item?

That's perfect! Only 92 lines are logged now and the overhead for this parameter is down to 12ms!

I'm embarrassed that I didn't see it in the Item syntax documentation. I was in the ItemGroup and Item Metadata pages and mainly following google searches for "msbuild item remove metadata."

Thank you!

**Comment by jnm2** [comment]
The entire target now runs in 110ms. Pretty sweet!

> I feel like I'm missing some context here, based on the first couple of paragraphs of this issue. 

My problem is solved, though I am pretty curious why it takes 100ms to send 92 items with an average of 9.6 custom metadata properties per item from a target to custom task's `ITaskItem[]` parameter.

**Comment by rainersigwald** [comment]
@jnm2 What log level (and what logger) are you using when measuring those timings? The console and file loggers do definitely slow the build down when cranked up to `Diagnostic`--that's part of the reason we introduced the binary logger.

**Comment by jnm2** [comment]
@rainersigwald Ad-hoc `msbuild /v:diag > out.log`. It didn't occur to me that might be messing with the timings! How bad is it? Is there a better way to time just one target, which is the only target I care about?

**Comment by rainersigwald** [comment]
There is! Check out the logger parameter [`PerformanceSummary`](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference#switches-for-loggers).

**Comment by jnm2** [comment]
That's really cool! Apparently the entire target is running in 100±5ms. Let me time ReferenceCopyLocalPaths on its own.

**Comment by jnm2** [comment]
@rainersigwald `ReferenceCopyLocalPaths` takes 0 ms. 😁 

Sorry for the rookie mistakes. I really appreciate you taking the time to educate me here.
