### ISSUE TITLE
Why is _GenerateCompileDependencyCache using ReferencePath?

### ISSUE THREAD

**Issue by davkean** [Microsoft/msbuild#2277]
_GenerateCompileDependencyCache is ~using~ adding ReferencePath to the compile cache but I'm not sure why, what's the reason?

The reason I ask is that it's making the assumption that ReferencePath is always relative to the project directory (via FullPath metadata) - when that's [not how it's treated by the compiler](https://github.com/dotnet/project-system/issues/1872).

**Comment by rainersigwald** [comment]
We want to add `ReferencePath` to the cache, so that if you alter it via some mechanism that doesn't involve changing the project file we still rebuild.

Team triage: 

We should drop the `FullPath` part.

**Comment by davkean** [comment]
But why only ReferencePath in that? Isn't this any input into csc?

**Comment by rainersigwald** [comment]
Yeah, this is a partial solution to the general problem that MSBuild doesn't keep track of the previous build's task inputs. It seemed that referenced assemblies and source files were most likely to be changed without changing the project.

**Comment by davkean** [comment]
Usage of full path was removed in https://github.com/Microsoft/msbuild/pull/2315.
