### ISSUE TITLE
msbuild for dotnet/corefx fails against sln files

### ISSUE THREAD

**Issue by pjanotti** [Microsoft/msbuild#2279]
I saw similar issues but not exactly the same, so opening a new one.

On the dotnet/corefx enlistment on Windows I am able to invoke msbuild against the sln file of any src/System.*, however, on macOS (10.12) it fails with error about not finding metaproj file:

```Terminal
Project "/Users/pjanotti/s/github/pjanotti/corefx/src/System.IO.FileSystem/System.IO.FileSystem.sln" (1) is building "/Users/pjanotti/s/github/pjanotti/corefx/src/System.IO.FileSystem/src/System.IO.FileSystem.csproj.metaproj" (2) on node 1 (Clean target(s)).
/Users/pjanotti/s/github/pjanotti/corefx/src/System.IO.FileSystem/src/System.IO.FileSystem.csproj.metaproj : error MSB4025: The project file could not be loaded. Could not find file '/Users/pjanotti/s/github/pjanotti/corefx/src/System.IO.FileSystem/src/System.IO.FileSystem.csproj.metaproj'.
```

However, if I change the folder delimiter from `"\"` to `"/"` in the sln file it works without issues. That is surprising because for the csproj files under the sln file msbuild works with `"\"` just fine.

Thanks

**Comment by rainersigwald** [comment]
I think this is #2022. Closing as a duplicate--please comment if you think it's distinct.

**Comment by pjanotti** [comment]
Yeah, it is the same issue. Thanks @rainersigwald
