### ISSUE TITLE
FileMatcher is allocating twice it needs to due to using Directory.GetFiles/GetDirectories

### ISSUE THREAD

**Issue by davkean** [Microsoft/msbuild#2287]
Turns out Directory.GetFiles/GetDirectories isn't very efficient, it allocates [two strings](http://referencesource.microsoft.com/#mscorlib/system/io/filesystemenumerable.cs,512) for every file even though only 1 is used by Dictionary,GetFiles.

That extra string allocation is causing 2.7% of all allocations opening a project. In this example below (ProjectSystem.sln) that's 90 MB of extra data that is never used or looked at.
![image](https://user-images.githubusercontent.com/1103906/28123362-28a9ba5a-6764-11e7-9c66-5f5a735fc648.png)

Looks like .NET Core has rewritten this path, unsure whether this will be ported to .NET Framework though. Do we push .NET to fix this? Or rewrite this to be a little less allocation heavy?

**Comment by danmosemsft** [comment]
cc @JeremyKuhne

**Comment by davkean** [comment]
Note, I have a bug against .NET under https://devdiv.visualstudio.com/DevDiv/_workitems/edit/470762 - but we have to decide if MSBuild itself makes a change here.

**Comment by davkean** [comment]
I'm closing this lieu of the above bug against .NET.
