### ISSUE TITLE
Unable to install MSBuild 15.0 on Windows 2012 (Not R2)

### ISSUE THREAD

**Issue by mynkow** [Microsoft/msbuild#2307]
Can I somehow Install MSBuild 15.0 on Windows 2012 (Not R2)? 
On Windows 2012R2 I installed VSBuildTools2017 and everything is great, but on Windows 2012 (Not R2) server I get an error:
>This Version of Windows is not supported. If you're running Windows 8.0, try upgrading to Windows 8.1.

But in documentation I see the following:

>Microsoft Visual Studio Build Tools 2017
The Build Tools support the same system requirements as Visual Studio with the following changes:

>Also installs on Windows Server 2012 and Windows Server 2008 R2 SP1

What am I doing wrong?

https://serverfault.com/questions/845267/how-to-install-msbuild-15-0-on-windows-2012-not-r2

**Comment by rainersigwald** [comment]
This repo doesn't have the installer logic, and the installer is written by a different team, so this isn't exactly the right place for it. But of course we don't expect you to know that! Thanks for letting us know.

I filed an internal bug about this with the setup team, but it's hard for you to track that externally. I think the best thing for you to do is file a new feedback issue at https://developercommunity.visualstudio.com. If you link it in this issue, I'll associate it with the bug I just filed and you should be able to get updates as they happen.

**Comment by rainersigwald** [comment]
The Setup team got back to me. Installation is not supported on Server 2012. The [system requirements page](https://www.visualstudio.com/en-us/productinfo/vs2017-system-requirements-vs) is now correct:

> ### Microsoft Visual Studio Build Tools 2017
> The Build Tools support the same system requirements as Visual Studio with the following changes:
> *	Also installs on Windows Server 2008 R2 SP1
