### ISSUE TITLE
Use the LargeAddressAware NuGet package to set the LARGEADDRESSAWARE flag

### ISSUE THREAD

**Issue by KirillOsenkov** [Microsoft/msbuild#2319]
Consider using the LargeAddressAware Nuget package:
https://github.com/KirillOsenkov/LargeAddressAware

It doesn't need Editbin.exe as it patches the byte in the PE header. I've seen problems in MSBuild build process stemming from Editbin.exe either being not found or some such.

Additionally, editbin.exe is not incremental, it will touch the file even if the bit is already set. The SetLargeAddressAware tool is incremental and won't touch the file if it doesn't need patching. This is much better for build incrementality. 

To use, just add the LargeAddressAware NuGet package version 1.0.1. Add the .targets file from the package to the build and it will inject itself after `CoreCompile`.

**Comment by KirillOsenkov** [comment]
@rainersigwald

**Comment by rainersigwald** [comment]
Sounds like a fine idea to me, though I feel a need to defend the status quo. Our implementation should only ever warn if editbin.exe isn't available (and even that is suppressed in our selfhost script), and it has reasonable incremental behavior (it might touch the file even though it's already marked correctly, but only if other parts of the build also would).

**Comment by KirillOsenkov** [comment]
Speaking of which. Is there a reason MSBuild.exe isn't AnyCPU with Prefer32Bit true? Such binaries are LargeAddressAware by default.

**Comment by gchq-zz** [comment]
We have a large 32 bit application (it has other 32 bit dependencies, like PDF reader) and does hit memory exceptions.  Will this help with this issue? If so, other than installing from NuGet what do we need to do to implement in a ClickOnce application?
Thank you

**Comment by KirillOsenkov** [comment]
Yes, it should help. Just install the NuGet package and use MSBuild logs to verify that this command is running: https://github.com/KirillOsenkov/LargeAddressAware/blob/master/LargeAddressAware.targets#L12

**Comment by gchq-zz** [comment]
Thank you for your prompt reply :-)
Have installed the NuGet package and run rebuild. Where exactly am I looking (VS 2017) to confirm this is running? Nothing seems to have been updated in App.config

**Comment by KirillOsenkov** [comment]
Run `dumpbin /headers YourApp.exe` where dumpbin is in one of these locations:
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.11.25503\bin\HostX86\x86\dumpbin.exe
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\dumpbin.exe
```

If the output contains the string `Application can handle large (>2GB) addresses` then you're good.

**Comment by gchq-zz** [comment]
Typical - there is DumpBin in VS 10, 11 and 12 - but not in 14.0. Can I use an older version?

**Comment by gchq-zz** [comment]
I ran it using DumpBin in v12 - PE Signature found | File Header Values | Optional Header Values | Section Header hash 1 | Debug Directories | Section Header hash 2 | Section Header hash 3 | Summary - no reference that I can see to 'handle large'

**Comment by gchq-zz** [comment]
Just to be sure I ran rebuild again, then DumpBin.  Still no string with anything like large addresses

**Comment by KirillOsenkov** [comment]
Oh, you probably need to add this line at the very bottom of your .csproj file:
```
  <Import Project="$(MSBuildThisFileDirectory)..\..\..\packages\LargeAddressAware.1.0.1\build\LargeAddressAware.targets" AND Exists('$(MSBuildThisFileDirectory)..\..\..\packages\LargeAddressAware.1.0.1\build\LargeAddressAware.targets')" />
```

Make sure the path to LargeAddressAware.targets is correct. You can use http://msbuildlog.com to investigate the build after you've added this line.

**Comment by gchq-zz** [comment]
This was added at the time to the vbproj file

``<Import Project="..\packages\LargeAddressAware.1.0.1\build\LargeAddressAware.targets" Condition="Exists('..\packages\LargeAddressAware.1.0.1\build\LargeAddressAware.targets')" />

Should we edit this?

I seem to remember that msbuildlog is not available for VB.NET projects

**Comment by KirillOsenkov** [comment]
It should work fine for VB.NET. Please use http://msbuildlog.com and inspect the build log to see if the LargeAddressAware target is running.

Alternatively, just switch your assembly to AnyCPU and set Prefer32Bit to true.

**Comment by gchq-zz** [comment]
The assembly won't compile in anything other than x86 (or x64) because of CefSharp browser that requires one or the other selected...

Everything is correct in the path and this works for CefSharp

`<Import Project="..\packages\cef.redist.x86.3.2987.1601\build\cef.redist.x86.targets" Condition="Exists('..\packages\cef.redist.x86.3.2987.1601\build\cef.redist.x86.targets')" />

Will look at buildlog again....
`

**Comment by gchq-zz** [comment]
`<Import Project="..\packages\cef.redist.x86.3.2987.1601\build\cef.redist.x86.targets" Condition="Exists('..\packages\cef.redist.x86.3.2987.1601\build\cef.redist.x86.targets')" />`

**Comment by gchq-zz** [comment]
Downloaded BuildLog - tried to run MSBuild with the /bl switch, but it threw the toys out because of CefSharp  - will have another look at this in the morning - there is a large brandy (drink not a stripper) calling my name right now :-)

**Comment by gchq-zz** [comment]
Apart from discovering that my desk is a lot harder than my head, no luck with MSBuild  - used every switch I can think of (e.g. /p:PlatformTarget=x86) and it still insists upon 'Debug|Any CPU' and then throwing out the toys at CefSharp. Can you tell I haven't used the VS CLI before? :-)  We'll just see if the 'out of memory'  error rate for processing images drops when it's deployed out in the wild. Thank you for your patience.

**Comment by gchq-zz** [comment]
Can't do that as it has a browser control that won't run if it's set to 
Any CPU

**Comment by KirillOsenkov** [comment]
I mean AnyCPU *32-bit preferred*
http://blogs.microsoft.co.il/sasha/2012/04/04/what-anycpu-really-means-as-of-net-45-and-visual-studio-11/

**Comment by jeffkl** [comment]
I did this in https://github.com/Microsoft/msbuild/pull/2944
