### ISSUE TITLE
Git - Add $(GitCommitIDShort) and $(GitCommitIDFull)

### ISSUE THREAD

**Issue by Korporal** [microsoft/msbuild#2327]
Is it possible to add functionality so that we can use the above macros in our build paths? The idea being that when we **publish** we can have an output folder that is named with the commit ID (say first 16 chars).

This of course assumes that app sits within a folder within a Git repo.

Is this possible? does anything like it exist already?

I'm primarily dealing with a site in which we **publish** most stuff within Visual Studio (manually) at this point, we do not (yet) have a more sophisticated build system. We'd be able to let developers **publish** (say to a shared network path) when we want to deliver a new version of an app to say our QA team. This publish operation would then put the output into a folder specific to the commit from which it was built.

$(GitCommitIDShort) could be say 8 hex chars, $(GitCommitIDLong) could be 16 hex chars and $(GitCommitIDFull) could be the full 40 char commit ID hex string.

PS, I did just see $(GitVersioningDir) in this file, line 5:

https://github.com/Microsoft/msbuild/blob/33eb3a05573f99af5b8d4433658194e33b666720/setup/Microsoft.Build.swixproj

What is that?

**Comment by rainersigwald** [comment]
So far, we've left this to extension mechanisms, and I think that's the right long-term approach. The core MSBuild engine isn't tied to any particular version-control system--it only knows about files on disk.

That said, there are many ways to get the information you want:
* Get it from the build/CI system (you allude to not having one, which is probably worth changing!)
* Write a target that directly `Exec`s `git` and captures its output (this is common though can be a bit of a pain)
* Write a task that uses Git (maybe through [LibGit2Sharp](https://github.com/libgit2/libgit2sharp))
* Use an existing NuGet package that provides this information (I'm aware of [GitInfo](https://github.com/kzu/GitInfo), [GitVersion](https://github.com/GitTools/GitVersion) and [Nerdbank.GitVersioning](https://github.com/AArnott/Nerdbank.GitVersioning/); there are [many others](https://preview.nuget.org/packages?q=git+version)). Note that some of these packages have Strong Opinions about how your _product's assembly versions_ should be defined.

Given your stated desires, I'd probably start with GitInfo, though that's not an endorsement or anything.

In this repo we're currently [using](https://github.com/Microsoft/msbuild/blob/5cb34686634f2211b355e4a82170c200fcf6b539/src/.nuget/project.json#L4) Nerdbank.GitVersioning with a [customized configuration](https://github.com/Microsoft/msbuild/blob/master/version.json).

**Comment by rainersigwald** [comment]
In addition to the above there's https://github.com/dotnet/sourcelink. We do not plan to build this into MSBuild itself.
