### ISSUE TITLE
Pre-release binaries

### ISSUE THREAD

**Issue by alrz** [Microsoft/msbuild#2335]
Is it possible to get pre-release binaries without VS preview? there's a standalone installer for build tools but I think that's not the latest bits.

**Comment by rainersigwald** [comment]
There's a preview-channel Build Tools installer too, it's just not listed anywhere! By analogy with the posted download links at https://www.visualstudio.com/vs/preview/, I found https://www.visualstudio.com/thank-you-downloading-visual-studio/?ch=pre&sku=BuildTools&rel=15.

May I ask why you're interested? It might influence our future release plans.

**Comment by alrz** [comment]
Thanks for the link!

I'm trying to build Roslyn which needs the latest compilers using Rider but that was a failed attempt. Think I should fallback to preview or vsix for now.
