### ISSUE TITLE
MSBuild is still opt'ing into the legacy GetFullPath behavior

### ISSUE THREAD

**Issue by davkean** [Microsoft/msbuild#2338]
.NET Framework recently made a change in 4.6.2 that improved the overhead of Path.GetFullPath by reducing the amount of processing within .NET itself, and letting it be handled by the operating system.

While MSBuild has their own version of GetFullPath (which should also be considered to be moved to the new GetFullPath), they are indirectly using the legacy behavior via Directory.GetFiles/GetDirectories, MSBuild should opt into the new behavior when running on 4.6.2 and above:

``` XML
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <runtime>
    <AppContextSwitchOverrides value="Switch.System.IO.UseLegacyPathHandling=false" />
  </runtime>
</configuration>
```

**Comment by davkean** [comment]
Did some quick analysis over 100,000 items:

Method |     Mean |    Error |   StdDev |     Gen 0 | Allocated |
---------------------- |-----------:|---------:|---------:|----------:|----------:|
 GetFullPath_New     | 263.9 ms | 1.344 ms | 1.191 ms | 8187.5000 |  32.81 MB |
 GetFullPath_Legacy | 318.0 ms | 0.7823 ms | 0.6935 ms | 9500.0000 |  38.15 MB |

**Comment by davkean** [comment]
In this trace for this: https://github.com/dotnet/sdk/pull/1432#issuecomment-316852561, normalizing the path for GetFiles/GetDirectories was ~2.0% of the overall CPU time:

![image](https://user-images.githubusercontent.com/1103906/28446062-aaa65844-6e0b-11e7-889d-f00dea8e1885.png)

**Comment by rainersigwald** [comment]
Oh, that's a distinct switch from `Switch.System.IO.BlockLongPaths` which is more complicated for us to adopt.

This should be pretty doable for us--I doubt anyone was passing things through MSBuild that were confusingly handled extended file attributes or anything.

**Comment by davkean** [comment]
Note, there's more here due this:

![image](https://user-images.githubusercontent.com/1103906/28702550-1c8f0ca4-73a1-11e7-81ea-ba43fa5eb023.png)

**Comment by davkean** [comment]
Here's another trace, we can remove the indicated frames by opt'ing into the new behavior:

![image](https://user-images.githubusercontent.com/1103906/28807965-0b398a6a-76bc-11e7-804e-fe89223a785e.png)

**Comment by davkean** [comment]
Even for a project with zero globs, we're hitting this just loading all the props/targets in the graph:

![image](https://user-images.githubusercontent.com/1103906/29304358-de7dc886-81d5-11e7-9a95-f03c81f76929.png)

**Comment by rainersigwald** [comment]
To get benefits for design-time, we'd need this in `devenv.exe.config` too, which would also affect extensions. I'm not sure what the right way to do that and validate that it's ok is--do you know?
