### ISSUE TITLE
Detecting and failing on old MSBuild versions

### ISSUE THREAD

**Issue by jaredpar** [Microsoft/msbuild#2350]
The [dotnet/roslyn](http://github.com/dotnet/roslyn) repo requires the MSBuild from at least VS2017 update 2 to compile. This the earliest version that has a number of SDK bug fixes that we depend on. When built with earlier versions of MSBuild we end up with some fairly cryptic error messages like

```
RuntimeIdentifier must be set for .NETFramework executables
```

This means customers with RTM builds of our product come up to our repos, build and get crpytic error messages. Feel like that makes our build process look broken / flaky. Trying to come up with a better experience here. 

The ideal is that when you run msbuild on our solution you end up with one or more messages that say:

```
This project requires at least MSBuild from VS2017 Update 2. 
```

That would be actionable by customers and save a lot of headache on our part. Think this would be really easy to do in a BeforeBuild Target / Task. But I can't figure out the best way to map an installation of MSBuild to say VS2017 update 2. Looking on my machine I can see the file version is 15.1.1012.6693. So I could just say if the version is greater than or equal to that then you're at least update 2. Feels a bit hacky though. Is there a better way of doing a version comparison on MSBuild binaries?

**Comment by jaredpar** [comment]
CC @tannergooding

**Comment by rainersigwald** [comment]
We have `$(MSBuildAssemblyVersion)` . . . but it does what it says, and isn't the file version that actually changes. We should introduce (and [document](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-reserved-and-well-known-properties)) a `$(MSBuildVersion)`.

But that's just a nicer way to expose the information you're already looking at. We do tag [our releases here](https://github.com/Microsoft/msbuild/releases) with the VS version they correspond to, so you can manually correlate in that way.

You could possibly correlate with `$(VisualStudioVersion)`, after https://github.com/Microsoft/msbuild/pull/2258 is fixed (in 15.5). Internally that's a headache across branches of course.

⚠️ As we've discussed offline, there can be reasons beyond the MSBuild engine + common.targets version that you can depend on. Having a heuristic for MSBuild version will probably catch most things especially for non-Microsoft users, but to be fully accurate you'd need `{MSBuild engine} + {dotnet sdk} + {any additional installed SDKs like VSSDK} + {compiler} + ...` versions.

**Comment by jaredpar** [comment]
> We should introduce (and document) a $(MSBuildVersion)

That would definitely help the scenarios that I'm interested in. 

> We do tag our releases here with the VS version they correspond to, so you can manually correlate in that way.

Perfect. Thanks!

> You could possibly correlate with $(VisualStudioVersion), 

That's a MSBuild variable that I generally avoid, possibly incorrectly. In my experience it's only set when building through Visual Studio while a lot of our builds are driven strictly through command line. Or maybe I've just gotten unlucky here and it's intended to be set more often. 

> Having a heuristic for MSBuild version will probably catch most things especially for non-Microsoft users, but to be fully accurate you'd need {MSBuild engine} + {dotnet sdk} + {any additional installed SDKs like VSSDK} + {compiler} + ... versions.

Yep. 100% agree. 

Been asking other teams similar questions to this one today 😄

**Comment by rainersigwald** [comment]
> > You could possibly correlate with $(VisualStudioVersion),
>
>That's a MSBuild variable that I generally avoid, possibly incorrectly. In my experience it's only set when building through Visual Studio while a lot of our builds are driven strictly through command line. Or maybe I've just gotten unlucky here and it's intended to be set more often.

I also tend to avoid it so it's hard for me to say this is a bad or wrong policy. The linked #2258 will ensure that it gets set all the time (in future MSBuild versions), but it's not very granular--it'll be 15.0 for the lifetime of the VS2017, so it won't help achieve your stated goal.

**Comment by jaredpar** [comment]
Took a stab at implementing this for Roslyn and I think this represents roughly the work required:

https://github.com/dotnet/roslyn/pull/21218/commits/cfb19ce4616c5b573ab82ded92b3a8add3f0b81a

Recent conversations with the SDK team make me feel even stronger that this is a feature we should have in MSBuild. There are now at least three different functionality levels of MSBuild within 15.0:

- 15.0: brings SDK 1.0 
- 15.1: brings SDK 1.1. 
- 15.3: min-req for SDK 2.0

This means using 15.0 to compile SDK 1.1 or 2.0 ends in a lot of cryptic error messages. Hence any repo that moves to SDK 2.0 is basically asking to confuse users until they upgrade to a new MSBuild version. Feel like we're really doing a disservice to our users there.

**Comment by dasMulli** [comment]
@jaredpar is your requirement to check for the actual msbuild version or the loaded version of an SDK (e.g. `Microsoft.NET.Sdk`)? The latter could be completely independent of the host msbuild version depending on what the resolvers resolve to.
From what I've read, I think the plan is still to ship VS 15.3 with MSBuild 15.3 and SDK 1.1 but include an SDK resolver that detects installed versions of the 2.0 SDK - so unless someone installs the 2.0 SDK, checking for MSBuild 15.3 is pretty useless if you depend on 2.0 SDK features. The mono version of MSBuild uses the same resolver.

While the SDK [introduced a `UsingMicrosoftNETSdk` property](https://github.com/dotnet/sdk/pull/1242/files), it may make more sense to add a version property as well to allow for checks. (this may be especially useful for nuget packages containing props/targets)

**Comment by jaredpar** [comment]
@dasMulli 

> is your requirement to check for the actual msbuild version or the loaded version of an SDK (e.g. Microsoft.NET.Sdk)?

Eventually both. This particular thread though I'm focused on the MSBuild version checking. The SDK team, as you pointed out, already provides a way to somewhat check the version already. 

> so unless someone installs the 2.0 SDK, checking for MSBuild 15.3 is pretty useless if you depend on 2.0 SDK features.

It's actually very useful. If you depend on the 2.0 SDK then you also implicitly depend on MSBuild 15.3. Hence it makes a lot of sense in your `"BeforeBuild"` targets to ensure you're on a minimum of MSBuild 15.3. Otherwise why bother with anything else in the compilation? It will just fail with a cryptic error that no one will understand.
