### ISSUE TITLE
ANSI color codes should be on by default for Linux

### ISSUE THREAD

**Issue by Veigres** [Microsoft/msbuild#2364]
Why isn't ANSI color codes on by default for Linux platforms? This is the reason why issues like #754 happen. A workaround is to just use /clp:ForceConsoleColor, but that makes using the command line more messy than it has to be.

**Comment by rainersigwald** [comment]
Can you clarify this?

> This is the reason why issues like #754 happen.

I don't understand Linux console output very well, but my understanding is that the `System.Console` APIs we call in the absence of `ForceConsoleColor` are just emitting the same ANSI control codes. The `Force` parameter just short-circuits CoreFX's attempt to not emit them to a redirected stream.

**Comment by Veigres** [comment]
Just as a demo, I am running MSBuild on a simple test project:
```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" DefaultTargets="Build">
	<Target Name="Build">
		<MakeDir Directories="tmp" />
		<Message Text="Hello MSBuild!" Importance="high" />
	</Target>
</Project>
```

Here is the result when runnning the command `dotnet msbuild test.proj /v:n`
![scr1](https://user-images.githubusercontent.com/3228043/28797448-a250b03e-7641-11e7-92ce-1dc2c5897959.png)

and here is the same project, but using `dotnet msbuild test.proj /v:n /clp:ForceConsoleColor`
![scr2](https://user-images.githubusercontent.com/3228043/28797493-cb9273d8-7641-11e7-806d-6306c9913389.png)

So there is clearly going something on when using ForceConsoleColor. I have used MSBuild quite a lot on the command line on Windows and the second case is more in line with what I would expect on default there, where implicit(?) messages are in a greyish tone, as opposed to black which seems to be the default on Linux.

I have not actually dug into the source code, but a simple search turned up [these lines](https://github.com/Microsoft/msbuild/blob/master/src/Build/Logging/ConsoleLogger.cs#L131-L151) from src/Build/Logging/ConsoleLogger.cs. It might have something to do with it.

As for the issue referenced, #754, they are experiencing exactly the same issue as I am, default text is black and hard to see on dark backgrounds.

**Comment by radical** [comment]
Maybe this will help - https://github.com/mono/msbuild/commit/84a7897588186e1426ac7416b4ea8f797036d810 ?

**Comment by rainersigwald** [comment]
Extra confusingly, this seems to be inverted on macOS:

<img width="809" alt="screen shot 2017-08-07 at 11 57 19 pm" src="https://user-images.githubusercontent.com/3347530/29056936-4d50025c-7bcc-11e7-96c7-9b2ee074c0eb.png">

`ForceConsoleColor` turns black-on-black, but without I see the expected `DarkGray` text.

**Comment by Veigres** [comment]
When I run the project in the integrated terminal in VS Code, I get the expected behavior without using `/clp`.

![image](https://user-images.githubusercontent.com/3228043/31971850-fae957c2-b91d-11e7-8b80-1a7d3e9a88c3.png)

I think this is very strange. Maybe there is something wrong with how the system terminal renders ANSI color codes? I know that VS Code uses a custom rendering for the terminal, so maybe that is why we are seeing inconsistent behavior? I am using VS Code 1.17.2 (I think the terminal rendering was changed in 1.16 or 1.17).

**Comment by Veigres** [comment]
Sorry for closing and reopening, I clicked the wrong button.

**Comment by rainersigwald** [comment]
This hasn't gotten attention in many years, and the new default is `-tl` which unconditionally uses ANSI escape colors, so I'm going to close it.
