### ISSUE TITLE
DispatchToInnerBuilds does not support matrix builds on Platforms

### ISSUE THREAD

**Issue by sharwell** [Microsoft/msbuild#2370]
Currently `DispatchToInnerBuilds` only supports building multiple outputs based on `$(TargetFrameworks)`, some projects, e.g. [Microsoft/perfview](https://github.com/Microsoft/perfview) would benefit from the ability to have the build matrix leverage other aspects (in this case `$(Platforms)`, as requested in the comments in Microsoft/perfview#319). I was able to implement this manually by overriding `DispatchToInnerBuilds` (see https://github.com/Microsoft/perfview/pull/319/commits/c7e54d556763ff6065e034a0d0f9c7bc98658350):

```xml
  <Target Name="DispatchToInnerBuilds" Returns="@(InnerOutput)">
    <ItemGroup>
      <_TargetPlatform Include="$(Platforms)" />
      <_TargetFramework Include="$(TargetFrameworks)" Platform="%(_TargetPlatform.Identity)" />
    </ItemGroup>

    <MSBuild Projects="$(MSBuildProjectFile)"
             Condition="'$(TargetFrameworks)' != ''"
             Targets="$(InnerTargets)"
             Properties="TargetFramework=%(_TargetFramework.Identity);Platform=%(Platform)">
      <Output ItemName="InnerOutput" TaskParameter="TargetOutputs" />
    </MSBuild>
  </Target>
```

**Comment by davkean** [comment]
This is somewhat by design to mimic existing behavior. We've never previously matrixed on platform so doing so might be a little confusing. I'm okay for an opt-in but for real support, VS side also needs to be made aware of this as it doesn't call DispatchToInnerBuilds.

**Comment by AndyGerlicher** [comment]
Team Triage:
Without Visual Studio support this isn't something we're considering at this point. @livarcocc for awareness.
