### ISSUE TITLE
0.5% of a design-time build is just checking that an element has a valid namespace

### ISSUE THREAD

**Issue by davkean** [Microsoft/msbuild#2373]
Looking at design-time builds of Roslyn (http://github.com/dotnet/roslyn), it looks like 0.5% of a build is just spent validating a namespace of an element:

![image](https://user-images.githubusercontent.com/1103906/28809066-2994fa00-76c4-11e7-95bb-1b39511dd627.png)

Looking at the code it's doing a string compare - is there a way we can switch this is reference equality via a name table?

**Comment by rainersigwald** [comment]
I'd be interested to know whether just swapping the nullorempty check into first place in the short-circuting `or` would cut that down significantly.

It also looks like that comparison should be case-sensitive [according to the XML spec](https://www.w3.org/TR/xml-names11/#NSNameComparison).

**Comment by AndyGerlicher** [comment]
Team Triage:
It seems to us that the right solution here is just to remove the check entirely. There's probably no reason to actually check this.
