### ISSUE TITLE
Microsoft.Build.Evaluation.Project.Save() clears empty lines from a csproj 

### ISSUE THREAD

**Issue by mishra14** [Microsoft/msbuild#2376]
Original issue: https://github.com/dotnet/cli/issues/7280

==================================================================

## Steps to reproduce
dotnet new a console app
dotnet add package <any package>

## Expected  behavior
whitespace between itemgroups etc is preserved

## Actual behavior
All blank lines are removed

## Environment data
`dotnet --info` output:

```
Product Information:
 Version:            2.0.0-preview3-006770
 Commit SHA-1 hash:  78e7163819

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview3-006770\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview3-25514-02
  Build    : 1b047a04057cec973cfb890fd21f7a639cfcd118


```

**Comment by mishra14** [comment]
I think this is an msbuild issue as [NuGet invokes msbuild API's](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.CommandLine.XPlat/Utility/MSBuildAPIUtility.cs) to read a csproj, add items/itemgroups and then save the csproj file.

**Comment by rainersigwald** [comment]
@mishra14 #1036 added a new argument to `ProjectRootElement.Open` to preserve the existing formatting of the file. Can you opt NuGet into it? That's what CPS did for VS-based edits.

**Comment by mishra14** [comment]
I see. I guess NuGet can take this. I will move this issue out.

**Comment by mishra14** [comment]
This issue was moved to NuGet/Home#5697

**Comment by mishra14** [comment]
This issue was moved to NuGet/Home#5698
