### ISSUE TITLE
2.5% of evaluation time is spent converting file spec into a regex string

### ISSUE THREAD

**Issue by davkean** [Microsoft/msbuild#2380]
Investigating long evaluation times in Roslyn and customer traces, and 2.5% of evaluation time (about 1% of build time) is spent just converting a file spec into a regex string:

![image](https://user-images.githubusercontent.com/1103906/28857741-e43c96ae-778e-11e7-944a-f4c915447d11.png)

Looks to be most time spent in Replace - is there a way we can be smarter about this and avoid all the replaces?

**Comment by davkean** [comment]
Looks like I'm only seeing this show up for the second project (with lots of removes/includes) over here: https://github.com/Microsoft/msbuild/issues/2392.

**Comment by AndyGerlicher** [comment]
Team Triage:
Closing this. We should rewrite the glob matching to be more efficient as described in #2392.

**Comment by davkean** [comment]
@cdmihai Does #2392 address RegularExpressionFromFileSpec?

**Comment by davkean** [comment]
According to @cdmihai #2393 doesn't address this so reopening.
