### ISSUE TITLE
Project dependency is "not compatible" even when not a reference

### ISSUE THREAD

**Issue by mhutch** [Microsoft/msbuild#2399]
The attached example contains two projects, ConsoleApp1, which references net40, and netstandardlib, which references netstandard1.6. They are both in one solution, and ConsoleApp1 is set to depend on netstandardlib but *not* reference it.

If I build it in VS, the build succeeds.

If I build on commandline, it fails with the following error:

```
"C:\Users\Mikayla\Projects\netstandardlib\netstandardlib.sln" (default target) (1) ->
"C:\Users\Mikayla\Projects\netstandardlib\ConsoleApp1\ConsoleApp1.csproj.metaproj" (default target) (3) ->
"C:\Users\Mikayla\Projects\netstandardlib\ConsoleApp1\ConsoleApp1.csproj" (default target) (4) ->
"C:\Users\Mikayla\Projects\netstandardlib\netstandardlib\netstandardlib.csproj" (GetTargetFrameworkProperties target) (2:3) ->
(GetTargetFrameworkProperties target) ->
  C:\Program Files\dotnet\sdk\1.1.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.Common.targets(73,5): error : Project 'C:\Users\Mikayla\Projects\netstandardlib\netstandardlib\netstandardlib.csproj' targe ts '.NETStandard,Version=v1.6'. It cannot be referenced by a project that targets '.NETFramework,Version=v4.0'. [C:\Users\Mikayla\Projects\netstandardlib\netstandardlib\netstandardlib.csproj]
```

VS2017 15.3 Preview 2. Can also repro if I install .NET Core SDK 2.0 preview 2.

[netstandardlib.zip](https://github.com/Microsoft/msbuild/files/1202659/netstandardlib.zip)

**Comment by mhutch** [comment]
I was able to work around this with the following target

```xml
<!-- workaround for https://github.com/Microsoft/msbuild/issues/2399 -->
<Target Name="WorkaroundMSBuildIssue2399" BeforeTargets="GetTargetFrameworkProperties">
  <PropertyGroup>
    <ReferringTargetFramework>$(TargetFramework)</ReferringTargetFramework>
  </PropertyGroup>
</Target>
```

**Comment by rainersigwald** [comment]
We've been tracking this in the Sdk repo, so I'm going to close this as a duplicate of https://github.com/dotnet/sdk/issues/939.

Your workaround is really nice, so I copied it over there.
