### ISSUE TITLE
Add setup documentation when Mono is built from source

### ISSUE THREAD

**Issue by ratstache** [Microsoft/msbuild#2409]
## Problem

When building mono from source msbuild isn't included by default. When trying to add msbuild after mono is already built the bootstrapping fails. Perhaps it is the lack of documentation about [building, testing, and debugging](https://github.com/Microsoft/msbuild/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild) on other platforms, but everything I've come across in discussion forums about this seem to indicate it is broken. @borgdylan seems to be the only person to have successfully done it and it wasn't without issue.

Any guidance, advice, or fixes are very welcome! Thanks in advance!

**Comment by radical** [comment]
Currently, for use with mono, you should be using the [xplat-master](https://github.com/mono/msbuild/tree/xplat-master) or [d15.3](https://github.com/mono/msbuild/tree/d15.3branch). And build it with `$ make`. And install to your prefix with `$ ./install-mono-prefix.sh <your_mono_prefix>`.

**Comment by ratstache** [comment]
This is working! FINALLY! Where is this documented and how come I wasn't able to find it?! Also, thank you so much!

**Comment by radical** [comment]
It's not. I'll fix that.

**Comment by ratstache** [comment]
I am now getting 

```ERROR: Could not restore build tools correctly. ```

Which then leads to:
```
error: Failed to retrieve information from remote source 'https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-buildtools/nuget/v3/flatcontainer/microsoft.dotnet.buildtools/index.json'.
error: The type initializer for 'System.Net.Http.CurlHandler' threw an exception.
error:   The type initializer for 'Http' threw an exception.
error:   The type initializer for 'HttpInitializer' threw an exception.
error:   Unable to load DLL 'System.Net.Http.Native': The specified module could not be found.
error:    (Exception from HRESULT: 0x8007007E)
error: Failed to retrieve information from remote source 'https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-buildtools/nuget/v3/flatcontainer/microsoft.dotnet.buildtools/index.json'.
error:   The type initializer for 'System.Net.Http.CurlHandler' threw an exception.
error:   The type initializer for 'Http' threw an exception.
error:   The type initializer for 'HttpInitializer' threw an exception.
error:   Unable to load DLL 'System.Net.Http.Native': The specified module could not be found.
error:    (Exception from HRESULT: 0x8007007E)
============= end of /home/landon.butterworth/miniconda3/conda-bld/msbuild_1502228788047/work/init-tools.log ===========
Initializing BuildTools...
/home/landon.butterworth/miniconda3/conda-bld/msbuild_1502228788047/work/init-tools.sh: line 127: /home/landon.butterworth/miniconda3/conda-bld/msbuild_1502228788047/work/packages/Microsoft.DotNet.BuildTools/1.0.27-prerelease-00927-05/lib/init-tools.sh: No such file or directory
ERROR: An error occured when trying to initialize the tools. Please check '/home/landon.butterworth/miniconda3/conda-bld/msbuild_1502228788047/work/init-tools.log' for more details.1
Makefile:2: recipe for target 'all-mono' failed
make: *** [all-mono] Error 1
```

**Comment by radical** [comment]
https://github.com/Microsoft/msbuild/wiki/Building-Testing-and-Debugging-on-Mono-MSBuild

Which distribution are you on?

**Comment by ratstache** [comment]
Ubuntu 16.04

**Comment by radical** [comment]
I had to install `libcurl3-dev` also (besides openssl) to get it to build.

**Comment by ratstache** [comment]
I already have libcurl4-openssl-dev installed

**Comment by radical** [comment]
@rainersigwald ^ :)

**Comment by ratstache** [comment]
This might be the issue 
```
packages/Microsoft.DotNet.BuildTools/1.0.27-prerelease-00927-05/lib/tool-runtime/project.lock.json(1,0): warning NU1006: Dependencies in project.json were modified. Please run "dotnet restore" to generate a new lock file.
Done initializing tools.
```

when trying to restore build tools version. I'll try throwing a dotnet restore in at that step...

**Comment by ratstache** [comment]
I'm closing this because the documentation has been updated I'll open a new issue for the problem I'm having
