### ISSUE TITLE
Equals signs in solution path causes CS1679 when calling CSC

### ISSUE THREAD

**Issue by ajryan** [Microsoft/msbuild#242]
It is valid for a Windows path to contain an equals ("=") sign.

**Preconditions**:

* The solution is located in a path containing an equals sign and no spaces.
* A project in the solution references another project or a Nuget package under the solution folder.

**Actual Result**

* References are passed to `csc.exe` unquoted in the form `/reference:C:\Development\=solution=\packages\test.dll`.
* The C# compiler returns `CS1679: Invalid extern alias for '/reference'; 'C:\Development\' is not a valid identifier`

**Expected Result**

* The solution builds without error.

**Comments**

When the solution path contains spaces, MSBuild encloses the paths passed to CSC `/reference` in double quotes. The issue would be resolved if all reference paths were quoted, or if reference paths containing an equals sign were quoted. Currently, CSC interprets unquoted reference paths containing an equals as aliases. I suppose the issue could be fixed in CSC (first check if the entire reference switch represents a valid path, only fall back on alias behavior if it does not), but it seems more appropriate for the MSBuild Csc task to understand how to craft valid arguments to CSC.

**Comment by AndyGerlicher** [comment]
This looks like an issue with [Roslyn](https://github.com/dotnet/roslyn/). Can you open this issue there? I think MSBuild is doing the right thing here and quotes shouldn't be needed around the `/reference`. @jaredpar let me know if you disagree here.

**Comment by rainersigwald** [comment]
Even if quotes are needed around the reference, the right place for that is in the Csc task, which isn't in the core MSBuild repo.

**Comment by ajryan** [comment]
Thanks for taking a look at this, guys.

@AndyGerlicher  - how is `CSC.EXE` supposed to know the difference between an alias and a path with an equals? What if I want to alias a reference that has an equals in its path? It is even possible to construct a path with multiple equals signs and commandline where it is ambiguous whether alias or direct reference is intended, without quotes. The caller who is constructing the commandline (i.e. the MSBuild Csc Task) has all of the information required to construct a valid commandline. 

@rainersigwald - what's the right way to file an issue against the Csc task? Connect?

**Comment by AndyGerlicher** [comment]
The Csc task is in Roslyn [here](https://github.com/dotnet/roslyn/tree/master/src/Compilers/Core/MSBuildTask).

**Comment by ajryan** [comment]
Thanks! Closing this and opened another over there.
