### ISSUE TITLE
File loggers should log their verbosity

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/msbuild#2426]
I look through a lot of MSBuild logs, and when they come from other people I don't always know what verbosity they're logged at--so it's not always clear whether a log message I'm looking for is missing because that build event didn't happen, or because the verbosity isn't where I expect it.

I'd like to see a line at the top of the log that mentions what verbosity is configured.

**Comment by AndyGerlicher** [comment]
Sounds great!

**Comment by CodeTherapist** [comment]
It's time to implement this - can I do it?

**Comment by rainersigwald** [comment]
@CodeTherapist absolutely! Please let us know if you run into any trouble.

**Comment by CodeTherapist** [comment]
@rainersigwald Thank you - very appreciated. 
I have implemented this change - but got a small question that I can't guess from your specification:

Do we expect this verbosity info also when the logger option `warningsonly` or/and `errorsonly` is set?

The test [EmptyErrorLogUsingWarningsErrorsOnly](https://github.com/microsoft/msbuild/blob/b2db71bebaae4f54f7236ca303e2b0a14aca1a0d/src/Build.UnitTests/FileLogger_Tests.cs#L344) fails as expected - it is expecting an empty log file.

**Comment by rainersigwald** [comment]
Ah, I didn't think of that! I definitely think we should emit this message as "a normal message", so it shouldn't be emitted in errors-only and warnings-only cases, or if the verbosity is set to minimal. That way it provides information in situations where there was already a lot of output, but doesn't trip people's "detect errors by seeing if the `.err` file is non-empty" scripting.

**Comment by CodeTherapist** [comment]
@rainersigwald I'm not certain that I implemented it as it should be 😟, because MSBuild is not that simple.

**Comment by rainersigwald** [comment]
@CodeTherapist That's certainly true! We'll take a look at your PR and let you know what we think.
