### ISSUE TITLE
TaskItemSpecFilenameComparer.Compare allocations 0.7% of a solution-wide design-time build

### ISSUE THREAD

**Issue by davkean** [Microsoft/msbuild#2433]
![image](https://user-images.githubusercontent.com/1103906/29347037-e4849ebe-828c-11e7-8262-f94636aa1a64.png)

**Comment by davkean** [comment]
From this trace: https://github.com/dotnet/project-system/issues/2712

**Comment by rainersigwald** [comment]
https://github.com/Microsoft/msbuild/blob/2d8a4341875e532bdf25a14f208f62a7bb547774/src/Tasks/AssemblyDependency/TaskItemSpecFilenameComparer.cs#L48-L66

Could probably replace those `Path.GetFileName` with a last-slash and a partial string compare.
