### ISSUE TITLE
Should GenerateBindingRedirects be running in a design-time build?

### ISSUE THREAD

**Issue by davkean** [Microsoft/msbuild#2441]
When running CompileDesignTime, GenerateBindingRedirects is running. Why?

https://github.com/dotnet/sdk/issues/1496

**Comment by rainersigwald** [comment]
Because `ResolveReferences` depends on it, and `CoreCompile` depends on that. I don't see a reason to avoid conditioning it on `DesignTimeBuild`.

What I really want to know is why this isn't trivial to tell from the design-time build log. MSBuild should be (and apparently is) emitting logs of the format

```
Target "{0}" in file "{1}" from project "{2}" (target "{3}" depends on it):
```

But what I see in logs is

```
29>Target "GenerateBindingRedirects" in file "C:\Program Files (x86)\Microsoft Visual Studio\Preview\EntInt\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets":
```

I can't see MSBuild ever forming that message in the debugger.

**Comment by davkean** [comment]
I suppose my question is not why is it scheduled, but rather what data is it producing that is interesting for a design-time build - by default projects turn off the warnings, etc around version conflicts that come from Csc- so what is Csc doing with this config that is interesting from a IntelliSense perspective?

**Comment by davkean** [comment]
@jaredpar Says that Csc doesn't read the binding redirects. Hmm, I was thinking it was scheduled before ResolveReferences because it was CoreCompile that had a dependency on it, but it sounds like something else is depending on that.

**Comment by rainersigwald** [comment]
Just ran across this: RAR accepts an app config as an input:

https://github.com/Microsoft/msbuild/blob/b179f6fd5295b9a56a94c6feb29e06259a3b779c/src/Tasks/Microsoft.Common.CurrentVersion.targets#L1964-L1967

https://github.com/Microsoft/msbuild/blob/b179f6fd5295b9a56a94c6feb29e06259a3b779c/src/Tasks/Microsoft.Common.CurrentVersion.targets#L1999

Not sure what it does with it.

**Comment by jaredpar** [comment]
@jasonmalinoski pointed out to me that the compiler does accept app.config as input. There is a section in app.config which tells the compiler whether or not it should compare assembly identities while taking into Silverlight quirks.

But that's the app.config which is provided in the project file (to my understanding). Not the one which gets generated at the end which includes binding redirects.

**Comment by davkean** [comment]
@rainersigwald RAR is probably using it as indicator on whether it should issue conflicts or not. What it should really do is "always issue conflicts" -> something later decides if we warn about said conflicts based on project type, app.config, etc. Don't think bug is really actionable at this time.
