### ISSUE TITLE
GetInstalledSDKLocations runs in every project regardless of whether they even target a Windows SDK

### ISSUE THREAD

**Issue by davkean** [Microsoft/msbuild#2443]
[GetInstalledSDKLocations target](https://github.com/dotnet/sdk/issues/1496) runs in every project regardless of whether the project has any SDKs. Can we put a condition on it so that only if there are SDKReferences do we run it?

https://github.com/Microsoft/msbuild/blob/d0d089c1c845bb51f6567593e00403b1ca94f65c/src/Tasks/Microsoft.Common.CurrentVersion.targets#L2163-L2200

**Comment by rainersigwald** [comment]
All of the tasks within it are conditioned on `'@(SDKReference)' != ''`; seems like we could promote that.

**Comment by davkean** [comment]
Make note this with the telemetry we've captured this is currently the 12th slowest target across all MS targets.
