### ISSUE TITLE
Question regarding Nuget target path in MSBuild project files

### ISSUE THREAD

**Issue by jonathanbyrne** [Microsoft/msbuild#2451]
I am trying to put .targets and .props files into the build directory of my NuGet package.  I know how to do this with a .nuspec file but I was hoping to do this in my MSBuild project file.

I can find no documentation of how to do this but it appears to be done in the core-setup file [Microsoft.NETCore.App.pkgproj](https://github.com/dotnet/core-setup/blob/master/src/pkg/projects/Microsoft.NETCore.App/Microsoft.NETCore.App.pkgproj).
```
    <File Include="$(PropsFile)">
      <TargetPath>build/$(NETCoreAppFramework)</TargetPath>
    </File>
```
When I try to replicate the usage above, the build succeeds but the element is apparently ignored because no build directory exists in the NuGet package.  Is there some trick to using this?  Thanks for any guidance you can provide.  (My apologies in advance if this is a question best posed to the NuGet team. I have also asked them.)

_**Version details:**
MSBuild 15.3.409.57025
NuGet 4.3.0.3
Visual Studio 2017 (15.3.0 Preview 7.1)
Windows 10.0.10586_

**Comment by jonathanbyrne** [comment]
I found a different way to accomplish my objective but I'm still confused how the example I referenced above was able to work.  If anyone has a quick explanation, I would love to know but please don't waste time researching anything.

```
<Content Include="MyTargets.targets">
    <Pack>true</Pack>
    <PackagePath>build</PackagePath>
</Content>
```

**Comment by rainersigwald** [comment]
This issue was moved to NuGet/Home#5791

**Comment by rainersigwald** [comment]
Moved this to NuGet since they'll have the best context on how the Pack target consumes MSBuild's output and figures out what to put into the package.
