### ISSUE TITLE
Toolset discovery accepts Team Explorer SKU

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/msbuild#2460]
See https://stackoverflow.com/questions/45760787/trying-to-build-nuget-package-with-vs-2017-team-explorer-installed, pointed out by @dasMulli in https://github.com/Microsoft/msbuild/issues/2369#issuecomment-323581649.

We should consider having a special case for Team Explorer--even if it carries a copy of MSBuild, I can't think of a reason someone would want to use that copy.

**Comment by kenorb** [comment]
Similar: https://github.com/tintoy/msbuild-project-tools-server/issues/8

**Comment by rainersigwald** [comment]
I think this was resolved by https://github.com/microsoft/MSBuildLocator/pull/76.
