### ISSUE TITLE
Building an sln containing a malformed project only generates a confusing warning

### ISSUE THREAD

**Issue by sandorfr** [microsoft/msbuild#2462]
I ran into this case where a project file was not properly modified on a build server. It was actually invalid xml (sample here : https://github.com/geeklearningio/gl-vsts-tasks-file-patch/issues/39)

```
Warning MSB4078: The project file "XXX.Database\XXX.Database.sqlproj" is not supported by MSBuild and cannot be built.
```

Because of this message I assumed there was an issue with SSDT on VSTS 2017 Hosted agent images (https://github.com/Microsoft/vsts-tasks/issues/5063). I think that when the xml is invalid msbuild should fail with an explicit message instead of the current misleading message. 

Actually, if msbuild is being run against the project and not the solution, it displays a more sensible message and it fails:

```
XXX\XXX.Database\XXX.Database.sqlproj(28,4): Error MSB4025: The project file could not be loaded. 'msbuild' is an undeclared prefix. Line 28, position 4.
```

**Comment by rainersigwald** [comment]
Team triage: closing due to age. If you're still seeing this problem, please let us know and we can reactivate it.

**Comment by mc0re** [comment]
The message is still there, still a warning. Should've been an error.
