### ISSUE TITLE
Need to build twice when modifying the csproj file

### ISSUE THREAD

**Issue by Roemer** [Microsoft/msbuild#2463]
Hello

I have the issue that I want to create an unsigned and a signed version of my product.
For this, I first build and pack the unsigned, then modify the csproj and then build again.
For some reason, the second build adds the wrong (the unsigned) nuget references into the generated package.
If I just build again, everything is then ok. It's 100% reproducable.
I use cake for that. The cake file is: https://github.com/Roemer/FlaUI/blob/master/build.cake
Just run Build, then Build-Signed. Now you have unsigned and signed assemblies in the nuget folder. Opening for example FlaUI.UIA2.Signed shows that it has a reference to FlaUI.Core (and not FlaUI.Core.Signed).
If you now run Build-Signed again and look at FlaUI.UIA2.Signed again, the reference is now correctly set to FlaUI.Core.Signed.

What can be the cause of that?

I use VS2017.3.2.

Thanks for your help.

**Comment by rainersigwald** [comment]
I'm afraid this is likely to be dependent on how Cake implements its `MSBuild()` function. I suspect that what you're seeing is the MSBuild project-file cache in action, which prevents loading two versions of the same project within a single build.

You'll have to ask the Cake folks about that.

But in general, I'd recommend replacing the XML manipulation with logic based on properties, and invoking the second build with a different set of properties (perhaps something like `FlaUISign=true`). MSBuild will happily build the same project multiple times with different global properties (just make sure the outputs are orthogonal).

**Comment by Roemer** [comment]
It's pretty much 2 separate msbuild calls. The name of the output and everything is cotrect, just not the nuget project references. Anyway good hint. I will try something like https://msdn.microsoft.com/en-us/library/ms171481.aspx tomorrow.

**Comment by Roemer** [comment]
I somehow can't get it to work correctly :(

I have added the following to the csproj:
```xml
<PropertyGroup Label="Signing" Condition="'$(EnableSigning)'=='true'">
  <SignAssembly>true</SignAssembly>
  <AssemblyOriginatorKeyFile>../../FlaUI.snk</AssemblyOriginatorKeyFile>
  <PublicSign Condition="'$(OS)'!='Windows_NT'">true</PublicSign>
  <AssemblyName>FlaUI.Core.Signed</AssemblyName>
  <OutputPath>bin\$(Configuration)\Signed</OutputPath>
  <IntermediateOutputPath>obj\$(Configuration)\Signed</IntermediateOutputPath>
</PropertyGroup>
```
and added `/p:EnableSigning=true` to the msbuild call.

Now the generated assembly is FlaUI.Core.Signed.dll but the other assemblies which reference this and also generate a package still reference FlaUI.Core (instead of the signed one).
Even rebuilding does not help.
But if I remove the `Condition="'$(EnableSigning)'=='true'"` from the csproj, everything is correct.

**Comment by Roemer** [comment]
I think that the problem is that the project reference
```
  <ItemGroup Label="Project References">
    <ProjectReference Include="..\FlaUI.Core\FlaUI.Core.csproj" />
  </ItemGroup>
```
does not know anything abot the EnableSigning property and adds a reference to the "default" one. Is there any way to fix this like passing the reference this property?

**Comment by Roemer** [comment]
One (ugly) way to solve this would be to use assembly references instead of project references and point to the according dll (either in signed folder or not) but this is far from optimal.

**Comment by rainersigwald** [comment]
You shouldn't need to go down that road.

Again, I don't know much about Cake, but from the msbuild perspective,

```
msbuild.exe your.sln /p:EnableSigning=true
```

or the equivalent API call sets that property for all projects in the solution (most probably ignore it). ProjectReferences should get a consistent view, especially since I from what you posted you're not using exotic metadata.

I'd recommend looking through a log (perhaps a binary log viewed through https://github.com/KirillOsenkov/MSBuildStructuredLog) to try to see where things are going wrong. But I don't know how hard it is to convince Cake to produce such a thing.

**Comment by Roemer** [comment]
I am not using cake until it works from command line right now.
I currently use: `"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\msbuild.exe" src\FlaUI.sln /p:EnableSigning=true` with the same result: The references point to the wrong unsigned one. I'll try to get that structured log.

**Comment by dasMulli** [comment]
@Roemer do I understand correctly that your problem is the dependency nodes of the resulting nuspec file?

The referenced package names are fixed at restore time so you'd need to do an `msbuild /t:Restore /p:EnableSigning=true` to fix that between builds. This is similar to https://github.com/NuGet/Home/issues/4790 but for the `PackageId` instead of just the version.

**Comment by rainersigwald** [comment]
Oh, THAT would explain it!

**Comment by Roemer** [comment]
Whoa awesome, that solves the problem although I do not fully understand why actually.
My situation:
I have FlaUI.Core.csproj and FlaUI.UIA2.csproj
FlaUI.UIA2 references (Project Reference) FlaUI.Core.
If I build the sln, I get two nuget packets and FlaUI.UIA2 correctly references FlaUI.Core in the nuget.
Now I have this property `p:EnableSigning` which changes the assembly name by adding a .Signed and set the signing to `true`. If I now build the solution with this property, I get the correctly named nuget packages. But the nuget reference from FlaUI.UIA2.Signed points to FlaUI.Core instead of FlaUI.Core.Signed.

If I now add a Restore before a Build, everything works correct :)

**Comment by dasMulli** [comment]
Yes the point is that the dependencies that go into the nuspec are read from `obj\project.assets.json` which is created at restore time from the values returned by the referenced projects. So if you have any properties that affect the resulting `PackageId` and `PackageVersion` names or the properties they are defaulted to (`AssemblyName`), they need to be set at restore time.

**Comment by Roemer** [comment]
Even if I use different IntermediateOutputPath for the signed and unsigned builds?

**Comment by Roemer** [comment]
It still is not working 100% :/ The first time it works right and from then on it's wrong again.
I build with Clean;Restore;Rebuild.
If I manually delete all bin/obj it works again.

**Comment by dasMulli** [comment]
about the output paths:
It really only depends on how much headache medicine you have for when things go wrong 😂 . There are many properties involved that control the restore+build experience - NuGet has a `RestoreOutputPath` that should be the same as `BaseIntermediateOutputPath` which in turn controls `MSBuildProjectExtensionsPath` (=> auto-imported props/targets that nuget generates) and `ProjectAssetsFile` (=> dependency graph). E.g. see https://stackoverflow.com/questions/45575280/msbuild-nuget-restoreoutputpath-how-to-make-it-work.

I guess we'd need to see a build log of a build that went wrong.. you can add `/bl` and zip+upload the resulting binary logfile here.

What's also a bit annoying is that incremental builds have problems with things passed in as commandline argument since there may not be a file change that triggers targets to rebuild - e.g. pack targets might think that there's noting to do to regenerate the nuspec file in your `obj` directory.

**Comment by dasMulli** [comment]
Crazy idea:

```xml
<ItemGroup>
  <NuGetPackInput Include="$(ProjectAssetsFile)" />
</ItemGroup>
```

👆 in the csproj to make sure that the `GenerateNuspec` target always runs even if all other inputs (build output) has not changed.

**Comment by Roemer** [comment]
What I see in the log is; 

> Projekt "E:\Development\MyGitHub\FlaUI\src\FlaUI.sln" auf Knoten "1", Restore Ziel(e).
> ValidateSolutionConfiguration:
>   Die Projektmappenkonfiguration "Release|Any CPU" wird erstellt.
> Restore:
>   Commit für Wiederherstellung wird ausgeführt...
>   Die Assetdatei wurde nicht geändert. Das Schreiben der Assetdatei wird übersprungen. Pfad: E:\Development\MyGitHub\FlaUI\sr
>   c\FlaUI.Core\obj\project.assets.json

So it skips the regeneration of the asset file for some reasons.

**Comment by Roemer** [comment]
Even Adding the NuGetPackInput does not change anything unfortunately. Best way currently is to delete the obj folder for th two builds.

**Comment by dasMulli** [comment]
Interesting. There's also an `/p:RestoreForce=true` option for nuget restores now in 4.3 to disable their new "no-op restore" feature.

**Comment by Roemer** [comment]
hmm interesting, let's try that one.

**Comment by Roemer** [comment]
That seems to finally do the trick.
In cake-term, my build now looks like:
```csharp
Task("Build")
    .IsDependentOn("Restore-NuGet-Packages")
    .Does(() =>
{
    var buildSettings = new MSBuildSettings {
        Verbosity = Verbosity.Minimal,
        ToolVersion = MSBuildToolVersion.VS2017,
        Configuration = configuration,
        PlatformTarget = PlatformTarget.MSIL,
    }.AddFileLogger(new MSBuildFileLogger {
        LogFile = "./BuildLog.txt",
        MSBuildFileLoggerOutput = MSBuildFileLoggerOutput.All
    });
    // Restore and build
    buildSettings.WithTarget("Restore").WithTarget("Build");
    // Hide informational warnings for now
    buildSettings.Properties.Add("WarningLevel", new[] { "3" });
    // Force restoring
    buildSettings.Properties.Add("RestoreForce", new[] { "true" });

    // First build with default settings
    MSBuild(slnFile, buildSettings);

    // Second build with signing enabled
    buildSettings.FileLoggers.First().LogFile = "./BuildLogSigned.txt";
    buildSettings.Properties.Add("EnableSigning", new[] { "true" });
    MSBuild(slnFile, buildSettings);
});
```

**Comment by dasMulli** [comment]
Ah I see you tried to call restore and build in the same invocation.. that's not very good.. https://github.com/Microsoft/msbuild/issues/2455

**Comment by Roemer** [comment]
Can split that as well. But the RestoreForce seems to have helped definitely.

**Comment by Roemer** [comment]
I adjusted it to:
```csharp
Task("Build")
    .IsDependentOn("Restore-NuGet-Packages")
    .Does(() =>
{
    var buildSettings = new MSBuildSettings {
        Verbosity = Verbosity.Minimal,
        ToolVersion = MSBuildToolVersion.VS2017,
        Configuration = configuration,
        PlatformTarget = PlatformTarget.MSIL,
    }.AddFileLogger(new MSBuildFileLogger {
        LogFile = "./BuildLog.txt",
        MSBuildFileLoggerOutput = MSBuildFileLoggerOutput.All
    });
    // Hide informational warnings for now
    buildSettings.Properties.Add("WarningLevel", new[] { "3" });
    // Force restoring
    buildSettings.Properties.Add("RestoreForce", new[] { "true" });

    // First build with default settings
    buildSettings.Targets.Clear();
    buildSettings.WithTarget("Restore");
    MSBuild(slnFile, buildSettings);
    buildSettings.Targets.Clear();
    buildSettings.WithTarget("Build");
    MSBuild(slnFile, buildSettings);

    // Second build with signing enabled
    buildSettings.FileLoggers.First().LogFile = "./BuildLogSigned.txt";
    buildSettings.Properties.Add("EnableSigning", new[] { "true" });
    buildSettings.Targets.Clear();
    buildSettings.WithTarget("Restore");
    MSBuild(slnFile, buildSettings);
    buildSettings.Targets.Clear();
    buildSettings.WithTarget("Build");
    MSBuild(slnFile, buildSettings);
});
```
No problems so far!

**Comment by rainersigwald** [comment]
Closing since the last comment had things working.
