### ISSUE TITLE
Content file not included when reference via PackageReference instead of packages.config

### ISSUE THREAD

**Issue by henning-krause** [Microsoft/msbuild#2466]
I recently switched my project to use the PackageReference method (`<RestoreProjectStyle>PackageReference</RestoreProjectStyle>`) to include nuget packages and ran into a problem when I tried import the [evopdf](https://www.nuget.org/packages/EvoPDF/) package.

The packages does two things:
* Add an assembly reference to the current project
* Add a content file of around 50MB to the output of the project (evointernal.dat).

The package is imported just fine when using the packages.config approach and the evointernal.dat appears in the output directory. 

But with the new approach, I have two issues:
1. Even after package restore / build, the package is not shown in the "References" section. The dlls appears in the output directory, however.
2. The evointernal.dat is never copied to the output directory.

I tried the restore both with Nuget 4.3 as well as msbuild 15.3.409.57025.

Is there something wrong with the package or is there a bug in the PackageReference implementation?

**Comment by rainersigwald** [comment]
This issue was moved to NuGet/Home#5803
