### ISSUE TITLE
Provide a way to check if a target exists in a project without errors

### ISSUE THREAD

**Issue by emgarten** [Microsoft/msbuild#2471]
### Proposal

There should be a way to check if a target exists or not in a project without the user seeing warnings/errors when it does not.

### Scenario

NuGet restore walks all project references by using the `<MSBuild>` element to call a target in child projects. Child projects that do not import common props/targets are missing the restore target display an error to the user. Often it is expected that the target will not exist, for example if the user creates a custom project file and references it.

Since Restore isn't able to gracefully probe projects the user sees a lot of extra noise when the target is missing. Restore also isn't able to tell the difference between a project that doesn't support restore, and one that has invalid XML or other issues.ore from failing when it should.

### Possible ways to solve this

* `<MSBuild>` could provide an option to skip projects where the target doesn't exist
* Provide a way to filter a set of projects based on the existence of a target or property

**Comment by emgarten** [comment]
@AndyGerlicher which release of VS/CLI will this be available in?

**Comment by AndyGerlicher** [comment]
Any 15.5 Preview 2 bits (CLI or VS). Around 15.5.154+ or so.

**Comment by mungojam** [comment]
It seems that this isn't implemented in msbuild /t:restore on VS 15.5, so we are still having to use 'nuget restore' instead. Will it be implemented in msbuild for VS 15.6?
