### ISSUE TITLE
Building a vs2017 csproj - how to resolve sdk path

### ISSUE THREAD

**Issue by dazinator** [Microsoft/msbuild#2477]
I'm using the msbuild nuget packages to try and build a vs2017 csproj file as part of an integration test. 

Here is what I am doing in the test:
```
 var projectCollection = new ProjectCollection();
 var project = projectCollection.LoadProject(projectFilePath)
 project.SetProperty("PackageVersion", "0.0.1");
 
 var result = project.Build("Pack");                
 return result;
```

However the build fails with this message:

```
Message: Microsoft.Build.Exceptions.InvalidProjectFileException : The SDK 'Microsoft.NET.Sdk' specified could not be found.  
```

What do I need to provide so that the SDK can be resolved during my test? Do I need to set some additional project or global properties?

If I switch the csproj file back to the old format (i.e explicity targets imports) it works.

**Comment by KirillOsenkov** [comment]
See https://github.com/Microsoft/msbuild/issues/2369

**Comment by dazinator** [comment]
Thanks. Will close this in favour of #2369
