### ISSUE TITLE
Custom MSBuild for .NET Core task cannot reference System.Xml.XPath.XmlDocument

### ISSUE THREAD

**Issue by jkoritzinsky** [microsoft/msbuild#2484]
If a custom MSBuild task uses `System.Xml.XPath.XmlDocument.dll`, MSBuild will fail to load it correctly and will throw a `FileNotFoundException` while trying to load it.

I have attached an example project: [XPathBugRepro.zip](https://github.com/Microsoft/msbuild/files/1265275/XPathBugRepro.zip)

It builds both an executable and a dll with a task. You can run the executable via the `dotnet` CLI and it will not crash. If you want to repro the issue with MSBuild, use either `dotnet build test.proj` or `dotnet msbuild test.proj` in the bin directories. The MSBuild test run will crash with the above exception.

**Comment by jkoritzinsky** [comment]
After some investigation, I've found the underlying issue:

MSBuild uses `System.Xml.XPath.XmlDocument` Version 4.0.1. My packages use version 4.3.0. Since the assembly version of version 4.3.0 is greater than the assembly version used by MSBuild, MSBuild fails to load the assembly, and subsequently crashes. I'm trying to reference the lower version, but I'm getting downgrade errors because a dependency I have uses it, so this fix is extremely fragile and I'm not even sure if it will work.

Any ideas on how to fix this so either there are better error messages or newer versions of the assembly can be loaded in?

**Comment by rainersigwald** [comment]
This should be resolved now by #4916.
