### ISSUE TITLE
NuGet package is generated when 'GeneratePackageOnBuild' is not set

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [Microsoft/msbuild#2495]
Could you please explain how `Generate NuGet packages on build` is enabled for [this]( https://github.com/scottdorman/cadru/blob/master/src/Cadru.Contracts/Cadru.Contracts.csproj) project without ` GeneratePackageOnBuild` explicitly set in `.csproj` file?

If you run `msbuild` against this project, it will generate NuGet package. If you open `Package` tab in properties in Visual Studio, you will see that `Generate NuGet packages on build` is checked. If you uncheck (without saving) then check and only then save, `<GeneratePackageOnBuild>true</GeneratePackageOnBuild>` will appear.

I need to understand how this is currently set implicitly. This is probably something very basic, sorry my ignorance.

Motivation behind this is the following: We in [AppVeyor CI]( https://www.appveyor.com/) have feature to [package NuGet]( https://www.appveyor.com/docs/build-phase/#packaging-net-core-nuget-libraries) too, and want to avoid duplication if `Generate NuGet packages on build` is set. It seems easy problem if we can rely on `<GeneratePackageOnBuild>true</GeneratePackageOnBuild>` in `.csproj`, but I feel uncertain now.

**Comment by dasMulli** [comment]
There is an import of [..\..\build\common.props](https://github.com/scottdorman/cadru/blob/0f1fdbf340e2906a3c353b1c826bafa9385253fe/src/Cadru.Contracts/Cadru.Contracts.csproj#L2) which contains https://github.com/scottdorman/cadru/blob/0f1fdbf340e2906a3c353b1c826bafa9385253fe/build/common.props#L5

**Comment by IlyaFinkelshteyn** [comment]
Ah, thanks a lot!
