### ISSUE TITLE
Cross-platform solution for default encoding

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#251]
The unit test `ExecTaskUnicodeCharacterInCommand` passes on full-framework master but fails in xplat, because the default encoding isn't available on CoreCLR.  We should fix that, and there are good ideas as to how in #246.  For now I'm going to disable the test since I'm more focused on getting failures to zero than on fixing things, and there's an easy workaround for this: don't build on paths with non-ASCII characters in them.

**Comment by rainersigwald** [comment]
This also applies to `FileLogger_Tests.BasicNoExistingFile`.

**Comment by cdmihai** [comment]
Fixed by #288
