### ISSUE TITLE
Nuget package added but not used TFS

### ISSUE THREAD

**Issue by Sm1le291** [microsoft/msbuild#2526]
[buildLog19.txt](https://github.com/Microsoft/msbuild/files/1303802/buildLog19.txt)
Hi guys! I have some problem with my packages which i add in runtime with this code:
``  <Target Name="BeforeResolveReferences" 
<Exec Command="&quot;\\out-oracle\nuget\nuget&quot; update $(MSBuildProjectDirectory)\packages.config -id Sbt.CMS -FileConflictAction overwrite -Source \\out-oracle\nuget -Version 1.0.$(BUILD_BUILDID); &quot;\\out-oracle\nuget\nuget&quot; update $(MSBuildProjectDirectory)\packages.config -id Sbt.CMS.Infrastructure -FileConflictAction overwrite -Source \\out-oracle\nuget -Version 1.0.$(BUILD_BUILDID)" /></Target>``
Packages successfully added but not used and i show this error in TFS logs:
``2017-09-14T16:44:03.9210456Z Output file "obj\Debug\Sbt.CMS.Cashflow.Infrastructure.dll" does not exist.
2017-09-14T16:44:03.9210456Z Task "Csc"``
And then a lot of errors about missing reference when msbuild tries to build solution. Who knows, why?
How I may say msbuild copy this refernce to output folder and use it?

**Comment by rainersigwald** [comment]
Team triage: closing due to age. If you're still seeing this problem, please let us know and we can reactivate it.
