### ISSUE TITLE
Couldn't find documentation concerning Private tag in ProjectReference item

### ISSUE THREAD

**Issue by kashmervil** [microsoft/msbuild#2528]
[This](https://docs.microsoft.com/en-us/visualstudio/msbuild/itemdefinitiongroup-element-msbuild) documentation doesn't contain anything about this tag even for Reference items.

[That](https://msdn.microsoft.com/en-us/library/bb629388.aspx?f=255&MSPPError=-2147217396) has some information about Private tag in Reference items but doesn't list it as available tag for ProjectReference, neither does MSBuild xml scheme definition file (making a logicaly correct msbuild file invalid from the schema perspective).

However VS inserts it inside ProjectReference Item if one toggles **Copy Local** setting, and MSBuild does take it into account omitting it from the ouput during the build process.

**Comment by rainersigwald** [comment]
This issue was moved to MicrosoftDocs/visualstudio-docs#5250
