### ISSUE TITLE
Cannot combine batching and item functions

### ISSUE THREAD

**Issue by natemcmaster** [Microsoft/msbuild#2546]
It appears MSBuild doesn't correctly evaluating item functions when batching a task.

**Repro**

```xml
<Project>
  <Target Name="Build">
    <Message Text="%(A.Identity)/%(A.Version) = @(A->AnyHaveMetadataValue('Version', '2.0'))" Importance="High"/>
  </Target>

  <ItemGroup>
    <A Include="Item1" Version="1.0" />
    <A Include="Item2" Version="2.0" />
  </ItemGroup>
</Project>
```

**Expected Output**
```
  Item1/1.0 = true
  Item2/2.0 = true
```

**Actual**
```
  Item1/1.0 = false
  Item2/2.0 = true
```

**Info**
```
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
```

**Comment by am11** [comment]
Seems like `TaskExecutionHost.SetTaskParameters` calls into the expander one at a time (`foreach` item). `AnyHaveMetadataValue` intrinsic is a special use case where it needs full set of items.

Batching fix would probably reside at `TaskExecutionHost` level, so the calls to `evaluatedItems.GetItems(expressionCapture.ItemType)` in expander get both instances of list `A`.

@rainersigwald, is it (by-design) limitation of MSBuild's evaluator that one cannot build logical disjunction?

**Comment by dasMulli** [comment]
Why would you expect true on the first item?

When batching over metadata (like `%(Version)`), the `@()` syntax only returns elements with that metadata. So for the batch with `%(Version)` = `1.0`, there is no item with `Version`=`2.0` metadata, thus evaluating to false.

For example:
```xml
<Project>
  <ItemGroup>
    <A Include="Item1" Version="1.0" />
    <A Include="Item2" Version="1.0" />
    <A Include="Item3" Version="2.0" />
    <A Include="Item4" Version="2.0" />
    <A Include="Item5" Version="3.0" />
  </ItemGroup>
  <Target Name="Build">
    <Message Importance="high" Text="%(A.Version): @(A)" />
  </Target>
</Project>
```

Prints:
```
  1.0: Item1;Item2
  2.0: Item3;Item4
  3.0: Item5
```

**Comment by am11** [comment]
Right, so we will have to define separate item list for LHS within the target:

```xml
<Project>

  <Target Name="Build">
    <ItemGroup>
      <Name Include="%(A.Identity)/%(A.Version)" />
    </ItemGroup>

    <Message Text="%(Name.Identity) = @(A->AnyHaveMetadataValue('Version', '2.0'))" Importance="High"/>
  </Target>

  <ItemGroup>
    <A Include="Item1" Version="1.0" />
    <A Include="Item2" Version="2.0" />
  </ItemGroup>

</Project>
``` 

Prints:

```powershell
  Item1/1.0 = true
  Item2/2.0 = true
```

**Comment by natemcmaster** [comment]
> When batching over metadata (like %(Version)), the @() syntax only returns elements with that metadata.

This is the behavior in question. I was expecting the item function evaluation to be independent of the batching. If this behavior is by-design, then this can be closed as user-error.

**Comment by natemcmaster** [comment]
Closing. Behavior is by-design.
