### ISSUE TITLE
Project Sdk property not optional on Unix?

### ISSUE THREAD

**Issue by siegfriedpammer** [Microsoft/msbuild#2550]
Some time ago we migrated our projects to the new build system. (The main csproj see here: https://github.com/icsharpcode/ILSpy/blob/master/ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj)

(Note: On Windows we use ILSpy.sln on Unix we use ICSharpCode.Decompiler.Console.sln)

This works perfectly fine on Windows, however when we try to open/build the project on mac/unix. VSmac and msbuild cannot open the project unless the `Sdk="Microsoft.NET.Sdk"` is added, however, when we add that on Windows as well, we get some warnings.

> \ILSpy\ICSharpCode.Decompiler\ICSharpCode.Decompiler.csproj(3,3): warning MSB4011: "C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props" cannot be imported again. It was already imported at "\ILSpy\ICSharpCode.Decompiler\ICSharpCode.Decompiler.csproj". This is most likely a build authoring error. This subsequent import will be ignored.

Seems like #1392 is not fully supported on Unix.

Is there a way to define the Sdk attribute conditionally (in one single file)? Using a separate csproj file per platform is not a usable workaround as all msbuild projects in the same directory use `obj\project.assets.json` and conflict with each other (among other problems we've experienced...).

**Comment by mrward** [comment]
The VS Mac bug is currently being tracked on [bugzilla](https://bugzilla.xamarin.com/show_bug.cgi?id=58564).

Ignoring VS Mac for now, is there a problem with just using msbuild from the command line if this [commit](https://github.com/icsharpcode/ILSpy/commit/7efe204b4726381cbb81920a30b30ea3e6af7d05) is reverted?

**Comment by radical** [comment]
I hit other issues trying to build `ILSpy.sln` with msbuild/mac on the command line. With these [changes](https://gist.github.com/radical/192ceccfd17e42b18643a7884f9330ff) changes I was able to get it to almost build. But there is other stuff that needs to be fixed in the projects before it will build completely, AFAICS.

**Comment by siegfriedpammer** [comment]
@radical `ILSpy.sln` is not indented for use on Unix as it contains WPF projects.

@mrward removing the conditions on the imports fixes the build. Not sure why I needed to add them before. Thanks for the reference on bugzilla.
