### ISSUE TITLE
Error building msbuild on OS X 10.12.6 (Sierra)

### ISSUE THREAD

**Issue by catastrophe-brandon** [Microsoft/msbuild#2559]
I am attempting to build `msbuild` on OSX 10.12.6 (Sierra). To kick off the build I executed the command as shown below:

```$ ./cibuild.sh --host CoreCLR
Installing dotnet cli...
Restoring BuildTools version 1.0.27-prerelease-00927-05...
The type initializer for 'Crypto' threw an exception.
ERROR: Could not restore build tools correctly. See '/Users/btweed/repos/github/msbuild/init-tools.log' for more details.1
Initializing BuildTools...
/Users/btweed/repos/github/msbuild/init-tools.sh: line 122: /Users/btweed/repos/github/msbuild/packages/Microsoft.DotNet.BuildTools/1.0.27-prerelease-00927-05/lib/init-tools.sh: No such file or directory
ERROR: An error occured when trying to initialize the tools. Please check '/Users/btweed/repos/github/msbuild/init-tools.log' for more details.1
```

Here are the contents of `init-tools.log`:

```
Running: /Users/btweed/repos/github/msbuild/init-tools.sh
Installing 'https://dotnetcli.blob.core.windows.net/dotnet/Sdk/1.0.0-preview3-003686/dotnet-dev-osx-x64.1.0.0-preview3-003686.tar.gz' to '/Users/btweed/repos/github/msbuild/Tools/dotnetcli/dotnet.tar'
Running: /Users/btweed/repos/github/msbuild/Tools/dotnetcli/dotnet restore "/Users/btweed/repos/github/msbuild/Tools/1.0.27-prerelease-00927-05/project.json" --no-cache --packages /Users/btweed/repos/github/msbuild/packages --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json --legacy-packages-directory
Running: /Users/btweed/repos/github/msbuild/packages/Microsoft.DotNet.BuildTools/1.0.27-prerelease-00927-05/lib/init-tools.sh /Users/btweed/repos/github/msbuild /Users/btweed/repos/github/msbuild/Tools/dotnetcli/dotnet /Users/btweed/repos/github/msbuild/Tools
```

It looks like there are files in the repo directory that the script expects to be there. Is there some additional configuration that needs to be done before running `cibuild.sh`? For example, is there some environment variable I need to set to point it to my installation of the .NET SDK for OS X?

**Comment by catastrophe-brandon** [comment]
Ok, I think I figured out what I actually need. In the .NET SDK for OSX is the `dotnet` command which takes `msbuild` as an argument. If I understand things correctly, to build a project one must execute `dotnet msbuild` which is a bit different from Windows, but very workable. Thank you!

**Comment by dasMulli** [comment]
I've run into similar restore issues - a `ulimit -n 5000` call usually resolves this.

**Comment by catastrophe-brandon** [comment]
In the end I was able to just sidestep the issue because I don't actually need to build `msbuild`. I'm just learning the tools and consequently doing some dumb things.
