### ISSUE TITLE
Add MSBuild property for current version of MSBuild

### ISSUE THREAD

**Issue by dsplaisted** [Microsoft/msbuild#256]
As [noted](https://github.com/Microsoft/msbuild/pull/254#discussion_r41272476) by @rainersigwald, the version number (14.1) is currently encoded in the path and project file for `Microsoft.Common.props`.  Ideally this number should be defined once and used to generate the right path, as well as version numbers such as `MSBuildConstats.CurrentProductVersion`, the assembly versions, and the assembly versions used in `Microsoft.Common.tasks` or other build files.

**Comment by AArnott** [comment]
FWIW, the Nerdbank.GitVersioning that this project already uses creates an ThisAssembly static class that contains all the version information. Perhaps that can be used to initialize these properties in the engine?

**Comment by rainersigwald** [comment]
This is done: `$(MSBuildVersion)` was added in #2819.
