### ISSUE TITLE
Linux/mono support (xplat branch)

### ISSUE THREAD

**Issue by AndyGerlicher** [Microsoft/msbuild#26]
We've done work internally to experiment with MSBuild on Linux/mono, we need to get this out in the open as soon as possible. Creating an issue so everyone is aware this is coming soon (within a week!).

**Comment by haruair** [comment]
:+1:

**Comment by shahid-pk** [comment]
:+1:

**Comment by directhex** [comment]
:+1:

**Comment by alanmcgovern** [comment]
:+1:

**Comment by enricosada** [comment]
:+1:

**Comment by Therzok** [comment]
:+1:

**Comment by noahmorrison** [comment]
:+1: 

Seriously though, I'm excited about this new Microsoft.

**Comment by t0b1nux** [comment]
:+1: Microsoft, I love what you are doing !

**Comment by ozkxr** [comment]
:+1:

**Comment by rokadias** [comment]
:+1:

**Comment by YagoCarballo** [comment]
:+1:

**Comment by lubingxian** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by Widrogo** [comment]
:+1:

**Comment by cnblogs-dudu** [comment]
:+1:

**Comment by JefWu** [comment]
:+1:

**Comment by tjoskar** [comment]
:+1:

**Comment by akoeplinger** [comment]
Looks like some WIP just showed up in the xplat branch: https://github.com/Microsoft/msbuild/commit/5063857bd05d080a0168f193ef7c19a1c1654960

**Comment by PandaTwo** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by jasonwilliams200OK** [comment]
> (within a week!).

@AndyGerlicher, meaning it's going to happen by tomorrow? :heart_eyes_cat:

**Comment by jordimontana82** [comment]
Lovely! Was using XBuild since now! :+1:

**Comment by HellDeveloper** [comment]
:heart_eyes_cat:

**Comment by AndyGerlicher** [comment]
Closing this issue since we pushed the xplat branch yesterday! We'll have separate issues for upcoming work.
