### ISSUE TITLE
MSBuildEngineLogger test fails on CoreCLR with DuplicateProjectSwitchError

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#260]
This test (in `Microsoft.Build.CommandLine.UnitTests.dll`) is failing with what looks like a misinterpretation of the command line somewhere in `MSBuildApp.Execute`.

**Comment by rainersigwald** [comment]
@cdmihai Can you take a look at this?  It seems likely to be self-contained and a good way to start debugging through .NET Core code and figuring out the internals of MSBuild.

**Comment by cdmihai** [comment]
fixed by #263
