### ISSUE TITLE
Auto increment assembly version

### ISSUE THREAD

**Issue by weitzhandler** [Microsoft/msbuild#2617]
Hi,

In the old _csproj_ file, we could set `AssemblyVersion("1.0.*")` (in the _AssemblyInfo.cs_ file) to have the assembly version auto increment by itself.

Currently (VS 15.3.5) when trying to set this in new project types, I get this error:

>Error CS7034: The specified version string does not conform to the required format - major[.minor[.build[.revision]]]

This used to be a very useful feature for many years. I beg you to please bring it back.

**Comment by rainersigwald** [comment]
You can still do this, though it's generally not recommended because it keeps your build from being a deterministic transformation of your source. See https://github.com/dotnet/roslyn/blob/eebf27679e00c1fafed8b0f6c53013fd54e04cc4/docs/compilers/Deterministic%20Inputs.md.
