### ISSUE TITLE
Normalization of path during wildcard includes breaks excludes

### ISSUE THREAD

**Issue by weshaggard** [Microsoft/msbuild#2620]
Looks like https://github.com/Microsoft/msbuild/pull/2557 caused a regression with some exclude code paths we have in corefx. See https://github.com/dotnet/corefx/pull/24534 for one change I've needed to work around this issue (I've since hit numerous other places that are affected).

Here is an example of the repro:
```
_NETStandardRefFolder = D:\git\corefx\packages/netstandard.library\2.0.1\build\netstandard2.0\ref
_excludeForNetFx contains multiple items but for my example it contains mscorlib

<_netstandardShimAssemblies Include="$(_NETStandardRefFolder)\*.dll" Exclude="@(_excludeForNetFx->'$(_NETStandardRefFolder)\%(Identity).dll')" />

After that statement is executing _netstandardShimAssemblies contains:
D:\git\corefx\packages\netstandard.library\2.0.1\build\netstandard2.0\ref\mscorlib.dll

But the Exclude contains:
D:\git\corefx\packages/netstandard.library\2.0.1\build\netstandard2.0\ref\mscorlib.dll
```
Notice the difference in slash after packages directory. 

That code used to work but doesn't any longer. Given both the wildcard and the Exclude expressions both use the same property I would expect this to work.

**Comment by cdmihai** [comment]
Marked as duplicate to #2621
