### ISSUE TITLE
Getting MSBuild properties from the new project format with the Visual Studio extension

### ISSUE THREAD

**Issue by Petermarcu** [microsoft/msbuild#2633]
@ionoy commented on [Mon Oct 09 2017](https://github.com/Microsoft/dotnet/issues/504)

I have an extension that needs to read MSBuild properties. 

Code looks like this:

```csharp
Project project = GetProject();
var intermediatePath = project.ConfigurationManager.ActiveConfiguration.Properties.Item("IntermediatePath");
```

It worked well with the old format, but with the new format, there is no `IntermediatePath` or `IntermediateOutputPath` or any property containing `obj` for that matter.

How do I get the intermediate output path with the new project format?

---

@ionoy commented on [Mon Oct 09 2017](https://github.com/Microsoft/dotnet/issues/504#issuecomment-335207062)

Maybe I'm misunderstanding something, but my issue is that I don't have all the properties loaded. There is no problem with SDK since VS/DTE takes care of it.

---

@jnm2 commented on [Mon Oct 09 2017](https://github.com/Microsoft/dotnet/issues/504#issuecomment-335208170)

Oh sorry, my bad.

**Comment by rainersigwald** [comment]
Team triage: closing due to age. If you're still seeing this problem, please let us know and we can reactivate it.
