### ISSUE TITLE
Integrating the latest msbuild preview into a Docker container

### ISSUE THREAD

**Issue by cveld** [Microsoft/msbuild#2659]
As posted on StackOverflow https://stackoverflow.com/questions/46883458/how-to-apply-the-latest-msbuild-in-a-docker-image I would like to know how I can get a Docker container running with the latest msbuild preview as part of Visual Studio 2017 preview 15.5.0 version 1.0. Here msbuild carries version 15.5.113.63837.

I already spotted the following blog:
https://blogs.msdn.microsoft.com/heaths/2017/09/18/installing-build-tools-for-visual-studio-2017-in-a-docker-container/

Which looks promising. Only now I need to know the magic string for this particular preview build of the vs_buildtools.exe executable.

**Comment by mawl** [comment]
We also would like to evaluate the new build tools in a container because of this issue: https://github.com/Microsoft/vstest/issues/940

Is there a roadmap when version 15.5 will be released?

**Comment by rainersigwald** [comment]
15.5 was released long ago; if build-tools-on-Docker breaks for a future release please file a new issue.
