### ISSUE TITLE
Old and new csproj format, problems with /target:restore;build

### ISSUE THREAD

**Issue by UncleFirefox** [microsoft/msbuild#2666]
Hi,

I have on sln with old and new csproj format together. All targeting net461. The old projects are still there are:

1. Migration project using EF6
2. Tests using Specflow and NUnit

This kind of projects do magic on the csproj so we preferred to keep them with the old format till we migrate to efcore and specflow gives support for the new csproj.

So with Visual Studio 15.4 everything seems to work fine but with Visual Studio Build Tools, when we issue `&'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe' /p:Configuration=Release "/t:Restore;Build"` we get the following problems:

1. Test project: `This project references NuGet package(s) that are missing on this computer. [...] The missing file is ..\..\packages\NUnit3TestAdapter.3.8.0\build\net35\NUnit3TestAdapter.props.`
2. EF project: `warning MSB3245: Could not resolve this reference. Could not locate the assembly "EntityFramework.Sq
lServer, Version=6.0.0.0 [...] Considered ..\..\packages\EntityFramework.6.1.3\lib\net45\EntityFramework.SqlServer.dll`

I guess it's because the restore issued here with msbuild puts everything on `%UserProfile%\.nuget` the thing is that with the normal nuget.exe issuing a restore, when it detects an old csproj it also puts dependencies on the packages folder of the solution, so it seems theres a mismatch on behavior, ultimately causing the build to fail... Is it the expected behavior or this is an unsupported scenario?

Thanks!

**Comment by dasMulli** [comment]
Please check the following:
* The `Restore` target will not restore packages.config based projects. For that you still need `nuget.exe restore`.
* You cannot safely run the restore and build target from the same invocation, see https://github.com/Microsoft/msbuild/issues/2455 (MSBuild 15.5 has a new `/restore` argument now).

**Comment by UncleFirefox** [comment]
Ok, good to know! By the way, you mention MSBuild 15.5 for the new `/restore` flag but the latest version as far as I'm aware is `15.4.8.50001`, is a new MSBuild to be released soon?

**Comment by dasMulli** [comment]
(not affiliated with MS) there's a preview already (https://www.visualstudio.com/en-us/news/releasenotes/vs2017-preview-relnotes)

**Comment by UncleFirefox** [comment]
Thanks @dasMulli! Another question, does anybody know when the BuildTools will include support for .NET  Core > 1.1 ? At least in the workflows you can install it mentions .NET Core 1.0 - 1.1, does that implicate being able to compile netcoreapp2.0 or it's scheduled for a future release?

**Comment by damtur** [comment]
@dasMulli 
> The Restore target will not restore packages.config based projects. For that you still need nuget.exe restore.

Can you please please put that into documentation here: https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#restore-target
I've been trying to find that information for a couple of hours. 

Thank you for that comment!
