### ISSUE TITLE
Support writing PerformanceSummary to file

### ISSUE THREAD

**Issue by dsplaisted** [Microsoft/msbuild#2669]
You can specify `/clp:PerformanceSummary` to show the time spent in each task and target.  However, there's no way to get this information with a file logger.  It would be helpful to be able to write this information to a log file.  This would make it easier to capture this information without having to redirect the console output.

**Comment by cdmihai** [comment]
Apparently it's possible. Most minimal thing I could get:  `/fl /flp:PerformanceSummary;v=q;ErrorsOnly`
