### ISSUE TITLE
Custom task assembly locked by MSBuild after building in Visual Studio

### ISSUE THREAD

**Issue by bretehlert** [microsoft/msbuild#2670]
When building a project in Visual Studio that has a custom task, the assembly containing the custom task is locked by MSBuild until the Visual Studio is closed and the process exits. Is there any way to get MSBuild to shadow copy the custom task assembly or unload the assembly, so that the original file is not locked and can be overwritten without closing VS?

We have in our csproj:
```
<UsingTask AssemblyFile="Path\To\MyTask.dll" TaskName="MyTask"/>
<Target Name="AfterBuild">
  <MyTask/>
</Target>
```

We would like the Path\To\MyTask.dll file to not be locked following a completed build of the csproj within Visual Studio.

**Comment by rainersigwald** [comment]
Specify `TaskFactory="TaskHostFactory"` in the `UsingTask`--see #5144.

**Comment by RobertAcksel** [comment]
> 
> 
> Specify `TaskFactory="TaskHostFactory"` in the `UsingTask`--see #5144.

I did specify TaskFactory as you suggested but this has no effect. My Task Assembly remains locked until i close VS 
Have this with VS 2019.10 on netcoreapp3.1 and net5.0.
I am missing something here?
