### ISSUE TITLE
Optimize away separate evaluation for /restore when the restore didn't actually pull down new props/targets

### ISSUE THREAD

**Issue by nguerrera** [Microsoft/msbuild#2677]
We're moving the CLI's implicit restore over to using /restore. I was describing to @DustinCampbell how this will eliminate the need for two processes, but not the need for two evaluations. He pointed out that we don't always need two evaluations. 

Common cases:
* No nuget packages are referenced that pull in props/targets
* Restore was incremental and did change the props/targets that were pulled down previously

Perhaps the Restore target could return a value to indicate whether or not it invalidated the evaluation. If it indicates that no props/targets have changed, then we could reuse the same evaluation for build...

cc @emgarten  @jeffkl @AndyGerlicher @davkean

**Comment by davkean** [comment]
This is a damn good idea. This would immediately save 400ms in our no changes restore.

//cc @jainaashish

**Comment by emgarten** [comment]
It should be possible to find the last modified date of .nuget.g.props and .nuget.g.targets before restore and compare it to the modified date after restore. If they are the same then there haven't been any changes. 

Restore checks that something actually changed before modifying the props/targets. These files should also always exist, if they aren't there then the project is in a bad state.

**Comment by davkean** [comment]
To do that we need to evaluate and know about stuff that only NuGet should know about. I'd prefer the restore target returning something.

**Comment by emgarten** [comment]
@davkean that makes sense. Restore could return a RestoreResult item with metadata for the props/targets change status.

I've opened https://github.com/NuGet/Home/issues/6122 to track the work for adding this to restore.

**Comment by kasper3** [comment]
Seems like fix is pending review from MSBuild team: https://github.com/NuGet/NuGet.Client/pull/1831.

**Comment by nkolev92** [comment]
This can be closed now as it will not bring us the initially expected expected benefit, due to the fact that restore evaluation is with ExcludeRestorePackageImports=true.

For OrchardCore:

/t:build /restore
Time Elapsed 00:00:57.75
Time Elapsed 00:00:58.31

/t:restore,build
Time Elapsed 00:00:57.81
Time Elapsed 00:00:58.82

**Comment by davkean** [comment]
Agreed. @nguerrera?
