### ISSUE TITLE
msbuild fails to build solution that starts with @

### ISSUE THREAD

**Issue by nnpcYvIVl** [microsoft/msbuild#2679]
msbuild fails when trying to build a sln file that starts with an @. Shouldn't the argument parser be able to understand that this is a sln file and not a response file?

Is there another parameter I can use to force this to build?

```
C:\Users\user\Desktop\@Test>"%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe" "@Test.sln"
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1022: Response file does not exist.
Switch: @Test.sln
```

**Comment by yaakov-h** [comment]
> Is there another parameter I can use to force this to build?

What happens if you put `@Test.sln` *inside* a response file? 😆

**Comment by nnpcYvIVl** [comment]
> What happens if you put @Test.sln inside a response file? 😆

Doesn't seem to work.

**Comment by rainersigwald** [comment]
Team triage: won't fix since this can be worked around by renaming the solution.
