### ISSUE TITLE
Reference Source doesn't have old MSBuild props/targets

### ISSUE THREAD

**Issue by Nirmal4G** [Microsoft/msbuild#2683]
I was looking into reference source at [Microsoft Reference Source](//referencesource.microsoft.com) and [Roslyn Source](//source.roslyn.io) to see the props/targets, to understand how they are written, while I was going through [MSBuild docs](//docs.microsoft.com/visualstudio/msbuild/).

When I found these lines, [Microsoft.Common.props(74)](https://referencesource.microsoft.com/#MSBuildFiles/C/ProgramFiles(x86)/MSBuild/14.0/Microsoft.Common.props,74) and [Same @ Roslyn Source](http://source.roslyn.io/#MSBuildFiles/C/ProgramFiles(x86)/MSBuild/14.0/Microsoft.Common.props,74)

```xml
<!-- If building using 4.X MSBuild, we want to act like this project is TV 4.0, so import
        Microsoft.Common.props from the 4.0 location, and make sure everything else in here is 
        set up such that if it's defaulted to something there, it won't be overridden here. -->
<Import Project="$(MSBuildExtensionsPath)\4.0\Microsoft.Common.props" Condition="'$(MSBuildAssemblyVersion)' == '' and Exists('$(MSBuildExtensionsPath)\4.0\Microsoft.Common.props')" />
```

I tried to click the 4.0 props file, It did not redirect, so I changed the URL from this:
`<domain>/#MSBuildFiles/C/ProgramFiles(x86)/MSBuild/`__`14.0`__`/Microsoft.Common.props`
to
`<domain>/#MSBuildFiles/C/ProgramFiles(x86)/MSBuild/`__`4.0`__`/Microsoft.Common.props`

I also tried 12.0, but no luck. I looked into this repo but it does not have 4.0 props.

So, Where can I find the 4.0 `Microsoft.Common.props` file and other props/targets that came with old MSBuild tools?

**Comment by KirillOsenkov** [comment]
http://referencesource.microsoft.com and http://source.roslyn.io do not support MSBuild 4.0.

You can maybe make one yourself using https://github.com/KirillOsenkov/SourceBrowser
You'll have to modify the project to use MSBuild 4.0, which might be tricky or even impossible. After that works, you'll just need to build and index any project that builds using MSBuild 4.0.

You can find the actual targets files for MSBuild 4.0 in your Windows directory:
C:\Windows\Microsoft.NET\Framework\v4.0.30319

As this is not an MSBuild issue I'm going to close this.

**Comment by Nirmal4G** [comment]
The target files are there, but what about the v4.0 `Microsoft.Common.props` file, I can't find it anywhere.

I checked in the repo and I can't find the file. Is there any 4.0 MSBuild redistributable containing this file, If so, where can I download them?

**Comment by KirillOsenkov** [comment]
I think you need to download the Build Tools 4.0, try this:
https://stackoverflow.com/questions/2567018/installing-msbuild-4-0-without-visual-studio-2010
https://www.microsoft.com/en-us/download/details.aspx?id=8279

**Comment by Nirmal4G** [comment]
Thanks.
