### ISSUE TITLE
Autoimport tries to import OS-generated "._Microsoft.Common.tasks" on mac

### ISSUE THREAD

**Issue by van800** [microsoft/msbuild#2691]
On MACOS ._Microsoft.Common.tasks file may be generated by OS itself.
More [info](https://stackoverflow.com/questions/10323580/what-are-all-these-hidden-prefixed-files-that-are-in-my-git-repo) about "dot underscore files".
[error.txt](https://github.com/Microsoft/msbuild/files/1437118/error.txt)

To reproduce:
Create  ._Microsoft.Common.tasks near  Microsoft.Common.tasks in "msbuild/15.0/bin"

**Comment by rainersigwald** [comment]
Team triage: closing due to age. If this is causing problems for you, please let us know and we can reactivate it.
