### ISSUE TITLE
Upgrade to .NET Core 2.0

### ISSUE THREAD

**Issue by AndyGerlicher** [Microsoft/msbuild#2706]
This is in no way a complete list, but I thought I would get started on it. @dsplaisted can you keep this up to date please? You can probably just edit this Issue.
- [x] Move `.csproj` to .NET Core SDK
- [x] Enable all tests (including deploying required dependencies) [2 days]
- [x] Enable "bootstrap" build for .NET Core, Full Framework [1 day]

### Full Framework specific
- [x] VS Insertion [.5 days]
  - [x] `/p:Platform='x86'` (VS insertion)
  - [x] `/p:Platform='amd64'` (VS insertion)
  - [x] Update `.swr` VSIX layout https://github.com/Microsoft/msbuild/blob/master/setup/files.swr
  - [x] What's the relationship between the different .vsix files produced, and why does `-pack` fail due to duplicates?
- [ ] MicroBuild: `/p:SignType=[Real/Test]`, otherwise Roslyn publicsign [0 days]
- [x] `EditBin` supported on x86 build: [0 days] https://github.com/Microsoft/msbuild/blob/e49204a31550c8a0a53a99013a23c765d02b4dfb/dir.targets#L168-L170
- [x] `MSBuildTaskHost.exe` targets .NET 3.5 [.5 days]
- [x] Package output for `MSBuild.Engine.Corext` and `VS.ExternalAPIs.MSBuild`
  - [x] Is MSBuild.Engine.Corext.nuspec in sync with files.swr?  It has some additional DLLs listed
  - [x] Is it OK to delete the NuGet targets from MsBuild.Engine.Corext now that VS 15.5 has shipped?

- [x] `/p:LocalizedBuild=true` sync `xlf` files to `resx` for building satellite assemblies [.5 days]
  - Ideally delete the `build/LocalizationTasks` folder and use repo toolset's functionality
  - [x] Do we still need English satellite assemblies?
  - [x] Do we need an equivalent to the `LocalizedTestBuild` functionality?
- [x] GitVersioning support* [.5 days]
_* Indicates nice to have building from .NET Core, required building from full framework_

### .Net Core on !Windows
- [x] Fix failing tests (#2884)

### Common
- [x] NuGet package output [.5 days]
- [x] Satellite assemblies packaged [.5 days]
- [x] Detect changed files after build

```batch
:: Only detect source control changes when running in the CI environment
:: Detect if there are any changed files which should fail the build
if DEFINED JENKINS_URL (
    echo Detecting changed files...
    git status
    git --no-pager diff HEAD --word-diff=plain --exit-code
    if ERRORLEVEL 1 (
        echo.
        echo [ERROR] After building, there are changed files.  Please build locally ^(cibuild.cmd --target All^) and include these changes in your pull request. 1>&2
        goto :error
    )
    goto :EOF
)
```

- [x] Linux / Mac build script support [.5 days]
- [ ] Mono support
- [ ] PublishToBlob.proj (orchestrated build)
- [x] LegacyPackages (probably no changes needed)
- [ ] MicrobuildTest.ps1
- [x] GenAPI / Reference assembly production [.5 days]
- [ ] PdbGit / SourceLink

```xml
  <!-- https://github.com/AArnott/PdbGit - stamps the .pdbs with URLs to sources on GitHub
       so that the debugger can download the exact matching source files during debugging -->
  <Import Project="$(PackagesDir)\pdbgit\3.0.41\build\PdbGit.targets" Condition="'$(DebugType)' == 'full' And '$(IsTestProject)' != 'true' And Exists('$(PackagesDir)\pdbgit\3.0.41\build\PdbGit.targets')" />

  <!-- https://github.com/ctaggart/SourceLink - stamps portable or embedded .pdbs with URLs to sources on GitHub
       so that debugger can download the exact matching source files during debugging -->
  <Import Project="$(PackagesDir)\sourcelink.create.commandline\2.1.2\build\SourceLink.Create.CommandLine.targets" Condition="'$(SourceLinkCreate)' == 'true' And '$(DebugType)' != 'full' And '$(IsTestProject)' != 'true' And Exists('$(PackagesDir)\sourcelink.create.commandline\2.1.2\build\SourceLink.Create.CommandLine.targets')" />
```
 - [x] Embed interop types for Microsoft.VisualStudio.Setup.Configuration.Interop

```xml
  <Target Name="LinkVSEmbeddableAssemblies" DependsOnTargets="ResolveReferences" AfterTargets="ResolveReferences">
    <ItemGroup>
      <ReferencePath Condition="'%(FileName)' == 'Microsoft.VisualStudio.Setup.Configuration.Interop'">
        <EmbedInteropTypes>true</EmbedInteropTypes>
      </ReferencePath>
    </ItemGroup>
  </Target>
```

- [ ] CI Setup
- [x] Do "Deprecated" projects need to be migrated?
- [x] Verify reference assembly changes are OK
- [ ] Verify correct version numbers for official builds (NuGet packages, assembly versions)
- [x] Produce XML API documentation, and include in NuGet packages
- [ ] cibuild.cmd fails if the repo path has spaces in it. (https://github.com/dotnet/roslyn-tools/issues/148)
- [ ] Update repo developer documentation

**Comment by dsplaisted** [comment]
As outlined in #2738, I've discovered that it's no longer going to be possible to create "portable" tasks that use a single DLL that works on both .NET Core and .NET Framework MSBuild after these changes.  I'm not sure how much of an issue that is.  It would still be possible to reference the older versions of the MSBuild libraries that target .NET Standard 1.3, you just wouldn't be able to use any newer MSBuild APIs.

**Comment by dsplaisted** [comment]
Work in progress for this is in the [exp/update-toolset](https://github.com/microsoft/msbuild/tree/exp/update-toolset) branch.

**Comment by dsplaisted** [comment]
To embed VS interop types, we can reference https://www.nuget.org/packages/Microsoft.VisualStudio.SDK.EmbedInteropTypes/

**Comment by filipnavara** [comment]
Please update the build documentation (https://github.com/Microsoft/msbuild/blob/master/README.md, https://github.com/Microsoft/msbuild/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild). I believe the information is not up-to-date now that cibuild.cmd was removed.

I'm still interested in how is the new system supposed to work for Mono builds. While I fully understand the work on that is not done yet I would appreciate at least a two sentence description of what is supposed to be the final state. Apparently, the `cibuild` script was replaced by `build/cibuild.sh`, but the `--host` and `--target` parameters are no longer valid. Am I supposed to just open MSBuild.sln and be able to build it in Visual Studio for Mac eventually?

**Comment by dsplaisted** [comment]
@filipnavara 

> I'm still interested in how is the new system supposed to work for Mono builds. While I fully understand the work on that is not done yet I would appreciate at least a two sentence description of what is supposed to be the final state. Apparently, the cibuild script was replaced by build/cibuild.sh, but the --host and --target parameters are no longer valid.

@radical is going to work on adding something similar to the new build scripts

> Am I supposed to just open MSBuild.sln and be able to build it in Visual Studio for Mac eventually?

You will probably have to run the build script first (this is what you have to do on Windows currently)

**Comment by dasMulli** [comment]
I was a bit confused by the `cibuild.sh` in the project root dir. I assume this is a leftover and `./build/build.sh` is to be used?

**Comment by dsplaisted** [comment]
@dasMulli Yes, that's left over.  For Windows, we have a build.cmd in the root which invokes the `build\build.ps1`.  We should probably do the same thing for the `.sh` script. @cdmihai

**Comment by kasper3** [comment]
>- [ ] MicroBuild: /p:SignType=[Real/Test], otherwise Roslyn publicsign [0 days]

Is this related to https://github.com/dotnet/roslyn/pull/23061? Now (starting with next, VS 15.6) roslyn supports strong named signing.

**Comment by rainersigwald** [comment]
I think all the scripts have been cleaned up, and this is definitely overall done. Closing--if you know of specific things that aren't already tracked in other issues, please open new issues.
