### ISSUE TITLE
Output artifacts from the previous build are removed when cleaning a UWP project

### ISSUE THREAD

**Issue by Thealexbarney** [microsoft/msbuild#2712]
### Steps to reproduce
Create a new UWP project.

Command line
```
msbuild /t:rebuild /p:AppxPackageDir=<output_directory_a>
msbuild /t:rebuild /p:AppxPackageDir=<output_directory_b>
```
### Expected  behavior
There will be two appx packages, one in directory 'a', and one in directory 'b'

### Actual behavior
When the project is built the second time, directory 'a' is deleted.

The `_CleanAppxPackage` target in `Microsoft.Build.AppxPackage.dll` reads the PackagingFileWrites log from the previous build, sees that the files in directory 'a' are listed in it, and removes them.

Let's say there's a UWP project that is built twice, but with a few changes made for the second build. If a build process builds a package with an output directory of `a`, modifies the project a little, and rebuilds the package with an output directory of `b`, only package `b` would exist at the end of the build, with little indication as to why package `a` was removed. Especially since doing the same thing with a console project does not clean the previous output path.

Building the second package without cleaning doesn't work either, because changes to the appxmanifest cause signtool to fail when signing the second package.

### Environment data
`msbuild /version` output:
15.4.8.50001

OS info:
Windows 10 15063.674

**Comment by rainersigwald** [comment]
Team triage: closing due to age. If you're still seeing this problem, please file Visual Studio feedback at https://developercommunity.visualstudio.com/ to route to the Appx packaging team.
