### ISSUE TITLE
[Question] CreateHardLinksForCopyLocalIfPossible and building inside Visual Studio

### ISSUE THREAD

**Issue by omariom** [Microsoft/msbuild#2717]
`CreateHardLinksForCopyLocalIfPossible` has the following definition in `Microsoft.Common.CurrentVersion.targets`:

```xml
<!-- By default we're not using Hard Links to copy to the output directory, and never when building in VS -->
<CreateHardLinksForCopyLocalIfPossible Condition="'$(BuildingInsideVisualStudio)' == 'true' or '$(CreateHardLinksForCopyLocalIfPossible)' == ''">false</CreateHardLinksForCopyLocalIfPossible>
```

Why is it a bad idea to use `CreateHardLinksForCopyLocalIfPossible`  when building in VS?

**Comment by danmosemsft** [comment]
I don't remember specifically but there likely was some circumstance where VS would take a lock on one file hardlinked to one the build is trying to modify or delete. 

If you modify that, you might find out.

**Comment by aolszowka** [comment]
While this is older there is similar discussion on #3788 cross linking to bubble that up.

**Comment by rainersigwald** [comment]
Duplicate of #3788
