### ISSUE TITLE
During batch property assignment, Condition and property function read stale values

### ISSUE THREAD

**Issue by geeeyetee** [Microsoft/msbuild#2719]
The following two targets attempt to set the value of the `Max` property to the highest value among the defined `Number` items.

- The first uses a `Condition` so that, while batching over the `Number` items, the `Max` property will never be set to a value lower than the value already assigned to it before or during the same batch operation. 
- The second uses a property function so that, while batching over the `Number` items, the `Max` property is always set to the greater of its current value and the value of the current batch iteration's `Number` item.

```
  <Target Name="PopulateMaxViaCondition">
    <ItemGroup>
      <Number Include="2" />
      <Number Include="1" />
    </ItemGroup>
    <PropertyGroup>
        <Max>0</Max>
        <Max Condition="%(Number.Identity) &gt; $(Max)">%(Number.Identity)</Max>
    </PropertyGroup>
    <Message Text="Max: $(Max)"/>
  </Target>
```

```
  <Target Name="PopulateMaxViaPropertyFunction">
    <ItemGroup>
      <Number Include="2" />
      <Number Include="1" />
    </ItemGroup>
    <PropertyGroup>
        <Max>0</Max>
        <Max>$([System.Math]::Max(`%(Number.Identity)`, `$(Max)`))</Max>
    </PropertyGroup>
    <Message Text="Max: $(Max)"/>
  </Target>
```

**Output, expected for target `PopulateMaxViaCondition`:**

> Added Item(s): Number=2
> Added Item(s): Number=1
> **Set Property: Max=0**
> **Set Property: Max=2**
>   **Max: 2** (TaskId:2)

**Output, expected for target `PopulateMaxViaPropertyFunction`:**

> Added Item(s): Number=2
> Added Item(s): Number=1
> **Set Property: Max=0**
> **Set Property: Max=2**
> **Set Property: Max=2**
>   **Max: 2** (TaskId:2)

**Output, actual for either target:**

> Added Item(s): Number=2
> Added Item(s): Number=1
> **Set Property: Max=0**
> **Set Property: Max=2**
> **Set Property: Max=1**
>   **Max: 1** (TaskId:2)

**Comment by geeeyetee** [comment]
Note that I originally posted this repro as a comment on another issue: https://github.com/Microsoft/msbuild/issues/2249#issuecomment-342578536

**Comment by geeeyetee** [comment]
@rainersigwald - I have verified that this unexpected behavior remains in MSBuild 15.8.168. This looks like a bug to me. What do you think?

**Comment by rainersigwald** [comment]
It's definitely confusing. It's "not a bug" because the implementation of `<PropertyGroup>` inside a target is just that passes the same item/property environment to each "parallel bucket" of work--in other words, each individual batched execution.

That's done intentionally:

https://github.com/Microsoft/msbuild/blob/6244c69aa4732353bbc0a2c9adfd2e5f79de5516/src/Build/BackEnd/Components/RequestBuilder/ItemBucket.cs#L90-L91

The reasoning here allows things like 

```xml
  <ItemGroup>
    <Thing Include="2" Color="blue" />
    <Thing Include="1" Color="red" />
  </ItemGroup>

  <Target Name="DemoParallelBatches">
    <ItemGroup>
      <Thing Condition=" '%(Color)' == 'blue' ">
        <Color>red</Color>
        <NeededColorChange>true</NeededColorChange>
      </Thing>
    </ItemGroup>
    <Message Importance="high"
             Text="Things: @(Thing->'%(Identity) is %(Color); needed change=%(NeededColorChange)')"/>
  </Target>
```

Without accidentally processing an item twice.

Given that, I don't think I'd want to try to fix this.

**Comment by geeeyetee** [comment]
Ah, I get it! I agree with you.

**Comment by gitfool** [comment]
I found this issue while searching for the equivalent of how to "set the value of the Max property to the highest value among the defined Number items" _from inside a target_. That particular question is not answered here so I'm left wondering if this possible, and if so how?
