### ISSUE TITLE
IntelliSense does not work at all while editing csproj with Windows and VS being Chinese.

### ISSUE THREAD

**Issue by davkean** [microsoft/msbuild#2723]
_From @Xiu-Li on November 16, 2017 1:48_

IntelliSense in editing .csproj does not work at all in windows 10 enterprise RTM Chinese-PRC x64.
![image](https://user-images.githubusercontent.com/24784908/32869656-1d45e488-cab3-11e7-92bc-ff6d513504d2.png)

_Copied from original issue: dotnet/project-system#2965_

**Comment by davkean** [comment]
On this issue, it appears that there's certain attributes (anything newer than MSBuild 4.0+) missing from intellisense too, here https://github.com/dotnet/project-system/issues/3234.

![image](https://user-images.githubusercontent.com/1103906/36452584-44a8ef02-16e9-11e8-9e7c-a1ab4fef30e3.png)

**Comment by couven92** [comment]
I have the same issue, I get no IntelliSense, but I am using a plain English system with a Western `nb-NO` keyboard layout.

**Comment by glenn-slayden** [comment]
Possibly related: DotNetAnalyzers/StyleCopAnalyzers#1711

**Comment by rainersigwald** [comment]
Internal setup authoring that controls this: https://dev.azure.com/devdiv/DevDiv/_git/VS?path=%2Fsrc%2FSetupPackages%2FCoreIde%2FCommunity%2Fres%2Ffiles.swr&version=GBmaster&line=203&lineEnd=210&lineStartColumn=1&lineEndColumn=1&lineStyle=plain

**Comment by davkean** [comment]
@Forgind Was this fixed?

**Comment by Forgind** [comment]
@davkean Yes, with https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/211888?_a=overview
