### ISSUE TITLE
_NTDRIVE and _NTROOT

### ISSUE THREAD

**Issue by jaredpar** [Microsoft/msbuild#2727]
There are numerous references in the code base to _NTDRIVE and _NTROOT. This is from our legacy razzle build system in Visual Studio.

At first I thought this was just hold over from that time and that we had shimmed the values in some way. But looking through the code I can't see anywhere we shim the values. Instead the values seem to be always unset and hence resulting in a lot of invalid imports in the code. Example:

``` xml
 <Import Project="$(_NTDRIVE)$(_NTROOT)\tools\Microsoft.DevDiv.Settings.targets"/>
```

Is this code just dead and hanging around for no reason? Or do we still build this code via razzle in some configuration?

**Comment by AndyGerlicher** [comment]
Dead code and should all be removed. Will wait till after the NET Core 2.0 upgrade work though to not make Daniel's life harder.
