### ISSUE TITLE
Can't build on OSX

### ISSUE THREAD

**Issue by dstrube1** [Microsoft/msbuild#2733]
### Steps to reproduce
Going by directions here:
https://github.com/Microsoft/msbuild/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild
I verified my Mac OSX (10.12.6) has OpenSSL (0.9.8zh), and Mono (5.4.1.6). I downloaded and unzipped msbuild-master.zip. In Terminal, I cd to Downloads/msbuild-master and run this command:
```
./cibuild.sh --target Mono
```

The result of the command is this:
```
ERROR: Could not restore build tools correctly. See '/Users/macserver/Downloads/msbuild-master/init-tools.log' for more details.1
Initializing BuildTools...
/Users/macserver/Downloads/msbuild-master/init-tools.sh: line 122: /Users/macserver/Downloads/msbuild-master/packages/Microsoft.DotNet.BuildTools/1.0.27-prerelease-00927-05/lib/init-tools.sh: No such file or directory
ERROR: An error occured when trying to initialize the tools. Please check '/Users/macserver/Downloads/msbuild-master/init-tools.log' for more details.1
```

Attached is the full log of the command as well as init-tools.log:
[init-tools.log](https://github.com/Microsoft/msbuild/files/1489191/init-tools.log)
[log1.txt](https://github.com/Microsoft/msbuild/files/1489192/log1.txt)

I've tried deleting the msbuild-master directory, then unzipping it again and copying init-tools.sh from `msbuild-master/packages/msbuild/` to `msbuild-master/packages/Microsoft.DotNet.BuildTools/1.0.27-prerelease-00927-05/lib/`, but that just led to a rabbit hole of other errors.

### Expected  behavior
```./cibuild.sh --target Mono``` succeeds.

### Actual behavior
```./cibuild.sh --target Mono``` fails.

### Environment data
OS info:
Mac OSX (10.12.6) has OpenSSL (0.9.8zh), and Mono (5.4.1.6)

**Comment by dstrube1** [comment]
Can someone weigh in this, please?

**Comment by filipnavara** [comment]
Are you by any chance running on macOS High Sierra?

The same error happens to me as well. Running the last failing command manually shows the following:

> /Users/filipnavara/Documents/msbuild/Tools/dotnetcli/dotnet restore "/Users/filipnavara/Documents/msbuild/Tools/1.0.27-prerelease-00927-05/project.json" --no-cache --packages /Users/filipnavara/Documents/msbuild/packages --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json --legacy-packages-directory
> log  : Restoring packages for /Users/filipnavara/Documents/msbuild/Tools/1.0.27-prerelease-00927-05/project.json...
> Segmentation fault: 11

The segmentation fault is further discussed at https://github.com/dotnet/core-setup/issues/2649. I don't have a definitive answer on how to fix or workaround the problem.

**Comment by rainersigwald** [comment]
@filipnavara That looks different since the OP reports being on 10.12.6, which should work.

Unfortunately, we can't update to the 10.13 fixed version(s) of the CLI at the moment because we need a specific, old CLI version that understands our (stale) `project.json` files. That will be addressed by #2868 (eventually).

**Comment by rainersigwald** [comment]
@dstrube1 It looks like our init-tools.sh doesn't correctly capture stderr of subcommands to its logging.

If you're still seeing this, what happens when you run the command that evidently failed in isolation?

```
/Users/macserver/Downloads/msbuild-master/Tools/dotnetcli/dotnet restore "/Users/macserver/Downloads/msbuild-master/Tools/1.0.27-prerelease-00927-05/project.json" --no-cache --packages /Users/macserver/Downloads/msbuild-master/packages --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json --legacy-packages-directory
```

**Comment by filipnavara** [comment]
I didn't notice that the version was included in the original report. Sorry, my fault. Nevertheless I still think it's a good idea to rerun the "dotnet restore" command from the log manually since the errors are not displayed in the log.

Thanks for linking to the pull request with the build tools update.

**Comment by rainersigwald** [comment]
Closing this since we've revamped the build process in #2868. Please open a new issue if you see problems with the new process.
