### ISSUE TITLE
Migrating tasks from old csproj to new csproj format

### ISSUE THREAD

**Issue by MNie** [Microsoft/msbuild#2746]
I'm currently in a process of migrating old csprojs to a new format. In some of them I have a msbuild task to replace app.config with app.debug/release.config (depending on build configuration).
In old csproj code to achieve that looks as follows:

```xml
<UsingTask TaskName="TransformXml" AssemblyFile="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\Web\Microsoft.Web.Publishing.Tasks.dll" />
  <Target Name="AfterCompile" Condition="Exists('App.$(Configuration).config')">
    <!--Generate transformed app config in the intermediate directory-->
    <TransformXml Source="App.config" Destination="$(IntermediateOutputPath)$(TargetFileName).config" Transform="App.$(Configuration).config" />
    <!--Force build process to use the transformed configuration file from now on.-->
    <ItemGroup>
      <AppConfigWithTargetPath Remove="App.config" />
      <AppConfigWithTargetPath Include="$(IntermediateOutputPath)$(TargetFileName).config">
        <TargetPath>$(TargetFileName).config</TargetPath>
      </AppConfigWithTargetPath>
    </ItemGroup>
  </Target>
```

Currently I have a piece of code like this which in fact doesn't work, but project compiles with it:

```xml
<UsingTask TaskName="TransformXml" AssemblyFile="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\Web\Microsoft.Web.Publishing.Tasks.dll" />
<Target Name="AfterCompile" AfterTargets="Build">
  <TransformXml Source="App.config" Destination="$(IntermediateOutputPath)$(TargetFileName).config" Transform="App.$(Configuration).config" />
  <ItemGroup>
    <AppConfigWithTargetPath Remove="App.config" />
    <AppConfigWithTargetPath Include="$(IntermediateOutputPath)$(TargetFileName).config">
      <TargetPath>$(TargetFileName).config</TargetPath>
    </AppConfigWithTargetPath>
  </ItemGroup>
</Target>
```

So the question is, is it supported in new csproj format? 
If yes, how I could port such task(s)?
If no, would it be supported in future?

OS info:
Visual studio 15.4.4

**Comment by rainersigwald** [comment]
@MNie How are you including this target in the project?

I suspect this is an issue where you're trying to override a target, but defining it _before_ the target you want to override. This has always been possible but is exacerbated by Sdk-style automatic import of `.targets` at the _very end_ of the file.

If that's the case, there are more details at https://github.com/Microsoft/msbuild/issues/1680, including other suggestions. I suggest going to a custom target name, maybe something like `ApplyConfigurationConfigFile`, with the appropriate `BeforeTargets` to hook it into the build process.

**Comment by MNie** [comment]
Hi @rainersigwald
I try to rename target and right now fragment of my csproj file which should replace config files looks like this:
```xml
<Import Project="$(MSBuildExtensionsPath)\Microsoft\VisualStudio\v15.0\Web\Microsoft.Web.Publishing.targets" />
<Message Text="Inside BeforeBuild" Importance="high" />
<UsingTask TaskName="TransformXml" AssemblyFile="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v15.0\Web\Microsoft.Web.Publishing.Tasks.dll" />
<Target Name="ApplyConfigurationConfigFile" BeforeTargets="Build">
  <ItemGroup>
    <AppConfigWithTargetPath Remove="App.config" />
    <AppConfigWithTargetPath Include="$(IntermediateOutputPath)$(TargetFileName).config">
      <TargetPath>$(TargetFileName).config</TargetPath>
    </AppConfigWithTargetPath>
  </ItemGroup>
  <Message Text="Inside BeforeBuild" Importance="high" />
  <TransformXml Source="App.config" Destination="$(IntermediateOutputPath)$(TargetFileName).config" Transform="App.$(Configuration).config" />
  <Message Text="Inside BeforeBuild" Importance="high" />
</Target>
```
In property group I add following element:
```xml
<BuildDependsOn>BeforeBuild</BuildDependsOn>
```
The result is that I see an information in output window:
![image](https://user-images.githubusercontent.com/7689103/34256140-2d6ad442-e654-11e7-8bf5-a1712d669fc6.png)

But task doesn't replace values in app.config file..

**Comment by rainersigwald** [comment]
@MNie `BeforeTargets="Build"` is probably too late (`Build` is actually, confusingly, one of the very _last_ targets to execute in most projects). Can you instead do `AfterTargets="PrepareForBuild"`? That is what [assigns `AppConfigWithTargetPath`](https://github.com/Microsoft/msbuild/blob/5213af78d17613417e5b715e7f83100dc1574ad6/src/Tasks/Microsoft.Common.CurrentVersion.targets#L1056-L1075), so it seems reasonable to me to tweak it immediately afterward.

> In property group I add following element:
> ```xml
><BuildDependsOn>BeforeBuild</BuildDependsOn>
> ```

This should [already be the case](https://github.com/Microsoft/msbuild/blob/5213af78d17613417e5b715e7f83100dc1574ad6/src/Tasks/Microsoft.Common.CurrentVersion.targets#L777-L778). May I ask why you did this?

**Comment by MNie** [comment]
@rainersigwald "May I ask why you did this?" I try everything to make it works :) Finally I remove this element cause it doesn't change nothign. It seems that my problem was an invalid attribute depending `when` the task should run. If I change to `AfterTargets="PrepareForBuild"` it works like a charm :). Thank you very much!

So finally to answer my own question, how to migrate msbuild task which previously looks like this:
```xml
<UsingTask TaskName="TransformXml" AssemblyFile="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\Web\Microsoft.Web.Publishing.Tasks.dll" />
<Target Name="AfterCompile" Condition="Exists('App.$(Configuration).config')">
  <!--Generate transformed app config in the intermediate directory-->
  <TransformXml Source="App.config" Destination="$(IntermediateOutputPath)$(TargetFileName).config" Transform="App.$(Configuration).config" />
  <!--Force build process to use the transformed configuration file from now on.-->
  <ItemGroup>
    <AppConfigWithTargetPath Remove="App.config" />
    <AppConfigWithTargetPath Include="$(IntermediateOutputPath)$(TargetFileName).config">
      <TargetPath>$(TargetFileName).config</TargetPath>
    </AppConfigWithTargetPath>
  </ItemGroup>
</Target>
```

You have to change `Target` to be suitable with new approach (in this situation **AfterTargets="PrepareForBuild"**) so the `new` part of csproj should looks like this:
```xml
<UsingTask TaskName="TransformXml" AssemblyFile="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\Web\Microsoft.Web.Publishing.Tasks.dll" />
<Target Name="ApplyConfigurationConfigFile" AfterTargets="PrepareForBuild">
  <ItemGroup>
    <AppConfigWithTargetPath Remove="App.config" />
    <AppConfigWithTargetPath Include="$(IntermediateOutputPath)$(TargetFileName).config">
      <TargetPath>$(TargetFileName).config</TargetPath>
    </AppConfigWithTargetPath>
  </ItemGroup>
  <TransformXml Source="App.config" Destination="$(IntermediateOutputPath)$(TargetFileName).config" Transform="App.$(Configuration).config" />
</Target>
```
@rainersigwald one more time many thanks for help, and wish you a Merry Christmas :)

**Comment by rainersigwald** [comment]
Glad that worked! One thing to note if you are doing the adoption gradually is that the new hooks should work fine with the old projects, too, so you can switch this independently of moving to Sdk-style imports.

**Comment by jjanuszkiewicz** [comment]
For anyone who stumbles upon this like I have: looks like the transform files are not taken into account by the `FastUpToDate` check (at least when they have Build Action = None, like they should). This causes a problem, because when the only file that is changed is e.g. `App.Debug.config`, the project is not rebuilt during subsequent builds.

This can be fixed by adding this to the csproj:

    <ItemGroup Condition="Exists('App.$(Configuration).config')">
      <CustomAdditionalCompileInputs Include="App.$(Configuration).config" />
    </ItemGroup>

Both this and the target from https://github.com/Microsoft/msbuild/issues/2746#issuecomment-353531239 can even be put in `Directory.Build.targets` and they automatically apply to all projects.

(thanks goes to https://github.com/dotnet/project-system/issues/4100#issuecomment-428899648 for inspiration)

**Comment by Taudris** [comment]
I was not able to get `CustomAdditionalCompileInputs` to work. `UpToDateCheckBuilt` works fantastically, however. I was also able to use the `TransformXml` task from `Microsoft.NET.Sdk.Publish` (just add it to your project's SDK list, then there is no need to use `UsingTask`).

    <Project Sdk="Microsoft.NET.Sdk.Worker;Microsoft.NET.Sdk.Publish">
      ...
    
      <Target Name="ApplyConfigurationConfigFile" AfterTargets="PrepareForBuild" Condition="Exists('App.$(Configuration).config')">
        <ItemGroup>
          <AppConfigWithTargetPath Remove="App.config" />
          <AppConfigWithTargetPath Include="$(IntermediateOutputPath)$(TargetFileName).config" TargetPath="$(TargetFileName).config" />
          <UpToDateCheckBuilt Include="$(IntermediateOutputPath)$(TargetFileName).config" Original="App.config" />
          <UpToDateCheckBuilt Include="$(IntermediateOutputPath)$(TargetFileName).config" Original="App.$(Configuration).config" />
        </ItemGroup>
        <TransformXml Source="App.config" Transform="App.$(Configuration).config" Destination="$(IntermediateOutputPath)$(TargetFileName).config" />
      </Target>
      
      <ItemGroup>
        <Content Remove="App.config" />
        <Content Remove="App.*.config" />
        <None Include="App.config" />
        <None Include="App.*.config" />
      </ItemGroup>
    
      ...
    </Project>

**Comment by 0xced** [comment]
A few years later, it's now even easier to perform App.config transforms thanks to the [Microsoft.VisualStudio.SlowCheetah](https://www.nuget.org/packages/Microsoft.VisualStudio.SlowCheetah/) NuGet package. Here's how to modify your csproj to enable transformations: add the `Microsoft.VisualStudio.SlowCheetah` pacakge and update your App.config original and configuration-specific files metadata with `TransformOnBuild` and repectively `IsTransformFile`.

```xml
<ItemGroup>
  <PackageReference Include="Microsoft.VisualStudio.SlowCheetah" Version="3.2.26" PrivateAssets="all" />
  <None Update="App.config">
    <TransformOnBuild>true</TransformOnBuild>
  </None>
  <None Update="App.*.config">
    <DependentUpon>App.config</DependentUpon>
    <IsTransformFile>true</IsTransformFile>
  </None>
</ItemGroup>
```

**Comment by OndrejValenta** [comment]
> A few years later, it's now even easier to perform App.config transforms thanks to the [Microsoft.VisualStudio.SlowCheetah](https://www.nuget.org/packages/Microsoft.VisualStudio.SlowCheetah/) NuGet package. Here's how to modify your csproj to enable transformations: add the `Microsoft.VisualStudio.SlowCheetah` pacakge and update your App.config original and configuration-specific files metadata with `TransformOnBuild` and repectively `IsTransformFile`.
> 
> ```
> <ItemGroup>
>   <PackageReference Include="Microsoft.VisualStudio.SlowCheetah" Version="3.2.26" PrivateAssets="all" />
>   <None Update="App.config">
>     <TransformOnBuild>true</TransformOnBuild>
>   </None>
>   <None Update="App.*.config">
>     <DependentUpon>App.config</DependentUpon>
>     <IsTransformFile>true</IsTransformFile>
>   </None>
> </ItemGroup>
> ```

Sweet Jesus Halelujah! There's so many packages out there one cannot possible know all the important ones and this package is definitely one of the most important of them all. 

Thank you very much!

Btw. the previous answers did not work for me because for some reason the transformation removed assemblyBinding nodes in 4.6.1 project and the application was confused what packages to load.

**Comment by timvdh** [comment]
> > A few years later, it's now even easier to perform App.config transforms thanks to the [Microsoft.VisualStudio.SlowCheetah](https://www.nuget.org/packages/Microsoft.VisualStudio.SlowCheetah/) NuGet package. Here's how to modify your csproj to enable transformations: add the `Microsoft.VisualStudio.SlowCheetah` pacakge and update your App.config original and configuration-specific files metadata with `TransformOnBuild` and repectively `IsTransformFile`.
> > ```
> > <ItemGroup>
> >   <PackageReference Include="Microsoft.VisualStudio.SlowCheetah" Version="3.2.26" PrivateAssets="all" />
> >   <None Update="App.config">
> >     <TransformOnBuild>true</TransformOnBuild>
> >   </None>
> >   <None Update="App.*.config">
> >     <DependentUpon>App.config</DependentUpon>
> >     <IsTransformFile>true</IsTransformFile>
> >   </None>
> > </ItemGroup>
> > ```
> 
> Sweet Jesus Halelujah! There's so many packages out there one cannot possible know all the important ones and this package is definitely one of the most important of them all.
> 
> Thank you very much!
> 
> Btw. the previous answers did not work for me because for some reason the transformation removed assemblyBinding nodes in 4.6.1 project and the application was confused what packages to load.

Also, even with VS 2022, I recommend installing the SlowCheetah extension, right click the app.config and "Add Transform". I believe it adds more accurate (per file) transformations to you project file.
