### ISSUE TITLE
dotnet pack doesn't include csproj summary into nupkg

### ISSUE THREAD

**Issue by tompostler** [Microsoft/msbuild#2766]
### Steps to reproduce

Project file:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net47</TargetFramework>
    <Description>
A longer description of this sample application that seems to just go on and on and on and on...

In fact, it's so long that dotnet pack is wanting us to create a summary even though one exists!

But just to make sure that we can trigger the build warning, here's a much longer third line that's basically repeating everything we've done so far yet again.
    </Description>
    <Summary>A short summary!</Summary>
  </PropertyGroup>

</Project>
```

Directory contents:
```
/
- a.cs
```

Command line
```
dotnet pack projectfile.csproj
```

### Expected  behavior
```
> dotnet pack projectfile.csproj

  projectfile -> E:\scratch\projectfile\bin\Debug\net47\projectfile.dll
  Successfully created package 'E:\scratch\projectfile\bin\Debug\projectfile.1.0.0.nupkg'.
```

And generated nuspec contains a `summary` tag with the summary.

### Actual behavior
```
> dotnet pack projectfile.csproj

  projectfile -> E:\scratch\projectfile\bin\Debug\net47\projectfile.dll
  Successfully created package 'E:\scratch\projectfile\bin\Debug\projectfile.1.0.0.nupkg'.
C:\Program Files\dotnet\sdk\2.0.3\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(204,5): warning : Issue found with package 'projectfile'. [E:\scratch\projectfile\projectfile.csproj]
C:\Program Files\dotnet\sdk\2.0.3\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(204,5): warning : Issue: Consider providing Summary text. [E:\scratch\projectfile\projectfile.csproj]
C:\Program Files\dotnet\sdk\2.0.3\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(204,5): warning : Description: The Description text is long but the Summary text is empty. This means the Description text will be truncated in the 'Manage NuGet Packages' dialog. [E:\scratch\projectfile\projectfile.csproj]
C:\Program Files\dotnet\sdk\2.0.3\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(204,5): warning : Solution: Provide a brief summary of the package in the Summary field. [E:\scratch\projectfile\projectfile.csproj]
```

And generated nuspec does not contain a `summary` tag with the summary. I also noticed that the tag is missing from `Microsoft.Build.CommonTypes.xsd`.

### Environment data

`msbuild /version` output:

    Microsoft (R) Build Engine version 15.4.8.50001 for .NET Framework
    Copyright (C) Microsoft Corporation. All rights reserved.

    15.4.8.50001

OS info from `systeminfo`:

    OS Name:      Microsoft Windows 10 Enterprise Insider Preview
    OS Version:   10.0.17035 N/A Build 17035

```
>dotnet --info
.NET Command Line Tools (2.0.3)

Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  12f0c7efcc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17035
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.3\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```

**Comment by jlahteen** [comment]
The Summary field is also missing from the project's Properties/Package view in Visual Studio 2017 (15.4.4), and build produces the same warnings as listed above.

**Comment by kkm000** [comment]
According to NuGet maintainers, Summary has been deprecated: https://github.com/NuGet/Home/issues/4587#issuecomment-288913324

Disable package analysis until/unless they fix the warnings: https://github.com/NuGet/Home/issues/4587#issuecomment-348734322

MSBuild just faithfully issues the warning it is asked to issue by their task, so it's not an MSBuild issue. But feel free to nag the NuGet team! :)

**Comment by tompostler** [comment]
Closing, as it is not an msbuild issue.

Thanks @kkm000 for digging in 😃

**Comment by kkm000** [comment]
@tompostler If you want me to volunteer as an issue steward for MSBuild, like filter issues that really require team attention, I am all for it. We all get bored by coding once in a while. Many are unclear or come from pilot errors, or just questions and not bugs, and there is 700+ of open tickets altogether--likely impossible to handle for the team as is. I'll need a permission to assign labels at the very least then, probably to create new labels and close issues too. Please ping me if you like the idea, or if you want to chat by e-mail first, the e-mail is in the profile.
