### ISSUE TITLE
upgraded to latest version

### ISSUE THREAD

**Issue by mmunchandersen** [microsoft/msbuild#2779]
I'm getting a msbuild related error after upgrading to visual studio 2017:

Invalid static method invocation syntax: "[MSBuild]::IsRunningFromVisualStudio()". Method '[MSBuild]::IsRunningFromVisualStudio' not found. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine('a', 'b'))

Please see this thread: https://github.com/Microsoft/msbuild/issues/2775

In the thread the proposed fix is to Upgrade to Microsoft.Build to v15.5.

How is msbuild upgraded to latest version?

**Comment by xen2** [comment]
Ran into the same issue. Had to switch from nuget.org to https://dotnet.myget.org/feed/msbuild/package/nuget/Microsoft.Build/15.5.179 and release an emergency upgrade for our product (Xenko).

However, I would like to understand how are we supposed to handle MSBuild dependencies if it is not "forward compatible" when reading newer Visual Studio targets?

* What should we assume in terms of upgrade, backward and forward compatibility for API and for Visual Studio MSBuild targets (that used new API in this case)?
* Is it bad practice to embed/copy MSBuild assemblies?
* Should we instead write an assembly resolver which would replicate some of the logic for locating the real MSBuild path?

**Comment by xen2** [comment]
Bump: Having the same forward-compat issues again: if our app is compiled against MSBuild 15.5.180, it can't load a project with latest VS. We have to upgrade it to MSBuild 15.6.82.

We get the following error: `Error: The "FindDependenciesOfExternallyResolvedReferences" parameter is not supported by the "ResolveAssemblyReference" task. Verify the parameter exists on the task, and it is a settable public instance property.`

We need guideline on how we are supposed to embed MSBuild to load/compile projects.

**Comment by rainersigwald** [comment]
@xen2 Can you take a look at https://github.com/rainersigwald/visualstudio-docs/blob/msbuild-api/docs/msbuild/updating-an-existing-application.md? I'd love any feedback you have about it before I push it to docs.microsoft.com

**Comment by xen2** [comment]
@rainersigwald Thanks, exactly what I was looking for!
(we were doing something similar manually, happy to switch to an official supported solution to solve this issue)

**Comment by xen2** [comment]
@rainersigwald Update: seems to work fine, doc was helpful!
