### ISSUE TITLE
Wrong ProjectVersion (and project structure) on VS 2017 + SSDT

### ISSUE THREAD

**Issue by robertoandrade** [Microsoft/msbuild#2797]
### Steps to reproduce

Created a new Reporting Services project in VS 2017 Community with SQL Server Data Tools but my project seems to be using some old format I'm not sure if it's an `msbuild` issue or an SSDT one.

Project file
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2000/10/XMLSchema" ToolsVersion="2.0">
  <DataSources />
  <Reports />
</Project>
```

Directory contents:
```
/
- Report Project.rptproj
```

### Expected  behavior

Regular project structure with projectVersion matching the environment's (ie: 15) like I've seen in other computers:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <FullPath>Debug</FullPath>
    <Platform>Win32</Platform>
    <OutputPath>bin\Debug</OutputPath>
    <ErrorLevel>2</ErrorLevel>
    <OverwriteDatasets>False</OverwriteDatasets>
    <OverwriteDataSources>False</OverwriteDataSources>
    <TargetServerVersion>SSRS2016</TargetServerVersion>
    <TargetReportFolder>Sample</TargetReportFolder>
    <TargetDatasetFolder>Datasets</TargetDatasetFolder>
    <TargetDatasourceFolder>Data Sources</TargetDatasourceFolder>
    <TargetReportPartFolder>Report Parts</TargetReportPartFolder>
    <TargetServerURL>http://localhost/reportserver</TargetServerURL>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'DebugLocal' ">
    ...
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    ...
  </PropertyGroup>
  <PropertyGroup>
    <State>...</State>
    <DataSources>@(DataSource)</DataSources>
    <DataSets>@(DataSet)</DataSets>
    <Reports>@(Report)</Reports>
  </PropertyGroup>
  <ItemGroup>
    <DataSource Include="XTP.rds" />
  </ItemGroup>
  <ItemGroup>
    <Report Include="Users.rdl" />
  </ItemGroup>
  <Import Project="$(MSBuildExtensionsPath)\Reporting Services\Microsoft.ReportingServices.MSBuilder.targets" />
</Project>
```

### Actual behavior

Project is crearted with old toolsVersion and I can't open projects with the "correct" toolsVersion.

### Environment data
`msbuild /version` output:

```
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

15.4.8.50001
```

OS info:

Windows 10 Enterprise

![image](https://user-images.githubusercontent.com/318969/33827894-1173d42e-de51-11e7-809f-55fc19b06c4c.png)

**Comment by rainersigwald** [comment]
This is a project format that actually predates MSBuild. The project is valid, just not buildable with MSBuild. The fact that it looks an awful lot like an MSBuild project was the root cause of #2064.

However, the SSDT team has recently released an update that _does_ use MSBuild: https://blogs.msdn.microsoft.com/sqlrsteamblog/2017/09/25/msbuild-support-for-reporting-services-projects-now-available/

You should be able to get the latest SSDT and use it to upgrade the project to an MSBuild format.

**Comment by jzabroski** [comment]
@rainersigwald  You should not have closed this.  The author posted an MSBuild-style rptproj config

**Comment by jzabroski** [comment]
Microsoft Visual Studio Professional 2017 
Version 15.6.4
VisualStudio.15.Release/15.6.4+27428.2015
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Professional

Visual F# Tools 10.1 for F# 4.1   00370-10200-04083-AA740
Microsoft Visual F# Tools 10.1 for F# 4.1

Application Insights Tools for Visual Studio Package   8.11.10212.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40314.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.51214.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.40215.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.3000.1
Microsoft Azure Data Lake Tools for Visual Studio

Azure Stream Analytics Tools for Visual Studio   2.3.3000.1
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   2.7.0-beta3-62715-05. Commit Hash: db02128e6e3c4bdfc93e6ec425ac9162b4d4fe80
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   15.6.18072.2
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

JetBrains ReSharper Ultimate 2017.3.3    Build 111.0.20180302.65130
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2018 JetBrains, Inc.

Microsoft Azure HDInsight Azure Node   2.3.3000.1
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.3000.1
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.3.3000.1
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.51212.2

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Open Command Line   2.1.179
Opens a command line at the root of the project. Support for all consoles such as CMD, PowerShell, Bash etc. Provides syntax highlighting, Intellisense and execution of .cmd and .bat files.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   15.6.18072.2
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Django support   15.6.18072.2
Provides templates and integration for the Django web framework.

Python - IronPython support   15.6.18072.2
Provides templates and integration for IronPython-based projects.

Python - Profiling support   15.6.18072.2
Profiling support for Python projects.

R Tools for Visual Studio   1.3.40104.1351
Provides project system, R Interactive window, plotting, and more for the R programming language.

SQL Server Data Tools   15.1.61801.210
Microsoft SQL Server Data Tools

SQL Server Reporting Services   14.0.1016.246
Microsoft SQL Server Reporting Services Designers 
Version 14.0.1016.246

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   15.6.20202.3
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.7.0-beta3-62715-05. Commit Hash: db02128e6e3c4bdfc93e6ec425ac9162b4d4fe80
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Universal Windows Apps   15.0.27428.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

**Comment by jzabroski** [comment]
I think this is a Visual Studio SSDT extension bug moreso than msbuild

**Comment by rainersigwald** [comment]
@jzabroski

> You should not have closed this. The author posted an MSBuild-style rptproj config

Can you clarify? The way I read it, the OP said that creating a new rptproj was producing the old-style project (with an example) rather than the new one (with an example).

Are you having a problem? Can you open a new issue with a description?

**Comment by jzabroski** [comment]
I'll drop it for now. I don't think this is the right project to file a bug with, anyway. I was just googling after encountering some similar oddities.

**Comment by jzabroski** [comment]
@rainersigwald  If you know the guys on the SSDT team, I would definitely appreciate you pushing them to fix this.  It's lame, and causes me problems managing a team of engineers adding new projects. It's definitely broken.

**Comment by rainersigwald** [comment]
@jzabroski Fix what, exactly? I don't understand what problem you're having.

**Comment by jzabroski** [comment]
The same problem reported by @robertoandrade : The rptproj generated by the current Business Intelligence rptproj template generates with ToolsVersion="2.0" and not ToolsVersion="15.0" and the SSDT 2017 MSBuild targets.

Steps to reproduce:
1. Install latest Visual Studio Professional 2017. Currently, this yields:
> Microsoft Visual Studio Professional 2017
> Version 15.6.4
> VisualStudio.15.Release/15.6.4+27428.2015
> Microsoft .NET Framework
> Version 4.7.02556
2.  Go to Extensions and Updates... > search Online in the Visual Studio Marketplace for "Microsoft Reporting Services Projects" > Version 1.21 > Click Install

**Comment by michaelmmcrae1** [comment]
I'm experiencing a similar issue to @jzabroski 
On VS 2015, with SSDT installed, when I create a new report project, it creates one with ToolsVersion="2.0" and the much older format. And VS 2015 cannot open/read more recent "up to date" project formats created by other developers with VS 2015.

@robertoandrade  or @jzabroski  did you ever find a way around this? Seems like my VS 2015 isn't honoring/using the installed SSDT, so it's using some old format.

**Comment by jzabroski** [comment]
Use VS2017, fix the ToolsVersion manually after installing the VSIX extension for SSRS.
