### ISSUE TITLE
Breaking Change in FileMatcher: ab*ba pattern matches aba by mistake

### ISSUE THREAD

**Issue by zhilich** [Microsoft/msbuild#2815]
Performance optimization #2392 led to a breaking change in FileMatcher logic. Please see suggested fix in my pull request #2814.

### Steps to reproduce

Let's examine the following project with a single web.config file in working directory:

```
<Project ToolsVersion="12.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" DefaultTarget="PublishFiles">
  <Target Name="PublishFiles">
    <ItemGroup>
      <DistributionFiles Include="**\*" Exclude="web.*.config">
      </DistributionFiles>
    </ItemGroup>
    <Message Text="@(DistributionFiles)" />
  </Target>
</Project>
```

### Expected  behavior
We should see web.config in the output

### Actual behavior
We don't see web.config in the output

**Comment by cdmihai** [comment]
Fixed in #2814
