### ISSUE TITLE
.NET Core 2.0 EXE is rebuilt every time in VS until project references are changed

### ISSUE THREAD

**Issue by loop-evgeny** [Microsoft/msbuild#2818]
### Steps to reproduce
[CoreBuildTest.zip](https://github.com/Microsoft/msbuild/files/1575617/CoreBuildTest.zip)

Open the solution in VS 2017. Make any change to Program.cs (e.g. add a space) and build the solution. Build the solution a second time.

### Expected  behavior

The second time all projects are considered up to date and not rebuilt. Build Output window shows

    ========== Build: 0 succeeded, 0 failed, 2 up-to-date, 0 skipped ==========

### Actual behavior

ConsoleApp1 is rebuilt every time:

    ========== Build: 1 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========

### Environment data
`msbuild /version` output:
```
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

15.5.180.51428
```

OS info: Visual Studio 15.5.2 on Windows 7 x64 SP1

### Note

If I either add or remove a project reference in ConsoleApp1 and build then the project is considered up-to-date from then on (further builds do not rebuild) until I modify a source file again.

**Comment by rainersigwald** [comment]
Looking at the logging of the subsequent build, it is incremental (the compiler doesn't run, for instance), indicating that this is a problem with the project system's fast up-to-date check. Moving to that repo.

**Comment by rainersigwald** [comment]
This issue was moved to dotnet/project-system#3070
