### ISSUE TITLE
Add GenerateDocumentationFile to the xsd

### ISSUE THREAD

**Issue by dasMulli** [Microsoft/msbuild#2828]
The property `DocumentationFile` is in the xsd but `GenerateDocumentationFile` is not, making it hard to discover. Since this is the property set by project.json>csproj migration, it should at least show up in IntelliSense.

**Comment by rainersigwald** [comment]
Manual sync was done by @AndyGerlicher in [an internal PR](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/100205). Should be available in the next preview release of VS 15.6.

**Comment by BradleyUffner** [comment]
This still isn't showing up in IntelliSense with VS 15.9.1
