### ISSUE TITLE
dotnet build resx error

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/msbuild#2838]
_From @tfsjohan on December 30, 2017_

When building a project from the command line on OSX using the dotnet build tools I get this error:

error MSB3103: Invalid Resx file. Length cannot be less than zero.

The resx files are not empty and they do work when building on Visual Studio 2017 on Windows. I can also build on Mac using Mono version of MSBuild without errors, but then the resources doesn't get build.

## Expected  behavior
Successful build and compiled resources.

## Actual behavior
Error MSB3103: Invalid Resx file.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.0)

Product Information:
Version: 2.0.0
Commit SHA-1 hash: cdcd192

Runtime Environment:
OS Name: Mac OS X
OS Version: 10.13
OS Platform: Darwin
RID: osx.10.12-x64
Base Path: /usr/local/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

Version : 2.0.4
Build : 7f262f453d8c8479b9af91d34c013b3aa05bc1ff

_Copied from original issue: https://github.com/dotnet/cli/issues/8307_

**Comment by rainersigwald** [comment]
@tfsjohan Would it be possible for you to share a `.resx` file that causes this, or create a minimal repro case?

**Comment by tfsjohan** [comment]
Sure. Here's one example, but the compiler gives me the same error for every resx file. 

[AccountController.resx.zip](https://github.com/Microsoft/msbuild/files/1601634/AccountController.resx.zip)

**Comment by tfsjohan** [comment]
Any updates on this? I still have the same issue with the latest 2.1.4 version of the dotnet sdk. Is there anything I can do in the resx files to avoid it?

**Comment by Kondamon** [comment]
The same issue here. I'm trying to build this repro: https://github.com/carstengehling/jirastopwatch and getting the same error message error MSB3103: Invalid Resx file.

/jirastopwatch-master/source/StopWatch/UI/MainForm.resx(5,5): Error MSB3103: Invalid Resx file. AND data length expected 512, read 0
Parameter name: stream Line 680, position 5. (MSB3103) (StopWatch)

**Comment by rainersigwald** [comment]
I would expect this to be fixed with `SDK 3.0.100-preview7` and `preview8`. If you see it again, please comment and we can reopen and track digging further into it.
