### ISSUE TITLE
Cannot build Release configuration problem with PDB git

### ISSUE THREAD

**Issue by mfilippov** [Microsoft/msbuild#2862]
I cannot build Release configuration. I got error:``` PdbGit.targets(9,5): error : Unable to detect the remote git service.```
[build.log](https://github.com/Microsoft/msbuild/files/1631216/build.log)

**Comment by rainersigwald** [comment]
@mfilippov Are you building from a .zip (or something) or an actual cloned git repo?

Does setting `PdbGitEnabled=false` as an environment variable get you past this error?

**Comment by mfilippov** [comment]
@rainersigwald Thank you for the workaround. It worked.

**Comment by mfilippov** [comment]
Could I fix original issue in my environment? Or is should just disable it over workaround?

**Comment by rainersigwald** [comment]
Unfortunately, I'm not sure what the actual problem is. It looks like GitLink is looking for the first remote in your git repo and finding that it doesn't match one of its built-in options. Is that the case?

https://github.com/AArnott/PdbGit/blob/72ca3ece1fee8258c1e2f5ef24dedde8e2f12bfe/src/PdbGit/Linker.cs#L81-L98

**Comment by mfilippov** [comment]
Thanks for the information I try to investigate this problem.

**Comment by mfilippov** [comment]
@rainersigwald I understand why you don't have this problem on CI. You running build with Debug configuration on CI server. And PdbGit has condition: ```<PdbGitEnabled Condition=" '$(DesignTimeBuild)' != 'true' and '$(Configuration)' == 'Release' and '$(PdbGitEnabled)' == '' ">true</PdbGitEnabled>``` I think you get this issue if you enable release build on CI.

**Comment by mfilippov** [comment]
Issue looks like fixed after move to new csproj.
