### ISSUE TITLE
SubType Designer is randomly added in csproj files

### ISSUE THREAD

**Issue by EnCey** [Microsoft/msbuild#2876]
### Steps to reproduce

Edit a `csproj` file and save it. A `Subtype` tag with `Designer` as content is randomly added.

```xml
<ItemGroup>
    <None Include="App.config">
        <SubType>Designer</SubType>
    </None>
    <None Include="packages.config">
        <SubType>Designer</SubType>
    </None>
</ItemGroup>
```

Here is a [Microsoft Connect issue](https://connect.microsoft.com/VisualStudio/feedback/details/783081/vs-needlessly-adds-subtype-designer-to-my-xml-documents) that describes this exact problem.

Here is a nearly a [decade old StackOverflow question](https://stackoverflow.com/questions/1573241/subtypedesigner-subtype-added-then-removed-by-visual-studio-on-load-unload) that describes this problem. According to an answer there, this issue has been present since Visual Studio 2008.

**Comment by KirillOsenkov** [comment]
P.S. Let's fix this, this has annoyed me for years.

**Comment by rainersigwald** [comment]
The only place I can see where we'd add this is in the pre-MSBuild-to-msbuild converter code, which should never be called:

https://github.com/Microsoft/msbuild/blob/419c6d8e55c9c8181da2ce8d0ef6f951fdfe08a3/src/Deprecated/Conversion/ProjectFileConverter.cs#L576-L578

I think this is a project system bug.

**Comment by rainersigwald** [comment]
This issue was moved to dotnet/project-system#3186
