### ISSUE TITLE
Removal of `v` from TargetFrameworkVersion is case sensitive

### ISSUE THREAD

**Issue by dsplaisted** [Microsoft/msbuild#2886]
There is a case-sensitive check to remove the `v` from the start of the `TargetFrameworkVersion` value here: https://github.com/Microsoft/msbuild/blob/91c86a746b312fce1aba31f8fb8540e949c11a01/src/Tasks/Microsoft.Common.CurrentVersion.targets#L1899

This should be case insensitive.  Similar logic in Microsoft.NET.Build.Extensions.targets is [causing projects to fail to evaluate](https://github.com/dotnet/sdk/issues/1884).  The incorrect check in MSBuild may not fail in the same way, but should still be fixed.

**Comment by rainersigwald** [comment]
I can fix this, I just introduced another instance of it.
