### ISSUE TITLE
Can't build MSBuild

### ISSUE THREAD

**Issue by cclauson** [Microsoft/msbuild#2889]
Sorry ahead of time if this is a noob question, and thanks to anyone who can help answer it!

### Steps to reproduce
*Download msbuild-master.zip from this github, unzip
*Open src/MSBuild.sln in Visual Studio 2017

### Expected  behavior
Projects are available in solution explorer to browse.

### Actual behavior
Microsoft.Build, Microsoft.Build.Framework, Microsoft.Build.Tasks, Microsoft.Build.Utilities, MSBuild and MSBuildTask host are all unavailable with (load failed).  If I try "Reload Project" I get an error such as:

C:\Users\Me\Downloads\msbuild-master2\msbuild-master\src\Build\Microsoft.Build.csproj : error  : The imported project "C:\Users\Me\Downloads\msbuild-master2\msbuild-master\packages\Nerdbank.GitVersioning\1.6.35\build\Nerdbank.GitVersioning.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\Me\Downloads\msbuild-master2\msbuild-master\src\dir.targets

When I look on my file sysem, the directory C:\Users\Me\Downloads\msbuild-master2\msbuild-master\packages doesn't exist.  If I run "Restore Nuget Packages" in Visual Studio on the top level solution, it reports a number of errors such as:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Framework' does not exist in the namespace 'Microsoft.Build' (are you missing an assembly reference?)	Microsoft.Build.Utilities.UnitTests	C:\Users\Me\Downloads\msbuild-master2\msbuild-master\src\Utilities.UnitTests\TrackedDependencies\TrackedDependenciesTests.cs	10	Active
Error	CS0234	The type or namespace name 'Framework' does not exist in the namespace 'Microsoft.Build' (are you missing an assembly reference?)	Microsoft.Build.Utilities.UnitTests	C:\Users\Me\Downloads\msbuild-master2\msbuild-master\src\Utilities.UnitTests\TrackedDependencies\TrackedDependenciesTests.cs	10	Active
Error	CS0234	The type or namespace name 'Tasks' does not exist in the namespace 'Microsoft.Build' (are you missing an assembly reference?)	Microsoft.Build.Utilities.UnitTests	C:\Users\Me\Downloads\msbuild-master2\msbuild-master\src\Utilities.UnitTests\TrackedDependencies\TrackedDependenciesTests.cs	12	Active
...

Again, sorry if this is an easy question, any advice is appreciated.

**Comment by cclauson** [comment]
I might have figured this out, looks like I need to first run:
.\cibuild.cmd --target Full --scope Compile --bootstrap-only

**Comment by rainersigwald** [comment]
That's correct for now; after #2868 lands this should be somewhat better/more intuitive.
