### ISSUE TITLE
MSBuild /help should link to docs

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/msbuild#2892]
Somewhere in the output of `msbuild /help` we should put a link to https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild.

(Thanks for the suggestion, @whoisj: https://github.com/Microsoft/msbuild/issues/2887#issuecomment-359844657.)

**Comment by joseotavioq** [comment]
Hi @rainersigwald!

Could it be something like this, when command `msbuild /help` is executed?

![image](https://user-images.githubusercontent.com/1444234/72208774-a282d780-3485-11ea-9e88-9bbcd87f42ee.png)
