### ISSUE TITLE
Master branch build is broken

### ISSUE THREAD

**Issue by chris1248** [Microsoft/msbuild#2909]
1. cloned the repo
2. Executed `cibuild` because that's what your docs said to do

### Expected  behavior
That it wouldn't freaking fail

### Actual behavior
```F:\msbuild\src\Shared\FileMatcher.cs(1468,35): error CS1528: Expected ; or = (cannot specify constructor arguments in declaration) [F:\msbuild\src\Utilities\Microsoft.Build.Utilit
ies.csproj]
F:\msbuild\src\Shared\FileMatcher.cs(1468,35): error CS1003: Syntax error, '[' expected [F:\msbuild\src\Utilities\Microsoft.Build.Utilities.csproj]
F:\msbuild\src\Shared\FileMatcher.cs(1468,93): error CS1003: Syntax error, '=>' expected [F:\msbuild\src\Utilities\Microsoft.Build.Utilities.csproj]
F:\msbuild\src\Shared\FileMatcher.cs(1491,14): error CS1003: Syntax error, ']' expected [F:\msbuild\src\Utilities\Microsoft.Build.Utilities.csproj]
F:\msbuild\src\Shared\FileMatcher.cs(1491,14): error CS1002: ; expected [F:\msbuild\src\Utilities\Microsoft.Build.Utilities.csproj]
F:\msbuild\src\Shared\FileMatcher.cs(1468,35): error CS1528: Expected ; or = (cannot specify constructor arguments in declaration) [F:\msbuild\src\Build\Microsoft.Build.csproj]
F:\msbuild\src\Shared\FileMatcher.cs(1468,35): error CS1003: Syntax error, '[' expected [F:\msbuild\src\Build\Microsoft.Build.csproj]
F:\msbuild\src\Shared\FileMatcher.cs(1468,93): error CS1003: Syntax error, '=>' expected [F:\msbuild\src\Build\Microsoft.Build.csproj]
F:\msbuild\src\Shared\FileMatcher.cs(1491,14): error CS1003: Syntax error, ']' expected [F:\msbuild\src\Build\Microsoft.Build.csproj]
F:\msbuild\src\Shared\FileMatcher.cs(1491,14): error CS1002: ; expected [F:\msbuild\src\Build\Microsoft.Build.csproj]
```
finally this:
```** Build completed. Exit code: 1

Bootstrap build failed with errorlevel 1

---------------------------------------
- cibuild.cmd FAILED. -
---------------------------------------
```

### Environment data
```F:\msbuild>msbuild -version
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.
```

OS info:

Running this from a vs 2015 developer command prompt, since none of the 2017 command prompts worked.

**Comment by rainersigwald** [comment]
I don't reproduce this on a clean clone and neither does our CI server. Can you share:

* The output of `git rev-parse HEAD`
* The contents of `F:\msbuild\src\Shared\FileMatcher.cs`
* The full build logs (should be `*.log` in the repo root; please include `init-tools.log`)
* Whether the behavior changes when you do `cibuild.cmd --target CoreCLR`

> Running this from a vs 2015 developer command prompt, 

Our repo requires VS 2017, as documented in the readme. I would not expect it to build using MSBuild 14. 

> since none of the 2017 command prompts worked.

What do you mean by this?

**Comment by chris1248** [comment]
I tried building from all the command prompts that vs 2017 gave me, and none of them worked.
These don't work:
![image](https://user-images.githubusercontent.com/2918666/35393090-2afea66c-01a1-11e8-9cf0-3dd9e73c1d55.png)

If you can't reproduce it, then there is a configuration problem that you have not documented, and that you don't see, since you have been working on it for so long. But for someone new to this repo, it's a blocker.

I'm at work now, so I'll try it on my work computer here and see if I can get it to work.

**Comment by rainersigwald** [comment]
We should be more clear about the correct command-prompt shortcut (it's the first one there). Added that to https://github.com/Microsoft/msbuild/pull/2910.

**Comment by chris1248** [comment]
Tried `cibuild.cmd --target Full --scope Compile --bootstrap-only` here at work, and it worked fine.
Using VS 2017 professional here. At  home where it failed was using VS 2017 community.

**Comment by rainersigwald** [comment]
We should work on Community, but it doesn't get exercised much by the core team since as Microsoft employees we don't have to pay for Enterprise.  When you get a chance, please share the stuff I asked for from your failing case; maybe there's a small fix we can make.

**Comment by chris1248** [comment]
`git rev-parse HEAD` => `419c6d8e55c9c8181da2ce8d0ef6f951fdfe08a3`
As for the contents of FileMatcher.cs, you can look it up according to where the HEAD was for the SSH I copied above.
[init-tools.log](https://github.com/Microsoft/msbuild/files/1691805/init-tools.log)

**Comment by chris1248** [comment]
This is water under the bridge now.
