### ISSUE TITLE
HighEntropyVA not set by default for 64-bit .net core apps

### ISSUE THREAD

**Issue by livarcocc** [Microsoft/msbuild#2912]
_From @michaelcfanning on November 15, 2017 0:41_

1. Create default .net core console app
2. Set configuration to x64, compile

result: high entropy va bit not set in PE.

Adding relevant MSBUILD property with correct value to the project resolves the issue. So the problem appears to be that our default property settings need to be corrected.

    <HighEntropyVA>true</HighEntropyVA>

_Copied from original issue: dotnet/sdk#1735_

**Comment by livarcocc** [comment]
I don't think we set this property anymore on the SDK itself.

This may be set by MSbuild itself actually.

**Comment by livarcocc** [comment]
Discussed this with @rainersigwald. Moving it to MSBuild.

**Comment by rainersigwald** [comment]
This is set in common targets:

https://github.com/Microsoft/msbuild/blob/6851538897f5d7b08024a6d8435bc44be5869e53/src/Tasks/Microsoft.NETFramework.CurrentVersion.props#L107-L113

That condition predates the `.NETCoreApp` and `.NETStandard` `TargetFrameworkIdentifier`s. We should make it true for netstandard or netcoreapp or {current check}.

**Comment by adkg** [comment]
Is this change available in new version ?

**Comment by rainersigwald** [comment]
The default behavior should be correct in .NET Core SDK 2.1.400 and higher (which carry MSBuild 15.8). Do you see otherwise @adkg?

**Comment by smmalis37** [comment]
I'm on Visual Studio 16.3.0 Preview 1.0, which seems to use MSBuild version 16.2.32702+c4012a063, and I'm not seeing this behavior by default. Using dumpbin /headers on compiled dlls does not show the HighEntropyVA capability getting set unless I add a `<HighEntropyVA>true</HighEntropyVA>` line to their csproj.

**Comment by hassan475** [comment]
I also fixed this issue by adding <HighEntropyVA>true</HighEntropyVA> property to .csproj file. Now can anyone tell me how to test this i.e. how to make sure that it is enable now ?

**Comment by michaelcfanning** [comment]
You can use the binary security checker BinSkim for this. If you put the tool into verbose mode, it will emit an explicit pass message for every rule (along with any failures). The relevant rule code is BA2015. Your command-line will be something like:

Binskim.exe analyze MyBinary.dll --verbose

https://www.nuget.org/packages/Microsoft.CodeAnalysis.BinSkim/

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
