### ISSUE TITLE
3rd party pdb files not copied to build output

### ISSUE THREAD

**Issue by ctaggart** [Microsoft/msbuild#2920]
### Expected  behavior

The 3rd party pdb files are copied to the build output for .NET Framework projects like they used to be before .NET Core project format. Is there a property I can set to get this? Is there a similar property to:

``` xml
<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
```

### Actual behavior

The 3rd party pdb file is not copied. In this case, there is a Newtonsoft.Json.pdb that should be copied, but is not.
![image](https://user-images.githubusercontent.com/80104/35466599-382f65fa-02d3-11e8-9391-43d5fe405711.png)

Using the same nupkg with the old format ends up copying the pdb file:
![image](https://user-images.githubusercontent.com/80104/35466792-2f87f596-02d5-11e8-986e-7f440025cafe.png)

In order to debug into source link enabled libraries, the pdb files need to be copied.

### Steps to reproduce

``` ps
git clone -b msbuild2920 https://github.com/ctaggart/sourcelink-test.git msbuild2920
cd msbuild2920
.\TryJson.sln
```

### Environment data

```
C:\Users\camer\cs\sourcelink-test [json ≡ +2 ~0 -0 !]> dotnet --info
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

**Comment by dasMulli** [comment]
Looks like a duplicate of https://github.com/dotnet/sdk/issues/1458
cc @nguerrera

**Comment by ctaggart** [comment]
It is a duplicate.
