### ISSUE TITLE
Adopt FallbackTargetFrameworks in GetReferenceNearestTargetFrameworkTask

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#2934]
After completion of https://github.com/NuGet/NuGet.Client/pull/1983, the call to that task in common.targets should support them through a project property.

cc @mishra14

**Comment by mishra14** [comment]
After talking with @emgarten @rainersigwald  @rrelyea, it seems that msbuild should be passing the `AssetTargetFallback` property as the fallback framework to the `GetReferenceNearestTargetFrameworkTask ` task.

**Comment by nguerrera** [comment]
Does this warn like package references do?

**Comment by nguerrera** [comment]
@rainersigwald @mishra14 I just tested this and I did not get a warning. .NET Core / .NET Standard projects have a default asset target fallback of net461. This was justified by the warning, but now the P2P subverts that.

**Comment by nguerrera** [comment]
cc @dsplaisted

**Comment by nguerrera** [comment]
https://github.com/NuGet/Home/issues/7137
