### ISSUE TITLE
Unable to create working msbuild.exe for C++

### ISSUE THREAD

**Issue by richt67** [Microsoft/msbuild#2945]
Hi,

Apologies if this noob question is in the wrong place but I couldn't find any other forum. Please let me know if there is a more suitable location for my query.

I've followed the instructions to build msbuild.exe using VS2017 (branch 15.7):

cibuild.cmd --target Full --scope Compile --bootstrap-only

I get can it to build C# projects, however I get the following error when building a C++ project:

error MSB4019: The imported project "~\bin\Bootstrap\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Default.props" was not found.

I'm running the version of msbuild in ~bin\Bootstrap\MSBuild\15.0\Bin\MSBuild.exe

I assume $(VCTargetsPath) is not being defined correctly, but the VS2017 version of msbuild works fine in the same environment.

Any help would be appreciated. BTW the documentation refers to cibuild.cmd (not present in the master branch) and BuildAndCopy.cmd (not present at all). 

Thanks

**Comment by rainersigwald** [comment]
The C++ targets and tasks are not open source, so they don't get built in our repo. Some of the more obscure C# tasks and targets are similar; we get them from the installed copy in BootStrapMSBuild:

https://github.com/Microsoft/msbuild/blob/52a12d7dc2409f91d7321eebfe91ce9a3357a776/build/BootStrapMSBuild.targets#L64-L66

The reason the VC tools work using installed MSBuild from the same environment as bootstrapped MSBuild is that this line

https://github.com/Microsoft/msbuild/blob/52a12d7dc2409f91d7321eebfe91ce9a3357a776/src/MSBuild/app.config#L104

Resolves correctly when using the MSBuild.exe in VS (which has a `VsInstallRoot`) but incorrectly in the just-built one (which doesn't).

Can you try setting the environment variable `VCTargetsPath` to the right value?

> BTW the documentation refers to cibuild.cmd (not present in the master branch) and BuildAndCopy.cmd (not present at all).

We just overhauled our own build yesterday (#2868) and some of the docs are a bit stale at the moment. Fixes welcome, though we'll probably get to them eventually. Specific pointers to things that are wrong would help.

**Comment by richt67** [comment]
Thanks for the quick response and explanation. Yes, setting VCTargetsPath works.
