### ISSUE TITLE
How to copy a folder to output directory and keep its root folder?

### ISSUE THREAD

**Issue by yhvicey** [Microsoft/msbuild#2949]
Came from https://github.com/dotnet/project-system/issues/3203

Following steps in @rainersigwald's post, files did have been copied to output folder, but the root folder ("config\" itself) can not be copy to output path. For example:
```
// Original
config
|--- config.json
|--- config.dev.json

// After build:
output
|--- config.json
|--- config.dev.json

// What I want:
output
|--- config
          |--- config.json
          |--- config.dev.json
```
 Is there any way to keep its root folder too?

Here's the code snippet:
```xml
<ItemGroup>
  <Folder Include="$(SolutionDir)config\" CopyToOutputDirectory="Always" />
</ItemGroup>
```

**Comment by dasMulli** [comment]
The 2.0 version of the .NET SDK (visual studio 15.4+, .NET CLI 2.0.0+) has a feature that can be used for this: the `LinkBase` metadata:

```xml
<ItemGroup>
  <None Include="$(SolutionDir)config\**" 
        CopyToOutputDirectory="PreserveNewest"
        LinkBase="config\" />
</ItemGroup>
```

**Comment by dasMulli** [comment]
Depending on which project type you have, the `None` items may already exist - e.g. for .net standard and .net core projects (non-web projects, web projects would use `Content` for `.json` files) and you could just update their `CopyToOutputDirectory` metadata:

```xml
<ItemGroup>
  <None Update="$(SolutionDir)config\**"  CopyToOutputDirectory="PreserveNewest"  />
</ItemGroup>
```

If you need to do this in non-.net standard/core projects (non-"SDK" projects), you can use the `Link` metadata:

```xml
  <ItemGroup>
    <Content Include="..\sql\**" CopyToPublishDirectory="PreserveNewest" Link="sql\%(RecursiveDir)\%(Filename)%(Extension)" />
  </ItemGroup>
```

e.g. see https://stackoverflow.com/questions/43569821/dotnet-core-publish-include-exclude-dir-in-output/43611163#43611163

**Comment by yhvicey** [comment]
It works. Thank you!

**Comment by ashishnegi** [comment]
@dasMulli How can specify the `target folder path` in the output directory ? Like final it should go in `abc/def` folder under output directory. This is for .net core projects.

**Comment by dasMulli** [comment]
@ashishnegi if you're using [this code](
https://github.com/Microsoft/msbuild/issues/2949#issuecomment-362823310), you can put the target folder into the `LinkBase` metadata attribute.

**Comment by ashishnegi** [comment]
I had to change `<None Update` to `<None Include` to make the copy work.

**Comment by dehghani-mehdi** [comment]
@dasMulli I have following structure:

```
MyProject.csproj
---Components
------A.dll
------B.dll
----------NestedDir
-------------X.dll
-------------Y.dll
```

How to remove the `Components` directory and put its content to output directory?
Using [this code](https://github.com/Microsoft/msbuild/issues/2949#issuecomment-362823310) copy `Components` folder into output directory.

**Comment by dasMulli** [comment]
Use the same code without `LinkBase` (or set it to `\`) and add

```xml
<PropertyGroup>
  <DefaultItemExcludes>$(DefaultItemsExclude);Components\**\*</DefaultItemExcludes>
</PropertyGroup>
```

So there won't be conflicting items with different copy metadata.

**Comment by dehghani-mehdi** [comment]
@dasMulli I got same result. I want to copy `Components`'s content into `Output`. I don't want to keep `Components` folder, just its content.

**Comment by CADbloke** [comment]
from https://stackoverflow.com/a/35065306/492 

``` xml
<ContentWithTargetPath Include="lib\some_file.dat">
  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  <TargetPath>some_file.dat</TargetPath>
</ContentWithTargetPath>
```

may be worth trying with wildcards. I haven't tried it with wildcards, works fine for just one file.

**Comment by SimonCropp** [comment]
this worked for me
```
    <ContentWithTargetPath 
       Include="$(MSBuildThisFileDirectory)..\Files\*.*"
       CopyToOutputDirectory="PreserveNewest"
       TargetPath="Files\%(Filename)%(Extension)" />
```

**Comment by MortInfinite** [comment]
Please note that using ContentWithTargetPath currently breaks incremental builds (As in, it will always build the project, even when nothing has changed). 

It seems to check the default target path for your file, instead of checking the specified TargetPath, and when the file isn't found at the default path, it concludes that the file is missing and the project must be built again.

**Comment by RobertAcksel** [comment]
> If you need to do this in non-.net standard/core projects (non-"SDK" projects), you can use the `Link` metadata:
> 
> ```
>   <ItemGroup>
>     <Content Include="..\sql\**" CopyToPublishDirectory="PreserveNewest" Link="sql\%(RecursiveDir)\%(Filename)%(Extension)" />
>   </ItemGroup>
> ```
> 
> e.g. see https://stackoverflow.com/questions/43569821/dotnet-core-publish-include-exclude-dir-in-output/43611163#43611163

It seems that this is not working in razor projects.

**Comment by KeithPoonNS** [comment]
thanks, the content include is work for me.

I want the puppeteer project to copy a folder to the build/debug directory

![image](https://user-images.githubusercontent.com/89375575/140450514-9f6554aa-75f2-4522-8e4c-7694b1ed14c4.png)

my startup project
```
  <ItemGroup>
    <None Update="ReportTemplate\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <!--<None Update="$(SolutionDir)PuppeteerReport\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>-->
    <Content Include="$(SolutionDir)PuppeteerReport\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Update="..\OfficeToPDF-1.9.0.2\OfficeToPDF.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
```

the puppeteer project
```
  <ItemGroup>
    <None Update="ReportTemplate\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <!--<None Update="$(SolutionDir)PuppeteerReport\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>-->
    <Content Include="$(SolutionDir)PuppeteerReport\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
```

**Comment by disouzam** [comment]
> The 2.0 version of the .NET SDK (visual studio 15.4+, .NET CLI 2.0.0+) has a feature that can be used for this: the `LinkBase` metadata:
> 
> ```
> <ItemGroup>
>   <None Include="$(SolutionDir)config\**" 
>         CopyToOutputDirectory="PreserveNewest"
>         LinkBase="config\" />
> </ItemGroup>
> ```

Saved my day! Thanks, @dasMulli !

**Comment by AmeerMansourWSP** [comment]
how to copy output including folders within it to different path ?
what i do is copying after build

` <Target Name="CopyFiles" AfterTargets="CoreBuild">
     <ItemGroup>
         <RootItem Include="$(ProjectDir)*.addin" />
         <AddinItem Include="$(TargetDir)*/*.*" />
     </ItemGroup>

     <PropertyGroup>
         <RootDir>bin\$(SharingType) $(RevitVersion) $(Configuration)\</RootDir>
         <AddinDir>$(RootDir)$(AssemblyName)\</AddinDir>
     </PropertyGroup>

     <Copy SourceFiles="@(RootItem)" DestinationFolder="$(RootDir)" />
     <Copy SourceFiles="@(AddinItem)" DestinationFolder="$(AddinDir)" />

     <ItemGroup>
         <AddinFiles Include="$(RootDir)**\*.*" />
     </ItemGroup>

     <Copy SourceFiles="@(AddinFiles)"
           DestinationFolder="$(AppData)\Autodesk\Revit\Addins\$(RevitVersion)\%(RecursiveDir)" />
 </Target>
 `
 so what happens  is my bin is like this

|-- file1.txt
|-- file2.txt
|-- subfolder1\
|   |-- subfolder2\
|   |   |-- file3.txt
|   |   |-- file4.txt
|-- subfolder2\
    |-- file5.txt

but after copying to my path, it copies all files but with no folders ! it will be like this 

|-- file1.txt
|-- file2.txt
|-- file3.txt
|-- file4.txt
 |-- file5.txt
