### ISSUE TITLE
msbuild and mono-devel file incompatability, cannot reinstall msbuild

### ISSUE THREAD

**Issue by martinellison** [Microsoft/msbuild#2958]
### Steps to reproduce
I had msbuild and  mono-devel installed and tried dnf upgrade. I could not upgrade so I erased msbuild and did the upgrade. Then omnisharp did not work so I tried to reinstall msbuild, and I got the following error:

  file /usr/lib/mono/xbuild/15.0/Microsoft.Common.targets/ImportAfter/Microsoft.NuGet.ImportAfter.targets from install of msbuild-1:15.4+xamarinxplat.2017.09.14.16.14-0.xamarin.4.epel7.noarch conflicts with file from package mono-devel-5.8.0.108-0.xamarin.2.epel7.x86_64

### Expected  behavior
msbuild should install

### Actual behavior
see above

### Environment data
`msbuild /version` output: (not installed)

OS info:
Linux xiaosan 4.14.14-200.fc26.x86_64 #1 SMP Fri Jan 19 13:27:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):

VSC
Version 1.19.3
Commit 7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba
Date 2018-01-25T10:32:23.601Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by martinellison** [comment]
I have installed nant now; does this mean that I do not need msbuild? Please advise.

Note: I was installing msbuild from the Centos repository. Previously this did not cause any issues.

**Comment by akoeplinger** [comment]
@directhex this looks like an RPM packaging issue for you :)

**Comment by akoeplinger** [comment]
We're already tracking this at https://github.com/mono/mono/issues/6757

**Comment by cdmihai** [comment]
@lifengl @dannyvv

**Comment by akoeplinger** [comment]
This was fixed on our end. @martinellison could you please confirm it works for you now and close the issue?

**Comment by martinellison** [comment]
I have re-installed msbuild, so confirmed fixed.
