### ISSUE TITLE
Fix API compatibility issues between .NET Core versions of MSBuild assemblies and full framework versions

### ISSUE THREAD

**Issue by dsplaisted** [Microsoft/msbuild#299]
Running ApiCompat (there's a batch file in the repo root) produces the following issues we should resolve:

Compat issues with assembly Microsoft.Build.Tasks.Core:
MembersMustExist : Member 'Microsoft.Build.Tasks.GetFrameworkPath.FrameworkVersion461Path.get()' does not exist in the implementation but it does exist in the contract.
Compat issues with assembly Microsoft.Build.Utilities.Core:
MembersMustExist : Member 'Microsoft.Build.Utilities.CommandLineBuilder.FixCommandLineSwitch(System.String)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'Microsoft.Build.Utilities.TargetDotNetFrameworkVersion Microsoft.Build.Utilities.TargetDotNetFrameworkVersion.Version461' does not exist in the implementation but it does exist in the contract.
EnumValuesMustMatch : Enum value 'Microsoft.Build.Utilities.TargetDotNetFrameworkVersion Microsoft.Build.Utilities.TargetDotNetFrameworkVersion.VersionLatest' is (System.Int32)7 in the implementation but (System.Int32)8 in the contract.
MembersMustExist : Member 'Microsoft.Build.Utilities.ToolLocationHelper.GetPathToDotNetFrameworkSdk()' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'Microsoft.Build.Utilities.ToolLocationHelper.GetPathToDotNetFrameworkSdkFile(System.String)' does not exist in the implementation but it does exist in the contract.

**Comment by cdmihai** [comment]
Here is an analysis of which branches these changes exist in, which commit introduced them, and possible ways to solve them:

Compat issues with assembly Microsoft.Build.Tasks.Core:
MembersMustExist : Member 'Microsoft.Build.Tasks.GetFrameworkPath.FrameworkVersion461Path.get()' does not exist in the implementation but it does exist in the contract.

--> master, xplat: Commit 9111eac2 : Adding support for Framework 4.6.1 SDK.

works if made internal

Compat issues with assembly Microsoft.Build.Utilities.Core:
MembersMustExist : Member 'Microsoft.Build.Utilities.CommandLineBuilder.FixCommandLineSwitch(System.String)' does not exist in the implementation but it does exist in the contract.

--> xplat: Commit 5063857b Adding crossplatform support

Breaks tests in CommandLineBuilder_tests if made internal

MembersMustExist : Member 'Microsoft.Build.Utilities.TargetDotNetFrameworkVersion Microsoft.Build.Utilities.TargetDotNetFrameworkVersion.Version461' does not exist in the implementation but it does exist in the contract.

--> xplat, master: Commit 9111eac2 : Adding support for Framework 4.6.1 SDK.

can be hidden via pp flag

EnumValuesMustMatch : Enum value 'Microsoft.Build.Utilities.TargetDotNetFrameworkVersion Microsoft.Build.Utilities.TargetDotNetFrameworkVersion.VersionLatest' is (System.Int32)7 in the implementation but (System.Int32)8 in the contract.

--> xplat, master: Commit 9111eac2 : Adding support for Framework 4.6.1 SDK.

can be hidden via pp flag

MembersMustExist : Member 'Microsoft.Build.Utilities.ToolLocationHelper.GetPathToDotNetFrameworkSdk()' does not exist in the implementation but it does exist in the contract.

--> xplat, master: Commit 9111eac2 : Adding support for Framework 4.6.1 SDK.

can be made internal

MembersMustExist : Member 'Microsoft.Build.Utilities.ToolLocationHelper.GetPathToDotNetFrameworkSdkFile(System.String)' does not exist in the implementation but it does exist in the contract.
Total Issues: 6

--> xplat, master: Commit 9111eac2 : Adding support for Framework 4.6.1 SDK.

can be made internal

**Comment by cdmihai** [comment]
After talking to @AndyGerlicher, the only one that needs fixing is FixCommandLineSwitch, by making it internal. The rest of the changes will go with update 1.
