### ISSUE TITLE
/cibuild.sh should be deleted

### ISSUE THREAD

**Issue by MasseGuillaume** [Microsoft/msbuild#3006]
/cc @cdmihai

I'm trying to build msbuild on linux (nixos). When I run `./cibuild.sh --target Mono` I get the following error:

```
init-tools.sh: No such file or directory
```
The following commit remove `init-tools.sh`
https://github.com/Microsoft/msbuild/commit/1b7d38d20eb036a292a08c827ec1ca9ae2f6def3

However, it's not clear from the commit message what happened `Remove obsolete init.sh`.

It's still used:
https://github.com/Microsoft/msbuild/blob/adf225bf6abf2c6ab41a3214f6806b7618878939/cibuild.sh#L319-L326
https://github.com/Microsoft/msbuild/blob/adf225bf6abf2c6ab41a3214f6806b7618878939/cibuild.sh#L17-L19

**Comment by kasper3** [comment]
TBH, inventing new conventions of build scripts is only causing confusion. Following (or at least trying to use) convention used by majority of dotnet repos like corefx, coreclr etc. will give sheer benefits.

Basic setup:

Windows: .\build.cmd release
Unix: ./build.sh release

Not sure why Roslyn and MSBuild teams chose the term `cibuild`. No harm in using different names, but there are more advantages in convergence for external contributors, engineering teams..

**Comment by mletterle** [comment]
I think the files under `/build` have replaced the functionality of `cibuild.sh` in the root, but it would be nice if there was a related issue for those commits to have been referenced against.

**Comment by rainersigwald** [comment]
This is lag from some recent changes to our build infrastructure, sorry.

`/cibuild.sh` should be deleted now; it's part of the pre-#2868 infrastructure and points to scripts that no longer exist.

We should also create a `/build.sh` that just calls `/build/build.sh`, as `/build.cmd` does.

For now, please call `/build/build.sh` (it has help for arguments).

**Comment by mletterle** [comment]
yes, but make sure you run `./build.sh -help` and not `./build.sh -h` otherwise it'll just start building ;)

**Comment by rainersigwald** [comment]
@mletterle snuck a fix for that into #3007

**Comment by kasper3** [comment]
Should the README for Windows and Wiki for Unix be updated accordingly? https://github.com/Microsoft/msbuild#building-msbuild-with-visual-studio-2017 and https://github.com/Microsoft/msbuild/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild.

Perhaps we can consolidate the building.md into source tree under `./documentation` directory, instead of having two separate places.

**Comment by rainersigwald** [comment]
@kasper3 Yes, they should, but I don't know if we'll be able to get to it quickly. I'd absolutely accept a PR that copied the current wiki page into `/documentation` and brought it up to date if someone wants to do that.
