### ISSUE TITLE
Microsoft.Web.Publishing.targets missing from install

### ISSUE THREAD

**Issue by Spongman** [Microsoft/msbuild#3011]
I'm trying to work out why the vs_buildtools.exe doesn't install all the tools necessary to build my projects. for example, i installed the following components:

![image](https://user-images.githubusercontent.com/1088194/36445055-e9f91684-1631-11e8-9b84-82e4ac87033d.png)

and i cannot find anywhere on my machine the `Microsoft.Web.Publishing.targets` file that is referenced in my project.

on the download page for this installer it says

> These Build Tools allow you to build native and managed MSBuild-based applications without requiring the Visual Studio IDE

but as it is it _doesn't_ allow me to do this.

do you really expect me to install the full VS on my build machine? if so, what is the point of `vs_BuildTools` in the first place? or do you expect me to copy files from my dev machine to my build machine (presumably breaking all kinds of licensing agreements) ? or is there some other installer that i should be running to get this support?

**Comment by dasMulli** [comment]
which workloads did you select?

**Comment by Spongman** [comment]
i chose 'web development build tools' and then i switched the sdk version to 4.7.1.

**Comment by paulsapps** [comment]
I've just stumbled upon this issue.. is it not in another component perhaps?

**Comment by rainersigwald** [comment]
There have been many improvements to Build Tools in the [15.7 preview 2](https://blogs.msdn.microsoft.com/visualstudio/2018/03/21/visual-studio-2017-version-15-7-preview-2/) release.

I see

```
C:\Program Files (x86)\Microsoft Visual Studio\Preview\BuildTools\MSBuild\Microsoft\VisualStudio\v15.0\Web\Microsoft.Web.Publishing.targets                     
```

On a machine where I have an internal 15.7 preview Build Tools installed with these options (`Web development build tools` and `.NET Core build tools` workloads)

![image](https://user-images.githubusercontent.com/3347530/37842611-92a676f2-2e90-11e8-9021-60881fd4fd16.png)

@paulsapps what workloads did you select, and what version of Build Tools did you install?

@Spongman my summary screen looks different from yours--specifically, I don't see a heading for `Web development build tools`. Can you double-check that that workload is selected?

**Comment by rainersigwald** [comment]
Closing since I think this is fixed. If you feel otherwise, please comment with the details I asked for in my previous post and we can reopen.

**Comment by paulsapps** [comment]
The vs_setup.exe version is 15.5.27130.2027

components are:

--add Microsoft.VisualStudio.Workload.MSBuildTools --add Microsoft.VisualStudio.Workload.NetCoreBuildTools --add Microsoft.VisualStudio.Component.VC.CoreBuildTools --add Microsoft.VisualStudio.Component.VC.Redist.14.Latest --add Microsoft.VisualStudio.Component.Windows10SDK --add Microsoft.VisualStudio.Component.Static.Analysis.Tools --add Microsoft.VisualStudio.Component.VC.CMake.Project --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.Windows10SDK.16299.Desktop --add Microsoft.VisualStudio.Component.Windows10SDK.16299.UWP --add Microsoft.VisualStudio.Component.Windows10SDK.16299.UWP.Native --add Microsoft.VisualStudio.ComponentGroup.WebToolsExtensions --add Microsoft.Component.VC.Runtime.UCRTSDK --add Microsoft.VisualStudio.Component.VC.ATL --add Microsoft.VisualStudio.Component.VC.ATLMFC --add Microsoft.VisualStudio.Component.VC.CLI.Support --add Microsoft.VisualStudio.Component.VC.Modules.x86.x64 --add Microsoft.Net.Component.4.6.1.SDK --add Microsoft.Net.Component.4.6.1.TargetingPack --add Microsoft.Net.Component.4.6.TargetingPack --add Microsoft.Net.ComponentGroup.DevelopmentPrerequisites --add Microsoft.VisualStudio.Wcf.BuildTools.ComponentGroup --add Microsoft.VisualStudio.Web.BuildTools.ComponentGroup --add Microsoft.Net.Core.Component.SDK --add Microsoft.VisualStudio.Component.NuGet.BuildTools --add Microsoft.Net.Component.3.5.DeveloperTools --add Microsoft.VisualStudio.Component.VC.Tools.14.11 --add Microsoft.Net.Component.4.5.TargetingPack --add Microsoft.Net.Component.4.5.1.TargetingPack --add Microsoft.Net.Component.4.5.2.TargetingPack
