### ISSUE TITLE
ToolLocationHelper.GetPathToReferenceAssemblies not thread safe

### ISSUE THREAD

**Issue by jairbubbles** [Microsoft/msbuild#3036]
*Sadly no clear repro on this one but I think a fix can be found by just looking at the code (which I did briefly).*

I'm evaluating in // many .csproj from a huge solution (hundreds of projects) to get their output path. Sometimes on some build machines I get:
```
The expression "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPathToStandardLibraries(.NETFramework, v4.6.1, '', AnyCPU)" cannot be evaluated. 
Collection was modified; enumeration operation may not execute. 
C:\Program Files (x86)\MSBuild\14.0\bin\amd64\Microsoft.Common.CurrentVersion.targets
```

I'm using Microsoft.Build@15.5.180 and my .sln is a VS2015 one.

When looking at the code:
https://github.com/Microsoft/msbuild/blob/75e5117ab8be40faad4601904600aceae6bf9ee1/src/Utilities/ToolLocationHelper.cs#L1779
There is some lock around some static variables but I guess some might be missing when iterating on the returned list. Maybe use ConcurrentDictionnary ?

**Comment by danmosemsft** [comment]
I noticed that in this location after publishing dotNetFrameworkReferenceAssemblies into s_cachedReferenceAssemblyPaths for other threads to see, the function goes on to modify its content:

https://github.com/Microsoft/msbuild/blob/75e5117ab8be40faad4601904600aceae6bf9ee1/src/Utilities/ToolLocationHelper.cs#L2226-L2242

I don't think that would cause the symptom above, but it is odd to share something via a cache and then continue to modify individual elements.

**Comment by jairbubbles** [comment]
I tried to reproduce my issue by writing simple code which evaluate in // many projects but nothing worked.

My last blind fix consisted to make all my .csproj in my solution to target .NET Framework 4.6.1 (3 of them were targetting older frameworks). But it didn't work and the crash reappeared on the build machines.

**Comment by AntonLapounov** [comment]
@danmosemsft I think you correctly identified the race condition.  Modifying the `dotNetFrameworkReferenceAssemblies` collection after publishing it bumps its version and breaks the `foreach` loop in the `GetPathToStandardLibraries` method.  To fix the issue, we need to move publishing after the `for` loop that modifies the collection.
