### ISSUE TITLE
Merge xplat branch to master

### ISSUE THREAD

**Issue by AndyGerlicher** [Microsoft/msbuild#305]
- [ ] 1. Document principles of each build flavor (differences in surface area, features, etc. for Full Framework, Mono, .NET Core)
- [x] 2. FI master->xplat (in-progress)
- [x] 3. Continuously FI after 2.
- [x] 4. Build Full Framework flavor in xplat CI
- [x] 5. Enable and fix FF & tests (all tests that currently pass in master)
- [x] 6. Audit the code diff
- [x] 8. Migrate / handle internal test collateral associated with MSBuild

Long term goal, assigning to distant future. This is something we want to do, but not something we have the time for right now. 

.NET Core features turned on/off based on configurations. OS specific behavior should be adjusted at runtime.

**Comment by rainersigwald** [comment]
This isn't quite complete--we're planning to keep the `master` branch around for a bit, just in case--but we shipped VS 2017 RC from xplat and expect future development to take place there. It would still be really great if we had a clear explanation of what worked in the different versions of MSBuild.

**Comment by kasper3** [comment]
Should https://github.com/Microsoft/msbuild/tree/xplat branch be deleted from the repo?
