### ISSUE TITLE
Visual Basic targets are not in UTF-8

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#306]
https://github.com/Microsoft/msbuild/blob/7eaf6cb744bdd48e8b88b952758e604e8d9ee638/src/XMakeTasks/Microsoft.VisualBasic.targets#L1

```xml
<?xml version="1.0" encoding="Windows-1252"?>
```

This caused test failures: 
```
System.Xml.XmlException : System does not support 'Windows-1252' encoding.
```

Which will be real failures as soon as we start building VB projects.

**Comment by cdmihai** [comment]
Fixed by #319
