### ISSUE TITLE
GenerateResource does not fail when converting binary .resx resources to .txt resources

### ISSUE THREAD

**Issue by cdmihai** [microsoft/msbuild#308]
On the full framework, if a .resx data element points to a path and there's a type specified to read that file, the conversion of the .resx resource to a .txt resource is impossible and the tasks logs an error (since .txt resources cannot have binary values).

However, the .net core behaviour is to write the file path to the .txt.

This happens because the full framework uses a special xml reader, ResXResourceReader , that reads a path in the .resx file directly to its specified .net object. However this special xml reader is not available in .net core, so a normal xml reader is used instead, which just reads the text file name.

Tests that capture failure:
- GenerateResource_Tests.UnsupportedTextType, InvalidReference, FailedResourceReader

Other implications
- .resx binary resources with specified .net types don't work.

@dsplaisted Should we copy the ResXResourceReader type to the msbuild codebase? If we try to mimic its behaviour, we end up re-implementing it.

**Comment by cdmihai** [comment]
I looked at all the FEATURE_RESX_RESOURCE_READER instances, and it modified the contract in the following manner:

__Read from .resx __ - allowed, but values are cast to string, not interpreted. Therefore binary resources referenced via a file are not loaded into their .net objects. Either the contract for resgen.exe and .resx format is different for .net core, or this is a bug
__Read from .resource__ - not allowed

__Write to .resx__ - not allowed
__Write to .resource__ - yes, but by coercing values to string

**Comment by rainersigwald** [comment]
This is fixable now that the ResX types are available in .NET Core 2, but MSBuild can't take advantage of that yet.
