### ISSUE TITLE
Test with programatic invoke of msbuild fails because wrong DLLs are resolved

### ISSUE THREAD

**Issue by cdmihai** [Microsoft/msbuild#309]
Some tests try to build a mock project as part of its state setup code. It does so by programmatically invoking `Project.Build()`
The build fails because its tasks bind to wrong DLLs in the `bin\Windows_NT\Debug-NetCore` directory.

Tests affected:
- `GenerateResource_Tests.ReferencedAssemblySpecifiedUsingRelativePath`, `DontLockP2PReferenceWhenResolvingSystemTypes`

**Comment by rainersigwald** [comment]
This no longer appears to be a problem, but the tests marked failing with it are failing for a different reason, which we're tracking as #4094.
