### ISSUE TITLE
Proposal - Write error to stderror

### ISSUE THREAD

**Issue by kasper3** [Microsoft/msbuild#3101]
Running `msbuild non-existing.sln > $null` in powershell should show the error.
Currently the error is written to stdout. Workarounds are there `/v:q /nolog` to get the errors out. However, the exit code of process should also reflect the truth.

**Comment by rainersigwald** [comment]
We discussed this a while ago at https://github.com/dotnet/cli/issues/4910 (in the context of the dotnet cli, but we should be consistent).

Until we have consensus on what tools in our ecosystem should do, I don't think we should change MSBuild, so I'm closing this in favor of that discussion. If we decide to adopt stderr, we can reopen this for the MSBuild work.

Also, if you only want errors, consider `/consoleloggerparameters:ErrorsOnly` (short: `/clp:ErrorsOnly`).

**Comment by kasper3** [comment]
Cool, thanks for the `clp` tip, it fixed my script! 😉
