### ISSUE TITLE
NullReferenceException in NodeProviderOutOfProc.ShutdownAllNodes()

### ISSUE THREAD

**Issue by jeffkl** [Microsoft/msbuild#3118]
While debugging something else in Visual Studio, I hit a NullReferenceException here:

https://github.com/Microsoft/msbuild/blob/6851538897f5d7b08024a6d8435bc44be5869e53/src/Build/BackEnd/Components/Communications/NodeProviderOutOfProc.cs#L178-L181

`ComponentHost.BuildParameters` was null so accessing the `EnableNodeReuse` property was throwing.  I'm not sure why its null as I didn't have time to look into at the time

**Comment by rainersigwald** [comment]
Duplicate of #1467
