### ISSUE TITLE
Is it ok to use undocumented GetLatestSDKTargetPlatformVersion in vcxproj?

### ISSUE THREAD

**Issue by ghost** [microsoft/msbuild#3155]
To be able to find available Windows 10 SDK target platform version, we can use:

```xml
<WindowsTargetPlatformVersion Condition="'$(WindowsTargetPlatformVersion)' == ''">$([Microsoft.Build.Utilities.ToolLocationHelper]::GetLatestSDKTargetPlatformVersion('Windows', '10.0'))</WindowsTargetPlatformVersion>
```

this is also to avoid hacky registry queries and hand-rolled code. However, this is not documented (yet). Is it ok for us to start relying on it?

Aside, with the aforementioned property in vcxproj, VS UI doesn't show the calculated value

![image](https://user-images.githubusercontent.com/33230602/38164504-68f77a66-350e-11e8-8469-6286afa3e713.png)

but MSBuild does and compilation from VS goes through as expected (without hardcoded version of Windows 10 SDK).

**Comment by 1vanK** [comment]
you can just write
```
<WindowsTargetPlatformVersion>10</WindowsTargetPlatformVersion>
```

**Comment by rainersigwald** [comment]
To answer the question though: yes, that's part of our public API surface and can be relied upon. That member isn't documented but the [property function docs](https://docs.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2019) do say

> In static property functions, you can use any static method or property of these system classes:
> * System.Byte
> ...
> * Microsoft.Build.Utilities.ToolLocationHelper
