### ISSUE TITLE
Document "magic" file names picked up by MSBuild: Directory.build.props, *.sln.targets, etc

### ISSUE THREAD

**Issue by KirillOsenkov** [Microsoft/msbuild#3166]
There should be documentation on all file names recognized by MSBuild that are auto-included if present on disk, but never explicitly mentioned.

Examples that I know of:
 * Directory.Build.props
 * Directory.Build.targets
 * <Solution>.sln.targets
 * Before.<Solution>.sln.targets (??)

**Comment by gfoidl** [comment]
`Directory.Build.[props|targets]` is documented in [Customize your build - Visual Studio | Microsoft Docs](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build)

On the same page the others could be documented as well.

**Comment by dasMulli** [comment]
E.g. Directory.Build.rsp which is new and no one really knows about..

**Comment by jaredpar** [comment]
File names and file locations. Guessing it's not well known that MSBuild will also import these files from user locations. This is all the known ways that we have found they are imported

https://github.com/dotnet/roslyn/blob/master/src/Workspaces/CoreTestUtilities/Resources/Directory.Build.props

**Comment by jaredpar** [comment]
There are target files you can apply to SLN files? What does that do?

**Comment by aL3891** [comment]
Those targets run once before/after all the projects in the solution, very useful but hidden feature.

**Comment by rainersigwald** [comment]
Feedback on MicrosoftDocs/visualstudio-docs#816 would be great: anything I missed? Got more questions about these mechanisms?

**Comment by jaredpar** [comment]
@rainersigwald overall looked good. Added some feedback.

One set of items I didn't see documented there was essentially all of the stuff listed in this file. 

https://github.com/dotnet/roslyn/blob/master/src/Workspaces/CoreTestUtilities/Resources/Directory.Build.props

I actually don't even know if these are valid extension points or if I'm disabling the properly. IIRC I essentially did a `/pp` on a build, looked for every `Import.*Before/After` and added a disable.

**Comment by aL3891** [comment]
Looks good, just added some nit comments

**Comment by rainersigwald** [comment]
docs PR closed. Thanks, folks--please continue to request documentation as you see the need for it!
