### ISSUE TITLE
Changing the TargetFrameworks list for a loaded project does not always has an effect

### ISSUE THREAD

**Issue by jeromelaban** [Microsoft/msbuild#3169]
In VS2017 15.7 Pre2, Win10 FCU:

* Create a Project A, with `<TargetFrameworks>netstandard2.0;net46</TargetFrameworks>`
* Create a Project B, with `<TargetFrameworks>netstandard2.0;net46</TargetFrameworks>`
* Make Project B reference project A
* Build once
* In the same VS instance, using the `Edit csproj` context menu
* Edit Project A, set `<TargetFrameworks>netstandard2.0</TargetFrameworks>`
* Save
* Edit Project B, set `<TargetFrameworks>netstandard2.0</TargetFrameworks>`
* Save
* Rebuild the solution

Sometimes, B won't compile because of a A does not target `net46`, a target that has just been removed.

Using these repro steps, you may also find that the `Edit csproj` context menu does not always open the file.

**Comment by rainersigwald** [comment]
This issue was moved to dotnet/project-system#3449
