### ISSUE TITLE
msbuild /t:pack does not include conditionally included pack content

### ISSUE THREAD

**Issue by jsmarcus** [Microsoft/msbuild#3173]
### Steps to reproduce

Packing a multi-targeted library with the conditionally included ItemGroup does not include the specified content files. If the condition is removed it includes the content but for all TFMs.

Project file
```xml
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">

  <PropertyGroup>
    <TargetFrameworks>netstandard1.3;netstandard2.0;Xamarin.iOS10;MonoAndroid80;uap10.0.16299</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <FontFiles Include="*.otf;*.ttf" />
  </ItemGroup>

  <ItemGroup Condition=" $(TargetFramework.StartsWith('Xamarin.iOS')) ">
    <BundleResource Include="@(FontFiles)" Pack="true" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MSBuild.Sdk.Extras" Version="1.3.0" PrivateAssets="All" />
  </ItemGroup>

  <Import Project="$(MSBuildSDKExtrasTargets)" Condition="Exists('$(MSBuildSDKExtrasTargets)')" />

</Project>
```

Directory contents:
```
/
- font.ttf
```

Command line
```
msbuild /t:pack
```
### Expected  behavior
font.ttf is included in the content and contentFiles portion of the nuspec/nupkg but only for the conditional target framework (in this case Xamarin.iOS10).

### Actual behavior
font.ttf is not included as content at all.

### Environment data
`msbuild /version` output:
Microsoft (R) Build Engine version 15.6.85.37198 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

15.6.85.37198

OS info:
Edition: Windows 10 Pro
Version: 1803
Build: 17133.1

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):
Visual Studio Professional 2017
Version 15.6.5

**Comment by rainersigwald** [comment]
Thanks for the report. I'm going to move this to the NuGet repo since that's where these targets come from.

**Comment by rainersigwald** [comment]
This issue was moved to NuGet/Home#6792
