### ISSUE TITLE
MSBuild 2015 can't find cvtres.exe

### ISSUE THREAD

**Issue by HarelM** [Microsoft/msbuild#3178]
### Steps to reproduce
Haven't tried to create a minimal reproduction but this is my setup:
1. Created a c++ project using visual studio 2010.
2. Created a C# project
3. Created a solution for both in VS 2015
4. Compiled it when VS 2010 and 2015 are installed using VS 2015 - should work.
5. Take the solution and place it on a windows server running TFS build agent when only VS 2010 and 2012 are installed and Build tools 2015 are installed.
6. Run MSBuild form installation folder on that solutoin.

### Expected  behavior
Build should succeed.

### Actual behavior
Build fails:
First it gave me an error since it didn't find `SDK40ToolsPath` so I configured it in the registry
Then it complained it doesn't know what `VCTargetsPath` is so I configured it in the registry too
Now it failed with the following error:
`LINK : fatal error LNK1158: cannot run 'cvtres.exe' `

I used procmon to try and find why and it seems like it doens't look in the right place.
Setting the path to `cvtres.exe` in the windows `PATH` variable seems to help but the build agent is running with a different user so it's not an ideal option.
Am I missing something?

### Environment data
`msbuild /version` output:
Microsoft (R) Build Engine version 14.0.23107.0
OS info:
Window server 6.2 build 9200

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):
command line

**Comment by AndreaLazz** [comment]
Have same problem with VS 2017, c++ DLL with resource (version info) and MSBuild.
It was functional in March, 2018, but now no more.
Perhaps a recent update of windows components (I'm investigating, probably Office 2003 or Skype for business) for security reason give problem to this functionality.
Steps to reproduce:

1) Create a Visual studio Project for a C++ DLL  (and related solution), for example dll1Prova
2) Add a resource file (file with ".rc" extension)  with version information
3) Save all files and compile. Compilation is good, and all seems functional
4) Then with MSBuild I try to build the solution with the following commands (from Command Prompt):

set VisualStudioVersion=15.0
set VCTargetsPath=C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets

"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\msbuild.exe" dll1Prova.sln /nologo /p:PlatformToolset=v141;Configuration=Debug /v:detailed

I obtain the following error at the end of the log:

"C:\Users\LazzaAnd\source\repos\Dll1Prova\dll1Prova.sln" (default target) (1) ->
"C:\Users\LazzaAnd\source\repos\Dll1Prova\Dll1Prova\Dll1Prova.vcxproj" (default target) (2) ->
(Link target) ->
  LINK : fatal error LNK1158: cannot run 'cvtres.exe' [C:\Users\LazzaAnd\source\repos\Dll1Prova\Dll1Prova\Dll1Prova.vcx
proj]

**Comment by HarelM** [comment]
The following is the workaround I eventually used to fix this for all users (a very bad one):
Copy and paste the file `vctres.exe` from:
`C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\`
to 
`C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\x86_amd64`

**Comment by AndreaLazz** [comment]
Path in VS 2017 are different.
I tried to do the same thing as you, that is copying cvtres.exe file from directory:

C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\SDK\ScopeCppSDK\VC\bin

to directories:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.13.26128\bin\Hostx86\x86
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.13.26128\bin\Hostx64\x64

but the problem still remains.
Even restoring cvtres.exe files from an old functional installation of VS 2017 is not functional.
Perhaps there's something changed in the build engine MSBuild or in libraries used by this engine.

**Comment by HarelM** [comment]
It depends on the C++ project. I used procmon to see where msbuild looks for the file and placed it where it looks.

**Comment by randomsock** [comment]
Thanks @AndreaLazz, running elevated fixed it for me too (VS 2015 Community Win32 DLL build)

**Comment by rainersigwald** [comment]
Note that just installing Build Tools is not supported for building C++ projects; you must install Visual C++ Build Tools 2015. More details are available in the [blog post](https://blogs.msdn.microsoft.com/vcblog/2016/03/31/announcing-the-official-release-of-the-visual-c-build-tools-2015/).

With Visual Studio 2017, the situation is simplified and you only need to select the C++ workloads in the Build Tools 2017 installer.

**Comment by rainersigwald** [comment]
Closing since this has been inactive and I think C++ Build Tools 2015 / Build Tools 2017 with the C++ workload should resolve the problem.
