### ISSUE TITLE
msbuild /pp output in section for PROCESSOR_ARCHITECTURE has incorrect comment

### ISSUE THREAD

**Issue by abatishchev** [Microsoft/msbuild#3186]
When I run `msbuild /pp:out.txt` I'm seeing the following section:

```xml
<!-- Msbuild runs as an x86 process.
If its running on a 64-bit machine, correctly set the PROCESS_ARCHITECTURE. -->
<PropertyGroup>
  <PROCESSOR_ARCHITECTURE Condition="'$(PROCESSOR_ARCHITECTURE)' == 'x86' and '$(PROCESSOR_ARCHITEW6432)' == 'AMD64'">AMD64</PROCESSOR_ARCHITECTURE>
</PropertyGroup>
```

Shouldn't it be

>set the PROCESSOR_ARCHITECTURE

rather than current

>set the PROCESS_ARCHITECTURE

?

**Comment by abatishchev** [comment]
Oh, I see. It comes from Environment.props which is a part of Microsoft internal MsBuild.Corext. Now I'm wondering how to report this issues to them. Do you know who are the owner of this package?

**Comment by rainersigwald** [comment]
Replied offline since it's MSFT-internal. Thanks for the report!
