### ISSUE TITLE
GetReferenceAssemblyPaths target should depend on GetFrameworkPaths

### ISSUE THREAD

**Issue by dsplaisted** [Microsoft/msbuild#3196]
See https://github.com/dotnet/sdk/issues/1730.  Normally `GetFrameworkPaths` will run before `GetReferenceAssemblyPaths`, but if you have a target that runs early and only depends on the latter, then `GetFrameworkPaths` may not run and you will get an error such as:

> C:\Program Files\dotnet\sdk\2.1.1-preview-007128\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.ConflictResolution.targets(58,5): error : Framework list file path 'v4.0.30319\RedistList\FrameworkList.xml' is not rooted. Only full paths are supported. [D:\Temp\repro_pack\repro_pack.csproj]

I've submitted a [PR](https://github.com/dotnet/sdk/pull/2145) to fix the target dependencies in the SDK, but it would be good for the target dependency to be updated in MSBuild itself.

**Comment by rainersigwald** [comment]
This kind of change has bitten us a shocking number of times in the past, so I think we need to do this in an early preview of a release to see if something has a terrible hidden dependency on this not being specified like this. But I agree that we should do it.
