### ISSUE TITLE
[Watson] Evaluation failures due to <TargetFrameworkProfile> containing only a new line & carriage return

### ISSUE THREAD

**Issue by davkean** [Microsoft/msbuild#3197]
### Steps to reproduce

Looking through project faults data in CPS projects, the vast majority of our project faults (on auto-reload) are due to the following construct. We have well over 1000 hits of this in the past month.

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <TargetFrameworkVersion>v4.6</TargetFrameworkVersion>
    <TargetFrameworkProfile>&#13;&#10;</TargetFrameworkProfile>
  </PropertyGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

Notice that profile contains the XML equivalent of `\r\n`

This results in the following evaluation failure:

```
The expression "[System.IO.Path]::Combine(D:\Temp\, .NETFramework,Version=v4.5,Profile=
 .AssemblyAttributes.cs)" cannot be evaluated. Illegal characters in path. C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets
```

I'm not sure what tool is causing projects to be in this form - but can we ignore TargetFrameworkProfile if it only contains whitespace?

Exception Message (click for more details) | Unique Users | Lifetime Exception Hits | First Seen | Last Seen
:---|---:|---:|---:|---:
The expression "[System.IO.Path]::Combine(C:\Users\[UserName]\AppData\Local\Temp\, .NETFramework,Version=v4.7.1,Profile=  .AssemblyAttributes.cs)" cannot be evaluated. Illegal characters in path. C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets | 11 | 150 | 03/08/2018 | 04/10/2018
The expression "[System.IO.Path]::Combine(C:\Users\[UserName]\AppData\Local\Temp\, .NETFramework,Version=v4.7.1,Profile=  .AssemblyAttributes.cs)" cannot be evaluated. Illegal characters in path. C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets | 10 | 193 | 03/08/2018 | 04/10/2018
The expression "[System.IO.Path]::Combine(C:\Users\[UserName]\AppData\Local\Temp\, .NETFramework,Version=v4.7.1,Profile=  .AssemblyAttributes.cs)" cannot be evaluated. Illegal characters in path. C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets | 8 | 184 | 03/08/2018 | 03/22/2018
The expression "[System.IO.Path]::Combine(C:\Users\[UserName]\AppData\Local\Temp\, .NETFramework,Version=v4.7.1,Profile=  .AssemblyAttributes.cs)" cannot be evaluated. Illegal characters in path. C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets | 8 | 141 | 03/08/2018 | 03/22/2018
The expression "[System.IO.Path]::Combine(C:\Users\[UserName]\AppData\Local\Temp\, .NETPortable,Version=v5.0,Profile=  .AssemblyAttributes.cs)" cannot be evaluated. Illegal characters in path. C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets | 7 | 64 | 03/26/2018 | 04/11/2018
The expression "[System.IO.Path]::Combine(C:\Users\[UserName]\AppData\Local\Temp\, .NETFramework,Version=v4.7.1,Profile=  .AssemblyAttributes.cs)" cannot be evaluated. Illegal characters in path. C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets | 7 | 16 | 03/13/2018 | 04/10/2018
The expression "[System.IO.Path]::Combine(C:\Users\[UserName]\AppData\Local\Temp\, .NETFramework,Version=v4.7.1,Profile=  .AssemblyAttributes.cs)" cannot be evaluated. Illegal characters in path. C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets | 6 | 110 | 03/06/2018 | 03/21/2018
The expression "[System.IO.Path]::Combine(C:\Users\[UserName]\AppData\Local\Temp\, .NETFramework,Version=v4.7.1,Profile=  .AssemblyAttributes.cs)" cannot be evaluated. Illegal characters in path. C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets | 6 | 103 | 03/06/2018 | 03/21/2018
The expression "[System.IO.Path]::Combine(C:\Users\[UserName]\AppData\Local\Temp\, .NETFramework,Version=v4.7.1,Profile=  .AssemblyAttributes.cs)" cannot be evaluated. Illegal characters in path. C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets | 6 | 11 | 03/13/2018 | 03/20/2018
The expression "[System.IO.Path]::Combine(C:\Users\[UserName]\AppData\Local\Temp\, .NETPortable,Version=v5.0,Profile=  .AssemblyAttributes.cs)" cannot be evaluated. Illegal characters in path. C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets | 5 | 36 | 03/28/2018 | 04/11/2018
The expression "[System.IO.Path]::Combine(C:\Users\[UserName]\AppData\Local\Temp\, .NETPortable,Version=v5.0,Profile=  .AssemblyAttributes.cs)" cannot be evaluated. Illegal characters in path. C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets | 5 | 9 | 03/26/2018 | 04/05/2018
The expression "[System.IO.Path]::Combine(C:\Users\[UserName]\AppData\Local\Temp\, .NETFramework,Version=v4.6.1,Profile=  .AssemblyAttributes.cs)" cannot be evaluated. Illegal characters in path. C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets | 4 | 55 | 03/07/2018 | 04/09/2018
The expression "[System.IO.Path]::Combine(C:\Users\[UserName]\AppData\Local\Temp\, .NETFramework,Version=v4.6.1,Profile=  .AssemblyAttributes.cs)" cannot be evaluated. Illegal characters in path. C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets | 4 | 44 | 03/07/2018 | 04/09/2018
The expression "[System.IO.Path]::Combine(C:\Users\[UserName]\AppData\Local\Temp\, .NETFramework,Version=v4.6.2,Profile=  .AssemblyAttributes.cs)" cannot be evaluated. Illegal characters in path. C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets | 4 | 4 | 03/29/2018 | 04/10/2018
The expression "[System.IO.Path]::Combine(D:\Temp\, .NETFramework,Version=v4.5,Profile=  .AssemblyAttributes.cs)" cannot be evaluated. Illegal characters in path. C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets | 3 | 70 | 03/23/2018 | 04/10/2018
The expression "[System.IO.Path]::Combine(D:\Temp\, .NETFramework,Version=v4.5,Profile=  .AssemblyAttributes.cs)" cannot be evaluated. Illegal characters in path. C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets | 3 | 51 | 03/23/2018 | 04/10/2018
The expression "[System.IO.Path]::Combine(C:\Users\[UserName]\AppData\Local\Temp\, .NETFramework,Version=v4.6.2,Profile=  .AssemblyAttributes.cs)" cannot be evaluated. Illegal characters in path. C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets | 3 | 43 | 03/15/2018 | 04/10/2018
The expression "[System.IO.Path]::Combine(C:\Users\[UserName]\AppData\Local\Temp\, .NETFramework,Version=v4.6.1,Profile=  .AssemblyAttributes.cs)" cannot be evaluated. Illegal characters in path. C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets | 3 | 35 | 03/27/2018 | 03/29/2018
The expression "[System.IO.Path]::Combine(C:\Users\[UserName]\AppData\Local\Temp\, .NETFramework,Version=v4.6.2,Profile=  .AssemblyAttributes.cs)" cannot be evaluated. Illegal characters in path. C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets | 3 | 34 | 03/15/2018 | 04/10/2018
The expression "[System.IO.Path]::Combine(C:\Users\[UserName]\AppData\Local\Temp\, .NETFramework,Version=v4.6.1,Profile=  .AssemblyAttributes.cs)" cannot be evaluated. Illegal characters in path. C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets | 3 | 30 | 03/13/2018 | 03/19/2018
The expression "[System.IO.Path]::Combine(C:\Users\[UserName]\AppData\Local\Temp\, .NETFramework,Version=v4.6.1,Profile=  .AssemblyAttributes.cs)" cannot be evaluated. Illegal characters in path. C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets | 3 | 25 | 03/27/2018 | 03/29/2018
The expression "[System.IO.Path]::Combine(C:\Users\[UserName]\AppData\Local\Temp\, .NETFramework,Version=v4.6.1,Profile=  .AssemblyAttributes.cs)" cannot be evaluated. Illegal characters in path. C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets | 3 | 11 | 03/13/2018 | 03/19/2018
The expression "[System.IO.Path]::Combine(C:\Users\[UserName]\AppData\Local\Temp\, .NETFramework,Version=v4.6.1,Profile=  .AssemblyAttributes.cs)" cannot be evaluated. Illegal characters in path. C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets | 3 | 7 | 03/09/2018 | 04/05/2018
The expression "[System.IO.Path]::Combine(C:\Users\[UserName]\AppData\Local\Temp\, .NETFramework,Version=v4.7.1,Profile=  .AssemblyAttributes.cs)" cannot be evaluated. Illegal characters in path. C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets | 3 | 4 | 03/13/2018 | 04/09/2018
The expression "[System.IO.Path]::Combine(C:\Users\[UserName]\AppData\Local\Temp\, .NETFramework,Version=v4.7.1,Profile=  .AssemblyAttributes.cs)" cannot be evaluated. Illegal characters in path. C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets | 2 | 69 | 03/06/2018 | 04/09/2018

**Comment by davkean** [comment]
Thing to note, weird if I copy the string from the original error message, it looks like it has only a carriage return \r:

`.NETFramework,Version=v4.6.1,Profile=\r.AssemblyAttributes.cs`

@nguerrera mentioned that this is old school Mac format, perhaps VS Mac is adding these?

**Comment by davkean** [comment]
Perhaps the real fix should be have the XML parser ignore \r like it does with \n\r?

**Comment by rainersigwald** [comment]
Based on very little, I suspect that this is a file that was created with and predominantly has `\n` line endings, but something edited it with a Windows-style `\r\n` in that new property. I think both System.Xml and the editor will treat this as a `\n` file with an oddball literal character.

But I can't repro this that way--I can only get it to happen with the XML entities in the file like your example. Is that what you're seeing, or is it just a stray newline-like character in the file? Or does telemetry not have enough information to tell?

**Comment by rainersigwald** [comment]
We could

**Comment by rainersigwald** [comment]
No, that is not what I meant to do, sorry.
