### ISSUE TITLE
Microsoft.CSharp.Core.Targets and Microsoft.VisualBasic.Core.Targets are not copied during build

### ISSUE THREAD

**Issue by cdmihai** [Microsoft/msbuild#320]
#296 stopped copying the compiler tools and the *.Core.Target files are not provided anymore.
This causes test `ProjectRootElement_Tests.ConcurrentProjectOpenAndCloseThroughProject` to fail because its test project cannot find Microsoft.CSharp.Core.Targets.

I committed a temporary workaround here: https://github.com/cdmihai/msbuild/commit/9df6b216560caae79e2d9fd41dfc938a674a3287
Should I send a PR with it?

@dsplaisted: Should those targets be brought in via some nuget package?

**Comment by cdmihai** [comment]
Applied the workaround in #321

**Comment by rainersigwald** [comment]
@cdmihai You didn't close this; is it fixed?

**Comment by cdmihai** [comment]
I did that workaround, but I do not know whether it is actually the correct fix, or whether those targets should be brought in via some nuget package in deploydependencies.
