### ISSUE TITLE
MSBuild includes project dependencies when called externally. 

### ISSUE THREAD

**Issue by lennoncork** [microsoft/msbuild#3200]
### Steps to reproduce

* Create a new solution with two projects (A and B)
* Make project A dependent on B (to enforce build order)
* Add a new text file to project B and set it to "Copy Always"
* Build from within visual studio and inspect the output 
* text file IS NOT present in the build output. 
* Build using MSBuild from the command line (C# Cake or TeamCity)
* text file IS present in the build output. 

### Expected  behavior
Calling MSBuild externally from Visual Studio should have the same behavior. The text file should not be copied to the output of the dependent project (it's not a reference). 

### Example
Attached is an example solution with C# Cake build script. 
[MSBuildError.zip](https://github.com/Microsoft/msbuild/files/1916333/MSBuildError.zip)

**Comment by lennoncork** [comment]
#2191

**Comment by lennoncork** [comment]
#2191

**Comment by cguedel** [comment]
Any update on this?

**Comment by rainersigwald** [comment]
You can configure this behavior by setting a property in the referencing project (or in all projects via [`Directory.Build.props`](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019#directorybuildprops-and-directorybuildtargets)):

```xml
<AddSyntheticProjectReferencesForSolutionDependencies>false</AddSyntheticProjectReferencesForSolutionDependencies>
```

**Comment by cguedel** [comment]
@rainersigwald Cool, that seems to work 👍

**Comment by rainersigwald** [comment]
I'm going to close this since the system is behaving as it appears to have been designed many years ago; I don't think we could change the default without breaking folks who depend on the current behavior (even if it's pretty strange behavior).
