### ISSUE TITLE
Need a performace and unified way to compare versions

### ISSUE THREAD

**Issue by wli3** [microsoft/msbuild#3212]
In msbuild condition. msbuild build will try to [parse it as dec or hex ]( https://github.com/Microsoft/msbuild/blob/e8b480c373eadd9daa975c6e96e4dbbabcd9a4fe/src/Build/Evaluation/Conditionals/NumericComparisonExpressionNode.cs#L44)first. So _2.11_ will be smaller than _2.2_.

```xml
<Project ToolsVersion="15.0" DefaultTargets="Try">
  <Target Name="Try">
   <Error Condition=" '2.11' &lt; 2.2 "
           Text='unexpected' />
  </Target>
</Project>
```

At the same time. If appending 0 at the end as in _2.2.0_, it will cause parse as number fail and consider it as Version. However, Version class's comparison does not consider _2.1_ and _2.1.0_ to be equal.[ In fact ](
https://msdn.microsoft.com/en-us/library/s3bf0xb2(v=vs.110).aspx)_2.1 < 2.1.0_. This will also occur in Property Function. 

```xml
<Project ToolsVersion="15.0" DefaultTargets="Try">
  <Target Name="Try">
   <Error Condition=" '2.1' &lt; 2.1.0 "
           Text='unexpected' />
  </Target>
</Project>
```

It is different behavior of [NuGet version](https://docs.microsoft.com/en-us/nuget/reference/package-versioning).

Also there is performance concern.

**Comment by wli3** [comment]
cc @dsplaisted @nguerrera @rainersigwald I hope we can discuss it on next Monday's sync meeting

**Comment by rainersigwald** [comment]
What's the performance concern? Something you've measured, or just theoretical?

**Comment by wli3** [comment]
@nguerrera do you have concrete example?

**Comment by nguerrera** [comment]
Try 
```
$([System.Version]::Parse("2.1").CompareTo($([System.Version]::Parse("2.1.0")))) < 0

**Comment by nguerrera** [comment]
I think we first have to normalize to four parts.

**Comment by nguerrera** [comment]
Somewhat separate, but we would also like there to be a way to compare semantic/nuget versions. We set $(NETCoreSdkVersion) currently based on that and we would like customers to be able to reason about it with minimum versions. Currently, Roslyn has code that is enforcing it as an exact version, and I'd like to get them to change it to a min version, but it occurs to me that I don't know how to write that.

**Comment by rainersigwald** [comment]
Can we get NuGet's `SemanticVersion` put into `System`? I don't want to add another dependency or reimplement semver in MSBuild :(

**Comment by rainersigwald** [comment]
Ah, already proposed: dotnet/corefx#13526.

**Comment by cdmihai** [comment]
If we had System.SemanticVersion, would we want to hardcode it in, as general enough? Or provide a way in which different package managers could plugin their own version comparers? I think there's little chance of having other package managers with tight msbuild integration right? :)

**Comment by rainersigwald** [comment]
I'd say we expose the ".NET Framework way". That's what we've done historically with `System.Version` but it doesn't behave according to modern expectations (witness `2.1` vs `2.1.0`). If we get `System.SemanticVersion`, that would just be a continuation. We'd probably have to add some syntax to invoke it directly since we can't hijack the existing direct-comparison syntax, since 4-part versions aren't allowed in semver.

**Comment by nguerrera** [comment]
Pragmatically, I'd want a single type / msbuild expression that supports 4 parts as an extension to semver. But I am not inclined to get into that debate. :(

**Comment by rainersigwald** [comment]
For 16.0, I propose

```
$([MSBuild]::CompareVersions($(left), $(right)))
```

That:

* `Version.Parse()`s each side
* Pads the resulting object with `.0` to reach 4 parts
* Returns `System.Version.CompareTo()` on the results.

Think this would be totally useless without support for prerelease semvers? Speak up, please!

**Comment by onovotny** [comment]
I think this would be helpful without the prerelease semvers, but adding prerelease semvers is helpful. Otherwise, we have to split, and if it's a property that might be, we always have to copy/test for it. Think .NET Core SDK version, which has prereleases and not.

**Comment by dsplaisted** [comment]
I think it would be helpful if `CompareVersions` would first drop the prerelease specifiers before parsing versions.  That way all prereleases of a given release are treated as equivalent in version to the RTM, but that may actually be a good thing.  It means you can't write logic testing if you are on a given prerelease or later, but it also means that you can test that the version is greater than or equal to the RTM version, and still have that logic work when that version is in prerelease.

**Comment by rainersigwald** [comment]
How about `CompareVersions(string left, string right, bool stripAfterHypen = false)`?

**Comment by nguerrera** [comment]
> But maybe it's sufficient to always do that, and doc the behavior.

I think I'd prefer that or something that will read better than a literal true in code review. CompareVersionsIgnoringPrerelease or something.

**Comment by nguerrera** [comment]
Do we also need to worry about versions with '+' and no '-', such as `15.8.166+gd4e8d81a88`

Could we get away with stripping after first non-digit-or-dot?

Also, can you allow leading v so that we can compare directly against TargetFrameworkVersion without our ugly _TargetFrameworkVersionWithoutV?

**Comment by dsplaisted** [comment]
> Also, can you allow leading v so that we can compare directly against TargetFrameworkVersion without our ugly _TargetFrameworkVersionWithoutV?

👍

**Comment by nguerrera** [comment]
Putting a note here that we will support $(_TargetFrameworkVersionWithoutV) outside the SDK. People use it already. But when we do a feature that compare against $(TargetFrameworkVersion) directly, we should encourage folks to do that.

**Comment by nguerrera** [comment]
(Putting that note here because I just approved a PR that uses it and points here.)

**Comment by rainersigwald** [comment]
@nguerrera ~was frustrated by this again~ volunteered to take a look at this.

**Comment by EdwardBlair** [comment]
>[All components of the version must be integers greater than or equal to 0. Metadata restricts the major, minor, build, and revision components for an assembly to a maximum value of UInt16.MaxValue - 1. If a component exceeds this value, a compilation error occurs.](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assemblyversionattribute?redirectedfrom=MSDN&view=netcore-3.1#remarks)

This implementation does not have such restrictions and can be used to compare, e.g. `AssemblyInformationalVersion`s.
