### ISSUE TITLE
Proposal: DownloadFile task

### ISSUE THREAD

**Issue by kasper3** [Microsoft/msbuild#3219]
Problem statement:

The mechanics require to accomplish:

* Download a file before build
* Include as Content, Compiler or None in the build / package

are quite cumbersome. Some folks accomplish this by downloading the content before invoking msbuild (isolated mode). Others use `<Exec>` and utilities like Invoke-WebRequest or curl-wget etc. Then there are people like me who are using [Roslyn]CodeTaskFactory and HttpClient in UsingTask to avoid the cross-platform disparities. But then reevaluation of package/compile targets makes it harder if you want to include the file in the build.

Part 1:

If we could get a decent download task that takes some basic parameters like URL, Destination, Credentials and use HttpClient behind the scenes from msbuild, that will mitigate the pain.

```xml
<DownloadFile
  TaskName="DownloadMySourceFile"
  Url="https://raw.githubusercontent.com/andreburto/FtpThing/d0e133c/FtpThing/RemoteFile.vb"
  Destination="$(MSBuildProjectDirectory)\SharedDTOs\RemoteFile.vb" />
```

Part 2 is moved to #3220

If you think it is common enough to be considered out of the box, please share your thoughts.

**Comment by rainersigwald** [comment]
Can you please split this into another bug for part 2? I think both parts could be useful independently.

Speaking for myself and not the team as a whole, I think `DownloadFile` makes a lot of sense. It's a common extension and we even use it in our own build.

**Comment by kasper3** [comment]
Done, part 2 moved to #3220. Thanks!

**Comment by rainersigwald** [comment]
@jeffkl This seems like just a straightforward task, but you seem to interpret it differently. What makes you think so?
