### ISSUE TITLE
Up to date checks check modification time of symlink, not its target

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#322]
This came up internally at Microsoft.  One of our teams makes heavy use of creating symlinks and using them in the build.  This causes problems when the symlink is newly created, but its target is old.  In that case, we unnecessarily choose to rebuild.

From that internal thread:
>You must examine the timestamp of the actual file, not the symlink file.  (For managed code, this means using File.GetLastWriteTime instead of FileInfo.GetLastWriteTime.  For native code, it means using GetFileTime instead of GetFileAttributesEx.)

[`IsUpToDate`](https://github.com/Microsoft/msbuild/blob/9c260bc40fd23ba68c7232462fa6880f4ebc4854/src/Utilities/TrackedDependencies/CanonicalTrackedInputFiles.cs#L499) does the check through `NativeMethods.GetLastWriteTimeUtc`, which does indeed [call](https://github.com/Microsoft/msbuild/blob/9c260bc40fd23ba68c7232462fa6880f4ebc4854/src/Utilities/TrackedDependencies/NativeMethods.cs#L32) `GetFileAttributesEx`.

**Comment by AndyGerlicher** [comment]
We should do this for Dev15 (not a future Update). Setting up for grabs. We will need to make sure this change is tested fully to ensure no regressions.

**Comment by rainersigwald** [comment]
Incremental build is handled in two ways in MSBuild:

* Normal `Target` based `Inputs`/`Outputs`: The aptly named [`TargetUpToDateChecker`](https://github.com/Microsoft/msbuild/blob/8b488bd508807f415193fe38d5084cd590931cfb/src/XMakeBuildEngine/BackEnd/Components/RequestBuilder/TargetUpToDateChecker.cs#L1236-L1295) handles this--it compares `FileInfo.LastWriteTime`, so it sees the symlink's time.

* Tracker-based incrementality: This is controlled by [`IsUpToDate`](https://github.com/Microsoft/msbuild/blob/9c260bc40fd23ba68c7232462fa6880f4ebc4854/src/Utilities/TrackedDependencies/CanonicalTrackedInputFiles.cs#L499), linked above. That calls out to the native method that gets the symlink's time.

A solution to this should affect both mechanisms (or maybe even _unify_ the mechanisms :astonished:). It should also introduce tests that validate the symlink behavior.

**Comment by rainersigwald** [comment]
It looks like `File.GetLastWriteTimeUtc` does *not* read through to the symlink target, so I'm going to have to try to `CreateFile`+`GetFileTime`, explicitly without `FILE_FLAG_OPEN_REPARSE_POINT`.

**Comment by rainersigwald** [comment]
After Target-level and FileTracker-style incrementality, the big remaining question for me is Copy with `SkipUnchangedFiles`.

I wasn't quite sure what the current behavior was, so I explored it a bit, using this simple `symlink_copy.proj`:

```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="b">
    <Copy SourceFiles="symlink.txt"
          DestinationFiles="destination.txt"
          SkipUnchangedFiles="$(copyIncremental)" />
  </Target>
</Project>
```

A copy through a symlink creates a (real) output file that matches the symlink's target timestamp:

```ShellSession
D:\play\symlink_copy>dir
 Volume in drive D is Data
 Volume Serial Number is DE97-EB96

 Directory of D:\play\symlink_copy

06/14/2016  10:05 AM    <DIR>          .
06/14/2016  10:05 AM    <DIR>          ..
06/14/2016  09:57 AM                13 real_source.txt
06/14/2016  10:01 AM    <SYMLINK>      symlink.txt [real_source.txt]
06/14/2016  09:40 AM               254 symlink_copy.proj
               3 File(s)            267 bytes
               2 Dir(s)  10,601,353,052,160 bytes free

D:\play\symlink_copy>msbuild symlink_copy.proj
Microsoft (R) Build Engine version 14.0.25123.0
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 6/14/2016 10:06:24 AM.
Project "D:\play\symlink_copy\symlink_copy.proj" on node 1 (default targets).
b:
  Copying file from "symlink.txt" to "destination.txt".
Done Building Project "D:\play\symlink_copy\symlink_copy.proj" (default targets).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.01

D:\play\symlink_copy>dir
 Volume in drive D is Data
 Volume Serial Number is DE97-EB96

 Directory of D:\play\symlink_copy

06/14/2016  10:06 AM    <DIR>          .
06/14/2016  10:06 AM    <DIR>          ..
06/14/2016  09:57 AM                13 destination.txt
06/14/2016  09:57 AM                13 real_source.txt
06/14/2016  10:01 AM    <SYMLINK>      symlink.txt [real_source.txt]
06/14/2016  09:40 AM               254 symlink_copy.proj
               4 File(s)            280 bytes
               2 Dir(s)  10,601,353,445,376 bytes free
```

(note `destination.txt` matches `real_source.txt` even though the project mentions only `symlink.txt`)

With incremental, the source (symlink) is newer than the destination, so the copy happens again:
```ShellSession
D:\play\symlink_copy>msbuild symlink_copy.proj /p:copyIncremental=true
Microsoft (R) Build Engine version 14.0.25123.0
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 6/14/2016 10:11:14 AM.
Project "D:\play\symlink_copy\symlink_copy.proj" on node 1 (default targets).
b:
  Copying file from "symlink.txt" to "destination.txt".
Done Building Project "D:\play\symlink_copy\symlink_copy.proj" (default targets).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.03
```

That is suboptimal, but potentially nonfatal since it won't cause a rebuild cascade--the "new" output file has the same timestamp as the one from the previous run.

**Comment by rainersigwald** [comment]
(Partial) inventory of other places that call suspicious APIs:

* `Shared\FileUtilities.cs` has a few calls to `GetFileAttributesEx` but doesn't look at date fields
* `NativeMethodsShared.GetLastWriteDirectoryUtcTime` calls `GetFileAttributesEx` but only on a directory.
* Many tests, which should be fine since they don't operate on symlinks.
* The `Touch` task sets metadata using `File.SetLastWriteTime` but that's OK because it _should_ operate on the symlink.
* RAR has a `GetLastWriteTime` delegate, but it's [correctly set](https://github.com/Microsoft/msbuild/blob/651b523f28ac351b96b9d89c50e41c6403e99c52/src/XMakeTasks/AssemblyDependency/ResolveAssemblyReference.cs#L2903-L2903) to use the (now patched) `NativeMethodsShared.GetLastWriteFileUtcTime`.
* The scheduler uses a `FileInfo` to [sort by size](https://github.com/Microsoft/msbuild/blob/651b523f28ac351b96b9d89c50e41c6403e99c52/src/XMakeBuildEngine/BackEnd/Components/Scheduler/Scheduler.cs#L969-L968) as a rough approximation of complexity, but if it's wrong no big deal.
* `GenerateResources` uses a lot of `FileInfo` manipulations.

The last one is the only one I'm worried about.

**Comment by rainersigwald** [comment]
Filed #703 to track possible future fixups in `Copy`.
