### ISSUE TITLE
Publish 15.7 RTM NuGet packages

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#3228]
We need to publish final release 15.7 packages. Since those bits will ship in both .NET Core SDK 2.1.300 and Visual Studio 2017 Update 7, which may ship at different times, this will be somewhat complicated.

The plan is:

- [x] Accept #3222 to drop the prerelease tag from our output version.
- [ ] Insert the output of that build to VS but **do not** publish packages.
- [ ] Msbuild stays in prodcon until the end, but fixes an unchanging branch (the final hash inserted into VS)
- [ ] Wait until 2.1 final shipping bits are produced in prodcon (producing MSBuild packages with the correct version reference)
- [ ] Publish the NuGet packages that came out of prodcon and point to RTM .NET Core package versions.
- [ ] Immediately check in a change to our `vs15.7` branch that freezes our `$(MicrosoftNETCoreAppVersion)` to the RTM version.
- [ ] Update CLI's reference to MSBuild to point to the release packages.
- [ ] Disconnect CLI's uptake dependency on MSBuild in prodcon so it depends on the checked-in package version.

**Comment by AndyGerlicher** [comment]
@mmitche FYI. Looks like we can't produce a package outside of prodcon that has the correct dependencies. This is our plan for this release.

**Comment by rainersigwald** [comment]
@livarcocc : This is our plan for unifying MSBuild versions and packages between the 15.7 and 2.1.300 releases. Unfortunately, it requires an insertion to CLI to prep for (theoretical) future 3xx releases, but it's the best we could come up with.

**Comment by livarcocc** [comment]
Seems feasible.

**Comment by mmitche** [comment]
Given that we won't know the final reference until the very end, and msbuild has dependency uptake, I think this should look a little more like:

- [ ] Accept #3222 to drop the prerelease tag from our output version.
- [ ] Insert the output of that build to VS but **do not** publish packages.
- [ ] Msbuild stays in prodcon until the end, but fixes on a single hash or unchanging branch (the final hash inserted into VS)
- [ ] Wait until 2.1 final shipping bits are produced
- [ ] Publish the NuGet packages that came out of prodcon and point to RTM .NET Core package versions.
- [ ] Immediately check in a change to our `vs15.7` branch that freezes our `$(MicrosoftNETCoreAppVersion)` to the RTM version.
- [ ] Update CLI's reference to MSBuild to point to the release packages.
- [ ] Disconnect CLI's uptake dependency on MSBuild in prodcon so it depends on the checked-in package version for servicing.

**Comment by rainersigwald** [comment]
The plan changed somewhat, because we had to take an urgent fix for 15.7.2 that we were able to get into .NET Core SDK 2.1.300 as well.

https://www.nuget.org/packages/Microsoft.Build/15.7.179
