### ISSUE TITLE
Question: Are item Include paths always relative to $(MSBuildProjectDirectory)

### ISSUE THREAD

**Issue by MarkPflug** [Microsoft/msbuild#3242]
### Steps to reproduce

In a somewhat non-standard build configuration, I have two csproj files that contain item definitions that I need to gather for a separate build process. I'm finding that item definition "Include" paths don't work the way I thought they did. 

As a minimal example:

Directory structure:
- Root/
  - Proj1/
    - Proj1.proj
    - Test1.cs
  - Proj2/
    - Proj2.proj
    - Test2.cs
  - Full.proj

[Full.proj]
```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <Import Project="Proj1/Proj1.proj"/>
  <Import Project="Proj2/Proj2.proj"/>
  
  <Target Name="Build">
    <Message Text="%(Compile.FullPath)"/>
  </Target>
</Project>
```

[Proj1.proj]
```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <Compile Include="Test1.cs"/>
  </ItemGroup>
</Project>
```

Command line
```
msbuild Full.proj
```
### Expected  behavior
  C:\users\mpflug\Desktop\msbuildtest\Proj1\Test1.cs
  C:\users\mpflug\Desktop\msbuildtest\Proj2\Test2.cs

### Actual behavior
  C:\users\mpflug\Desktop\msbuildtest\Test1.cs
  C:\users\mpflug\Desktop\msbuildtest\Test2.cs

### Environment data
`msbuild /version` output: `15.6.85.37198`

OS info: Win 10 64bit

I had expected that the Compile Include paths would be relative to the ProjX.proj files (`$(MSBuildThisFileDirectory)`) rather than being relative to the Full.proj (`$(MSBuildProjectDirectory)`) that is importing them. Has it always worked this way? Is there a reasonable way to accomplish what I'm trying to do?

Example project: https://github.com/MarkPflug/MSBuildCombine

**Comment by rainersigwald** [comment]
Yes, relative paths in `<Import>`ed files are relative to the _project_, not the _file they came from_. That's discussed a bit in the docs [here](https://docs.microsoft.com/en-us/visualstudio/msbuild/import-element-msbuild#remarks).

One option to do what you want is to explictly `<Compile Include="$(MSBuildThisFileDirectory)\Test1.cs" />` though VS won't maintain that for you.

The "standard" VS way to accomplish this goal is with a shared project (`.shproj`). Have you tried that?

**Comment by MarkPflug** [comment]
That behavior feels backwards to me. It seems like if you want to include files relative to the *entry-project* that you should have to `Include="$(MSBuildProjectDirectory)/**/*.cs"`. Since the standard for any user-land project file (csproj, vbproj) is to define items relative to *itself*. That way the burden would be on the build targets author (you), who could be expected to understand such esoterica. I know that nothing can be done about it at this point... I'm just looking for validation that I'm not crazy.

Never heard of a shared project before, I suspect they aren't going to suit my particular scenario, but I'll look into it.  I suspect I'll have to write a custom build task to parse the child project files, and scrape out their Includes with the corrected absolute path. Ugly, but it should work.

Thanks for the quick response.

**Comment by rainersigwald** [comment]
I don't think that's unreasonable--there are arguments either way. But MSBuild has behaved like this since v1 so as you say there's no changing it now.

Don't parse project files yourself, it's asking for pain and suffering. What if one of those projects uses a shared project, or imports something, or uses a wildcarded Include, or a conditional Include, or a conditional ItemGroup, or expands a property in an Include? Soon you'll have all kinds of other opinions about how MSBuild should have been designed (we certainly do!).

A better approach would be to let the MSBuild do all of that work on behalf of the other project. Add a target in Proj1 and Proj2 (define it only once; import it in the projects) that `Returns` the item you're interested in, just `BeforeTargets` it would be consumed (probably in `CoreCompile`). Then in Full.proj, `<MSBuild>` that target in the other projects and use its output as you wish. Does that make sense?

**Comment by chipplyman** [comment]
> The "standard" VS way to accomplish this goal is with a shared project (`.shproj`). Have you tried that?

For posterity, the way that Visual Studio accomplishes this goal within a .shproj is by implicitly prepending `$(MSBuildThisFileDirectory)` to every item in the `.projitems` file.

The implementation of a .shproj from the perspective of MsBuild is nothing more than `<Import Project="..\SharedProject\SharedProject.projitems" Label="Shared" />`. If (as I did) you manually edit the `.projitems` file to add a file using a relative path, its FullPath will be wrong from the perspective of the consuming project.
