### ISSUE TITLE
RequestHandlerPumpProc leads into thread pool exhaustion issue

### ISSUE THREAD

**Issue by lifengl** [Microsoft/msbuild#3281]
The code starts a normal task and call into this method, which doesn't exit.  It will take one thread out of the thread pool, and when the overall number goes lower, it can lead into thread pool exhaustion issue.

The fix is easy, you need pass a flag to tell CLR that this is a long run task, so it starts it with a new thread.  (Or you can create your own thread to run this proc.)

**Comment by lifengl** [comment]
Note, this issue is showing in OrchardCore RPS test trace.

**Comment by rainersigwald** [comment]
Seems reasonable. It's only instantiated one place:

https://github.com/Microsoft/msbuild/blob/7960c8032a98990d5a4a96ae0e6be7f66327e24b/src/Build/BackEnd/Components/SdkResolution/MainNodeSdkResolverService.cs#L112

@jeffkl There should only be one of these per process, right? Or is it one per build?

**Comment by jeffkl** [comment]
Yeah its only one thread in the main node.  Doesn't the main node exit?  So this thread is only around until it exits?  Or does it live longer in VS?  Either way, I can send a PR shortly...

**Comment by rainersigwald** [comment]
In VS, the main node lives for the life of `devenv.exe`, so this does seem worth doing for that case.
