### ISSUE TITLE
Support targeting .NET 4.7.2

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#3285]
MSBuild needs to understand .NET 4.7.2 so developers can target it using new VS/MSBuild.

**Comment by zachsa** [comment]
Thanks - I have been trying to do just this. And my knowledge of .NET is such that without finding this pull request via google I would have been completely stumped. Do you know when this will be introduced?

**Comment by rainersigwald** [comment]
AFAIK this is done with #3286. We can reopen if there's more work discovered.
