### ISSUE TITLE
Output Colors

### ISSUE THREAD

**Issue by abk-x** [Microsoft/msbuild#3296]
### Steps to reproduce
I originally posted the issue to here https://github.com/dotnet/cli/issues/9250, but according to one of the comments it looks like I should investigate msbuild.

### Summary:

- dotnet build and dotnet run commands do not color output (at all). 
- dotnet build /clp:ForceConsoleColor allows colors to correctly appear
- This does not work for dotnet run of course.

My main questions are: 
- Is there a ForceConsoleColor command (perhaps an environment variable) for `dotnet run`
- How does one troubleshoot why this is occurring?

### Environment data
`msbuild /version` output: `Microsoft (R) Build Engine version 15.7.177.53362 for .NET Core`

OS info:

Linux, x86, with dotnet core:

  Version: 2.1.0-rc1
  Commit:  eb9bc92051

**Comment by rainersigwald** [comment]
Do I understand correctly that you also don't see colors _when running your custom application_ that uses `Console.ForegroundColor`?

**Comment by abk-x** [comment]
Correct! I run it via dotnet run though, which according to https://github.com/dotnet/cli/issues/9250#issuecomment-388116275 , it seems msbuild is somehow involved in this?

**Comment by rainersigwald** [comment]
MSBuild is invoked to build  your code, then it's run. Since it sounds like neither the `dotnet` CLI itself nor MSBuild nor your application is working, this sounds like a problem with the common coloring library itself. I'll move the CLI bug (which has more info) to the appropriate repo for that.

**Comment by abk-x** [comment]
Cool, thank you for that (and your response time was epic)! It is confusing to decouple the components involved. I will close this one.
