### ISSUE TITLE
IncludeSource in .csproj doesn't work

### ISSUE THREAD

**Issue by josh-endries** [Microsoft/msbuild#3302]
I've been trying to embed source and/or PDBs into a NuGet package but can't figure it out with the new `csproj` files. I have a project that targets a few frameworks. I'm using VSTS, which is a whole other mess, but it doesn't work locally in VS2017 either. I used to just use `<files/>` in the `nuspec` file, but that doesn't work with the new projects, apparently, or multi-targeting at least.

Based on [this page](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj) I tried to add `<IncludeSource>true</IncludeSource>` to my `PropertyGroup` but that didn't work. It did build a symbols package but that's not what I'm looking for. I also tried adding `<IncludeSourceFilesProjectOutputGroup></IncludeSourceFilesProjectOutputGroup>` but that didn't work either. There's no real or useful documentation on that though and I don't know what it is, it just sounded related. This whole thing is so confusing it's insane.

I just tried `msbuild /t:pack /p:IncludeSource=true` but that didn't do it either. The page linked above doesn't really make clear what sort of keyword they all are.

**Comment by rainersigwald** [comment]
This issue was moved to NuGet/Home#6931
