### ISSUE TITLE
Debugging a Remove operation on an ItemGroup

### ISSUE THREAD

**Issue by jaredpar** [Microsoft/msbuild#3307]
I'm attempting to remove an item in the `<None>` collection via a `Remove` operation in our core targets file:
```
<ItemGroup>
  <None Remove="*\_common\xunit.abstractions.dll" />
</ItemGroup>
```

This is not functioning. The item remains in the group and further actions are taken on it. As far as I can tell by looking at the binlog this target is processed but it doesn't seem to have an effect. 

How can I debug this? I'm interested in knowing ...

a. For certain this ItemGroup declaration is processed. 
b. Why this particular Remove operation failed. The glob and name are correct (as far as my understanding of msbuild globs go at least). 

Any help here would be appreciated. For the moment I am stuck on this.

**Comment by rainersigwald** [comment]
We don't tend to log much around glob expansion since it can be super chatty.

Can you print the directory tree involved with `tree /f` or similar?

You can always fall back to a Printf-style debugging option:

```xml
<ItemGroup>
  <Debug_Remove Include="*\_common\xunit.abstractions.dll" />
</ItemGroup>

<Warning Text="Tried to remove @(Debug_Remove)" />
```

**Comment by jaredpar** [comment]
Here is my updated Target now:

``` xml
  <Target Name="RemoveXUnitAbstractions">
    <Warning Text="Before xunit.abstractions remove @(None)" />
    <ItemGroup>
      <None Remove="*\_common\xunit.abstractions.dll" />
    </ItemGroup>
    <Warning Text="After xunit.abstractions remove @(None)" />
  </Target>
```

This is the text of building:

``` cmd
E:\code\roslyn\build\Targets\Imports.targets(389,5): warning : Before xunit.abstractions remove e:\nuget\xunit.runner.visualstudio\2.3.1\build\net20\..\_common\xunit.runner.vi sualstudio.testadapter.dll;e:\nuget\xunit.runner.visualstudio\2.3.1\build\net20\..\_common\xunit.runner.reporters.net452.dll;e:\nuget\xunit.runner.visualstudio\2.3.1\build\net 20\..\_common\xunit.runner.utility.net452.dll;e:\nuget\xunit.runner.visualstudio\2.3.1\build\net20\..\_common\xunit.abstractions.dll;Resources/default.win32manifest;Resources/ nativeWithStringIDsAndTypesAndIntTypes.res;Resources/Roslyn.ico.blah;Resources/VerResourceBuiltByRC.RES;Properties\launchSettings.json;E:\code\roslyn\build\Targets\..\Defaults \Desktop\app.config [E:\code\roslyn\src\Compilers\Core\CodeAnalysisTest\CodeAnalysisTest.csproj]
E:\code\roslyn\build\Targets\Imports.targets(393,5): warning : After xunit.abstractions remove e:\nuget\xunit.runner.visualstudio\2.3.1\build\net20\..\_common\xunit.runner.vis ualstudio.testadapter.dll;e:\nuget\xunit.runner.visualstudio\2.3.1\build\net20\..\_common\xunit.runner.reporters.net452.dll;e:\nuget\xunit.runner.visualstudio\2.3.1\build\net2 0\..\_common\xunit.runner.utility.net452.dll;e:\nuget\xunit.runner.visualstudio\2.3.1\build\net20\..\_common\xunit.abstractions.dll;Resources/default.win32manifest;Resources/n ativeWithStringIDsAndTypesAndIntTypes.res;Resources/Roslyn.ico.blah;Resources/VerResourceBuiltByRC.RES;Properties\launchSettings.json;E:\code\roslyn\build\Targets\..\Defaults\ Desktop\app.config [E:\code\roslyn\src\Compilers\Core\CodeAnalysisTest\CodeAnalysisTest.csproj]
```

Feel like I'm missing something basic here. The target is running when I would expect, the glob seems simple enough to match and yet it's still there after the ItemGroup is processed.

**Comment by jaredpar** [comment]
Here is the `tree /f` view of the NuGet folder 

```
Folder PATH listing for volume New Volume
Volume serial number is 000000E5 E8A6:FDDD
E:.
└───2.3.1
    │   xunit.runner.visualstudio.2.3.1.nupkg
    │   xunit.runner.visualstudio.2.3.1.nupkg.sha512
    │   xunit.runner.visualstudio.nuspec
    │
    └───build
        ├───net20
        │       xunit.runner.visualstudio.props
        │
        ├───netcoreapp1.0
        │       xunit.abstractions.dll
        │       xunit.runner.reporters.netcoreapp10.dll
        │       xunit.runner.utility.netcoreapp10.dll
        │       xunit.runner.utility.netcoreapp10.xml
        │       xunit.runner.visualstudio.dotnetcore.testadapter.deps.json
        │       xunit.runner.visualstudio.dotnetcore.testadapter.dll
        │       xunit.runner.visualstudio.props
        │
        ├───uap10.0
        │       xunit.runner.reporters.netstandard11.dll
        │       xunit.runner.utility.netstandard11.dll
        │       xunit.runner.visualstudio.props
        │       xunit.runner.visualstudio.targets
        │       xunit.runner.visualstudio.uwp.dll
        │       xunit.runner.visualstudio.uwp.pri
        │
        └───_common
                xunit.abstractions.dll
                xunit.runner.reporters.net452.dll
                xunit.runner.utility.net452.dll
                xunit.runner.visualstudio.testadapter.dll
```

**Comment by rainersigwald** [comment]
And where is the file that contains the target?

The problem is probably that our glob matcher isn't smart enough to match `..` elements; they may have to be explicitly added.

**Comment by jaredpar** [comment]
> And where is the file that contains the target?

source code: `e:\roslyn`
nuget: `e:\nuget`

> The problem is probably that our glob matcher isn't smart enough to match .. elements; they may have to be explicitly added.

Hmm. That means we essentially have to take a dependency on how the props file of the NuGet package chooses to include the files. It is explicitly done via `..` today. That's less than ideal.

**Comment by jaredpar** [comment]
> The wildcard is expanded from the target file's location. 

Sigh. I think this is probably the third time you've mentioned this to me. I will try to not forget it this time 😦 

> Are you saying that is not in the NuGet package? 

No it's definitely there (sadly). The problem I'm having is removing it in a reliable manner. The current Remove is a bit flaky and I was digging into why this morning. I tried to make it simpler with a glob but didn't quite understand the limitations of globs (can't process `..`) or the design (begins from target file location). 

Either way though this has unblocked me. I can now at least debug what is going on here and attempt to make it a bit more solid. Thanks!

**Comment by jzabroski** [comment]
@jaredpar Thank you for forgetting the answer to this question for a third time, so that @rainersigwald could post a public reply here and help me on 7/19/2021 troubleshoot `NU5050: Attempted to pack multiple files into the same location(s). The following destinations were used multiple times: Web.Prototype.config, Web.Alpha.config, Web.Beta.config, Web.config, Web.Production.config`
