### ISSUE TITLE
Transitive PackageReference packages do not contribute build logic

### ISSUE THREAD

**Issue by dansiegel** [Microsoft/msbuild#3314]
### Description

When adding a top level dependency with PackageReference, children are not properly loaded, causing build Tasks to be missing during build.

### Steps to reproduce

See attached sample project with binlog

[Foo.zip](https://github.com/Microsoft/msbuild/files/2005711/Foo.zip)

### Expected  behavior

Install a top level PackageReference such as Prism.DryIoc.Forms with a dependency on Prism.Forms, with a dependency on Xamarin.Forms and the build tasks from Xamarin.Forms should be executed during the build.

### Actual behavior

Build tasks are missing from the build pipeline unless Xamarin.Forms is added as it's own PackageReference.

### Environment data
`msbuild /version` output:
Microsoft (R) Build Engine version 15.7.0.0 (xplat-master/402b4b23 Wed Mar 28 23:51:55 EDT 2018) for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

OS info: OSX 10.13.4

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):

**Comment by rainersigwald** [comment]
Thanks for reporting. This looks like a NuGet restore behavior, so I'm going to move this to the NuGet repo.

**Comment by rainersigwald** [comment]
This issue was moved to NuGet/Home#6934

**Comment by dansiegel** [comment]
@rainersigwald nuget restore works just fine and intellisense from inside the IDE works just fine... it's just not being picked up by MSBuild

**Comment by rainersigwald** [comment]
NuGet restore is responsible for creating (in your example) `obj\Foo.csproj.nuget.g.targets` with links to the build logic delivered in the referenced NuGet packages. It's completing successfully, but that file doesn't have a link to the XF targets, so it's not doing the right thing.
