### ISSUE TITLE
How to get help with PR?

### ISSUE THREAD

**Issue by cclauson** [Microsoft/msbuild#3333]
Hi,

I have a PR up that should fix an issue with the MSBuild expression parser.  The PR is here:
https://github.com/Microsoft/msbuild/pull/3165

I posted previously here:
https://github.com/Microsoft/msbuild/issues/3163
but got no replies.  Can anyone with MSBuild help me with this?

Thank you so much.

**Comment by rainersigwald** [comment]
Duplicate of #3163

**Comment by cclauson** [comment]
@rainersigwald Maybe, but how do I actually get help?  Is there any procedure for this?  Thanks so much.
