### ISSUE TITLE
Automatically import $(MSBuildProjectName).props/.targets if found

### ISSUE THREAD

**Issue by kzu** [Microsoft/msbuild#3338]
The IDE(s) will typically modify the .csproj whenever you add/remove stuff and save. Sometimes, it's not 100% full-fidelity (i.e. it will modify the newlines in attributes you might have carefully crafted). 

In addition, sometimes you just want to keep the declarative project structure and props in the csproj, and leave the augmented behavior in a separate `.targets` file alongside the project (I do this all the time for VSIX projects, for example, or to separate the packaging aspects from the build aspects of the project).

It would be useful if the Common.props and Common.targets already imported those files automatically, like:

```xml
<Import Project="$(MSBuildProjectDirectory)\$(MSBuildProjectName).props"
        Condition="Exists('$(MSBuildProjectDirectory)\$(MSBuildProjectName).props')" />
```
and
```xml
<Import Project="$(MSBuildProjectDirectory)\$(MSBuildProjectName).targets"
        Condition="Exists('$(MSBuildProjectDirectory)\$(MSBuildProjectName).targets')" />
```

**Comment by AndyGerlicher** [comment]
There are already a lot of extension points. I would think Directory.Build.props/targets might be close? Unless you don't want any imports? In which case I would use an SDK from a NuGet package or something like that.

**Comment by kzu** [comment]
Indeed, there are. Just thinking that something seamless like the auto-correct importing of directory.build.props/targets would make sense at the project level too.

**Comment by kzu** [comment]
Closing. This is easily achievable with those two lines in `Directory.Build.props` and `Directory.Build.targets`, so ¯\_(ツ)_/¯
