### ISSUE TITLE
Evaluating project file from .Net Core application throws StackOverflowException

### ISSUE THREAD

**Issue by kovalikp** [Microsoft/msbuild#3352]
### Steps to reproduce

I'm trying to evaluate project file from .Net Core application using `Microsoft.Build` packages. Target project uses `Microsoft.NET.Sdk`. The approach is similar to `Microsoft.Build.Locator` package, where `Microsoft.Build` dependencies are marked with `ExcludeAssets="runtime"`. Instead loading them from application directory, the application uses `AppDomain.CurrentDomain.AssemblyResolve` to load assemblies from SDK directory.

You can find sample over here: https://github.com/kovalikp/MSBuildCoreTest

### Expected  behavior

Being able to load project get list of targets from project file.

### Actual behavior

Application crashes on `Exception Unhandled: System.StackOverflowException`. Exception does not have stack trace or any other useful data.

### Environment data

OS info:
Windows 10
Version	10.0.17134 Build 17134

Microsoft Visual Studio Enterprise 2017 
Version 15.7.2
VisualStudio.15.Release/15.7.2+27703.2018

Project target framework:
netcoreapp2.0

NuGet package 
Microsoft.Build 15.7.179

dotnet 
sdk 2.1.201

**Comment by JoeRobich** [comment]
I ran into the same issue. I was able to work around it by not excluding the assets from the MSBuild nuget packages, delivering them with my application, and disabling my custom MSBuildLocator. I would prefer to simply load the version supplied in the dotnet SDK since the workaround makes my deliverable much bigger.

**Comment by JoeRobich** [comment]
I found a preferable work around. Instead of including the package assets, if I load the MSBuild assemblies from the dotnet sdk folder upfront (`Assembly.LoadFrom`), everything works as expected.
