### ISSUE TITLE
Better Pdb story for MSBuild repo

### ISSUE THREAD

**Issue by KirillOsenkov** [microsoft/msbuild#3354]
Currently it seems that we're publishing the .pdb files inside the `lib\net46` folder of NuGet packages for MSBuild (e.g. https://www.nuget.org/packages/Microsoft.Build). However those .pdbs don't seem to be SourceLinked (i.e. they don't point to sources on GitHub). They also seem to be classic (not portable) pdbs.

It would be great if these .pdbs were source linked, i.e. mapped to the exact source of the commit on GitHub.

cc @tmat

**Comment by rainersigwald** [comment]
They were sourcelinked; I think moving to repo-toolset broke that. We have to generate classic PDBs to push to the public symbol servers, which is unfortunate. Maybe that's better now? It's worth looking into.

**Comment by tmat** [comment]
> We have to generate classic PDBs to push to the public symbol servers, which is unfortunate.

Generally the guidelines is to build with Portable PDBs and convert them to Windows PDBs when publishing to MS symbol server. The toolset has support for such process and it's easy to do. 

First, I'd recommend converting your VSTS build definitions to YAML format. See e.g. https://github.com/dotnet/roslyn/blob/master/.vsts-ci.yml. That makes it much easier to make the necessary changes to symbol publishing.

**Comment by KirillOsenkov** [comment]
This is fixed. The pdbs are embedded and sourcelinked.
