### ISSUE TITLE
MSBuild run target does not run .NET Core app

### ISSUE THREAD

**Issue by danmosemsft** [Microsoft/msbuild#3355]
### Steps to reproduce

Create any .NET Core project (eg., with `dotnet new console`)
Build it (eg., with `dotnet build` or `msbuild /t:restore;build`)
Run it with msbuild (ie., `msbuild /t:run`)

### Expected  behavior

It runs similar to doing `dotnet run` or `dotnet exec`

### Actual behavior

`C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(1056,5): error : Cannot run '....\xyz.dll' because project output type is not '.exe' [...\xyz.csproj]`

### Environment data
`msbuild /version` output: 15.8.52.54110

OS info: Win 10

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):
```
>dotnet --version
2.1.4
```

Not sure many people know about the `run` target so perhaps this isn't a big deal - but ideally something in the .NET Core SDK targets would override it to make it work.

cc @livarcocc

**Comment by rainersigwald** [comment]
I didn't know about this! I think the right fix would be an override in the SDK so I'm going to move this to that repo.

**Comment by rainersigwald** [comment]
This issue was moved to dotnet/sdk#2283
