### ISSUE TITLE
Misleading license header in MSBuildTasks.h in repo

### ISSUE THREAD

**Issue by omajid** [Microsoft/msbuild#3361]
The MSBuildTasks.h file (https://github.com/Microsoft/msbuild/blob/xplat/src/Tasks/MSBuildTasks.h) has a license header that looks a bit weird:

```
//--------------------------------------------------------------------------
//
// Copyright (C) 2015 Microsoft Corporation,
// All rights reserved
//
```

This seems to imply (with the "all rights reserved", and no license note) that this file is not open source. Would it  be possible to switch to the format used by other files in this repository? For example,

```

// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
```

(From https://github.com/Microsoft/msbuild/blob/xplat/src/Tasks/AssemblyRemapping.cs). Or some header that is more consistent with the main LICENSE file in the repository? This would address my concerns. Thanks!

**Comment by rainersigwald** [comment]
Thanks for the report, @omajid.
