### ISSUE TITLE
Add tasks for working with file hashes

### ISSUE THREAD

**Issue by natemcmaster** [Microsoft/msbuild#3369]
We've found it useful to have MSBuild tasks for computing and checking file hashes. I'd like to contribute back these tasks to MSBuild. Is this something you would consider taking?

See https://github.com/dotnet/arcade/tree/6bb34082e02ae8a816787d39eb4affc347dad35b/src/Microsoft.DotNet.Build.Tasks.IO#getfilehash and https://github.com/dotnet/arcade/tree/6bb34082e02ae8a816787d39eb4affc347dad35b/src/Microsoft.DotNet.Build.Tasks.IO#verifyfilehash

cc @jeffkl

**Comment by jeffkl** [comment]
As long as the new tasks don't require any new assemblies (which they don't appear to), we'd be happy to accept them!
