### ISSUE TITLE
Clear documentation strategy

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#338]
Currently, we have Microsoft official documentation on MSDN, a variety of old blog posts, and no clear way for people to contribute documentation.  That's no good!  We should have a clear description of what exists and a plan to get to a nice, uniform way to produce + improve documentation.

**Comment by rainersigwald** [comment]
I'd especially like to hear from folks outside our team at Microsoft:  what would you like our doc story to look like?  Are there projects you'd like us to emulate?

**Comment by jasonwilliams200OK** [comment]
Yes please, especially the milestone docs which gives some (rough) timeline for issues like #64 (so we can resurrect #116) and #103; to get all the efforts streamlined in one unified branch and one unified release cycle with same quality for all the supported platforms and OSes. :)

**Comment by rainersigwald** [comment]
Ideally we'd do what CoreCLR and friends do, perhaps using tooling like https://github.com/dotnet/core-docs.

**Comment by cdmihai** [comment]
What would be some requirements for the documentation system / workflow?

1. versioned history, in case something goes amiss -> CoreCLR git repo approach
2. review mechanism, so we can check what goes in -> CoreCLR git repo approach
3. keep in sync with MSDN documentation?
  1. Ideally, if MSDN is modular enough, we can replace the MSBuild documentation with a git repo that merges and cherry picks commits from the potential MSBuild GH documentation repo.
  2. If MSDN is closed, then the MSBuild GH documentation repo could become the official one and MSDN becomes a historical reference
  3. Format wise, depending on how the MSDN docs are kept on the server, we might have to write a quick adapter between the two.

**Comment by rainersigwald** [comment]
We have new documentation available at https://docs.microsoft.com/en-us/visualstudio/msbuild that is user-editable (and indeed stored on GitHub: https://github.com/Microsoft/visualstudio-docs/tree/master/docs/msbuild). Now we just have to make it awesome.
