### ISSUE TITLE
A build with /nodeReuse:false will reuse nodes that were left running by a previous build

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#339]
Consider this:
```cmd
msbuild /m /nr:true someBigProject.proj
msbuild /m /nr:false someOtherProject.proj
```

Most people would expect the first build to leave child processes running (that being the point of the `/nodeReuse` flag).  The second shouldn't leave any new processes running.

What's surprising is that the second build will reuse processes left over from the first build.  That causes problems if you have per-node state, or if you're looking at I/O from the process cone of MSBuild.

This appears to be intentional but I can't justify the behavior.  I think we should change `/nr:false` to always spawn new processes.

**Comment by rainersigwald** [comment]
It looks like we already have a "handshake" process to determine whether a given worker node is in the right elevation level, username, and so on.  I think we can add "is allowed to be reused" to that safely.  See https://github.com/Microsoft/msbuild/blob/ab862ac37e6c5c828dea9f2c5fc492d02310b8cb/src/XMakeBuildEngine/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs#L155

**Comment by rainersigwald** [comment]
This change has been ported to our internal repo as well, so it should be available in Update 2.

**Comment by petervlad** [comment]
Anyone still has this problem? Using VS 2019. Because of the processes left behind I have errors like this one: _MSB3191	Unable to create directory "obj\Debug\net472\". Access to the path 'obj\Debug\net472\' is denied_

**Comment by rainersigwald** [comment]
@petervlad please file a new issue describing your problem in detail. This issue would not have resulted in that error.
