### ISSUE TITLE
No valid MSBuild was detected for the selected target.

### ISSUE THREAD

**Issue by jdnichollsc** [Microsoft/msbuild#340]
Hi guys,

When you going to create a new Cordova Project on Visual Studio 2015 and building it for Windows x86 one exception is displayed

See please the following video for more details: http://screencast.com/t/H1EBKQeLdYr0

Regards, Nicholls

**Comment by rainersigwald** [comment]
@jdnichollsc That error message appears to be generated in Cordova tooling, not by MSBuild itself.

Searching for the literal text of the error turns up https://www.mail-archive.com/commits@cordova.apache.org/msg25355.html, which seems to have introduced this error.  Unfortunately, I know nothing about the Cordova build process, so I'm not sure what would cause this error.

I think your best bet is to contact the Cordova folks.  If they have a question about their interaction with MSBuild related to this problem, we may be able to help investigate.

**Comment by jasonwilliams200OK** [comment]
Based on https://github.com/MSOpenTech/cordova-windows, perhaps @sgrebnov can assist?

Also, there is Twitter and Email provided in first paragraph of this blog post: http://blogs.msdn.com/b/visualstudio/archive/2014/08/04/apache-cordova-tooling-update-with-support-for-windows-7.aspx.

**Comment by jeffkl** [comment]
I believe this has been taken care of. If not please re-open.
