### ISSUE TITLE
Capture .sln.metaproj in binlog if MSBUILDEMITSOLUTION is specified

### ISSUE THREAD

**Issue by KirillOsenkov** [Microsoft/msbuild#3402]
If I run a solution build with /bl and MSBUILDEMITSOLUTION=1 environment variable, it would be nice to capture the emitted .sln.metaproj along with other files in the binlog archive.

**Comment by rainersigwald** [comment]
This would be good even when that diagnostic flag isn't set if it isn't expensive.

One wrinkle: when `MSBUILDEMITSOLUTION=1`, we actually emit _two_ files for each solution. We should collect both.

**Comment by AndyGerlicher** [comment]
Also, if you have project build dependencies configured in your sln you get a `.metaproj` for _each_ project... so even more fun!
