### ISSUE TITLE
Nuget package installation continues if Init.ps1 fails

### ISSUE THREAD

**Issue by jpsalada** [Microsoft/msbuild#3413]
### Steps to reproduce

Install a Nuget package that executes an Init.ps1 script during the installation. The script ends with Exception (we use throw, and also tried Exit 1 or Exit -1), but the installation continues.

### Expected  behavior

We expected that the installation would fail upon Init.ps1 failure.  Basically we have dependencies on external binaries. If the binaries are not found in the system, installation should fail, as our Nuget is not usable.

### Actual behavior

Installation continues if Init.ps1 terminates with error.

### Environment data
`msbuild /version` output:
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

15.7.179.6572

OS info:
Windows 10
If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):
Visual Studio Community 2017 Version 15.7.3

**Comment by rainersigwald** [comment]
This issue was moved to NuGet/Home#7039
