### ISSUE TITLE
xplat CI builds should build full-framework and netcore MSBuild

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#342]
Currently, the `RebuildWithLocalMSBuild.cmd` script that is the CI entry point only builds the `Debug-netcore` configuration of MSBuild in the xplat branch.  In preparation for branch unification, we need to make sure  MSBuild is working correctly in full-framework mode in that branch as well.

**Comment by AndyGerlicher** [comment]
Lets rename that to something like cibuild.cmd though :)

**Comment by rainersigwald** [comment]
This has been done for a while. We should add Mono soon.
