### ISSUE TITLE
Microsoft.Build.* is not compatible with netstandard1.6

### ISSUE THREAD

**Issue by mwpowellhtx** [Microsoft/msbuild#3435]
I started off targeting ``netstandard1.6`` basing my assumptions off a template I was using as reference. However, soon discovered these errors.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Microsoft.Build.Framework 15.7.179 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package Microsoft.Build.Framework 15.7.179 supports:
  - net46 (.NETFramework,Version=v4.6)
  - netstandard2.0 (.NETStandard,Version=v2.0)	BumpAssemblyVersions	G:\Source\Kingdom Software\BumpAssemblyVersions\Prototype\src\BumpAssemblyVersions\BumpAssemblyVersions.csproj	1	
Error	NU1202	Package Microsoft.Build.Utilities.Core 15.7.179 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package Microsoft.Build.Utilities.Core 15.7.179 supports:
  - net46 (.NETFramework,Version=v4.6)
  - netstandard2.0 (.NETStandard,Version=v2.0)	BumpAssemblyVersions	G:\Source\Kingdom Software\BumpAssemblyVersions\Prototype\src\BumpAssemblyVersions\BumpAssemblyVersions.csproj	1	

```

I changed the ``TargetFramework`` to ``netstandard2.0`` and am still receiving this error. Even after a Rebuild.

My package references are thus:

```Xml
<ItemGroup>
  <PackageReference Include="Microsoft.Build.Framework" Version="15.7.179" />
  <PackageReference Include="Microsoft.Build.Utilities.Core" Version="15.7.179" />
  <PackageReference Include="System.Xml.XDocument" Version="4.3" />
  <PackageReference Include="System.Xml.XPath.XDocument" Version="4.3" />
  <PackageReference Include="Newtonsoft.Json" Version="11" />
  <PackageReference Update="@(PackageReference)" PrivateAssets="All" />
</ItemGroup>
```

At the moment, I am not multi-targeting at all. Do I need to account for the ``4.6`` path in the targeting set?

Thanks!

**Comment by rainersigwald** [comment]
Have you done a new restore after updating your `TargetFramework`?

**Comment by mwpowellhtx** [comment]
Oh, I think I see... I needed to be more specific in my ``Version`` request...

**Comment by mwpowellhtx** [comment]
@rainersigwald However, I would suggest, there may be a stale message ``netstandard1.6`` even though the package indeed multi-targets [``netstandard2.0`` and ``net46``](https://www.nuget.org/packages/Microsoft.Build.Framework/#Dependencies). That could mislead some folks into chasing either (or both) of those rabbit holes to no avail.
