### ISSUE TITLE
MSBuild Out of Memory Error when run from Jenkins

### ISSUE THREAD

**Issue by E2102** [Microsoft/msbuild#3436]
Hello. I've been running into this problem for the last couple days on a project I'm working on and can now reliably reproduce it.

We have a jenkins machine setup to build a Visual Studio solution. The solution is generated from CMake and has about 2 dozen projects in it. The build takes about 20 minutes.

I wanted to speed it up so I added the /m[axcpucount] option. The machine has 6 CPUs. Running MSBuild on the machine directly or through SSH with the /m flag works fine and the build is faster. For some reason, running the command from Jenkins causes the machine to continuously spawn MSBuild.exe or MSBuild.dll* processes which eventually causes Windows to run out of memory.

I really don't understand why this is the case from Jenkins but it doesn't happen when running MSBuild on the machine directly in DOS, MSBuild console or MSYS2 (which is how I'm connecting over SSH).

Has anyone seen similar behavior or have an idea what might be the culprit?

This is with a setting of /m:3

![msbuild_spam](https://user-images.githubusercontent.com/31298292/41696155-77004252-74c7-11e8-8b02-c16f0258c506.png)

The command jenkins was running is 
`cmd.exe /C " chcp 1252 && "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" /m:3 C:\Path\to\Solution.sln`

> The output is:
> Active code page: 1252
> Microsoft (R) Build Engine version 14.0.25420.1
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> Build started 6/20/2018 8:11:22 PM.
>      1>Project "C:\Path\to\Solution.sln" on node 1 (default targets).
>      1>ValidateSolutionConfiguration:
>          Building solution configuration "Debug|x64".
>        ValidateProjects:
>          The project "PROJECT_1" is not selected for building in solution configuration "Debug|x64".
>          The project "PROJECT_2" is not selected for building in solution configuration "Debug|x64".
>          The project "PROJECT_3" is not selected for building in solution configuration "Debug|x64".
>          The project "PROJECT_4" is not selected for building in solution configuration "Debug|x64".

After the first 4 projects it hangs. When running MSBuild on the machine directly though it continues and builds the rest of the solution.

Any help here would be greatly appreciated. Thank you!

**Comment by rainersigwald** [comment]
That sounds like the entry-point MSBuild.exe is correctly creating nodes, but then can't connect to them for some reason.

There may be some debugging information available by setting the environment variable `MSBUILDDEBUGCOMM=1`, which enables tracing to the `%TEMP%` directory (in recent MSBuild the directory is configurable but you're on 14 based on the log).

**Comment by livarcocc** [comment]
Closing due to lack of information.
