### ISSUE TITLE
error CS0101: when moving to Directory.Build.props

### ISSUE THREAD

**Issue by Duracell1989** [Microsoft/msbuild#3440]
When building; I get the warning to following warning:

> C:\Program Files\dotnet\sdk\2.1.201\Microsoft.Common.CurrentVersion.targets(818,5): warning MSB3539: The value of the property "BaseIntermediateOutputPath" was modified after it was used by MSBuild which can lead to unexpected build results. Tools such as NuGet will write outputs to the path specified by the "MSBuildProjectExtensionsPath" instead. To set this property, you must do so before
> Microsoft.Common.props is imported, for example by using Directory.Build.props.  For more information, please visit https://go.microsoft.com/fwlink/?linkid=869650

I had the following construction:
Project file:
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <Import Project="../config/configuration.props" />
[snip]
</Project>
```
configuration.props:
```
<Project>
  <PropertyGroup>
    <Configurations>Debug;Release</Configurations>
    <Platforms>AnyCPU</Platforms>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <BaseIntermediateOutputPath>..\..\artifacts\obj\</BaseIntermediateOutputPath>
    <OutputPath Condition="'$(Configuration)' == 'Release'">..\..\artifacts\build\</OutputPath>
  </PropertyGroup>
</Project>
```
I had created a configuration.props to unify the same properties across a couple of projects within the solution. As the warning suggests; I created a _Directory.Build.props_ on solution-level; remove the line from the _configuration.props_ and added it to a newly created _Directory.Build.props_:
```
<Project>
    <PropertyGroup>
      <BaseIntermediateOutputPath>..\..\artifacts\obj\</BaseIntermediateOutputPath>
    </PropertyGroup>
</Project>
```

I do see some files appearing in the artifacts\obj folder; but:

### Actual behavior
```
{Project1} -> r\artifacts\build\win10-x64\{Project1}.dll
obj\Debug\{Project2}.Program.cs(3,7): error CS0101: The namespace '<global namespace>'
already contains a definition for 'AutoGeneratedProgram' [\src\{Project2}\{Project2}.csproj]
```
### Expected  behavior
A working build.

I even tried
```
<BaseIntermediateOutputPath>..\..\artifacts\obj\$(MSBuildProjectName)</BaseIntermediateOutputPath>
```
but, this also doesn't work.

**Comment by dasMulli** [comment]
When you change your `BaseIntermediateOutputPath`, be sure to delete the default `obj` folder in your project file since the generated .cs files in there will conflict with the ones in the new location.

**Comment by Duracell1989** [comment]
That's it!
