### ISSUE TITLE
Document XmlPoke Namespaces parameter

### ISSUE THREAD

**Issue by pmisik** [Microsoft/msbuild#3451]
### Steps to reproduce
Current documentation of [XmlPoke ](https://docs.microsoft.com/en-us/visualstudio/msbuild/xmlpoke-task) is not clear how to use Namespaces attribute
Always I need to use XmlPoke with xml with multiple names I feel like I rediscover the wheel and I end up within code. I think it would be really worthy provide better description and also sample how to use it.
I think it is really worthy provide a sample on xml with multiple namespaces.

Form my knowledge ``Namespaces`` parameter is 
- xml escaped list of ``Namespace`` elements
- each element must have attributes ``Prefix`` and ``Uri``
- ``Prefix`` attribute specifies the prefix to associate with the namespace specified in ``Uri`` attribute
- Avoid using empty namespace ``Prefix`` as it does not work and replace it with some artificial ``Prefix`` name and modify ``Query`` according it.

Here is sample.xml to modify:
```xml
<Package xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10" 
         xmlns:mp="http://schemas.microsoft.com/appx/2014/phone/manifest" 
         xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10" >
<Identity Name="Sample.Product " Publisher="CN=1234" Version="1.0.0.0" />
<mp:PhoneIdentity PhoneProductId="456" PhonePublisherId="0" />
</Package>
````
If we want to modify ``/Package/mp:PhoneIdentity/PhonePublisherId``, then use 

```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

<Target Name="SampleUsageOfXmlPokeWithMultipleNamespaces">
  <XmlPoke
    XmlInputPath="Sample.xml"
    Value="MyId"
    Query="/dn:Package/mp:PhoneIdentity/@PhoneProductId"
    Namespaces="&lt;Namespace Prefix='dn' Uri='http://schemas.microsoft.com/appx/manifest/foundation/windows10'/&gt;
                &lt;Namespace Prefix='mp' Uri='http://schemas.microsoft.com/appx/2014/phone/manifest'/&gt;
                &lt;Namespace Prefix='uap' Uri='http://schemas.microsoft.com/appx/manifest/uap/windows10'/&gt;"/>
</Target>

</Project>
```

### Expected  behavior
Well documented ``Namespaces`` parameter with example on xml with multiple namespaces.

### Actual behavior
Unclear documentation

### Environment data
`msbuild /version` output:
```
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

15.7.179.6572
```
OS info:
All version/OS.

**Comment by rainersigwald** [comment]
That looks like a very nice example. Would you be interested in sending it as a PR to the docs page at https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/xmlpoke-task.md?

**Comment by pmisik** [comment]
I thought it is generated from sources comments. I had a prepared fix for xmldoc in src/Tasks/XmlPoke.cs. So I did not send PR to msbuild repo but according your comment I prepared PR  for https://github.com/MicrosoftDocs/visualstudio-docs/pull/1162

**Comment by pmisik** [comment]
Closed in favor of https://github.com/MicrosoftDocs/visualstudio-docs/pull/1162
