### ISSUE TITLE
Microsoft.VisualBasic.targets encoding is not supported in .NetCore

### ISSUE THREAD

**Issue by joperezr** [Microsoft/msbuild#351]
When trying to build corefx using .net Core msbuild, the build will throw an error when trying to import Microsoft.VisualBasic targets since it's encoding is set to 'Windows-1252' instead of utf-8

**Comment by joperezr** [comment]
cc @dsplaisted

**Comment by rainersigwald** [comment]
This was fixed with #319.  Are you still seeing problems?

**Comment by joperezr** [comment]
I see, I'll close this issue then and will cherry-pick the fix to my fork. Thanks!
