### ISSUE TITLE
Remote Debugging MSBuild properties not working with new MSBuild Format

### ISSUE THREAD

**Issue by TFTomSun** [Microsoft/msbuild#3524]
Using the old MSBuild Format it was possible to specify remote debugging settings like this:

```
  <PropertyGroup>
    <StartAction>Program</StartAction>
    <StartProgram>C:\MyRemote\Executable.exe</StartProgram>
    <RemoteDebugEnabled>true</RemoteDebugEnabled>
    <RemoteDebugMachine>MyRemoteMachine</RemoteDebugMachine>
  </PropertyGroup>
```
These properties seem to be not be evaluated by the new MSBuild Format, even if the Project is marked as a Net4.6.1 project.

Is that a bug or does the new MSBuild Format don't support remote debugging by simply starting debugging anymore?

**Comment by rainersigwald** [comment]
That should continue to work from the MSBuild perspective. What errors are you seeing? How do you know it's not working? I've never used remote debugging, so I don't know how to investigate.

**Comment by TFTomSun** [comment]
First off all, when the new sdk based MSBuild Format is used, the remote debugger settings in the project properties are not available anymore. When I manually set the remote debugger settings in the csproj file, it still does start a local debugging… It seems like the MSBuild properties are ignored. When the project is created using the old MSBuild Format, remote debugging works fine even with the latest VS 2017 Version.

**Comment by jp2masa** [comment]
The problem is probably that the feature hasn't been implemented in the .NET SDK: https://github.com/dotnet/sdk.

**Comment by rainersigwald** [comment]
Based on the description, I think it might be that it's not implemented yet in the new project system. I'll move this over there; if I'm wrong and it's actually the SDK we can move it there instead.

**Comment by rainersigwald** [comment]
This issue was moved to dotnet/project-system#3756
