### ISSUE TITLE
Expand help text for /restore to include cache clearing

### ISSUE THREAD

**Issue by dasMulli** [Microsoft/msbuild#3561]
The current help text for `/restore` reads:

```
  /restore[:True|False]
                     Runs a target named Restore prior to building
                     other targets.  This is useful when your project
                     tree requires packages to be restored before they
                     can be built. Specifying /restore is the same as
                     specifying /restore:True.  Use the parameter to
                     override a value that comes from a response file.
                     (Short form: /r)
```

This help text doesn't make it clear that `/r` with a `Restore` target should be used over constructs like `DependsOnTargets="Restore"`.

Please find a few words that make users use this switch instead. It doesn't have to go into details of the cache mechanisms, just something like:
`Use this switch to ensure the build uses the output generated by the Restore target`

**Comment by rainersigwald** [comment]
That's a very good idea. Would you be interested in contributing such a fix?
