### ISSUE TITLE
Turn on max path detection

### ISSUE THREAD

**Issue by cdmihai** [Microsoft/msbuild#3589]
Replace [flag](https://github.com/Microsoft/msbuild/blob/7b3a457540ab87cf02f6d41ce6095e6ecbbb6ea7/src/Shared/NativeMethodsShared.cs#L477) with runtime check. Leave it on by default. Add an escape hatch to revert back to old max path behaviour. Tests shoulds turn maxpath on so we test that reverting back is still possible.

**Comment by rainersigwald** [comment]
I don't think we have anything else to do on this.
