### ISSUE TITLE
Automatically prepend path of the project file with the latest timestamp

### ISSUE THREAD

**Issue by cdmihai** [Microsoft/msbuild#3591]
The current idiom of putting all project files in `$(MSBuildAllFiles)` has [perf implications](https://github.com/Microsoft/msbuild/issues/3004). Since it's used for incrementality checks, we can provide a reserved property like `MSBuildLatestProject` which avoids appending.

An alternative would be to [compute](https://github.com/Microsoft/msbuild/issues/1299) `MSBuildAllFiles`. This has complications though because the c++ sdks appends more files to it than just msbuild project files.

**Comment by radical** [comment]
Did you mean `MSBuildAllProjects`? What do you mean by "incrementality" checks?

**Comment by jeffkl** [comment]
I'm closing this in favor of #1299
