### ISSUE TITLE
Error parsing solution file ... invalid image with Mono 5.14.0.177, msbuild 15.0 in Travis CI

### ISSUE THREAD

**Issue by denfromufa** [Microsoft/msbuild#3604]
This is from gitter chat in Mono: https://gitter.im/mono/mono

**Any idea why we are getting "invalid image" error from VS solution file under certain conditions? Seems to be working under .NET Core and .NET Framework, but not Mono.**

https://travis-ci.org/pythonnet/pythonnet/jobs/415741698#L1874

```
Currently running NuGet.exe 4.1.0.
Updating NuGet.exe to 4.7.1.
Update successful.
MSBuild auto-detection: using msbuild version '15.0' from '/usr/lib/mono/msbuild/15.0/bin'.
Error parsing solution file at /home/travis/build/pythonnet/pythonnet/pythonnet.sln: Invalid Image
```

Katelyn Gadd @kg 22:36
invalid image parsing sln makes it sound like it's having trouble loading msbuild assemblies
Microsoft/msbuild#3282 this is the same error message
rather, the first part is the same. different exception
so it is indeed caused by a managed exception
https://github.com/rainersigwald/msbuild/commit/7960c8032a98990d5a4a96ae0e6be7f66327e24b#diff-af08e5d2c5235a664572f4581ba0e7c6R161 it looks like msbuild has had mono compatibility issues before

Denis Akhiyarov @denfromufa 22:41
@kg thanks for diagnostics, any easy workaround the get the CI builds going? I don't recall these errors last week for the same build configuration:
https://travis-ci.org/pythonnet/pythonnet/builds/413267958

Katelyn Gadd @kg 22:42
i'm sorry, i don't know enough to recommend a solution right now. you might want to ping @rainersigwald to see if he has any ideas
or you could file an issue since it's an exception in msbuild to see if they can suggest a fix. i think that error message is insufficient
so it is a useful defect report in the sense of 'we should at least improve this error message'
it looks like it only outputs exc.Message which is insufficient in this case

**Comment by rainersigwald** [comment]
That error is actually thrown from NuGet here: https://github.com/NuGet/NuGet.Client/blob/203c517a85791243f53ea08d404ee5b8fae36e35/src/NuGet.Clients/NuGet.CommandLine/MsBuildUtility.cs#L378-L414

I'll move this to the NuGet repo. When we collect more information about what's actually going wrong, we may need to reactivate this bug and fix the underlying MSBuild problem, but the diagnosability problem is in NuGet.

**Comment by rainersigwald** [comment]
This issue was moved to NuGet/Home#7202

**Comment by rainersigwald** [comment]
@denfromufa What happens if you try to run

```
/usr/lib/mono/msbuild/15.0/bin/msbuild /home/travis/build/pythonnet/pythonnet/pythonnet.sln
```

? That might have a clearer error.

**Comment by denfromufa** [comment]
@rainersigwald this command is causing the build error, how can I debug this in travis ci? I tried verbose flags, but this did not reveal the error.

'mono tools/nuget/nuget.exe restore pythonnet.sln -o packages'

**Comment by denfromufa** [comment]
@rainersigwald btw, the mono target of pythonnet solution was using xbuild in the previous builds, which seem to have auto-switched to msbuild recently.

**Comment by rainersigwald** [comment]
Those are questions for the NuGet bug I filed. They'll surely want to know the version of that `nuget.exe`.
