### ISSUE TITLE
When Exec action prints console output text "signtool error:" it causes msbuild to fail.

### ISSUE THREAD

**Issue by GitHubSachin** [Microsoft/msbuild#3622]
We have a custom batch script which is invoked in build by using Exec, recently we added some more verbose output in the batch script and discovered that if you print/echo magic sentence "SignTool error : An error occurred while attempting to sign", then the msbuild exit code becomes non success.
In this case we were just printing some troubleshooting info in the script without actually calling signtool
You can repro issue by just calling echo command as in example project below.

### Steps to reproduce

Either include a project sample, attach a zipped project, or provide IDE / CLI steps to create the project and repro the behaviour. Example of a project sample:

Project file
```xml
<Project
DefaultTargets="Build"
xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
<Target
Name="Build">

<Exec
Command="&quot;$(COMSPEC)&quot;
/d /c echo SignTool error : An error occurred while attempting to sign &amp; exit /b 0"
/>

</Target>
</Project>
```

Directory contents:
```
/
- a.cs
- b.cs
- dir/
     - c.cs
```

Command line
```
msbuild /bl
```
### Expected  behavior
Build should pass.

### Actual behavior
error MSB3073: The command ""C:\WINDOWS\system32\cmd.exe" /d /c
        echo SignTool error : An error occurred while attempting to sign & exit /b 0" exited with code -1.
     1>Done Building Project "D:\dev\home\sources\validate\msbuild\exec-task.proj" (default targets) -- FAILED.

### Environment data
`msbuild /version` output:
14.0.25123.0 and Latest 
OS info:
Windows 10 (Version 1803)
If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):

**Comment by rainersigwald** [comment]
By default `Exec` parses output for "standard" error and warning patterns, which match the form `error : `. You can avoid this by setting the task parameter `IgnoreStandardErrorWarningFormat="true"`.

**Comment by GitHubSachin** [comment]
So is the "SignTool error :" text part of "standard" error and warning pattern?

**Comment by rainersigwald** [comment]
Yes, it matches this part of the regex:

https://github.com/Microsoft/msbuild/blob/f77c70752e324864bf89efd346648cbb9ada6ba0/src/Shared/CanonicalError.cs#L68-L72

**Comment by GitHubSachin** [comment]
OK, got it. Thanks, looks like this is by design then, any custom scripts needs to be aware of this regex. Otherwise they will accidently make msbuild fail by printing something which matches this but its not error.
