### ISSUE TITLE
Microsoft.Cpp.props was not found

### ISSUE THREAD

**Issue by chippagiriSaiCharan** [microsoft/msbuild#3629]
[exec] Build FAILED.
     [exec] 
     [exec] "C:\BlrApps\ViewingInfra\Src\Viewing.sln" (Build target) (1) ->
     [exec] "C:\BlrApps\ViewingInfra\Src\ViewerSolution\Viewer\Viewer.csproj.metaproj" (default target) (14) ->
     [exec] "C:\BlrApps\ViewingInfra\Src\ViewerSolution\DXWrap\DXWrap.vcxproj" (default target) (15) ->
     [exec]   C:\BlrApps\ViewingInfra\Src\ViewerSolution\DXWrap\DXWrap.vcxproj(50,3): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.Cpp.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
     [exec] 
     [exec] 
     [exec] "C:\BlrApps\ViewingInfra\Src\Viewing.sln" (Build target) (1) ->
     [exec] "C:\BlrApps\ViewingInfra\Src\ApplicationUISolution\ApplicationUI\ApplicationUI.csproj.metaproj" (default target) (16) ->
     [exec] "C:\BlrApps\ViewingInfra\Src\ImageProcessing3DSolution\ImageProcessing3D\ImageProcessing3D.csproj.metaproj" (default target) (17) ->
     [exec] "C:\BlrApps\ViewingInfra\Src\Imaging3DSolution\Imaging3D\Imaging3D.csproj.metaproj" (default target) (18) ->
     [exec] "C:\BlrApps\ViewingInfra\Src\Algorithms\Managed\Algorithms.vcxproj.metaproj" (default target) (19) ->
     [exec] "C:\BlrApps\ViewingInfra\Src\Algorithms\Managed\Algorithms.vcxproj" (default target) (20) ->
     [exec]   C:\BlrApps\ViewingInfra\Src\Algorithms\Managed\Algorithms.vcxproj(52,3): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\**_Microsoft.Cpp.props" was not found_**. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
     [exec] 
     [exec] 
     [exec] "C:\BlrApps\ViewingInfra\Src\Viewing.sln" (Build target) (1) ->
     [exec] "C:\BlrApps\ViewingInfra\Src\DisplayWrapper\DisplayWrapper.vcxproj.metaproj" (default target) (56) ->
     [exec] "C:\BlrApps\ViewingInfra\Src\DisplayWrapper\DisplayWrapper.vcxproj" (default target) (57) ->
     [exec]   C:\BlrApps\ViewingInfra\Src\DisplayWrapper\DisplayWrapper.vcxproj(55,3): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.Cpp.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
     [exec] 
     [exec]     0 Warning(s)
     [exec]     3 Error(s)

**Comment by livarcocc** [comment]
This is entirely about the c++ props/targets it seems. This is not really the right repo for this issue. if this is still happening to you, please file a vs feedback item through visual studio.
