### ISSUE TITLE
The Project.DEPS.JSON files produced by VS and MSBUILD are different

### ISSUE THREAD

**Issue by IanHot** [Microsoft/msbuild#3645]
### Steps to reproduce
Having created some framework depended .net core projects and built them in both VS and MSbuild I get different DEPS.JSON files. VS produces deps file that contains relative file paths while msbuild appears to produce full paths. for example a VS entry looks like this

"runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl/4.3.0": {
        "runtimeTargets": {
          **"runtime/debian.8-x64/native/_._": {**
            "rid": "debian.8-x64",
            "assetType": "native"
          }
        }
 },

While the MSbuild entry look like this

"runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl/4.3.0": {
        "runtimeTargets": {
          **"runtimes/debian.8-x64/native/System.Security.Cryptography.Native.OpenSsl.so": {**
            "rid": "debian.8-x64",
            "assetType": "native",
        }
    }
},

If I use the MSbuild version of the JSON files the application fails to find assemblies when run on non windows platforms. 
IF I simply replace the MSbuild (DEPS.JSON) files with their VS counterparts the applications run on LINUX and MAC environments.

How do I get MSBuild to produce identical JSON file to VS?

I am using VS and MSBuild version 15.8.1. This did occur with 15.7.6 as well.

**Comment by IanHot** [comment]
[Xifintiq.Origami.DockerGrid.Manager.deps.json.MSBUILD.txt](https://github.com/Microsoft/msbuild/files/2310530/Xifintiq.Origami.DockerGrid.Manager.deps.json.MSBUILD.txt)
[Xifintiq.Origami.DockerGrid.Manager.deps.json.VS.txt](https://github.com/Microsoft/msbuild/files/2310532/Xifintiq.Origami.DockerGrid.Manager.deps.json.VS.txt)
I have now included the complete files just in case they are needed.

**Comment by rainersigwald** [comment]
This issue was moved to dotnet/sdk#2487
