### ISSUE TITLE
Referencing Assembly gets built even when Referenced Assembly's Public interface has not changed

### ISSUE THREAD

**Issue by geetmenon** [Microsoft/msbuild#3646]
Say, Project A has a reference to Project B in the same VS solution.

Scenario 1:  Project B's public interface changed.
Expected behavior: Project B should get built again and Project A should also get built.  
Observed behavior: Same as Expected behavior

Scenario 2: There was a logic change but not public interface change in Project B.
Expected behavior: Only Project B should get build. Project A should not. 
Observed behavior: Project B and Project A are both getting built again. This is incorrect.

Why is this? Is there a fix available or at least a workaround available for this issue?

**Comment by rainersigwald** [comment]
Does project A (or both projects) opt into reference-assembly creation by setting the property `<ProduceReferenceAssembly>true</ProduceReferenceAssembly>`? This is done by default in the .NET Core SDK (for both full framework and .NET Core/Standard-targeting projects) but is not enabled by default for existing projects.

If reference assemblies are enabled, more detailed repro steps would be appreciated.

**Comment by geetmenon** [comment]
This is a Visual Studio 2013 solution using .Net Framework 4.7. Is this Property  ProduceReferenceAssembly supported for this stack?

**Comment by rainersigwald** [comment]
No; it was introduced in Visual Studio 2017, version 15.3.

**Comment by geetmenon** [comment]
So is there any workaround for this issue?

**Comment by rainersigwald** [comment]
None that's worth investing the time into. You could conceivably create the reference-only assembly yourself and juggle the references to it, but that is difficult and very error-prone. I would recommend updating to 2017 where it's built in.
