### ISSUE TITLE
No final product was generated despite all projects were built successfully. 

### ISSUE THREAD

**Issue by ChinShengHao** [microsoft/msbuild#3649]
I'm facing a problem that when the projects were built successfully, no folder known as 15.0 was generated.
I might have missed some essential files or incorrect configuration steps that leads to this inconsistency in building.

### Steps to reproduce
1. Install Visual Studio 2017. Select the following Workloads:
    .NET desktop development
    .NET Core cross-platform development
2. Install the .NET Core 2.1 SDK.
3. Clone the source code (see above).
4. Open a Developer Command Prompt for VS 2017 prompt.
5. Build the code using the build.cmd script. This also restores packages needed to open the projects in Visual Studio.
6. Open MSBuild.sln in Visual Studio 2017.

### Expected  behavior
When build success, a folder known as 15.0 was generated containing the products.

### Actual behavior
When build success, no folder known as 15.0 was generated.

### Environment data
``` msbuild /version ``` output:

```
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

14.0.25420.1
```

```dotnet --info ``` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.401
 Commit:    91b1c13032

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.401\

Host (useful for support):
  Version: 2.1.3
  Commit:  124038c13e

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by ChinShengHao** [comment]
@rainersigwald 
Thank you for the reply, yes the folder named 15.0 I'm expecting is indeed locate in ``` artifacts\Debug\bootstrap\net46\MSBuild ```.

As per reason why I would expect a folder named 15.0: The first time I built the project (perhaps due to incorrect configuration steps), a folder named 15.0 was generated in the ``` msbuild ``` and not ``` artifacts\Debug\bootstrap\net46\MSBuild``` .

**Comment by livarcocc** [comment]
Closing as the question seem to have been answered. Besides that, we have moved to a significantly different build infra-structure.
