### ISSUE TITLE
GlobInfo uses excessive amount of memory

### ISSUE THREAD

**Issue by lifengl** [microsoft/msbuild#3668]
Based on some dump files collected by Svet, we noticed that GlobInfo we gathered from msbuild is bigger than expected, and in some traces, it uses 1.2% of the total heap.

The majority of those objects are RegEx objects.  CPS gathers GlobInfo from every projects, and uses it to watch directory changes.  Because the majority of the .Net Core project uses exactly the same globbing pattern, we hope those RegEx can be reused (or maybe a more efficient globbing matching logic can be used to replace RegEx), and we can have a much reduced memory usage for that structure.

**Comment by panopticoncentral** [comment]
@ladipro I just wanted to check -- did this get integrated to 16.7 before the cutoff, or is it going to be 16.8?

**Comment by ladipro** [comment]
@panopticoncentral yes, it is in 16.7.
