### ISSUE TITLE
CoreClr build uses targets designed for full framework

### ISSUE THREAD

**Issue by ValMenn** [Microsoft/msbuild#367]
GetFrameworkPaths & GetReferenceAssemblyPaths targets are used in CoreClr build. This causes build warnings and takes build time, but these targets are not needed for CoreClr build. The tasks that generate warnings can be disabled if TargetFrameworkMonitor is empty (built from TargetFrameworkIdentifier and TargetFrameworkVersion), but the moniker is used by some targets that need to run for CoreClr build and cannot currently be empty. The solution is to either use different property for the needed targets or to extend conditions of the unneeded tasks in Microsoft.Common.CurrentVersion.targets to have more control over the tasks we don't need.

**Comment by rainersigwald** [comment]
This is now semi-by-design, enabling targeting full framework with .NET Core MSBuild on Windows. We may wish to revisit it in the .NET Core 2.0 timeframe when addressing https://github.com/dotnet/sdk/issues/120.
