### ISSUE TITLE
Unable to associate MSBuild with custom cl bundle

### ISSUE THREAD

**Issue by ararunprasad** [Microsoft/msbuild#3768]
I have created a striped down version of Visual Studio build tools (Only CL & rest of its dependencies), I'm unable to compile the project using MSBuild.

I tried using `ClToolPath`, it picks the correct cl compiler, but it uses INCLUDE & LIB path from default Visual Studio path.

msbuild /p:ClToolPath="custom/cl/path" Foo.sln

Is there a way to pass system INCLUDE & LIB paths also to msbuild?

**Comment by rainersigwald** [comment]
The C++ tasks and targets aren't open source and don't live in this repo. The best way to get support for them is using the "send feedback" functionality in Visual Studio.

One note: please be careful with the licensing and redistribution of Microsoft software that isn't open source (like the C++ stuff).
