### ISSUE TITLE
ImportsBefore mechanism not working from System Account

### ISSUE THREAD

**Issue by dbolkensteyn** [Microsoft/msbuild#3781]
Might relate to #1830

The ImportsBefore file is not being picked up when MSBuild is launched using the System Account. From a user account, it works as expected.

The properties all seem correct with respect to what [Microsoft.CSharp.CurrentVersion.targets#L27](Microsoft.CSharp.CurrentVersion.targets#L27) expects, as shown during a `/v:diag` build:
```
MSBuildToolsVersion = 15.0
MSBuildUserExtensionsPath = C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\MSBuild
MSBuildVersion = 15.8.168
ImportUserLocationsByWildcardBeforeMicrosoftCSharpTargets = true
```

### Steps to reproduce

1. Run [`psexec -i -s cmd.exe`](http://download.sysinternals.com/files/PSTools.zip)
2. `"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe" C:\Project\Project.csproj`

Project file 
- `C:\Project\Project.csproj`
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildBinPath)\Microsoft.CSharp.targets" />
</Project>
```

ImportsBefore files (duplicated)
- `C:\Users\%USERNAME%\AppData\Local\Microsoft\MSBuild\15.0\Microsoft.Common.targets\ImportBefore\Test.targets`
- `C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\MSBuild\15.0\Microsoft.Common.targets\ImportBefore\Test.targets`
```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="MyImportBeforeTarget" BeforeTargets="CoreCompile">
    <Error Text="ImportsBefore feature is working as expected." />
  </Target>
</Project>
```

### Expected  behavior
```
"C:\Project\Project.csproj" (default target) (1) ->
(MyImportBeforeTarget target) ->
  C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\MSBuild\15.0\Microsoft.Common.targets\ImportBefore\Test.targets(3,5): error : ImportsBefore feature is working as expected. [C:\Project\Project.csproj]
```

### Actual behavior
```
"C:\Project\Project.csproj" (default target) (1) ->
(CoreCompile target) ->
  CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point [C:\Project\Project.csproj]
```

### Environment data
`msbuild /version` output:
```
Microsoft (R) Build Engine version 15.8.168+ga8fba1ebd7 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

15.8.168.64424
```

OS info:

* windows-1803-core
* https://download.visualstudio.microsoft.com/download/pr/12210059/e64d79b40219aea618ce2fe10ebd5f0d/vs_BuildTools.exe with full install

**Comment by dbolkensteyn** [comment]
Digging a bit further into this: This indeed is related to #1830

According to the [WoW64 Wikipedia article](https://en.wikipedia.org/wiki/WoW64), the `%SystemRoot%\system32` folder is transparently translated into `%SystemRoot%\SysWoW64` for 32-bits processes running on 64 bits Windows.

Hence, by placing the `Test.targets` file into  the `C:\Windows\SysWOW64\config\systemprofile\AppData\Local\Microsoft\MSBuild\15.0\Microsoft.Common.Targets\ImportBefore` folder, it does get picked up by MSBuild.

The same Wikipedia article also mentions that 32 bits applications can access the native `%SystemRoot%\system32` under `%SystemRoot%\sysnative`.

So, I could copy my targets file to 32 bits path for MSBuild to find, but MSBuild could also look for target files under the 64-bits path.

WDYT @rainersigwald ?

**Comment by rainersigwald** [comment]
> On my side I personally believe that the current behaviour is in fact acceptable. The integration is a bit complicated due to WoW64, and it's probably not MSBuild's role to attempt to fully abstract away those tiny details.
> 
> WDYT @rainersigwald ?

That's my position as well. I would rather not run code in every build to detect the relatively-rare running-as-System case, especially when the code would be working around intentional Windows behavior (even if I don't like that behavior). We get reports on this occasionally, which I'd like to fix, but changing the behavior in MSBuild-owned file accesses wouldn't fix everything--for example, you could write a file from 32-bit MSBuild and try to read it from a 64-bit process, and there's nothing we could do to fix that.
