### ISSUE TITLE
Support multiple entry points in the ProjectGraph

### ISSUE THREAD

**Issue by dfederm** [Microsoft/msbuild#3795]
For some programmatic API scenarios, multiple entry points would be required.

Command-line still only has the ability to provide one file though, so this is purely for consumers of the ProjectGraph API.

Example scenario: "Open folder" (no sln), or constructing a graph for an entire repo which doesn't have a root-level traversal project.

A possible alternative would be to "fake" a project which simply has `<ProjectReference Include="**\*.*proj" />` as the entry point, but allowing multiple entry points instead is more flexible.

**Comment by rainersigwald** [comment]
Counterpoint: MSBuild.exe has never had this, and VS mostly hasn't either ("open folder" is new and doesn't really work the same way). I think this should be cut at least for v1.
