### ISSUE TITLE
Add support for building on Mac

### ISSUE THREAD

**Issue by AndyGerlicher** [Microsoft/msbuild#38]
After Linux support, we need to add support for building on Mac (under mono).

**Comment by nathanaeljones** [comment]
TravisCI has a waiting list for mac build runners; I'd go ahead and contact them to get on the list. Took us about 45 days to get our repo(s) activated for mac tests.

**Comment by akoeplinger** [comment]
@nathanaeljones the existing [Jenkins CI](http://dotnet-ci.cloudapp.net/computer/) already has mac and linux workers.

**Comment by nathanaeljones** [comment]
Nice! Does it build pull requests automatically?

**Comment by akoeplinger** [comment]
Yes: http://dotnet-ci.cloudapp.net/job/microsoft_msbuild_prtest/ (it's just not hooked up to the mac and linux workers yet)

**Comment by nathanaeljones** [comment]
Is there a guide for people who want to run CI against their own fork?

**Comment by akoeplinger** [comment]
@nathanaeljones I don't understand? You can do whatever you want in your fork, including setting up your own CI.

**Comment by nathanaeljones** [comment]
Of course, but in practice it can be difficult to get a CI server set up to mirror the official version. The beauty of supporting Travis and AppVeyor is that the user only needs to flip a switch on their accounts, and their fork is automatically building. While my company could use a dedicated CI server, our users are better served by us maintaining .travis.yml and appveyor.yml files, as they can fork and experiment without losing the crucial benefit of CI. Of course, all of our projects are public OSS, so there aren't many downsides.

**Comment by akoeplinger** [comment]
Hmm, yeah that's a valid point, but in practice I think it's not that difficult to set up your own CI as this repo has very few dependencies (i.e. cloning the repo and running build.cmd should be enough).

**Comment by AndyGerlicher** [comment]
MSBuild team triage: Closing because Mac support is now in. Eventually we'd like to get Mac CI support, but Linux will come first.
