### ISSUE TITLE
Make BuildEventArgsReader public

### ISSUE THREAD

**Issue by daveaglick** [Microsoft/msbuild#3813]
Now that binlog is shipped in-the-box and awareness is improving, it would be nice to be able to use the MSBuild APIs to playback binlog files. All the functionality is there in `BuildEventArgsReader` but it's `internal`. Would you be willing to take a PR changing `BuildEventArgsReader` to `public`?

cc @KirillOsenkov

**Comment by rainersigwald** [comment]
I would, unless @KirillOsenkov has some objection.

**Comment by daveaglick** [comment]
Done!

FWIW, this was the only thing [I found tricky](https://github.com/daveaglick/MsBuildPipeLogger/blob/master/src/MsBuildPipeLogger.Server/BuildEventArgsReaderProxy.cs) about reading the binary log format from code.

Writing serialized binary log events was more difficult, and required copying over code from https://github.com/KirillOsenkov/MSBuildStructuredLog since there's a lot more involved with that and most of the supporting helpers are `internal`. I don't think it's necessary to make serialization support `public` though - my use case was pretty niche and I can't see many folks wanting to write binary logs themselves.

**Comment by rainersigwald** [comment]
Yeah, I don't think I'm too interested in helping write arbitrary log files at the moment. But reading them makes total sense.

Removing up-for-grabs since the PR is out.
