### ISSUE TITLE
New msbuild package update on Ubuntu crashes environment

### ISSUE THREAD

**Issue by mvodanovic** [Microsoft/msbuild#3829]
### Steps to reproduce

I have an Ubuntu environment for my .NET Core 2.1 project. Today apt reported there are some updates available. After upgrading my environment broke, failing to load projects in the solution.

These packages were updated: mono-llvm-tools msbuild msbuild-sdkresolver

This is the error given:
Project 'MyProject' load failed: The SDK 'Microsoft.NET.Sdk.Razor' specified could not be found.

That SDK is referenced in 2 files:
/usr/lib/mono/msbuild/15.0/bin/Sdks/Microsoft.NET.Sdk.Web/Sdk/Sdk.props
/usr/lib/mono/msbuild/15.0/bin/Sdks/Microsoft.NET.Sdk.Web/Sdk/Sdk.targets
As a workaround I commented out a reference to that SDK in those files and now my environment is working again.

I don't know if it's a mono or msbuild issue. The only thing I know is that it was working before the update of those packages and stopped working afterwards. Nothing else changed.

Version info:

Setting up mono-llvm-tools (3.6.0+mono201805011452-0xamarin1+ubuntu1804b1) ...                                                                                           
Setting up msbuild-sdkresolver (1:15.8+xamarinxplat.2018.07.31.22.43-0xamarin5+ubuntu1804b1) ...                                                                         
Setting up msbuild (1:15.8+xamarinxplat.2018.07.31.22.43-0xamarin5+ubuntu1804b1) ... 

Mono JIT compiler version 5.14.0.177 (tarball Mon Aug  6 09:07:45 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          yes(3.6.0svn-mono-/)
        GC:            sgen (concurrent by default)

Microsoft (R) Build Engine version 15.1.8.0 ( Wed Sep  5 19:27:37 UTC 2018) for Mono

**Comment by rainersigwald** [comment]
@radical Can you take a look? I'd expect the `msbuild-sdkresolver` package to include the NuGet SDK resolver, but I don't actually know the Mono distribution details.

**Comment by nguerrera** [comment]
It would not be expected to use the NuGet SDK resolver to find Microsoft.NET.Sdk.Razor. It is a depdency of Microsoft.NET.Sdk.Web. What's happening here is that resolution has fallen back to the default Sdk resolver, which found a default web sdk without its razor sdk dependency. If mono msbuild bundles web sdk for use without .NET Core SDK, it needs to also bundle the razor sdk.

See also https://github.com/OmniSharp/omnisharp-vscode/issues/2604#issuecomment-430046231

**Comment by akoeplinger** [comment]
Hmm I thought we're bundling Razor (https://github.com/mono/msbuild/blob/105cb8a15778bf32efa730b5125d1503e5b44629/mono/build/SdkVersions.txt#L4) but I indeed don't see it in my Mono install.

**Comment by nguerrera** [comment]
Does a Mono install normally carry Microsoft.DotNet.MSBuildSdkResolver?

FWIW, we are moving in the opposite direction in VS where we will not be putting any SDKs in the default MSBuildSdksPath.

See https://github.com/dotnet/cli/issues/6795

The problem with the default resolver is that it hides errors with the .NET Core SDK resolver, and it's very hard to diagnose. 

I suspect that some of the folks seeing razor failures are first having a hidden failure to resolve from .NET Core SDK, and then seeing that the default location doesn't have Razor as the only error message.

**Comment by akoeplinger** [comment]
Yes we do ship the Microsoft.DotNet.MSBuildSdkResolver cause afaik it was the only way to get SDK style projects to work.

I'm not really deeply familiar with all of this though, @radical would be the subject matter expert (but he is out till end of this month).

**Comment by marchy** [comment]
Any updates on this @radical / @akoeplinger?

Would be great to see this resolved, all our web projects are broken due to this.

**Comment by rainersigwald** [comment]
Closing since @marchy reported it fixed.
