### ISSUE TITLE
MSBuildAssemblyVersion is reporting "Current" instead of the version

### ISSUE THREAD

**Issue by joj** [Microsoft/msbuild#3882]
In the latest versions of MSBuild the MSBuildAssemblyVersion property is reporting Current. This is not very useful, but it also may break existing targets that compare the version to a number (Current cannot be compared to a number). I'm not sure when this started but @rainersigwald thinks it may have to do with changing ToolsVersion to Current.

**Comment by kzu** [comment]
@rainersigwald would this automatically fix all these props? (binpath, toolspath, etc.)

![image](https://user-images.githubusercontent.com/169707/48142250-3312c600-e28b-11e8-8f5f-4c93a50f9066.png)

**Comment by kzu** [comment]
Also, do we know when this is going to be inserted in dev16?

**Comment by rainersigwald** [comment]
@kzu This should be in preview 1 builds (I see it in your screenshot there: `MSBuildAssemblyVersion` is `16.0`).

What do you mean by 

> fix all these props? (binpath, toolspath, etc.)

? They look like they're correctly set to me.

**Comment by kzu** [comment]
Oh.. I see! So the actual path *on disk* of MSBuild.exe is now under *Current\Bin*!

It's working great for me in that build, yes 👍
