### ISSUE TITLE
Update xplat to use Roslyn compiler

### ISSUE THREAD

**Issue by AndyGerlicher** [Microsoft/msbuild#39]
Currently using the mono C# compiler. Tasks/Targets need to be updated to use Roslyn.

**Comment by migueldeicaza** [comment]
This probably should be an option until the new debug format becomes available, as currently Roslyn does not produce debug symbols on Unix (or when Portable PDB gets merged, there are yet no consumers for it)

**Comment by jaredpar** [comment]
@migueldeicaza good point. Suggestions welcome on the name.  My immediate reaction was to make it `/p:Compiler=Mono`

**Comment by dsplaisted** [comment]
Removed the CoreCLR label since the .NET Core build does use Roslyn

**Comment by rainersigwald** [comment]
Long done.
