### ISSUE TITLE
Ubuntu and OSX CIs fail at DNU restore

### ISSUE THREAD

**Issue by cdmihai** [Microsoft/msbuild#390]
The current bar for Ubuntu and OSX CIs is to pass compilation without running any tests. However, both CIs fail at DNU restore.

On my OSX instance (10.11) DNU restore succeeds. I also tried Nuget 3.3.0, but it still freezes while restoring.

**Comment by rainersigwald** [comment]
Just to be clear:  we do want to pass tests cross-platform as well.  But the immediate goal is to ratchet up the CI process by making sure builds work.  After that's tested and guarded against regressions, we can start tackling tests.

**Comment by cdmihai** [comment]
fixed in #404
