### ISSUE TITLE
Can I Pack  multi-packages for multi-target project 

### ISSUE THREAD

**Issue by moh-hassan** [Microsoft/msbuild#3903]
I have multi-target project     

                 <TargetFrameworks>net45;netcoreapp2.1</TargetFrameworks>   
            
I try to generate multi-package one per framework using the following xml:

                 	<Choose>
			<When Condition="'$(TargetFramework)' == 'net45'">
			  <PropertyGroup>
				<PackageId>MyPackage.net45</PackageId>
				<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
			  </PropertyGroup>
			  
			</When>
			<When Condition="'$(TargetFramework)' == 'netcoreapp2.1'">
			  <PropertyGroup>
				<PackageId>MyPackage.NetCore</PackageId>
                                 <PackAsTool>true</PackAsTool>
				<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
			  </PropertyGroup>

			</When>
		  </Choose>

only one package with the name `PackageId`  for both targets is generated.
msbuild ignore the `PackageId`  in the `<choose> <when>` statement.

Why msbuild ignored the packageid in the   `<chose>` statement ?
Is'it possible to have such a scenario  for generating multi packages: one per framework?

I want to distribute two different packages one for net45 and the other as a global tool in netcoreapp2.1

**Comment by rainersigwald** [comment]
This issue was moved to NuGet/Home#7463
