### ISSUE TITLE
ProjectExtensionsElement doesn't do correct comparison for new and old value

### ISSUE THREAD

**Issue by PavelUstinovMS** [Microsoft/msbuild#3904]
### Steps to reproduce

1. Open Web Application project (ASP .NET Web Application (.NET Framework)) (or create if you don't have one)
2. Add new class to this project
3. Click "Save All" button.
4. Close VS

### Expected  behavior
<project>.csproj.user file is not updated after this operation.

### Actual behavior
<project>.csproj.user file is updated after this operation.

### Where problem is?
The problem is in the [ProjectExtensionsElement.cs](https://github.com/Microsoft/msbuild/blob/master/src/Build/Construction/ProjectExtensionsElement.cs) code in the method 'public string this[string name].set()' in this line:
if (idElement.InnerXml != value)

Here we compare serialized value of Xml in memory and new value. If it is the same we do nothing, otherwise we overwrite new value and mark node as a 'dirty' which causes re-write *.user file. Comparison is not correct, because InnerXml also adds schema information in the serialized string, but 'value' doesn't have this information. In this case this condition always 'true', even though XMLs are the same. Example:

**InnerXml**: `<FlavorProperties GUID="{349c5851-65df-11da-9384-00065b846f21}" xmlns="http://schemas.microsoft.com/developer/msbuild/2003"><WebProjectProperties><StartPageUrl></StartPageUrl><StartAction>CurrentPage</StartAction> .... and so on`

**Value**: `<FlavorProperties GUID="{349c5851-65df-11da-9384-00065b846f21}"><WebProjectProperties><StartPageUrl></StartPageUrl><StartAction>CurrentPage</StartAction>.... and so on`

**Comment by rainersigwald** [comment]
Fallout from #699, probably, same as #1457 (but more severe).
