### ISSUE TITLE
[Question] - Pack Native dependencies

### ISSUE THREAD

**Issue by deinok** [Microsoft/msbuild#3909]
Hi, I'm searching the internet for this information, trying to reproduce what other libs, etc.. But I can't find a way to do the following:

Imagine that I want to create library for https://github.com/intel-iot-devkit/mraa
So I create a netstandard2.0 called `Mraa.runtime.linux-arm` that just have a a folder like this `runtimes/linux-arm/native/` and inside that folder I put the generated libmraa.so for linux-arm

Inside `Mraa.runtime.linux-arm.csproj` is something like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RuntimeIdentifier>linux-arm</RuntimeIdentifier>
		<TargetFramework>netstandard2.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<Content CopyToOutputDirectory="PreserveNewest"
			Include="runtimes/linux-arm/native/**/*"
			Pack="true"
			PackagePath="runtimes/linux-arm/native/"/>
	</ItemGroup>

</Project>
```

But due the fact that I have to support diferent RIDs I create a `Mraa.runtime.linux-x64` with the same aproach but for `linux-x64`, and the list could continuate for diferent RIDs

Now, I create a `Mraa.runtimes` that just referenciate all the specific RIDs, like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Mraa.runtime.linux-x64.csproj" />
		<ProjectReference Include="..\Mraa.runtime.linux-arm.csproj" />
                <!--Other runtimes-->
	</ItemGroup>

</Project>
```

What I'm doing wrong?
I expect that when working with OS Any and Arch Any, unpack everything.
If publish with Os Any and Arch Any, unpack everything.
If a project have <RuntimeIdentifiers> just unpack that required runtimes.
If publish with --runtime linux-arm just publish the linux-arm *.so
Also, can I pack inside `runtime/<rid>/native/` executable files, like *.exe, *.py, *.ps1, *.cmd, *.sh?

Can somebody point me to a standard documentation, or a convention?

**Comment by rainersigwald** [comment]
This issue was moved to NuGet/Home#7479
