### ISSUE TITLE
Property value is not cached for build (VersionSuffix)

### ISSUE THREAD

**Issue by skarllot** [microsoft/msbuild#3913]
### Steps to reproduce

I use dynamic `VersionSuffix` to automatically build (CI) the pre-release packages, as defined below:

Project file
```xml
<Project>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <VersionSuffix>pre$([System.DateTime]::UtcNow.ToString(yyyyMMdd-HHmm))</VersionSuffix>
  </PropertyGroup>
</Project>
```

### Expected  behavior
The property value be evaluated once and cached for entire build.

### Actual behavior
The property value is not cached causing evaluation for every usage.
The problem arises when there are multiple projects on same solution that depends of each other, causing impossible to resolve dependencies.

```xml
<package>
  <metadata>
    <id>Verion.Presentation.View</id>
    <version>1.0.0-pre20181107-1458</version>
  </metadata>
</package>
```

```xml
<package>
  <metadata>
    <id>Verion.Presentation.View.XamarinForms</id>
    <version>1.0.0-pre20181107-1459</version>
    <dependencies>
      <group targetFramework=".NETStandard2.0">
        <dependency id="Verion.Presentation.View" version="1.0.0-pre20181107-1459" exclude="Build,Analyzers" />
      </group>
    </dependencies>
  </metadata>
</package>
```

**Comment by skarllot** [comment]
This issue will be revised or should I close?

**Comment by rainersigwald** [comment]
Can you clarify under what circumstances you expect the value to be cached, and what you mean by "cached"? I don't think I understand the problem you're describing.

Can you also describe how you're building the projects?

**Comment by skarllot** [comment]
The problem is found when the solution build take more than few seconds and has multiple projects.
Because each project evaluates the `VersionSuffix` variable instead of being evaluate once for entire solution.
If when building the first project the time is "10:30" and the second project the time is "10:31" it results the second project depending on first project on version "1.0.0-pre20191114-1031" that does not exist.

**Comment by rainersigwald** [comment]
And how and where do you define `VersionSuffix`? It's expected that each project gets its own copy of the variable (and may experience a different time).

The usual solution to this problem is to set a timestamp outside the build (in a script or CI system), or to have references to a single project that evaluates once and returns the value to other projects.

**Comment by skarllot** [comment]
I define the `VersionSuffix` on `Directory.Build.props`.

Currently I defining the timestamp outside the build as a workaround of this problem.

**Comment by rainersigwald** [comment]
`Directory.Build.props` is imported into each project individually, so you’re seeing the expected behavior.
