### ISSUE TITLE
error MSB4057: The target "Restore" does not exist in the project in Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe

### ISSUE THREAD

**Issue by jeanfrancoislarente** [Microsoft/msbuild#3932]
### Steps to reproduce

Using CakeBuild 0.28 
Running Build Solution .WithRestore()

Works perfectly with `Microsoft (R) Build Engine version 15.8.169+g1ccb72aefa` (15.8.169.51996)
Fails with title error with `Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe` (15.9.20.62856)
```
Task("Build-Solution")
.Does(() => {
    MSBuild(configuration.SolutionFile, cfg => InitializeMSBuildSettings(cfg));
});
```

For completeness, settings:
```
public MSBuildSettings InitializeMSBuildSettings(MSBuildSettings settings)
{
    settings.SetConfiguration(configuration.BuildConfiguration)
            .SetVerbosity(Verbosity.Minimal)
            .SetMSBuildPlatform(MSBuildPlatform.Automatic)
            .SetPlatformTarget(PlatformTarget.MSIL)
            .UseToolVersion(configuration.MSBuildToolVersion)
            .WithRestore();
    return settings;
}
```

**Comment by rainersigwald** [comment]
Can you reproduce outside of Cake? Can you collect additional logging?

**Comment by jeanfrancoislarente** [comment]
My bad...

I was typing my detailed response with log snippets, etc and typed the following sentence which of course was a facepalm moment for me.

> I *only* have MSBuild Tools for VS 2017 installed on the machine (download installer, click Install - no other options)

So - no NuGet targets or Package Management tools installed.

Installed those missing components and we're off to the races. Thanks for the reply @rainersigwald and apologies for the bother!
