### ISSUE TITLE
`ProjectStartedEventArgs.ParentBuildEventContext` should report the `TaskId` of the respective parent MSBuild `TaskStarted` event

### ISSUE THREAD

**Issue by MarkKharitonov** [microsoft/msbuild#3939]
Having just the `NodeId` and `Project{Instance,Context}Id` does not help to disambiguate the parent-child relationship in many cases.

**Comment by rainersigwald** [comment]
Can you elaborate? In what scenario do you need the more-detailed information?

**Comment by MarkKharitonov** [comment]
I am preparing a detailed response. Thank you for your patience.

**Comment by KirillOsenkov** [comment]
I think what Mark says makes sense. If a build was started by the MSBuild task, it would indeed be useful to have the task ID of that parent MSBuild task.

@MarkKharitonov I'm guessing at this point you have the most knowledge of us all about this problem. Would you consider preparing a PR that implements your proposal? This way you could test and see if it solves your problem.

**Comment by KirillOsenkov** [comment]
cc @panopticoncentral since I know you were looking at parenting project builds under their corresponding MSBuild task.

**Comment by MarkKharitonov** [comment]
Guys, I do not know the code. With my current time constraints it would take me a very long time to figure out how to do it.

**Comment by KirillOsenkov** [comment]
No problem, just setting your expectation that it'll likely take the team a long time too :| Sorry about that.

**Comment by panopticoncentral** [comment]
Yes, if you look at https://github.com/dotnet/project-system-tools/blob/master/src/LogModel/Builder/ModelBuilder.cs, the function ConnectBuildTasks tries to heuristically connect a project build to the parent MSBuild (or GenerateTemporaryTargetAssembly for XAML) task. It's kind of fragile, so this information would be helpful, maybe I'll see if I can propose a fix at some point (may take a while), though.

**Comment by MarkKharitonov** [comment]
Guys, please have a look at https://github.com/Microsoft/msbuild/pull/4142

**Comment by MarkKharitonov** [comment]
Anyone?

**Comment by KirillOsenkov** [comment]
Hi Mark, we saw your PR and will get to it as soon as we can. Thanks!

**Comment by MarkKharitonov** [comment]
Thank you.

**Comment by MarkKharitonov** [comment]
Guys, any chances this will be done?
We cannot visualize msbuild builds without it.

**Comment by rainersigwald** [comment]
Ah, we marked the PR but not this bug. My plan is to find time in the next month or so to dig into the repercussions of the PR and either accept it or try to devise a new solution.

**Comment by MarkKharitonov** [comment]
@rainersigwald - thank you so much. Looking forward.

**Comment by KirillOsenkov** [comment]
@MarkKharitonov thanks for your patience. I've finally had time to play with your change and I've convinced myself that it's a good one that we should take as-is. I've rebased it to latest and added a unit-test here:
https://github.com/microsoft/msbuild/pull/5013

@rainersigwald @livarcocc please consider taking this for 16.5. It would be a serious improvement for viewing binlogs. Many people have been asking for this. Thanks!

**Comment by KirillOsenkov** [comment]
I've already made the binlog viewer change, in anticipation: https://github.com/KirillOsenkov/MSBuildStructuredLog/commit/78aff51e941f1fb7fcada9d2c612dac03c754e09

It will light up magically once this is shipped.
