### ISSUE TITLE
VS2015 Update 1 - %(RelativeDir) transform returning full paths (instead of relative paths)

### ISSUE THREAD

**Issue by nicholashead** [Microsoft/msbuild#395]
Not sure where to file this. I filed it on Microsoft Connect already, and I've spent a few days diagnosing/pulling my hair out on it. We have a .csproj that builds just fine pre-VS2015 Update 1. After Update 1 is installed, the build fails. We have "copy" commands in the project file that are copying files to an output directory, and they use the `%(RelativeDir)` transform. It appears instead of returning a relative path, it's returning a full path now (causing the build to fail).

Any help would be appreciated, or point me in the right direction!

**Comment by rainersigwald** [comment]
We got a similar report internally but I'm still waiting on follow-up from the person who reported it.  Can you post a repro project somewhere?  Even sharing just the .csproj file as a gist should be instructive.

The internal report project uses `Microsoft.WebApplication.targets` and has problems copying a `Content` item.  Is that the same for you?

(A trivial project that uses `RelativeDir` seems to be fine and our tests continue to pass, so I suspect that something outside of the implementation of `RelativeDir` itself is the problem.  Unfortunately, that doesn't narrow it down much so we still need help reproducing the issue to figure out what's wrong.)

**Comment by nicholashead** [comment]
@rainersigwald thanks for replying! I will work on a repo project, but to answer your question, yes it does reference that target:

```xml
<Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v14.0\WebApplications\Microsoft.WebApplication.targets" />
```

And here's the portion of our `.csproj` that is failing:

```xml
<PropertyGroup>
    <ProjectDir Condition=" '$(ProjectDir)' == '' ">$(MSBuildProjectDirectory)\</ProjectDir>
    <IntermediateDir>$(SolutionDir)deploy\_Packages\$(ProjectName)\</IntermediateDir>
  </PropertyGroup>
<PropertyGroup>
    <BuildDependsOn>
	      BeforeBuild;
		  CompileTypeScript;
    </BuildDependsOn>
  </PropertyGroup>
<Target Name="Build" DependsOnTargets="$(BuildDependsOn)">
    <ItemGroup>
      <NewIntermediateFiles Include="@(Content)" />
      <NewIntermediateFiles Include="@(ScssFile)" />
      <OldIntermediateFiles Include="$(IntermediateDir)**\*.*" />
      <DeleteIntermediateFiles Include="@(OldIntermediateFiles)" />
      <DeleteIntermediateFiles Remove="@(NewIntermediateFiles->'$(IntermediateDir)%(RelativeDir)%(Filename)%(Extension)')" />
    </ItemGroup>
    <Delete Files="@(DeleteIntermediateFiles)" />
    <Copy SourceFiles="@(NewIntermediateFiles)" DestinationFiles="@(NewIntermediateFiles->'$(IntermediateDir)%(RelativeDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>
```

Specifically, that last `<Copy>` statement is spitting out a full path for `%(RelativeDir)` instead of a relative one, causing the copy to fail with an error message.

**Comment by nicholashead** [comment]
@rainersigwald https://github.com/Microsoft/TypeScript/issues/5894 appears to be the real issue

**Comment by rainersigwald** [comment]
That does look convincing!  Thanks for following up; I've passed that bug along to the internal reporter as well.

**Comment by nicholashead** [comment]
Thanks. We definitely deploy compiled TypeScript and that's exactly what is failing during the copy. But it appears no other file types are failing. So it most likely does seem to be a bug with TypeScript. Thanks again.
