### ISSUE TITLE
Feature Request: AppDomain option for UsingTask

### ISSUE THREAD

**Issue by kjkrum** [Microsoft/msbuild#3951]
I'm developing a code generation tool. It's working in the form of a console app that's invoked via `Exec`. I explored making it a custom MSBuild task, but I'm running into the old issue where [Visual Studio locks the task assembly](https://stackoverflow.com/questions/3371545/visual-studio-2008-locks-custom-msbuild-task-assemblies), preventing the target project from being built more than once. There are some messy workarounds discussed in that Q&A, but I haven't had any success with them.

My understanding is that Visual Studio has an app domain that persists between builds. Either this is the [neutral app domain](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-unload-an-application-domain) that cannot be unloaded, or some other app domain that either cannot be unloaded or just isn't. In any case, when `UsingTask` loads the task assembly, it gets loaded into that persistent app domain. The next time you try to build, `UsingTask` tries to copy the .dll again and finds it locked.

I *think* the solution would be for `UsingTask` to have some option that tells it to load the task assembly in an unloadable app domain. Am I on the right track, and would this be feasible?

**Comment by kjkrum** [comment]
@rainersigwald From a comment on the top rated answer on that Q&A:

> I don't see how extending AppDomainIsolatedTask is supposed to work in this situation, since MSBuild has already loaded the assembly in the primary AppDomain by the time it tries to read the types.

In any case, extending `AppDomainIsolatedTask` was one of the first things I tried, and it did not solve the problem. But other attempted fixes may have interfered, so I'll try again with a fresh new project.

**Comment by kjkrum** [comment]
@rainersigwald Confirmed that extending `AppDomainIsolatedTask` does not solve the problem. However, there may be something else going on. If the target project (the one invoking the custom task) ever fails to build for any reason, then neither the target project nor the project containing the task can be rebuilt because the .dll is locked by a zombie MSBuild. Sometimes it's also locked by VS, seemingly at random.

Also, when I was working on this a couple days ago, I was invoking the custgom task with the target `<Target Name="Whatever" BeforeTargets="Build">`. I've changed nothing, but now `Build` does not work - my task is simply not invoked. I have to use `PrepareForBuild`, which causes all sorts of other problems.

MSBuild is truly bizarre. People say Maven is complicated, but I've never spent more than a couple hours getting it to do absolutely anything I want. I'm going on two weeks with this MSBuild insanity.

**Comment by kjkrum** [comment]
I found a blog post by a MS employee from another team explaining how to use custom MSBuild tasks. SO Q&As and the practically non-existent documentation led me down some wrong paths. I'm still running into problems with MSBuild semi-randomly not exiting and keeping the .dll locked, but I don't think it's just old bugs, not anything to do with app domains or node reuse as everyone seems to think, so I'm closing this issue.

**Comment by Inirit** [comment]
@kjkrum Can you please elaborate a bit on your latest comment, or maybe just provide a link to the blog post you mentioned? I'm also having problems with Visual Studio holding a lock on my custom task dll and I'm tearing my hair out trying to coerce it into behaving.

**Comment by kjkrum** [comment]
@Inirit My main reason for wanting to use an MSBuild task in the first place was nicer logging. I haven't tried it yet, but [MSBuild / Visual Studio aware error messages and message formats](https://blogs.msdn.microsoft.com/msbuild/2006/11/02/msbuild-visual-studio-aware-error-messages-and-message-formats/) might render that moot.
