### ISSUE TITLE
Fails building RESX when it contains a 3rd party type not present in GAC or HintPath, but present through NuGet packageReference

### ISSUE THREAD

**Issue by MihaMarkic** [Microsoft/msbuild#3955]
### Steps to reproduce

This is a .NET Framework 4.6.1 WinForms project.
Use a 3rd party library that injects its types into RESX file. In my case I use Developer Express WinForms suite. Everything is fine while DevExpress assemblies are in GAC and probably also works when they are accessible through a HintPath.
However, it doesn't work when NuGet feed is used for DevExpress packages (in my case also packageReference is used).

RESX file excerpt
```xml
<assembly alias="DevExpress.Utils.v18.1" name="DevExpress.Utils.v18.1, Version=18.1.7.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" />
  <data name="imageCollection.ImageStream" type="DevExpress.Utils.ImageCollectionStreamer, DevExpress.Utils.v18.1" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        SOMEVALUEHERE
</value>
  </data>
```
Command line
```
MSBuild.exe /v:minimal /p:Configuration="Release" /target:Build "PATH/MYSOLUTION.sln" /m
```
### Expected  behavior

MSBuild should find the reference to DevExpress.Utils.v18.1 assembly through NuGet location.

### Actual behavior

Build fails with
SOMEPATH\FILE.resx(133,5): error MSB3103: Invalid Resx file. Type DevExpress.Utils.ImageCollectionStreamer, DevExpress.Utils.v18.1, Version=18.1.7.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a in the data at line 127, position 4 cannot be located. Line 133, position 5. [PATH\PROJECT.csproj]

### Environment data

MSBuild is run from 'Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin/amd64'.

### Possible workaround

Is there a way to let MSBuild know the path of said assembly through arguments as a workaround for now?

**Comment by MihaMarkic** [comment]
After experimenting and digging into this error I found out that it's a wrong and misleading error. The real error was in solution configuration but it was manifesting, oddly, as the error mentioned in the post above. Oh, well.

**Comment by albigi** [comment]
@MihaMarkic any chance you remember what was the issue in the end? Getting the same problem here at the moment.
Thanks in advance

**Comment by MihaMarkic** [comment]
@albigi I wish I was younger :) Check out if all projects in solution are checked for building. Also create a minimal repro project (which would build I assume) and compare the csproj files.

**Comment by svenschmidt75** [comment]
In case someone else hits this one: For me it was caused by the fact that I referenced a netcore DevExpress package in a .NET 4.7 framework app. I founds this after many hours by looking at the references passed to resgen.exe during the build process (set verbosity to detailed). Not at all obvious from the original error message...
