### ISSUE TITLE
Keep msbuild server around (/m) on .NET Core?

### ISSUE THREAD

**Issue by xoofx** [Microsoft/msbuild#3963]
Hey,

This is a question about msbuild with multiple build node. Today when we are issuing a `dotnet build` on Linux, it takes more than 1 second to complete even if nothing has changed in a csproj.
If I remember, there is a server mode for msbuild and it doesn't seem to be used for .NET Core, is it correct?

What is preventing msbuild to bring support for that? Is it AppDomains? Would a version using collectible AssemblyLoadContext work in this case? How much work would it be to bring such support?

**Comment by dasMulli** [comment]
This should already be used by default by `dotnet build`. You can disable it by adding `-m:1`.
The .NET Core SDK also provides a CLI for shutting down build servers using the `dotnet build-server shutdown`.
To investigate build time issues, make sure that you have the latest tools (`dotnet --version` should show 2.1.500 at the moment) and add `-clp:PerformanceSummary` to output some diagnostics that would help to understand where build time issues come from.

**Comment by dasMulli** [comment]
That being said, on my machine the incremental build times for a hello world app are also 1.3s or 1.05s (`--no-restore`).

**Comment by rainersigwald** [comment]
Node reuse has been available (and on by default) on .NET Core since .NET Core 2.1 (#3106 turned it on, with some tweaks afterward).

@xoofx How many projects are built in your scenario? MSBuild will only start worker nodes if it can use them, and the entry-point node isn't reused (we have some vague notions about possibly changing that but nothing concrete yet).

**Comment by xoofx** [comment]
> @xoofx How many projects are built in your scenario? MSBuild will only start worker nodes if it can use them, and the entry-point node isn't reused (we have some vague notions about possibly changing that but nothing concrete yet).

I was actually testing on only one project. On Windows I'm able to go down to around 900ms.  I have done a small exe that is calling msbuild in a loop (so it doesn't have to reload it, all assemblies...etc.) and I can go down to 200ms after that (parsed only once). So I suspect that a good part of running msbuild is actually spent in loading all the msbuild/nuget assemblies (even though msbuild shipped with dotnet CLI seems crossgen)

I'm experimenting how much I can go down with a msbuild in-flight in terms of compilation time. So I assume that when compiling a single project, msbuild doesn't forward to a node reuse and build directly from the running instance?

**Comment by rainersigwald** [comment]
> when compiling a single project, msbuild doesn't forward to a node reuse but is actually building from the running instance?

Correct.

**Comment by xoofx** [comment]
ok, so is there any way for msbuild to forward to a node reuse even if you have only one project, while I could keep the client msbuild in-process for example?

**Comment by rainersigwald** [comment]
Using the API, yes: you can set [`BuildParameters.DisableInProcNode = true`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.execution.buildparameters.disableinprocnode?view=netframework-4.7.2#Microsoft_Build_Execution_BuildParameters_DisableInProcNode).

**Comment by xoofx** [comment]
Cool, thanks, I will give this a try
