### ISSUE TITLE
.NET applications invoked through <Exec> tasks may send malformed UTF-8 to their children

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#397]
This was reported internally in reference to the Windows Driver Kit.

Visual Studio 2015 Update 1 shipped with a fix (#143) to allow tools to run with paths that included non-ANSI Unicode characters.  It did this by changing the Windows codepage within the `.cmd` script emitted by `Exec` to one that supports UTF-8.

This causes problems when a child process spawns another child process and attempts to write to its standard input.  From the excellent internal repro:
```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Target Name="Repro">
        <Exec Command="repro.exe" />
    </Target>
</Project>
```

Where `repro.exe` is compiled from
```C#
using System;
using System.Diagnostics;
using System.IO;

namespace Repro
{
    class Repro
    {
        static void Main(string[] args)
        {
            using (Process cmdProcess = new Process())
            {
                ProcessStartInfo cmdProcessStartInfo = new ProcessStartInfo("cmd.exe");
                cmdProcessStartInfo.UseShellExecute = false;
                cmdProcessStartInfo.RedirectStandardInput = true;
                cmdProcess.StartInfo = cmdProcessStartInfo;
                cmdProcess.Start();

                StreamWriter inputWriter = cmdProcess.StandardInput;
                inputWriter.AutoFlush = true;
                inputWriter.WriteLine("set CL=");
                inputWriter.WriteLine("exit");
                cmdProcess.WaitForExit();

                Console.WriteLine("Exit code: " + cmdProcess.ExitCode);
            }
            Console.Write("Repro Exiting");
        }
    }
}
```

Produces this output:
```
Microsoft (R) Build Engine version 14.0.24720.0
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 12/7/2015 5:00:43 PM.
Project "d:\work\sdv_encoding\project.vcxproj" on node 1 (default targets).
Repro:
  repro.exe
  Microsoft Windows [Version 10.0.10240]
  (c) 2015 Microsoft Corporation. All rights reserved.

  d:\work\sdv_encoding>���set CL=
  '���set' is not recognized as an internal or external command,
  operable program or batch file.

  d:\work\sdv_encoding>exit
  Exit code: 9009
  Repro Exiting
Done Building Project "d:\work\sdv_encoding\project.vcxproj" (default targets).
```

Note the super-sketchy "unknown Unicode character" glyphs that `cmd.exe` is complaining about not understanding when prepended to `set`.

**Comment by rainersigwald** [comment]
I narrowed down what was going on here by adding logging to the repro program:
```csharp
Console.WriteLine($"input enc: {cmdProcess.StandardInput.Encoding}");
```

That showed that for success cases (`repro.exe` run from a bare command line), the encoding was `System.Text.SBCSCodePageEncoding`, while when invoked from MSBuild it was `System.Text.UTF8Encoding`.

By default, UTF-8 encodings in .NET use a Unicode [Byte Order Mark](http://unicode.org/faq/utf_bom.html#bom1) at the beginning of the stream.  `cmd.exe` does not support BOMs, and the UTF-8 BOM is three bytes, so it's probably what we're seeing here.

This hypothesis is confirmed by setting the codepage at an interactive console with `chcp 65001`, then running the program.  The same error is produced.

Since that's the case, while this problem was exposed by the MSBuild change, it's not exactly *caused* by it.

A managed tool can ensure that it won't send a BOM to a child process's stdin, but only indirectly.  The [source for the Process class](http://referencesource.microsoft.com/#System/services/monitoring/system/diagnosticts/Process.cs,2160) creates a child process's stdin stream by creating a new stream based on the current process's `Console.InputEncoding`.  Unfortunately, there's no good way to determine whether a UTF-8 encoding will or will not emit a BOM.

Adding this snippet before creating a child process seems to avoid the issue by ensuring that a BOM is never sent to a child process if the current process is in UTF-8 land.
```csharp
if (Console.InputEncoding.Equals(Encoding.UTF8))
{
    Console.InputEncoding = new UTF8Encoding(false);
}
```

**Comment by PKRoma** [comment]
Just as a FYI: A BOM has no place in a UTF-8 encoding. A byte order mark only has a place in a 16-bit encoding, where it is unknown whether the encoding it little- or big-endian, and so the first character to be emitted in the 16-bit stream is a BOM. In translating a 16-bit stream to a UTF-8 stream, any BOM should be stripped out and not emitted at all.

**Comment by rainersigwald** [comment]
@PKRoma I thought that too, but it doesn't appear to be specified that way.  http://unicode.org/faq/utf_bom.html#bom4 explicitly mentions that it is valid in UTF-8.

And, of course, programs are at the mercy of the implementations of the .NET Framework and the Windows shell.  .NET's `UTF8Encoding` uses a BOM by default, and `cmd.exe` cannot interpret one, so this problem arises.

**Comment by rainersigwald** [comment]
Another possible workaround:  change the `Exec` task's `Command` attribute to prepend
```cmd
chcp 437 &&
```
to the command.  That will effectively undo the change we made and return `cmd.exe` to the "standard" codepage (for US English).  It may be easier to deploy this workaround than to fix the tool that is called.

**Comment by drbo** [comment]
I think that MSBuild is doing the right thing; the problem is with the WDK.  I don't want to lose the ability to use Unicode filenames in MSBuild tasks.

**Comment by PKRoma** [comment]
Hmm. I still have a question here. How is it that cmd.exe is interpreting the first three bytes of stdin in repro.exe as three separate characters and printing error blobs for each of them? If the problem only exists when the encoding is 65001 as you found, then they shouldn't be interpreted as three separate characters at all, but rather, if anything at all, they should be interpreted as a single BOM Unicode character and cause only one error blob? Once it figures out that it's got a BOM character, couldn't cmd.exe then treat it as a NOP?

**Comment by rainersigwald** [comment]
@PKRoma I think the issue is that the innermost `cmd.exe` is operating with the system default codepage (which is 437 on US English Windows).  When it gets fed the UTF-8 BOM bytes, it interprets them each as bogus ASCII.  I'm not sure what would happen if you started `cmd.exe`, ran `chcp 65001`, and *then* streamed UTF-8-with-BOM to it.

**Comment by rainersigwald** [comment]
@drbo Thanks for the feedback.  We agree.  Unless we hear from more folks that this is causing real problems, we plan to keep the current behavior.

**Comment by rainersigwald** [comment]
Update:  There are indeed some more problems related to this change.  See [comments](http://blogs.msdn.com/b/bharry/archive/2015/11/30/vs-2015-update-1-and-tfs-2015-update-1-are-available.aspx#10658899) [on](http://blogs.msdn.com/b/bharry/archive/2015/11/30/vs-2015-update-1-and-tfs-2015-update-1-are-available.aspx#10658449) Brian Harry's Update 1 blog post, both of which used `al.exe` in a post-build event (which is just a UI way of creating an `Exec`).  @jaredpar posted the `chcp 437` workaround there, which worked for those folks.

There was [another related problem report](http://blogs.msdn.com/b/bharry/archive/2015/11/30/vs-2015-update-1-and-tfs-2015-update-1-are-available.aspx#10658922) there as well.  That user had an em dash in their project file rather than a hyphen character.  This sort of thing happens all the time when you copy/paste code from Outlook or another program that autocorrects.  Prior to Update 1, it looks like that dash was [fallback encoded](https://msdn.microsoft.com/en-us/library/ms404377(v=vs.110).aspx#FallbackStrategy) to the tool-expected hyphen.  After Update 1, the dash was included in the Exec-generated `.cmd` file and the command line tool stopped recognizing it.

**Comment by rainersigwald** [comment]
Team triage: we're going to attempt to conditionalize the codepage change, so that if the string from the project contains non-ANSI characters we'll use the current behavior of changing the codepage to Unicode. If the string is representable in the current system encoding, we'll use the old behavior with no `chcp`. This makes understanding this sort of problem when it occurs vastly more difficult, but should dramatically reduce the incidence rate.

**Comment by jaredpar** [comment]
@rainersigwald 

> Team triage: we're going to attempt to conditionalize the codepage change, so that if the string from the project contains non-ANSI characters

Which string are you referring to here?

In addition to detection have you all considered an option to let users specifically opt in / out of this behavior?

**Comment by rainersigwald** [comment]
@jaredpar The string is the (property- and item-expanded) contents of the `Exec`'s `Command` attribute. It sounds like @AndyGerlicher is planning to allow a codepage override in addition to the detection logic. IM transcript:

```
[‎1/‎20/‎2016 6:18 PM] Andy Gerlicher: 
so... should we add a property to override for Exec?
CodePage as int? something like that?
[‎1/‎20/‎2016 6:18 PM] Rainer Sigwald: 
I say no because it's basically impossible to decide when to use it
for example, the UI-accessible PostBuildEvent is implemented with Exec
are we going to modify that target definition to take an additional variable?
I guess we could
[‎1/‎20/‎2016 6:20 PM] Rainer Sigwald: 
we could just have a convention that all Exec tasks take an optional $(ExecCodepageNumber) and if an individual is having problems with a project they could set that
[‎1/‎20/‎2016 6:20 PM] Andy Gerlicher: 
I would say we don't modify anything, just have an out for the user if a workaround is needed
[‎1/‎20/‎2016 6:21 PM] Rainer Sigwald: 
but to use the out, they'd have to modify the callsite of Exec
if it's in our targets or in a package they can't do that
[‎1/‎20/‎2016 6:21 PM] Andy Gerlicher: 
I'm thinking for custom Exec, not our stuff
this change should fix our stuff
[‎1/‎20/‎2016 6:22 PM] Rainer Sigwald: 
oh, so you're thinking in addition?
[‎1/‎20/‎2016 6:23 PM] Andy Gerlicher: 
yeah. like an OverrideCodePage property you could set
and if you set that it will always use it
on that exec call
[‎1/‎20/‎2016 6:23 PM] Rainer Sigwald: 
that makes sense to me, I think
```

**Comment by jaredpar** [comment]
@rainersigwald @AndyGerlicher how would one specify the equivalent of `CP_ACP` in this setting?  Essentially asking for the behavior before this change?

**Comment by pvandervelde** [comment]
This issue is currently breaking my builds in that the error stream of one of my applications called via exec is suddenly producing something (Character 65279, which should be a zero-width no breaking space) when it shouldn't.

So for those of us who have been hit by this is there a work around until VS2015.2 comes out (assuming this patch will be in that release)?

**Comment by rainersigwald** [comment]
@pvandervelde #442 will be in Update 2 (and it is in the currently-available CTP). Until then, you can work around the way that you did, or by explicitly setting the codepage in the `Exec` task invocation as mentioned [above](https://github.com/Microsoft/msbuild/issues/397#issuecomment-162925595).

I'm surprised at a few things from your situation:
* Your task invokes a `Process` directly, *not* through `Exec`. That shouldn't be subject to the codepage change. Are you invoking `msbuild.exe` within an `Exec` task from another MSBuild?
* The fact that you're seeing the BOM emitted to an otherwise-empty stream is interesting, though. IIRC .NET does not emit it when the stream is set up, only before the first written character. It might be worth looking at the behavior of OpenCover when run under the Unicode codepage--which is something that a user could set up outside of MSBuild, which would potentially cause problems regardless of MSBuild's behavior.
