### ISSUE TITLE
15.9.3 msbuild hangs

### ISSUE THREAD

**Issue by gilm0079** [Microsoft/msbuild#3994]
I just noticed issues in the past few days.  My VS 2017 Pro locks constantly.  If I change the solution build config it locks. If I change a project assembly version it locks.  If I build it locks.  

When it locks up task manager is showing MSBuild.exe (sometimes 2-3 instances under this VS 2017 process instance) running at 25%.  My desktop has 4 cores so that means it is running 1 core at 100%.  Restarts have not changed anything.  It is always the MSbuild.exe that is locking up my visual studio for several minutes.  When those processes complete what they are doing then visual studio becomes usable again.  Any ideas?

Windows 10 Pro
Visual Studio 2017 Pro 15.9.3

I also noticed now in the Visual Studio Installer it now shows a "Visual Studio Build Tools 2017 (2)" item installed (version 15.9.2) as well as the usual "Visual Studio Professional 2017" (version 15.9.3).  The build tools must have been added in a recent update?

**Comment by rainersigwald** [comment]
Can you please use the Visual Studio feedback tool to report the hang? It collects a lot of information related to VS that should be useful to diagnose your problem. Please link the feedback item here and we can investigate further.

Build Tools has existed for a long time and an update to VS itself shouldn't have caused it to be installed. If you don't need it, it would be interesting to try uninstalling it, but its presence should not cause hangs.

Also, obligatory context questions: 
* Did you notice this immediately after updating to 15.9.3?
* Were you on 15.9.2 before?
* Does this happen for all solutions, or only some? What about a trivial new project?
* If you check out an old version of your code do you see the same problem?

**Comment by gilm0079** [comment]
Will do on the feedback tool.  I always feel like those feedback things go into black holes in most apps.  Good to hear it actually reaches someone.

As far as I know I don't use MSBuild outside of visual studio.  I'll try to remove it.

I'm not sure exactly when I installed 15.9.3.  I would assume the beginning of this week. The issues started presenting themselves on Wednesday.  At least that's when I noticed it get bad enough that it was making development difficult.
Yes, I was previously on 15.9.2.
I've only been using 2 solutions recently.  1 is mostly just class library projects, EF and web.api.  That one builds fine.  The one I'm having issues with is a front end website project so heavy on MVC, web.api, angular, javascript, etc.  That is the one with issues.  

Is there a way to have MSbuild be verbose when it is executing or export a log?  Maybe it is something MSBuild is executing or a certain task it is taking a long time on and seeing that may quickly narrow down the cause.

**Comment by livarcocc** [comment]
@davkean as well in this case this anything to do with the project system.

**Comment by gilm0079** [comment]
I've been doing testing.  I don't think the issue is isolated to MSBuild as far as I can tell.  It does however seem to be isolated to a single solution.

For this solution, the behavior I'm seeing is when I open the solution in VS, VS goes not responding for several minutes before I can use it.  This also happens when closing the solution, when executing a build, and when using msdeploy via publish it freezes prior to requesting authentication and at the very end of the publish before it marks it in the output window as complete.

Any suggestions how I can troubleshoot VS to see what it is having issues with?  I'm not seeing any visible errors or errors during the build output that are pointing me in the right direction.  I think I need more of VS application diagnostic logging..

**Comment by gilm0079** [comment]
Thanks. That's helpful for at least the build issues, which could be related to the other issues.  After running the build logging it shows the MVC project getting stuck for many minutes on the WebCompiler.CompilerBuildTask.  This is the Web Essentials 2017 less/css compiler.  I've re-installed with no luck and had no response from issues on their repo.  I'll keep looking into that.

**Comment by gilm0079** [comment]
That led me to the answer. I ended up pulling down the WebCompiler source and stepping through it.  Basically, it was probably looping thousands of files within the project when running.  Probably, also why it made the UI look like it was hanging.  I put the solution related to the WebCompiler here:
[https://github.com/madskristensen/WebCompiler/issues/397](https://github.com/madskristensen/WebCompiler/issues/397)

I'll close this issue out. Feel free to post updates though if you have questions.

**Comment by davkean** [comment]
The legacy project system (used for .NET Framework-based/Xamarin/UWP projects) blocks the UI on design-time builds. Long design-time builds can lead to pauses like you've found.
