### ISSUE TITLE
Truncated source file

### ISSUE THREAD

**Issue by gluck** [Microsoft/msbuild#4]
[src/Shared/ThreadingUtilities.cs](https://github.com/Microsoft/msbuild/blob/master/src/Shared/ThreadingUtilities.cs) has invalid (truncated) content.

Fun than it seems to be truncated at 2048 :smile_cat:

**Comment by akoeplinger** [comment]
Lol :smile: Seems the file/class isn't used anywhere, so it can probably just be deleted.

**Comment by khellang** [comment]
Fixed by #8 :smile:

**Comment by gluck** [comment]
We'll never know how the 2048 truncation happened ! :smile:
