### ISSUE TITLE
Ability to run MSI installer projects

### ISSUE THREAD

**Issue by EasyAsABC123** [Microsoft/msbuild#4005]
### Steps to reproduce

Attempt to build an MSI installer project which will fail because you can't install the VSIX with only msbuild installed.

### Expected  behavior
As a developer i should be able to build msi projects with msbuild only.

### Actual behavior
Successful generation of MSIs

### Environment data
`msbuild /version` output:
```
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
```
15.9.20.62856
OS info:
```
Windows Server 2016
```

**Comment by rainersigwald** [comment]
Can you clarify what you mean by "msbuild only"?

As a bit of background: components of Visual Studio and third parties can extend the types of projects that MSBuild can build, so you need to install the appropriate workloads as part of Visual Studio or Build Tools for Visual Studio and in some cases install SDKs separately before you can build some kinds of project.

**Comment by EasyAsABC123** [comment]
this needs to be installed: https://marketplace.visualstudio.com/items?itemName=VisualStudioClient.MicrosoftVisualStudio2017InstallerProjects

which doesn't seem to be compatible with msbuild15 (without installing VS)

**Comment by EasyAsABC123** [comment]
**More detailed message:**
![image](https://user-images.githubusercontent.com/1851104/50694456-f30c5d00-1007-11e9-805a-2a09e9410d40.png)

```
1/4/2019 2:55:07 PM - Microsoft VSIX Installer
1/4/2019 2:55:07 PM - -------------------------------------------
1/4/2019 2:55:07 PM - vsixinstaller.exe version:
1/4/2019 2:55:07 PM - 15.6.152+ge95e4dd1ce
1/4/2019 2:55:07 PM - -------------------------------------------
1/4/2019 2:55:07 PM - Command line parameters:
1/4/2019 2:55:07 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\jschuhmann\Desktop\InstallerProjects.vsix
1/4/2019 2:55:07 PM - -------------------------------------------
1/4/2019 2:55:07 PM - Microsoft VSIX Installer
1/4/2019 2:55:07 PM - -------------------------------------------
1/4/2019 2:55:08 PM - Initializing Install...
1/4/2019 2:55:08 PM - Extension Details...
1/4/2019 2:55:08 PM - 	Identifier         : VSInstallerProjects
1/4/2019 2:55:08 PM - 	Name               : Microsoft Visual Studio Installer Projects
1/4/2019 2:55:08 PM - 	Author             : Microsoft
1/4/2019 2:55:08 PM - 	Version            : 0.9.0
1/4/2019 2:55:08 PM - 	Description        : This official Microsoft extension provides support for Visual Studio Installer Projects in Visual Studio.
1/4/2019 2:55:08 PM - 	Locale             : en-US
1/4/2019 2:55:08 PM - 	MoreInfoURL        : 
1/4/2019 2:55:08 PM - 	InstalledByMSI     : False
1/4/2019 2:55:08 PM - 	SupportedFrameworkVersionRange : [4.6.1,)
1/4/2019 2:55:08 PM - 
1/4/2019 2:55:09 PM - 	SignatureState     : ValidSignature
1/4/2019 2:55:09 PM - 	SignedBy           : Microsoft Corporation
1/4/2019 2:55:09 PM - 	Certificate Info   : 
1/4/2019 2:55:09 PM - 		-------------------------------------------------------
1/4/2019 2:55:09 PM - 		[Subject]       : CN=Microsoft Corporation, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
1/4/2019 2:55:09 PM - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
1/4/2019 2:55:09 PM - 		[Serial Number] : 330000026ECE6AE5984BFC96A900000000026E
1/4/2019 2:55:09 PM - 		[Not Before]    : 9/6/2018 9:00:30 PM
1/4/2019 2:55:09 PM - 		[Not After]     : 9/6/2019 9:00:30 PM
1/4/2019 2:55:09 PM - 		[Thumbprint]    : 99B6246883B4B32EA59AE18B36945D205A876800
1/4/2019 2:55:09 PM - 
1/4/2019 2:55:09 PM - 	Supported Products : 
1/4/2019 2:55:09 PM - 		Microsoft.VisualStudio.Community
1/4/2019 2:55:09 PM - 			Version : [15.0,17.0)
1/4/2019 2:55:09 PM - 
1/4/2019 2:55:09 PM - 	References         : 
1/4/2019 2:55:09 PM - 	Prerequisites      : 
1/4/2019 2:55:09 PM - 		-------------------------------------------------------
1/4/2019 2:55:09 PM - 		Identifier   : Microsoft.VisualStudio.MinShell
1/4/2019 2:55:09 PM - 		Name         : Visual Studio Min Shell
1/4/2019 2:55:09 PM - 		Version      : [15.0.26205,17.0)
1/4/2019 2:55:09 PM - 
1/4/2019 2:55:09 PM - 		-------------------------------------------------------
1/4/2019 2:55:09 PM - 		Identifier   : Microsoft.Component.ClickOnce
1/4/2019 2:55:09 PM - 		Name         : ClickOnce Publishing
1/4/2019 2:55:09 PM - 		Version      : [15.0,17.0)
1/4/2019 2:55:09 PM - 
1/4/2019 2:55:09 PM - Signature Details...
1/4/2019 2:55:09 PM - 	Extension is signed with a valid signature.
1/4/2019 2:55:09 PM - 
1/4/2019 2:55:09 PM - Searching for applicable products...
1/4/2019 2:55:09 PM - Found installed product - Global Location
1/4/2019 2:55:09 PM - Found installed product - Visual Studio Build Tools 2017
1/4/2019 2:55:09 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by livarcocc** [comment]
This is not something that we can fix on MSBuild. Like @rainersigwald mentioned, additional components are required depending on what kinds of projects you are trying to build.

I would suggest filling a feedback ticket through VS itself, so that this issue gets routed to the appropriate VS team.

**Comment by JackZylkin** [comment]
@EasyAsABC123 Hey did you ever get a resolution on this?  I have the same problem. I think it is silly that I can't release an MSI using my build server.

**Comment by EasyAsABC123** [comment]
There is no solution and Microsoft doesn't care, that's the feeling I get

**Comment by tomuxmon** [comment]
Hello.
I am not an advocate for Microsoft but I think the guys closing the issue are right. You should install additional tools to your build server manually and then use MSBuild with extended task list.
From the comment above I saw @EasyAsABC123  tried installing VSIX that is visual studio extension. Visual studio and MSBuild are different things. You should install something that extends MSBuild and not the Visual Studio. 
I would personally recommend using [Wix Toolset](https://wixtoolset.org/)  to build MSI packages. it belongs to .Net foundation and I think it is de-facto way to author MSI packages.
Hope my comment is a bit useful.

**Comment by EasyAsABC123** [comment]
@tomuxmon i don't disagree, i'd think backporting would be simple for the people with the code.  I'd be happy if there is an extension for msbuild to create MSIs.

No new solutions on this.
