### ISSUE TITLE
Could not find reference "mscorlib".

### ISSUE THREAD

**Issue by jeffkl** [Microsoft/msbuild#4009]
_From @Cyrus-d on November 2, 2018 12:18_

Hi,

I am using  'RoslynCodeTaskFactory' for my task as suggested in here:

[MSBuild inline tasks with RoslynCodeTaskFactory](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-roslyncodetaskfactory?view=vs-2017)

Task Code:

```
<UsingTask TaskName="ExecAsync" TaskFactory="RoslynCodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll">
    <ParameterGroup>
      <Command ParameterType="System.String" Required="true" />
    </ParameterGroup>
    <Task>
      <Code Type="Fragment" Language="cs">
        <![CDATA[
            var procStartInfo =
                new System.Diagnostics.ProcessStartInfo("cmd", "/c" + Command)
                {
                    RedirectStandardOutput = false,
                    UseShellExecute = true,
                    CreateNoWindow = false,
                    WindowStyle=System.Diagnostics.ProcessWindowStyle.Minimized
                };

            System.Diagnostics.Process proc = new System.Diagnostics.Process
            {
                StartInfo = procStartInfo
            };
            proc.Start();
       ]]>
      </Code>
    </Task>
  </UsingTask>
```

it does work fine in the visual studio, however, when running 'dotnet build' it will throw the following errors:

- error MSB3755: Could not find reference "mscorlib". If this reference is required by your code, you may get compilation errors.

- error MSB3755: Could not find reference "netstandard". If this reference is required by your code, you may get compilation errors.

- error MSB4175: The task factory "RoslynCodeTaskFactory" could not be loaded from the assembly "C:\Program Files\dotnet\sdk\2.2.100-preview3-009430\Microsoft.Build.Tasks.Core.dll". The task factory must return a value for the "TaskType" property.

Target: .NET Core v2.1

maybe related problem here:
[https://github.com/Microsoft/msbuild/issues/3726](https://github.com/Microsoft/msbuild/issues/3726)

Can you please tell what am I missing here.

Thanks

_Copied from original issue: jeffkl/RoslynCodeTaskFactory#39_

**Comment by jeffkl** [comment]
_From @SimplerSoftware on December 13, 2018 18:52_

@Cyrus-d - Did you find a solution to this?  Running into this same error.

**Comment by jeffkl** [comment]
_From @rainersigwald on December 13, 2018 18:57_

Duplicate of https://github.com/Microsoft/msbuild/issues/3726, which has some workarounds.

**Comment by jeffkl** [comment]
Closing in favor of #3276

**Comment by eduherminio** [comment]
@jeffkl probably meant #3726.
