### ISSUE TITLE
Invalid static method invocation [Microsoft.Build.Utilities.ToolLocationHelper]::GetPathToStandardLibraries

### ISSUE THREAD

**Issue by jlarbi** [microsoft/msbuild#4026]
@rainersigwald Same issue when loading a .csproj using MSBuildWorkspace. It was working when i had only VS2015 installed, but since I installed vs2017, I get this error : -- ERROR: Msbuild failed when processing the file 'D:\DCGF_KillCA\Externals\XRoslyn\MyTypes\MyTypes.csproj' with message: Invalid static method invocation syntax: "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPathToStandardLibraries($(TargetFrameworkIdentifier), $(TargetFrameworkVersion), $(TargetFrameworkProfile), $(PlatformTarget), $(TargetFrameworkRootPath), $(TargetFrameworkFallbackSearchPaths))". Méthode 'Microsoft.Build.Utilities.ToolLocationHelper.GetPathToStandardLibraries' introuvable. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(a, b)). C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets

Previously, I assume it was doing stuff in C:\Program Files (x86)\Microsoft Visual Studio\2015.... and it was working

The code :
     var lBuildConfiguration = new Dictionary<string, string>
     {
     { "Configuration", "Release" }, // Or "Debug", or whatever is known to your projects.
     { "Platform", "x86" }, // Or x64, AnyCPU, etc...
     { "CheckForSystemRuntimeDependency", "true" }
     // ... more properties that could influence a build
      };

        this.mWork = MSBuildWorkspace.Create( lBuildConfiguration );
        this.mWork.LoadMetadataForReferencedProjects = true;
        this.mWork.SkipUnrecognizedProjects = false;
        // Load the project straight.
         this.mProject = this.mWork.OpenProjectAsync( pProjectPath ).Result;

Can we force a MSbuild version in config strings?

I suspecte when trying to load a csproj (inducing there is no solution at open time) MSbuildWorkspace create a default one to load my csproj in it. In the case there was only VS2015, the default solution created was VS2015, but now there is vs2017, the default solution MSbuildWorkspace is creating is a VS2017 temp sln which attempt to load a csproj vs2015 formatted that obviously mismatches in matter of (MSBuildExtensionsPath)$(MSBuildToolsVersion) or whatever...

**Comment by jlarbi** [comment]
The exception is not on load project but during compilation

this.mProject.GetCompilationAsync().Result;

**Comment by rainersigwald** [comment]
This sounds like a problem that can be resolved by [using MSBuildLocator](https://docs.microsoft.com/en-us/visualstudio/msbuild/updating-an-existing-application?view=vs-2019).

Since we let this issue get very stale, I'm going to close it. Please let us know if you see the problem after using Locator and we can reopen and investigate further.
