### ISSUE TITLE
CurrentMSBuildExePath error causes an exception

### ISSUE THREAD

**Issue by wangchaoyu1992** [Microsoft/msbuild#4031]
### Steps to reproduce
Compile fail.
How does "currentMSBuildExePath" in the "BuildEnvironment" constructor get it
Is it an environment variable or registry
If yes, can you tell me how to configure it
Thank you very much
Because currentMSBuildExePath is incorrect.[printscreen](https://github.com/wangchaoyu1992/First/blob/master/111.jpg)
### Expected  behavior
Compile successfully

### Actual behavior
Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk' specified could not be found.  F:\Project\Blazor\src\Microsoft.AspNetCore.Blazor.Mono\Microsoft.AspNetCore.Blazor.Mono.csproj

### Environment data
`msbuild /version` output: 15.7

OS info:

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):

**Comment by livarcocc** [comment]
Can you tell us more of what you are trying to do here? It is not very clear from your description above.

**Comment by wangchaoyu1992** [comment]
I found there was a problem with the "currentMSBuildExePath" path query
Reason is can't find "C: \ ProgramData \ Microsoft \ VisualStudio \ Setup \ x86 \Microsoft.VisualStudio.Setup.Configuration.Native.dll "
I compile a project with MSBuild15.7 and report an error
Then I looked at the source code of MSBuild and found that it was "new Guid" (" 177f0c4a-1cd3-4de7-a32c-71dbbb9fa36d ").
The registry could not be found
I wonder when this registry was registered
What do I need to install？
[my code:](https://github.com/wangchaoyu1992/First/blob/master/22.jpg)
Exception: 
Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk' specified could not be found. F:\Project\Blazor\src\Microsoft.AspNetCore.Blazor.Mono\Microsoft.AspNetCore.Blazor.Mono.cspro

**Comment by rainersigwald** [comment]
I still don't quite understand what you're trying to do. Are you writing an application that uses the MSBuild API to run builds? If so, are you using [MSBuildLocator](https://docs.microsoft.com/en-us/visualstudio/msbuild/updating-an-existing-application?view=vs-2017)?

**Comment by wangchaoyu1992** [comment]
I solved the problem.
Thank you very much
