### ISSUE TITLE
Question: How do you get non cs files using the Microsoft.Build package?

### ISSUE THREAD

**Issue by taori** [Microsoft/msbuild#4032]
I am using the MSBuildWorkspace and was suprised to notice that neither Project.Documents nor Project.AdditionalDocuments did list any xaml/resx/etc files. What am i missing here?

**Comment by Pilchie** [comment]
This is a better question for https://github.com/dotnet/roslyn which provides the MSBuildWorkspace. However, it is generally a very C#/VB compiler centric view of the world - only the inputs the compiler are tracked in that workspace.

**Comment by taori** [comment]
@Pilchie Mhm, yes. i originally wanted to ask there but came to the same conclusion - roslyn is just the compiler which processes the files it gets, so i figured i would have to ask here. That's odd. Guess i'll try over at roslyn then. Thanks.

**Comment by Pilchie** [comment]
`MSBuildWorkspace` was written by the Roslyn team, for people to use Roslyn with MSBuild based solutions.  So, the question is really, do you want to work with Roslyn (which is compiler centric), or do you want to work with MSBuild, in which case, you'd have to use the MSBuild APIs (possibly looking at the implementation of MSBuildWorkspace for inspiration).[

**Comment by taori** [comment]
Yeah. I'll have a look. Thanks a lot.
