### ISSUE TITLE
WriteLinesToFile should create the directory if it doesn't exist

### ISSUE THREAD

**Issue by KirillOsenkov** [Microsoft/msbuild#4033]
The `WriteLinesToFile` task doesn't create the directory for the file if it doesn't exist.

It should call `Directory.CreateDirectory(Path.GetDirectoryName(File))` to help with the pit of success. Too much ceremony with requiring authors to create the directory themselves.

**Comment by CodeTherapist** [comment]
I would like to implement this.

**Comment by Therzok** [comment]
@CodeTherapist this should be a good start, and where the task lives: https://github.com/Microsoft/msbuild/blob/master/src/Tasks/FileIO/WriteLinesToFile.cs#L15

**Comment by rainersigwald** [comment]
All yours, @CodeTherapist. Let us know if you need any help.

**Comment by CodeTherapist** [comment]
@rainersigwald, @Therzok: Thank you for your helpfulnes :)
