### ISSUE TITLE
Including additional "Web.config" files in WebConfigsToTransform causes ParameterizeTransformXml to fail

### ISSUE THREAD

**Issue by richardszalay** [Microsoft/msbuild#4034]
I realise that this issue belongs with the VS / Web Publishing team, but I wasn't sure of the best place to log it. Please let me know if there's a better place where I can submit it and I'll be happy to do so.

(For that reason, I've also omitted things like MSBuild version since it's irrelevant here)

### Steps to reproduce

1. In an ASP.NET ("classic") Project, include transforms on Views\Web.config (or otherwise include an additional `WebConfigsToTransform` on a file named Web.config)
2. Publish to an MSDeploy target (eg. package)

### Expected  behavior

Connection strings in Web.config are auto-parameterised.
The additional Web.config does not cause an error.

### Actual behavior

The following error is generated:

> C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\Web\Microsoft.Web
> .Publishing.targets(2311,5): error : Could not open Source file: Could not find a part of the path 'obj\Debug\TransformWebConfig\transformed\Views\Web.config;obj\Debug\TransformWebConfig\transformed\Web.config'.
> 

### Root cause

The issue is that `ParameterizeTransformXml.Source` is a `string` rather than an `ITaskItem`, but it's use in `AutoParameterizationWebConfigConnectionStringsCore` makes it look like it's batchable. The net result is that while all of the _metadata_ values cause the invocation to be batched, the `Source` property itself just gets the same semicolon-delimited string representation of the items when there is more than one.

### Workaround

Setting `AutoParameterizationWebConfigConnectionStrings` to `false` works, but it also disables auto-parameterization of Web.config connection strings (unsurprisingly).

`AutoParameterizationWebConfigConnectionStringsCore` uses `_WebConfigsToAutoParmeterizeCS`, which is copied from `WebConfigsToTransform` in `PreAutoParameterizationWebConfigConnectionStrings`. The workaround is therefore to hook in after that and remove all Web.config items from `_WebConfigsToAutoParmeterizeCS` that _aren't_ "/Web.config":

```xml
<Target Name="RemoveAdditionalWebConfigsToTransformToPreventParameterizeTransformXmlError" AfterTargets="PreAutoParameterizationWebConfigConnectionStrings">
  <ItemGroup>
    <_WebConfigsToAutoParmeterizeCS Remove="@(_WebConfigsToAutoParmeterizeCS)" 
      Condition="'%(TransformScope)' != '$([System.IO.Path]::GetFullPath($(WPPAllFilesInSingleFolder)\Web.config)'" />
  </ItemGroup>
</Target>
```

**Comment by livarcocc** [comment]
Please, move the issue to github.com/aspnet/websdk.

**Comment by richardszalay** [comment]
Done, thanks! Though FYI you can actually transfer issues via the right hand panel
