### ISSUE TITLE
/interactive does not work with nuget

### ISSUE THREAD

**Issue by wli3** [Microsoft/msbuild#4036]
The only use case of /interactive is to work with nuget for auth. So `/interactive` is not useable today.

Repo step
1. Create an project reference a private nuget feed. And run "installcredprovider.sh".
2. `dotnet msbuild /t:build /restore /interactive` does not invoke auth extension while `dotnet msbuild /t:build /restore /p:NuGetInteractive=true` do

In https://github.com/Microsoft/msbuild/pull/3697 we plan to create a new option `/interactive` to replace `NuGetInteractive`. However, from my understanding, nuget should detect `MSBuildInteractive` instead of [directly looking into](https://github.com/NuGet/NuGet.Client/blob/e1656fa697cb189b342c1fe509eebb16d90e9817/src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets#L125) `NuGetInteractive`.
 
We need discussion. Either msbuild also set NuGetInteractive at the same time when /interactive is used or nuget should read `MSBuildInteractive` instead.

**Comment by wli3** [comment]
FYI @jeffkl @nkolev92

**Comment by nkolev92** [comment]
>  However, from my understanding, nuget should detect MSBuildInteractive instead of directly looking into NuGetInteractive

Maybe NuGetInteractive defaults to MSBuildInteractive? 

When you run a `dotnet msbuild /t:randomTarget /interactive`, does `MSBuildInteractive` get set?

//cc @rrelyea

**Comment by rainersigwald** [comment]
> Maybe NuGetInteractive defaults to MSBuildInteractive?

Yeah, I think that'd be a good plan: add

```xml
<NuGetInteractive Condition="'$(NuGetInteractive)' == ''">$(MSBuildInteractive)</NuGetInteractive>
```

in `NuGet.targets`.

**Comment by nkolev92** [comment]
I have a PR out on NuGet side to address this. https://github.com/NuGet/NuGet.Client/pull/2665

I'll wait for the conclusion of this thread before merging.

**Comment by wli3** [comment]
NuGet/NuGet.Client#2665 is good to me. @dsplaisted @johnbeisner @livarcocc  @nguerrera @peterhuene ?

**Comment by wli3** [comment]
@rainersigwald @nkolev92 I doubled check in slack. No objection, let's go for this solution

**Comment by nkolev92** [comment]
The NuGet side is merged. 

It will some time until we get an insertion going though.

**Comment by rainersigwald** [comment]
@wli3 We don't need any MSBuild changes to pick that up, right? Should we close this?
