### ISSUE TITLE
MSBuild should continue to support calling batches containing piped finds

### ISSUE THREAD

**Issue by bluerobotch** [Microsoft/msbuild#405]
After updating to Visual Studio 2015 Update 1 (MSBuild 14.0.24720.0) batches containing piped find commands do not work anymore.

The following batch command searches for 'b' in 'abc' and finds a match. The errorlevel is set to 0 by the find command.
```Batchfile
echo abc | find "b"
```

When executing a batch file containing the above command from MSBuild, then no match is detected. This worked before with MSBuild 14.0.23107.0.

But when using findstr instead of find there is no issue with  MSBuild 14.0.24720.0.
```Batchfile
echo abc | findstr /L "b"
```

see https://gist.github.com/bluerobotch/5d160080dba4400e2c6b for a full example.

**Comment by bluerobotch** [comment]
By the way, is there an official source for the Build Tools 2015 "Update 1" (The build tools installed with visual studio 2015 update 1)?

I can only find the Build Tools 2015 download:
https://www.microsoft.com/en-us/download/details.aspx?id=48159

**Comment by rainersigwald** [comment]
Thanks for the report (and the nice repro)! This (like #397) is more fallout from the change in #143 to change the default codepage of the `cmd.exe` shell spawned by the `Exec` task. Your workaround is a good one.

As with the others, you should also be able to work around the problem by running

```cmd
chcp 437
```

at the beginning of the Exec's `Command` or in the batch file that you're calling.  I confirmed that `find.exe` does use the current console codepage to determine what string conversions to apply--though I'm still confused about exactly what's going wrong in this case.

**Comment by rainersigwald** [comment]
There is no standalone update for the Build Tools package, but my understanding is that if you install Build Tools 2015 and then run the Update 1 installer, you'll get an updated MSBuild.

**Comment by bluerobotch** [comment]
@rainersigwald thanks for the quick response. Its a good thing to know that MSBuild now executes commands using the utf-8 code page when running on hosts with >= win7. 
As i understand it's more a problem with `find.exe` than with MSBuild. Therefore we will keep our workaround.

Concerning Update 1, thanks pointing that out.

**Comment by rainersigwald** [comment]
Thanks for following up. I'm going to leave this issue open for now as we decide whether or not to adjust the codepage policy going forward.

**Comment by rainersigwald** [comment]
Incidences of this should have been reduced with #442 and Build Tools 2015 Update 2.
