### ISSUE TITLE
PackageReferences build packages are not referenced

### ISSUE THREAD

**Issue by TFTomSun** [Microsoft/msbuild#4063]
I've created a build package (a nuget package with build/*.props and build/*.target files). Unfortunately all PackageReferences that I add to the build package (e.g. in the .props file) are not processed at all during build.

Steps to reproduce:
* Create a build package
* add a package reference to the build package (e.g. in the props file) (for example package reference to MyLibrary)
* pack and push the build package
* reference the build package in some other project (e.g. HelloWorld)

Expected behavior:
- HelloWorld restores and references MyLibrary during build 
Actual behavior:
- The PackageReference to MyLibrary is not considered at all

**Comment by rainersigwald** [comment]
It's not possible to recursively reference packages in this way.

The core problem is that doing this would require restoring multiple times. The first restore would bring down the build package, which adds a new ProjectReference, but the new ProjectReference wouldn't be restored. You would then have to restore again with the partially-restored project, to see the new PackageReference. It could then repeat the process.  To avoid this, NuGet does not include build logic from packages when restoring.

One alternative would be to define a package-level dependency on the package with `build/` files. Then restore will bring down its transitive closure, including the library package.

I'm going to move this to the NuGet repo; I couldn't find an issue there to duplicate it against and they may have some more input.

**Comment by rainersigwald** [comment]
This issue was moved to NuGet/Home#7687
