### ISSUE TITLE
RoslynCodeTaskFactory cannot find compiler in VS2019

### ISSUE THREAD

**Issue by huoyaoyuan** [Microsoft/msbuild#4069]
### Steps to reproduce
Just follow the default doc instructions at https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-roslyncodetaskfactory?view=vs-2017#hello-world

### Expected  behavior
Compiles

### Actual behavior
`error MSB4175: The task factory "RoslynCodeTaskFactory" could not be loaded from the assembly "C:\Program
 Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\bin\Microsoft.Build.Tasks.Core.dll". The task factory must return a value for the "TaskType" property`

### Environment data
`msbuild /version` output: 16.0.218.25180

OS info:
Windows 10 Insider Pro 18312.1001
If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):
Both VS2017(15.9.5) and 2019(Preview 1.1) are installed.

After investigating code, https://github.com/Microsoft/msbuild/tree/99997527ab8314a9f305701af7efb40a228ff3d2/src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactoryCompilers.cs#L26-L38 , `RoslynCodeTaskFactory` attempts to find a `Roslyn` directory siding to `MSBuild.exe`. It exists for VS2017, but doesn't exist for VS2019.

![image](https://user-images.githubusercontent.com/5644458/51089079-271f1500-17a2-11e9-995e-11916ef0d25a.png)
![image](https://user-images.githubusercontent.com/5644458/51089084-3736f480-17a2-11e9-9520-eca645df2a17.png)

**Comment by pieandcakes** [comment]
We are noticing a similar issue attempting to determine where `csc.exe` is by using `MSBuildBinPath` to locate the `Roslyn` folder and then subsequently `csc.exe`. Do we know if this will be fixed for Dev16 or do I need to find another way to locate `csc.exe` in my target?

**Comment by rainersigwald** [comment]
This is fixed in to-be-released-in-preview4 internal VS builds now, with https://github.com/dotnet/roslyn/pull/33114 and the corresponding #4138. Thanks for the reports!

@pieandcakes that fix moves `csc.exe` to the same relative position from `MSBuildBinPath` that it had in dev15, so your stuff should start working again too.

**Comment by pieandcakes** [comment]
@rainersigwald Thanks. I added a variable for the Roslyn tools location to unblock me. Should i remove it now or rely on that location going forward?

**Comment by rainersigwald** [comment]
I don't think we _plan_ to move it again, but it'll be a little while before p4 is easily available . . .
