### ISSUE TITLE
Msbuild raise an error: The element <Import> beneath element <When> is unrecognized

### ISSUE THREAD

**Issue by moh-hassan** [Microsoft/msbuild#4070]
Environment:
Msbuild version 15.9.21
Visual studio: Vs2017.9.2

In C# project using SDK style, I try to import props project based on condition using the following xml fragment:

        <Project Sdk="Microsoft.NET.Sdk">
           

           <PropertyGroup>
             <TargetId>abc</TargetId>
             <OutputType>Exe</OutputType>
            </PropertyGroup>

      <Choose>
        <When Condition="$(TargetId) == 'xyz'">
         
          <Import Project="$(MSBuildThisFileDirectory)projectxyz.props"/>    
        </When>
        <Otherwise>
         
          <Import Project="$(MSBuildThisFileDirectory)projectAbc.props"/>
        </Otherwise>
      </Choose>

      </Project>

Vs2017 fail to load the project with errors:

    error  : The element <Import> beneath element <When> is unrecognized.   
    error  : The element <Import> beneath element <Otherwise> is unrecognized.  

The documentation permit using Import with Choose. See the last line in the [note](https://docs.microsoft.com/en-us/visualstudio/msbuild/import-element-msbuild?view=vs-2017)

What's I missed or wrong with this code?

**Comment by rainersigwald** [comment]
Looks like the documentation is wrong and putting an Import under a Choose has never been supported.

```
s:\msbuild>C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe choose-import.proj
Microsoft (R) Build Engine version 4.7.3190.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 1/14/2019 3:32:59 PM.
Project "s:\msbuild\choose-import.proj" on node 1 (default targets).
s:\msbuild\choose-import.proj(3,5): error MSB4067: The element <Import> beneath element <When> is unrecognized.
Done Building Project "s:\msbuild\choose-import.proj" (default targets) -- FAILED.


Build FAILED.

"s:\msbuild\choose-import.proj" (default target) (1) ->
  s:\msbuild\choose-import.proj(3,5): error MSB4067: The element <Import> beneath element <When> is unrecognized.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.11

s:\msbuild>C:\Windows\Microsoft.NET\Framework\v2.0.50727\MSBuild.exe choose-import.proj
Microsoft (R) Build Engine Version 2.0.50727.9031
[Microsoft .NET Framework, Version 2.0.50727.9035]
Copyright (C) Microsoft Corporation 2005. All rights reserved.

s:\msbuild\choose-import.proj(5,7): error MSB4067: The element <Import> beneath element <When> is unrecognized.
```

I can't think of a good reason for this other than "never got around to it", but I also don't place a high priority on supporting it, since the alternative is pretty straightforward:

```xml
     <!-- it has <TargetFramework> element net45 -->
      <Import Condition="$(TargetId) == 'xyz'" Project="$(MSBuildThisFileDirectory)projectxyz.props"/>    
      <Import Condition="$(TargetId) != 'xyz'"  Project="$(MSBuildThisFileDirectory)projectAbc.props"/>
```

**Comment by moh-hassan** [comment]
I used the alternative

      
      <Import Condition="$(TargetId) == 'xyz'" Project="$(MSBuildThisFileDirectory)projectxyz.props"/>    
      <Import Condition="$(TargetId) != 'xyz'"  Project="$(MSBuildThisFileDirectory)projectAbc.props"/>

But this  code is working fine if I run msbuild from commandLine:

                msbuild myproject.cs  /t:build  /p:TargetId=xyz

But it's not working from within vs2017 IDE when  I click build.

It's noted in the [documentation](https://docs.microsoft.com/en-us/visualstudio/msbuild/import-element-msbuild?view=vs-2017)
>While conditional import statements work in command-line MSBuilds, they do not work with MSBuild in the Visual Studio integrated development environment (IDE).

Is this a bug in visual studio 2017.9?

**Comment by livarcocc** [comment]
@moh-hassan would you mind filling an issue on microsoft/docs to fix the documentation?

**Comment by moh-hassan** [comment]
@livarcocc , I filled an [issue ](https://github.com/MicrosoftDocs/visualstudio-docs/issues/2210)on microsoft/docs to fix the documentation
