### ISSUE TITLE
Warn when Restore target encounters packages.config projects

### ISSUE THREAD

**Issue by PhilipDaniels** [Microsoft/msbuild#4071]
### Steps to reproduce

I have a sample project which I was attempting to build (on a Bamboo CI machine) using these steps:

```
msbuild /t:restore;build
```

This gave an error

```
This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.1\build\net46\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props.
```

I then tried changing the build step to

```
msbuild /restore /t:build
```

and still got the same error. 
I then tried using two build steps instead of one

```
msbuild /t:restore
msbuild /t:build
```

or 

```
msbuild /restore
msbuild /t:build
```

But the same error persisted. Finally I had to change the build to do

```
nuget.exe restore
msbuild /t:build
```

And the solution then builds successfully.

### Environment data

MSBuild Version: Microsoft (R) Build Engine version 15.8.169+g1ccb72aefa for .NET Framework

NuGet Version: 4.4.1.4656
MSBuild auto-detection: using msbuild version '15.8.169.51996' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\bin'.

OS info: Windows Server 2012 (probably R2, not sure though)

Bamboo CI server

### References
https://github.com/Microsoft/msbuild/issues/3000#issuecomment-417675215
and https://github.com/Microsoft/msbuild/issues/2811 

### Followup
The solution, projects and builds logs contain proprietary information and I cannot paste them here. If there is something specific you want from the log I can probably extract that.

**Comment by rainersigwald** [comment]
Does the project reference NuGet packages with `PackageReference` items, or the older `packages.config` file? The latter is only supported with an explicit `nuget.exe restore`, which was the only option at the time it was current. Since then, `PackageReference` has been added, enabling the smoother `msbuild /restore` experience.

**Comment by rainersigwald** [comment]
This issue was moved to NuGet/Home#7799
