### ISSUE TITLE
Add private scopes for properties and items

### ISSUE THREAD

**Issue by cdmihai** [microsoft/msbuild#4074]
We've talked about this many times, but I can't find an issue for it, so here it goes.

Many MSBuild targets create properties and items with the only purpose to process data from other properties and items. In many cases, this target created state is not used afterwards. However, the new state declared in targets becomes part of the global state, thus polluting and bloating it.

A larger scope than targets, but still not global, is the state declared in a project file, with the intent for it to be consumed just in that project file.

Adding a private modifier that introduces a new scope that gets cleaned on exit would be interesting to experiment with. Perf wise it could provide improvements in memory reduction (e.g. transient items that process globbing results) and speedup global state lookups. Usability wise, it could end the proliferation of global state, thus reducing complexity by reducing the chances of accidental coupling between project files.

**Comment by erwinbonsma** [comment]
This appears to be a duplicate of [#2480 ](https://github.com/microsoft/msbuild/issues/2480).

Btw, I would like to see this feature implemented.

**Comment by cdmihai** [comment]
Duplicate of  #2480
