### ISSUE TITLE
WriteCodeFragment should be deterministic and not include timestamp in comments

### ISSUE THREAD

**Issue by jaredpar** [Microsoft/msbuild#408]
The `WriteCodeFragment` task includes a comment in the generated file that has the value `DateTime.Now` of when the file was generated.  This interferes with determinism compiles because it means every build of a project that uses `WriteCodeFragment` is guaranteed to have a file with a different checksum.  

Can we provide a way to disable this timestamp?  Or really can it just be removed by default from the task?  I don't think it provides much value.  It's a generated file that ideally no one is looking at.  If they are looking at it the timestamp is of questionable value because knowing when it was generated is less valuable than knowing the inputs that generated it (at least IMHO).  

Note: in many cases it doesn't directly affect determinism because it often doesn't include executable code, just attributes.  But even in those cases it makes it difficult to track down problems.

**Comment by VSadov** [comment]
I assume the task is a some kind of codegenerator. Should it activate only when inputs have changed?
There is a value in including the date stamp in the outs when code was _re_ -generated, but not otherwise.

**Comment by jaredpar** [comment]
@VSadov what does the timestamp give though?  These are almost always used for temporary files that are little more than build artifacts.  The timestamp for those just gives you a relative time in which the build was run.  

> There is a value in including the date stamp in the outs when code was re -generated, but not otherwise.

Even having this defeats determinism.  It means that two developers who build the same code on different machines will have different inputs passed to the compiler.  

If it wants to provide useful information about the source code why not include the checksum of the inputs it was generated off of?

**Comment by cdmihai** [comment]
Agreed, the timestamp should be removed from output. I updated the issue title.
Regarding incrementality, the target calling the task needs to have inputs / outputs defined (and issues submitted to the owners of target files with no input / outputs for the targets that call this task). I did a quick check and the msbuild owned targets that call this task are incremental (hopefully I got all of them :) )

**Comment by rainersigwald** [comment]
Team triage: unless someone can convince us otherwise, we think the timestamp should just be removed (and no option to add it back).

@jaredpar I marked this up-for-grabs, so it should be gotten to . . . eventually. If you'd like to contribute a fix feel free, and if you need it for a specific release (like Update 2?), please let us know.

**Comment by jaredpar** [comment]
@rainersigwald happy to do the work here.

Was looking through the docs.  Didn't see any guide onto how to run the unit tests.  Is there something I'm missing that I can look at?

**Comment by akoeplinger** [comment]
@jaredpar there's a page in the wiki that should have you covered: https://github.com/Microsoft/msbuild/wiki/Building%20Testing%20and%20Debugging#running-unit-tests

**Comment by jaredpar** [comment]
@akoeplinger doh, read right past that :frowning:  Thanks for pointing it out.
