### ISSUE TITLE
how to create .resources file using dotnet core on linux

### ISSUE THREAD

**Issue by tarekgh** [Microsoft/msbuild#4082]
_From @ramsubbaraoc on December 13, 2018 10:59_

On Windows we can use Resgen tool to generate .resources files from the text files. How can we achieve the same using dotnet core

_Copied from original issue: dotnet/corefx#34067_

**Comment by tarekgh** [comment]
_From @danmosemsft on December 14, 2018 22:58_

Do you need to generate them during a build? If so you would do `dotnet build` on your project file.

If you have to run resgen directly, I am not sure there is a way to do that on .NET Core. I see no `dotnet` comamnd for it. @livarcocc do you know?

**Comment by tarekgh** [comment]
msbuild own resgen in general. I am moving this issue to their repo.

**Comment by rainersigwald** [comment]
There is no `resgen.exe` equivalent on .NET Core, and there aren't any current plans to create one. If you have a strong use-case for such a tool, please let us know.

The MSBuild `GenerateResource` task can transform some inputs, but is limited--bringing it up to speed is #2221.

**Comment by livarcocc** [comment]
Given that we have no plans to support resgen.exe and that we already have an issue tracking improving the supported files by GenerateResource, I am going to close this issue.
