### ISSUE TITLE
Normal builds still run under devenv.exe in VS 16.0 Pre2

### ISSUE THREAD

**Issue by jeromelaban** [Microsoft/msbuild#4095]
### Steps to reproduce

When build [this solution](https://github.com/nventive/Uno/blob/master/src/Uno.UI.sln), and more specifically [this project](https://github.com/nventive/Uno/blob/master/src/Uno.UI/Uno.UI.csproj) under visual studio, the following message appear:

```
1>------ Build started: Project: Uno.UI (Uno.UI\Uno.UI), Configuration: Debug Any CPU ------
1>Building target framework: xamarinmac20
1>Building target framework: xamarinios10
1>Building target framework: net46
1>Building target framework: netstandard2.0
1>src\SourceGenerators\Uno.UI.Tasks\Content\Uno.UI.Tasks.targets(53,5): warning : The Uno.UI.Tasks build task is running under devenv.exe you will have to restart Visual Studio to rebuild it.
1>Done building project "Uno.UI.csproj".
1>src\SourceGenerators\Uno.UI.Tasks\Content\Uno.UI.Tasks.targets(77,5): warning : The Uno.UI.Tasks build task is running under devenv.exe you will have to restart Visual Studio to rebuild it.
1>Done building project "Uno.UI.csproj".
```

This message is [produced by this task](https://github.com/nventive/Uno/blob/950bf7f581c13dd99c0bc0215322ba0528f535df/src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets#L106) to warn the user of a devenv.exe locked task.

I tried reproducing using a smaller sample, but could not get it.

### Environment data
`msbuild /version` output:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview>msbuild /version
Microsoft (R) Build Engine version 16.0.360-preview+g9781d96883 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.0.360.33175
```

OS info:
```
Microsoft Windows [Version 10.0.17134.472]
(c) 2018 Microsoft Corporation. All rights reserved.
```

**Comment by davkean** [comment]
This issue was moved to dotnet/project-system#4494
