### ISSUE TITLE
Solution does not builds under VS 2019 preview 2

### ISSUE THREAD

**Issue by sylveon** [Microsoft/msbuild#4096]
### Steps to reproduce

After updating to VS 2019 preview 2, the solution in https://github.com/TranslucentTB/TranslucentTB (branch master) doesn't builds anymore.

Command line
```
msbuild
```
### Expected  behavior

The solution builds

### Actual behavior

It outputs something akin to for each project in the solution without building:

```
The "Configuration" property is a global property, and cannot be modified.
The "Configuration" property is a global property, and cannot be modified.
The "SolutionDir" property is a global property, and cannot be modified.
The "SolutionExt" property is a global property, and cannot be modified.
The "Configuration" property is a global property, and cannot be modified.
The "SolutionName" property is a global property, and cannot be modified.
The "SolutionFileName" property is a global property, and cannot be modified.
The "SolutionPath" property is a global property, and cannot be modified.
The "SolutionDir" property is a global property, and cannot be modified.
The "SolutionExt" property is a global property, and cannot be modified.
Project "C:\Projects\tmp\TranslucentTB\TranslucentTB.sln" (1) is building "C:\Projects\tmp\TranslucentTB\TranslucentTB\TranslucentTB.vcxproj" (2) on node 1 (default targets).
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(775,5): error : The OutputPath property is not set for project 'TranslucentTB.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='Win32'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\Projects\tmp\TranslucentTB\TranslucentTB\TranslucentTB.vcxproj]
Done Building Project "C:\Projects\tmp\TranslucentTB\TranslucentTB\TranslucentTB.vcxproj" (default targets) -- FAILED.
```

### Environment data
```
Microsoft (R) Build Engine version 16.0.360-preview+g9781d96883 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.0.360.33175
```

OS info:

Visual Studio 2019 Preview 2 developer command prompt. Windows 10 Enterprise Insider Preview (build 18317)

**Comment by rainersigwald** [comment]
I can't reproduce this with https://github.com/TranslucentTB/TranslucentTB/commit/833ae80fe3040177c933b2a7ef362c421b10f7ed. I get this failure, which seems to be after what you're reporting:

```
Build FAILED.

"C:\TranslucentTB\TranslucentTB.sln" (default target) (1) ->
"C:\TranslucentTB\TranslucentTB\TranslucentTB.vcxproj" (default target) (2) ->
"C:\TranslucentTB\CPicker\CPicker.vcxproj" (default target) (3) ->
(ClCompile target) ->
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\windows.h(167): fatal error : 'excpt.h' file not found
 [C:\TranslucentTB\CPicker\CPicker.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:12.74
```

Can you capture and share a binary log? Please look at https://gist.github.com/dsplaisted/b256d7804672a6f6375476a5f5658b7b for instructions and caveats.

**Comment by sylveon** [comment]
I've created a binary log for both master and develop (where the issue also occurs) but I did not manage to get anything interesting out of it: [binlogs.zip](https://github.com/Microsoft/msbuild/files/2793722/binlogs.zip)

Note that for building `develop` on VS 2019, a patched platform toolset is required: https://reviews.llvm.org/D56034

**Comment by sylveon** [comment]
Changing the platform toolset to v142 seems to have fixed it, it's a bug in the llvm toolset.

**Comment by rainersigwald** [comment]
Thanks for following up!

**Comment by rolandh** [comment]
I am having a similar issue here with the same errors in the bin log. I've attached bin logs to the issue. Is this the same bug or a different one?
https://developercommunity.visualstudio.com/content/problem/817870/intellisense-lag-and-huge-number-of-false-red-squi.html?childToView=832130#comment-832130
