### ISSUE TITLE
Consider supporting .slnf solution filters

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/msbuild#4097]
This is a new feature in VS: https://docs.microsoft.com/en-us/visualstudio/ide/filtered-solutions?view=vs-2019. MSBuild doesn't understand `.slnf` files so you can't build them at the command line, but I assume (without looking into it at all) that it would be possible to build a solution metaproject using a `.slnf` and its `.sln` and build it.

**Comment by snow-jallen** [comment]
Yes please!  We currently have several different solution files that we use for building different subsets of our code base in different CI/CD pipelines.  It would be *really* nice to just have a single sln file with different .slnf definitions.

**Comment by Postlagerkarte** [comment]
Any news on this?

**Comment by GearedToWar** [comment]
This is coming up repeatedly as an ask from customers who are giving us feedback about solution filters. Please consider adding this support.

**Comment by snow-jallen** [comment]
Very happy to see progress made on this issue. :)  Thank you!

**Comment by dnperfors** [comment]
Did this feature actually land in 16.6?
I just installed VS 16.6 and started a build for an .slnf file and i got the following error:
```
error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.
```

**Comment by Forgind** [comment]
No 😢 
Now I'm hoping to get it in 16.7

**Comment by s-bauer** [comment]
@rainersigwald In which version of msbuild is this going to land?

**Comment by Forgind** [comment]
16.7 (Preview 3 to be precise)
