### ISSUE TITLE
Add GetFileHash and VerifyFileHash tasks to XSD (for IntelliSense)

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/msbuild#4103]
_Reported by @japj in https://github.com/Microsoft/msbuild/pull/3999#issuecomment-458141311._

#3398 exposed two new tasks, but they're not exposed to Visual Studio's autocompletion because they're not mentioned in the XSD used for that.

They need an entry like

https://github.com/Microsoft/msbuild/blob/966cdf2ac602e359530ad63f608e6cbba9c9fd0f/src/MSBuild/Microsoft.Build.CommonTypes.xsd#L2198-L2211

but with the right inputs/outputs.

**Comment by santoshyadav198613** [comment]
Hi @rainersigwald ,

Will work on it, first time contributor here so may need some help.

**Comment by rainersigwald** [comment]
Sounds good! Removing up-for-grabs; this is @santoshyadav198613's.

Let us know if you run into trouble!

**Comment by santoshyadav198613** [comment]
HI @rainersigwald ,

Just one help, should i add the schema at the end in the file, or should i add in it TASKS section like others.
Is there any pattern we follow here.

**Comment by rainersigwald** [comment]
I'd say in that TASKS section, sorted alphabetically by task name.

**Comment by santoshyadav198613** [comment]
Cool sounds good will make the changes accordingly.
