### ISSUE TITLE
How to do GetDirectoryNameOfDirectoryAbove?

### ISSUE THREAD

**Issue by japj** [Microsoft/msbuild#4106]
Question or feature request.

How can I (with a buildin MSBuild mechanism) find a parent directory like with GetDirectoryNameOfFileAbove.

Example scenario would be to find the parent .tf or .git folder in order to determine the repository root folder without depending on other content.

Or is there a generic way to do this differently with MSBuild?

**Comment by japj** [comment]
Nevermind, I can look for .tfignore/.gitignore

**Comment by Esgariot** [comment]
In my case I don't have a .gitignore near .git, would still like to navigate to vcs repo root
