### ISSUE TITLE
Need trim start whitespace per line in string of $@ format

### ISSUE THREAD

**Issue by chenyj796** [Microsoft/msbuild#4110]
### Steps to reproduce

When I declare a string in a method as below:
``` csharp
void Test()
{
    var str = $@"
line one
line two
";
}
```

I hope it can be writen as below:
``` csharp
void Test()
{
    var str = $@"
          line one
          line two
         ";
}
```
and the compiler can auto remove the leading whitespace if I add a property in the csproj file, such as:
``` xml
<TrimStartWhitespaceForStringDeclaration>true</TrimStartWhitespaceForStringDeclaration>
```

### Environment data
`msbuild /version` output:

OS info:

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):

**Comment by rainersigwald** [comment]
This issue was moved to dotnet/roslyn#32965

**Comment by rainersigwald** [comment]
Moved since this is a C# language feature request. If the C# team takes it up, it might need MSBuild changes, but they would come after compiler support.
