### ISSUE TITLE
MSBuild messages for Global Properties in stock vcxproj projects

### ISSUE THREAD

**Issue by prashantchahar** [Microsoft/msbuild#4112]
### Steps to reproduce

Create a C++ console application e.g CP1.vcxproj with Dev16 Preview 2.
Open Developer Command prompt
run following command

msbuild CP1.vcxproj /p:Configuration=Debug /p:Platform=win32

### Expected  behavior
No Warning or Errors

### Actual behavior
The "Configuration" property is a global property, and cannot be modified.
The "Platform" property is a global property, and cannot be modified.
The "Configuration" property is a global property, and cannot be modified.
The "Configuration" property is a global property, and cannot be modified.
The "Configuration" property is a global property, and cannot be modified.

### Environment data
Microsoft (R) Build Engine version 16.0.360-preview+g9781d96883 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
OS info: Latest Windows 10

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):

**Comment by rainersigwald** [comment]
These messages (nit: they're not warnings) were added in #3958. Firing for all C++ projects and also solution builds may mean we need to turn the verbosity down as we thought we might need to.

cc @livarcocc

**Comment by jeffkl** [comment]
👍 from me, my restore contains hundreds of these messages for large repos.

**Comment by rolandh** [comment]
Is this related to our issue? We have the same errors in our bin logs and intellisense is completely broken.
https://developercommunity.visualstudio.com/content/problem/817870/intellisense-lag-and-huge-number-of-false-red-squi.html?childToView=832130#comment-832130

**Comment by rainersigwald** [comment]
@rolandh I doubt it; this is an informational message that doesn't change any behavior relative to how it was before.
