### ISSUE TITLE
Build downloads proprietary .NET SDK package

### ISSUE THREAD

**Issue by JL2210** [Microsoft/msbuild#4116]
When building MSBuild from source, a proprietary .NET SDK package is downloaded, which may be unsuitable in some environments.

Solution: Allow to use system .NET implementation or use Mono.

**Comment by livarcocc** [comment]
Which package are you referring to?

**Comment by JL2210** [comment]
`build.sh` first downloads https://dot.net/v1/dotnet-install.sh, which then proceeds to download https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.401/dotnet-sdk-2.1.401-linux-x64.tar.gz.

**Comment by livarcocc** [comment]
That's the .NET Core SDK and it is as proprietary of Microsoft and MSBuild itself is. We have no plans to remove this dependency.
