### ISSUE TITLE
Hide "Project X (#) is building Y (#) on node # (TARGET targets)." logging messages on [/v:normal]

### ISSUE THREAD

**Issue by d0ru** [Microsoft/msbuild#413]
Example project build with (default) normal verbosity level:

    Project "PATH\build.proj" on node 1 (default targets).
    Project "PATH\build.proj" (1) is building "PATH\build.proj" (1:2) on node 1 (ENTRY target(s)).
    Project "PATH\build.proj" (1:2) is building "PATH\build.proj" (1:3) on node 1 (TARGET target(s)).
    TARGET:
      [some messages from TARGET]

I propose to hide the "node #" lines on "normal" verbosity level, thus display it only on "/v:d" or "/v:diag".
In most cases these "building on node" lines are noise, the target name presents enough information.

Thanks

**Comment by rainersigwald** [comment]
Thanks for the suggestion!

Team triage: this is reasonable in isolation, but we're worried about changing the log format in this way, given that we know many people have MSBuild log parsers. We think that the risks of this change are likely to outweigh the benefits.

**Comment by d0ru** [comment]
Really? MSBuild log parsers should already treat this case for /v:minimal.
In general, log parsers are affected by new content not by less content/removed lines.
