### ISSUE TITLE
Error during SDK resolution has no code

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/msbuild#4135]
_Reported offline by @lifengl._

> When a solution happens to have a global.json and points to some SDK not installed, CPS will fail to load the project with some confusing message (something like “incomplete project”).  If I use msbuild command line, it will produce a much understandable message string, like:
> 
> ```
> D:\Sources\CpsDBG\src\CpsDbgCore\CpsDbgCore.csproj : error : Unable to locate the .NET Core SDK. Check that it is installed and that the version specified in global.json (if any) matches the installed version.
> ```
> 
> we did get this build event to tell us that the SDK cannot be resolved.  But there is no code or anything, which is not localized for us to identify this message.  Can msbuild carry a meaningful code in this case?
> 
> ```
> {Microsoft.Build.Framework.BuildErrorEventArgs}
>     BuildEventContext: {Microsoft.Build.Framework.BuildEventContext}
>     Code: null
>     ColumnNumber: 0
>     EndColumnNumber: 0
>     EndLineNumber: 0
>     File: "C:\\s\\CpsDBG\\src\\CpsDbg\\CpsDbg.csproj"
>     HelpKeyword: null
>     LineNumber: 0
>     Message: "Unable to locate the .NET Core SDK. Check that it is installed and that the version specified in global.json (if any) matches the installed version."
>     ProjectFile: null
>     SenderName: "MSBuild"
>     Subcategory: null
>     ThreadId: 53
>     Timestamp: {2/4/2019 12:33:31 PM}
>     _localTimestamp: {2/4/2019 12:33:31 PM}
>     arguments: null
>     buildEventContext: {Microsoft.Build.Framework.BuildEventContext}
>     code: null
>     columnNumber: 0
>     endColumnNumber: 0
>     endLineNumber: 0
>     file: "C:\\s\\CpsDBG\\src\\CpsDbg\\CpsDbg.csproj"
>     helpKeyword: null
>     lineNumber: 0
>     locker: {object}
>     message: "Unable to locate the .NET Core SDK. Check that it is installed and that the version specified in global.json (if any) matches the installed version."
>     originalCultureInfo: {en-US}
>     originalCultureName: "en-US"
>     projectFile: null
>     senderName: "MSBuild"
>     subcategory: null
>     threadId: 53
>     timestamp: {2/4/2019 8:33:31 PM}
> ```
>
> BTW, we didn’t get an exception in this scenario, because we set flags like `MSBuild.ProjectLoadSettings.IgnoreMissingImports | MSBuild.ProjectLoadSettings.IgnoreInvalidImports`.

**Comment by nguerrera** [comment]
Can we not preserve anything with Build*Error*EventArgs and use it in the ultimate message? Like as the shortest term fix, just append all build error events to the "project file is incomplete" message. Are there any errors that we want to suppress entirely here?

**Comment by rainersigwald** [comment]
Going with @nguerrera's plan for 16.0.

**Comment by livarcocc** [comment]
Just talked to @nguerrera. He mentioned this has been implemented in CPS actually.
