### ISSUE TITLE
Version UserExtensionsPath imports with VisualStudioVersion

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#4149]
Suggested by @duncanp-sonar in https://github.com/Microsoft/msbuild/issues/3778#issuecomment-460638770

> The discussion above mentions `MSBuildExtensionsPath` but it doesn't mention `MSBuildUserExtensionsPath`. This change looks like it will break the per-user extension mechanism.
> 
> `MSBuildUserExtensionsPath` is in the form `C:\Users\[user id]\appdata\local\Microsoft\msbuild` so it is shared by all instances of MSBuild on the machine. Changing `MSBuildToolsVersion` to `Current` will break existing extensions, and it will also break the ability for per-user extension targets to be versioned by folder.
> 
> e.g. `ImportUserLocationsByWildcardBeforeMicrosoftCommonTargets` from `Microsoft.Common.CurrentVersion.targets`:
> 
> ```
> <Import Project="$(MSBuildUserExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.targets\ImportAfter\*" Condition="'$(ImportUserLocationsByWildcardAfterMicrosoftCommonTargets)' == 'true' and exists('$(MSBuildUserExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.targets\ImportAfter')"/>
> ```
> Per-user extension targets are important to third-party extensions as they allow targets to be injected into the build without requiring elevation (e.g. the _[Sonar Scanner for MSBuild](https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+MSBuild)_ that provides build integration with _[SonarQube/SonarCloud](https://sonarcloud.io/dashboard?id=sonarscanner-msbuild)_);
> 
> Could this breaking change be avoided by changing the per-user location to use a different build variable (e.g. either `VisualStudioVersion` or a new variable)?

**Comment by rainersigwald** [comment]
I think we can switch that to `$(VisualStudioVersion)` with no noticeable impact other than things continuing to work.

**Comment by rainersigwald** [comment]
@jeffkl I feel like you might have an opinion on this.

**Comment by jeffkl** [comment]
I feel pretty strongly that `MSBuildToolsVersion` be `Current` for sure.  We could use `VisualStudioVersion` here instead or we could have a folder named `Current` and extensions start to check `MSBuildAssemblyVersion` from now on.  It might be worth it now so we don't have to keep having a folder for every version, which is the point of moving to `Current`.

**Comment by duncanp-sonar** [comment]
My main concern was that this was a breaking change that didn't appear to have been covered in the original ticket. Thinking about it further, I don't have a strong preference for either solution, as long as extenders have a clear versioning story that works across multiple versions of MSBuild.

I see the attraction in having a fixed folder name, and this would work for us as so far I think we've shipped the same `ImportBefore` target for each version.

However, I think `Current` is a very misleading name for a shared folder: I certainly wouldn't expect
`c:\Users\JohnSmith\AppData\Local\Microsoft\MSBuild\Current\Microsoft.Common.props\ImportBefore\` to be checked by multiple versions of MSBuild.

Changing the folder name to `Current` is a breaking change anyway, so it would perhaps be better to change it to something that is more descriptive e.g. `c:\Users\JohnSmith\AppData\Local\Microsoft\MSBuild\Current\Shared`.


#### Interaction with _-toolsversion:xxx_
I do have a question about how either solution would work in a future version. Is it still valid for the user to specify a different ruleset using `-toolsversion:xxx`, and if so what effect does that have on the `$(MSBuildToolsVersion)` property?

e.g. when running under MSBuild 17.0, a user specifies either `-toolsversion:16.0` or a custom toolset. If it is still valid to specify a toolset like this, then presumably neither `$(VisualStudioVersion)` nor `($MSBuildAssemblyVersion)` will tell extenders which toolset the user was targeting.

**Comment by rainersigwald** [comment]
> I see the attraction in having a fixed folder name, and this would work for us as so far I think we've shipped the same `ImportBefore` target for each version.

I think I'm now leaning toward leaving things as they are, based on this. If an extension author wants to condition an import in the future, they can put a file in Current that inspects `MSBuildAssemblyVersion` or `VisualStudioVersion` and import version-specific logic based on that.

> Is it still valid for the user to specify a different ruleset using `-toolsversion:xxx`, and if so what effect does that have on the `$(MSBuildToolsVersion)` property?

This is mostly obsolete now. You can choose a different toolsversion by finding a different (side-by-side installable) MSBuild/VS/BuildTools installation. If you have a custom toolset, it still defines MSBuildToolsVersion as it has.

**Comment by rainersigwald** [comment]
Closing "won't-fix" based on that reasoning (https://github.com/Microsoft/msbuild/pull/4152#issuecomment-461854792).

As always, we can reactivate if new information comes in.

**Comment by duncanp-sonar** [comment]
Thanks for looking into this @rainersigwald. The versioning story outlined in the comments works for us, although having a shared folder called _Current_ does seem weird.
