### ISSUE TITLE
Do .NET Core projects have MSBuild bug where DLL references from project dependencies are not copied into bin?

### ISSUE THREAD

**Issue by SurajGupta** [Microsoft/msbuild#4156]
For .NET Framework projects, MSBuild has (IMO a bug) an issue where, sometimes, DLL references in project dependencies are not copied to the bin folder. Here's a pretty full discussion of the issue: 
https://stackoverflow.com/questions/1132243/msbuild-doesnt-copy-references-dll-files-if-using-project-dependencies-in-sol

Is this also the case in .NET Core projects?

**Comment by wli3** [comment]
This is an effort in dotnet core SDK. https://github.com/dotnet/cli/issues/10061 it is merged to the branch for netcoreapp3.0 release
