### ISSUE TITLE
Publish command is treating .NET Framework web project with new SDK project file format as a .NET Core project

### ISSUE THREAD

**Issue by amybingzhao** [Microsoft/msbuild#4157]
### Steps to reproduce
1. start with an existing .NET Framework 4.6 solution that includes a web project
2. from the command line, run `msbuild -p:DeployOnBuild=true -p:WebPublishMethod=Package -p:PackageAsSingleFile=true` --> a zip is outputted with Content items and a bin folder containing relevant dll's
3. Convert the project to use the new csproj (but still running .NET Framework 4.6)
4. from the command line, run `msbuild -p:DeployOnBuild=true -p:WebPublishMethod=Package -p:PackageAsSingleFile=true` --> the .zip file that gets outputted contains the contents of the output directory (i.e. a bunch of dll's, views, and items we've specified to be copied to the output directory via the <CopyToOutputDirectory> tag), rather than Content items and the bin folder.

### Expected  behavior
a deployable zip w/ Content items, config-related fiels (e.g. web.config), and a bin folder w/ dll's

### Actual behavior
a zip w/ the contents of the output directory

### Environment data
`msbuild /version` output:
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

OS info:
Windows 7

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):
Visual Studio 2017 Professional Edition
dotnet CLI: version 2.1.2

**Comment by livarcocc** [comment]
This issue was moved to dotnet/cli#10727
