### ISSUE TITLE
GeneratePackageOnBuild doesn't work

### ISSUE THREAD

**Issue by chenyj796** [Microsoft/msbuild#4164]
### Steps to reproduce

I created a web project on .NET Core 3.0, and set it's OutputType to Library:

Project file
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <OutputType>Library</OutputType>
```

### Expected  behavior
Generate a .nupkg file: $(ProjectDir)$(PackageOutputPath)$(PackageId).$(PackageVersion).nupkg

### Actual behavior
No .nupkg file.
If I change the Sdk to "Microsoft.NET.Sdk.WindowsDesktop", it works fine.

### Environment data
` dotnet.exe --version` output:
3.0.100-preview-009812

OS info:
Windows 10 

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):

**Comment by livarcocc** [comment]
This is likely some limitation or option on the web sdk that prevents this property from working. Moving this to the websdk repo for initial investigation.

**Comment by livarcocc** [comment]
This issue was moved to aspnet/websdk#477
