### ISSUE TITLE
NuGet cant resolve F# 4.5 on Mac High Sierra (DotNetCore 2.2.1)

### ISSUE THREAD

**Issue by geoeo** [Microsoft/msbuild#4179]
### Steps to reproduce

1)Create vanilla F# project
2) restore will fail since NuGet cant resolve F# 4.5

I mentioned this [here] prior (https://github.com/Microsoft/visualfsharp/issues/5595)

Project file
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    # Uncomment this for fail
    <PackageReference Update="FSharp.Core" Version="4.3.4" />
  </ItemGroup>

</Project>
```

OS info: Mac High Sierra 10.13.6

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):

dotnet cli

**Comment by rainersigwald** [comment]
As mentioned in the [Microsoft/visualfsharp#5595](https://github.com/Microsoft/visualfsharp/issues/5595), this currently looks like a NuGet issue, not an MSBuild one. NuGet tracks issues at https://github.com/nuget/home.

One thought that may be worth trying: have you run `dotnet nuget locals --clear all`? ⚠ this is a destructive operation.

**Comment by geoeo** [comment]
it fixed. it thanks a lot!
