### ISSUE TITLE
"MSBuildExtensionsPath" in "Sdk.props" is empty

### ISSUE THREAD

**Issue by livarcocc** [Microsoft/msbuild#4184]
_From @baruchiro on February 17, 2019 8:18_

https://github.com/dotnet/sdk/blob/2eb6c546931b5bcb92cd3128b93932a980553ea1/src/Tasks/Microsoft.NET.Build.Tasks/sdk/Sdk.props#L31

I create an object of [`Microsoft.Build.Evaluation.Project`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.evaluation.project?view=netframework-4.7.2&viewFallbackFrom=netcore-2.1) with existing `.csproj` file path.
When I compile it in `net471` everything works fine.

If I compile it in `netcoreapp2.1`, the file `Sdk.props` throw an error because he search the file `Microsoft.Common.props` in current working directory (the folder of my executable dll) instead of in `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Microsoft.Common.props`.
I think it is because the `$(MSBuildExtensionsPath)` is empty.

If you think to answer that "this is not soppurted in *.net core*", I will happy to know how to evulate `.csproj` files in *.net core*.

_Copied from original issue: dotnet/sdk#2955_

**Comment by livarcocc** [comment]
This is a question about msbuild API usage, so I moved it here.

When evaluating the project, you need to set MSBuildExtensionsPath to the location where MSBuild is.

For instance, in the CLI, were we also use this API, we do so like this: https://github.com/dotnet/cli/search?l=C%23&q=MSBuildExtensionsPath

**Comment by baruchiro** [comment]
I invested the code, and I still don't understand who registers the environment variable "*MSBuildExtensionsPath*".
Can you help me with this?
Or maybe provide a library that can read, parse and evaluate `.cspro`j files in *.net Core*?

**Comment by rainersigwald** [comment]
@baruchiro [MSBuildLocator](https://github.com/Microsoft/MSBuildLocator) can help with that as of 1.2--can you try using the [newest package](https://github.com/Microsoft/MSBuildLocator/pull/51#issuecomment-463281861)? Instructions for using it can be found in the now-confusingly-named [Update an existing application for MSBuild 15
](https://docs.microsoft.com/en-us/visualstudio/msbuild/updating-an-existing-application) page.
