### ISSUE TITLE
Improve text of NoReferenceAssemblyDirectory error

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/msbuild#4202]
The existing message

https://github.com/Microsoft/msbuild/blob/99e150416ed43660782db8ea88b2d12135aca855/src/Tasks/Resources/Strings.resx#L2119-L2122

Can be very confusing, and doesn't have an actionable link.

This error is from

https://github.com/Microsoft/msbuild/blob/99e150416ed43660782db8ea88b2d12135aca855/src/Tasks/GetReferenceAssemblyPaths.cs#L249

Rewording (from me and @kathleendollard):

> MSB3644: The reference assemblies for .NETFramework,Version=v4.6.2 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

Leaving the space out of `.NETFramework,Version=v4.6.2` allows us to directly use `frameworkmoniker.ToString()`, but we might be able to do better using the fields of `frameworkmoniker`.

**Comment by KathleenDollard** [comment]
Thought I'd state directly that the developer packs link goes to the download archives.
