### ISSUE TITLE
NugetPackageRoot not getting set after package restore.

### ISSUE THREAD

**Issue by DevKumar4Git** [Microsoft/msbuild#4207]
I have a simple custom project file where I am using package reference to pull props & targets file from NuGet. This variable $(NuGetPackageRoot) is never set to global NuGet cache.  I am importing Common targets & props in my props & targets which I am trying to bring in via package reference.
 
<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
                <Name>MyProjName</Name>
                <ProjectGuid>32de6665-de71-4c85-aabc-d0696a45dbd9</ProjectGuid>
    
  <PropertyGroup>
    <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
  </PropertyGroup>
 
  <ItemGroup>
                <PackageReference Include="Microsoft.PowerApps.MSBuild.Tools" Version="0.1.0"/>
  </ItemGroup>
  
  <Import Project="$(NuGetPackageRoot)$(PackageName)/$(PackageVersion)/build/MyProp.props" 
    Condition="Exists('$(NuGetPackageRoot)$(PackageName)/$(PackageVersion)/build/MyProp.props')" />
  
  <Import Project="$(NuGetPackageRoot)$(PackageName)/$(PackageVersion)/build/MyTarget.targets" 
    Condition="Exists('$(NuGetPackageRoot)$(PackageName)/$(PackageVersion)/build/MyTarget.targets')" />
  
</Project>

**Comment by livarcocc** [comment]
Can you share the custom project file? Is it a sdk style project?

Why are you particularly interested in that Property?

**Comment by DevKumar4Git** [comment]
[myprojtype.zip](https://github.com/Microsoft/msbuild/files/2920789/myprojtype.zip)

**Comment by DevKumar4Git** [comment]
Attached the project file. This is a custom project type where I have my own props & targets file that I am pulling through a NuGet package & then importing it.

**Comment by DevKumar4Git** [comment]
I figured that this is getting set if I import Microsoft.Common.Targets & Microsoft.Common.Props file in my project file. I had the targets imported in my props & targets file. I am planning to move them to proj file.
