### ISSUE TITLE
ToolTask.cs replaces all backslashes with forward-slashes in response files

### ISSUE THREAD

**Issue by mellinoe** [Microsoft/msbuild#422]
See https://github.com/Microsoft/msbuild/blob/xplat/src/Utilities/ToolTask.cs#L1598

From some comments in the file, it seems like this is just a temporary workaround to get things up and running x-plat (i.e. to quickly normalize all file paths): https://github.com/Microsoft/msbuild/blob/xplat/src/Utilities/ToolTask.cs#L1510

``` CSharp
// This is a hack..!
```

I just wanted to point out that I think this is causing us some issues when compiling VB projects for us in the corefx repo. The VB response file has some define constants in it, and the values for those contain strings that are escaped with backslashes. For example:

```
-define: "CONFIG=\"Debug\"
```

When Tooltask runs, it normalizes it to this

```
-define: "CONFIG=/"Debug/"
```

This is no longer valid, and the VB compiler errors out. This is preventing us in corefx from building VB projects in x-plat builds. We only have one such project, so right now we just disabled the build for that when outside of Windows.

**Comment by rainersigwald** [comment]
https://github.com/Microsoft/msbuild/issues/137 for VB only is a subset of this.

**Comment by rainersigwald** [comment]
https://github.com/Microsoft/msbuild/pull/2114 provides two types of fix a mechanism for this: it avoids correcting slashes that precede a `"` character (which fixes the immediate VB define problem), and it provides a new method `AdjustCommandsForOperatingSystem` that an OS-aware `ToolTask` can override to either apply tool-specific heuristics or do nothing.

This doesn't fully solve the problem, but I don't know how much better we can do.

**Please comment on this issue if** you've found another tool that encounters this type of problem, or if you have an idea about how to make a fully general default implementation of `AdjustCommandsForOperatingSystem`.
