### ISSUE TITLE
Question: how to hook SDK into common targets mechanisms

### ISSUE THREAD

**Issue by japj** [Microsoft/msbuild#4222]
Hello,
I have run into a conceptual problem related to building my own MSBuild Sdk in combination with Microsoft.NET.Sdk based projects.

My MSBuild Sdk needs to hook into the PrepareForBuildDependsOn/BuildDependsOn/etc mechanisms to run certain targets as part of the build.

The key problem here seems to be related to import ordering related to `Microsoft.Common.CurrentVersion.targets` (which defines these properties and overwrites any previous values). This file is imported from Sdk.targets.

On https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2017 it is described how the `Project Sdk` is transformed into implicit imports of the Sdk props/targets.

Thus my own Sdk.targets file needs to be imported *after* setting PrepareForBuildDependsOn/BuildDependsOn/etc in `Microsoft.Common.CurrentVersion.targets`, so I can append to these values.

However if I include my Sdk reference in the csproj then it will be imported before `Microsoft.Common.CurrentVersion.targets` due to the implicit Sdk imports.

Is there a way to solve this from the csproj file?

I did notice that the Directory.Build.props/targets mechanism is done after this, but in this specific instance I really would like to know if it can be done without using that
(we have a mix of other/older projects that work correctly because they are not Microsoft.NET.Sdk based and I would like to limit the impact of the 'solution')

**Comment by japj** [comment]
This problem might be related/similar to #1680 but instead for after/beforebuild Targets this is actually about properties that get overridden by the import order in common targets.

**Comment by rainersigwald** [comment]
Have you tried setting (really _appending_, please, semicolon-delimited 🙂) the `CustomAfterMicrosoftCommonTargets` property to a path that contains your needs-to-tweak-properties-from-common-targets content?

https://github.com/Microsoft/msbuild/blob/5c48991b4affeed33eb52f4f4b7338065abe7de0/src/Tasks/Microsoft.Common.CurrentVersion.targets#L6091

**Comment by japj** [comment]
thanks! this indeed solves it in a clean way
