### ISSUE TITLE
Error MSB4216 when building a project that holds a reference to an x86 project with a resource file

### ISSUE THREAD

**Issue by dockell** [Microsoft/msbuild#4229]
The attached solution contains three projects:
- TestRandom, a simple .Net app that holds a reference to
- TestX86: a .Net app that has Platform Target set to x86 and has a resources file (with a single string resource)
- TestBuildProject: another simple .Net app that uses Microsoft.Build.Evaluation.Project.Build() to build TestRandom.

The full exception message is:
C:\Program Files (x86)\MSBuild\12.0\bin\amd64\Microsoft.Common.CurrentVersion.targets(2554,5): error MSB4216: Could not run the "GenerateResource" task because MSBuild could not create or connect to a task host with runtime "CLR4" and architecture "x86".  Please ensure that (1) the requested runtime and/or architecture are available on the machine, and (2) that the required executable "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe" exists and can be run.
C:\Program Files (x86)\MSBuild\12.0\bin\amd64\Microsoft.Common.CurrentVersion.targets(2575,7): error MSB4028: The "GenerateResource" task's outputs could not be retrieved from the "FilesWritten" parameter. Object does not match target type.

This is an example project cut down from the full project that I use to build a large number of utility dlls.

If the resource is removed from TestX86, TestBuildProject runs fine.
If TestX86's Platform Target is set to 'any' or 'x64', TestBuildProject runs fine.

My test machine is running 64-bit Windows 10, Version 10.0.17134 Build 17134

[TestRandom.zip](https://github.com/Microsoft/msbuild/files/2958154/TestRandom.zip)

**Comment by rainersigwald** [comment]
This is a symptom of an incomplete copy of MSBuild, which is arising because you reference some of the MSBuild packages but don't fully reconstruct an MSBuild environment.

But you don't want to have to do that! Instead, you can use the existing MSBuild environment on the machine. See the docs on [using MSBuildLocator to load MSBuild](https://docs.microsoft.com/en-us/visualstudio/msbuild/updating-an-existing-application) instead of directly referencing it in your application.

**Comment by dockell** [comment]
Thanks, Rainer, your suggestion worked. I'll try and close this now. Thanks for your help!

**Comment by LinqLover** [comment]
@rainersigwald In my project, I use a legacy DLL for which I don't have any further build files available so it is only `<Reference>`d in my `csproj` file using a `<HintPath>` to the plain DLL file. Is there any option to build the project anyway?
