### ISSUE TITLE
Error when signtool.exe can't be found should include the path we looked in

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#425]
[This line](https://github.com/Microsoft/msbuild/blob/98d38cbf34fe35142792556aff80cec08d7315cc/src/XMakeTasks/ManifestUtil/SecurityUtil.cs#L773) makes it hard to figure out *why* signtool appeared to be missing. We had an internal bug where the .exe was actually not present on disk, but the error was just:

```
1>Task "SignFile" (TaskId:43)
1>  Task Parameter:CertificateThumbprint=AAD0491335D003B4BAE60CCCEE28EC62600D224D (TaskId:43)
1>  Task Parameter:SigningTarget=bin\Debug\app.publish\\setup.exe (TaskId:43)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\OfficeTools\Microsoft.VisualStudio.Tools.Office.targets(609,9): error MSB3482: An error occurred while signing: SignTool.exe not found.
1>Done executing task "SignFile" -- FAILED. (TaskId:43)
```

Would have been nice to know where it was looking!

**Comment by nikson** [comment]
@rainersigwald, if search path add in message `SignTool.exe not found. Path: {0}`
and move the exception to nearest code, it should be OK

    if (!File.Exists(toolPath))
    {
          throw new ApplicationException(String.Format(CultureInfo.CurrentCulture, resources.GetString("SecurityUtil.SigntoolNotFound"), toolPath));
         .......

**Comment by rainersigwald** [comment]
@nikson Yes, that seems like a good approach. I was initially concerned that it didn't report everywhere we looked, but after looking at the code again, we actually only look in one place, so having an "audit trail" isn't necessary like I thought.

**Comment by stijnherreman** [comment]
It would be useful to have it list all attempted paths. Right now, you can get an error saying signtool.exe was not found at the current directory (e.g. the project root directory), but it's not clear that it first attempted to find signtool.exe in other directories.
