### ISSUE TITLE
Edcoding Property in WriteLinesToFile Task is missing from xsd and has incorrect definition

### ISSUE THREAD

**Issue by santoshyadav198613** [Microsoft/msbuild#4257]
### Steps to reproduce

Either include a project sample, attach a zipped project, or provide IDE / CLI steps to create the project and repro the behaviour. Example of a project sample:

 <xs:element name="WriteLinesToFile" substitutionGroup="msb:Task">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="msb:TaskType">
                    <xs:attribute name="Encoding" />
                    <xs:attribute name="File" use="required" />
                    <xs:attribute name="Lines" />
                    <xs:attribute name="Overwrite" type="msb:boolean" />
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>

Below 2 properties are missing from xsd , also notice the comment for Encoding
 /// <summary>
        /// If true, overwrite any existing file contents.
        /// </summary>
        public string Encoding { get; set; }

        /// <summary>
        /// If true, the target file specified, if it exists, will be read first to compare against
        /// what the task would have written. If identical, the file is not written to disk and the
        /// timestamp will be preserved.
        /// </summary>
        public bool WriteOnlyWhenDifferent { get; set; }
contents 

### Expected  behavior

The properties should exists in xsd and encoding property should have correct comment

### Actual behavior
properties missing from xsd and has incorrect definition for property

### Environment data
`msbuild /version` output:

OS info:

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):

**Comment by santoshyadav198613** [comment]
Let me know if this is valid , will open the PR.

**Comment by rainersigwald** [comment]
Looks like Encoding is there:

https://github.com/Microsoft/msbuild/blob/54f51302b719878aac2874359de7b754b9045ad4/src/MSBuild/Microsoft.Build.CommonTypes.xsd#L2956-L2960

But `WriteOnlyWhenDifferent` isn't.

It'd be great to fix this and the bad doc comment on `Encoding`. Please do the two changes in separate commits, since they're logically separable.

**Comment by santoshyadav198613** [comment]
ok please assign this to me i will raise a separate PR.

**Comment by santoshyadav198613** [comment]
PR https://github.com/Microsoft/msbuild/pull/4259 open please check
