### ISSUE TITLE
MSBuild.exe /? still shows /debug option

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#426]
We removed support for `/debug` in #163, but we didn't remove the help text that mentions it. We shouldn't tease people with a cut feature.

**Comment by nikson** [comment]
@rainersigwald, is it reasonable to remove `enum` value `ParameterlessSwitch.Debugger` from the set?

**Comment by rainersigwald** [comment]
@nikson My first inclination is to leave the enum value (and the string resource) while we have the code `#if`ed out. When we commit to removal we can clean it all up together.

**Comment by rainersigwald** [comment]
Fixed via #430. Thanks, @nikson.
