### ISSUE TITLE
Exec task writes invalid batch files on Windows 10 with beta feature enabled

### ISSUE THREAD

**Issue by AustinWise** [microsoft/msbuild#4268]
### Steps to reproduce

1. Enable "Beta: Use Unicode UTF-8 for worldwide support" option in Windows 10 system locale settings: https://1drv.ms/u/s!As3RYTwbfwtP3gTMBcyVXyqjSWdp
1. Reboot.
1. Try to use the `Exec` task.

I can't find any official documentation for this new Windows feature, just forum posts and tweets.

Project file
```xml
<Project>
  <Target Name="Build">
    <Exec Command="echo hi" />
  </Target>
</Project>
```

Directory contents:
```
/
- test.build
```

Command line
```
dotnet msbuild /nologo test.build
```
### Expected  behavior
```
  hi
```

### Actual behavior
```
  hi
  '?E?setlocal' is not recognized as an internal or external command,
  operable program or batch file.
```

### Environment data
`dotnet msbuild /version` output:
```
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

15.9.20.62856
```

OS info:
Windows 10.0.17763.379

### Workarounds

Set `UseUtf8Encoding="ALWAYS"` on the `Exec` task.

### Source of problem

One effect of this beta Windows feature is that `GetOEMCP` returns 65001 (meaning UTF-8). [`EncodingUtilities.CurrentSystemOemEncoding`](https://github.com/Microsoft/msbuild/blob/9cd77f3983fcce0da728565a3385ef49f011347b/src/Shared/EncodingUtilities.cs#L46) calls `GetOEMCP` to figure out the current system code page. [`Exec.BatchFileEncoding`](https://github.com/Microsoft/msbuild/blob/9cd77f3983fcce0da728565a3385ef49f011347b/src/Tasks/Exec.cs#L672-L690) uses this value by default when writing the a temporary batch file. cmd.exe does not like the UTF-8 BOM at the start of the batch file, causing extra text to be written.

**Comment by AustinWise** [comment]
From my perspective it looks like `Exec.BatchFileEncoding` needs to add some extra checking to make sure it is not using UTF-8 with BOM. Neither the Unix shell nor cmd.exe respond well to BOMs at the start of their scripts.

**Comment by rainersigwald** [comment]
Thanks for the report! I agree with your assessment that we should avoid writing BOMs. #4271 is my (as yet untested) attempt to do so. I shot an email to some internal cmd folks to see if there's a preferred way.

> the Unix shell

Fortunately, we should be covered here:

https://github.com/Microsoft/msbuild/blob/9cd77f3983fcce0da728565a3385ef49f011347b/src/Tasks/Exec.cs#L665-L670
