### ISSUE TITLE
VC compiler bug

### ISSUE THREAD

**Issue by cheblin** [Microsoft/msbuild#4274]
The following code works differently on latest VS compare to others compiler

```C
#include <stdbool.h>
#include <stdio.h>
typedef struct {
	int field;
} bar;

static int b = 0;

bool foo() {
	b++;
	return true;
}

int main()
{
	bar test = foo() ? (bar) { b } : (bar) { 0 };
	printf("%d", test.field);
}
```

https://rextester.com/ULJY22979 - VC print 0
https://rextester.com/XXPDHB19435 - CLANG - print 1
https://rextester.com/AYW77930 - GCC - print 1

according to:

 SO/IEC 9899:2018, 6.5.15.4:

The first operand is evaluated; there is a sequence point between its evaluation and the evaluation of the second or third operand (whichever is evaluated).

from my point of view, this behavior is bug

with best regards
Chikirev Sirguy

**Comment by rainersigwald** [comment]
Can you please use the Visual Studio Feedback tool to report the problem? That will route to the compiler team. Since this is a C++ compiler issue, the MSBuild repo isn't the right place for it.
