### ISSUE TITLE
Use custom match in FileUtilities.GetFullPath

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/msbuild#4283]
@davkean, @BenVillalobos and I were doing some exploratory PerfView analysis and noticed this.

#3969 tried to reduce the allocation of `Regex.Match` objects that aren't necessary because all we care about is `IsMatch`. That simplified the code greatly. But unfortunately, it still allocates a `Match` object under the covers.

We should replace usages of `FileUtilitiesRegex.DrivePattern`, `FileUtilitiesRegex.UncPattern`, `StartWithDrivePattern`, and `StartsWithUncPattern` with functions that do the match explicitly without allocation. The patterns are pretty straightforward, so the matcher methods should still be pretty readable.

**Comment by rainersigwald** [comment]
This will help with part of #2645.

**Comment by BenVillalobos** [comment]
This was fixed in #4304
