### ISSUE TITLE
Why is the MSBuild 16 assembly version still 15.1.0.0?

### ISSUE THREAD

**Issue by bording** [Microsoft/msbuild#4293]
I noticed that the MSBuild 16 binaries have `AssemblyFileVersion` and `AssemblyInformationalVersion` values that indicate they are version 16, but the `AssemblyVersion` is still 15.1.0.0.

I assume this was done for some sort of compatibility reason, but I'm curious about the specifics. Why couldn't you also bump it up to 16.0.0.0?

**Comment by rainersigwald** [comment]
Lots of details and discussion on this in https://github.com/Microsoft/msbuild/issues/3778.

**Comment by bording** [comment]
@rainersigwald Thanks for the link. I should have known the answer to my question was: binding redirects.

It's always binding redirects!
