### ISSUE TITLE
Error MSB3103: Invalid Resx file on Net Core 3.0 project

### ISSUE THREAD

**Issue by mikhailovalex** [microsoft/msbuild#4296]
### Steps to reproduce

Install latest netcore 3.0 SDK from [here](https://github.com/dotnet/core-sdk/blob/master/README.md#installers-and-binaries).  Run Visual Studio 2019. Ensure you turn on "Use previews of the .NET Core SDK". Try to rebuild an MSBuild_Fail.NetCore.Desktop.sln. You will see an error, although MSBuild_Fail.sln will be successfully built (.Net Framework).
Example of a project sample:
[MSBuild_Fail.zip](https://github.com/Microsoft/msbuild/files/3057486/MSBuild_Fail.zip)

### Expected  behavior
Successful build MSBuild_Fail.NetCore.Desktop.sln.

### Actual behavior
C:\Users\mikhailov.alexander\source\repos\MSBuild_Fail\WindowsFormsApp1\Form1.resx(123,5): error MSB3103: Invalid Resx file. Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058) Line 123, position 5.

### Environment data
`msbuild /version` output:
Microsoft (R) Build Engine version 16.0.461+g6ff56ef63c for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.0.461.62831

OS info:

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):
Visual Studio Professional 2019 Version 16.0.0
`dotnet --version` output:
3.0.100-preview4-011024

**Comment by lukashankeln** [comment]
I´m getting the same error, when I try to Upgrade to netcore3. On net471 it works fine.

Is there any workaround? Or any idea when this will be fixed?

### Environment

` msbuild /version `

Microsoft (R)-Build-Engine, Version 16.2.37902+b5aaefc9f for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.2.37902.0

` dotnet --version `

3.0.100-preview9-013959

**Comment by rainersigwald** [comment]
Please try to use the latest [preview](https://visualstudio.microsoft.com/vs/preview/) of Visual Studio 16.3.

The resource build process has changed in .NET Core, and requires both the latest SDK and the latest Visual Studio to successfully build from Visual Studio.

**Comment by rainersigwald** [comment]
I just tried the project in the OP with my latest bits that should go out with 3.0.100-preview9/Visual Studio 16.3-preview3, and it looks like it's working ok.

**Comment by lukashankeln** [comment]
You are right. I only used the latest SDK, but when I used Visual Studio 16.3-preview2 as well, it worked fine. 
Thanks a lot.

**Comment by rainersigwald** [comment]
Folks, please try with .NET Core SDK 3.0.100-preview9 and Visual Studio 16.3 preview 3. We believe all outstanding issues have been solved. Please file a new bug with any problems you encounter.
