### ISSUE TITLE
Depend on NuGet PackageGroup instead of NuGet.BuildTools

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#4307]
Internal bug: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/844554

Once it exists, we will need to retarget the MSBuild VSIX package to depend on the new NuGet PackageGroup, instead of:

https://github.com/Microsoft/msbuild/blob/0da7b4d3d9066daf43658fa09a13d1c299a02487/src/Package/MSBuild.VSSetup/files.swr#L8-L10

**Comment by zivkan** [comment]
The name of the new package group is Microsoft.VisualStudio.PackageGroup.NuGet
