### ISSUE TITLE
"salt" MSBuild handshake in test / dogfood environment

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/msbuild#4308]
_From @dsplaisted on Tuesday, 29 January 2019 01:54:52_

Right now for our tests (and in the dogfood script) we override the MSBuildSDKsPath to point MSBuild to the SDK under test.  However, this doesn't seem to prevent sharing MSBuild nodes that didn't have this set, which can end up causing assembly loading or other issues.

Ideally in our test environment we would add a "salt" to the node connection handshake, so that MSBuild would only be able to connect to nodes that come from the same test environment.

This would probably require a change in MSBuild to allow us to provide such a "salt".

@rainersigwald, thoughts?

_Copied from original issue: dotnet/sdk#2880_

**Comment by rainersigwald** [comment]
_From @rainersigwald on Tuesday, 29 January 2019 15:43:32_

I'd be on board with adding the value of a `MSBUILDNODEHANDSHAKESALT` environment variable to the handshake. I don't think it's generally useful, but for internal development and especially tests that require multiple invocations and need node reuse to be enabled it'd be nice.

**Comment by danmosemsft** [comment]
Would it work to just hash the path to msbuild.exe into the handshake? So parent and child must be the same binary. Perhaps I misunderstand because I thought it did this actually.

**Comment by dsplaisted** [comment]
@danmosemsft For the dotnet/sdk repo, we don't create an entirely new layout of the CLI for our test environment.  We use the stage 0 MSBuild, with environment variables that redirect to the SDK under test.  Because of this, we have to disable node reuse for our tests, to avoid them connecting to a stage 0 node.

**Comment by BenVillalobos** [comment]
@rainersigwald I recall you mentioning a possible issue with the implementation in #4337? 

If I'm misremembering, the issue should be closed.

**Comment by rainersigwald** [comment]
Oh man, I vaguely remember something there but not the details.

Perhaps it was that we should change the default to be path + version (to prevent intermixing same-sdk different-unzip-locations)? But we can leave the salt. I'm ok closing this.
