### ISSUE TITLE
MSB4018	“CopySources” task failed unexpectedly?

### ISSUE THREAD

**Issue by zuowanbushiwo** [microsoft/msbuild#4340]
System.NullReferenceException: Object reference not set to an instance of an object。
   在 Microsoft.Build.Linux.Tasks.RemoteToolTask.Execute()
   在 Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   在 Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	server	D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0\Linux.targets	162

**Comment by danmosemsft** [comment]
This looks most likely a bug in the C++ owned task. (?). @olgaark are those in another repo somewhere?

**Comment by livarcocc** [comment]
Looks like that to me as well. pinging @olgaark again to see what is the best way to track this.
