### ISSUE TITLE
After installing VS2019, msbuild fails to build msbuild tasks with error MSB4025

### ISSUE THREAD

**Issue by ljani** [Microsoft/msbuild#4341]
### Steps to reproduce

- Install VS2019
  - `msbuild build.msbuildproj` fails to build

`build.msbuildproj`:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="15.0">
  <Target Name="Build">
    <MSBuild Projects="msbuildissue.sln" ToolsVersion="15.0"/>
  </Target>
</Project>
```

`msbuildissue.sln`:
```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 15
VisualStudioVersion = 15.0.26124.0
MinimumVisualStudioVersion = 15.0.26124.0
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Debug|x64 = Debug|x64
		Debug|x86 = Debug|x86
		Release|Any CPU = Release|Any CPU
		Release|x64 = Release|x64
		Release|x86 = Release|x86
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
EndGlobal
```

Directory contents:
```
/
- build.msbuildproj
- msbuildissue.sln
```

Command line
```
Microsoft (R) Build Engine version 16.0.461+g6ff56ef63c for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\msbuild.exe /bl build.msbuildproj
Build started 30.4.2019 8.33.37.
Project "C:\devel\msbuildissue\build.msbuildproj" on node 1 (default targets).
Project "C:\devel\msbuildissue\build.msbuildproj" (1) is building "C:\devel\msbuildissue\msbuildissue.sln" (2) on node 1 (default targets).
C:\devel\msbuildissue\msbuildissue.sln(2,1): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 2, position 1.
Done Building Project "C:\devel\msbuildissue\msbuildissue.sln" (default targets) -- FAILED.

Done Building Project "C:\devel\msbuildissue\build.msbuildproj" (default targets) -- FAILED.

Deferred Messages

  Detailed Build Summary
  ======================


  ============================== Build Hierarchy (IDs represent configurations) =====================================================
  Id                  : Exclusive Time   Total Time   Path (Targets)
  -----------------------------------------------------------------------------------------------------------------------------------
  0                   : 0.065s           0.074s       C:\devel\msbuildissue\build.msbuildproj ()
  . 1                 : 0.009s           0.009s       C:\devel\msbuildissue\msbuildissue.sln ()

  ============================== Node Utilization (IDs represent configurations) ====================================================
  Timestamp:            1        Duration   Cumulative
  -----------------------------------------------------------------------------------------------------------------------------------
  636921992171909587:   0        0,061s     0,061s #
  636921992172519086:   1        0,009s     0,070s
  636921992172609045:   0        0,004s     0,074s
  -----------------------------------------------------------------------------------------------------------------------------------
  Utilization:          100,0    Average Utilization: 100,0

Build FAILED.

"C:\devel\msbuildissue\build.msbuildproj" (default target) (1) ->
"C:\devel\msbuildissue\msbuildissue.sln" (default target) (2) ->
  C:\devel\msbuildissue\msbuildissue.sln(2,1): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 2, position 1.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.09
```
### Expected  behavior

Solution will build. It worked with VS2017, but even installing VS2019 side-by-side breaks the build. Changing the versions to 16.0 does not help either.

### Actual behavior

Solution fails to build with MSB4025.

### Environment data
`msbuild /version` output:

```
Microsoft (R) Build Engine version 16.0.461+g6ff56ef63c for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.0.461.62831
```

OS info: Windows 10 Enterprise 1809 17763.437

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):
Developer command prompt for VS2019 16.0.2

EDIT: 
VS2019 builds the `msbuildissue.sln` correctly and `msbuild msbuildissue.sln` works very well.

**Comment by ljani** [comment]
Aha, *removing* the `ToolsVersion="15.0"` from `MSBuild` task works. Is there something to fix?

This will build without any problems when invoked via `<MSBuild />` task:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="15.0">
  <Target Name="Build">
    <MSBuild Projects="msbuildissue.sln" />
  </Target>
</Project>
```

This will fail when invoked via `<MSBuild />` task:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="16.0">
  <Target Name="Build">
    <MSBuild Projects="msbuildissue.sln" ToolsVersion="16.0"/>
  </Target>
</Project>
```

**Comment by rainersigwald** [comment]
> It worked with VS2017, but even installing VS2019 side-by-side breaks the build.

Can you elaborate on this, please? What error do you get when you build using MSBuild from VS2017 after the 2019 installation?

Other than that issue, which I'd like to investigate, I think the underlying problem here is #4319. Removing `ToolsVersion` from the MSBuild task is the right solution; fixing #4319 will mean that it can be present but will be ignored.

**Comment by ljani** [comment]
> 
> 
> > It worked with VS2017, but even installing VS2019 side-by-side breaks the build.
> 
> Can you elaborate on this, please? What error do you get when you build using MSBuild from VS2017 after the 2019 installation?

From above:

```
error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 2, position 1.
```

Also it occurred to me that I have not tried running `msbuild` from `Developer Command Prompt for VS 2017`, only from `Developer Command Prompt for VS 2019` and Azure DevOps Server 2019 continuous integration build, which is probably picking up 2019 as default as well.

> Other than that issue, which I'd like to investigate, I think the underlying problem here is #4319. Removing `ToolsVersion` from the MSBuild task is the right solution; fixing #4319 will mean that it can be present but will be ignored.

Ah, thanks. I'll close this as a duplicate.

**Comment by rainersigwald** [comment]
> Also it occurred to me that I have not tried running `msbuild` from `Developer Command Prompt for VS 2017`, only from `Developer Command Prompt for VS 2019` and Azure DevOps Server 2019 continuous integration build, which is probably picking up 2019 as default as well.

That makes sense. Now that Visual Studio (and thus MSBuild) is allowed to have multiple installed versions side-by-side, the way to select the toolset you wish to use to build is to select the right Visual Studio instance to start from. So #4319 will cause problems for _builds initiated from MSBuild 16.0_, but specifying `ToolsVersion="15.0"` should work fine for _builds initiated from MSBuild 15_. If you see otherwise, that's a bad bug that we should fix immediately, which is why I wanted to get clarification on this.

**Comment by mwpowellhtx** [comment]
@rainersigwald I think I've stumbled into the same sort of issue after installing VS2019, then iterating back on a VS2017 build pipeline. Fails restoring an internal `dotnet CLI tool` that was working seamlessly, seems prior to VS2019 installation in our estimation. Where do we set the `ToolsVersion`? In the project file(s)? We can set this in a `DirectoryBuild.props`?

**Comment by mwpowellhtx** [comment]
So... Looking for workarounds, resolutions. Besides potentially need to install and/or re-install SDKs, runtimes, etc. Haven't gotten quite that far in my troubleshooting. Short of that, crude answer is for us to visit each of our `.csproj` project files and add the `ToolsVersion` attribute in the appropriate version? I assume that's `15.0` for VS2017? Is there a more elegant way to do that in swath? i.e. through Directory.Build.props, for instance, by convention, as contrasted with by specification?

**Comment by labilbe** [comment]
Otherwise you can specify `ToolsVersion="Current"`
