### ISSUE TITLE
SSDT SqlTasks.targets generate spurious 'High importance' logs

### ISSUE THREAD

**Issue by benlaan** [Microsoft/msbuild#4345]
I realise that this bug is probably a little OT.. but SSDT doesn't have a repository to log a bug against.. and it does impact my msbuild scripts...

### Steps to reproduce

Add an SSDT (sqlproj) project to the solution. run the build step. sqlproj outputs messages that aren't that interesting or necessary even though I've set my build to minimal verbosity.

Command line
```
msbuild x.sln /v:minimal
```
### Expected  behavior

I don't want any 'info' type logging to be output

### Actual behavior

The following messages are output:

* Creating a model to represent the project...
* Loading project references...
* Loading project files...
* Building the project model and resolving object interdependencies...
* Validating the project model...
* Writing model to  ... \Model.xml...

I have tracked down the issue to Microsoft.Data.Tools.Schema.Tasks.Sql.TaskHostLoader.LogMessage(), which is passing 0 as the importance level, which is mapped to 'High'..

```
internal static void LogMessage(TaskLoggingHelper providedLogger, string msg)
{
    providedLogger.LogMessage(0, msg, Array.Empty<object>());
}
```

This means that all logging from within SSDT is highly important, which it definitely is not..

**Comment by livarcocc** [comment]
Please file a VS Feedback ticket through Visual Studio and this can then be routed to the right team internally. Even if it is for SSDT.
