### ISSUE TITLE
Can't build ms sample project (VS2019, .NET Core 3.0) [error NETSDK1073: The FrameworkReference 'Microsoft.DesktopUI' was not recognized]

### ISSUE THREAD

**Issue by anubi** [Microsoft/msbuild#4351]
1. I downloaded the latest preview of dot net core 3.0 (Preview 4, https://dotnet.microsoft.com/download/dotnet-core/3.0) and enabled via "Use previews of .NET Core SDK" in VS2019 (Professional edition). I realize this is a preview build, so I'm not expecting a graceful experience 💃 
2. I then got the latest version of https://github.com/dotnet/samples/tree/master/windowsforms/matching-game
3. I then attempt to build the project and receive the following error: NETSDK1073: The FrameworkReference 'Microsoft.DesktopUI' was not recognized

I'm not exactly sure what's amiss. So I did some digging through my msbuild logs, set to diagnostic. But it doesn't reveal anything to my unfamiliar eyes. Since this is a microsoft sample project, I figured I should report I could not easily get it to compile here. I'm guessing this is the right place, since I don't think there should be anything wrong with the sample project itself.

[msbuildlog.log](https://github.com/Microsoft/msbuild/files/3142446/msbuildlog.log)

I have tried a couple other projects in .NET Core 3.0 that utilize windows forms and also experience this error there, too, so I suspect something's up.

**Comment by livarcocc** [comment]
This is not an issue with MSBuild.

The sample you are using is very much out of date (it has last been updated 6 months ago it seems).

I would suggest either just doing dotnet new winforms (to create a new winforms project) and using this new project to play around.

Or, file this issue in the dotnet/samples repos.
