### ISSUE TITLE
TargetDotNetFrameworkVersion.VersionLatest should be 4.8 in 16.x

### ISSUE THREAD

**Issue by pieandcakes** [microsoft/msbuild#4354]
When using VS 2019.1 INT PREVIEW with the NET Framework 4.7.2 SDK installed, when asking for the following, the following call returns empty string.

            string ILDAsmFileLocation = Microsoft.Build.Utilities.ToolLocationHelper.GetPathToDotNetFrameworkSdkFile("ildasm.exe", TargetDotNetFrameworkVersion.VersionLatest);

**Comment by pieandcakes** [comment]
SideNote: when I F12 `VersionLatest` its coming back as `5`.

**Comment by rainersigwald** [comment]
What version of MSBuild are you compiling against? C#/.NET bakes enum _values_ into the referencing assembly, so if you're compling against an old MSBuild (like say the one from .NET 4.5), new MSBuild will think you're explicitly asking for an older version.

We added `.Latest` instead of `.VersionLatest` in MSBuild 15.1 to give the actually-desired behavior here. But that means you must compile against and run exclusively on 15.1+.

**Comment by pieandcakes** [comment]
@rainersigwald How do I check? The command line version of MSBuild I'm running against is:
`Microsoft (R) Build Engine version 16.1.68-preview+g64a5b6be6d for .NET Framework`

**Comment by rainersigwald** [comment]
Is this happening in a piece of code that you own/compile? Or did you disassemble something to get to the line of code you showed?

**Comment by rainersigwald** [comment]
Talked to @pieandcakes offline. The task is an inline task, so it is compiling against current MSBuild, but there's a problem.

The [real implementation](https://github.com/Microsoft/MIEngine/blob/49ae86895d4eb2642485f25620477411f85d417a/src/MakePIAPortable/MakePIAPortable.csproj#L61-L80) suggested a minimal repro:

```xml
<Project>
  <UsingTask TaskName="FindILDAsm" TaskFactory="CodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.v4.0.dll">
    <ParameterGroup>
      <ILDAsmFileLocation ParameterType="System.String" Output="true" />
    </ParameterGroup>
    <Task>
      <Using Namespace="Microsoft.Build.Utilities" />
      <Code Type="Fragment" Language="cs">
        <![CDATA[
          ILDAsmFileLocation = Microsoft.Build.Utilities.ToolLocationHelper.GetPathToDotNetFrameworkSdkFile("ildasm.exe" , TargetDotNetFrameworkVersion.VersionLatest);
        ]]>
      </Code>
    </Task>
  </UsingTask>
  <Target Name="GeneratePortablePIA" BeforeTargets="SignFiles" AfterTargets="Build">
    <FindILDAsm>
      <Output PropertyName="ILDAsmFileLocation" TaskParameter="ILDAsmFileLocation" />
    </FindILDAsm>
    <Message Importance="High" Text="ILDAsmFileLocation: $(ILDAsmFileLocation)" />
  </Target>
</Project>
```

On my machine, that returns

```text
  ILDAsmFileLocation: C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\ildasm.exe
```

I happen to have that SDK installed, but VS doesn't do it automatically. It does imply 4.7.2, though. Like #4049, `TargetDotNetFrameworkVersion.VersionLatest` should be 4.7.2.

## Workaround

Use `TargetDotNetFrameworkVersion.Version472` or `TargetDotNetFrameworkVersion.Latest`.
