### ISSUE TITLE
Nullable properties in XSD

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/msbuild#4391]
The properties (and their values) that control the [C# 8 nullable features](https://github.com/jcouv/roslyn/blob/master/docs/features/nullable-reference-types.md) should be mentioned in the XSD.

@jcouv I see a list of values in that doc, but is there help text available for each of `-nullable:{enable|disable|safeonly|warnings|safeonlywarnings}`? We'd probably just want to copy it into the XSD.

**Comment by jcouv** [comment]
`safeonly` and `safeonlywarnings` are no longer a thing

**Comment by livarcocc** [comment]
I used a simplified version of your text. I don't think we have text formatting available to us in the xsd file.

**Comment by rainersigwald** [comment]
Reactivating as per https://github.com/dotnet/project-system/issues/6345 this has regressed.

**Comment by rainersigwald** [comment]
This will be resolved by the internal PR AB#250249.

**Comment by Forgind** [comment]
Validated
