### ISSUE TITLE
GetPathsOfAllDirectoriesAbove produces duplicate paths

### ISSUE THREAD

**Issue by JoeRobich** [microsoft/msbuild#4392]
Roslyn uses `GetPathsOfAllDirectoriesAbove` to produce a list of potential .editorconfig paths.

```xml
<PotentialEditorConfigFiles Include="@(Compile->GetPathsOfAllDirectoriesAbove()->Combine('.editorconfig'))" Condition="'$(DiscoverEditorConfigFiles)' != 'false'" />
```

When a project contains linked files that use relative paths this causes `GetPathsOfAllDirectoriesAbove` to produce multiple paths which are equivalent.

![image](https://user-images.githubusercontent.com/611219/58193530-10209000-7c78-11e9-97ec-f6e09d0ae9c9.png)

**Comment by tmeschter** [comment]
It is definitely not supposed to produce equivalent paths.

**Comment by livarcocc** [comment]
Closing this issue as fixed.
