### ISSUE TITLE
TargetPlatformSdkPath assignment

### ISSUE THREAD

**Issue by slluis** [Microsoft/msbuild#44]
Is this TargetPlatformSdkPath assignment really necessary? 

https://github.com/Microsoft/msbuild/blob/master/src/XMakeTasks/Microsoft.Common.CurrentVersion.targets#L88

It doesn't work on Mono, and looks like the logic for getting the sdk path should all be in ToolLocationHelper.

**Comment by AndyGerlicher** [comment]
MSBuild team triage: Is this an issue in the xplat branch? The master branch doesn't have any of the changes we implemented in xplat.

**Comment by AndyGerlicher** [comment]
Closing. We have a single branch now (xplat) and the logic should be correct for Mono. Re-open if it's not.
