### ISSUE TITLE
[Question] Another Build System

### ISSUE THREAD

**Issue by redradist** [microsoft/msbuild#4404]
MSBuild is not a perfect Build Tool ...
Unfortunately it is not easy to create custom target and extend Build Tool with plugin ...

Do you consider a switch at least to other Build System ?

On other hand there is exist Gradle. It is very extensible Build System and very easily extended with custom plugin.
There is an open issue https://github.com/gradle/gradle/issues/1428 which is relates to support of C# and .sln

I know there are people which is annoying that Gradle is written on JVM, but at the end of the day it s just a technology, and does not matter on which language it is built in ... Matter only quality of the technology ...

Do you consider possibility to switch or at least add plugin support to Gradle for C# language ?

P.S.: This question is also asked on DotNet https://github.com/dotnet/coreclr/issues/24789

**Comment by livarcocc** [comment]
We have no intention of switching. There is a huge ecosystem built around MSbuild that would be extremely difficult and expensive to replicate.

**Comment by redradist** [comment]
@livarcocc You wrote:
> We have no intention of switching. There is a huge ecosystem built around MSbuild that would be extremely difficult and expensive to replicate.

It is sad to hear (:
MSBuild would never be as powerful as Gradle because it is hard to mix in XML also imperative style of programming ...
