### ISSUE TITLE
Avoid losing callstack for some exceptions

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/msbuild#4413]
https://github.com/microsoft/msbuild/blob/c70d6ded175c0a7da632018b856daff9f9cd392e/src/Build/BackEnd/BuildManager/BuildManager.cs#L411-L417

https://github.com/microsoft/msbuild/blob/c70d6ded175c0a7da632018b856daff9f9cd392e/src/Build/BackEnd/BuildManager/BuildManager.cs#L776-L780

I think these could both be improved if we threw a new exception that had a stringification (including stack) of the original exception.

**Comment by ericstj** [comment]
You could either wrap, preserving inner exception, or use [ExceptionDispatchInfo](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.exceptionservices.exceptiondispatchinfo?view=netframework-4.8) to preserve the original stack ([examples](https://source.dot.net/#System.Private.CoreLib/shared/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs,1443447025759846,references)).

**Comment by rainersigwald** [comment]
`ExceptionDispatchInfo` is _perfect_ for this, thank you.
