### ISSUE TITLE
Copy Task: error when UseHardlinksIfPossible/UseSymboliclinksIfPossible fails

### ISSUE THREAD

**Issue by sbanni** [microsoft/msbuild#4433]
I would like to be able to specify the level of error if copying a file using hardlink fails to create the link.  This would extend beyond MessageImportance and allow me to create an error that will fail the build.

I recently ran into an issue where a file was copied using hardlinks, the copy was edited but the original was not also updated because it is normally hardlinked.

**Comment by livarcocc** [comment]
So, you are looking for a per-task logging level that is independent of the general logging mechanism for msbuild?

**Comment by sbanni** [comment]
I want to be able to know the results of the Copy task if it was successful in using hard/sym links.

**Comment by rainersigwald** [comment]
The current "try to sym-/hard-link the file, but if it fails silently fall back to copy" behavior is a bit confusing; I suspect it was chosen to maximize backward compatibility. There are many ways for hardlinking to fail, some of which might be quite annoying to deal with as a build failure.

"Fail if you can't hardlink" is a perfectly reasonable behavior. I think the best option given our current behavior is a new bool parameter (named something like `ErrorIfLinkFails`?) that disables the fallback and errors out. Would that be sufficient for your needs @sbanni?

**Comment by sbanni** [comment]
@rainersigwald Yes that would would very well. Thanks!

**Comment by rainersigwald** [comment]
Great. It's not currently very high on our team's priority list, so I added up-for-grabs to indicate that we'd be open to taking a PR that added it.
