### ISSUE TITLE
GenerateProjectSpecificOutputFolder does not play nice with nuget package creation and multi-targetting

### ISSUE THREAD

**Issue by MarkusHorstmann** [microsoft/msbuild#4435]
### Steps to reproduce

Create a VS solution with a Project file myproject.csproj, targetting multiple frameworks and creating a nuget package. 
For example (derived from https://docs.microsoft.com/en-us/dotnet/standard/frameworks):

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net40;net45</TargetFrameworks>
    <AssemblyName>MyProject</AssemblyName>
    <PackageId>MyProject</PackageId>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <!-- Conditionally obtain references for the .NET Framework 4.0 target -->
  <ItemGroup Condition=" '$(TargetFramework)' == 'net40' ">
    <Reference Include="System.Net" />
  </ItemGroup>

  <!-- Conditionally obtain references for the .NET Framework 4.5 target -->
  <ItemGroup Condition=" '$(TargetFramework)' == 'net45' ">
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Threading.Tasks" />
  </ItemGroup>

</Project>
```

Then build the solution from a VS developer command prompt using something like this:
```
msbuild somesolution.sln /p:Configuration=Debug;OutDir="c:\test\debug\\";GenerateProjectSpecificOutputFolder=true
```

### Expected  behavior
1) The 3 dlls/outputs for netstandard2.0, net40 and net45 should be written to different directories, i.e. c:\test\debug\myproject.net45 or c:\test\debug\myproject\net45 or c:\test\debug\net45\myproject.
2) The generated .nupkg should appear in or under the c:\test\debug directory.

### Actual behavior
1) All 3 outputs are written into the same directory (c:\test\debug\myproject), overwriting each other and creating build race conditions for larger solutions.
2) The generated .nupkg only appears in the bin\debug directory under the directory containing the .csproj, but nowhere under the outdir (c:\test\debug).

### Workaround:
Add this to the .csproj:

```xml
    <ProjectName>$(AssemblyName).$(TargetFramework)</ProjectName>
    <PackageOutputPath>$(OutDir)</PackageOutputPath>
```
This creates directories c:\test\debug\myproject.net45 etc. and places the .nupkg into c:\test\debug.

It would be nice if this could just work without customizing each .csproj.

### Environment data

`msbuild /version` output:
Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
16.1.76.45076

VS 2019 16.1.2, VS 2017 15.9.11
Also happens on the Azure DevOps VS2017 managed build agent as of June 2019.

OS info: Windows 10

**Comment by livarcocc** [comment]
This is a dup of https://github.com/dotnet/sdk/issues/867.
