### ISSUE TITLE
ZipTask output is corrupted

### ISSUE THREAD

**Issue by Azure3bt** [microsoft/msbuild#4445]
Whenever i and my teammate working on one specific project, and push to deploy server and run msbuild with ZipTask all operations successful but can't unzip file as output and give error that dll of same project is corrupted.
Finally we test this mission on your local machine everything is fine.
Note: We are using same vs version and build

**Comment by livarcocc** [comment]
Can you zip other things on the server machine?

Are there any logs for he zip task that you could share? Given that this works locally, it usually indicates something wrong in your build machine. Is it always the same build machine? Could you try it on a different one?

**Comment by Azure3bt** [comment]
> Can you zip other things on the server machine?
> 
> Are there any logs for he zip task that you could share? Given that this works locally, it usually indicates something wrong in your build machine. Is it always the same build machine? Could you try it on a different one?

**Comment by Azure3bt** [comment]
It's correct but when i push branch that include commit related to this project give this error.
Before i issue it give error but update msbuild version of server machine to 15.5 everything was correct until i push second branch and give error. then update to msbuild 16 and seem everything is ok, I didn't know how happen on server.
Sorry i don't have any logger on server for this, in fact this server used as deploy server only running msbuild batch file and update zip file to other customer server.

**Comment by livarcocc** [comment]
Sorry, I am confused. Does it work when you update the server to 16.0?

**Comment by Azure3bt** [comment]
Yes it does, But i didn't know happened on server.

As i say my workmate push to deploy branch everything work when i push it to server give a this error.

Ok i'm going to test its and send result to you

**Comment by livarcocc** [comment]
@Azure3bt what sort of source control do you use? By push to the server... is this a git push or something else?

**Comment by Azure3bt** [comment]
Git, Yes it's work with git push command

**Comment by Azure3bt** [comment]
Sorry i think is issue related to [MsbuildTask](https://github.com/loresoft/msbuildtasks) not you and your team.

**Comment by livarcocc** [comment]
I see. You are using the Zip task from there. Ok, I am going to go ahead and close this issue. Thanks for letting us know.
