### ISSUE TITLE
error APPX0002: Task 'ValidateAppxManifest' failed ONLY when running from service azure agent

### ISSUE THREAD

**Issue by gilbdev** [microsoft/msbuild#4448]
i'm trying to build an UWP .appx

the sln project is generated via Unity3D

- if the command below is launched manually, it works just fine, as expected.
- if it's launched during a build step from azure on the same machine, same user, but as an azure agent configured to run as a service, the error message is displayed and package creation fails.

`C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(2638,5): error APPX0002: Task 'ValidateAppxManifest' failed. Namespace prefix 'm' is not defined. [C:\TFSagent\_work\1\s\MyProject.vcxproj]`
(there is not any use of a namespace 'm' in the manifest file, and the package creation works fine when launching same command by hand)
I don't see what's wrong and the error itself doesn't help much in how to solve it...

### Steps to reproduce

Command line (same one launched , manually or as a service build step)
```
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe" "C:\TFSagent\_work\1\s\MyProject.sln" /t:Build /p:Configuration=master /p:Platform=x86"
```
### Expected  behavior
build .appx without any error where as it's launched from a serviec or not

### Actual behavior
fails when running as a service

### Environment data
`msbuild /version` output:
```
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

15.9.21.664
```

OS info: Windows 10 VM
Microsoft Visual Studio Team Foundation Server Version 16.131.28507.4
within a simple command line build step

agent is configured as a service using a dedicated local user that has admin rights (i've also tried with default NT NETWORK SERVICE user)

### Please Help
or redirect me to another more adapted github if necessary (msbuild-task ? azure ? )

**Comment by gilbdev** [comment]
msbuild logs as diagnostic verbosity (its 200k lines, so jsut targeting the part concerning the task where the problem is, ask for other parts on demand):

working one:
```
Task "ValidateAppxManifest"
  Task Parameter:Input=C:\TFSagent\_work\1\s\Unity\Builds\WSAPlayer\build\bin\Win32\Master\AppxManifest.xml
  Task Parameter:SourceAppxManifest=Package.appxmanifest
                  SubType=Designer
  Task Parameter:
      AppxManifestSchema=
          C:\Program Files (x86)\Windows Kits\10\\Include\10.0.18362.0\WinRT\FoundationManifestSchema.xsd
                  NamespaceAlias=m
                  NamespaceUri=http://schemas.microsoft.com/appx/manifest/foundation/windows10
          C:\Program Files (x86)\Windows Kits\10\\Include\10.0.18362.0\WinRT\UapManifestSchema.xsd
                  NamespaceAlias=uap
                  NamespaceUri=http://schemas.microsoft.com/appx/manifest/uap/windows10
  Task Parameter:TargetPlatformVersion=10.0.18362.0
  Task Parameter:TargetPlatformIdentifier=UAP
...Etc...(same on both logs)
```

non-working one:
```
2019-06-18T14:07:06.2435158Z Task "ValidateAppxManifest" (TaskId:209)
2019-06-18T14:07:06.2435260Z   Task Parameter:Input=C:\TFSagent\_work\1\s\Unity\Builds\WSAPlayer\build\bin\Win32\Master\AppxManifest.xml (TaskId:209)
2019-06-18T14:07:06.2435361Z   Task Parameter:SourceAppxManifest=Package.appxmanifest
2019-06-18T14:07:06.2435446Z                   SubType=Designer (TaskId:209)
2019-06-18T14:07:06.2435530Z   Task Parameter:TargetPlatformVersion=10.0.18362.0 (TaskId:209)
2019-06-18T14:07:06.2435615Z   Task Parameter:TargetPlatformIdentifier=UAP (TaskId:209)
...Etc...(same on both logs)
```

so, now : why does the working version does have an extra parameter for this task ?

**Comment by livarcocc** [comment]
This task is not really produced out of this repo. I would suggest that you file a VS Feedback item through VS and the issue will be routed to the appropriate team. I don't believe there is a public repo that you can use for it.

Meanwhile, I am going to close the issue here.
