### ISSUE TITLE
On Mac MSBuild does not accept absolute path on command line

### ISSUE THREAD

**Issue by JohnChen0** [Microsoft/msbuild#445]
An absolute path on Mac OS X starts with a / character, making it look like a switch on the command line. However, the special logic to distinguish absolute path from switches is not enabled on Mac, thus absolute paths on command line are mistaken for switches, causing command line parsing to fail.

**Comment by rainersigwald** [comment]
Should be fixed with our packages starting with `0.1.0-preview-00015`.
