### ISSUE TITLE
Bring back support for Splashscreen build action

### ISSUE THREAD

**Issue by miguep** [microsoft/msbuild#4462]
### Steps to reproduce

The following reports "The SplashScreen Build Action is not supported in the selected Target Framework." when included in a .NET Core 3 project.

```xml
<ItemGroup>
    <SplashScreen Include="startupSplash.png" />
  </ItemGroup
```

Can we bring back support for it? Now that WPF runs in .NET Core 3.0 this is a very common scenario and an obstacle for application looking to move to .NET Core 3.0

**Comment by livarcocc** [comment]
Closing this issue in favor of the wpf one. The code for this lives in the WPF repo.
