### ISSUE TITLE
How to check why files rebuild

### ISSUE THREAD

**Issue by jmecosta** [microsoft/msbuild#4465]
Hi,

Cant crack this one, Visual Studio -> 
13>All outputs are up-to-date.
13>Time Elapsed 10 ms
========== Build: 0 succeeded, 0 failed, 13 up-to-date, 0 skipped ==========

Msbuild Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
d:\prod\structures\Core\Common>msbuild.exe /p:TSPlatform=x64 /p:Platform=x64 /p:Configuration=Release /m:6 /t:Build /v:minimal
Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  timer.cpp
  libclock.vcxproj -> D:\prod\structures\ObjDrop\Work\Release\x64\lib\libclock.lib
  cancel_lib.cpp
  libcancel.vcxproj -> D:\prod\structures\ObjDrop\Work\Release\x64\lib\libcancel.lib
  libsearch.vcxproj -> D:\prod\structures\ObjDrop\Work\Release\x64\lib\libsearch.lib
  dummy.cpp
  libfilesystem.vcxproj -> D:\prod\structures\ObjDrop\Work\Release\x64\lib\libfilesystem.lib
  libdbdatabase.vcxproj -> D:\prod\structures\ObjDrop\Work\Release\x64\lib\libdbdatabase.lib
  libcommondbase.vcxproj -> D:\prod\structures\ObjDrop\Work\Release\x64\lib\libcommondbase.lib
  libdbkitinterface.vcxproj -> D:\prod\structures\ObjDrop\Work\Release\x64\lib\libdbkitinterface.lib
     Creating library D:\prod\structures\ObjDrop\Work\Release\x64\sharedlibs\Common.lib and object D:\prod\structures\ObjDrop\Work\Release\x64\s
  haredlibs\Common.exp
  Common.vcxproj -> D:\prod\structures\BuildDrop\Work\bin_release_x64\Common.dll
     Creating library D:\prod\structures\ObjDrop\Work\Release\x64\sharedlibs\LibSearchTests.lib and object D:\prod\structures\ObjDrop\Work\Relea
  se\x64\sharedlibs\LibSearchTests.exp
     Creating library D:\prod\structures\ObjDrop\Work\Release\x64\sharedlibs\LibDbDatabaseTests.lib and object D:\prod\structures\ObjDrop\Work\R
  elease\x64\sharedlibs\LibDbDatabaseTests.exp
     Creating library D:\prod\structures\ObjDrop\Work\Release\x64\sharedlibs\LibFileSystemTests.lib and object D:\prod\structures\ObjDrop\Work\R
  elease\x64\sharedlibs\LibFileSystemTests.exp
  LibSearchTests.vcxproj -> D:\prod\structures\BuildDrop\Work\bin_release_x64\GTests\LibSearchTests.exe
  LibDbDatabaseTests.vcxproj -> D:\prod\structures\BuildDrop\Work\bin_release_x64\GTests\LibDbDatabaseTests.exe
  LibFileSystemTests.vcxproj -> D:\prod\structures\BuildDrop\Work\bin_release_x64\GTests\LibFileSystemTests.exe
     Creating library D:\prod\structures\ObjDrop\Work\Release\x64\sharedlibs\LibDbKitInterfaceTests.lib and object D:\prod\structures\ObjDrop\Wo
  rk\Release\x64\sharedlibs\LibDbKitInterfaceTests.exp
  LibDbKitInterfaceTests.vcxproj -> D:\prod\structures\BuildDrop\Work\bin_release_x64\GTests\LibDbKitInterfaceTests.exe

Running with /v:detailed or /v:diagnostic
       Task "Touch"
         Creating "D:\prod\structures\ObjDrop\Work\Release\x64\libclock\libclock.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
       Done executing task "Touch".

However i cant track what is causing AlwaysCreate to be true. Any way i can figure out what is the problem. Things ive checked:
1. no header files/otherfiles are included in project but not found in src control (very typical)

the documentiaion availble mostlry focus on those (easy to spot), https://blogs.msdn.microsoft.com/vsproject/2009/07/20/enable-c-project-system-logging/ https://blogs.msdn.microsoft.com/dsvc/2013/03/12/alwayscreate-forces-project-to-be-re-built/

I have tried wtih vs 2017 and the incremental build works properly
E:\prod\ts-build\Core\Common>msbuild  /p:PreBuildDeployPreCompileHeadersEnabled=false /p:TSPlatform=x64 /p:Platform=x64 /m /v:minimal
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  libclock.vcxproj -> E:\prod\ts-build\MSBuild\..\ObjDrop\Work\Debug\x64\lib\libclock.lib
  libcancel.vcxproj -> E:\prod\ts-build\MSBuild\..\ObjDrop\Work\Debug\x64\lib\libcancel.lib
  libcommondbase.vcxproj -> E:\prod\ts-build\MSBuild\..\ObjDrop\Work\Debug\x64\lib\libcommondbase.lib
  libsearch.vcxproj -> E:\prod\ts-build\MSBuild\..\ObjDrop\Work\Debug\x64\lib\libsearch.lib
  libdbkitinterface.vcxproj -> E:\prod\ts-build\MSBuild\..\ObjDrop\Work\Debug\x64\lib\libdbkitinterface.lib
  libfilesystem.vcxproj -> E:\prod\ts-build\MSBuild\..\ObjDrop\Work\Debug\x64\lib\libfilesystem.lib
  libdbdatabase.vcxproj -> E:\prod\ts-build\MSBuild\..\ObjDrop\Work\Debug\x64\lib\libdbdatabase.lib
  Common.vcxproj -> E:\prod\ts-build\MSBuild\..\BuildDrop\Work\bin_x64\Common.dll
  LibSearchTests.vcxproj -> E:\prod\ts-build\MSBuild\..\BuildDrop\Work\bin_x64\GTests\LibSearchTests.exe
  LibFileSystemTests.vcxproj -> E:\prod\ts-build\MSBuild\..\BuildDrop\Work\bin_x64\GTests\LibFileSystemTests.exe
  LibDbDatabaseTests.vcxproj -> E:\prod\ts-build\MSBuild\..\BuildDrop\Work\bin_x64\GTests\LibDbDatabaseTests.exe
  LibDbKitInterfaceTests.vcxproj -> E:\prod\ts-build\MSBuild\..\BuildDrop\Work\bin_x64\GTests\LibDbKitInterfaceTests.ex
  e

Thanks

**Comment by livarcocc** [comment]
I would suggest using a binary log to try to spot why this is happening. You can generate one by using the `/bl` parameter in your build. It will generate a msbuild.binlog file that you can then use to see more information about your build.

For more info about binlogs, check here: https://gist.github.com/dsplaisted/b256d7804672a6f6375476a5f5658b7b

Let me know if that is still not enough for you.

**Comment by jmecosta** [comment]
well today i cant replicate, but thanks for the hint. not aware of this tool. Looks great!
