### ISSUE TITLE
developer command 2019 prompt broken

### ISSUE THREAD

**Issue by jmecosta** [microsoft/msbuild#4466]
Hi,

Trying to migrate our builds to use 2019 (16.1.3) tooling, however the only way i can get them to compile is to run them via cmd.exe. 

When i start developer command prompt 2019 (16.1.76+g14b0a930a7 for .NET Framework) it fails to link some of my c++ dlls
 "d:\prod\structures\Core\Reinforcement\ReinforcementTests\ReinforcementTests.vcxproj" (default target) (188) ->
       (Link target) ->
         polymesh_face_test.obj : error LNK2019: unresolved external symbol "public: static class std::shared_ptr<class
        rbrPolymeshFace_c> __cdecl rbrPolymeshFace_c::CreateFace(struct Id_c const &,class std::shared_ptr<class rbrReb
       arSetAggregate_c> const &,int,double,class geometry::Polymesh_c const &)" (?CreateFace@rbrPolymeshFace_c@@SA?AV?
       $shared_ptr@VrbrPolymeshFace_c@@@std@@AEBUId_c@@AEBV?$shared_ptr@VrbrRebarSetAggregate_c@@@3@HNAEBVPolymesh_c@ge
       ometry@@@Z) referenced in function "private: virtual void __cdecl REBAR_rbrPolymeshFaceTest_IntersectPlaneWithCy
       linder1_Test::TestBody(void)" (?TestBody@REBAR_rbrPolymeshFaceTest_IntersectPlaneWithCylinder1_Test@@EEAAXXZ) [d
       :\prod\structures\Core\Reinforcement\ReinforcementTests\ReinforcementTests.vcxproj]

My guess, is that the windows sdk is somehow messed up, and not using the 8.1 that i have centrally defined for all projects. 

I tried several things, having vs 2017 and vs 2019 installed, vs 2019 only. Run those in build farm. Eveyrhting works except in developer and c++ native command prompt. Also VS enterpresie or Professional results in same issue

Seems some kind of regression in 2019.

PS: this is a v141 compiler, centrally configured for all projects.

thanks

**Comment by livarcocc** [comment]
@jmecosta Thanks for filling this issue, however, this is not the best place to file c++ issues.

Could you instead file a vs feedback ticket through VS itself. It will make its way to the vc++ team quicker and you will get a more timely response to your issue.

Meanwhile, I am going to close this one.

**Comment by jmecosta** [comment]
thanks for the help anyway
