### ISSUE TITLE
Preserialized resources error fires when not required

### ISSUE THREAD

**Issue by ericstj** [microsoft/msbuild#4474]
See https://github.com/dotnet/corefx/pull/38964#discussion_r297945596

To reproduce, exclude System.Resources.Extensions.dll (either through DisableImplicitFrameworkReferences and manually adding references, or subtracting it with a target) from a netcoreapp3.0 project, add a resource with only string resources and build.

Expect: No Error

Actual: Error about missing S.R.E

**Comment by ericstj** [comment]
So it turns out this is causing an error in File -> New Project.  System.Resources.Extensions is not part of the base shared framework, it's only part of Windows Desktop.  This needs to be fixed ASAP.  /cc @livarcocc

**Comment by livarcocc** [comment]
@nguerrera is looking into this for 3.0 P7 and 16.3 P1.

**Comment by roederja2** [comment]
Should I ever see this error when building for net462? This started happening after installing the .net 3 SDK preview 8. The project actually has non-string resources and the problem can be fixed by referencing System.Resources.Extensions and setting GenerateResourceUsePreserializedResources to true, but I'm not sure I should have to do this for framework builds?

**Comment by nguerrera** [comment]
If you were building using dotnet build, any non-string resources were being corrupted and turned into strings with the value equal to how it was serialized in the resx. That was bogus and we had a lot of reports of it.

If you were building with msbuild or VS, then it would have worked and should still work without the property or reference. If you see this error building for net462 without any project changes, then there's a bug. 

This is strictly a breaking change which should go in release notes. @kathleendollard

**Comment by roederja2** [comment]
Building with VS still works with no changes. Building with dotnet (we do that on the build server) worked (as in no compiler error - I don't know if the resources got corrupted). This now doesn't work anymore unless the dependency and the option are added.

**Comment by rainersigwald** [comment]
Thanks for confirming; that's the expected behavior, because the resources were in fact being corrupted and would fail at runtime.
