### ISSUE TITLE
Version seems no "+" supported

### ISSUE THREAD

**Issue by liesauer** [microsoft/msbuild#4475]
### Steps to reproduce

Command line
```
dotnet build /path/to/project.csproj /p:Version=1.0.0+fdfee1b1
```

### Expected  behavior

generate a nuget package called `xxxx.1.0.0+fdfee1b1.nupkg`

### Actual behavior
```
Successfully created package '/path/to/project/xxxx.1.0.0.nupkg'.
```

### Environment data
```
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
```

**Comment by liesauer** [comment]
closed due to no response

**Comment by rainersigwald** [comment]
Sorry this was missed. The answer is that semver metadata doesn't make it into the package _filename_, but is encoded in the package itself. For the example you gave, for instance, the generated/embedded nuspec from the package has

```xml
<version>1.0.0+fdfee1b1</version>
```

If you have further questions about this NuGet behavior, please file an issue at https://github.com/nuget/home.
