### ISSUE TITLE
Consider creating a Nuget package.

### ISSUE THREAD

**Issue by nosami** [Microsoft/msbuild#45]
I'd like to use Microsoft.Build.Evaluation both for parsing project files and writing back to them in OmniSharp https://github.com/OmniSharp/omnisharp-roslyn

Please could you consider creating a nuget package so that I can easily consume this code? Thanks.

**Comment by nathanaeljones** [comment]
A nuget package to contain msbuild.exe would also be quite nice. Most CI scripts call `paket restore` or `nuget restore` before invoking msbuild anyway; no reason we can't install it and change an environment variable to point to it.

**Comment by ctaggart** [comment]
A nuget package for `Microsoft.Build` package would be awesome! I can't figure out a way to [reference the latest `Microsoft.Build` assembly in the GAC from F# interactive](http://stackoverflow.com/questions/30010283/reference-latest-gac-assembly-in-f-interactive). Solving that would help me [fix a SourceLink issue](https://github.com/ctaggart/SourceLink/issues/50#issuecomment-98436214). I always end up with `4.0.0`. A nuget package would allow me to simply reference the file which would be perfect.

**Comment by ctaggart** [comment]
I went ahead and published my branch here with three of the assemblies I needed:
https://www.nuget.org/packages/SourceLink.MSBuild/

The build was created on AppVeyor using [this build script](https://github.com/ctaggart/msbuild/blob/a23a11d49ffbd56ddcae88a18e548816ec2a230a/build.ps1). All tests pass.
![image](https://cloud.githubusercontent.com/assets/80104/7522279/fc8e4c86-f4a8-11e4-877f-90d9445d3c13.png)

I'll put together a blog with more details.  I'm mentioning this here in case others can use this NuGet package or want a build script.

**Comment by jasonwilliams200OK** [comment]
@ctaggart, please consider sending a PR to this repo, so everyone depend on the same updated package.

**Comment by akoeplinger** [comment]
A PR for NuGet packages was already opened here: https://github.com/Microsoft/msbuild/pull/95
