### ISSUE TITLE
Custom task that invokes nodejs does not work with FileTracker

### ISSUE THREAD

**Issue by rhpijnacker** [microsoft/msbuild#4504]
### Steps to reproduce

I created a custom task that runs nodejs to perform some actions. This task works as it should.
I want to use file tracker to track file access on this task, but when I enable that using `FileTracker.StartTrackingContext`, suddenly nodejs cannot be started anymore.
I get an error that states:

```
HelloWorld.proj(9,5): error MSB6003: The specified task executable "node.exe" could not be run. The operation identifier is not valid
```
[HelloWorld.zip](https://github.com/microsoft/msbuild/files/3385335/HelloWorld.zip)

Command line
```
msbuild HelloWorld.proj
```
### Expected  behavior
It runs the nodejs process

### Actual behavior
It gives an error

### Environment data
`msbuild /version` output: 15.9.20.62856
OS info: Windows 10 1607

**Comment by rhpijnacker** [comment]
After some more digging around, it looks like the problem is caused by Tracker.exe (32 bit) starting nodejs (64 bit).
Adding `/d FileTracker64.dll` does not seem to help in any way.

Running the same command in a 64bit VisualStudio cmd prompt makes it work (as a workaround).

**Comment by rainersigwald** [comment]
Your project references `Microsoft.Build.Utilities.v4.0`, which predates support for launching processes across architectures (which was introduced with microsoft/msbuild#650 in MSBuild 14.3).

I was able to make your project work with this change, updating to use the copy of MSBuild installed with my VS:

```diff
diff --git a/CustomTasks/CustomTasks.csproj b/CustomTasks/CustomTasks.csproj
index 5fcd810..40a27fc 100644
--- a/CustomTasks/CustomTasks.csproj
+++ b/CustomTasks/CustomTasks.csproj
@@ -9,7 +9,7 @@
     <AppDesignerFolder>Properties</AppDesignerFolder>
     <RootNamespace>CustomTasks</RootNamespace>
     <AssemblyName>CustomTasks</AssemblyName>
-    <TargetFrameworkVersion>v4.7</TargetFrameworkVersion>
+    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
     <FileAlignment>512</FileAlignment>
     <Deterministic>true</Deterministic>
   </PropertyGroup>
@@ -32,7 +32,7 @@
   </PropertyGroup>
   <ItemGroup>
     <Reference Include="Microsoft.Build.Framework" />
-    <Reference Include="Microsoft.Build.Utilities.v4.0" />
+    <Reference Include="Microsoft.Build.Utilities.Core" />
     <Reference Include="System" />
     <Reference Include="System.Core" />
     <Reference Include="System.Xml.Linq" />
```

For production use, I'd recommend referencing MSBuild with [our NuGet packages](https://www.nuget.org/packages/Microsoft.Build.Utilities.Core/16.0.461) instead.

**Comment by rhpijnacker** [comment]
It turns out I was using an older version of Tracker.exe. Using the one shipped with VS2017 made it work.
