### ISSUE TITLE
Many duplicate strings held by MSBuildGlob.globRoot

### ISSUE THREAD

**Issue by panopticoncentral** [microsoft/msbuild#4511]
Looking at the managed heap of large CPS-based solutions, about 1% of the heap is being wasted by duplicate strings held in MSBuildGlob.globRoot in MSBuildGlob.Parse. The problem appears to be:

` globRoot = FileUtilities.NormalizePath(globRoot).WithTrailingSlash()`

When a lot of globs come from the same path, they're all going to have the same root but since we tack on the trailing slash in Parse, none of them are going to be shared, they'll all be their own instances. Looking at the use of GlobRoot, it looks like it only used with `Path.Combine`, which means I'm not even sure why we're adding the trailing slash in the first place?

**Comment by livarcocc** [comment]
@BenVillalobos who has been looking at these kinds of issues for us.

**Comment by BenVillalobos** [comment]
Will jump on this 👍
