### ISSUE TITLE
Microsoft.Build 16.0 package unavailable to netstandard libraries

### ISSUE THREAD

**Issue by mletterle** [microsoft/msbuild#4521]
The [Microsoft.Build NuGet Package](https://www.nuget.org/packages/Microsoft.Build/) has always contained an appropriate netstandard version of the library since the beginning, however the most recent release [16.0.461](https://www.nuget.org/packages/Microsoft.Build/16.0.461) only contains net472 and netcoreapp2.1 libraries. This is a problem for any netstandard tasks that are evaluating Projects.

Is there a reason netstandard2.0 wasn't included?

**Comment by rainersigwald** [comment]
There is no version of MSBuild 16 that runs on every platform that supports `netstandard2.0`, because it uses new (`netcoreapp2.1`-specific) functionality when built in "core" mode.

It's unfortunate but unavoidable (AFAIK) that this requires downstream libraries to multitarget, but it has the nice property that the problem occurs at build time, rather than at run time.

**Comment by mletterle** [comment]
Is there a reason project parsing requires netcoreapp specific functionality?

**Comment by rainersigwald** [comment]
The MSBuild API doesn't draw a distinction between evaluating projects and building them, so even if evaluation succeeded in some cases, we wouldn't want to advertise netstandard support for the overall API.

MSBuild runs a ton of code during project evaluation, including a ton of stuff around paths and file I/O that changed in the 2.1 timeframe. I would not expect evaluation to succeed for all projects on the core 2.0 runtime.

**Comment by rainersigwald** [comment]
(And more importantly, we don't _test_ that, so we shouldn't make promises about it working.)

**Comment by mletterle** [comment]
Thanks!

**Comment by mletterle** [comment]
Oh, one followup @rainersigwald, wouldn't a library that uses project evaluation (like say a task library or somesuch), be loaded into the specific platform runtime? There's no reason a "reference assembly" couldn't be netstandard?
