### ISSUE TITLE
Why some reference assemblies is locked and how to remove them, in Multitarget project?

### ISSUE THREAD

**Issue by ahdung** [microsoft/msbuild#4530]
Please look:
![微信截图_20190720120032](https://user-images.githubusercontent.com/12094247/61575560-92ee8b80-aaff-11e9-9fea-02bd01ca6275.png)

I'm not reference these assemblies at all in .csproj, Why them here? Why them locked? How remove them?

**Comment by u7pro** [comment]
if you want to remove those implicit references, you can add `DisableImplicitFrameworkReferences` to your csproj :

```xml
<PropertyGroup>
  <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
</PropertyGroup>
```

**Comment by ahdung** [comment]
@u7pro It works, thank you very much. And how to know this things? any documentation?

**Comment by u7pro** [comment]
Check out this link : https://github.com/microsoft/msbuild/blob/master/documentation/wiki/Something's-wrong-in-my-build.md#tools

You can also preprocess your csproj using `msbuild your.csproj /pp:file.xml` to expand all imports and try to find what's wrong..

**Comment by ahdung** [comment]
@u7pro Thank you!
