### ISSUE TITLE
Binary resource error MSB3822 incorrectly skips subsequent incremental build

### ISSUE THREAD

**Issue by deadman2000** [microsoft/msbuild#4553]
Project for test: https://github.com/deadman2000/BinaryResourceTest/

### Steps to reproduce

* Clean project
* Remove `obj` folders
* Build with `dotnet build`
* Getting error `MSB3822: Non-string resources require the System.Resources.Extensions assembly at runtime, but it was not found in this project's references`
* Build again with `dotnet build`
* Project builded. BUT `ResourceManager.GetObject` returns `null`

Full log: https://raw.githubusercontent.com/deadman2000/BinaryResourceTest/master/test.txt

### Environment data

.NET Core SDK
 Version:   3.0.100-preview7-012821
 Commit:    6348f1068a

**Comment by rainersigwald** [comment]
Nice repro! The `MSB3822` error is correct, and it should be emitted every time.

**Comment by schuettecarsten** [comment]
Similar problem here. We wonder why 3.0-preview7 is used even if there is a global.json next to the sln file that requests use of SDK version 2.1.508 (which is also installed on the machine):

```
{
  "sdk": {
    "version": "2.1.508"
  }
}

**Comment by rainersigwald** [comment]
Fixed by #4664.
