### ISSUE TITLE
HighEntropyVA capability not getting set in netstandard2.0 dlls

### ISSUE THREAD

**Issue by smmalis37** [microsoft/msbuild#4566]
Similar to #2912. 

1. Create .net standard library.
2. Set configuration to AnyCPU, compile.

Result: high entropy va bit not set in PE.

Adding relevant MsBuild property with correct value to the csproj resolves the issue.
`<HighEntropyVA>true</HighEntropyVA>`

`msbuild /version` output: 16.200.19.32702

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):
Visual Studio 16.3.0 Preview 1.0

**Comment by marklio** [comment]
It looks like the fix for #2912 fixed it in a props that isn't imported for core/netstandard assemblies using SDK projects.

**Comment by jhudsoncedaron** [comment]
I don't get it. /HIGHENTROPYVA means nothing for .DLL files. You can set the bit, but only executable images use it.

**Comment by rainersigwald** [comment]
This should be fixed by microsoft/msbuild#4895.
