### ISSUE TITLE
BuildInParallel for dependent custom build steps

### ISSUE THREAD

**Issue by stefan1000** [microsoft/msbuild#4576]
Hi,

I'm trying to run custom builds steps in parallel (C++ VS 2019 16.2). It seems that parallel execution is switched off when those custom build steps inputs depend on another custom build steps output, as stated in the log file:
```
"The build of 'SomeHeader.h' depends on 'OtherHeader.h' which is produced by the build of 'some_other_gen_file'. The items cannot be built in parallel."
```
In the project I have around 20x `SomeHeader.h` type of build steps and they all rely on this one file 'OtherHeader.h', so we don't get any benefit from using BuildInParallel for those tasks.

Is there any way to make them run in parallel ?

`msbuild /version` output:
Microsoft (R) Build Engine version 16.2.32702+c4012a063 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.200.19.32702

OS info:

VS 2019 16.2 on W10 Prof 64bit.

**Comment by rainersigwald** [comment]
The task that does that Makefile-like custom build steps with dependencies based on file outputs/inputs is not part of MSBuild, it's part of Visual C++'s build tasks. Can you please file a Visual Studio Feedback issue on this? If you respond here with the link, I'll expedite getting it routed to the right folks.

**Comment by stefan1000** [comment]
Thanks, the issue is now under investigation by the visual studio team:
https://developercommunity.visualstudio.com/content/problem/677838/buildinparallel-for-dependent-custom-build-steps.html
