### ISSUE TITLE
GenerateResource has incomplete handling for ResXFileRef

### ISSUE THREAD

**Issue by ericstj** [microsoft/msbuild#4581]
Copied from https://github.com/dotnet/corefx/issues/39980, filed by @Symbai

Accessing a resource file throws a `System.MissingMethodException: Constructor on type 'System.Byte[]' not found.`

Please see linked issue for repro.

ResX contains
```xml
  <data name="TestFile" type="System.Resources.ResXFileRef, System.Windows.Forms">
    <value>..\Resources\TestFile;System.Byte[], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
```

GenerateResource is treating this as an Activator resource and adding it via AddActivatorResource. 
https://github.com/microsoft/msbuild/blob/d31fdbf016616835b237d2846f3f1535560bb2d5/src/Tasks/ResourceHandling/FileStreamResource.cs#L44

Here's the relevant desktop code: https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/Resources/ResXFileRef.cs,313
```c#
if(toCreate.Equals(typeof(byte[]))) {
    created = temp;
} else {
    MemoryStream memStream = new MemoryStream(temp);
    if(toCreate.Equals(typeof(MemoryStream))) {
        return memStream;
    } else if(toCreate.Equals(typeof(System.Drawing.Bitmap)) && fileName.EndsWith(".ico")) {
        // we special case the .ico bitmaps because GDI+ destroy the alpha channel component and
        // we don't want that to happen
        Icon ico = new Icon(memStream);
        created = ico.ToBitmap();
    } else {
        created = Activator.CreateInstance(toCreate, BindingFlags.Instance | BindingFlags.Public | BindingFlags.CreateInstance, null, new Object[] {memStream}, null);
    }
}
```
It looks like we missed a special case for `byte[]`.  There is also a special case here for `MemoryStream` that is likely also relevant.

**Comment by rainersigwald** [comment]
Investigate `MemoryStream`/`UnmanagedMemoryStream` magic (definitely some in StronglyTypedResourceBuilder).

**Comment by rainersigwald** [comment]
@ericstj do you know if things will work if I instantiate a `MemoryStream` in .NET Core and pass that as a live object to `AddResource`, and then try to access it at runtime in .NET Framework? Or will the type names/assemblies mismatch and cause problems?

(Likewise the other possible combinations of building on `{netcoreapp,net472}` and targeting `{netcoreapp,netstandard,netXX}`)

microsoft/msbuild#4607 has a fix for `byte[]`, and it'd be easy enough to wrap it with a `MemoryStream` but I don't understand the implications.

**Comment by ericstj** [comment]
It should work if you call [one](https://docs.microsoft.com/en-us/dotnet/api/system.resources.resourcewriter.addresource?view=netframework-4.8#System_Resources_ResourceWriter_AddResource_System_String_System_IO_Stream_) the stream [overloads](https://docs.microsoft.com/en-us/dotnet/api/system.resources.resourcewriter.addresource?view=netframework-4.8#System_Resources_ResourceWriter_AddResource_System_String_System_IO_Stream_System_Boolean_).  For these type name isn't stored, but its treated as a primitive type and will provide an UMS at runtime.
