### ISSUE TITLE
.Net Core MSBuild shouldn't try to copy .mdb files when DebugType = Portable in Linux

### ISSUE THREAD

**Issue by joperezr** [Microsoft/msbuild#459]
When using .Net Core MSBuild to build corefx repo, I'm hitting this issue when I set DebugType = Portable. The reason is that with portable pdb generation enabled, a _.pdb file will be created, instead of a *.mdb file(_.mdb files are only generated when using Mono MSBuild). The failure I'm getting is that according to Microsoft.Common.CurrentVersion.targets located on the Microsoft.Build.Targets nuget package, whenever DebugType is set to portable in a non-Windows environment, it will try to copy the PDB file as well as the MDB file which doesn't exist.
Instead of doing this, MSBuild should notice if it is running Mono MSBuild or .Net Core MSBuild, and depending on which one it is, then choose to copy the PDB or the MDB but not both.

Code in Microsoft.Common.CurrentVersion.targets looks like this:

``` xml
<_DebugSymbolsIntermediatePathMDB Include="$(IntermediateOutputPath)$(TargetName)$(TargetExt).mdb" Condition="'$(OS)' != 'Windows_NT' and '$(OutputType)' != 'winmdobj' and '@(_DebugSymbolsIntermediatePath)' == ''"/>
<_DebugSymbolsIntermediatePath Include="@(_DebugSymbolsIntermediatePathPDB);@(_DebugSymbolsIntermediatePathMDB)" Condition="'$(OutputType)' != 'winmdobj' and '@(_DebugSymbolsIntermediatePath)' == ''"/>
```

@rainersigwald provided a workaround that can be applied into corefx directly for now, but it would be nice to have the right fix in MSBuild instead.

**Comment by rainersigwald** [comment]
My commit from a year ago claims to have fixed this.
