### ISSUE TITLE
Special case String::Copy to just return the original string instead of calling String.Copy

### ISSUE THREAD

**Issue by dsplaisted** [microsoft/msbuild#4615]
Calling property functions (such as String.Replace) on item metadata values is tricky.  Generally I've seen people [use String::Copy](https://stackoverflow.com/a/8904902/) to get this to work:

```
$([System.String]::Copy('%(Filename)').Replace('config',''))
```

However, AFAIK the implementation of String.Copy creates a copy of the string data, which is unnecessary overhead.  It's possible to use `MSBuild::ValueOrDefault` to avoid this, but it's a bit more cumbersome:

```
$([MSBuild]::ValueOrDefault('%(MetadataName)', '').Replace('foo', 'bar'))
```

We should consider special-casing the `String::Copy` call to just return the string directly without the overhead of copying.

We could also add a new intrinsic function for this purpose to make it easier to understand or discover how to do this.

**Comment by rainersigwald** [comment]
If we can figure out a fix for #1155, we wouldn't need this. But it's a great quick & easy thing that would make the most popular approach a bit more efficient.
