### ISSUE TITLE
Flag for forcing output with colors when redirecting stdout

### ISSUE THREAD

**Issue by assafnativ** [Microsoft/msbuild#464]
Currently MSBuild has nice and helpful command line colors. The colors help a great deal when scanning a long output manually.
However, when redirecting the MSBuild output, like when executing MSBuild from Jenkins for instance, the colors are automatically removed. In most cases this is a reasonable thing to do, because most text editors can't parse the ANSI escape characters.
However, there is flag that was made just for that (/clp:DisableConsoleColor).
It seems like the colors are removed only becuase the C# ConsoleColors API is not good enought, it throw an exception when used while STDOUT is redirected to a file.
I think it's not a good idea to make MSBuild spit ANSI escape characters at this points, becuase users are not expecting that when redirecting the output. But there is a room for a new flag that forces the colors.
Therefore, I suggested my Pull Request #458.

**Comment by AndyGerlicher** [comment]
I'm not opposed to this entirely, but I'm a little worried that it's pretty corner case to implement in the standard console logger. Also if you want to write colorized file, it seems like using a logger that was aware of the output file format would be a much better choice than modifying the console logger and redirecting to a file. This would be very easy to implement in that way. Thoughts?

**Comment by assafnativ** [comment]
1. Implementing a new logger requires overriding the SetColor method which is defined as "internal static void SetColor (ConsoleColor c)". The code duploication in the BaseConsoleLogger.cs and ConsoleLogger.cs, makes it even harder.
2. It seems like there is a full support for colors in the default logger. However, the poor C# ConsoleColors API is throwing exception when used with redirection and all of the hard work that was done in order to generate these colors in the first place is lost.
3. The Jenkins + MSBuild environment is a very common one, everyone who uses it need to replace the default logger to get the data that is already in there.
4. It was quite hard for me to follow the trail of compiling to pinpoint what part is to blame for not having colors.
5. Colors are awesome, you want them in MSBuild.
BTW: Your Jenkins builds of MSBuild itself is so colorless for the same reason.

**Comment by AndyGerlicher** [comment]
Sorry for the delay. We discussed this one at length in triage today. We really don't like that it re-implements what should be core .NET functionality and don't want to be in the business of doing that when possible.

However, we agreed that we'd like to take this change in this case. I like that you've refactored and reduced code duplication and made the change optional behind a feature flag. And I do agree this could benefit a lot of people on CI systems such as our Jenkins build.

Please reopen the pull request I think we had a few minor comments to address. Also keep in mind that master at this point would mean Dev15 (whatever is after Visual Studio 2015), not an update.

**Comment by assafnativ** [comment]
Thank you for taking the time addressing the issue.
I've reopened the pull request.
I too would like it if .NET had a working console color API, but it doesn't. I might open a pull request there, but it's more problematic as it won't be backwards compatible.
It's a bit unfortunate it won't make it to VS2015 SP2...
