### ISSUE TITLE
 [loc][Query][msbuild] Localizability of 0; "HelpMessage_11_LoggerSwitch", 0; "HelpMessage_18_DistributedLoggerSwitch"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/msbuild#4674]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
  -logger:<logger>   Use this logger to log events from MSBuild. To specify\r\n                     multiple loggers, specify each logger separately.\r\n                     The <logger> syntax is:\r\n                       [<class>,]<assembly>[,<options>][;<parameters>]\r\n                     The <logger class> syntax is:\r\n                       [<partial or full namespace>.]<logger class name>\r\n                     The <logger assembly> syntax is:\r\n                       {<assembly name>[,<strong name>] | <assembly file>}\r\n                     Logger options specify how MSBuild creates the logger.\r\n                     The <logger parameters> are optional, and are passed\r\n                     to the logger exactly as you typed them. (Short form: -l)\r\n                     Examples:\r\n                       -logger:XMLLogger,MyLogger,Version=1.0.2,Culture=neutral\r\n                       -logger:XMLLogger,C:\\Loggers\\MyLogger.dll;OutputAsHTML\r\n

  -distributedLogger:<central logger>*<forwarding logger>\r\n                     Use this logger to log events from MSBuild, attaching a\r\n                     different logger instance to each node. To specify\r\n                     multiple loggers, specify each logger separately.\r\n                     (Short form -dl)\r\n                     The <logger> syntax is:\r\n                       [<class>,]<assembly>[,<options>][;<parameters>]\r\n                     The <logger class> syntax is:\r\n                       [<partial or full namespace>.]<logger class name>\r\n                     The <logger assembly> syntax is:\r\n                       {<assembly name>[,<strong name>] | <assembly file>}\r\n                     Logger options specify how MSBuild creates the logger.\r\n                     The <logger parameters> are optional, and are passed\r\n                     to the logger exactly as you typed them. (Short form: -l)\r\n                     Examples:\r\n                       -dl:XMLLogger,MyLogger,Version=1.0.2,Culture=neutral\r\n                       -dl:MyLogger,C:\\My.dll*ForwardingLogger,C:\\Logger.dll\r\n

File Name:
MSBuild\Resources\xlf\Strings.xlf

==========================================
Query:
It seems that some of the locked text can (and should) be localized. Please check if it is really so.

We have found that there is a locrule 
{StrContain='<strong name>'} , hence this part of this string can not be translated , otherwise it causes locvers on our side. Please advise.

**Comment by tmeschter** [comment]
@PDostalek I'm not sure where you are seeing the `{StrContain=''}` locrule. Looking at [Strings.xlf](https://github.com/microsoft/msbuild/blob/master/src/MSBuild/Resources/xlf/Strings.xlf) there are comments in the `<notes>` field:

```
      LOCALIZATION: The following should not be localized:
      1) "MSBuild", "MSBuild.exe" and "MSBuild.rsp"
      2) the string "proj" that describes the extension we look for
      3) all switch names and their short forms e.g. /property, or /p
      4) all verbosity levels and their short forms e.g. quiet, or q
      LOCALIZATION: None of the lines should be longer than a standard width console window, eg 80 chars.
```
but no explicit loc rules.

**Comment by PDostalek** [comment]
just to clarify:

 all brackets <> are part of code or can be localized ? @tmeschter 
![image](https://user-images.githubusercontent.com/29253790/66653821-2801ac00-ec39-11e9-837b-56dedbe0c3f5.png)

**Comment by rainersigwald** [comment]
Ah!

Those angle brackets are only there to indicate to the end user what can be passed in that part of the syntax. They're not intentionally related to localization. Feel free to replace them with other characters appropriate to the target language.
