### ISSUE TITLE
Add a .vsconfig to the repo

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/msbuild#4676]
Visual Studio 2019 now supports [checking in a `.vsconfig` file next to a solution](https://docs.microsoft.com/en-us/visualstudio/install/import-export-installation-configurations?view=vs-2019#automatically-install-missing-components), which presents users with a nice dialog offering to install the required workloads if they're missing some.

The MSBuild repo should have one of these. That's a much nicer experience than the existing "manually install stuff based off `README.md`".

**Comment by rainersigwald** [comment]
@forgind, can you take a look at this?

**Comment by Forgind** [comment]
Will do
