### ISSUE TITLE
Use Master as Baseline for Builds in exp/* branch

### ISSUE THREAD

**Issue by BenVillalobos** [microsoft/msbuild#4683]
Builds that are automatically triggered due to the `exp/*` prefix are always going to fail unless we set the baseline in yaml. This baseline should only be set to master and on the condition that we're on a branch with the prefix `exp/*`

**Comment by rainersigwald** [comment]
I think we can do this with a condition changing what gets passed to this:

https://github.com/microsoft/msbuild/blob/9cb0441e12879e7a70fe7c0de8ab6d5131b62c63/.vsts-dotnet.yml#L81

But I don't know how to format the condition, and if we can drop a condition in there directly or have to define a variable with a condition and then use that.

**Comment by BenVillalobos** [comment]
Closed as of https://github.com/microsoft/msbuild/pull/4897
