### ISSUE TITLE
Support disabling XML comment warnings (1591,1573) when run against a .sln

### ISSUE THREAD

**Issue by nathanaeljones** [Microsoft/msbuild#47]
MSBuild does not currently offer any way to pass-through properties to the projects within a .sln file.

[Despite the documentation](https://msdn.microsoft.com/en-us/library/ms164311.aspx), properties provided at the command line with a solution file are ignored. 

This makes it very difficult to disable XML warnings on a CI server in order to reduce output noise. Many developers feel that 30% of their lines of code should not be  `/// <summary>`, and that code noise (like output noise) must be justified .

**Comment by Craig-Campbell-MS** [comment]
@nathanaeljones I just created a project and a solution and I was able to pass through a property /p:A=B to the project while building the solution file. Can you expand on what you'd like to see? Thx

**Comment by nathanaeljones** [comment]
This may help: http://stackoverflow.com/questions/4318790/how-can-i-suppress-all-compiler-and-code-analysis-warnings-from-msbuild-at-the-c

Have you tried passing `/p:NoWarn=1591,1573` in ?

**Comment by jeffkl** [comment]
I'll be fixing this soon with #68
