### ISSUE TITLE
spurious maxcpucount warning

### ISSUE THREAD

**Issue by slymz** [microsoft/msbuild#4705]
With the following *explicit* use of `-m` switch:

```
msbuild /clp:Verbosity=minimal /nologo z-parallel-projects.sln /m:1
```

we get the following spurious warning:

```
Building the projects in this solution one at a time. To enable parallel build, please add the “/m” switch.
…
```

Not only that the message is redundant, but also our users complain and worry about the quality of an internal tooling in house which uses MSBuild in the back end.

**Comment by rainersigwald** [comment]
Related: #2005. Marking as up-for-grabs (ideally both would get fixed at once).

**Comment by Matthiee** [comment]
I'll take this one!

**Comment by rainersigwald** [comment]
All yours, @Matthiee! Please let us know if you have any questions while you're looking at it.
