### ISSUE TITLE
msbuild on dotnet on linux keeps rebuilding cs project

### ISSUE THREAD

**Issue by jeffsaremi** [microsoft/msbuild#4735]
I created this in dotnet/projectsystem thinking that that's where msbuild is
But i'm posting this here:
https://github.com/dotnet/project-system/issues/5490

I can give you the complete project to test once you tell me how I can attach files here

### Steps to reproduce

EThis is linux
Have a project that I can share with you. It keeps rebuilding no matter how many times you run msbuild /t:build

I have the full diagnostic output from the build as well

Steps to Reproduce:
```
dotnet msbuild /t:build /p:Configuration=Release path/project.csproj
```

### Expected  behavior
Build once
Then do not build as long as the input files are not modified

### Actual behavior
Builds as many times as you execute the above command and outputs new binaries with new timestamps

### Environment data
`msbuild /version` output:
$ dotnet msbuild /version
Microsoft (R) Build Engine version 16.2.32702+c4012a063 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

16.200.19.32702

OS info:
dotnet 2.2.402
and
dotnet 2.1.801

on ubuntu 16.04 x64

**Comment by livarcocc** [comment]
You mentioned in the project system issue that the issue there has been solved. Is this one still needed?

if so, we could definitely use either a repro project that we can use to try things out ourselves or, which might be better in this case, a binlog: https://aka.ms/binlog.

**Comment by jeffsaremi** [comment]
SDK 3.0.100-preview7-012821 has fixed this issue
possibly related to 
https://github.com/dotnet/project-system/issues/4736

**Comment by jeffsaremi** [comment]
What is very confusing is what is this project and what is `project-system` project? Which one do we go after when there's a build problem?

**Comment by rainersigwald** [comment]
@jeffsaremi `dotnet/project-system` is the code that Visual Studio uses to understand projects when loading them in the IDE. File issues there when they arises _only_ in Visual Studio and not on command-line builds using `MSBuild.exe` or `dotnet build`.

`microsoft/msbuild` is where the core MSBuild engine (used in `msbuild.exe` and `dotnet build`), core tasks, and core targets live. `dotnet/sdk` is the .NET Core SDK, which is used to build project targeting .NET Core.

We understand this is all pretty complicated, and we're happy to move issues around if you don't get it right on your initial try (we do that ourselves sometimes!). Don't hesitate to just take a guess.

**Comment by jeffsaremi** [comment]
Thank you for the explanation. So what I thought could have the been the fix is probably not it. But regardless the latest dotnet preview sdk fixes this problem
