### ISSUE TITLE
How do I reduce the number of intermediate folders for my zip creation

### ISSUE THREAD

**Issue by rakeshjjain** [microsoft/msbuild#4753]
Hi Team,

I am running into the same situation as case # 3682 by SamKni8 two years ago.

Did we have a solution? Can someone share?

Thanks,
Rakesh

Hi, I am new to TFS and when i build my app and Package binaries by passing inline MSBuild Argument:
/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation=$(build.artifactstagingdirectory)
Also used "Publish Build Artifact" task and provided path to publish as "$(build.artifactstagingdirectory)"
And the binaries are copied as zip but with this lengthy folder path on build server; \$BuildServer\e$\WebWork\1\a\Content\E_C\WebWork\1\s\Dev\ProviderGeoSearch\obj\Release\Package\PackageTmp$Allbinarieshere. Want to reduce these lengthy subfolders.

**Comment by rainersigwald** [comment]
@rakeshjjain I don't see a connection between your question and #3682.

It sounds like this is a problem you're encountering in Azure DevOps. Can you please [file feedback for that team with the feedback tool](https://docs.microsoft.com/en-us/azure/devops/project/feedback/give-feedback)?

Team triage: closing as this appears to be external to MSBuild.

**Comment by rakeshjjain** [comment]
Hi I have similar issue. Because of this when the Publish/Package step of the build happens using VSTS the zip has all the required folders that should be directly under wwwroot folder, way down several folders. PackageTmp has folders like app, css, bin, filters, less, Global.asax, web.config, package.json and so forth 

E:\Drop\2020.1.1.0\2020.1.1.0_20190919.3\_PublishedWebsites\JHA.ProfitStars.PSI.Devops.Web_Package\JHA.ProfitStars.PSI.Devops.Web.zip\Content\E_C\Builds\122\PSI\2020.1.1.0\Sources\Source\JHA.ProfitStars.PSI\JHA.ProfitStars.PSI.Devops.Web\DeployPackage\PackageTmp

**Comment by rakeshjjain** [comment]
@rainersigwald - can you reopen my issue and see if I can get the answer

**Comment by rakeshjjain** [comment]
![image](https://user-images.githubusercontent.com/53621485/65466277-f8bf0280-de23-11e9-9350-d28dbd5bf923.png)

**Comment by rainersigwald** [comment]
@rakeshjjain Please file feedback with the Azure DevOps (VSTS) team, since as you've described it the problem only occurs when building in VSTS.

**Comment by rakeshjjain** [comment]
@rainersigwald  - can you transfer my issue to that team and have me go through recreation?

**Comment by rainersigwald** [comment]
No, I'm sorry, we don't have tools to do that that would keep you in the loop.
