### ISSUE TITLE
Wrong output colors in OS X

### ISSUE THREAD

**Issue by JunielKatarn** [microsoft/msbuild#476]
Running a trivial PROJ file which only outputs a string:
https://gist.github.com/JunielKatarn/44bd27f56030dbbc7b23/579bf7d66babd699127f0bf64f96d0688111dc85

The output doesn't take the native color for the output font, but always seems to use black (tried this under different Terminal profiles).
Note, this also holds true for third party terminal emulators for OS X like iTerm2.
Running Mac OS X 10.11.3 .
Error messages do show in red color, though.

![image](https://cloud.githubusercontent.com/assets/4507319/12944598/ff1e2442-cf9c-11e5-9309-e94d73bed8c5.png)

**Comment by livarcocc** [comment]
Can't repro this anymore.
