### ISSUE TITLE
<UsingTask> with <TargetFramework> that .NET Framework doesn't support failed in VS

### ISSUE THREAD

**Issue by NextTurn** [microsoft/msbuild#4763]
### Steps to reproduce

Given the simplest sample

*MyTask.csproj*
```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>see below</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="16.0.461" />
  </ItemGroup>

</Project>
```

*MyTask.cs*
```cs
public class MyTask : Microsoft.Build.Utilities.Task
{
    public const string S1 = "1";
    public const string S2 = "2";

    public override bool Execute() => true;
}
```

Main project
```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <UsingTask TaskName="MyTask" AssemblyFile="...MyTask.dll" />

  <Target Name="AfterBuild" AfterTargets="Build">
    <MyTask />
  </Target>

</Project>
```

### Expected  behavior

The task should work when the `<TargetFramework>` is specified as `netcoreapp3.0`.

### Actual behavior

MSBuild in .NET CLI succeeds.

MSBuild in VS:

If the `<TargetFramework>` is specified as `netstandard2.0`, the build succeeds with the runtime to be .NET Framework.

If the `<TargetFramework>` is specified as `netcoreapp3.0`

> error MSB4062: The "MyTask" task could not be loaded from the assembly ...MyTask.dll. Could not load file or assembly '**System.Runtime**, Version=4.2.1.0, ...' or one of its dependencies. The system cannot find the file specified. ...

If the `<TargetFramework>` is specified as `netstandard2.1`

> error MSB4062: The "MyTask" task could not be loaded from the assembly ...MyTask.dll. Could not load file or assembly '**netstandard**, Version=2.1.0.0, ...' or one of its dependencies. The system cannot find the file specified. ...

### Environment data

`MSBuildBinPath` in VS:
*C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin*

**Comment by dasMulli** [comment]
The way all .NET Core tooling does this at the moment is building for both .NET Framework and .NET Core and using msbuild logic to determine the correct assembly at runtime:

```xml
<PropertyGroup>
  <CustomTaskAssembly Condition=" '$(MSBuildRuntimeType)' == 'Core' ">...\netcoreapp3.0\tasks.dll</CustomTaskAssembly>
  <CustomTaskAssembly Condition=" '$(MSBuildRuntimeType)' != 'Core' ">...\net472\tasks.dll</CustomTaskAssembly>
</PropertyGroup>

<UsingTask TaskName="MyTask" AssemblyFile="$(CustomTaskAssembly)" />
```

**Comment by NextTurn** [comment]
So it's not possible to use .NET Core specific APIs right now?

**Comment by dasMulli** [comment]
Not if it has to run on the .NET Framework version of MSBuild which is used by VS as well as VS/Mac and OmniSharp (mono).

**Comment by SimonCropp** [comment]
@dasMulli is there any eta on when netstandard2.1 will be able to be used when running an msbuild task from within VS? is there any issue to track that work?

**Comment by dasMulli** [comment]
I think never since .net framework will never support ns2.1
But not sure if the Team has other plans

**Comment by rainersigwald** [comment]
Filed microsoft/msbuild#4834 to track @SimonCropp's request. It is not currently on our radar, but I suspect that we'll need it at some point as adoption of .NET Core increases.

**Comment by Jinjinov** [comment]
Is this feature coming in .Net 8?
