### ISSUE TITLE
Design-time build tasks aren't all available in .NET Core

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/msbuild#4770]
See https://github.com/dotnet/roslyn/issues/36072#issuecomment-536088468 for a nice repro by @d-dizhevsky.

> I have created repro project here: https://github.com/d-dizhevsky/owss
> 
> It contains:
> 
> * `src/OpenWebSecurityScanner` project which targets `netcoreapp2.1` and runs MSBuildWorkspace
> * `testProjects/WebAPI1` which was created with `dotnet new webapi`
> * `testProjects/TestCoreLib` which was created with `dotnet new classlib`
> 
> The `WebAPI1` has a project reference on `TestCoreLib`.
> Just do `cd src/OpenWebSecurityScanner/` and then `dotnet run`.
> 
> Thats my output on OSx:
> ![image](https://user-images.githubusercontent.com/25821724/65800583-82056a80-e17f-11e9-8b47-89d6df9be873.png)

----

This is happening because some tasks that are used in design-time builds (and design-time-like builds like Roslyn `MSBuildWorkspace`) aren't ported to .NET Core.

Right know there's only one known failure; I suspect there may be a few more after fixing this one:

- [ ] [`ResolveNonMSBuildProjectOutput`](https://github.com/microsoft/msbuild/blob/49729650232e1e7c1f7a1016c83c5d6f254cfa04/src/Tasks/ResolveNonMSBuildProjectOutput.cs).

**Comment by rainersigwald** [comment]
The .NET Core flavor of `ResolveNonMSBuildProjectOutput` should probably just do nothing; I don't think .NET Core MSBuild needs to support non-MSBuild `ProjectReference`s.

**Comment by ceztko** [comment]
How this can not affect almost 100% of real world use cases in Linux/MacOSX? Very simple project dependency graphs doesn't work trying to compile them with `MSBuildWorkspace`, and Linux/MacOSX should support only .NET core/standard projects, if I'm not wrong. Also, projects don't compile even when targeting `.netstandard2.0`, as the [#36072](https://github.com/dotnet/roslyn/issues/36072#issue-450522001) reporter clearly states in the first post. It would be great if there's an attempt fix by implementing an empty `ResolveNonMSBuildProjectOutput`: this should allow to quickly spot other issues, if present. Will fixing this issue require an upgrade of the .NET core sdk?

**Comment by ceztko** [comment]
Fantastic! Any idea of when this will be integrated in VS?

**Comment by ceztko** [comment]
Now I noticed the branch where the commit was merged: microsoft:vs16.5. Thank you.

**Comment by miyu** [comment]
Following ceztko's reasoning, this, updating VS, and a few other manual twiddles likely fixed loading .net core 3.1 projects with Roslyn for me. Adding a link to my notes for any other unfortunate (now fortunate!) adventurers :) 

https://github.com/dotnet/roslyn/issues/36072#issuecomment-610809322
