### ISSUE TITLE
Question: Restore package in a publish way

### ISSUE THREAD

**Issue by TFTomSun** [microsoft/msbuild#4771]
Is there any possibility to simply restore a package and all of its dependencies and put them together in one output like a publish build would do it? 

My current workaround is to create a temporary project with a package reference to the given package and then perform a build on that temporary project. 

Unfortunately I need to know the TargetFramework(s) of the package to create a matching temp project and I get additional output (dll) for the temp project, which I actually don't need. I would like to have a common solution that always works, no matter which package I want to restore (even if I don't know its supported target frameworks).

**Comment by livarcocc** [comment]
Please, file an issue for this on nuget/home. You might get a better and faster answer there.
