### ISSUE TITLE
GenerateResource w/ ResXFileRef System.IO.MemoryStream, mscorlib, Version=2.0.0.0 fails at runtime

### ISSUE THREAD

**Issue by ericstj** [microsoft/msbuild#4773]
Originally reported here https://github.com/dotnet/coreclr/issues/26472#issuecomment-536176848.  Thanks @koszeggy 

### Steps to reproduce
Include resources that use ResXFileRef for a MemoryStream with 2.0.0.0 assembly identity for mscorlib.
Build.
Access resource at runtime.

### Expected  behavior
Resource is returned as UnmanagedMemoryStream.

### Actual behavior
Resource is treated as an Activator resource and we attempt to call the a MemoryStream constructor passing in the backing stream, which fails because MemoryStream doesn't have a constructor that takes a stream.

### Environment data
dotnet.exe 3.0.100

Bug is here: https://github.com/microsoft/msbuild/commit/edb3be367107d5976dd5a9b30ed067b24f982668#diff-5a51b7df470ec16b6d58bdf7234efefeR85

Here's  a repro: https://github.com/ericstj/repros/tree/master/testMemStreamResXFileRef

/cc @rainersigwald

**Comment by rainersigwald** [comment]
I could have sworn we discussed this and decide on only 4, but I don't see that discussion, just the mscorlib/System.Private.CoreLib. Perhaps I was just confused. This is similar to what was necessary for `string` in microsoft/msbuild#4638.

Is checking for `2.0.0.0` sufficient, or are there other relevant versions? Looks like string was just 2.

## Workaround

Change the resx to MemoryStream version 4, for example:

```diff
diff --git a/testMemStreamResXFileRef/Resources.resx b/testMemStreamResXFileRef/Resources.resx
index f4201cc..f7d3df7 100644
--- a/testMemStreamResXFileRef/Resources.resx
+++ b/testMemStreamResXFileRef/Resources.resx
@@ -122,6 +122,6 @@
     <value>test.wav;System.IO.MemoryStream, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
   </data>
   <data name="test2.0" type="System.Resources.ResXFileRef, System.Windows.Forms">
-    <value>test.wav;System.IO.MemoryStream, mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
+    <value>test.wav;System.IO.MemoryStream, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
   </data>
 </root>
\ No newline at end of file
```

**Comment by ericstj** [comment]
Looks like this eventually calls Type.GetType https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/Resources/ResXFileRef.cs,289

That appears to be super tolerant of garbage if the assembly name is `mscorlib`.  All the following work for me:
```
Type.GetType("System.IO.MemoryStream, mscorlib, Version=5i.300.-2.π, Culture=neutral, PublicKeyToken=0000086753090000")
Type.GetType("System.IO.MemoryStream, mscorlib, Version=never, Culture=nowhere, PublicKeyToken=nobody")
Type.GetType("System.IO.MemoryStream, mscorlib, trash trash, blah blah")
Type.GetType("System.IO.MemoryStream, mscorlib, ............")
Type.GetType("System.IO.MemoryStream, mscorlib, , , , , , , , , , , , , , , ")
Type.GetType("System.IO.MemoryStream, mscorlib,............")
Type.GetType("System.IO.MemoryStream, mscorlib,d.dkjfhsahgliofsdty -08u[0ip'fjsdcgv;okhn aWE; YUFGQPOIJH DFSG/LVN'ASSDFAKULGD FLIKJHJDGFKAJHSDL'AH;vrne4oosjh;'lyhkjh;'lskdfgjh;'okshj'pofrijg]sdojf.,fkdf;'.afds./.,/s.fdfdDZlJXJMDA;KOLUIFDUH")
```

I bet a check of StartsWith would be safe and match what was previously permitted.
