### ISSUE TITLE
EmbeddedResource not working inside Target

### ISSUE THREAD

**Issue by Jmales** [microsoft/msbuild#4778]
I have some TypescriptCompile files which I then want to embed in my .dll. I had to migrate to the new csproj format and now I can't embed while inside a Target.

This works:

```
    <Project Sdk="Microsoft.NET.Sdk">
       <PropertyGroup>
           <TargetFramework>net472</TargetFramework>
       </PropertyGroup>
       <ItemGroup>
           <EmbeddedResource  Include="testFile.ts" />
       </ItemGroup>
    </Project>
```

While this does not:

```
    <Project Sdk="Microsoft.NET.Sdk">
       <PropertyGroup>
           <TargetFramework>net472</TargetFramework>
       </PropertyGroup>
       <Target Name="AddGeneratedToBuildOutput" BeforeTargets="CoreCompile">
           <ItemGroup>
               <PackageFiles Include="$(MSBuildProjectDirectory)\**\*.*;"/>
           </ItemGroup>
           <Message Text="The target is called: %(PackageFiles.FullPath)" Importance="high"/>
           <ItemGroup>
               <EmbeddedResource  Include="testFile.ts" />
           </ItemGroup>
        </Target>
    </Project>

```
Note that the message gets written and the referred file is in the project, hence we can be sure that the target gets called.

I already tried other targets instead of `**CoreCompile**` but since I'm using TypeScriptCompile, if I use `**BeforeBuild**`, `**Build**` or `**ResolveReferences**` I get compilation errors since the .js files are not generated yet. 

I'm using JetBrains' DotPeek to inspect the resources and msbuild 15.0.

**Comment by rainersigwald** [comment]
The supported extension point for adding just-built resources to `@(EmbeddedResource)` so that they get compiled is `BeforeTargets="BeforeResGen"`. I don't know where TypeScript hooks their compiler; it might be later than that in the default build process. You'd have to ask them if they'd support being forced to run earlier.

**Comment by Jmales** [comment]
@rainersigwald `BeforeResGen` doesn't seem to solve my problem. I'll go in that direction, finding out which is the TypescriptHook.

**Comment by Jmales** [comment]
But wait, I was checking again and this has nothing to do with **TypeScript** in fact.

I can't add any resource within a target with  "BeforeResGen".

**Comment by rainersigwald** [comment]
It looks like dynamically emitting an `EmbeddedResource` at build time requires some additional metadata:

https://github.com/microsoft/msbuild/blob/3af6804637c057bf46bddccf23f1ede027885088/src/Tasks/Microsoft.Common.CurrentVersion.targets#L3280-L3281

I was able to get your target to work like this:

```xml
<EmbeddedResource Include="dynamic.ts" Type="Non-Resx" WithCulture="false" />
```

**Comment by Jmales** [comment]
Yes, this solves the problem. Thanks a lot mate!

**Comment by Jmales** [comment]
@rainersigwald I noticed that the resources are in fact added but without the full name as before. For example, this:

**ProjectName.View.A.file.js**

after the suggested modifications is now embedded simply with name:

**file.js**

I'm having a problem with this project's dll and I guess that it is related to this. Do you know if this is because of the "WithCulture=false" and how to solve the issue?

Thanks

**Comment by Jmales** [comment]
To answer my own question, the way that I found to solve this was to use <LogicalName> like this:

         `<LogicalName>MyProject.$([MSBuild]::ValueOrDefault('%(TypeScriptCompile.RelativeDir)', '').Replace('\', '.'))%(TypeScriptCompile.Filename).js</LogicalName>`

This in fact solves my issue at runtime.

**Comment by SmiRam** [comment]
This solution by @Jmales is not working for me.

I want to add a resx file which is generated dynamically to my .Net standard project. The below script does not work if I use the Embedded resource tag inside a target

```
<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <ResxFileToInclude Include="D:\WS\Latest\Build\x64\Release\AFS.resx"/>
    </ItemGroup>
    <Target Name="ResxInclude" AfterTargets="Compile">
        <ItemGroup>
            <EmbeddedResource Include="@(ResxFileToInclude -> '%(RelativeDir)%(Filename).resx')" Type="Resx" WithCulture="true">
            <LogicalName>"$([MSBuild]::ValueOrDefault('%(ResxFileToInclude.RelativeDir)', '').Replace('\', '.')).%(ResxFileToInclude.Filename).resx"</LogicalName>
        </EmbeddedResource>
        </ItemGroup>
    </Target>
</Project>
```

Can anyone help me in this?

**Comment by rainersigwald** [comment]
@SmiRam your target is happening pretty late in the build process (`AfterTargets="Compile"`). Can you change that to `BeforeTargets="BeforeResGen"`?

**Comment by SmiRam** [comment]
@rainersigwald : Thanks for supporting my issue.
 It was my misassumption that the resource file is not getting included in the project. The disassembly of the binary shows that actually the resx file is part of assembly. But when the project is loaded for the first time in Visual Studio, the included resx file will be shown with a cross mark beside the file in VS IDE. 

![Screenshot 2021-06-02 230034](https://user-images.githubusercontent.com/44302530/120526139-83784300-c3f6-11eb-94f9-e6f6a4dfd890.jpg)

Rebuild of the project will not get rid of the cross mark, but a project reload will do.
For a background information, the resx file is generated before the execution of the target "CoreCompile"
How to remove this cross mark for the first time loading of project in Visual Studio?
VS version:16.10.0
