### ISSUE TITLE
Need Solution File extensibility point that works for multiple solution files

### ISSUE THREAD

**Issue by jeffkl** [microsoft/msbuild#4784]
# Background

Currently, MSBuild generates an in memory "metaproj" representation of a Visual Studio Solution File.  This metaproj can be extended with two mechanisms:

1. Place a file in `$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\SolutionFile\ImportBefore` and/or `$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\SolutionFile\ImportAfter`
2. Create a file named `before.MySolution.sln.targets` and/or `after.MySolution.sln.targets`

The first extensibility mechanism is machine wide and requires elevated privileges to write to.  The second extensibility mechanism requires a file per Solution File.

We need a third extensibility point for the metaproj similar to `Directory.Build.props`/`Directory.Build.targets`.  This mechanism is per repository and would apply to the building of all Solution Files rather than each one.

## Design Spec

The metaproj should import a file named `Directory.Solution.props` at the top and a file named `Directory.Solution.targets` at the bottom.  We cannot reuse `Directory.Build.props` or `Directory.Build.targets` because those files already exist today and if the next version of MSBuild started importing them when building a Solution File then it could be a breaking change.

Users can opt to have their `Directory.Solution.props` simply import `Directory.Build.props` so it wouldn't end up being that much overhead for users who want to adopt the feature.  On the plus side, having a separate file for extending metaproj versus every project in the tree would mean users wouldn't have to condition everything in the single file.  

It should be possible to disable each import with the following properties:

1. `ImportDirectorySolutionProps`
2. `ImportDirectorySolutionTargets`

And users can specify a custom full path file name if they don't want to use the default:

1. `DirectorySolutionPropsPath`
2. `DirectorySolutionTargetsPath`

Finally, the feature should be documented here: https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build

Related to #222
Follows in the footsteps of #751

**Comment by omariom** [comment]
Is there any way to pass properties from the solution metaproj to its projects?

**Comment by rainersigwald** [comment]
@omariom Can you open a new issue with that question, including some background on why you'd like to do that, please?
