### ISSUE TITLE
Unable to build old projects with VS2019 - MSB4019

### ISSUE THREAD

**Issue by weitzhandler** [microsoft/msbuild#4786]
### Steps to reproduce
Hello

I'm trying to get the [odata.net](https://github.com/OData/odata.net) repo to build on VS2019.
I've updated the build.ps1 file (https://github.com/weitzhandler/odata.net/commit/3dbcceffba5c49f95515b534d17505ecf99fe0cc) with the appropriate paths and all, but I'm still getting the following error x5:

>C:\Users\HP\source\repos\odata.net\tools\CustomMSBuild\Portable.targets(17,3): error MSB4019: The imported project 
"C:\Program Files (x86)\Microsoft Visual 
Studio\2019\Community\MSBuild\Microsoft\Portable\v5.0\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. 
[C:\Users\HP\source\repos\odata.net\src\Microsoft.Spatial\Build.NetStandard\Microsoft.Spatial.NetStandard.csproj]

After checking, the `Portable` folder is completely missing.
I only have 2019 installed on my machine.

Is there anyway I can get this to run on a VS-only machine while still maintain project backwards compatibility (so that it can still build in older versions of VS)?

### Expected  behavior
File [build.ps1](https://github.com/weitzhandler/odata.net/blob/vs2019/build.ps1) should execute properly

### Actual behavior
Old build paths not found

### Environment data
`msbuild /version` output: 

>16.2.37902.0

OS info:
Windows 10x64 (1903 - build 18362.356)
VS 2019 (16.2.x)

**Comment by jmarolf** [comment]
If you scroll all the way down below Snapshot Debugging on the [VS 2019 release notes](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-v16.0#dotnettools) (or just search for PCL on the page). You will see:

> Portable Class Library (PCL) project templates are no longer available, and project support will not be installed by default. New projects intended to target multiple platforms should use the .NET Standard project type. Customers who require PCL project support must install the component separately from the Individual Components tab in the Visual Studio installer.

Here is the item in the installer you will need to check for things to work

![image](https://user-images.githubusercontent.com/9797472/66274892-1b93e280-e838-11e9-912b-c2487a903362.png)

**Comment by weitzhandler** [comment]
Hi there and thanks for your response.
That item is checked in my installation.

**Comment by weitzhandler** [comment]
That solved the issue.
Thank you so much!

**Comment by devsoftx** [comment]
Hi
I got this error when I executed dotnet build, I just updated vs2019 with new .NET 5, however when I build with VS2019 works, but with CLI:

C:\Program Files\dotnet\sdk\5.0.100\Current\SolutionFile\ImportAfter\Microsoft.NET.Sdk.Solution.targets(14,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\3.1.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.Common.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\sdk\3.1.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.Common.targets" is correct, and that the file exists on disk

same issue with msbuild XXX.sln

 error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.

dotnet msbuild version:
MSBUILD : error MSB1001: Unknown switch.
Switch: --version

Thanks in advance

**Comment by stonstad** [comment]
> Hi
> I got this error when I executed dotnet build, I just updated vs2019 with new .NET 5, however when I build with VS2019 works, but with CLI:
> 
> C:\Program Files\dotnet\sdk\5.0.100\Current\SolutionFile\ImportAfter\Microsoft.NET.Sdk.Solution.targets(14,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\3.1.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.Common.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\sdk\3.1.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.Common.targets" is correct, and that the file exists on disk
> 
> same issue with msbuild XXX.sln
> 
> error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
> 
> dotnet msbuild version:
> MSBUILD : error MSB1001: Unknown switch.
> Switch: --version
> 
> Thanks in advance

I'm seeing the same behavior.  w/ .NET Portable Library targeting pack already installed.

**Comment by marekdovjak** [comment]
Same issue here, .NET Portable Library targeting pack already installed. Anyone got solution?

**Comment by marekdovjak** [comment]
I migrated the old .net4.x project causing the issue to netstandard (or net5) and it works now

**Comment by ailn** [comment]
Same issue:
C:\Program Files\dotnet\sdk\5.0.103\Current\SolutionFile\ImportAfter\Microsoft.NET.Sdk.Solution.targets(14,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\3.1.404\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.Common.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\sdk\3.1.404\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.Common.targets" is correct, and that the file exists on disk.
