### ISSUE TITLE
Update help to show the correct switch prefix

### ISSUE THREAD

**Issue by david-mitchell** [Microsoft/msbuild#48]
When msbuild is built in one of the Mono configurations, all command line switches are configured to require a `-` prefix rather than a `/` prefix. However, the contents of the `-help` command line switch have not been updated to reflect this.

**Comment by david-mitchell** [comment]
From my reading of the code, it appears that Windows accepts `/` or `-`, while Unix only accepts `-`. Given this, the simplest fix would be to replace `/` with `-` across the board in all help messages.

**Comment by akoeplinger** [comment]
I'd strongly vote for accepting `/` as the command line switches, otherwise migrating builds scripts from xbuild (which accepts `/`) will be a huge pain.

**Comment by david-mitchell** [comment]
@akoeplinger I believe the only thing needed to do for that approach would be to eliminate the `#if` block at https://github.com/Microsoft/msbuild/blob/f112881f2ef7647d964a92690e15d8613685e5a1/src/XMakeCommandLine/XMake.cs#L1295-1300

**Comment by AndyGerlicher** [comment]
MSBuild team triage: The change was done for simplicity to be able to determine if the parameter is a path or MSBuild switch, it's definitely more involved than just removing the #if block. We would accept the change if it included unit tests for the different scenarios (files, invalid parameters, etc.). We're also happy for the help text to be updated in the xplat branch either way.

**Comment by akoeplinger** [comment]
@AndyGerlicher is the only concern here that MSBuild would mistake a file named e.g. `/nologo` as a switch on Linux if we just removed the #if? That wouldn't doesn't sound like a compelling reason to me honestly :)

**Comment by ValMenn** [comment]
@akoeplinger It has more to do with what happens when a path (that starts with a slash) is interpreted as a switch, only to determine that it is not valid (that's what would currently happen after the #if block is removed). Additional code needs to be added to check if the "bad" switch is in fact a file path. Your case (when a file path happens to be a valid switch) is less likely and may not be of concern as there is no easy way to handle this anyway.

**Comment by akoeplinger** [comment]
@ValMenn ok, thanks for your response. I'll take a look and see if I can come up with something here.

**Comment by akoeplinger** [comment]
I opened a PR that allows using / for switches: https://github.com/Microsoft/msbuild/pull/91

**Comment by akoeplinger** [comment]
@david-mitchell since my PR was merged, I think the primary reason for this issue does no longer apply, so I think this can be closed. Or do you think we should still be recommending `-` prefix on Unix?

**Comment by david-mitchell** [comment]
@akoeplinger agreed.
