### ISSUE TITLE
Standalone Build Tools update

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#480]
People often install [Microsoft Build Tools 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48159) alone on a build server, to avoid having to manage a full Visual Studio installation. But the latest Build Tools installer is for VS2015 RTM, and there's no way to update it (trying to run the full VS update installer fails because "nothing applicable" is installed).

This is something we can only fix internally, since it's official-release-process related.

**Comment by DanTup** [comment]
If there's any workaround in the meantime (such as installing the original build tools and copying stuff from a VS machine), we'd be interested to know. We're keen to start using the new features, but we're nervous about some of the issues reported in the original release of the compilers :(

**Comment by wgtmpeters** [comment]
I think managing the build tools on a server is a larger problem then just the MS Build Tools currently.
As there is no way to simple install everything you need on a CI.
Currently is seems to involve manual installation of Build Tools, SDK's and copying reference assemblies and msbuild targets from developer machines to get it to work.
It would be great if there was a better solution for the installation process of a CI for msbuild.

**Comment by DanTup** [comment]
Do you know how likely this might be addressed in time for Update 2 RTM? If it's unlikely and we need to start adding the NuGet packages to our projects, it'd be good to get a head-start!

**Comment by rainersigwald** [comment]
@DanTup We've made the internal changes and daily builds of Update 2 RC are producing this installer. We do expect it to be released with RC and with RTM Update 2.

**Comment by DanTup** [comment]
@rainersigwald Excellent! Thanks for the update :)

**Comment by rainersigwald** [comment]
Update 2 RC has a Build Tools package available: http://go.microsoft.com/fwlink/?LinkId=690660. Please let us know if you try it and see any problems since the Update 2 RTM release is fast approaching.

**Comment by DanTup** [comment]
I'd be nervous about installing the RC on our production build server and don't easily have another way to test this; though I have faith in your ability to build the installer and presume the compilers will get a good testing by others :D

**Comment by DanTup** [comment]
That said; I'm presuming installing this would cause our builds to automatically use it; if it would need to us to change which MSBuild we call and wouldn't affect anything else then maybe we can test it (we're currently using a pre-2015 MSBuild (12?) and never installed the original version of these build tools).

**Comment by rainersigwald** [comment]
@DanTup Ah, that's interesting. I too would be nervous about applying the RC in production. Note that AFAIK the only way to use the updated Roslyn across the board would be to switch to MSBuild 14 (with Update 2)--MSBuild 12 should be untouched by this installation.

**Comment by FranklinWhale** [comment]
Visual Studio 2015 Update 2 RTM is now available. Can we expect that an updated MSBuild will be released soon?

**Comment by DanTup** [comment]
The update tools appear to be here :)

https://www.visualstudio.com/downloads/download-visual-studio-vs#d-build-tools

However there's a weird layout issue with that page so you'll have to scroll down to see them!

**Comment by wgtmpeters** [comment]
Maybe the Visual Studio Update 2 release should also mention the Build tools Update 2 and its location. Because its hard to find if you do not know where to look for it. Especially for users that have no idea that this was going to be release together with the update.

**Comment by DanTup** [comment]
I found the link from this page:

https://www.visualstudio.com/en-us/news/vs2015-update2-vs.aspx

It's under "Related releases" labelled "Microsoft Build Tools 2015 Update 2" :)

**Comment by wgtmpeters** [comment]
My bad! Guess my eyes skip over that part :)

**Comment by rainersigwald** [comment]
I created a GitHub [release](https://github.com/Microsoft/msbuild/releases/tag/v14.0.25123.0-ish) for Update 2, which links to both the overall update announcement page and the Build Tools standalone installer. Thanks for making finding those links easy, @DanTup :grinning:

**Comment by jihohan** [comment]
@DanTup the page no longer has the build tools under Related Releases section
@rainersigwald the link to the update 2 installer no longer exists
I wish Microsoft had a proper download page for it. Fortunately, I am an MSDN subscriber and it's available as a download. It's good to know that money still works.

**Comment by DanTup** [comment]
This link still works for me:

https://www.visualstudio.com/downloads/download-visual-studio-vs#d-build-tools

shows "Microsoft Build Tools 2015 Update 3"

However, it did redirect me to a "beta" website which I had to click "Exit" from and then navigate back to the link.

Direct download link: https://go.microsoft.com/fwlink/?LinkId=615458

**Comment by mburr** [comment]
It would be nice if Microsoft could indicate in the filename which version it is.

**Comment by Pavnii** [comment]
Is it possible to have MSbuild update 1 and update 3 on same build server?

**Comment by rainersigwald** [comment]
@Pavnii For Build Tools 2015, no, that's not possible. It is now possible to have multiple copies installed starting with Build Tools 2017.
