### ISSUE TITLE
Code Analysis is not working for WDK project on Windows container

### ISSUE THREAD

**Issue by liangming2003** [microsoft/msbuild#4801]
I got following error when compiling a C++ driver project with Build Tools 2017 in Windows container “windowservercore”.

```
Running Code Analysis for C/C++...

c1xx : error C2220: warning treated as error - no 'object' file generated [C:\jenkins\workspace\ABC-DEV\ABC\ABC.vcxproj]

c1xx : fatal error C1250: Unable to load plug-in 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\localespc.dll'. [C:\jenkins\workspace\ABC-DEV\ABC\ABC.vcxproj]
```

Building it with same build tools and workloads on Win10 does not have this problem.
localespc.dll is actually present under ‘C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin’ in container.

Compile script:

```
call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x64

"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe"  C:\Work\ABC.sln /p:configuration=Release /p:platform=x64 /t:rebuild
```

The Error C1250 can be resolved by adding the /p:PlatformToolset=v141 to the compile command, but the project cannot be built successfully with the value of PlatformToolset change from “WindowsKernelModeDriver10.0” to “v141”.

Any idea what wrong with it?  Thanks.

BTW, is there any MSbuild option that can override the code analysis setting in the project file and I want to disable the code analysis if the error can not be resoved.  

For details of the problem,please see the below link.
https://developercommunity.visualstudio.com/content/problem/647444/code-analysis-is-not-working-on-windows-container.html

**Comment by livarcocc** [comment]
Please, file a VS feedback item for this through Visual Studio and this will get routed to the right team. You will get a faster and better answer that way.

**Comment by livarcocc** [comment]
As suggested in the VS Feedback item, this is a bug on the Windows SDK for this issue. The MSBuild repo is not the right repo for this issue.
