### ISSUE TITLE
ItemGroup inside skipped Target still gets called

### ISSUE THREAD

**Issue by Jmales** [microsoft/msbuild#4809]
Apparently, ItemGroups inside Targets are always called, no matter if the target gets skipped or not. Is this the expected behavior?

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

    <Target Name="Test" BeforeTargets="Ts2LangBuild">
		<Message Text="CompileBefore:@(Compile)" Importance="high" />    
    </Target>
    
    <Target Name="Test2" AfterTargets="Ts2LangBuild">
		<Message Text="CompileAfter: @(Compile)" Importance="high" />    
    </Target>

    <Target Name="Ts2LangBuild" BeforeTargets="CoreCompile" Inputs="test.ts" Outputs="testOutput.txt">
        ....
        <ItemGroup>
            ....
            <Compile Remove="@(Compile)" />
            ....
        </ItemGroup>
        <Message Text="The target is called: %(PackageFiles.FullPath)" Importance="high" />
    </Target>
</Project>
```

If I build this project, the target **Ts2LangBuild** is reported as skipped but **CompileAfter** returns empty because the **<Compile Remove .. />** is still called.

If a target gets skipped I expect that everything inside it getting skipped as well. Why is **ItemGroup** not skipped?

Using MSBuild 16.2.37902.0.

**Comment by rainersigwald** [comment]
Yes, this is expected; it's documented as [output inference](https://docs.microsoft.com/en-us/visualstudio/msbuild/incremental-builds#output-inference).

Skipping item creation in targets that were skipped as up-to-date would be bad in some situations. For example:

* Target `A` runs before the compiler and generates some code `C.cs` based on `input.txt`
* `A` defines inputs/outputs so it can be run incrementally.

1. Build the project completely
   1. `A` is out of date so it generates `C.cs` and adds it to the `Compile` item.
   1. The compiler sees `C.cs`
1. Edit a source file but _not_ `input.txt`
1. Build the project incrementally
   1. `A` is skipped because it is up to date
   1. Without output inference, `C.cs` doesn't get added to `@(Compile)`
   1. The compiler fails when code refers to types defined in `C.cs`.

**Comment by Jmales** [comment]
Thanks a lot for the answer @rainersigwald.  Didn't knew about that at all!

So, in my case, how do I avoid an Item Group or a Compile Remove to get called when a target gets skipped? 

I think I need that because in my specific case I remove the duplicates from a list so I need all of this inside my target:

```
         <ItemGroup>
                     <CompileList Include="@(Compile->'%(FullPath)')"/>
         </ItemGroup>

        <CreateItem Include="$(ProjectDir)Generated\**\*.cs">
			<Output TaskParameter="Include" ItemName="CompileList"/>
        </CreateItem>
 
        <RemoveDuplicates Inputs="@(CompileList)">
			<Output TaskParameter="Filtered" ItemName="FilteredCompile" />
        </RemoveDuplicates>
         
         <ItemGroup>
		 <Compile Remove="@(Compile)" />
		 <Compile Include="@(FilteredCompile)" />
         </ItemGroup>
```

And RemoveDuplicates doesn't seem to be running when the target gets skipped. Using **diagnostic** verbosity level I noticed that the `CompileList` items are added and the ` (Compile)` are removed, probably because `FilteredCompile` is empty (can't know for sure because I can't put a **Message** inside an **ItemGroup**.

**Comment by rainersigwald** [comment]
Can you move the item manipulations to an always-run target (no inputs/outputs) that depends on the incremental target that generates the files?

**Comment by Jmales** [comment]
Yeah I can, and that seems to solve the issue at hands. Thanks a lot mate, you have been a great help in this and in other issues that I stumble upon ;)

Still, I wonder why `Compile Remove`, `Somelist Include` get called when the target gets skipped but not the `RemoveDuplicates`? Is it because task `RemoveDuplicates` is not an  item creation task and only item creation tasks are called as part of the output inference?

**Comment by rainersigwald** [comment]
> Still, I wonder why `Compile Remove`, `Somelist Include`, etc get called when the target gets skipped but not the `RemoveDuplicates`? Is it because task `RemoveDuplicates` is not an item creation task and only item creation tasks are called as part of the output inference?

Exactly. While `RemoveDuplicates` is shipped with MSBuild and we could probably predicts its results, that's not true of a task in general, since they can run arbitrary .NET code. So the predictor predicts only "standard" item operations.

**Comment by Daniel-Khodabakhsh** [comment]
Thanks for the suggestion @rainersigwald but I don't see how that would solve the issue: the always-run target will always run, which is not what @Jmales wants. @Jmales wants to conditionally manipulate the itemgroup items based on whether or not the target is run. Even though you `DependsOnTargets` on a skipped target, the item group manipulation target will still run whether or not the incremental target runs.

Similar to @rainersigwald's suggestion, move the item manipulation to a separate target, but then use [`CallTarget` task](https://docs.microsoft.com/en-us/visualstudio/msbuild/calltarget-task?view=vs-2019) from within your incremental target to call the itemgroup item manipulation target:

```xml
<Project ...>

    <Target Name="UpdateMyItems">
        <ItemGroup>
            <!-- This is just an example of some item group manipulation. -->
            <SomeItemType Remove="@(SomeItemType)" />
            <SomeItemType Include="SomeDirectory\**" />
        </ItemGroup>
    </Target>

    <Target Name="MyIncrementalTarget" Inputs="..." Outputs="...">
        <SomeTask1 ... />
        <SomeTask2 ... />
        <CallTarget Targets="UpdateMyItems" />
        <SomeTask3 ... />
    </Target>

</Project>
```

With this, the `UpdateMyItems` target will not be called if `MyIncrementalTarget` is skipped to due its incremental nature.

Another advantage of doing it this way is that the tasks within `MyIncrementalTarget` are executed sequentially, so `SomeTask3` would be exposed to the updated item groups.
