### ISSUE TITLE
 [loc][Query][msbuild] Localizability of 0; "ImportedProjectNotFound"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/msbuild#4815]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
MSB4019: The imported project "{0}" was not found. Confirm that the expression in the Import declaration "{1}" is correct, and that the file exists on disk.

File Name:
Build\Resources\xlf\Strings.xlf

==========================================
Query:
According to the DevComment, `<Import>` should not be localized.
Does it refer to "Import" of "the Import declaration" in this source?
Could you please confirm?

**Comment by rainersigwald** [comment]
@PDostalek I edited your post to put `` ` `` characters around `<Import>`; if you don't do that, GitHub-flavored Markdown hides the text inside the `<>`.

**Comment by rainersigwald** [comment]
That instruction is intended to read as

> Don't localize the word `Import` in `the Import declaration`; it refers to an XML attribute.

**Comment by PDostalek** [comment]
Thanks for clarification
