### ISSUE TITLE
MSBuild 15.3.409.57025 fails to build .net 2.2 apps when .NET Core 3.0.100 SDK is present

### ISSUE THREAD

**Issue by patricklee2** [microsoft/msbuild#4826]
MSBuild 15.3.409.57025 fails when .NET Core 3.0.100 SDK is present

My project targets 2.2, msbuild should ignore 3.0 sdk

I'm aware that msbuild 16 is require to build .net core 3.0 apps, but I'm building a 2.2 app
Is there a way to allow them to live side by side without upgrading to msbuild 16

### Steps to reproduce
project: https://github.com/patricklee2/dotnetcore22console
installed SDKs
2.2.109
3.0.100

Command line
MSBuild.exe" dotnetcore22console\dotnetcore22console.csproj 

### Expected  behavior
Should be able to build the project

### Actual behavior
 error : The current .NET SDK does not support targeting .NET Core 2.2.  Eit
her target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2. [D:\Users\webworkeradmin\Desktop\dotnetcore22console\dotnetcore22console\dotnetcore22console.csproj]

OS info:
windows

**Comment by livarcocc** [comment]
This is by design. The MSBuild version required by the SDK is determined by the SDK version and not by the target framework of the application that you are trying to build with that SDK.

**Comment by patricklee2** [comment]
I understand that 3.0 requires msbuild 16. but I'm building 2.2 apps.

2.2 apps do not have a dependency on ms build 16, and should still work with msbuild 15

**Comment by felyperennan** [comment]
We need .Net to be reliable and respect project's target settings, because if we have to worry that having the newest SDK will break our working code then we'll have more problems than our fucked up daily routine already gives us.

**Comment by patricklee2** [comment]
this occurs because we had a custom version of msbuild.  I tried it on msbuild I got from VS 2019 and it works as expected.

Working with msbuild team directly to solve it.

**Comment by felyperennan** [comment]
It took me a long lasting while to find out that you can overwrite dotnet.exe default action and force it to use a specific SDK version to build your project/solution; All it takes is to add a global.json to the solution/project folder 🤷‍♀️

Example: 
```
{
  "sdk": {
    "version": "2.2.300"
  }
}
```

If you add a global.json to a folder with that content having dotnet sdk 3.1 installed and then run dotnet --version, it will report 2.2.300 and it's fantastically magic. Move to another directory dotnet --version and boom 3.1.100 🤷‍♀️
But most importantly the older projects build with the old SDK just as it did prior to installing dotnet sdk 3.1, I wish this information were more readily available.
