### ISSUE TITLE
Unable to detect build errors Using build definition

### ISSUE THREAD

**Issue by girishgalla** [microsoft/msbuild#4833]
I Have created a build definition for ASP.net core 2.2 application on .sln file,
i intensionally commited wrong code which i will get build error in visual studio 2017, but when build definition is run build task it is not showing any error and build is also passing ....please help me

![1](https://user-images.githubusercontent.com/44398188/67200466-7bd27900-f421-11e9-8ddc-39714fb9428f.png)

![2](https://user-images.githubusercontent.com/44398188/67200482-82f98700-f421-11e9-9cfd-8f802eada7b9.png)
![3](https://user-images.githubusercontent.com/44398188/67200485-84c34a80-f421-11e9-9255-c54dff16c8cb.png)
![4](https://user-images.githubusercontent.com/44398188/67200487-85f47780-f421-11e9-8122-e9dce482d9e1.png)
![5](https://user-images.githubusercontent.com/44398188/67200489-868d0e00-f421-11e9-894f-f7f50fd7cbf3.png)
![6](https://user-images.githubusercontent.com/44398188/67200495-8a209500-f421-11e9-8175-a094459a32c7.png)
![7](https://user-images.githubusercontent.com/44398188/67200499-8b51c200-f421-11e9-9517-c9c3a6baae41.png)

**Comment by livarcocc** [comment]
You should file an issue on Azure DevOps for this. This is not the right repo for this issue.
