### ISSUE TITLE
The SDK 'Microsoft.NET.Sdk' specified could not be found.

### ISSUE THREAD

**Issue by XmaXStalker** [microsoft/msbuild#4858]
Recently I started modding Terraria. As a beginner I watched some tutorials online but I came across a problem on Windows 10, Visual Studio 2019 (version 4.8.03761).
Wanever I try to open the .csproj file, This Error pops up.

![Error](https://user-images.githubusercontent.com/57114913/67717388-e6f5ef80-f9cd-11e9-9260-624096ca9d9a.png)

Then A UpgradeLog.htm file is added to the folder. When I open it It shows this info.

![Error2](https://user-images.githubusercontent.com/57114913/67717596-553ab200-f9ce-11e9-825f-682ec03b59ec.png)

I have no ideea what is causing this problem and I would like to get some answers about it.

**Comment by rainersigwald** [comment]
When you installed Visual Studio, what checkboxes did you select? This error might indicate that you did not select ".NET Core cross-platform development".

> Visual Studio 2019 (version 4.8.03761)

I think that's the version of the .NET Framework. Can you tell us the version of Visual Studio itself? In Help -> About it's here:

![image](https://user-images.githubusercontent.com/3347530/67781583-a762ee00-fa35-11e9-9e68-ae7b2d5c7fd8.png)

Did you create the project `TMMC3.csproj` or is it downloaded from somewhere?

**Comment by XmaXStalker** [comment]
Oh yeah my bad. That was the Microsoft .NET Framework version. My Visual Studio Version is 16.3.6, I think it's the latest one.

![Screenshot_1](https://user-images.githubusercontent.com/57114913/67787142-b9b24b80-fa78-11e9-84f0-191737814da9.png)

I did create the file in a way or another. The file was created inside Terraria with TModLoader (64 bit)

![Screenshot_2](https://user-images.githubusercontent.com/57114913/67787351-11e94d80-fa79-11e9-8b87-e99ebd11cdd9.png)

This is the directory of the file I'm trying to open.

![Screenshot_3](https://user-images.githubusercontent.com/57114913/67787731-bc617080-fa79-11e9-9995-58762f85e218.png)

**Comment by rainersigwald** [comment]
Can you share the `.csproj` file (or ideally the whole folder)?

**Comment by XmaXStalker** [comment]
Sure.
[TMMC3.zip](https://github.com/microsoft/msbuild/files/3784878/TMMC3.zip)

**Comment by rainersigwald** [comment]
That opened in my VS. Can you confirm that you have the .NET Core workload installed?

1. Run `Visual Studio Installer` (not Visual Studio itself).
2. Select `Modify` on your Visual Studio instance.
3. Verify that this box is checked
   
![image](https://user-images.githubusercontent.com/3347530/67792343-fe24f380-fa46-11e9-997a-12bd452746a2.png)

4. Verify that this box is checked

![image](https://user-images.githubusercontent.com/3347530/67792387-0ed56980-fa47-11e9-9512-831dc9902126.png)

**Comment by XmaXStalker** [comment]
Okay. Thanks. It works just fine now. Gotta start programming now:)

**Comment by ianxmrj** [comment]
I have that problem to can you tell me how exactly do i fix this

**Comment by TheSkyFather** [comment]
Hi my dear friends. I recorded a video about this problem. Solved

https://youtu.be/SagJ4sI45lk
