### ISSUE TITLE
Add back EventSource

### ISSUE THREAD

**Issue by Forgind** [microsoft/msbuild#4875]
As noted in #4873, the changes in #4837 and #4724 caused a regression bug (a hang when opening certain projects) and were thus removed. The goal here is to put them back into the code base without causing that bug.

**Comment by rainersigwald** [comment]
@davkean asked whether we should recycle an existing VS event category to avoid having to change all the infrastructure that currently captures events (RPS, VSFeedback, various scripts).

**Comment by Forgind** [comment]
What would our alternative be?

**Comment by Forgind** [comment]
In talking with @davkean, it sounds like we won't have to change other parts of the infrastructure as long as we change the "name" of MSBuildEventSource to Microsoft-VisualStudio-Common. Although we should make sure it still works with RPS after that, that should be a straightforward change.
