### ISSUE TITLE
Setup merge bot

### ISSUE THREAD

**Issue by BenVillalobos** [microsoft/msbuild#4889]
@nguerrera has info on this.

**Comment by rainersigwald** [comment]
Internal convo: https://teams.microsoft.com/l/message/19:2db9948434504972b9bc70d3b3ad71e2@thread.skype/1572377387850?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4ba7372f-2799-4677-89f0-7a1aaea3706c&parentMessageId=1572377387850&teamName=.NET%20Developer%20Experience&channelName=CLI&createdTime=1572377387850

PR to do this for some of the other repos: https://github.com/dotnet/versions/pull/521

**Comment by BenVillalobos** [comment]
Closed as of https://github.com/dotnet/versions/pull/557
