### ISSUE TITLE
Synchronize concurrent tasks

### ISSUE THREAD

**Issue by MarcoRossignoli** [microsoft/msbuild#4898]
Hi here Marco from coverlet https://github.com/tonerdo/coverlet

One of most requested feature is "Solution wide coverage".

To do that we need to sync/communicate with concurrent running task https://github.com/tonerdo/coverlet/tree/master/src/coverlet.msbuild.tasks

Is there a build-in mechanism?
If I run for instance `dotnet test /p:CollectCoverage=true MergeWith.sln` (https://github.com/tonerdo/coverlet/issues/598#issuecomment-551174529) I see overlapping task instances and concurrent tests.
We should sync `CoverageResultTask ` https://github.com/tonerdo/coverlet/blob/master/src/coverlet.msbuild.tasks/CoverageResultTask.cs#L73 and wait all tests and merge results.

Is there a way/pattern to do this?Or we need to implement custom sync/interprocess communication(we need a unique identifier to group task of same sln build)?

cc: @tonerdo

**Comment by rainersigwald** [comment]
There is no built-in mechanism for this. In addition, people rolling their own locks have a long, sad history of causing confusing, hard-to-debug build breaks and hangs. So please consider whether there's any way you can redesign to avoid the need for the synchronization.

**Comment by MarcoRossignoli** [comment]
> There is no built-in mechanism for this. In addition, people rolling their own locks have a long, sad history of causing confusing, hard-to-debug build breaks and hangs. So please consider whether there's any way you can redesign to avoid the need for the synchronization.

Eh...it's also my concern 😞 but users complain about the fact that msbuild works only with "project" and there are some tool/fields that need to be grouped to "solution" to be useful.
Users want only 1 coverage report file but we can run task only "project based" and also runs in parallel 

Thank's for quick response @rainersigwald if you've some link on docs or some project that tackled this problem let me know.
