### ISSUE TITLE
Feature Request: Diff two binlogs to show what is different

### ISSUE THREAD

**Issue by randyram-at-ms** [microsoft/msbuild#4901]
Often when I am trying to debug an msbuild issue, I have a known-good build for which I produce a binlog.  Then I apply my changes which results in errors and I'd like to take the binlog from that and "diff" it against the known-good binlog to find out why the error is happening.

**Comment by livarcocc** [comment]
I wonder if this should be filled on the binlogviewer repo instead.

**Comment by KirillOsenkov** [comment]
There's already one ;P

https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/163

**Comment by rainersigwald** [comment]
Since there's a wide range of interpretation about how to display this information, and it's not directly related to producing the log or the build, I think pushing it out of core MSBuild into the viewer or another utility is the best path forward.
