### ISSUE TITLE
Duplicate items error if using custom task with file globbing and metadata and culture specific resource file

### ISSUE THREAD

**Issue by Dresel** [microsoft/msbuild#4912]
When using the following combination

- Custom Task (before PrepareForBuild) with globbing and metadata to include embedded resources
- Additional culture specific resource files (eg `Resource.de.resx`)

the build fails with an duplicate items error.

The build works though if

- the file globbing is specified without the custom task or
- if the culture specific resource file (`Resource.de.resx`) is removed or
- if no metadata is used (eg `LogicalFileName="a"` instead of `LogicalFileName="%(FileName)%(Extension)"`)

dotnet build and Visual Studio are producing the same output.

Don't know if this is a known limitation or just a bug?

### Steps to reproduce

```
git clone https://github.com/Dresel/FileGlobbingTargetResX.git
dotnet build
```

### Expected  behavior

Build succeeds

### Actual behavior

Build fails
### Environment data

`msbuild /version` output: Build Engine version 16.3.0+0f4c62fea for .NET Core

OS info: Windows 10

**Comment by rainersigwald** [comment]
I think you've hit #1053. I was able to work around it in your project like this:

```diff
diff --git a/FileGlobbingTargetResX/FileGlobbingTargetResX.csproj b/FileGlobbingTargetResX/FileGlobbingTargetResX.csproj
index b8da198..019da32 100644
--- a/FileGlobbingTargetResX/FileGlobbingTargetResX.csproj
+++ b/FileGlobbingTargetResX/FileGlobbingTargetResX.csproj
@@ -6,7 +6,10 @@
 
   <Target Name="MyTask" BeforeTargets="PrepareForBuild">
     <ItemGroup>
-      <EmbeddedResource Include="..\assets\*.*" LogicalFileName="%(FileName)%(Extension)" />
+      <EmbeddedResource Include="..\assets\*.*" />
+      <!-- Work around https://github.com/microsoft/msbuild/issues/1053:
+           set this after item creation. -->
+      <EmbeddedResource LogicalFileName="%(FileName)%(Extension)" />
     </ItemGroup>
   </Target>
 
```

**Comment by Dresel** [comment]
Of course it's `LogicalName` but the behaviour is the same anyway.

Thanks for your time and letting me know the workaround, this works now as expected :thumbsup:

**Comment by rainersigwald** [comment]
Duplicate of #1053

**Comment by Dresel** [comment]
The workaround
   
    <EmbeddedResource LogicalName="%(FileName)%(Extension)" />

also affects all other EmbeddedResource items. Is there an easy way to only modify those added by the include statement (`Include="..\assets\*.*"`) above?

**Comment by rainersigwald** [comment]
Something like

```xml
      <EmbeddedResource Include="..\assets\*.*" UpdateLogicalName="true" />
      <!-- Work around https://github.com/microsoft/msbuild/issues/1053:
           set this after item creation. -->
      <EmbeddedResource LogicalName="%(FileName)%(Extension)"
        Condition="'%(UpdateLogicalName)' == 'true'" />

```

should work for that (but I haven't confirmed it explicitly).

**Comment by Dresel** [comment]
I got a compiler error to use `EmbeddedResource.UpdateLogicalName` but except for that it works now as expected (again) :smile: - thanks again.

Final csproj definition:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <Target Name="MyTask" BeforeTargets="PrepareForBuild">
    <ItemGroup>
      <EmbeddedResource Include="..\assets\*.*" UpdateLogicalName="true" />
      <!-- Work around https://github.com/microsoft/msbuild/issues/1053: set this after item creation. -->
      <EmbeddedResource LogicalName="%(FileName)%(Extension)" Condition="'%(EmbeddedResource.UpdateLogicalName)' == 'true'" />
    </ItemGroup>
  </Target>

</Project>
```
