### ISSUE TITLE
Tasks need to be able to access current project's global properties

### ISSUE THREAD

**Issue by jeffkl** [microsoft/msbuild#4925]
From a task, we'd like to access the global properties of the current project.  This is so you can do evaluations outside of MSBuild but part of a task.  The global properties passed from the command-line are not made available to any running component like tasks at the moment.

I spoke with @rainersigwald and we thought of two possible implementations:

## Add a new `GetGlobalProperties` task

A new task could be made to fetch global properties into an item group.  This item group could then be passed to the task that needs the values:

```xml
<Project>
  <Target Name="Example">
    <!--
      Call a new task that gets the global properties  stores them in a return ItemGroup
    -->
    <GetProjectGlobalProperties>
      <Output TaskParameter="GlobalProperties" ItemName="CurrentProjectGlobalProperties" />
    </GetProjectGlobalProperties>

   <!-- Call my task that takes the item containing global properties -->
    <MyTask GlobalProperties="@(CurrentProjectGlobalProperties)" />
  </Target>
</Project>
```
The nice thing about this implementation is that logs would clearly show that global properties were fetched and passed along.

One drawback of this approach is that escaping could be difficult since things need to made available as strings for items.

## Add `IBuildEngine6`
We could also implement a new interface to extend `IBuildEngine` which would have a method like:

```C#
public interface IBuildEngine6 : IBuildEngine5
{
    IReadOnlyDictionary<string, string> GetGlobalProperties();
}
```

This method would return a copy of the global properties and the task could call it to get them.

The drawback of this implementation is that its not as clear in any logs that global properties were fetched and used.

**Comment by jeffkl** [comment]
@rainersigwald I'm leaning towards `IBuildEngine6` after giving this more thought just so I don't have to deal with escaping.  I'd like to code this up today or tomorrow, please let me know what you think.

**Comment by rainersigwald** [comment]
I still think the other way is cleaner. Wouldn't the escaping be automatically handled at item creation time/item input decoding time?
