### ISSUE TITLE
[Question]Does msbuild reuse process node?

### ISSUE THREAD

**Issue by MarcoRossignoli** [microsoft/msbuild#4954]
Simple question to be sure...does msbuild reuse process host during build right(for instance on a solution with a lot of projects)?
I mean if I've got a task with static data it's possible that different builds reuse same process(app domain) and my statics are previous value?
related issue https://github.com/Microsoft/msbuild/issues/2916
I need only an "I confirm"

**Comment by rainersigwald** [comment]
> I need only an "I confirm"

If only it were that simple! :)

MSBuild always reuses processes within a build, so your example of "a solution with a lot of projects" will always have a finite set of processes. The processes will last _at least_ until the end of the build in all cases.

If node reuse is enabled (it is enabled by default), worker nodes will outlive the build that created them, and may be reused for subsequent builds. There is no guarantee that the subsequent build is of the same or similar projects, and there is no guarantee that a subsequent build of the same projects will assign a particular project to the same node it used before.

It is also possible to define a [task that gets its own AppDomain](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.utilities.appdomainisolatedtask), which complicates the statics situation.

**Comment by MarcoRossignoli** [comment]
> There is no guarantee that the subsequent build is of the same or similar projects

But same solution?

**Comment by rainersigwald** [comment]
Nodes are reusable by the same user for their lifetime.

No guarantee that it's the same solution; a user could have two repos open in different command lines and build one, then the other.

**Comment by MarcoRossignoli** [comment]
Ok thanks a lot for the clarification!
