### ISSUE TITLE
RAR is logging all inputs twice under /bl

### ISSUE THREAD

**Issue by KirillOsenkov** [microsoft/msbuild#4956]
When `/bl` is used (== MSBUILDLOGTASKINPUTS is set) RAR logs its full set of inputs twice (once by the general mechanism to log task inputs and once by its own custom detailed input logger).

![image](https://user-images.githubusercontent.com/679326/70252040-b2343f80-17a6-11ea-996f-0307b1d8ff2c.png)

We should detect this situation and only log all inputs once (decide whether to just keep the automatic logging or turn off automatic logging in favor of better manual logging). It's important to ensure that whatever we keep it should be a full superset of whatever we delete.

I expect this this should significantly help with both build performance and binlog sizes. RAR inputs are by far the biggest contributor to binlog size.

**Comment by rainersigwald** [comment]
The last time I looked at this, neither was a superset of the other, but I would tend to lean toward dropping the custom in-RAR logging when `MSBUILDLOGTASKINPUTS` will allow us to reconstruct the actual inputs to the task. That feels cleaner than special-casing the general mechanism to know about RAR.

> RAR inputs are by far the biggest contributor to binlog size.

I wish. C++ projects are much, much worse.

**Comment by KirillOsenkov** [comment]
Luckily I mostly look at binlogs without any C++ in them :)

We could come up with a hybrid and drop the custom-in-RAR logging where it is redundant, but keep the useful pieces.
