### ISSUE TITLE
Folder is not copied when initially empty

### ISSUE THREAD

**Issue by mdmoura** [microsoft/msbuild#4979]
On an ASP.NET Core 3.1 csproj file I have an `approot` folder with client code (javascript).

Using webpack the client code is built and saved on the folder `approot\dist`.

Then I need to copy `approot\dist` content to `webroot` folder which is initially empty.

So I added the following to my project `csproj` file:

```xml
  <ItemGroup> 
    <Content Include="webroot\**\*.*"> 
      <CopyToOutputDirectory>Always</CopyToOutputDirectory> 
    </Content> 
  </ItemGroup>

  <Target Name="OnBuild" BeforeTargets="BeforeBuild;BeforePublish">
    <Exec WorkingDirectory="approot" Command="npm install" />
    <Exec WorkingDirectory="approot" Command="npm run build --prod" />
    <ItemGroup>
      <Folder Include="approot\dist\**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(Folder)" DestinationFolder="webroot\%(RecursiveDir)"></Copy>
  </Target>
```

**Problem**

The `webroot` folder is **not copied** to the Output folder. I built it a second time and now it is.

So I tried the following:

```xml
  <Target Name="OnBuild" BeforeTargets="BeforeBuild;BeforePublish">
    <Exec WorkingDirectory="approot" Command="npm install" />
    <Exec WorkingDirectory="approot" Command="npm run build --prod" />
    <ItemGroup>
      <Folder Include="approot\dist\**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(Folder)" DestinationFolder="webroot\%(RecursiveDir)"></Copy>
    <ItemGroup> 
      <Content Include="webroot\**\*.*"> 
        <CopyToOutputDirectory>Always</CopyToOutputDirectory> 
      </Content> 
    </ItemGroup>
  </Target>
```

And now it works ... Is this expected?

**OS info**

.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.1.100 [/usr/local/share/dotnet/sdk]

**Comment by Forgind** [comment]
Yes, that is expected behavior. The ItemGroup is outside of a target, so its wildcards are expanded at project evaluation time—before running any targets—so it moves the files you want into webroot, then copies what had _originally_ been the list of contents of webroot (nothing) into the output directory, whereas you want it to move files into webroot then copy the current contents to the output directory.

In code, it might look something like:
```
var files = ExpandGlob("webroot\**\*.*")
// Evaluation completes
// OnBuild:
Copy(approot, webroot)
// something, later
Copy(files, output)
```
Your second snippet is a good way to do it.
