### ISSUE TITLE
AppxPackagePayload in vcxproj not working when building for Store

### ISSUE THREAD

**Issue by eklipse2k8** [microsoft/msbuild#4989]
### Steps to reproduce

Adding AppxPackagePayload files will build locally, but won't make their way into the final .appx package.

Project file
```xml
      <AppxPackagePayload Include="$(ProjectDir)..\DatabaseGen\CorePackage.dat">
        <TargetPath>CorePackage.dat</TargetPath>
      </AppxPackagePayload>
```

**Comment by livarcocc** [comment]
Please, file a VS Feedback item for this through Visual Studio and your issue will be triaged to the appropriate team.

The logic for this does not leave on this repo. Filling the VS feedback item will make the team responsible for this aware of your issue quicker.

**Comment by sonsaw1** [comment]
I am running into the same issue.
Were you able to find out the cause and the solution.
