### ISSUE TITLE
Not able to open NuGet package manager from the tools dropdown.

### ISSUE THREAD

**Issue by foxcrot** [microsoft/msbuild#4992]
### Steps to reproduce

In the tools dropdown > NuGet Package manager > Manage Packages for solution is throwing Object reference not set an instance of an object.
 I have included the screenshots of the errors.
  
![Full Error](https://user-images.githubusercontent.com/30600786/70974059-ef64cf80-20cc-11ea-9507-48cb1697a0c7.png)
![Null obj](https://user-images.githubusercontent.com/30600786/70974060-effd6600-20cc-11ea-9cde-86accce2cfd7.png)

**Comment by livarcocc** [comment]
@foxcrot thanks for filling the issue, however, I recommend filling a VS Feedback item through VS itself.

This is not the right repo for this repo.
