### ISSUE TITLE
Incremental build is less reliable on .NET Core MSBuild

### ISSUE THREAD

**Issue by mellinoe** [Microsoft/msbuild#500]
See https://github.com/dotnet/corefx/issues/6220. I have noticed that incremental build is not working in our x-plat corefx build for most libraries. The tricky part here is that the targets we use are slightly different in our x-plat builds (because we restore them from NuGet packages rather than use the targets installed with Windows MSBuild), which may explain some differences. I'm filing this here because it seems the biggest difference in our builds is the use of regular MSBuild vs. CoreCLR MSbuild rather than the individual targets files.

The easiest way to repro this is to just run the CoreCLR MSBuild on any of our library projects in corefx twice. For example, `src/System.Private.Uri/src/System.Private.Uri.csproj`. The second run of the build will re-run some of the more expensive targets when they should be up to date.

**Comment by jeffkl** [comment]
Is this still an issue?  A lot has changed in this space.

**Comment by Sarabeth-Jaffe-Microsoft** [comment]
Hi @mellinoe-- are there still discrepancies in your incremental builds? We made a lot of improvements in this area for [VS 2017 RC.](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes). 

See #1327.

Please re-open issue if so.
