### ISSUE TITLE
Question about suppress contentfiles flow

### ISSUE THREAD

**Issue by sungam3r** [microsoft/msbuild#5012]
Hi. My problem is described in detail in [Nuget repo](https://github.com/NuGet/Home/issues/8867). I do not know where it is better to address my question. I will be very grateful for the advice.

**Comment by nkolev92** [comment]
Hey @sungam3r 
I'm on the NuGet team, this an issue best handled in the NuGet repo. 

I'd suggest closing this issue. 

I'm looking into the original issue filled and will respond on it soon.
