### ISSUE TITLE
Why is NativeMethodsShared.FixFrameworkPath required?

### ISSUE THREAD

**Issue by radical** [Microsoft/msbuild#503]
This method essentially converts paths of the form

`/framework/base/path/vA.B/foo` to `/framework/base/path/xbuild/vA.B/bin/foo` 

.. if A.B > 4.0 .

I am not sure why this is required or when it might be hit. The `xbuild/*/bin` path
contains the Microsoft.Build* assemblies for versions 12.0 and 14.0..
But how would we get a resolved path to these?

Also, this gets applied to results of property/item expansions via `MaybeAdjustFilePath`,
which means that any Property containing such a path gets adjusted. And this can get
applied multiple times, so ..

` <Foo>/Users/ankit/dev/misc/lib/mono/v8.0/asd</Foo>`

.. becomes ..

`/Users/ankit/dev/misc/lib/mono/xbuild/8.0/bin/bin/asd` 

So, my question is why is this useful?

**Comment by AndyGerlicher** [comment]
@ValMenn does this look familiar?

We're not really sure. Probably seemed like a good idea at the time. I don't know of any reason for or against keeping it.

**Comment by radical** [comment]
Thanks!
