### ISSUE TITLE
C++/CLI dot net core 3.1 Utility style projects

### ISSUE THREAD

**Issue by davidhunter22** [microsoft/msbuild#5040]
I'm not sure if this is the correct project to post this issue but it seemed more likely to be msbuild related than dotnet coreclr.
Anyway I recently ported an existing C++/CLI vcxproj  based solution to build using DotNet Core 3.1 and it mostly worked which is awesome.
However a couple of projects failed with the build error

> C++/CLI projects targeting .NET Core must be dynamic libraries.
These project turned out to be
```
  <PropertyGroup>
    <ConfigurationType>Utility</ConfigurationType>
  </PropertyGroup>
```
So they were really just bags of files and not building anything. I can understand the C++/CLI support not building all project types but can it allow "utility" style projects? Given that they don't actually build anything I was a bit surprised they weren't allowed.

**Comment by rainersigwald** [comment]
@wli3 can you take a look at this?

**Comment by wli3** [comment]
@davidhunter22 sorry we don't support it at this time. cc @olgaark
