### ISSUE TITLE
Validate RuntimeIdentifiers during build

### ISSUE THREAD

**Issue by jochenz** [microsoft/msbuild#5044]
NuGet uses RuntimeIdentifiers to prohibit restoring packages on unsupported architectures. For example, you can't restore a `linux` library on a Windows 10 machine.

However, msbuild doesn't seem to validate those runtime requirements. I can perfectly create a Linux-only library:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RuntimeIdentifiers>linux</RuntimeIdentifiers>
  </PropertyGroup>
</Project>
```

And reference that in a Windows-only application:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RuntimeIdentifier>win7-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyLinuxLib\MyLinuxLib.csproj" />
  </ItemGroup>

</Project>
```

That doesn't seem to make sense to me and it looks like msbuild should be capable of detecting these inconsistencies.

**Comment by rainersigwald** [comment]
This issue was moved to dotnet/sdk#4164
