### ISSUE TITLE
Microsoft Build Tools 2015 on Microsoft Download Center should be updated

### ISSUE THREAD

**Issue by lextm** [Microsoft/msbuild#507]
https://stackoverflow.com/questions/35722454/different-versions-of-msbuild-when-installing-directly-or-through-visual-studio

As discussed above, if people want to set up their build servers to match Visual Studio 2015 Update 1 on developer machines, there is currently no separate download package for MSBuild 14.0.24720.0.

The [current download](https://www.microsoft.com/en-us/download/details.aspx?id=48159) is still 14.0.23107.10.

**Comment by rainersigwald** [comment]
We are tracking this as #480. We've already made the required internal changes, and we expect to publish a standalone Build Tools package with Visual Studio 2015 Update 2 RC (and eventually the final Update 2 when it's ready).
