### ISSUE TITLE
Global msbuild.rsp with /nr:false can break /m builds

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#509]
This was discovered internally by @AArnott. Thanks for the report and for giving us access to that repro machine.

MSBuild ships with an empty `msbuild.rsp` next to `msbuild.exe` in Program Files. If edited, any line in this response file is effectively prepended to the command line of a normal, undecorated `msbuild` invocation. Presumably this is to allow easily setting defaults for MSBuild across the entire machine.

Since #346, if this response file contains `/nr:false` to disable node reuse, multiproc builds will a) actually use only one process while b) continually spawning new instances of `msbuild.exe /nodeMode:1` until that one process completes.

This is because cc051cb9d4fb8507144aabdd7bfbc44669c862d2 changed how the child/client/worker node handled the `/nodeReuse` command line switch. Before, it was ignored and the child process would always live until it was sent a kill signal or it hit its timeout. After, it uses the value of the switch (after response-file inclusion, and defaulting to true) as part of its handshake computation.

In this situation, the main MSBuild spawned a new child process with no `/nodeReuse` flag, which in the absence of a response file is equivalent to `/nodeReuse:true`. Since there *was* a response file, the child actually started with `/nodeReuse:false`, computed its handshake value using that, and rejected the connection attempt that wanted `/nodeReuse:true`. For every attempted child process, in a loop, until the build ended.

**Comment by rainersigwald** [comment]
Likely fix: add an else clause to 137c0139090f012de10c9785eb6d3084865bfa14 explicitly passing *either* node-reuse mode.

**Comment by rainersigwald** [comment]
Workaround: remove any `/nodeReuse` line from `C:\Program Files (x86)\MSBuild\14.0\Bin\msbuild.rsp`.

**Comment by rainersigwald** [comment]
Another thought: should worker nodes use response files at all? Maybe they should be spawned with `/noautoresponse`.

**Comment by AArnott** [comment]
> Another thought: should worker nodes use response files at all? Maybe they should be spawned with /noautoresponse.

That sounds like the right approach to me.
And yes, thanks for the workaround.

**Comment by AArnott** [comment]
Thanks!
