### ISSUE TITLE
Cannot exclude assemblies of referenced project from build output

### ISSUE THREAD

**Issue by tebjan** [microsoft/msbuild#5093]
### Steps to reproduce

Referenced projects in the solution always get copied to the build output folder, regardless of the `Private` flag setting.

Project file
```xml
<Project>
  <ItemGroup>
    <ProjectReference Include="..\..\..\public\ShouldNotBeInBuildOutput.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
</Project>
```

### Expected behavior
Assembly of ShouldNotBeInBuildOutput.csproj shouldn't be in the build output folder. Neither any reference of it.

### Actual behavior
Assembly and all references are copied to output folder.

### Environment data
`msbuild /version` output: 16.4.0.56107

OS info: Win 10 Pro
Version	10.0.18363 Build 18363

**Comment by tebjan** [comment]
While trying to create a small sample project I noticed that it works for simple cases. But in our solution with 40+ projects, the flag doesn't work anymore. Any hints what I could look for in order to debug it?

**Comment by lionelberton** [comment]
We have a similar problem, on a SDK format csproj, with private=false, where the reference is not copied (good) but all its dependencies are?!, and we don't understand why.

**Comment by dsplaisted** [comment]
I highly recommend creating binary logs and using MSBuild Structured Log Viewer to debug build issues: http://msbuildlog.com/

**Comment by rainersigwald** [comment]
This sounds like it may be related to changes made in #4865. If you [use a `Directory.Build.props`](https://docs.microsoft.com/visualstudio/msbuild/customize-your-build?view=vs-2019#directorybuildprops-and-directorybuildtargets) to set the property `MSBuildCopyContentTransitively=false` for all projects in your solution, do you still get the transitive copying?
