### ISSUE TITLE
msbuild /preprocess or /pp does not work when specifying a project on the command line

### ISSUE THREAD

**Issue by asklar** [microsoft/msbuild#5094]
VS2019 build: 16.4.0+e901037fe

msbuild myproject.vcxproj /pp:out.xml

This builds the project and doesn't actually produce out.xml 

This means if the directory contains more than one project or solution, you can't generate a preprocessed output of it.

**Comment by rainersigwald** [comment]
@asklar I don't reproduce this on my machine. Do you have a `Directory.Build.rsp` file or a wrapper script that invokes MSBuild that is adding other command-line arguments?

**Comment by boczar** [comment]
2.5 years later - I'm having problems with this too. No matter where or how I use either /preprocess:out.txt or -pp:out.txt it just builds the solution for me. I'm manually running msbuild from the developer VS2022 prompt:

Microsoft (R) Build Engine version 17.2.1+52cd2da31 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

17.2.1.25201
