### ISSUE TITLE
Integrate custom .targets file in a new csproj files with .Net Core 3.0

### ISSUE THREAD

**Issue by QuantumDeveloper** [microsoft/msbuild#5097]
Hi. 

I faced with an issue that I cannot find info about how to integrate my `.targets` file from .Net Framework to a new .Net Core project file.

Can someone point me in the right direction please?

**Update**
Currently I am struggling with my `.targets` file trying to make it work, but in one case it just dont run at all, in other - there is compilation error saying:
`task could not be loaded from the assembly...`
`Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.`

Which is I think related to some inconsistency between .Net Core and .Net standard (which uses MSBuild.Uitilities nuget package

**Comment by QuantumDeveloper** [comment]
Ok, I actually found out what is going on. MSBuild for some reason in trying to start wrong environment (seems .Net framework instead of .Net Core) In Rider there is an option to select MSBuild version and it working quite well, but in such configuration it fails to run under VS 2019.
Is there any way to make it work or I need to switch using Exec task instead?

I cannot use `netstandard2.0` in my projects, so this variant is inappropriate for me.

**Comment by rainersigwald** [comment]
Can you provide some more details, please? Does your `.targets` file use a custom task? If so, how is that built?

**Comment by QuantumDeveloper** [comment]
@rainersigwald I already found out that this happenes because MSBUILD cold not run .NetCore 3.0 or higher tasks, but only netstandrad2.0 or lower, which war very strange and unexpected to me.
For ex., Rider is building and running such task without issues, because it uses MSBUILD for .Net core instead of some custom, which Visual Studio is using.

And my question is:
Do you to ship fix for this anytime soon? Maybe at least for .Net 5 release?

**Comment by rainersigwald** [comment]
That's tracked by #4834, which isn't currently scheduled.

Closing this since you figured out the issue and we have tracking for the underlying problem.
