### ISSUE TITLE
[loc][Query][msbuild] Localizability of 0; "CacheMissesNotAllowedInIsolatedGraphBuilds"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/msbuild#5102]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Sources:
MSB4252: Project "{0}" with global properties\r\n ({1})\r\n is building project "{2}" with global properties\r\n ({3})\r\n with the ({4}) target(s) but the build result for the built project is not in the engine cache. In isolated builds this could mean one of the following:\r\n - the reference was called with a target which is not specified in the ProjectReferenceTargets item in project "{0}"\r\n - the reference was called with global properties that do not match the static graph inferred nodes\r\n - the reference was not explicitly specified as a ProjectReference item in project "{0}"\r\n 

File Name:
Build\Resources\xlf\Strings.xlf

==========================================
Query:
Would you please let us know what will replace the placeholder {4}? Will it be a number of a list of target(s)?

**Comment by rainersigwald** [comment]
It will be a list of targets like `Build;CustomizedTarget;SomethingElse`, right @cdmihai?

**Comment by cdmihai** [comment]
That's correct, it's a list of semicolon delimited target names.

**Comment by PDostalek** [comment]
thanks for replies
