### ISSUE TITLE
How to change code from one project for dependency project in C#?

### ISSUE THREAD

**Issue by soroshsabz** [microsoft/msbuild#5107]
ITNOA

I have a question in [stackoverflow](https://stackoverflow.com/q/60061866/1539100) but I think this place can make better for get better answer to my question.

I want to learn how should I change code behavior and segment from one project for one of dependency project in C#

I think my question is ambiguous ,so I try to explain my question in another language and ecosystem.

In C++ We can write some library like below

```
// My library header file
#ifndef MY_LIBRARY_H_
#define MY_LIBRARY_H_

#ifdef ML_HOOSHANG
constexpr bool TEST = true;
#else
constexpr bool TEST = false;
#endif

#endif
```

In this scenario if I have another project that wants to use top library, we can change behavior of top library like below

```
// Main.cpp this is another project

#include <iostream>

#define ML_HOOSHANG 1
#include <MyLibrary.h>

int main()
{
    cout << ::TEST == true ? "Hoooray" : "Nooo" << endl;
}

```

And we see this result

```
Hoooray
```

And if I want to see `Nooo` we easily can ‍‍`#undef ML_HOOSHANG` in user library (the library make reference to `MyLibrary`.

Another mechanism in C++ for doing something between library and very popular mechanism in C++ community that define some constant in build stage ,for example in [CMake](https://stackoverflow.com/questions/9017573/define-preprocessor-macro-through-cmake) with `add_compile_definitions` , and it is very useful approach when we want to change some basic platform or environmental dependent behavior in dependency libraries of our project.

now I want some similar mechanism in C# and `msbuild` ecosystem to provide same functionality, for example I have many projects and libraries, that all of them reference to one specific our library with nuget mechanism. and I want different behavior of this library depend on each project and library. so my question is How do I do this?

If I want to show similar mechanism in C#, I can refer to [PCL mechanism](https://stackoverflow.com/questions/5238955/what-is-a-portable-class-library) in solution to multi target problem. or [netstandard library](http://gigi.nullneuron.net/gigilabs/multi-targeting-net-standard-class-libraries/) mechanism for multi targeting different behavior approach.

My problem is very similar to two top examples, except it is not multi target and those examples solving multi target problem, and I want to do something similar to what they did for solving multi target ,but different. I want to do something like what they did for solving multi target problem , for solving a problem similar to [`<DefineConstants>`](https://docs.microsoft.com/en-us/visualstudio/msbuild/when-element-msbuild?view=vs-2019#example) in [msbuild](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-reference?view=vs-2019) one project from another project that depend on it.

How do I do this?

How to create nuget package that have multiple output depend on multi define constants value? and how to [package reference](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files) in `csproj` to another `nuget` depend on constatns?

Thanks a lot

**Comment by rainersigwald** [comment]
The output of a .NET process is a single build artifact that is consumed in binary form by other projects. It's more analogous to a .lib or .dll than it is to a header-based include. As a result, there's no way to change the behavior of a library from its consumer. You would have to change the build of the producer to have multiple outputs with different behaviors--but in general I'd recommend not doing this if you can avoid it, in favor of runtime behavior flags.
