### ISSUE TITLE
Document if CodeTaskFactory is deprecated

### ISSUE THREAD

**Issue by jeffkl** [microsoft/msbuild#5117]
From RoslynCodeTaskFactory created by [malkia](https://github.com/malkia): jeffkl/RoslynCodeTaskFactory#41  

Today, one of our teams experienced issues with CodeTaskFactory. Replacing it with RoslynCodeTaskFactory fixed the issue, but it was rather unexpected - no other code change was done, and the only other visible change was the Windows Update.

So I'm getting conflicting information whether CodeTaskFactory is deprecated, or not. Also not very straightforward answers.

We are not first-class users of it, but simply by reusing another .targets/.props file from the Qt Projec t (QtMsBuild) it actually used CodeTaskFactory and that's how it broke us.

Ref: https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-roslyncodetaskfactory?view=vs-2019

And here is the message that we had today:

```
6>------ Build started: Project: SomeProject, Configuration: Release x64 ------
6>...\sdk\qt\qtmsbuild\qt.targets(705,5): error MSB4175: The task factory "CodeTaskFactory" could not be loaded from the assembly "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Build.Tasks.Core.dll". A required privilege is not held by the client
```

According to some, this might've caused the change: "KB4534132 Cumulative Update for .NET Framework 3.5 and 4.8 for Windows 10 Version 1903"

**Comment by jeffkl** [comment]
I've moved this issue to MSBuild, since the `CodeTaskFactory` is owned by it and the `RoslynCodeTaskFactory` is now built it.

As far as I know, `CodeTaskFactory` is not deprecated entirely, only for .NET Core.  If your build only runs on Windows .NET Framework, then `CodeTaskFactory` will work just fine.  If your build needs to run on cross platform Linux, Mac, or Windows .NET Core, you have to use `RoslynCodeTaskFactory`.  In my opinion, this is documented well.

The error you're getting is:

> A required privilege is not held by the client

That seems like you're trying to do something in your task that requires running as elevated but your process is not running as Administrator.

**Comment by rainersigwald** [comment]
I think [the docs on inline tasks](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-inline-tasks?view=vs-2019) are fairly clear:

> Starting in .NET Framework version 4, you can create tasks inline in the project file. You do not have to create a separate assembly to host the task. This makes it easier to keep track of source code and easier to deploy the task. The source code is integrated into the script.
> 
> In MSBuild 15.8, the RoslynCodeTaskFactory was added which can create .NET Standard cross-platform inline tasks. If you need to use inline tasks on .NET Core, you must use the RoslynCodeTaskFactory.

Is there wording that would have "CodeTaskFactory is not deprecated but only works on MSBuild.exe on .NET Framework", @malkia?

**Comment by malkia** [comment]
I need to investigate more. I think I'm missing details on what went with that update. We are on .NET Framework (or I would thinks so, e.g. we call msbuild.exe, and this should be .NET Framework, not .NET Core). I'll try go get more info as the week goes by, and update. You can close this, and thanks for looking and explaining it!

**Comment by malkia** [comment]
@rainersigwald - re: deprecation - I think it was a post/message written about it, and I prematurely drew my conclusions (not checking with the docs in first place), but since we've experienced it, I thought it was so. Sorry!

**Comment by rainersigwald** [comment]
No problem, there are plenty of places where we're not clear and we'd rather know about them than not! I'm going to go ahead and close this, though.
