### ISSUE TITLE
Question about how tool package variables work when referenced by a project

### ISSUE THREAD

**Issue by eddie-jb** [microsoft/msbuild#5119]
### Question
If I have a package with a `tools` folder, lets call it `SomeTool.nupkg`, that gets referenced by a project called `Proj1.csproj` this will create a variable in `Proj1.csproj.nuget.g.props` called `PkgSomeTool`. 

My question is: Is it possible to also create a `SomeTool.props` and `SomeTool.targets` in `SomeTool.nupkg` that can reference the `PkgSomeTool` variable? Something like...

SomeTool.nuspec file
```xml
<?xml version="1.0"?>
<package >
  <metadata>
    ...
  </metadata>
  <files>
    <file src="bin/Release/netcoreapp3.0/**" target="tools" />
    <file src="SomeTool.props" target="build" />
    <file src="SomeTool.targets" target="build" />
  </files>
</package>
```
SomeTool.props file
```xml
<Project>
    <PropertyGroup>
        <MyTool>$(PkgSomeTool)/tools/SomeTool.dll</MyTool>
    </PropertyGroup>
</Project>
```
SomeTool.targets file
```xml
<Project>
    <Target Name="BeforeBuild">
        <Exec Command="dotnet $(MyTool)" />
    </Target>
</Project>
```
### Actual
The command that runs during build is `dotnet /tools/SomeTool.dll`. 
On the other hand, if the package only contains the `tools` folder, and I add 
```xml
<PropertyGroup>
  <MyTool>$(PkgSomeTool)/tools/SomeTool.dll</MyTool>
  <PreBuildEvent>$(MyTool)</PreBuildEvent>
</PropertyGroup>
```
to `Proj1.csproj`, the build works because `MyTool` has the full path.

Thanks for any help on this.

**Comment by rainersigwald** [comment]
The usual approach to this is to anchor paths in your NuGet package payload with `$(MSBuildThisFileDirectory)` or similar. You can combine that with `..` to get full paths to files in the package.

**Comment by eddie-jb** [comment]
...Well that was easy, thanks 👍
