### ISSUE TITLE
[Directory.Build.props] Using PackageReferences with Nuget packages from custom nuget feed

### ISSUE THREAD

**Issue by ceregador** [microsoft/msbuild#5128]
We use Directory.Build.props in several solutions to inject common PackageReference (StyleCop.Analyzers) to solution's projects to enable linting:

`<PackageReference Include="StyleCop.Analyzers" Version="1.1.118" PrivateAssets="all" />`

Every solution contains its own ruleset but the rules are the same.
So we decided to create one common ruleset and provide it with all necessary files via Nuget package.
This Nuget package is hosted by our company's Nuget server and it has StyleCop.Analyzers as dependency.

We also use other Nuget packages from this server so Visual Studio Nuget package sources contain the url.

But if I add PackageReference with this package to Directory.Build.props, Visual Studio (2019) will not restore this package.
`<PackageReference Include="NugetPackage.FromInternalFeed" Version="1.0.0" PrivateAssets="all" />`

I tried Restore Nuget Packages and Build/Rebuild commands from the ui.

It seems Nuget packages from custom feeds are ignored and not restored.

Does Directory.Build.props ignore Nuget packages from custom feeds?
Should I do some additional actions to enable this process?

**Comment by rainersigwald** [comment]
This issue was moved to NuGet/Home#9178
