### ISSUE TITLE
Error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.

### ISSUE THREAD

**Issue by LuckyDice6** [microsoft/msbuild#5134]
I get the following Error within my "Self-hosted Windows agents".
C:\agent\_work\1\s\Edr.Common.Validation\Edr.Common.Validation.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
After looking around the internet and trying to solve this problem i tried multiple things.
 - Installing different SDK's (https://dotnet.microsoft.com/download/visual-studio-sdks)
 - let my Yaml file install SDK
 - Creating variable path "MSBuildSDKsPath" (https://github.com/microsoft/msbuild/issues/2532)
 - Building with debug
 
Beside this i tried the following
 - Specify version msbuild within my ymal file. This moved the Error to the nuget restore and the build failed because i didn't had my packages.

Lastly i tried to build i my self thought Visual studio maybe VS can tell more. But with no problem Vs count build the solution on the server.
Thanks to this i know the correct sdk and smbuild is on the server my yml file + build agent are not finding them.

Yaml file
```
trigger:
- master

pool: 'Default'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  system.debug: 'true'

steps:
- task: NuGetToolInstaller@0

#- task: UseDotNet@2
#  inputs:
#    packageType: 'sdk'
#    version: '3.1.101'

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 3.1.101
    installationPath: $(Agent.ToolsDirectory)/dotnet
    includePreviewVersions: true

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    # msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
#    vsVersion: "15.0" #'latest' # Optional. Options: latest, 16.0, 15.0, 14.0, 12.0, 11.0

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '/1ad8be6e-855d-4d0e-b761-f414b845fddd'

**Comment by rainersigwald** [comment]
I'm not sure I understand the problem. Are you getting that error in the `VSBuild` task? What version of Visual Studio is installed on the agent? Does the agent have the .NET Core SDK installed, or is it only made available through `UseDotNet`?

Is it possible to share a diagnostic-level (or [binary](http://aka.ms/msbuild/binlog)) log of the failure?

**Comment by LuckyDice6** [comment]
@rainersigwald Thx for replaying. I will try do explain more.
I see that i never told that this problem happans in my DevOps Pipeline.
Within my log of msbuild i get the following Error:

##[error]#####.csproj(0,0): Error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
Project "#####.sln" (1) is building "#####.csproj" (2) on node 1 (default targets).
#####.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
Done Building Project "#####.csproj" (default targets) -- FAILED.

Project name is blured for security reasons

The version of msbuild i am using is : AGENT_VERSION = 2.153.1
on the server i sdk is installed an within the logfile i see the following variable : MSBUILDSDKSPATH = C:\\Program Files\\dotnet\\sdk\\2.1.511
on the server this folder exist.

because of security reasons i am not allowed of share my log files with you.

**Comment by LuckyDice6** [comment]
After looking around more a found the answer. I needed to change my build variabele to have use '64bits' platform in instead of 'any cpu'


`buildPlatform: '64x'`
