### ISSUE TITLE
Trigger master-branch optprof runs periodically

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/msbuild#5147]
Today, optprof collection from (internal-only link) https://dev.azure.com/devdiv/DevDiv/_release?definitionId=1370&view=mine&_a=releases runs for every `vs*` build but not for `master` builds. We should run it on some schedule--not every build. Maybe weekly?

**Comment by Forgind** [comment]
Now set to run every week on Fridays at 3pm PST.
