### ISSUE TITLE
Can a .sln file be create from a sln.metaproj file?

### ISSUE THREAD

**Issue by galloglach** [microsoft/msbuild#5154]
Is it possible to create a _.sln_ file from the contents of a _.sln.metaproj_ file?

**Comment by rainersigwald** [comment]
Not easily, no. There's some lossiness in the sln->metaproj conversion, because the metaproj is specialized to a specific configuration/platform when it's constructed (since it's intended to be transient).

Can you elaborate on your scenario? Maybe there's something else that could be done.

**Comment by galloglach** [comment]
I've an XML file that defines an application based on a collection of known projects. A tool then  reads it, creates a _.metaproj_ file  and passes it to _msbuild_ using _Microsoft.Build.Execution.BuildManager.Build(BuildParameters, BuildRequestData)_.

So I was wondering if it was possible to use the _.metaproj_ file to create a _.sln_ file.

One approach looked at is using the [_EnvDTE_ API](https://docs.microsoft.com/en-us/dotnet/api/envdte) to build a solution instead of building the _.metaproj_ file.

Also, looked at using _Microsoft.CodeAnalysis_ from _Roslyn_, but don't see support for saving solutions using _Workspace_ or _AdhocWorkspace_.

**Comment by rainersigwald** [comment]
@galloglach wait, is the `.metaproj` just a project then, not the in-memory metaproj that MSBuild itself creates when building a `.sln` file?

You might also be interested in https://github.com/microsoft/SlnGen (but note it's not an officially supported part of Visual Studio).

**Comment by galloglach** [comment]
@rainersigwald, _SlnGen_ was what I was looking for. Thanks for pointing me to it.
