### ISSUE TITLE
Setting MSBuildEmitSolution=0 will still cause metaproj files to be created

### ISSUE THREAD

**Issue by Inirit** [microsoft/msbuild#5166]
### Steps to reproduce
I've attached a solution+project that repros the bug pretty easily: [Repro.zip](https://github.com/microsoft/msbuild/files/4301234/Repro.zip)

Within the zip archive and adjacent to the .sln file are two batch scripts: 
#### build_without_var.bat
Unset variable MSBuildEmitSolution by setting it equal to nothing and then invoke "msbuild Repro.sln /restore" on the solution directory.

#### build_with_var_set_0.bat
Set variable MSBuildEmitSolution equal to 0 and then invoke "msbuild Repro.sln /restore" on the solution directory. 

_Note that both scripts use the default 2019 BuildTools path for msbuild, you may need to change the path to whatever it would be on your own machine._

First execute **build_without_var.bat** and then note the contents of the solution directory. Then execute **build_with_var_set_0.bat** and look again at the contents of the solution directory.

### Expected behavior
Both scripts should be functionally equivalent, no metaproj files are persisted to disk.

### Actual behavior
**build_with_var_set_0.bat** will cause metaproj files to be persisted to disk despite MSBuildEmitSolution having a value of 0

I'm not at all familiar with the source code and could be way off, but [this](https://github.com/microsoft/msbuild/blob/master/src/Shared/Traits.cs#L75) stood out to me as a potential source of the bug. The field is set to true if the value of MSBuildEmitSolution is any non-empty string rather than just the string "1" (as seems to be the case [here](https://github.com/microsoft/msbuild/blob/master/src/Shared/Traits.cs#L62)).

### Environment data
`msbuild /version` output:
```
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.4.0.56107
```
OS info:
```
Microsoft Windows 10 Enterprise
10.0.17763 Build 17763
```
~~If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):~~

**Comment by rainersigwald** [comment]
Unfortunately, our environment variable behavior for engine feature flags/escape hatches is inconsistent between "is environment variable defined", "is environment variable set to 1" and other behavior.

In addition, `MSBuildEmitSolution` is mostly unneeded now: the same information is captured in a binary log if you use one. Can you explore using that for your needs?

Team triage: We don't think this issue is high enough priority to spend time fixing.
