### ISSUE TITLE
Change default location of Exec files

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/msbuild#5168]
_From @danielbecroft on Monday, March 9, 2020 1:59:58 AM_

When an `<Exec />` command is used in the `csproj` file, a temporary file is generated in the users %LOCALAPPDATA% folder with the filename:

`%LOCALAPPDATA%\Temp\tmp1423b2926a6342b7b437fa1f148b3963.exec.cmd`

Unfortunately, in an enterprise environment where paths are whitelisted in order to be able to execute, this path is not ideal. It could be whitelisted to `tmp*.exec.cmd`, but that could be insecure.

Is it possible, or could it be possible, to change where this file is generated?

_Copied from original issue: dotnet/sdk#10802_

**Comment by rainersigwald** [comment]
@danielbecroft The location of this file is controlled by the environment variable `TEMP`. Can you set that to a custom value before invoking MSBuild?

**Comment by Pilchard123** [comment]
How would I go about doing this in a way that will work for VS and `dotnet build\test\publish`? On the advice of [this SO question](https://stackoverflow.com/questions/14267938/msbuild-how-to-set-environment-variables), I've tried

```
<Target Name="ToolRestore" BeforeTargets="PreBuildEvent">
  <Exec Command="dotnet tool restore" StandardOutputImportance="high" EnvironmentVariables="TEMP=C:\MSBuildTemp" />
</Target>
```

but it's not made any difference. What am I doing wrong?

**Comment by Pilchard123** [comment]
@rainersigwald , I tried changing the user-level `TEMP` environment variable, logging out and back in to make sure it had taken, then tried building again and and those files are still generated in `%LOCALAPPDATA%`. as described in the original issue.
