### ISSUE TITLE
Command line builds that conditionally remove project references still bring through NuGet dependencies for the removed project

### ISSUE THREAD

**Issue by MonkeyTennis** [microsoft/msbuild#5172]
### Steps to reproduce

Attached is a solution that reproduces the issue described below:

I have a .NET Core 3.1 console application, written using Visual Studio 2019, that has the following csproj contents:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AddDependency>true</AddDependency>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Condition="'$(AddDependency)' == 'true'" Include="..\DependencyProj\DependencyProj.csproj" />
  </ItemGroup>

</Project>
```
The referenced project, DependencyProj, contains the following:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Identity.Client" Version="4.9.0" />
  </ItemGroup>

</Project>
```
The following scenarios work as expected:

1) Visual Studio build where AddDependency = **true**, DependencyProj.dll and Microsoft.Identity.Client.dll are placed into the bin folder for PackageReferenceDependencyApp

2) Visual Studio build where AddDependency = **false**, DependencyProj.dll and Microsoft.Identity.Client.dll are **NOT** placed into the bin folder for PackageReferenceDependencyApp

3) Command line build where AddDependency = **true**, DependencyProj.dll and Microsoft.Identity.Client.dll are placed into the bin folder for PackageReferenceDependencyApp
```
msbuild .\PackageReferenceDependencyApp.csproj /t:clean;rebuild /p:AddDependency=true
```
The issue is when I run the following scenario:

4) Command line build where AddDependency = **false**
```
msbuild .\PackageReferenceDependencyApp.csproj /t:clean;rebuild /p:AddDependency=false
```
I would expect the outcome to be the same as 2). However, whilst DependencyProj.dll is absent as expected, Microsoft.Identity.Client.dll is present in the PackageReferenceDependencyApp bin folder.

It therefore seems that for command line builds, even though a project reference is screened out using a Condition, the NuGet packages for the referenced project are still brought through.

Perhaps I am doing something wrong but this does not feel right to me. Whilst the sample is contrived, this is a very real issue for my current project where there is a need to keep the contents of application bin folders to the bare minimum.

### Environment data
`msbuild /version` output:

16.4.0.56107

OS info:

Windows 10 Enterprise, OS Build 18363.719

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):

Visual Studio 2019 v16.4.6

**Comment by MonkeyTennis** [comment]
[PackageReferenceDependencyApp.zip](https://github.com/microsoft/msbuild/files/4318817/PackageReferenceDependencyApp.zip)

**Comment by Forgind** [comment]
Thanks for reporting this! The ProjectReference graph NuGet uses is built at restore time, not build time, so I was only able to reproduce this issue when I restored first with AddDependency=true. Conversely, if I restored with AddDependency=false, even building with AddDependency=true would not put Microsoft.Identity.Client.dll in the bin folder.

Would you mind running `dotnet build /restore /p:AddDependency=false` just before building with `/p:AddDependency=false` and letting me know how it goes? Thanks!

**Comment by rainersigwald** [comment]
Closing due to lack of response.

**Comment by MonkeyTennis** [comment]
Hi, I can confirm that adding a /restore command does fix the issue.

Thanks!
