### ISSUE TITLE
InitialTargets cannot reference a target from a PackageReference .targets file

### ISSUE THREAD

**Issue by alexis-** [microsoft/msbuild#5178]
### Steps to reproduce
- Use or migrate a project with/to PackageReference (as opposed to package.config)
- Reference a NuGet package that provides a .targets file which defines a `Target`
- Reference that target in your Project tag's InitialTargets e.g. `<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" InitialTargets="MyTarget">`, where `MyTarget` is the target defined in the package.

### Expected behavior
MSBuild should run the `MyTarget` target as part of initial targets

### Actual behavior
MSBuild cannot find the `MyTarget` target . This, however, works fine with package.config type projects.

`error MSB4057: The target "MyTarget" does not exist in the project.`

### Environment data
`msbuild /version` output: `16.4.0.56107`

OS info: `Windows 10 18362.657`

If applicable, version of the tool that invokes MSBuild: `Visual Studio 2019`

**Comment by rainersigwald** [comment]
The difference between `package.config` and `ProjectReference` here is that restore happens _inside MSBuild_ in ProjectReference-driven builds. That means that they must be valid projects both with and without restore--because running Restore means running targets in the project.

In your case, before restore there's no `MyTarget`, because it's defined in the package. But MSBuild expects `InitialTargets` to exist, so it errors.

Can you hook the new target to a point very early in the build instead of as an `InitialTargets`? For example `BeforeTargets="BeforeBuild"`? That also helps in some other circumstances where `InitialTargets` causes problems, for example Visual Studio design-time builds (where you may or may not be surprised to run the new target).

**Comment by alexis-** [comment]
Thanks for the detailed explanation, that is insightful. The issue here is that in my case, `MyTarget` defines variables in a `PropertyGroup` which are then used in the `Condition` attribute of some of my `<Project>`'s Target.

An example would be a `Target` which reads the .suo to extract the currently selected Solution configuration to make it available as a MSBuild variable (I think they are called macro ? Apologies if I got the terminology wrong).

As far as I could infer, the `Condition` clause is verified before running `BeforeTargets` or `DependsOnTargets`, which leaves no opportunity for the macro to be defined.

**Comment by rainersigwald** [comment]
> to make it available as a MSBuild variable (I think they are called macro ? Apologies if I got the terminology wrong).

There are two types of MSBuild variables, properties (single-valued, strings) and items (multi-valued, can be annotated with metadata). "Macro" is sometimes used in Visual Studio contexts but honestly I don't understand why.

> As far as I could infer, the `Condition` clause is verified before running `BeforeTargets` or `DependsOnTargets`, which leaves no opportunity for the macro to be defined.

That's true, but there are many targets defined in common.targets that unconditionally run pretty early in the build. Is `BeforeTargets="BeforeBuild"` too late for you? That should be before any of the load-bearing targets, which generally hook onto `CoreBuild`.

Extremely detailed docs on target ordering: https://docs.microsoft.com/visualstudio/msbuild/target-build-order?view=vs-2019#determine-the-target-build-order

**Comment by alexis-** [comment]
I had not completely understood the implications of your proposed solution. I have implemented it today, and my issue was indeed solved. Even better, my targets will now be run automatically after adding my NuGet package, without manually editing the `InitialTargets`.

Thank you for your assistance and for the educative process.

**Comment by anders9ustafsson** [comment]
@rainersigwald I have a similar issue. In my target in the NuGet package, I add an item group with an Android archive file, something like this:

> <ItemGroup>
  <LibraryProjectZip Include="my.aar">
    <Link>Jars\my.aar</Link>
  </LibraryProjectZip>
</ItemGroup>

However, it is not sufficient for my project to recognize this .aar file if I use `BeforeTargets="BeforeBuild"`, I need to locate it earlier in the MSBuild process. Pre-VS 16.8 I used `BeforeTargets="ResolveLibraryProjects"`, but with the latest VS update this does not seem to work anymore.

Any other target I could reference in my .targets file?
