### ISSUE TITLE
 [loc][Query][msbuild] Localizability of 0; "UndeclaredMSBuildTasksNotAllowedInIsolatedGraphBuilds"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/msbuild#5185]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Sources:
MSB4254: The MSBuild task is building project(s) "{0}" which are not specified in the ProjectReference item. In isolated builds this probably means that the references are not explicitly specified as a ProjectReference item in "{1}"

File Name:
Build\Resources\xlf\Strings.xlf

==========================================
Query:
Would you please check if some part of the instruction is dated? It says "task" is also not to be translated, but it seems translatable . Would you please check and advise?

  | Dev={StrBegin="MSB4254:"}DevComment=\r\n       LOCALIZATION: Do not localize the following words:  ProjectReference, MSBuild, task.;
-- | --

**Comment by rainersigwald** [comment]
@PDostalek In this context `task` specifically means "MSBuild task", not a general meaning of the word. But it seems that we generally translate `task` in that context, for instance

https://github.com/microsoft/msbuild/blob/3453beee039fb6f5ccc54ac783ebeced31fec472/src/Tasks/Resources/xlf/Strings.it.xlf#L1395-L1399

So I think you're right, and `task` is translatable here.

cc @cdmihai

**Comment by PDostalek** [comment]
Thank you for confirming
