### ISSUE TITLE
Small build tools

### ISSUE THREAD

**Issue by muv1** [microsoft/msbuild#5197]
From visiting here:

<https://stackoverflow.com/questions/59868753>

I came up with this command:

~~~
./vs_BuildTools \
--lang en-us \
--layout out \
--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64
~~~

which downloads `nmake.exe` and other tools. However the issue is that the size
is 648 MB. I am coming from the MinGW world where you can get the compiler and
libraries at 148 MB:

<https://github.com/mstorsjo/llvm-mingw/releases>

So I am hoping I can use another command for smaller result. I tried using this
command instead:

~~~
./vs_BuildTools \
--lang en-us \
--layout out \
--add Microsoft.VisualCpp.Tools.HostX64.TargetX64
~~~

but I get this result:

~~~
Error: The package 'Microsoft.VisualCpp.Tools.HostX64.TargetX64' is not
recognized.
~~~

even though its in the catalog:

~~~
"id": "Microsoft.VisualCpp.Tools.HostX64.TargetX64",
"version": "14.25.28611",
"type": "Vsix",
"chip": "x64",
~~~

then, looking back at the original command, I browsed the output, and among other
things I found this:

~~~
Microsoft.Net.4.7.2.FullRedist,version=4.7.3062.3/
dotNetFxLatest-x86-x64-AllOS-ENU.exe
111 MB
~~~

...I already have Microsoft .NET Framework installed, matter of fact I have even
the newer version 4.8. So I guess my questions are:

- why is my original command pulling in unneeded stuff?
- why cant I use my second command, when it seems to be a valid package?
- is a better way available to get a small output?

**Comment by rainersigwald** [comment]
This is great feedback for the Visual Studio installer team and the owners of the C++ workloads. Can you please file it at https://developercommunity.visualstudio.com/?

To take a quick look at your questions, I suspect that `Microsoft.VisualCpp.Tools.HostX64.TargetX64` is a subcomponent that can't be installed by itself, and Visual Studio requires .NET 4.7.2 or higher to function (for example to run MSBuild), so it runs as prerequisites. I don't think the C++ workload should include targeting packs for older .NET Versions but that's a question for the C++/installer folks.

**Comment by muv1** [comment]
@rainersigwald if another GitHub repo is better suited for this issue, I can post there.

But I will not pushed off to some Microsoft specific site. If thats the recommendation, then issue can just die here. Cheers!
