### ISSUE TITLE
GetAllGlobs should filter out items which are clearly not file path

### ISSUE THREAD

**Issue by lifengl** [microsoft/msbuild#5198]
Add this block to the project, and GetAllGlobs will include it as a potential glob item, although it contains invalid path characters. It becomes a problem, when later code doesn't expect this kind of items. If msbuild can filter them out, it will reduce the chance to run into this problem.

  <ItemGroup>
    <PropsFileHeader Include="&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;" />
  </ItemGroup>

**Comment by lifengl** [comment]
```xml
  <ItemGroup>
    <PropsFileHeader Include="&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;" />
  </ItemGroup>
```

**Comment by rainersigwald** [comment]
That's a legal filename pattern on Linux :(

But I don't think it would be unreasonable functionality-wise to amend this to exclude XML

https://github.com/microsoft/msbuild/blob/2d82e1a861d890fce68c8e2d42b569e5bbaf5687/src/Build/Utilities/EngineFileUtilities.cs#L97-L119

But it's also a historically perf-sensitive area (called for every item include in the build) so I'm not sure it's worth the effort.

From an internal email it sounded like you worked around this?

**Comment by marcpopMSFT** [comment]
@lifengl did you find a workaround for this?  We're determining if this is a priority.
