### ISSUE TITLE
MSBuild NodeExeLocation will fallback to .NET Framework path

### ISSUE THREAD

**Issue by AndyGerlicher** [Microsoft/msbuild#520]
The [FindMSBuildExe](https://github.com/Microsoft/msbuild/blob/a4e0dd5f4b31a6c9acb1bab25ac401c438c3dfac/src/XMakeBuildEngine/BackEnd/BuildManager/BuildParameters.cs#L975-L1060) method will look for MSBuild.exe in the current location with some extra logic to fallback on in case it doesn't find it.

However, when creating a worker node MSBuild will only use it if it's the same version. So the .NET Framework version will _never_ work. If we can't find the msbuild.exe by the previous methods we should fail and throw an exception if it's used.

**Comment by rainersigwald** [comment]
@AndyGerlicher was this fixed with 9780855?

**Comment by rainersigwald** [comment]
I'm going with "yes, it was".
