### ISSUE TITLE
GeneratePackageOnBuild generates invalid package for WinForms control library

### ISSUE THREAD

**Issue by lextm** [microsoft/msbuild#5208]
Not sure if this is an MSBuild or NuGet issue, so post it here first.

### Steps to reproduce

I was trying to build NuGet packages for an open source project. The goal is to compile a WinForms control (DockPanel Suite) for three platforms, .NET Core 3.1, .NET Framework 4.0 and 3.5.

So the main project can be found here,

https://github.com/dockpanelsuite/dockpanelsuite/blob/86dd840c3f3c12676c2fff5d107ea27ae76c3622/WinFormsUI/WinFormsUI.csproj

`GeneratePackageOnBuild` is set to `true` so NuGet packages can be generated during build.

### Expected behavior

The generated NuGet packages should be valid to consume.

### Actual behavior

The generated NuGet package references itself, so cannot be consumed at all.

You can refer to this CI build for more information,

https://github.com/dockpanelsuite/dockpanelsuite/runs/541996859?check_suite_focus=true

The invalid package (`DockPanelSuite.3.1.0-beta6.nupkg`) contains .nuspec fragment like,

    <dependencies>
      <group targetFramework=".NETFramework4.0">
        <dependency id="DockPanelSuite" version="3.1.0-beta6" exclude="Build,Analyzers" />
      </group>
      <group targetFramework=".NETCoreApp3.1">
        <dependency id="DockPanelSuite" version="3.1.0-beta6" exclude="Build,Analyzers" />
      </group>

### Environment data
MSBuild version can be seen from the CI log,

Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Framework

The CI image is windows-latest.

**Comment by rainersigwald** [comment]
This issue was moved to NuGet/Home#9377
