### ISSUE TITLE
PackageReferences of Runtime dependencies are not copied over

### ISSUE THREAD

**Issue by elangelo** [microsoft/msbuild#5219]
### Steps to reproduce

Either include a project sample, attach a zipped project, or provide IDE / CLI steps to create the project and repro the behaviour. Example of a project sample:

Attached zip file
[Solution.zip](https://github.com/microsoft/msbuild/files/4413317/Solution.zip)

Directory contents:
```
/
- Solution.sln
- Interfaces/
   - Interfaces.csproj
   - IStorage.cs
- Runtime
   - Runtime.csproj
   - Program.cs
- RuntimeDependency
   - RuntimeDependency.csproj
   - AzureStorage.cs
```

Command line
```
msbuild Solution.sln
```
### Expected behavior
As RunTimeDependency.csproj has a depedency on Microsoft.Azure.Storage.DataMovement I would expect that library to be copied over in the Runtime's bin directory

### Actual behavior
Only the RunTimeDependency.dll is copied over. It's depedencies are ignored.

### Environment data
`msbuild /version` output:
```
msbuild /version
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.4.0.56107
```
OS info:
Windows 10, Version 1909 (OS Build 18363.752)

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):
Same results with Visual Studio 2019 and dotnet build  (dotnet version: 3.1.101)

**Comment by rainersigwald** [comment]
This issue was moved to NuGet/Home#9376
