### ISSUE TITLE
Visual Studio reuses MSBuild process although MSBuild node reuse is disabled

### ISSUE THREAD

**Issue by BenVillalobos** [microsoft/msbuild#5221]
MSBuild Node reuse is disabled via Environment variable (MSBUILDDISABLENODEREUSE=1), but Visual Studio starts the MSBuild child process with /nodeReuse:true.

As we are developing an MSBuild task that is compiled and used in the same project, we are getting file locking issues, because of the kept alive msbuild processes.

-----

Issue created from feedback ticket: [AB#1055938](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1055938)

**Comment by BenVillalobos** [comment]
Responded to the thread with a workaround that I'll post here in case someone runs into this issue.

https://github.com/microsoft/msbuild/pull/5144. Basically you need to set `TaskFactory="TaskHostFactory"` as metadata on the task you're using.

Or see the feedback ticket [here](https://developercommunity.visualstudio.com/content/problem/893220/visual-studio-reuses-msbuild-process-although-msbu.html)

**Comment by rainersigwald** [comment]
I'd describe that as a long-term fix for the build-task-and-use-it-in-same-solution problem; it's more than a workaround :)

**Comment by BenVillalobos** [comment]
I totally knew that and posted that originally and never edited the post 👀 nope not me.

Thanks!

**Comment by BenVillalobos** [comment]
Gentle nudge @sabotageandi. Please see the [feedback ticket](https://developercommunity.visualstudio.com/content/problem/893220/visual-studio-reuses-msbuild-process-although-msbu.html) for my response.

**Comment by BenVillalobos** [comment]
After some investigation it looks like MSBuild is launched differently for Design Time Builds compared to regular builds. These builds don't respect the environment variable `MSBUILDDISABLENODEREUSE` because they explicitly set nodeReuse to true.

A point of discussion to have: Should we update the MSBuild API https://github.com/microsoft/msbuild/blob/9eb5d09e6cd262375e37a15a779d56ab274167c8/src/Build/BackEnd/BuildManager/BuildParameters.cs#L397 to respect the environment variable `MSBUILDDISABLENODEREUSE`, or should we kick it off to the CPS folks?

Follow the link for the code on the CPS side of things (internal link): 
https://devdiv.visualstudio.com/DevDiv/_git/ProjectServices?path=%2Fsrc%2FMicrosoft.VisualStudio.ProjectServices%2FDesignTimeBuild%2FDesignTimeBuildScheduler.cs&version=GBmaster&line=635&lineEnd=635&lineStartColumn=21&lineEndColumn=44&lineStyle=plain

**Comment by rainersigwald** [comment]
@lifengl do you know anything about the history of CPS explicitly setting `EnableNodeReuse=true`? Would you have a problem if we stopped respecting that (if the user has specified the undocumented environment-variable escape hatch)?
