### ISSUE TITLE
GlobalProperties are not available in SDK-style projects (ProjectCollection.SetGlobalProperty)

### ISSUE THREAD

**Issue by alexis-** [microsoft/msbuild#5237]
### Context
I am developing a Visual Studio extension [Package](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.asyncpackage) with the objective of adding or overriding MSBuild properties in the solution's projects. These properties should be available in all of the projects' targets.

### Expected behavior
The properties that are defined(<sup>1</sup>) in the VS extension should be available to the projects' MSBuild targets. E.g.

```xml
<Target BeforeTargets="Build" Name="TestGlobalProperty">
  <Error Text="$(MyProperty)" />
</Target>
```

ℹ️ This functionality works correctly with the **old csproj** format.

### Actual behavior
With the new **sdk-style** projects, these properties are not set in any of the targets.

E.g., in the example line `<Error Text="$(MyProperty)" />`, $(MyProperty) isn't defined and MSBuild outputs ` error : (No message specified)` instead of the value specified in the VS extension.

### Steps to reproduce
(<sup>1</sup>): I have tried several methods to make the properties available to the MSBuild targets. I have detailed them below.

For each of these methods I have attempted to operate the changes at several points of the build execution. I have also detailed them below (<sup>2</sup>).

#### A - ProjectCollection.GlobalProjectCollection.SetGlobalProperty
The `GlobalProperties` Property of the `Microsoft.Build.Evaluation.ProjectCollection.GlobalProjectCollection`.

```csharp
var projCol = ProjectCollection.GlobalProjectCollection;

projCol.SetGlobalProperty("MyProperty", "MyPropertyValue");
```

- Program flow steps tested: 3 - 6
- Result with **old csproj** format: Works
- Result with **new sdk csproj** format: Doesn't work

#### B - IEventSource.ProjectStarted
This method is a hack. I accessed `BuildManager.DefaultBuildManager.LoggingService` through reflection in order to register my own `ILogger` implementation.

In my `ILogger` implementation I registered a event handler for the `ProjectStarted` event.

```csharp
var loggingSvc = BuildManager.DefaultBuildManager
  .GetType()
  .GetProperty("Microsoft.Build.BackEnd.IBuildComponentHost.LoggingService",
              BindingFlags.NonPublic | BindingFlags.Instance)
  .GetValue(BuildManager.DefaultBuildManager);

return (bool)loggingSvc
  .GetType()
  .GetMethod("RegisterLogger", BindingFlags.Public | BindingFlags.Instance, null, new[] { typeof(ILogger) }, null)
  .Invoke(loggingSvc, new object[] { new ReusableLogger(this) });
```

The ILogger implementation:

```csharp
public void Initialize(IEventSource eventSource)
{
  _eventSrc = (IEventSource3)eventSource;
  _eventSrc.ProjectStarted += _eventSrc_ProjectStarted;
}
```

The `ProjectStarted` event handler's implementation:

```csharp
private void _eventSrc_ProjectStarted(object sender, ProjectStartedEventArgs e)
{
  try
  {
    e.GlobalProperties["MyProperty"] = "MyPropertyValue";
  }
  catch (Exception ex)
  {
    JoinableTaskFactory.Run(() => this.WriteDebugAsync($"[SMA] ProjectStarted exception {ex}"));
  }
}
```

- Program flow steps tested: 1 - 2
- Result with **old csproj** format: Doesn't work
- Result with **new sdk csproj** format: Doesn't work

#### C - EnvDTE.Project.Properties.Item
After obtaining the `EnvDTE.Project` instance from `IVsHierarchy` using the `GetProperty` method, I tried to set the MSBuild properties using the `Properties.Item` object's property.

```csharp
var props = project.Properties;
var prop = props.Item("MyProperty");

if (prop != null)
  try
  {
    // None of these two methods worked:
    prop.Value = (object)"MyPropertyValue";
    prop.let_Value("MyPropertyValue");
  }
  catch (Exception ex)
  {
    this.WriteDebug($"SetProjectProperty '{project.Name}' exception:\n{ex}");
  }

project.Save();
```

- Program flow steps tested: 3 - 6
- Result with **old csproj** format: Doesn't work
- Result with **new sdk csproj** format: Doesn't work

I realize that this is the intended behaviour, I am outlining my experiments here for the sake of exhaustivity.

#### D - Program flow steps
(<sup>2</sup>): I have tried setting them at different stages, in case it had any influence:
1 - [BuildEventsClass.OnBuildProjConfigBegin](https://docs.microsoft.com/en-us/dotnet/api/envdte.buildeventsclass.onbuildprojconfigbegin?view=visualstudiosdk-2017)
2 - [BuildEventsClass.OnBuildBegin](https://docs.microsoft.com/en-us/dotnet/api/envdte.buildeventsclass.onbuildbegin)
3 - [IVsUpdateSolutionEvents2.UpdateProjectCfg_Begin](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.ivsupdatesolutionevents2.updateprojectcfg_begin)
4 - [IVsSolutionEvents.OnAfterOpenProject](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.ivssolutionevents.onafteropenproject)
5 - [IVsSolutionEvents.OnAfterLoadProject](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.ivssolutionevents.onafterloadproject)
6 - [OnAfterBackgroundSolutionLoadComplete](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.ivssolutionloadevents.onafterbackgroundsolutionloadcomplete)

### Environment data
`msbuild /version` output: `16.5.0.12403`
OS info: `Windows 10 18362.657`
If applicable, version of the tool that invokes MSBuild: `Visual Studio 2019 16.5.2`

**Comment by Forgind** [comment]
This issue was moved to dotnet/project-system#6116

**Comment by Forgind** [comment]
You might find this helpful:
https://github.com/dotnet/project-system/issues/6116#issuecomment-618080568
