### ISSUE TITLE
[RFC] ToolLocationHelper.GetPathToStandardLibraries(..) does not respect $(TargetFrameworkRootPath)

### ISSUE THREAD

**Issue by radical** [microsoft/msbuild#524]
`$(FrameworkPathOverride)` property is set by calling `Microsoft.Build.Utilities.ToolLocationHelper.GetPathToStandardLibraries(..)` (in [Microsoft.Common.CurrentVersion.targets](https://github.com/Microsoft/msbuild/blob/master/src/XMakeTasks/Microsoft.Common.CurrentVersion.targets#L81)), but it does not respect `$(TargetFrameworkRootPath)`. So, if the project targets a different framework, which is not available in the default frameworks location, then this ends up adding an invalid reference to `mscorlib.dll` from the .NET framework.

A solution to this would be to add an overload like:

```
    string GetPathToStandardLibraries(string targetFrameworkIdentifier, string targetFrameworkVersion, string targetFrameworkProfile, string platformTarget, string targetFrameworkRoot)
```

.. which accepts an additional parameter `targetFrameworkRoot`. And `$(TargetFrameworkRootPath)` can be passed as argument for this in `Microsoft.Common.CurrentVersion.targets` like:

```
-    <FrameworkPathOverride Condition="'$(FrameworkPathOverride)' == ''">$([Microsoft.Build.Utilities.ToolLocationHelper]::GetPathToStandardLibraries($(TargetFrameworkIdentifier), $(TargetFrameworkVersion), $(TargetFrameworkProfile), $(PlatformTarget)))</FrameworkPathOverride>
+    <FrameworkPathOverride Condition="'$(FrameworkPathOverride)' == ''">$([Microsoft.Build.Utilities.ToolLocationHelper]::GetPathToStandardLibraries($(TargetFrameworkIdentifier), $(TargetFrameworkVersion), $(TargetFrameworkProfile), $(PlatformTarget), $(TargetFrameworkRootPath)))</FrameworkPathOverride>
```

Does this sound acceptable?

It might also make sense to add a corresponding overload:

```
    IList<String> GetPathToReferenceAssemblies(string targetFrameworkIdentifier, string targetFrameworkVersion, string targetFrameworkProfile, string targetFrameworkRoot)
```

Though the change to `GetPathToStandardLibraries` can be implemented without a new overload for `GetPathToReferenceAssemblies`.

**Comment by radical** [comment]
I have opened a PR ( #529) that implements this, for feedback, specifically the commits - https://github.com/Microsoft/msbuild/pull/529/commits/85edfccaecfdb882188b1d6439f9da1d487f7b90 and https://github.com/Microsoft/msbuild/pull/529/commits/7cf8e080119d0bd9133f8aee8a10e5d31c1e92eb

**Comment by rainersigwald** [comment]
Assuming this is long addressed.
