### ISSUE TITLE
Null dereference check is not performed when creating tuples

### ISSUE THREAD

**Issue by EgorManevich** [microsoft/msbuild#5243]
### Steps to reproduce
When creating tuples using properties of nullable reference type, no null dereference checks are performed

```csharp
class Program {
	static void Main(string[] args) {
		M1(null);
	}
	static void M1(C? c) {
		var a = (c.I, c.I); //no warnings or errors on build
		Console.WriteLine(a);
	}
}
class C {
	public int? I { get; set; }
}
```

### Expected behavior
 Warning generated
`Dereference of a possibly null reference.`

### Actual behavior
No warnings are generated 

### Environment data
Build Engine version 16.5.0+d4cbfca49 for .NET Core

OS info:
Tried on MacOS, Windows

**Comment by rainersigwald** [comment]
This issue was moved to dotnet/roslyn#43140
