### ISSUE TITLE
[RFC] Support fallback search paths for Target frameworks

### ISSUE THREAD

**Issue by radical** [microsoft/msbuild#526]
Currently, target frameworks are looked up in the default location or a path specified by `$(TargetFrameworkRootPath)`. It would be useful to be able to look for these frameworks in more than one location. For example, in case of Xamarin products on OSX, mobile specific frameworks are installed in `/Library/Frameworks/Mono.framework/External/xbuild-frameworks` and the .net ones are installed in `/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/xbuild-frameworks` .

With support for fallback search paths, a lookup for a target framework would follow the order:

```
    1. $(TargetFrameworkRootPath) or Default location is $(TargetFrameworkRootPath) is ''
    2. Fallback search paths
```

These fallback search paths can be set in app.config, per os, like:

```
<msbuildToolsets default="14.1">
  <toolset toolsVersion="14.1">
    <property name="TargetFrameworkRootPathSearchPathsOSX" value="/tmp/foo;/tmp/bar" />
    <property name="TargetFrameworkRootPathSearchPathsWindows" value="C:\tmp\foo;C:\tmp\bar" />
    ...
```

This also depends on the issue #524 . 
I have a working patch for this approach.

If we don't want to add the new public overload from that issue, then the order could be:

```
    1. Default location (`$(TargetFrameworkRootPath)` being ignored :( )
    2. Fallback search paths
```

I think the former approach, i.e., respect `$(TargetFrameworkRootPath)`, would be better.

Comments? Does this sound like something useful for master too?

**Comment by radical** [comment]
I have opened a PR for this, #529 . Since I am not sure whether this approach is acceptable or not, the PR is still missing some tests.

**Comment by radical** [comment]
Any thoughts on this and #524 ?

**Comment by radical** [comment]
Another way to specify the search paths might be to make it consistent with the extensions path, like:

```
<msbuildFallbackSearchPaths>
        <searchPaths os="windows">
                <property name="MSBuildExtensionsPath" value="c:\foo\bar"/>
                <property name="MSBuildExtensionsPath32" value="c:\foo\bar32"/>

                <property name="TargetFrameworkRootPath" value="c:\foo\frmks"/>
        </searchPaths>
       <searchPaths os="osx">
                <property name="MSBuildExtensionsPath" value="/Library/Frameworks/Mono.framework/External/xbuild"/>
                <property name="MSBuildExtensionsPath32" value="/Library/Frameworks/Mono.framework/External/xbuild"/>

                <property name="TargetFrameworkRootPath" value="/Library/Frameworks/Mono.framework/External/xbuild-frameworks"/>
        </searchPaths>
</msbuildFallbackSearchPaths>
```

This would be consistent and easier to document+understand from the user pov.

**Comment by rainersigwald** [comment]
@radical we resolved this long ago, right?

**Comment by radical** [comment]
Yep, resolved by https://github.com/microsoft/msbuild/pull/3277 .
