### ISSUE TITLE
Resolution uses 'Current' instead of '15.0'

### ISSUE THREAD

**Issue by matkoch** [microsoft/msbuild#5263]
While loading a project roughly using the following code:

```
var projectCollection = new ProjectCollection();
var projectRoot = Microsoft.Build.Construction.ProjectRootElement.Open(projectFile, projectCollection, preserveFormatting: true);
var msbuildProject = Microsoft.Build.Evaluation.Project.FromProjectRootElement(projectRoot, new Microsoft.Build.Definition.ProjectOptions
{
    GlobalProperties = GetProperties(configuration, targetFramework),
    ToolsVersion = projectCollection.DefaultToolsVersion,
    ProjectCollection = projectCollection
});
```

I get an error:

```
The imported project "/usr/local/share/dotnet/sdk/2.1.300/Current/Microsoft.Common.props" was not found. Confirm that the expression in the Import declaration "/usr/local/share/dotnet/sdk/2.1.300/Current/Microsoft.Common.props" is correct, and that the file exists on disk.  /usr/local/share/dotnet/sdk/2.1.300/Sdks/Microsoft.NET.Sdk/Sdk/Sdk.props
```

I'm using the `16.5.0` packages. I'm setting `MSBUILD_EXE_PATH` to `/usr/local/share/dotnet/sdk/2.1.300/MSBuild.dll`. This path is resolved from calling `dotnet --info` in the respected project directory, and checking `Base Path: xxxxx`, to obey `global.json`.

I'm sure that instead of `Current` it should look in `15.0`.

**Comment by dasMulli** [comment]
You're using the 16.* nuget packages, right? If so, this should work with the 2.1.6xx and higher SDKs that use MSBuild 16 as well.
It's a sort-of breaking change that should remove exactly this issue in future releases.

**Comment by matkoch** [comment]
So this is not a bug, but a known limitation? No wqys to workaround?

**Comment by matkoch** [comment]
FYI, explicitly setting the `DefaultToolsVersion` errors with:

```
System.InvalidOperationException: The tools version "15.0" is unrecognized. Available tools versions are "Current".
```

**Comment by rainersigwald** [comment]
@matkoch, are you using [MSBuildLocator ](https://docs.microsoft.com/visualstudio/msbuild/updating-an-existing-application) to load MSBuild? It sounds like you're using a locally-deployed MSBuild (version 16.5) to use a .NET SDK (version 2.1.300, using MSBuild 15). That won't work very well for this and other reasons.

In addition, you shouldn't need to specify `ToolsVersion` . . . anywhere in 15.0+, as far as I know.
