### ISSUE TITLE
Request for release of a new mono-msbuild.zip build, for bootstrapping

### ISSUE THREAD

**Issue by radical** [Microsoft/msbuild#527]
The fix from PR #517 helps bootstrap with mono/master and the upcoming mono version.

**Comment by radical** [comment]
This is required for building with the new (alpha) release of Mono.

**Comment by cdmihai** [comment]
Unfortunately the Mono build is broken on all platforms.  #555 step 1) should get done before doing a new release for bootstrapping.

**Comment by radical** [comment]
Mono build based on 5e01f077d8cb7a94e0c100305512a872096c0b43 :
https://dl.dropboxusercontent.com/u/203926/mono_msbuild_5e01f07.zip

**Comment by radical** [comment]
Please retain the file name as is, to indicate that the `.zip` is meant purely for bootstrap purpose. I will update the `cibuild.sh` script to use this.

**Comment by cdmihai** [comment]
Thanks!
It's here: https://github.com/Microsoft/msbuild/releases/tag/mono-hosted-msbuild-v0.2

**Comment by radical** [comment]
Thanks :)
