### ISSUE TITLE
dotnet build failed

### ISSUE THREAD

**Issue by GioviQ** [microsoft/msbuild#5278]
Please clone this https://github.com/GioviQ/blazorboilerplate/tree/restructure.
Visual Studio 2019 16.5.3 builds correctly with configuration Release_CSB or Release_SSB, but dotnet build fails with errors https://enkodellc.visualstudio.com/blazorboilerplate/_build/results?buildId=646&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=f8ed7bd8-2a7f-56f6-9385-7fc29a8b5b7b&l=60

I think dotnet build does not support conditional construct Choose presents in https://github.com/GioviQ/blazorboilerplate/blob/restructure/src/Server/BlazorBoilerplate.Server/BlazorBoilerplate.Server.csproj

**Comment by rainersigwald** [comment]
> I think dotnet build does not support conditional construct Choose presents in

Can you elaborate on why you think that? The error you linked is a restore failure in another project:

```
D:\a\1\s\src\Shared\BlazorBoilerplate.Localization\BlazorBoilerplate.Localization.csproj : error NU1101: Unable to find package Microsoft.AspNetCore.Localization. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\1\s\src\BlazorBoilerplate.sln]
D:\a\1\s\src\Shared\BlazorBoilerplate.Localization\BlazorBoilerplate.Localization.csproj : error NU1101: Unable to find package Microsoft.Extensions.Localization. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\1\s\src\BlazorBoilerplate.sln]
```

**Comment by GioviQ** [comment]
Github has some other issues, because it can't restore packages. Maybe I shouldn't post that link because it can be misleading. 
If I try locally with dotnet build ./src/BlazorBoilerplate.sln --configuration Release_CSB > dotnet.log
[dotnet.log](https://github.com/microsoft/msbuild/files/4483212/dotnet.log)

Instead Visual Studio 2019 16.5.4 builds correctly.
