### ISSUE TITLE
Versions of MSBuild NuGet packages are incorrect

### ISSUE THREAD

**Issue by agocke** [Microsoft/msbuild#528]
The authoring of numerous MSBuild packages, including Microsoft.Build.Utilities.Core, includes dependencies to other MSBuild packages without version specifiers, like so:

```
<group targetFramework=".NETPlatform5.0">
    <dependency id="Microsoft.Build.Framework" />
</group>
```

This causes the implicit version reference to be 0.0.0, which is a release version. However, the versions for the packages are all prerelease, which causes NuGet to produce warnings about downgrading since we're referencing a prerelease version instead of a release version, e.g.,

```
 ToolsetPackages (>= 1.0.0) -> Roslyn.Build.Util (>= 0.9.2-portable) -> Microsoft.Build.Utilities.Core (>= 0.1.0-preview-00005) -> Microsoft.Build.Framework
 ToolsetPackages (>= 1.0.0) -> Roslyn.Build.Util (>= 0.9.2-portable) -> Microsoft.Build.Framework (>= 0.1.0-preview-00005)
```

Roslyn solves this by including a `version="[$version$]"` when building our packages, where `$version$` gets replaced during the build by the NuGet package version. This causes all our packages to have explicit references on each other. MSBuild should probably do the same.

**Comment by cdmihai** [comment]
@agocke 
I happily tried putting variables into our nuspecs as you suggested but the build failed :(
It seems that MSBuild and Roslyn generate packages differently. MSBuild is using a [BuildPackages](https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/packages.targets#L17) target from the BuildTools repo, whereas Roslyn has its custom [script](https://github.com/dotnet/roslyn/blob/master/build/BuildNuGets.csx)

I am going to try and update the [NugetPack](https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetPack.cs) task that buildtools uses so it accepts properties as well.

In the meantime, you can use the same workaround as buildtools is using to acquire msbuild, which is to reference all msbuild packages with the same version, thus forcing nuget to get packages with that version: https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json#L6-L10

**Comment by tmat** [comment]
@cdmihai Any update one this?

**Comment by cdmihai** [comment]
It's in the works. I am currently fixing up other issues with msbuild's nuget packages and then I am going to get back at this. 

I am going to fix this by updating the [NugetPack](https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetPack.cs) task in BuildTools to accept nuspec $$ properties. That way we can punch in the correct version with every build.

**Comment by tmat** [comment]
@cdmihai It's not blocking. We are just getting a bunch of warnings. I woudl rather have a clean build. Are the changes you're working on including supporting netstandard and netcoreapp TFMs? That's another thing I run into with the current packages.

**Comment by cdmihai** [comment]
I sent a PR to buildtools: https://github.com/dotnet/buildtools/pull/763
As soon as it gets merged and new buildtools packages get out, I can bump up msbuild's dependency of buildtools to latest and send out the msbuild PR.
I tested out the changes locally, with private build tools packages and everything works (msbuild nuget packages get their p2p references versioned).

@tmat The latest msbuild nuget packages are targeting netstandard1.3. You can reference them from both net46 and netcoreapp.

**Comment by jasonmalinowski** [comment]
@cdmihai Any update on this bug?

**Comment by cdmihai** [comment]
My PR to the corefx build tools repo that enables the NugetPack task to inject versions into the nuspec did not get much attention and in the meantime I started working on other issues :(

The plan is to eventually pick up pinging the buildtools repo owners after I get done with other work.

Is this a blocking issue for you? Are you able to use the current workaround of pinning the right msbuild versions in your project.json?

**Comment by anurse** [comment]
This is somewhat blocking most consumers of the MSBuild package, since we need to manually add these transitive dependencies to any project.json we use to reference MSBuild in order to eclipse the broken dependency.

**Comment by Sarabeth-Jaffe-Microsoft** [comment]
@cdmihai Any update on this? Looks like https://github.com/dotnet/buildtools/pull/763 was merged.

**Comment by cdmihai** [comment]
@jeffkl is working on bumping msbuild's version of buildtools to get the change, but a lot has changed and there's many problems to fix (mainly around corerun.exe -> dotnet.exe)
