### ISSUE TITLE
MSBuild doesnt make reference to shared data sources in SSRS

### ISSUE THREAD

**Issue by mcgiany** [microsoft/msbuild#5283]
Hi,

i tried to automatize deploy process of my rptproj project by using msbuild.exe
I have several reports, that has references to shared datasource and also shared data sets. When i deploy project via Visual Studio, everything is fine. When i use msbuild, it ends up with this error:

    warning : The dataset `RPT' refers to the shared data source `RPT', which is not published on the report server.  The shared data source `RPT' must be published before this report can run.

But, this problem is only when i want to put shared data sources and data sets into the folders. This is what i run from command line:

```
MSBuild.exe "Reports.rptproj" /target:Deploy /p:TargetServerUrl=http://localhost/ReportServer /p:TargetDatasetFolder=Datasets /p:TargetDataSourceFolder="Data Sources" /p:TargetReportFolder=Reports /p:TargetReportPartFolder="Report Parts" /p:OverwriteDataSources=False /p:OverwriteDatasets=False
```

Everything is deployed fine, but references are missing. When i use Visual Studio deploy, everything is fine. Reports are in folder, data sets are in folder, data source also and references are created.

When i dont use parameters TargetDatasetFolder, TargetDataSourceFolder, TargetReportFolder then also references are good, but everything is deployed into root which i dont want.

It is there something that i miss? I cant find proper documentation. Also tried catch what visual studio run under the hood during deploy, with no luck.

**Comment by rainersigwald** [comment]
@mcgiany, I think this is a bug/question for the SSRS folks. Can you please report this at https://developercommunity.visualstudio.com? If you reply here with a link I can help expedite routing to the right team.
