### ISSUE TITLE
RAR resolves from a location not explicitly specified

### ISSUE THREAD

**Issue by KirillOsenkov** [microsoft/msbuild#5300]
This was a build of Roslyn, ping me for the binlog. 

It reported these three locations as used assembly search paths:
![image](https://user-images.githubusercontent.com/679326/79790448-91f1c100-8300-11ea-9b44-3219bdf4c3da.png)

Upon further investigation it looks like `Resolved file path is "C:\roslyn\artifacts\bin\Microsoft.CodeAnalysis.Remote.Workspaces\Debug\net472\Microsoft.Diagnostics.Tracing.EventSource.dll".` was resolved from the directory that contained one of `AssemblyFiles`: 

![image](https://user-images.githubusercontent.com/679326/79790379-7d152d80-8300-11ea-89b5-a6cf9d3f2d17.png)

I'm not sure it's the desired or by-design behavior but it was not obvious that RAR will attempt to resolve from locations where other assemblies are.

If I am correct and this is indeed the behavior, we should investigate adding an option to turn it off, so only the explicitly allowed locations are used.

**Comment by rainersigwald** [comment]
I think this is intentional; it's how transitive ProjectReferences are generally resolved (from the bin folder of the direct reference). Because of that I'm not sure an option to turn it off makes sense . . .

**Comment by KirillOsenkov** [comment]
Got it, seems to be by design then!
