### ISSUE TITLE
Allow specifying environment variables in Exec Task

### ISSUE THREAD

**Issue by ViktorHofer** [microsoft/msbuild#5308]
The Exec Task currently doesn't allow specifying environment variables which would be set for the to invoked process.

### Example use case
The SDK currently defines a `Run` target which is used by VS to F5 an application. The properties used in the `Run` target are `RunCommand`, `RunArguments` and `RunWorkingDirectory`: https://github.com/dotnet/sdk/blob/3ed908ee77c592bae787ac78f466c3bc0581970a/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L757.

If the Exec Task would allow specifying environment variables we could add a `RunEnvironmentVariables` property which would remove the need for an extra launchSettings.json file: https://github.com/dotnet/runtime/blob/817ebcaeb617813f98650e78c14e76bbd8b733b0/eng/testing/launchSettings.json#L14-L16.

### Other references
- http://blog.jdhardy.ca/2011/12/setting-environment-variables-for.html
- https://www.develop-bugs.com/article/21515881/Use+path+system+environment+variable+in+MSBuild+exec+task

cc @rainersigwald

**Comment by rainersigwald** [comment]
`Exec` does support this.

Example from the Mac I'm on right now:

```xml
<Project>
  <Target Name="Exec">
    <Exec Command="env | grep FOO"
          EnvironmentVariables="FOO=bar" />
  </Target>
</Project>
```

```sh-session
$ echo $FOO


$ dotnet msbuild exec-env.proj
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  FOO=bar
```

@ghogen, I suspect this is an example of the `ToolTask`-derived task docs not being sufficiently clear that they expose the `ToolTask` parameters. We have a link in each of them pointing to the base class, but is there a way to define a central snippet that could be included in each doc page?

**Comment by ViktorHofer** [comment]
OK I forgot to look into ToolTask... I would definitely add an outline to the docs page: https://docs.microsoft.com/en-us/visualstudio/msbuild/exec-task?view=vs-2019

**Comment by ghogen** [comment]
@rainersigwald Yes we can write a separate code snippet and reference it from each article.
https://review.docs.microsoft.com/en-us/help/contribute/code-in-docs?branch=master#in-repo-snippet-references

We use an older outdated syntax in our docs though: see msbuild/build-loggers.md for examples

[!code-csharp[msbuild_SimpleConsoleLogger#2](../msbuild/codesnippet/CSharp/build-loggers_1.cs)]

If you have the code, I can set this up.

**Comment by rainersigwald** [comment]
@ghogen close, I think what we want is https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master to include a table of the ToolTask arguments.

Let me throw a draft of that together.

**Comment by rainersigwald** [comment]
https://github.com/MicrosoftDocs/visualstudio-docs/pull/5175

**Comment by rainersigwald** [comment]
@ViktorHofer fyi: https://docs.microsoft.com/en-us/visualstudio/msbuild/exec-task?view=vs-2019#tooltaskextension-parameters is now there.

**Comment by ViktorHofer** [comment]
This is super helpful, thanks a lot Rainer 👍

**Comment by hairlesshobo** [comment]
This may be obvious to most, but in case it isn't and you find yourself here by googling this like I did.. if you need to specify multiple environment variables to an Exec command, separating them with a semicolon seems to do the trick.

**Comment by rainersigwald** [comment]
@hairlesshobo would MicrosoftDocs/visualstudio-docs#5783 help?
