### ISSUE TITLE
Pack with IncludeBuildOutput set to false still adds netstandard as a dependency

### ISSUE THREAD

**Issue by TFTomSun** [microsoft/msbuild#5309]
### Steps to reproduce

Create a project file like this:

Project file
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.1</TargetFramework>
    <IncludeBuildOutput>false</IncludeBuildOutput>
  </PropertyGroup>
</Project>

```
Pack it with:

Command line
```
dotnet pack
```
### Expected behavior

The resulting package has no dependency to NetStandard, because I don't include the build output. I would expect a package that can be installed standalone... without any dependency.

### Actual behavior
The package has a dependency to NetStandard

**Comment by rainersigwald** [comment]
This issue was moved to NuGet/Home#9470
