### ISSUE TITLE
Add tests using old NuGet restoring with the newly created boostrapped MSBuild

### ISSUE THREAD

**Issue by Forgind** [microsoft/msbuild#5313]
Preventing the issue underlying https://github.com/microsoft/msbuild/pull/5257 from recurring. Ideally, this would be part of our CI test suite.

**Comment by rainersigwald** [comment]
My mental model for this is: get an ancient `nuget.exe` from https://www.nuget.org/packages/NuGet.CommandLine/4.1.0 and run it, passing `nuget.exe restore -MSBuildPath {path to private, just-built MSBuild}`.
