### ISSUE TITLE
Design Time Builds failing if we have some derived properties in Implicit or leading imports

### ISSUE THREAD

**Issue by Anipik** [microsoft/msbuild#5319]
In case of multple TargetFrameworks,  DesignTimeBuild uses  msbuild ```setproperty``` function to  set the TargetFramework property.  

So this updates a property if it exists, otherwise it searches for the first unconditioned PropertyGroup in the project file to add the property to. This is always going to be after any implicit imports as well as explicitly leading imports. This appears to be the long-standing behavior of SetProperty. Contrast that to SetGlobalProperty, which will treat the property as global.

Hence any property derived from targetFramework in implicit imports and leading imports will not be evaluated correctly.

There is a detail repro here https://github.com/dotnet/runtime/issues/33427#issuecomment-597634844

cc @ericstj @ViktorHofer 

similar issue https://github.com/OmniSharp/omnisharp-roslyn/issues/1738

**Comment by rainersigwald** [comment]
This issue was moved to dotnet/project-system#6143
