### ISSUE TITLE
Document CopyLocalLockFileAssemblies and how to control copying to output

### ISSUE THREAD

**Issue by KirillOsenkov** [microsoft/msbuild#5321]
See the issue that prompted this:
https://github.com/microsoft/msbuild/issues/5312

We have this article but it's kind of dated:
https://github.com/microsoft/msbuild/blob/master/documentation/wiki/ResolveAssemblyReference.md

We have this:
https://stackoverflow.com/questions/43837638/how-do-i-get-net-core-projects-to-copy-nuget-references-to-the-build-output

Google search for CopyLocalLockFileAssemblies doesn't have the docs.microsoft.com among the first few results.

**Comment by rainersigwald** [comment]
This is a .NET Core SDK concept rather than core MSBuild (fuzzy line, of course). I see it mentioned only here: https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support#plugin-with-library-dependencies.

@marcpopMSFT can you help route to SDK docs team?

**Comment by marcpopMSFT** [comment]
This issue was moved to dotnet/docs#18183
