### ISSUE TITLE
ResolveAssemblyReference Exception, EmulateFileIOPermissionChecks 

### ISSUE THREAD

**Issue by skyyearxp** [microsoft/msbuild#5323]
**msbuild ver 16.5.0+d4cbfca49**, installed with visual studio 2019 installer.
after install vs2019, when build some project will fail, cause exception ResolveAssemblyReference 

```
System.AggregateException: 发生一个或多个错误。 ---> System.NotSupportedException: 不支持给定路径的格式。
   在 System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   在 System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   在 System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   在 Microsoft.Build.Tasks.AssemblyFoldersExCache.<>c__DisplayClass3_0.<.ctor>b__0(AssemblyFoldersExInfo assemblyFolder)
```

after use dnSpy debug msbuild, set capture all exception, i find the problem when test directory, the directory value is like read from registry, the value look like a uninstalled vs2010 path, the path start with "-:\" cause the exception.
```
**regkey**: HKLM\Software\Microsoft\.NETFramework\v4.0.30319\AssemblyFoldersEx\Public Assemblies v10.0
**regvalue**: @"**-:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PublicAssemblies\**"
```
but i can't find that regkey in Regedit, i don't known where the value read out.

temp solution, in the below read function, contain a EnviromentVariable Test, can bypass the Folder Check.  
```
internal AssemblyFoldersExCache(AssemblyFoldersEx assemblyFoldersEx, FileExists fileExists)
....
...
if (Environment.GetEnvironmentVariable("MSBUILDDISABLEASSEMBLYFOLDERSEXCACHE") != null)
{
this._useOriginalFileExists = true;
return;
}
```

after set the EnvironmentVariable **MSBUILDDISABLEASSEMBLYFOLDERSEXCACHE=1**, then i can build the project successful.

but i think that's a problem, so a i open this issuse.

i have tried use dotNet_TotalUninstaller to uninstall all VS product, and reinstall VS2019, nothing work.

i think may be, need check path or try catch this exception, not throw it. as a developer don't known how to do with this exception. and the exception does not show enough exception detail.

**Comment by skyyearxp** [comment]
NOTE:
1、temp solution, set the EnvironmentVariable **MSBUILDDISABLEASSEMBLYFOLDERSEXCACHE=1**
2、debug msbuild，set the EnvironmentVariable **MSBUILDDEBUGONSTART=2**, start msbuild, it will wait for debugger attach. BUT i think the easyest way is to use dnSpy, ;)

**Comment by rainersigwald** [comment]
> i can't find that regkey in Regedit

Did you look in the 32-bit registry under `WOW6432Node`?

If it's set there, MSBuild is failing due to corrupt state on your machine which I wouldn't treat as a bug.

**Comment by skyyearxp** [comment]
@rainersigwald YES, i fogot to look in WOW6432Node.

HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v4.0.30319\AssemblyFoldersEx\Public Assemblies v10.0
-:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PublicAssemblies\

I have reinstall the system, so let it go. tks.
