### ISSUE TITLE
msbuild does not build Xamarin.Forms project correctly when building from Xamarin.iOS csproj

### ISSUE THREAD

**Issue by beeradmoore** [microsoft/msbuild#5336]
### Steps to reproduce

1. Clone sample repo: https://github.com/beeradmoore/AppCenterBuildConfig
2. Restore nuget and build project.
```
cd AppCenterBuildConfig

# Restore nugets the same way AppCenter does.
find . -name '*.sln' -type f -print0 | /usr/bin/xargs -0 grep -l 'AppCenterTestBuild.iOS.csproj' | /usr/bin/xargs -I '{}' nuget restore '{}' -DisableParallelProcessing

msbuild ./AppCenterTestBuild.iOS/AppCenterTestBuild.iOS.csproj \
    /p:Configuration=AppCenter \
    /p:Platform=iPhone \
    /p:BuildIpa=true \
    /t:Build \
    /p:Codesignkey="REDACTED" \
    /p:CodesignProvision="REDACTED"
```

Either deploy the app to view the displayed output or examine the build log to see that `__APPCENTER__` define constants in `AppCenterTestBuild/AppCenterTestBuild.csproj` were never included in the build of that project.

I have attached two build logs, one for building with csproj, and one for building with sln. The sln build is the same as above, but the first line of the msbuild is replaced with 
```
msbuild ./AppCenterTestBuild.sln \
```

You can observe the difference in the building of the Xamarin.Forms project with  [build_csproj.log](https://github.com/microsoft/msbuild/files/4590142/build_csproj.log) on line 62, or in the other [build_sln.log](https://github.com/microsoft/msbuild/files/4590143/build_sln.log) on line 67.

Defined constants in csproj build log:
`/define:TRACE;APPCENTER;NETSTANDARD;NETSTANDARD2_0`

Defined constants in sln build log:
`/define:TRACE;RELEASE;NETSTANDARD;NETSTANDARD2_0;__APPCENTER__;APPCENTER;NETSTANDARD;NETSTANDARD2_0`

(note: `APPCENTER` is in the defines as it is the build config name, `__APPCENTER__` is the one that I have included in all projects)

### Expected behavior
When the app is ran it is expected that `__APPCENTER__` was included resulting in AppCenter being displayed next to `Forms build type:`.

![IMG_3883 copy](https://user-images.githubusercontent.com/904737/81243132-52daa400-9052-11ea-82dc-0bfeffcbf3b5.png)

### Actual behavior
Both Release and AppCenter is missing next to `Forms build type:`. They were however used correctly from the `AppCenterTestBuild.iOS.csproj` which controls the output for `Device build type:`. `RELEASE` is also missing as shown above in csproj build log above, this is why Release is also missing from the output displayed in the app for that particular project.

![IMG_3884 copy](https://user-images.githubusercontent.com/904737/81243145-5ec66600-9052-11ea-9ac9-6a9f7470d9e5.png)
### Environment data
`msbuild /version` output:
```
Microsoft (R) Build Engine version 16.5.0-ci for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

16.5.0.16201
```

OS info:
macOS 10.15.4

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):
Invoked just from Terminal app. I am using Xcode 11.4 and I have Visual Studio 8.5.4 installed.

### Additional information
Building the same project for Android builds with the expect define constants in the build log, however I was unable to install this app as I am unsure how to sign the package via command line. 
```
msbuild ./AppCenterTestBuild.Android/AppCenterTestBuild.Android.csproj \
    /t:PackageForAndroid \
    /p:Configuration=AppCenter 
```
The build log is here: 
[build_android.log](https://github.com/microsoft/msbuild/files/4590181/build_android.log)

Line 44 shows Xamarin.Forms project being built, it contains the same defined constants as the iOS sln project has.
```
/define:TRACE;RELEASE;NETSTANDARD;NETSTANDARD2_0;__APPCENTER__;APPCENTER;NETSTANDARD;NETSTANDARD2_0
```

Building iOS project in Visual Studio for Mac and deploying to device or simulator displays the expected output. I am also opening the .sln file, which above is shown to generate the correct output.

**Comment by rainersigwald** [comment]
@redth, can you help us route this?

**Comment by Redth** [comment]
Maybe I'm underthinking this but your Condition is dependant on `$(Platform)` being equal to `AnyCpu` and it looks like the .csproj build is using `iPhone` which means your condition is never met.

Can I recommend using a [pre-defined AppCenter environment variable](https://docs.microsoft.com/en-us/appcenter/build/custom/variables/#pre-defined-variables) to add the constant to the build when running on appcenter instead?

```
<PropertyGroup Condition="'$(APPCENTER_BUILD_ID)'!=''">
	<DefineConstants>$(DefineConstants);__APPCENTER__</DefineConstants>
</PropertyGroup>
```

**Comment by beeradmoore** [comment]
I had wondered why it was working for Android and not iOS considering they are both built the same way from the command line. Thats why I assumed its some internal msbuild issue of how it handles different projects.

Last weekend that actually led me to try something similar to your workaround (although I have only tested locally, not on AppCenter). Only difference is I check if the config is AppCenter. That way a release that is intended for AppStore won't have AppCenter in it. Configurations I normally have is Debug, Release, and AppCenter.

```
<PropertyGroup Condition=" '$(Configuration)' == 'AppCenter' ">
    <DefineConstants>$(DefineConstants);__APPCENTER__</DefineConstants>
</PropertyGroup>
```

I'll go try this on AppCenter to see if it does resolve my issue there.

I'm still not exactly sure why this is happening only to iOS builds, why building the .sln instead of .csproj fixes it, or why/when this had possibly changed at some point (I don't recall us changing our configs, maybe someone else in the team did that I wasn't aware of). I didn't hear much people having issues with it while researching it so I assume it isn't a common issue or use case.

**Comment by Redth** [comment]
The android build’s Platform _would_ be `AnyCpu`.  For historic reasons iOS uses `iPhone` to build for iOS device. This will be more normalized and consistent in .NET6. 

Your other workaround works because it only specified the Configuration and not Platform as well. 

I suggested my workaround also because it works with the default Release and Debug configurations and doesn’t require you set up an additional config just for appcenter. 

In any case sounds like you have a working solution!

**Comment by beeradmoore** [comment]
Ohh, I see what you mean about AnyCPU/iPhone now. The forms csproj is checking platform of AnyCPU. I don't know if I didn't see that or if I just assumed AnyCPU meant iPhone/iPhoneSimulator. 

I can't do the exact AppCenter workaround you mentioned because our app has lots of hidden bells and whistles that get enabled for our internal AppCenter builds, but then master branch is pure and to TestFlight/Google Play Beta. I however will play with what you said and do something similar to this,

```
<PropertyGroup Condition=" '$(APPCENTER_BRANCH )' != '' And '$(APPCENTER_BRANCH)' != 'master' ">
```

In our code we normally do things like
```
#if __APPCENTER__
 var server = "https://someDebugServer";
#elif DEBUG
 var server = "https://someLocalServer";
#endif
```
or we use both like this,
```
#if DEBUG || __APPCENTER__
  HiddenMenu.IsVisible = true;
#endif
```
So that will handle it for our use case.

If we were to keep our 3 build types I'd probably go change our Forms csproj from

```
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    ...
</PropertyGroup>
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    ...
</PropertyGroup>
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'AppCenter|AnyCPU' ">
    ...
</PropertyGroup>
```
to
```
<PropertyGroup Condition="'$(Configuration)'=='Debug'">
    ...
</PropertyGroup>
<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    ...
</PropertyGroup>
<PropertyGroup Condition=" '$(Configuration)' == 'AppCenter' ">
    ...
</PropertyGroup>
```

**Comment by beeradmoore** [comment]
I have confirmed that this workaround works great in AppCenter. Thanks @Redth
