### ISSUE TITLE
Error en PowerShell

### ISSUE THREAD

**Issue by crtlJSM** [microsoft/msbuild#5354]
C:\Program Files\dotnet\sdk\3.1.202\Microsoft.Common.CurrentVersion.targets(3032,5): error MSB3822: Los recursos que no son de cadena requieren el ensamblado System.Resources.Extensions en tiempo de ejecución, pero no se encontró en las referencias del proyecto. [C:\Users\Josei\Josei.csproj]
C:\Program Files\dotnet\sdk\3.1.202\Microsoft.Common.CurrentVersion.targets(3032,5): error MSB3822: Los recursos que no son de cadena requieren el ensamblado System.Resources.Extensions en tiempo de ejecución, pero no se encontró en las referencias del proyecto. [C:\Users\Josei\Josei.csproj]
C:\Program Files\dotnet\sdk\3.1.202\Microsoft.Common.CurrentVersion.targets(3032,5): error MSB3822: Los recursos que no son de cadena requieren el ensamblado System.Resources.Extensions en tiempo de ejecución, pero no se encontró en las referencias del proyecto. [C:\Users\Josei\Josei.csproj]

No se pudo llevar a cabo la compilación. Corrija los errores de compilación y vuelva a ejecutar el proyecto.

**Comment by rainersigwald** [comment]
Can you provide more context for your problem? This error is expected if you do not have

```xml
<PackageReference Include="System.Resources.Extensions" Version="4.7.1" />
```

In your project file.
