### ISSUE TITLE
Log MSBuild process locale

### ISSUE THREAD

**Issue by KirillOsenkov** [microsoft/msbuild#5356]
I often see binlogs in German, French, etc. but there's no way to easily get the language except for guessing. 

If we want to properly parse localized binlogs we need to know the language. Since we already log the binlog path, process, arguments, etc. let's also log the current culture of MSBuild.exe.

**Comment by KirillOsenkov** [comment]
See related: https://github.com/microsoft/msbuild/issues/1596

**Comment by KirillOsenkov** [comment]
Same approach as in https://github.com/microsoft/msbuild/issues/2810

**Comment by KirillOsenkov** [comment]
https://source.dot.net/#q=GetMessagesToLogInBuildLoggers

**Comment by KirillOsenkov** [comment]
https://github.com/microsoft/msbuild/pull/5426

**Comment by rainersigwald** [comment]
Do we need more than #5426?

**Comment by KirillOsenkov** [comment]
Nope
