### ISSUE TITLE
GenerateFullPaths should be on default for all projects

### ISSUE THREAD

**Issue by davkean** [microsoft/msbuild#5358]
### Steps to reproduce

`GenerateFullPaths` property controls whether a variety of targets generate full paths to for the `File` property in their errors, warnings and messages.

Both C#/VB projects (legacy and CPS) work around the fact that this property is set to false, by _after the fact_ modification of the event args to set the full path of the error before reporting to it the Error List/Output windows:

For example, the following code is duplicated 3 times for error, warning and message:

``` C#
        private BuildWarningEventArgs MakeRooted(BuildWarningEventArgs e)
        {
            if (this.TryMakeRooted(e.ProjectFile, e.File, out string rootedPath))
            {
                return new BuildWarningEventArgs(
                    e.Subcategory,
                    e.Code,
                    rootedPath,
                    e.LineNumber,
                    e.ColumnNumber,
                    e.EndLineNumber,
                    e.EndColumnNumber,
                    e.Message,
                    e.HelpKeyword,
                    e.SenderName,
                    e.Timestamp)
                {
                    BuildEventContext = e.BuildEventContext,
                    ProjectFile = e.ProjectFile
                };
            }

            return e;
        }

        private bool TryMakeRooted(string projectFile, string file, out string result)
        {
            if (!string.IsNullOrEmpty(projectFile) && !string.IsNullOrEmpty(file))
            {
                try
                {
                    string basePath = Path.GetDirectoryName(projectFile);

                    result = Path.Combine(basePath, file);
                    return true;
                }
                catch (ArgumentException)
                {
                }
                catch (PathTooLongException)
                {
                }
            }

            result = null;
            return false;
        }
```

This code is problematic because 

1) It increases the number of allocations per message
2) It assumes that msbuild will not derive from, or add any new fields to these events.

This has been attempted to be fixed a number of times from a VS perspective and in AzureDevOps, can we please centralize the fix in MSBuild by flipping this property to true by default both via command-line and VS. 

See: https://github.com/dotnet/project-system/issues/5588 for more context.

**Comment by rainersigwald** [comment]
We can't think of a reason that flipping the default to the more reasonable value would break many people, and they'd have the ability to opt out by specifying the current behavior. We'll try to take this for 16.7p3.

**Comment by davkean** [comment]
We've stopped setting this property as a global property:  https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/267434. Be sure to inform us if this is changed again.
