### ISSUE TITLE
IndexOf(Char, StringComparison) is used instead of IndexOf(Char, Int32), resulting in build errors.

### ISSUE THREAD

**Issue by auott** [microsoft/msbuild#5360]
### Steps to reproduce

Add the following to a project file or targets file that gets included when building:

```xml
  <PropertyGroup>
    <Revision>$([System.DateTime]::Now.ToString(yyyyMMdd)).99</Revision>
    <TheIndex>$(Revision.IndexOf('.', 10))</TheIndex>
  </PropertyGroup>
```

### Expected behavior
The project can build successfully and IndexOf(Char, Int32) is invoked on Revision.

### Actual behavior
An error is produced:
```
error MSB4184: The expression ""20200519.99".IndexOf(., 10)" cannot be evaluated. The string comparison type passed in is currently not supported. Parameter name: comparisonType
```

It appears that it's only attempting to use IndexOf(Char, StringComparison) and 10 isn't
a valid value for the StringComparison enum. However, it should still be using IndexOf(Char, Int32)
### Environment data
`msbuild /version` output:

Microsoft (R) Build Engine version 16.7.0-preview-20265-07+31a1a34cb for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.7.0.26507

OS info:
Windows - 10.0.18362

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):
Occurs opening the project in VS or when trying to build the project from a VS command prompt.

**Comment by andrewcrawley** [comment]
Note that this worked fine until recently.  Here's a working version of msbuild:

```
D:\>msbuild /version
Microsoft (R) Build Engine version 16.7.0-preview-20228-06+9571f7584 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.7.0.22806
```

**Comment by rainersigwald** [comment]
Probably introduced by #5342. cc @cdmihai.

Let's try to revert before shipping 16.7preview2.

**Comment by rainersigwald** [comment]
(Thanks for the report @auott!)
