### ISSUE TITLE
Unable to publish solution that has projects targeting multiple frameworks.

### ISSUE THREAD

**Issue by Xeeynamo** [microsoft/msbuild#5373]
### Steps to reproduce

Download or clone the repository https://github.com/xeeynamo/openkh

Command line
```
git clone https://github.com/xeeynamo/openkh
cd openkh
git submodule update --init
dotnet publish -f netcoreapp3.1
```
### Expected behavior

The solution should be compiled without any error, as `dotnet build` output.

### Actual behavior

Projects that uses `<TargetFrameworks>net472;netcoreapp3.1</TargetFrameworks>` or `<TargetFramework>netstandard2.0</TargetFramework>` may fail with the following error:
```
error NETSDK1005: Assets file 'D:\openkh\OpenKh.Bbs\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v3.1'. Ensure that restore has run and that you have included 'netcoreapp3.1' in the TargetFrameworks for your project.
```

### Environment data

`msbuild /version` output:
```
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.6.0.22303
```

`dotnet --list-sdks` output:
```
3.1.300-preview-015135 [C:\Program Files\dotnet\sdk]
3.1.300 [C:\Program Files\dotnet\sdk]
```

OS info: Windows 10 19041.264

Searching through the existing issues, I became aware that there was a regression for MSBuild 15.9 that has been fixed in #3628. Although the issue looks very similar.

**Comment by rainersigwald** [comment]
Thanks for the report. Publish at the solution level is not supported today. https://github.com/dotnet/sdk/issues/3650 has details and is the best place for additional feedback.
