### ISSUE TITLE
binlog should record item updates

### ISSUE THREAD

**Issue by zivkan** [microsoft/msbuild#5374]
The binlog has "Add Item" nodes in the graph. I think it should also record "Update Item", to make it easier to

1. see metadata that was added or changed
2. Discover where an item was modified, which may not be obvious when it comes from an imported MSBuild file.

### Steps to reproduce

Project file
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NuGet.Versioning" Version="5.6.0" />
  </ItemGroup>

  <Target Name="CopyPackageAssembliesToSubFolder" AfterTargets="ResolveReferences">
    <ItemGroup>
      <ReferenceCopyLocalPaths Condition=" '%(ReferenceCopyLocalPaths.NuGetPackageId)' != '' "
        Update="%(ReferenceCopyLocalPaths)"
        DestinationSubDirectory="libs\" />
    </ItemGroup>
  </Target>

</Project>
```

Command line
```
dotnet build -bl
```
### Expected behavior

Opening the binlog and searching for "DestinationSubDirectory" should show results.

### Actual behavior

0 results

### Environment data
`dotnet msbuild -version` output: 16.6.0.18102

OS info: Win10 1903

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc): dotnet 5.0.100-preview.3.20216.6

**Comment by KirillOsenkov** [comment]
Probably a dupe of https://github.com/microsoft/msbuild/issues/3538

**Comment by zivkan** [comment]
I agree. I didn't manage to find it with github issue search :(
