### ISSUE TITLE
Replacement for ToolsVersion 

### ISSUE THREAD

**Issue by MichaelKetting** [microsoft/msbuild#5376]
In my build script, I call the msbuild task with the toolsversion parameter. This allows me to use MSBuild 2017 (v15.0) to run a build script that uses the CSC.exe from MSBuild 2013 (v12.0) 
```xml
<MSBuild Projects="@(ProjectFiles)"
         ToolsVersion="12.0">
</MSBuild>
```

MSBuild has changed the tools version to "Current" (https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-toolset-toolsversion?view=vs-2019). There's also questions on the internet about this, answered as "by-design": https://developercommunity.visualstudio.com/content/problem/404485/vs2019-msbuildtoolsversion-is-not-a-version.html

So, no my question is: how can I select the CSC.exe binaries to use, starting with the next version of MSBuild, given there is just the new catch-all tools version "current"?

Thanks, Michael

**Comment by rainersigwald** [comment]
To use a specific toolset, use the MSBuild that shipped with that version of Visual Studio. The old approach with toolsets didn't really work as expected and was made much more complicated by Visual Studio's support (in VS 15.0) for side-by-side installations of the same version of Visual Studio (for instance: if you have 16.5.3 and 16.7-preview1 installed, which gets used for `ToolsVersion="16.0"`?).

**Comment by MichaelKetting** [comment]
Thank you for the explanation.
