### ISSUE TITLE
Add a .targets file to the MSBuild-VS project

### ISSUE THREAD

**Issue by KKacer** [microsoft/msbuild#5382]
I am new to using .targets file and MSBuild, tried to create the simplest form of MSBuild example with a ".targets" file.

How can I add/attach the ".targets" file to the build process? Seems the target file isn't attached right now, and the **MESSAGE** isn't shown, how can I be sure it is attached and see the message? Am I missed any step? (Added the sample code at the end)

Project Names: MSBuildTest2, LibXy (The library to be compiled as a nuget package with .targets file) .Targets file location: LibXy project\build\LibXy.Targets (the same name as the project, want to have it in the folder)

**.CSProj file**
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="build\" />
    <Content Include="build\*.targets" PackagePath="build\" />
  </ItemGroup>

</Project>
```

**build\LibXy.targets**

```
<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <Target Name="TestTarget" AfterTargets="Build">
    <Message Importance="High" Text="-------------MHM----------------" />
  </Target>

</Project>
```

I built the project in 2 ways, with the build menu and with the command below in the CMD/terminal?

dotnet msbuild LibXy\LibXy.csproj

tried also with "-v:diag" which I don't think be the case, and I prefer the tidier look, and using that also didn't help.

Github project to try if needed:

Sample project on github
https://github.com/KKacer/MSBuildTest2

Visual Studio 16.6
.Net Standard 2.0
Windows 10

**Comment by KKacer** [comment]
Thanks for the feedback,
I read almost every article on the internet including your link,
but I admit that it is still possible that I missed something in between.

I don't know why the .targets file never get triggered unless we import them manually, though their file names are equal to the project name. 
Did I miss anything about them?

**Please check this video which explain my issue:**
https://1drv.ms/v/s!AlScPmE9PLAKgS1worlnqNrGLUsN?e=d4dcrF

**Comment by rainersigwald** [comment]
@KKacer, there's no automatic import of `build/{projectname}.targets`. Did you find an indication somewhere that there was? The only automatic import is of `Directory.Build.props` and `Directory.Build.targets` files.

**Comment by KKacer** [comment]
Back again, 

Seems there was a basic rule about MSBuild targets that I didn't know when I started it recently,
and that was the fact that the targets would run on the target assembly and not the assembly included the targets file. That led me wrong.
But I think one other issue also was happening in every project, some times it seems those target files even wouldn't run on the targets project randomly and they start working after quit/reopen, clearing bin/obj thing, and such other tricks.
By the way seems I am currently on the path, and my projects and the MSBuild files are working as expected.

thank you for following the topic,
If possible I have 2 other questions,
which can ask and mention you in a different topic

regards,
Kasra

**Comment by KKacer** [comment]
Opened one issue/question in the msbuildtasks repository,
if you be interested and can help on it:
https://github.com/loresoft/msbuildtasks/issues/296
