### ISSUE TITLE
MS Build Error - dotnet restore 

### ISSUE THREAD

**Issue by rebecca-makar** [microsoft/msbuild#5397]
### Steps to reproduce

I have been running on azure devops ubuntu 16.04 hosted pipeline:
`  dotnet restore Microsoft.Azure.Management.StorageCache.Tests.csproj`

and starting on Monday I started to get this error for the above call:

```
MSBUILD : error MSB1008: Only one project can be specified.
Switch: Microsoft.Azure.Management.StorageCache.Tests.csproj
```
I checked and we have been running the same version of the ubuntu image for the past 9 days.

### Environment data
Initializing job: 
```

Current agent version: '2.169.1'
Operating System
Virtual Environment
Current image version: '20200525.2'
Agent running as: 'vsts'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: AzureKeyVault (1.169.1)
Downloading task: UsePythonVersion (0.151.3)
Downloading task: CmdLine (2.164.1)
Downloading task: UseDotNet (2.169.1)
Downloading task: CodeSignValidationInjected (1.113.0)
Checking job knob settings.
   Knob: AgentToolsDirectory = /opt/hostedtoolcache Source: ${AGENT_TOOLSDIRECTORY} 
   Knob: AgentPerflog = /home/vsts/perflog Source: ${VSTS_AGENT_PERFLOG} 
Finished checking job knob settings.
Start tracking orphan processes.
```

Dotnet SDK Version: 3.0.100

**Comment by rainersigwald** [comment]
@rebecca-makar are you still seeing this? Did the version of the `dotnet` command change in between?

**Comment by rebecca-makar** [comment]
@rainersigwald should have closed this once you helped via teams and azure devops. I had to add an empty `Directory.Build.rsp`

Thanks again.
