### ISSUE TITLE
XPlat AssignCulture task incorrectly categorizes some EmbeddedResources as culture-specific

### ISSUE THREAD

**Issue by mellinoe** [Microsoft/msbuild#541]
We've noticed that some of the embedded resources in some of our tests in corefx are not being passed through to csc.exe. This led me to discover that MSBuild was categorizing EmbeddedResource's as culture-specific if they had any period in their file name. In theory, this task is supposed to be splitting the last part of the filename, and then determining if that part is equal to some culture string, i.e. `MyAssembly.en-us.dll` -> `en.us` -> valid culture. However, it seems to be accepting any string as a valid culture. In our case, we have an EmbeddedResource named `Interop.Mock01.dll`. MSBuild is assigning the culture "Mock01" to this assembly, even though that is clearly an invalid culture.

I'm pretty sure the issue is due do differences in code in Culture.cs, line 74. 
````CSharp
if ((cultureName != null) && (cultureName.Length > 1))
                {
                    // ... strip the "." to make "en-US"
                    cultureName = cultureName.Substring(1);
                    validCulture = CultureInfoCache.IsValidCultureString(cultureName);
                }
````
This is different from the desktop code:
````CSharp
        if (text != null && text.Length > 1)
        {
            // ... strip the "." to make "en-US"
                    cultureName = cultureName.Substring(1);
                    validCulture = CultureStringUtilities.IsValidCultureString(cultureName);
        }
````
I'm pretty sure this is causing us to consider culture strings that are actually invalid (i.e. "Mock01" and "Impl") as valid. I haven't analyzed all of the code paths this stuff goes through, but it seems very likely, especially given how much code is #if'd in CultureInfoCache.cs.

**Comment by AndyGerlicher** [comment]
Can you try with package version 00022? I believe that the change #504 that @cdmihai made recently should address this. We used to just do `new CultureInfo(culture)` but that like you mentioned will accept any string in .NET Core. We now have a hard coded list to make it behave more like the desktop version.

**Comment by mellinoe** [comment]
It sounds like that will definitely fix this issue. When I was looking through the code I did notice that it had been changed semi-recently, but I wasn't aware of how old the version we are using in corefx was. We're planning on moving to version 00022 soon, so once we do that I will verify that this issue is fixed.

**Comment by mellinoe** [comment]
@AndyGerlicher We updated to version 00022 and it seems to have fixed the issue. Thanks!
