### ISSUE TITLE
Wildcards expansion is silenty skipped when the pattern comes from a complex expression

### ISSUE THREAD

**Issue by yotauber** [microsoft/msbuild#5418]
### Steps to reproduce

Programmatically generate a file pattern that contains a wildcard and try to create an item list from it. Compare the results to a hard-coded pattern, or a pattern that comes directly from a property.

Project file
```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" DefaultTargets="MyTarget">
	<PropertyGroup>
		<MyPattern>*.txt</MyPattern>
	</PropertyGroup>
	
	<ItemGroup>
		<GenItem1 Include="*.txt" />
		<GenItem2 Include="$(MyPattern)" />
		<GenItem3 Include="$(MyPattern.Replace('this does', 'nothing'))" />
	</ItemGroup>
	
	<Target Name="MyTarget">
		<Message Text="Direct wildcard: @(GenItem1)" />
		<Message Text="Via property: @(GenItem2)" />
		<Message Text="Via complex expression: @(GenItem3)" />
	</Target>
</Project>
```

Directory contents:
```
/
- a.txt
- b.txt
```

Command line
```
msbuild my.proj
```
### Expected behavior
Wildcards should be expanded according to the final value of the expression, even if it is a complex expression. Output should be:
```
Direct wildcard: a.txt;b.txt
Via property: a.txt;b.txt
Via complex expression: a.txt;b.txt
```

### Actual behavior
When the pattern is generated by some expression, wildcards are not expanded. Output is:
```
Direct wildcard: a.txt;b.txt
Via property: a.txt;b.txt
Via complex expression: *.txt
```

### Environment data
`msbuild /version` output: 16.4.0.56107

OS info: Microsoft Windows [Version 10.0.18363.836]

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc): CMD

**Comment by rainersigwald** [comment]
This because [the result of property functions is an escaped string](https://docs.microsoft.com/visualstudio/msbuild/property-functions). If you want to unescape it, you can use the property function `$([MSBuild]::Unescape())`.
