### ISSUE TITLE
The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.

### ISSUE THREAD

**Issue by sunny868** [microsoft/msbuild#5419]
## Steps to reproduce
`shell
git clone https://github.com/Microsoft/msbuild.git
git checkout v16.4.0.56107
./build.sh --configration Debug /p:DisableCrossgen=true /p:PortableBuild=true /p:SkipTests=true

cp artifacts/bin/MSBuild/Debug/netcoreapp2.1/MSBuild.dll  /tmp/dotnet-sdk-3.0.100-preview7-012821-linux-x64/sdk/3.0.100-preview7-012821/.

cd /tmp/otnet-sdk-3.0.100-preview7-012821-linux-x64
./dotnet new console -o test
`
## Expected behavior
create test project successfully.

## Actual behavior
there is a error:
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.0.0-preview7-27912-14 at [/home/loongson/sunguoyun/dotnet-sdk-3.0.100-preview7-012821-linux-x64/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

## Environment data

.netcore SDK version output:
3.0.100-preview7-012821
OS info:
Linux fool-OptiPlex-7060 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by sunny868** [comment]
## My Question is :
How to build MSBuild to match SDK version  3.0.100-preview7-012821 ?

**Comment by rainersigwald** [comment]
There's no trivial way to do this, unfortunately. MSBuild is built as a .NET Core 2.1 application, but the .NET Core SDK deploys it as a .NET Core 3.0 application (in the 3.0 SDK), which updates some metadata in the `.deps.json` file indicating that `MSBuild.dll` can be run on the current runtime.

Are you really updating only `MSBuild.dll`? That won't get you a valid set of binaries; you need to update all of the MSBuild assemblies.

Can you clarify what you're trying to accomplish here, by updating an old preview SDK with a private build of an old MSBuild?

**Comment by sunny868** [comment]
Net core SDK 3.0 msbuild.dll is architecture related (PE32 +), can't run on MIPS platform . so  I plan to recompile msbuild as platform independent code (maybe PE32).
Actually ,I copied artifacts/bin/MSBuild/Debug/netcoreapp2.1/*  to sdk_3.0_path  and update .json file . Then "dotnet new " run normally.
