### ISSUE TITLE
Binary logging file size expectation

### ISSUE THREAD

**Issue by michael-baker** [microsoft/msbuild#5432]
### Steps to reproduce

The documentation for binary logging sells the technology as smaller, faster and more better than text logging. My experience is the binary logs grow into the hundreds of megabytes. 

My build typically contains about 900+ projects. The project sequencing is controlled by my own graph build. This tool predates the MSBuild work in this area and I have a custom build cache/accelerator (predates the BuildXL, Bazel releases etc). 

My question is should 900 projects emit a 538 MB binlog?

I notice these variables are present - I'm assuming these options are set internally when the binlog is enabled.

MSBUILDLOGIMPORTS = 1
MSBUILDTARGETOUTPUTLOGGING = true

Command line
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe /nologo /bl:C:\B\448\1\s\build.binlog /clp:FORCENOALIGN=true /flp:Verbosity=Normal /m:4  /target:BuildAndPackage C:\B\448\1\s\_BUILD_1110301\Src\Build\ComboBuild.targets
```

My problem is I cannot upload the binlog at the end of a build to the CI server (TFS) due to the large size at the number of builds per day.

The text log which is just the TFS build agent console slurp - not the MSBuild file logger is around 13 MB zipped - but obviously with less fidelity.

### Environment data
```
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

15.9.21.664
```

**Comment by KirillOsenkov** [comment]
What you're seeing is currently expected. We're working on reducing binlog size and you can see a summary of this planned work here:
https://github.com/KirillOsenkov/MSBuildStructuredLog/wiki/BinLog-Perf

Binlog philosophy was always to log as much as possible to enable best possible diagnostics. The price for that is what you're seeing. There are a few knobs you can tweak to reduce the size and various associated tradeoffs.

538 MB for 900 projects is roughly what I would expect. If you "play back" the binlog into a text log using `msbuild msbuild.binlog /flp:v=diag /noconlog` it will probably expand to ~10-20 GB of raw text.

**Comment by michael-baker** [comment]
Fantastic info - thank you.
