### ISSUE TITLE
AssignLinkMetadata is missing in xplat Microsoft.Tasks.Core

### ISSUE THREAD

**Issue by agocke** [Microsoft/msbuild#544]

**Comment by AndyGerlicher** [comment]
We haven't for whatever reason converted this to .NET Core yet. Looking quickly at the code I think it should be pretty straightforward. Is this blocking anything for you (to help with priority)?

**Comment by agocke** [comment]
@AndyGerlicher We don't have anything depending on it, but it did force me to remove the reference in the Microsoft.Common.CurrentVersion.targets file. If you remove the reference yourself until it's implemented I don't think it require any fixups on our side.
