### ISSUE TITLE
Close Older Milestones

### ISSUE THREAD

**Issue by shaggygi** [microsoft/msbuild#5449]
Could the following milestones be closed now they are completed/outdated?

[MSBuild 16.6 Preview 2](https://github.com/microsoft/msbuild/milestone/39)
[MSBuild 16.6 Preview 3](https://github.com/microsoft/msbuild/milestone/41)
[MSBuild 16.6](https://github.com/microsoft/msbuild/milestone/33) (21 issues remaining)
[MSBuild 16.7 Preview 1](https://github.com/microsoft/msbuild/milestone/42)
[MSBuild 16.7 Preview 2](https://github.com/microsoft/msbuild/milestone/43) (2 issues remaining)

**Comment by rainersigwald** [comment]
Yup, thanks.
