### ISSUE TITLE
[Static Graph] Transitive project references that are directly used fail with `/graph` 

### ISSUE THREAD

**Issue by kassemsandarusi** [microsoft/msbuild#5456]
The details are below. I get the sense this might be intended based on some of the documentation for the static graph feature. However, it's not obvious from the error thrown nor is it obvious from the public documentation (like the CLI -help) on the graph flag.

### Steps to reproduce

1. Have three projects, A,B,C
2. Add project reference from A -> B
3. Add project reference from B -> C
4. Add direct call into C from A.
5. msbuild.exe /t:build /graph A.csproj

### Expected behavior

Successfully compiles or throws error indicating code directly used cannot be indirectly referenced.

### Actual behavior

`The type or namespace name 'C' could not be found (are you missing a using directive or an assembly reference?) [C:\...]`

### Environment data
`msbuild /version` output: `16.5.0.12403`

**Comment by cdmihai** [comment]
Support for transitive references added in #5326
Works with msbuild version 16.7.0.30801
