### ISSUE TITLE
[Windows ARM64] BinaryFormatter decode warnings when building dotnet projects

### ISSUE THREAD

**Issue by eiriktsarpalis** [microsoft/msbuild#5474]
I'm seeing this issue pretty consistently using the arm64 build of dotnet sdk, across a variety of projects. It tends to correlate with other problems like builds hanging randomly. 

### Steps to reproduce

Using the latest .NET 5.0 preview SDK:

```powershell
> .\dotnet-install.ps1 -Architecture arm64 -Version 5.0.100-preview.6.20318.15
> dotnet new xunit
> dotnet build # no warnings
> dotnet build # produces a warning
```

### Expected behavior

Should build without warnings..

### Actual behavior

Produces the warning:
```
C:\Users\eitsarpa\AppData\Local\Microsoft\dotnet\sdk\5.0.100-preview.6.20318.15\Microsoft.Common.CurrentVersion.targets(2084,5): warning MSB3088: Could not read state file "obj\Debug\net5.0\msbuild-repro.csprojAssemblyReference.cache". Invalid BinaryFormatter stream. [C:\Users\eitsarpa\devel\tests\msbuild-repro\msbuild-repro.csproj]
```

### Environment data

`dotnet msbuild /version` output: 16.7.0.31007
OS info: Windows 10 build 18363 on Surface Pro X

**Comment by rainersigwald** [comment]
Possibly related: we may change the format of this file on disk away from BinaryFormatter for #5247. But if there are bigger problems with `BinaryFormatter` on ARM64, that could impact our IPC as well as this particular warning.

**Comment by ladipro** [comment]
Closing in favor of the runtime bug causing this: https://github.com/dotnet/runtime/issues/39701

We are failing to read the RAR on-disk data because it contains a `Hashtable` which internally uses `ConditionalWeakTable<>` during its deserialization and `ConditionalWeakTable<>` in turn uses dependent handles which have an implementation issue on this platform.
