### ISSUE TITLE
"System.MissingMethodException: Method not found" when building with msbuild

### ISSUE THREAD

**Issue by FelixLamontagne** [microsoft/msbuild#5479]
### Environment data
`msbuild /version` output:
```
C:\.conan\f93b45\1>msbuild /version
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.6.0.22303
```

OS info: Microsoft Windows [Version 6.3.9600]

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):
We use fastbuild and jenkins. I'm not sure about the versions so if asked i'll search for them. When building the c# projects it's just a cmd line that invokes MSBuild.

### Description of the problem

I'm currently in the process of updating our build tools from v141 to v142, but i'm having problems on our build machine. On my machine it works (haha), but when trying to build on the build machine it doesn't. According to what I have found it seems to be a problem with old dlls laying around, but I have no idea what to do next. c# isn't my main language so i'm having a hard time with this problem.

In our repository we have c++ projects (which are the main projects) and then we have a couple of c# projects that are not building successfully since the build tools update. For the c++ projects we use fastbuild as a build system, but I think that for the c# projets it's only msbuild that we use (fastbuild does generate the project files for the c# projects though).

The build tools are in a conan package and they are a fresh install with this command : 
```
vs_BuildTools.exe  --installPath "Dir" --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.VC.CLI.Support --addProductLang En-us
```
I was thinking that maybe there is something missing in this installation? But then why would it work in my environment 🤔Could I have global stuff in my environment that MSBuild would find and use (for example gac)? 

I looked at other similar issues to try to resolve my problems but I couldn't manage to apply it to my project. Here are two of the issues that I looked at #4382 and #4286. I have attached files that were asked in those issues to save time if we need them here too.

[msbuild_versions.txt](https://github.com/microsoft/msbuild/files/4865225/msbuild_versions.txt) Output of EnumerateMSBuild.ps1
[output_build.txt](https://github.com/microsoft/msbuild/files/4865223/output_build.txt) Output when trying to build a c# project
[output_gacutil.txt](https://github.com/microsoft/msbuild/files/4865224/output_gacutil.txt) Output of gacutil /l

Complete error that is outputted (it's also at the bottom of output_build.txt)
```
  C:\.conan\f93b45\1\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1630,5): error MSB4018: The "MSBuild" task failed unexpectedly. [C:\workspace\APT-1-Update-build-tools-to-v142\src\monorepo\project\msvc12\VirtualHandheld\VirtualHandheld.csproj]
C:\.conan\f93b45\1\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1630,5): error MSB4018: System.MissingMethodException: Method not found: 'Void System.Collections.Generic.HashSet`1..ctor(Int32)'. [C:\workspace\APT-1-Update-build-tools-to-v142\src\monorepo\project\msvc12\VirtualHandheld\VirtualHandheld.csproj]
C:\.conan\f93b45\1\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1630,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.GetUndeclaredProjects(MSBuild msbuildTask) [C:\workspace\APT-1-Update-build-tools-to-v142\src\monorepo\project\msvc12\VirtualHandheld\VirtualHandheld.csproj]
C:\.conan\f93b45\1\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1630,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [C:\workspace\APT-1-Update-build-tools-to-v142\src\monorepo\project\msvc12\VirtualHandheld\VirtualHandheld.csproj]
```

**Comment by rainersigwald** [comment]
We don't officially support Conan. But maybe I can help anyway.

It looks like that method was added in .NET 4.7.2: https://apisof.net/catalog/System.Collections.Generic.HashSet%3CT%3E..ctor(Int32)

Do you have .NET 4.7.2 or 4.8 installed on the machine?

**Comment by FelixLamontagne** [comment]
@rainersigwald 
I think this was the problem, thank you so much! 

I went in remote desktop to manually install dotnet 4.8 so before confirming that this is resolved i'll update our build machine image with the correct dotnet version, complete the whole build process and then come back here in a couple of days to close the issue if it's resolved or further update you if it's not. Thanks again for the help, very appreciated!

**Comment by FelixLamontagne** [comment]
Updating dotnet to 4.8 resolved the problem.
