### ISSUE TITLE
Question: How can I create a "soft dependency" between 2 projects

### ISSUE THREAD

**Issue by TFTomSun** [microsoft/msbuild#5482]
Let's assume I have project A and project B. They have different incompatible TargetFrameworks, but the build of A depends on the build of B. I want to keep the delta compile compatibility, too.  That means:

- no changes to both projects -> no build
- change in B -> Build of A triggers build of B first, then builds A
- change in A -> Only A builds

Is there a common approach to achieve that for all kind of SDK-style projects?

**Comment by xerif** [comment]
You can set project A to be dependent on B, without actually referencing B, using `ProjectReference` with:
- `ReferenceOutputAssembly` set to **false**
- `SkipGetTargetFrameworkProperties` set to **true**

_This is loosely based on https://github.com/microsoft/msbuild/issues/3843_

```xml
<!-- ProjectA.csproj -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net20</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProjectB\ProjectB.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <SkipGetTargetFrameworkProperties>true</SkipGetTargetFrameworkProperties>
    </ProjectReference>
  </ItemGroup>
</Project>
```
```xml
<!-- ProjectB.csproj -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
</Project>
```

This appears to fit your requirements, so:
- projects are incompatible (`net20` cannot reference `netstandard2.1`)
- when changing something in A:
   - and building A => only A builds
   - and building B => nothing builds
- when changing something in B:
   - and building A => only **B** builds (nothing changed in A, so A doesn't)
   - and building B => only B builds

**Comment by TFTomSun** [comment]
@xerif  thanks alot! SkipGetTargetFrameworkProperties was the property I didn't know before.

**Comment by rainersigwald** [comment]
Thanks @xerif! Closing this as that was a great answer.
