### ISSUE TITLE
RoslynCodeTaskFactory: The task factory "CodeTaskFactory" could not be loaded from the assembly

### ISSUE THREAD

**Issue by Legends** [microsoft/msbuild#5487]
### Steps to reproduce

VS2019 
win10
.net core console project v3.1
dotnet --version: 3.1.400-preview-015178

> error MSB4175: **The task factory "CodeTaskFactory" could not be loaded from the assembly** "C:\Users\xx\.nuget\packages\roslyncodetaskfactory\1.2.6\build\netstandard1.5\RoslynCodeTaskFactory.dll". **Method not found**: 'System.Xml.XmlNodeType System.Xml.Linq.XObject.get_NodeType()'.

Project file
```xml
<UsingTask
    TaskName="CustumCodeTask"
    TaskFactory="CodeTaskFactory"
    AssemblyFile="$(RoslynCodeTaskFactory)"
    Condition=" '$(RoslynCodeTaskFactory)' != '' ">
    <ParameterGroup />
    <Task>
      <Reference Include="System.Xml" />
      <Using Namespace="System" />
      <Using Namespace="System.Collections.Generic" />
      <Using Namespace="System.Xml" />
      <Using Namespace="System.Xml.Linq" />
      <Code Type="Fragment" Language="cs">
        <![CDATA[
			<!--public static void ScriptMain() {-->
				List<string> list = new List<string>();
				list.Add("Happy");
				list.Add("New");
				list.Add("Year");
				Console.WriteLine("Hello MSBuild Community Scripting World.");
				foreach(string s in list)
				{
				  Console.WriteLine(s);
				}
			<!--}-->
			]]>
      </Code>
    </Task>
  </UsingTask>
```
 
Command line
```
dotnet msbuild -v:d -t:CustumCodeTask
```
### Expected behavior

see the messages
### Actual behavior

> error MSB4175: **The task factory "CodeTaskFactory" could not be loaded from the assembly** "C:\Users\xx\.nuget\packages\roslyncodetaskfactory\1.2.6\build\netstandard1.5\RoslynCodeTaskFactory.dll". **Method not found**: 'System.Xml.XmlNodeType System.Xml.Linq.XObject.get_NodeType()'.

### Environment data
`msbuild /version` output:
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Framework
> 16.6.0.22303

OS info:
win 10 x64
If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):

dev console for VS2019
win10
.net core console project v3.1 (VS2019)
dotnet --version: 3.1.400-preview-015178

**Comment by jeffkl** [comment]
The RoslynCodeTaskFactory that you're using is technically from here: https://github.com/jeffkl/RoslynCodeTaskFactory/

I've since built it into MSBuild so you don't need to reference it as a package.  

I think you just need to change the name of the task factory to RoslynCodeTaskFactory.  The below sample works great:

```xml
<Project>
  <UsingTask
    TaskName="CustumCodeTask"
    TaskFactory="RoslynCodeTaskFactory"
    AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll">
    <ParameterGroup />
    <Task>
      <Using Namespace="System" />
      <Using Namespace="System.Collections.Generic" />
      <Using Namespace="System.Xml" />
      <Using Namespace="System.Xml.Linq" />
      <Code Type="Fragment" Language="cs">
        <![CDATA[
				List<string> list = new List<string>();
				list.Add("Happy");
				list.Add("New");
				list.Add("Year");
				Console.WriteLine("Hello MSBuild Community Scripting World.");
				foreach(string s in list)
				{
				  Console.WriteLine(s);
				}
			]]>
      </Code>
    </Task>
  </UsingTask>

  <Target Name="Build">
    <CustumCodeTask />
  </Target>
</Project>
```

```
D:\Stuff>msbuild roslyncodetaskfactory.proj
Microsoft (R) Build Engine version 16.7.0-preview-20330-08+96403c598 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 7/6/2020 9:24:17 AM.
Hello MSBuild Community Scripting World.
Happy
New
Year

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.73
```

**Comment by Legends** [comment]
Thanks for your response.

I've replicated your build file from above, but I get:

> C:\Program Files\dotnet\sdk\**3.1.400-preview-015178**\**Microsoft.Common.CurrentVersion.targets**(2799,7): error MSB4057: The target "**CreateManifestResourceNames**" does not exist in the project

Command is:
`dotnet msbuild build.xml -v:d -t:build`

**Comment by jeffkl** [comment]
Hmm its working fine for me:
```
D:\Stuff>C:\Users\jeffkl\Downloads\dotnet-sdk-latest-win-x64\dotnet.exe --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.400-preview-015203
 Commit:    b1dcd32553

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\jeffkl\Downloads\dotnet-sdk-latest-win-x64\sdk\3.1.400-preview-015203\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.400-preview-015203 [C:\Users\jeffkl\Downloads\dotnet-sdk-latest-win-x64\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [C:\Users\jeffkl\Downloads\dotnet-sdk-latest-win-x64\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Users\jeffkl\Downloads\dotnet-sdk-latest-win-x64\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Users\jeffkl\Downloads\dotnet-sdk-latest-win-x64\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

D:\Stuff>C:\Users\jeffkl\Downloads\dotnet-sdk-latest-win-x64\dotnet.exe build roslyncodetaskfactory.proj
Microsoft (R) Build Engine version 16.7.0-preview-20330-08+96403c598 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

Hello MSBuild Community Scripting World.
Happy
New
Year

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.81
```

What else does your project have?

**Comment by Legends** [comment]
It contains a `Program.cs` and a T4 TextTemplate file `VersionIncreaser.tt`.

One thing my build file also contains is this:

```
<PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
```

**Comment by Legends** [comment]
My directory structure:

I've put the build.xml into the solution folder and a copy into the project folder:

```
build.xml
ConsoleApp.sln
  -ConsoleApp:
			  	Program.cs
			    build.xml
```

When I execute the `build.xml` from the solution folder I get:

> build.xml" (build target) (1) ->
>        (ResolvePackageAssets target) ->
>          C:\Program Files\dotnet\sdk\3.1.400-preview-015178\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(240,5): error NETSDK1004: Assets file 'D:\SystemFolders\Downloads\ConsoleAppCrap\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. [D:\SystemFolders\Downloads\ConsoleAppCrap\build.xml]

When I execute the `build.xml` from the project dir I get:

> build.xml" (build target) (1) ->
>          C:\Program Files\dotnet\sdk\3.1.400-preview-015178\Microsoft.Common.CurrentVersion.targets(2799,7): error MSB4057: The target "CreateManifestResourceNames" does not exist in the project. [D:\SystemFolders\Downloads\ConsoleAppCrap\ConsoleAppCrap\build.xml]

**Comment by Legends** [comment]
Ok, using `NoTargets` with specified `version` works:

`<Project Sdk="Microsoft.Build.NoTargets/1.0.110" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">`

**Official MsBuild SDKs:**

- Microsoft.Build.Traversal
- Microsoft.Build.CentralPackageVersions
- Microsoft.Build.NoTargets
- Microsoft.Build.Artifacts

**Default SDKs, project related:**

Microsoft.NET.Sdk	The .NET Core SDK	https://github.com/dotnet/sdk
Microsoft.NET.Sdk.Web	The .NET Core Web SDK	https://github.com/aspnet/websdk
Microsoft.NET.Sdk.Razor	The .NET Core Razor SDK	
Microsoft.NET.Sdk.Worker	The .NET Core Worker Service SDK	
Microsoft.NET.Sdk.WindowsDesktop

**Comment by Legends** [comment]
Ok, it works when I use:

```
"sdk": {
    "version": "3.1.301"
  }
```
