### ISSUE TITLE
Using 'var' to deduce type with a string constant causes type to be deduced as a nullable string

### ISSUE THREAD

**Issue by firedraco** [microsoft/msbuild#5491]
### Steps to reproduce
With `<Nullable>enabled</Nullable>` in the csproj file, use var to deduce the type of a variable assigned with a string constant. By highlighting the type, looking at Intellisense results, or building the project, you can see that the deduced type is of 'string?'.

```
var str = "value"; // str is of type 'string?'
```

On earlier versions of Visual Studio (Like 16.4.x), the type was deduced as 'string'. This resulted in some discrepancies in behavior and created additional warnings in the code that were not present before.

### Expected behavior
The deduced type of str would be 'string'

### Actual behavior
On 16.4.3: The type of str is 'string'
On 16.6.1, 16.6.3: The type of str is 'string?'

### Environment data

Used Visual Studio 16.6.1 or 16.6.3 to compile on Windows 10 (64bit)

### Project demonstrating issue
[TestApp.zip](https://github.com/microsoft/msbuild/files/4886421/TestApp.zip)

**Comment by rainersigwald** [comment]
This issue was moved to dotnet/roslyn#45787

**Comment by firedraco** [comment]
Thanks for moving this to the correct spot!
