### ISSUE TITLE
File paths need better support on Unix

### ISSUE THREAD

**Issue by david-mitchell** [Microsoft/msbuild#55]
Because most project files assume that the directory path delimiter is a `\`, MSBuild contains a `FileUtilities.FixFilePath` method that is used by many tasks to ensure that paths are properly constructed when running on Unix systems.

However, some projects contain references to custom tasks that deal with file paths but do not have access to this method. (see, for example, the [DownloadFile](https://github.com/dotnet/coreclr/blob/82440897d45e16d706e80dc96918d362339d0d95/dir.targets#L4-22) task in coreclr)

After [some discussion](https://gitter.im/dotnet/coreclr?at=5517850d2278254a76090d89) in the coreclr chat room, it was proposed that this functionality might be best exposed as a [Property Function](https://msdn.microsoft.com/en-us/library/dd633440.aspx).

Such a property function would most likely need to be a member of the `MSBuild` set of property functions, which are defined in [`IntrinsicFunctions`](https://github.com/Microsoft/msbuild/blob/master/src/XMakeBuildEngine/Evaluation/IntrinsicFunctions.cs). It would also need a name--`FixFilePath` might be acceptable, but I suspect that a more descriptive name would be desired.

I would be happy to submit a Pull Request if a member of the team signs off on this issue (and we agree on a name for the function)

**Comment by AndyGerlicher** [comment]
MSBuild team triage: Sounds good. How about ToFilePath for the function name? David feel free to assign this to yourself.

**Comment by david-mitchell** [comment]
I'd love to take it, but I don't have permission to assign issues in this project.
