### ISSUE TITLE
Intermittent CI Failure: TimeoutFailsEvenWhenExitCodeIsIgnored

### ISSUE THREAD

**Issue by BenVillalobos** [microsoft/msbuild#5510]
Build #20200710.12 had test failures
5 errors / 0 warnings

Microsoft.Build.UnitTests.Exec_Tests.TimeoutFailsEvenWhenExitCodeIsIgnored
Assert.Equal() Failure\nExpected: 143\nActual:   259

**Comment by rainersigwald** [comment]
Duplicate of #5506
