### ISSUE TITLE
Possible compiler bug, I need your advice.

### ISSUE THREAD

**Issue by sebas77** [microsoft/msbuild#5512]
Hi,

The only way to report this issue is to upload the project, as the structure of the project, and not just the code, affects the outcome. However, I would like to show you what leads me to think it's a compiler bug before to proceed further. 

![image](https://user-images.githubusercontent.com/945379/87456739-45680a00-c5ff-11ea-91f4-bc318d4f40ec.png)
![image](https://user-images.githubusercontent.com/945379/87456755-4ac55480-c5ff-11ea-84e7-783b471f350f.png)

If my assumptions about how the compiler works are right, this looks to me like a paradox.  QuickSaveEngine.cs cannot be compiled if LocalInputEntityStruct is not compiled first and LocalInputEntityStruct cannot be compiled if it's nullable, right? The struct itself is 100% unmanaged and doesn't have nullable fields, but since it's a complex struct, the implementation of the interface with unmanaged constraint is my way to prove it. If you agree that there is something fishy, please let me know if and how I should proceed. Note: the same code compiles if I don't use separate assemblies.

OS info:

Windows 10, MSBuild 2017 (c# 7.3)

**Comment by rainersigwald** [comment]
This issue was moved to dotnet/roslyn#46003
