### ISSUE TITLE
<Assets> and CopyToOutputDirectory not respected

### ISSUE THREAD

**Issue by ericnewton76** [microsoft/msbuild#553]
Since we have front-end javascript developers that dont use Visual Studio, we frequently are missing neccesary files from a build/deploy and the csproj is frequently referencing files that have been renamed/moved around etc.

Under ItemGroup, theres an Assets element that supports wildcard inclusion of a directory tree, and displays correctly in VisualStudio2013 (only one I've seen so far) but MSBuild apparently doesnt see these nodes, and none of the assets displayed in Visual Studio are included in a build/deploy.

This needs to be added to the core MSBuild (and back ported to prior versions, at least v12)

This feels like an easy fix depending on how MSBuild enumerates files, and whether that enumeration process is hard coded to only bother looking at <Content> elements or whether the enumeration first builds up a list/array of files to be processed.

**Comment by rainersigwald** [comment]
`Assets` is not an item that MSBuild's common targets do anything with. Visual Studio usually displays all items, regardless of what the build process will do with them, but the build process should be treated as canonical.
