### ISSUE TITLE
Versioning scheme for package, assembly, and file versions

### ISSUE THREAD

**Issue by cdmihai** [Microsoft/msbuild#557]
On xplat, we use different version numbers for packages (e.g. 0.1.0-preview-00022-160326), and assemblies and file versions (e.g. 14.1.0.0).

We should come up with a consistent story where we use one common set of version number seeds to generate package versions, assembly versions, and file versions. We should also define what is the version number relationship between multiple targeted platforms (#556)

**Comment by jeffkl** [comment]
# Proposal
Build numbers will be defined with major.minor[-tag] in the `version.json`.  The build number will remain as `0` while the build definition's build number will be appended to the tag.  The build definition's build number is currently set to `$(Date:yyyyDDmm)(Rev:.r)` which generates build numbers like `20160918.1`.  Local builds will use a build number with the revision being zero, such as `20161017.0`.

# Example
version.json
``` json
{
  "version": "15.1-preview",
  "publicReleaseRefSpec": [
    "^refs/heads/master$",
    "^refs/heads/xplat$"
  ]
}
```
* Major version: `15`
* Minor version: `1`
* Prerelease tag `-preview`

Build number from official build
`20161017.01`

The resulting NuGet package version would be `15.1.0-preview-20161017-01`.  If we did multiple builds in a single day, the revision would increment giving is the ability to publish 99 packages per day.

# Required changes
1. The build definition will need to be updated to include 2 digits of the revision.  If it's left at 1, we can only publish 9 packages per day.
2. Update `version.json` with the correct prerelease tag
3. Add target to `CreateNuGetPackages.proj` like this:
``` xml
<Target Name="GetNuGetPackageVersionEx" DependsOnTargets="GetNuGetPackageVersion">
  <!--
    This target is used to customize the versions generated by NerdBank.GitVersioning.  The $(PrereleaseVersion) is read from version.json and
    then then the date and build number is appended.
  -->
  <PropertyGroup>
    <BuildNumber>0</BuildNumber>
      
    <!-- Local builds count as the zero-th build of the day -->
    <PrereleaseVersion Condition="'$(PrereleaseVersion)' != '' And '$(BUILD_NUMBER)' == ''">$(PrereleaseVersion)-$([System.DateTime]::Today.ToString('yyyyMMdd'))-00</PrereleaseVersion>
      
    <!-- Offical builds provide the BUILD_NUMBER variable which we'll use -->
    <PrereleaseVersion Condition="'$(PrereleaseVersion)' != '' And '$(BUILD_NUMBER)' != ''">$(PrereleaseVersion)-$(BUILD_NUMBER.Replace('.', '-'))</PrereleaseVersion>
      
    <!-- Override the NuGet package version provided by Nerdbank.GitVersioning -->
    <NuGetPackageVersion>$(MajorMinorVersion).$(BuildNumber)$(PrereleaseVersion)</NuGetPackageVersion>
  </PropertyGroup>
</Target>
```

Let me know what you think @cdmihai, @AndyGerlicher, and @rainersigwald

**Comment by rainersigwald** [comment]
99/day should be enough for anyone! /ducks

This sounds fine. Do we need NerdBank.GitVersioning any more? I guess it still gives us commit ID version stamping into the binaries--but anything else?

**Comment by jeffkl** [comment]
Yes, the commit ID is more important for the assembly versions.  My proposal doesn't cover that yet, I think I need to have a quick discussion on what we want there.

I don't think we need it personally.  The CLI runs a git.exe command to get the commit height which we could use.

**Comment by cdmihai** [comment]
Looks good.

Questions:
- We won't publish separate nuget packages for desktop / xplat / mono? build flavors right? Both desktop and xplat dlls ship together in the same nuget package (and in future mono?). Asking because otherwise this scheme would lead to version conflicts.
- Watch out for the nuget version length limitation of 20 characters. [The limitation got taken out today.](https://github.com/NuGet/Home/issues/2735) but it may take some time to propagate to our repo.

**Comment by jeffkl** [comment]
> We won't publish separate nuget packages for desktop / xplat / mono? build flavors right?

We technically published packages out of master and xplat but they have different versioning schemes.  Packages out of master are `0.1.0` and will go away soon.

> Watch out for the nuget version length limitation of 20 characters.

I did take this into account, we'll need to be careful of the prerelease tag we use.  `Preview` is nice and short and works well, but something like `prerelease` gets us closer to the limit.

**Comment by rainersigwald** [comment]
So I followed Mihai's link and wandered into a discovery that apparently SemVer 2.0 suggests [using dots instead of hyphens in the pre-release identifiers](http://semver.org/#spec-item-9), suggesting that `15.1.0-preview.20161017.01` is preferable to `15.1.0-preview-20161017-01`.

I don't care about SemVer whatsoever but it might be better to go with the flow. Though the hyphenated world you're proposing matches more closely with what corefx and friends are doing. So maybe ignore this whole thing 😥

**Comment by jeffkl** [comment]
> Apparently SemVer 2.0 suggests using dots instead of hyphens in the pre-release identifiers

I didn't read it as suggesting one way or the other but that's still interesting to know.  I think we're better off sticking with the schema we've seen other teams at MS use.  The tag will go away when we release anyway, so I'm not sure if it really matters.

**Comment by jeffkl** [comment]
Per Andy, I'm switching to using the git commit height.
