### ISSUE TITLE
Move MSBuild out of the GAC / Registry

### ISSUE THREAD

**Issue by AndyGerlicher** [Microsoft/msbuild#558]
See [Visual Studio “15”: Installing Just What You Need](https://blogs.msdn.microsoft.com/visualstudio/2016/04/05/visual-studio-15-installing-just-what-you-need/) for context since this relates to the new install experience.

We're in the process of experimenting with shipping MSBuild 1) built directly from the GitHub sources (no internal mirror!) and 2) outside of the registry / GAC. This means we would ship under the Visual Studio installation folder and not install to `C:\Program Files (x86)\MSBuild`. This isn't set in stone at this point, but I wanted to create this Issue to track progress and get feedback.

**Comment by jeffkl** [comment]
Should we close this?

**Comment by rainersigwald** [comment]
Yup, this is done as of VS2017 Preview 5 (with the new VS installer).

**Comment by rseanhall** [comment]
The WiX toolset has a tool called `heat` that uses MSBuild API's to "harvest" the outputs of a project into the installer. It requires that MSBuild is installed on the target machine, and loads the appropriate version of `Microsoft.Build.dll` and friends from the GAC based on the `ToolsVersion`. How are standalone executables supposed to find MSBuild 15 now that it's not installed in the registry or the GAC? Keep in mind that WiX may be installed on a build machine with only the build tools and not VS 2017.  https://github.com/wixtoolset/issues/issues/5490

**Comment by rainersigwald** [comment]
@rseanhall For VS2017 (including the Build Tools flavor), the right way to locate MSBuild is by using Visual Studio Setup Configuration. There are examples for [C++, C#, and VB](https://code.msdn.microsoft.com/Visual-Studio-Setup-0cedd331) and a newer [PowerShell wrapper](https://github.com/Microsoft/vssetup.powershell) that can help guide you. Note that a new wrinkle that you wouldn't have had to consider before is that there can be multiple Visual Studio and MSBuild installations side-by-side. Identifying the correct one can be difficult (maybe a user installed the C++ workload with their Professional edition install, but also has a Community install that doesn't have C++. It's hard to know from the outside that the project you're building needs the C++ install and query for it).

**Comment by SwooshyCueb** [comment]
This may not be the appropriate place to ask this, but if MSBuild's assemblies are no longer GAC'd, how can we ensure that custom MSBuild task assemblies pull in the latest versions of these assemblies present on the system?

**Comment by rainersigwald** [comment]
@SwooshyCueb When loaded as part of a build, the task will use the MSBuild assemblies that match the build's entry point--the entry point's binding redirects should ensure that that is the loaded version. Is that what you're asking?

**Comment by SwooshyCueb** [comment]
@rainersigwald I think so, thanks!
