### ISSUE TITLE
MSBuild running on coreclr

### ISSUE THREAD

**Issue by japj** [Microsoft/msbuild#58]
As per request from the coreclr people, moving over discussion to here from https://github.com/dotnet/coreclr/issues/497

What is needed for getting MSBuild running on coreclr?

**Comment by MattWhilden** [comment]
I presume that the Xplat work will also be the branch for "run on coreclr". I see the branch here: https://github.com/microsoft/msbuild/tree/xplat

What's the general status? Are there items that interested parties can tackle? Is a plan still being formulate? So many questions. :-)

**Comment by AndyGerlicher** [comment]
Ultimately we do want MSBuild to run on Core CLR, but we are not currently working on that. We would accept contributions towards this goal in the xplat branch.

**Comment by dsplaisted** [comment]
We are in the process porting MSBuild to .NET Core (see [this blog post](http://blogs.msdn.com/b/dotnet/archive/2015/09/03/msbuild-is-going-cross-platform-with-net-core.aspx)), but this work item isn't useful to track the work (it's too broad) so I'm closing it.
