### ISSUE TITLE
CustomBuild Command environment does not contain the result of a SetEnv even though Exec does

### ISSUE THREAD

**Issue by janitha09** [Microsoft/msbuild#582]
I have used CoApp to create a nuget package to package some code generators (binaries). I want to be able to use these code generators in a msbuild custombuild step to generate the code

I have a targets file that defines the following (using CoApp)
`<SetEnv Condition="'$(Platform.ToLower())' == 'x64' And '$(PlatformToolset.ToLower())' == 'v100' And ( $(Configuration.ToLower().IndexOf('debug')) == -1 )" Name="PATH" Prefix="true" Value="$(MSBuildThisFileDirectory)../..//build/native/bin/x64\v100\Release;">
  <Output TaskParameter="OutputEnvironmentVariable" PropertyName="PATH" />
</SetEnv>`

The targets file containing this snippet is imported like so into a project (vcxproj file)

`<Import Project="..\packages\habitat.id.redist.1.0.0.5\build\native\habitat.id.redist.targets`

within the project
`<Exec Command="echo %PATH%"/>`
returns the desired outcome i.e. that which takes the form
`../..//build/native/bin/x64\v100\Release;`
so I can call the executable that I want to run from the project. (except for unlike a custombuild command step there is no concept of outputs. So incremental builds will thence not work)

however 
`<CustomBuild Include="..\directory\filename">
  <FileType>Document</FileType>
  <Command Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
  echo $(PATH)
</Command>`
does not contain the path that I want that was set through the SetEnv.

There are unit tests that show the desired behavior for the Exec command though it uses/loads a custom assembly for setenvv.

For Exec it goes through the temporarybatchfile routine. What is the equivalent for the CustomBuild >  Command

The question has also been asked here [http://stackoverflow.com/questions/36489469/msbuild-14-0-visual-studio-2015-custombuild-command-environment-does-not-contain](url)

I would like to fix this issue but need help to know where the code is

**Comment by rainersigwald** [comment]
You're not finding the code here because the CustomBuild task is part of the C++ task assembly, not the core MSBuild package. The C++ team's code is still Microsoft-internal, and supported through the usual Microsoft mechanisms. But you might not need to go through them.

Do you really need to use CustomBuild? Can you just create a target that uses Exec?

You may also be able to avoid using environment variables at all by making your target take a full path and just setting it as an MSBuild property. You're already computing the path in MSBuild.

**Comment by janitha09** [comment]
I wanted to continue to use the custom build because it is exposed through the standard visual studio property sheet, a custom target is not (until you customize the property sheet hence introducing something that not everyone is familiar with and will forget to install and then complain) So I was hoping to get a product level solution that would come through the next product update. That looks unlikely

I was looking to continue to use the environment variable approach because that's the way CoApp does it for nuget package it creates for C++ binaries. It's easy enough to change the spec file. (Not using Coapp's Write-NugetPackage but use nuget pack instead)

Yes I will use the Target-Exec-Property combination because that looks like the next best option

Should I close this issue or will this be forwarded to the C++ team?
