### ISSUE TITLE
Path used for inline task reference is not honored

### ISSUE THREAD

**Issue by Sarabeth-Jaffe-Microsoft** [Microsoft/msbuild#594]
The path specified in a reference is respected during compilation, but not during execution. 

Repro Steps: Create an inline task, add a reference to a non-standard assembly and attempt to use it in a code fragment. 

This bug has also been reported on [StackOverflow](http://stackoverflow.com/questions/9455354/msbuild-inline-task-reference-non-standard-microsoft-assemblies).

Code that reproduces the error:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="TestBuild" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <UsingTask TaskName="Hello" TaskFactory="CodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll" >
    <ParameterGroup />
    <Task>
      <Reference Include="$(MSBuildExtensionsPath)\Microsoft\VisualStudio\v14.0\Web\Microsoft.Web.XmlTransform.dll"/>
      <Reference Include="System.Xml" />
      <Code Type="Fragment" Language="cs">
        <![CDATA[
          var f = new Microsoft.Web.XmlTransform.XmlTransformationException("test");
          Log.LogMessage("test: " + f.Message);  
        ]]>
      </Code>
    </Task>
  </UsingTask>
  <Target Name="TestBuild">
    <Hello />
  </Target>
</Project>
```

**Comment by nigelgbanks** [comment]
This is still an issue if using `RoslynCodeTaskFactory`. 
```error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly```

But it does work with `CodeTaskFactory`.
