### ISSUE TITLE
TargetFrameworkRootPath not respected

### ISSUE THREAD

**Issue by jaredpar** [Microsoft/msbuild#598]
The variable `TargetFrameworkRootPath` appears to let developers customize the location of items like Portable Reference Assemblies.  In theory I should be able to copy the portable ref assemblies to a custom place on my hard drive, point `TargetFrameworkRootPath` to that location and MSBuild will run it's normal algorithm on that location.  

While this variable is respected for most reference assembly lookup, it is not respected for mscorlib.  The mscorlib reference is calculated from `_ExplicitReference` which derives it's value from `FrameworkPathOverride`.  That property is set via the following

``` xml
<FrameworkPathOverride Condition="'$(FrameworkPathOverride)' == ''">$([Microsoft.Build.Utilities.ToolLocationHelper]::GetPathToStandardLibraries($(TargetFrameworkIdentifier), $(TargetFrameworkVersion), $(TargetFrameworkProfile), $(PlatformTarget)))</FrameworkPathOverride>
```

This boils down to the [following code](https://github.com/Microsoft/msbuild/blob/131d5eeeafe66b5db52e2c8908c424c4471b2919/src/Utilities/ToolLocationHelper.cs#L1555) in MSBuild:

``` cs
public static string GetPathToStandardLibraries(string targetFrameworkIdentifier, string targetFrameworkVersion, string targetFrameworkProfile)
```

This method does not take a path specifying the target framework root and hence goes to the standard `Program Files (x86)`.  This method should respect `TargetFrameworkRootPath` to allow for customized locations of the reference assemblies.

**Comment by AndyGerlicher** [comment]
This seems reasonable, do you need this for Update 3? Or Dev15?

**Comment by radical** [comment]
An implementation for this can be seen at https://github.com/Microsoft/msbuild/pull/529/commits/af480115aa70de8d5123e67b827a101d29e0d0aa  and https://github.com/Microsoft/msbuild/pull/529/commits/53d0f5bad22e207b5b489462fcaa00a68bc88a43 in PR #529 .

**Comment by jaredpar** [comment]
Preferably update 3.  This is part of a bigger set of changes I'm trying to do to our build system.  May drop you a line about the overall plan.

**Comment by radical** [comment]
I have split the commits from the previous PR #529 into a new PR #627, with just the commits relevant for this issue.

**Comment by jaredpar** [comment]
I believe this issue can be closed now.  I can verify it works on MSBuild 15.0 as we rely on it for our build.
