### ISSUE TITLE
Migrate from MSTest to xunit

### ISSUE THREAD

**Issue by akoeplinger** [Microsoft/msbuild#6]
MSTest isn't available cross-platform and the other dotnet open source projects like corefx migrated to xunit already.

**Comment by AndyGerlicher** [comment]
Our cross platform branch already has them in nunit so they work on other platforms. Xunit is probably a better choice though since corefx/coreclr is using that.

Either way that branch should be posted within a week or so.

**Comment by akoeplinger** [comment]
Great! Yeah I think it'd be good to use the same testing frameworks as the .NET Core repos.

**Comment by mmitche** [comment]
+1 to using the same harness please.

**Comment by olivierrr** [comment]
:+1:

**Comment by NotMyself** [comment]
:shipit:

**Comment by Maxwe11** [comment]
Which xunit should be installed (from nuget.org or dotnetbuild-tools on myget.org) ?
What else should be done except changes in code?

**Comment by mmitche** [comment]
@Maxwe11 You should use the one on dotnet-buildtools, which is being updated as necessary to work well with CoreCLR

**Comment by mmitche** [comment]
Add to this that the tests should be runnable from the command line.

@AndyGerlicher We probably need to make the tests runnable from the command line (or directly from the build) to make them useful in CI.  Can we move msbuild to xunit (also has VS integration) and integrate the tests into the command line build (like corefx) asap?  Can that change be merged into master?

**Comment by AndyGerlicher** [comment]
Yes @mmitche that is definitely a change we would want to take (and merged into master). Just not the highest priority right now (focusing on getting corefx to build on Linux/Mac).

**Comment by AndyGerlicher** [comment]
Ideally this should be done in master.

**Comment by rainersigwald** [comment]
Because of xunit/xunit#560, it looks like the initial implementation of this will drop VS support and have only command line/MSBuild test execution.

**Comment by AndyGerlicher** [comment]
Moving to Sprint 89.

**Comment by rainersigwald** [comment]
Done with #201.  Some follow-up work: #210, #211.
