### ISSUE TITLE
If TEMP is set to a bare drive, FileTracker may throw

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#606]
Ran across http://stackoverflow.com/questions/3221565/microsoft-build-utilities-filetracker-threw-an-exception-error-happens-with-dif while looking for something. It looks like that code still exists.

**Comment by rainersigwald** [comment]
Looking further it's not entirely clear to me why the go-up-one-level code is required. It's not commented--everything seems to act like it just needs TEMP.

**Comment by akoken** [comment]
Current code is trying to get directory name after getting temp path. I think it's enough to use just temp path here. I can send a PR for this if it's ok @rainersigwald  ?

**Comment by rainersigwald** [comment]
@akoken Sounds like the right approach to me. Please do!
