### ISSUE TITLE
How to get MSBuild binaries without cloning the repo

### ISSUE THREAD

**Issue by thany** [Microsoft/msbuild#607]
Could you provide binaries for those who don't need or want the sources entirely, or don't know how to build the sources, or simply couldn't be bothered? For those who just need MSBuild without all of VS2015 that it comes with.

**Comment by rainersigwald** [comment]
The supported way to get MSBuild without Visual Studio is the [Microsoft Build Tools](https://www.visualstudio.com/downloads/download-visual-studio-vs#d-build-tools) installer, linked from the Releases tab.

**Comment by thany** [comment]
What releases tab?
![capture](https://cloud.githubusercontent.com/assets/152227/15069760/1892375c-1380-11e6-934d-e14dfd01f45f.PNG)

**Comment by nosami** [comment]
<img width="1024" alt="screen shot 2016-05-06 at 10 47 01" src="https://cloud.githubusercontent.com/assets/667194/15069785/f2c7ae4c-1377-11e6-92a8-6661ee9c2ef0.png">

**Comment by thany** [comment]
Ah there it is.

Anyway, why not host the installer here as well? If the linked installer is the one built from the source code here at github, they should belong together. If not, then my requests still standas to release prebuilt versions of the sourcecode.

**Comment by AndyGerlicher** [comment]
The installer is hosted on the download site for Visual Studio. We intend to provide a NuGet package so you don't have to install it, but that work is not yet complete. For now this is the only released version we provide.
