### ISSUE TITLE
Need to update [DebuggerDisplay] attributes to match renamed field names

### ISSUE THREAD

**Issue by KirillOsenkov** [Microsoft/msbuild#610]
See here, for example:
https://github.com/Microsoft/msbuild/blob/master/src/XMakeBuildEngine/Instance/ProjectPropertyGroupTaskInstance.cs#L23

Field name is _condition, however DebuggerDisplay references condition.

As a result, these objects are difficult to inspect in the debugger.

**Comment by KirillOsenkov** [comment]
![image](https://cloud.githubusercontent.com/assets/679326/15095333/8490c7ba-1476-11e6-8f9c-9e0a5c89b9a7.png)

**Comment by AndyGerlicher** [comment]
We should definitely do this!
