### ISSUE TITLE
Visual C++ tasks are missing

### ISSUE THREAD

**Issue by mweisshaupt1988** [Microsoft/msbuild#65]
Hello I would like to use MSBuild on a buildserver without installing it or Visual Studio. I already got the VC++ compiler to run standalone on virtual machine but I also need MSBuild to build the VC++-Solution.

I noticed that the Visual C++ tasks are missing. Is it possible that you add them to the Github repository or is there a way to include the tasks and properties that are bundled with Visual Studio 2015 Preview?

Thanks in advance.

**Comment by NikolaiTillmann** [comment]
We are checking with the C++ team in Microsoft what can be done. Please stand by.

**Comment by NikolaiTillmann** [comment]
The C++ team is considering it, but there is no further information we can share at this time.
