### ISSUE TITLE
Hang on build failure

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#651]
I've seen this a couple of times now. I made an error in C# and rebuilt (here in the MSBuild repo), and MSBuild appeared to hang after emitting the error. Hitting ctrl-c spits out the expected `Attempting to cancel the build...` message, but doesn't seem to do anything--it's still hung.

**Comment by cdmihai** [comment]
It works if you turn off /m.

@dsplaisted 
Do you know where / how the extra msbuild processes might miss the build cancelled events?

**Comment by rainersigwald** [comment]
This is happening on Windows/CoreCLR too.

**Comment by rainersigwald** [comment]
Was just able to repro this on OS X building our own build, but it took several attempts.

**Comment by rainersigwald** [comment]
I think this is resolved. If the symptom remains it should at least have a different cause.
