### ISSUE TITLE
Cannot build WPF app using Microsoft.Build.* version 14

### ISSUE THREAD

**Issue by agc93** [Microsoft/msbuild#653]
I have a WPF app using C# 6 features. My understanding is that necessitates the use of MSBuild 14. However, if I reference version 14 of the Microsoft.Build* assemblies, I cannot successfully build a WPF project.

Instead I get an InvalidCastException that `MarkupCompilePass1` cannot be casted to an `ITask`:

```
System.InvalidCastException occurred
Message: Exception thrown: 'System.InvalidCastException' in Microsoft.Build.dll
Additional information: Unable to cast object of type 'Microsoft.Build.Tasks.Windows.MarkupCompilePass1' to type 'Microsoft.Build.Framework.ITask'.
```

A full and and basic sample of this can be found [here](https://github.com/agc93/msbuild-sample), but the steps can be summarised as follows:

1. New blank solution
2. New WPF application (from VS template)
3. New Console Application (from VS template)
4. Add references to v14 MSBuild libraries through Add References > Extensions
5. Attempt to build WPF application project from console app

```
            var pc = new ProjectCollection();
            var path = Directory.CreateDirectory(Path.GetTempPath() + Guid.NewGuid().ToString("N") + "\\");
            var props = new Dictionary<string, string>
            {
                {"Configuration", "Debug"},
                {"Platform", "AnyCPU"},
                {"OutputPath", path.FullName}
            };
            var buildParams = new BuildParameters(pc)
            {
                DetailedSummary = true,
                Loggers = new List<ILogger> {new ConsoleLogger()},
                DefaultToolsVersion = "14.0"
            };
            var targets = new List<string> {"PrepareForBuild", "Clean", "Build", "Publish"};
            var reqData = new BuildRequestData(GetProjectPath(), props, "14.0", targets.ToArray(), null);
                Log("Starting MSBuild build");
                BuildManager.DefaultBuildManager.BeginBuild(buildParams);
                var buildResult = BuildManager.DefaultBuildManager.BuildRequest(reqData);
                Log($"MSBuild build complete: {buildResult.OverallResult}");
            
```

This code will fail with an `InvalidCastException` and the build will fail with no error message.

Is this expected behaviour? Are there extra targets now?

Please let me know if you need more information.

**Comment by rainersigwald** [comment]
Thanks for an excellent bug report, with repro! This isn't something we can fix with a change to MSBuild itself, but you can fix the problem in your client application.

Since `PresentationBuildTasks` (where the XAML/WPF tasks live) was compiled against an old version of MSBuild, this error arises when the application can't handle multiple different definitions of `ITask` (the new one from your v14.0 references, and the old one transitively from WPF).

Fortunately, this problem isn't unique to MSBuild, and .NET provides us a solution: [Binding Redirects](https://msdn.microsoft.com/en-us/library/7wd6ex19(v=vs.110).aspx). I was able to make your repro executable work by providing this `app.config` file:

```XML
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
  </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Build.Framework" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="14.0.0.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Build.Framework" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" />
        <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="14.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Build" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" />
        <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="14.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

`MSBuild.exe` itself uses the same mechanism: check out `C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe.config` on your machine.

**Comment by agc93** [comment]
Awesome, I just put in a binding redirect and the build went through! Thanks heaps.

If you don't mind the quizzing: how does .NET determine where to load redirects from? For example, if I have a Console app calling a Class Library (with the Microsoft.Build references) building *something*, do the redirects need to go in the app.config for the console app (the running app) or the library (the app with the references)?

**Comment by rainersigwald** [comment]
> how does .NET determine where to load redirects from? 

I believe it's a property of the _executable_, and the only place the loader looks for redirects is `{executablepath}\{executablename}.exe.config`. But I don't know the area deeply and I would not be surprised if that's wrong!

I'm going to close this issue since you're up and running.

**Comment by lancesnead** [comment]
I've used the code that @agc93 provided and modified it using the instructions for [updating an existing application to MSBuild 15](https://docs.microsoft.com/en-us/visualstudio/msbuild/updating-an-existing-application?view=vs-2017). I believe I've done everything correctly, but I just can't seem to build an WPF project, or any solution containing a WPF project. I always get the following:

`Target MarkupCompilePass1:
    C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.WinFx.targets(268,9): error MC1000: Unknown build error, 'Object reference not set to an instance of an object.'
Done building target "MarkupCompilePass1" in project "WpfApplication.csproj" -- FAILED.`

You can find an updated [repo](https://github.com/lancesnead/msbuild-sample) with [my changes here](https://github.com/agc93/msbuild-sample/compare/master...lancesnead:master).

I'm in the process of updating our internal build application to use MSBuild 15, but am currently stuck trying to figure out this error. Any help you could provide would be greatly appreciated!
