### ISSUE TITLE
MSBuild 14.0.25123.0 not restoring nuget packages

### ISSUE THREAD

**Issue by ravensorb** [Microsoft/msbuild#657]
I am not sure if this is a nuget issue or a msbuild issue.  When I build a solution in Visual Studio 2015 Update 2 - all nuget packages are restored 100% correctly and the solution builds.  When I try to build via MSbuild, no packages are restored at all regardless of how I configure my build scripts.

Note: I am now looking into using the nuget.exe command line tool to force a restore, however that also is having issues as it is not restoring specific framework packages (like Microsoft.CSharp).

**Comment by rainersigwald** [comment]
At the moment, MSBuild does not restore packages; you must run restore as a separate step before invoking MSBuild. That's true in Visual Studio, but it's handled for you. On the command line you must use `nuget.exe` explicitly.

There's some documentation about this from NuGet: http://docs.nuget.org/consume/package-restore#package-restore-approaches

**Comment by ravensorb** [comment]
Thanks, that is what I thought and the command line restore isn't working.  I submitted a possible bug [here](https://github.com/NuGet/Home/issues/2854)

**Comment by ravensorb** [comment]
Note: It would be great if msbuild would also be able to restore

**Comment by jeffkl** [comment]
In MSBuild 15.0 with some of the newer logic, there is now a `Restore` target.  The target isn't called for you so it still needs to be run first.

`MSBuild.exe /Target:Restore`

MSBuild 14 won't be getting an update to enable this target so I'm going to close this issue.  We are working closely with the NuGet team to improve the experience in future versions.
