### ISSUE TITLE
openssl must be in a specific location to bootstrap on OS X

### ISSUE THREAD

**Issue by danrossi** [Microsoft/msbuild#665]
Following 

https://github.com/Microsoft/msbuild/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild

ran
```
./cibuild.sh --target CoreCLR
```

I get this. 

```
./cibuild.sh: line 57: ./Tools/corerun: No such file or directory
```

If I select the .NET core will that let me rebuild a silverlight player project at all ? I need to rebuild it on the command line adding in compiler constants.

**Comment by danrossi** [comment]
I get this in the install log. Tried everything. The library is sitting in

```
./Tools/dotnetcli/shared/Microsoft.NETCore.App/1.0.0-rc2-3002547/System.Security.Cryptography.Native.dylib
```

There is many issues related to this but no fix. I don't run homebrew but macports. Updated to latest openssl. 

```
error: Unable to load the service index for source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json.
error:   The type initializer for 'Crypto' threw an exception.
error:   The type initializer for 'CryptoInitializer' threw an exception.
error:   Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.
error:    (Exception from HRESULT: 0x8007007E)
```

**Comment by danrossi** [comment]
Forgive me. It seems its hardcoding a path for openssl. I had to try and install with homebrew as macports is /opt/local.  It seems to be downloading files now

**Comment by rainersigwald** [comment]
Reopening because I didn't think there was actually a strong homebrew dependency. We need to update our documentation or see if we can get things working with the `/opt/local` paths.

Thanks for the report!

**Comment by rainersigwald** [comment]
I updated the setup page to mention the `/usr/local` requirement: https://github.com/Microsoft/msbuild/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild/35d78ed9acee0c4186c1c53d053137d567be1a3a

Thanks again for pointing this out, @danrossi.
