### ISSUE TITLE
Identifying tests is broken in xplat

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#669]
`InternalErrorException.ConsiderDebuggerLaunch` is set up to launch the debugger if `!FileUtilities.RunningTests`: https://github.com/rainersigwald/msbuild/blob/bcf80f0923eb121b74ef43c47b28410988534691/src/Shared/InternalErrorException.cs#L119-L119

This is broken on the latest xplat with #666, because identifying tests is now more accurate (from master) but broken (because in netcore we are checking only `Process.GetCurrentProcess().ProcessName`, which is pretty much always `corerun.exe`).

On full framework, we fall back to checking `Environment.GetCommandLineArgs()[0]`, which would work correctly. We're not using it in netcore because it wasn't part of the API surface, but it [now is](https://github.com/dotnet/corefx/pull/4435). Unfortunately, it seems to be part of the `netstandard1.5` surface, while we target 1.3.

I'm working around this by setting the opt-out environment variable `MSBUILDDONOTLAUNCHDEBUGGER` when running tests inside our build, but we should fix the underlying behavior.

**Comment by cdmihai** [comment]
I'd vote to just wait for corefx to start bringing stuff back, and as that happens, progressively undo our xplat only code, when possible.

This blog post suggest we'll see a lot of the missing APIs coming back: https://blogs.msdn.microsoft.com/dotnet/2016/05/27/making-it-easier-to-port-to-net-core/

**Comment by rainersigwald** [comment]
Agreed, but I'm not clear about the 1.3/1.5 implications. The API we want for this is available in .NET Core but not in netstandard1.3.

**Comment by cdmihai** [comment]
I guess we don't know yet how the APIs are coming back. Whether will they get added to all netstandard versions, or will there be ns1.6, ns1.7, etc.

If they'll be coming back as bumped up ns numbers, I'd vote to just use reflection, like we do for Assembly.Location.

**Comment by cdmihai** [comment]
@ericstj

Should we just wait for corefx to bring back the APIs, or use reflection for Environment.GetCommandLine? :)
Or, alternatively, really generate ns1.3 reference assemblies and then have specific runtime implementation dlls (net46, netcoreapp, mono), where GetCommandLine is actually available.

**Comment by cdmihai** [comment]
Yea, unfortunately RunnerUtilities is a shared source file :(

**Comment by ericstj** [comment]
@cdmihai we've already brought it back, it's not going to come back further.  As you mention you could seperate ref and impl, then your portable impl could be built against a higher netstandard version and you could cover all your platforms through bait-and-switch.
