### ISSUE TITLE
[Mac OS X] NullRef from Microsoft.Build.Shared.NativeMethothdsShared.FindOnPath

### ISSUE THREAD

**Issue by joshfree** [Microsoft/msbuild#671]
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/release_1.0.0/job/checked_osx_prtest/54/consoleFull#209475141579494335-f7bd-47d0-8771-8661e00c2db2
> 14:04:40 /Users/dotnet-bot/j/workspace/dotnet_coreclr/release_1.0.0/checked_osx_prtest/Tools/versioning.targets(304,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object. [/Users/dotnet-bot/j/workspace/dotnet_coreclr/release_1.0.0/checked_osx_prtest/build.proj]
14:04:40 /Users/dotnet-bot/j/workspace/dotnet_coreclr/release_1.0.0/checked_osx_prtest/Tools/versioning.targets(304,5): error MSB4018:    at Microsoft.Build.Shared.NativeMethodsShared.FindOnPath(String filename) [/Users/dotnet-bot/j/workspace/dotnet_coreclr/release_1.0.0/checked_osx_prtest/build.proj]
14:04:40 /Users/dotnet-bot/j/workspace/dotnet_coreclr/release_1.0.0/checked_osx_prtest/Tools/versioning.targets(304,5): error MSB4018:    at Microsoft.Build.Utilities.ToolTask.ComputePathToTool() [/Users/dotnet-bot/j/workspace/dotnet_coreclr/release_1.0.0/checked_osx_prtest/build.proj]
14:04:40 /Users/dotnet-bot/j/workspace/dotnet_coreclr/release_1.0.0/checked_osx_prtest/Tools/versioning.targets(304,5): error MSB4018:    at Microsoft.Build.Utilities.ToolTask.Execute() [/Users/dotnet-bot/j/workspace/dotnet_coreclr/release_1.0.0/checked_osx_prtest/build.proj]
14:04:40 /Users/dotnet-bot/j/workspace/dotnet_coreclr/release_1.0.0/checked_osx_prtest/Tools/versioning.targets(304,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/Users/dotnet-bot/j/workspace/dotnet_coreclr/release_1.0.0/checked_osx_prtest/build.proj]
14:04:40 /Users/dotnet-bot/j/workspace/dotnet_coreclr/release_1.0.0/checked_osx_prtest/Tools/versioning.targets(304,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext() [/Users/dotnet-bot/j/workspace/dotnet_coreclr/release_1.0.0/checked_osx_prtest/build.proj]
14:04:40 Invoking "/Users/dotnet-bot/j/workspace/dotnet_coreclr/release_1.0.0/checked_osx_prtest/src/pal/tools/gen-buildsys-clang.sh" "/Users/dotnet-bot/j/workspace/dotnet_coreclr/release_1.0.0/checked_osx_prtest" 3 5 x64 Checked  Include_Tests

**Comment by Sarabeth-Jaffe-Microsoft** [comment]
@joshfree Can you elaborate more on this bug and send over some repro steps?

Also, can you also explain the relationship between this bug and https://github.com/dotnet/coreclr/issues/5379

**Comment by joshfree** [comment]
@Sarabeth-Jaffe-Microsoft this callstack shows a unhandled nullref from Msbuild that occurred in our CI. The linked PR is where the msbuild failure occurred during CI. 

Repro steps
1. Run "build.sh" from a clone of /dotnet/corefx on OS X 10.11. 

I've only seen this issue once.

**Comment by Sarabeth-Jaffe-Microsoft** [comment]
We haven't been able to repro this. Please re-file if you see this issue again.

Thanks!
MSBuild Team
