### ISSUE TITLE
How to build MSBuild without Visual Studio

### ISSUE THREAD

**Issue by dlaub123** [Microsoft/msbuild#672]
"Visual Studio uses MSBuild, but MSBuild does not depend on Visual Studio." - sounds good - except when I attempt to run any of the *.cmd Windows Command Scripts (e.g. build.cmd) I get the error message: 
"Error: This script should be run from a Visual Studio 2015 Command Prompt."

so I appear to be stuck in a chicken & egg scenario

**Comment by rainersigwald** [comment]
MSBuild (the product) does not depend on Visual Studio--you can run MSBuild without VS installed. To _build_ MSBuild, you need a build environment, and for that we use an installed Visual Studio. Instructions for getting up and running are at https://github.com/Microsoft/msbuild/wiki/Building-Testing-and-Debugging-on-Full-Framework-MSBuild.

**Comment by dlaub123** [comment]
I get the distinction now (building vs. running) - however I'm running on a
PC without Local Admin rights, hence there is very little I can install
(i.e. I can't install VS)  I can't install SharpDevelop either - but
SharpDevelop does have an install from source option, but it depends on
MSBuild - which I'll assume at this point I can't install.  So, my options
appear to be zero on that front at this point.  I am lucky enough on this
no admin access machine to already have .net installed on it AND the csc
compiler is in the .net directory - so I do have this very lowest common
denominator option of writing simple c# apps - and that appears the best
I'll be able to use.

**Comment by rainersigwald** [comment]
There is also an older version of MSBuild installed as part of the .NET Framework. If you're just trying to build things, that should work (it's missing new features and doesn't support new SDKs, but should wrap the csc that's in the framework well). It should be in `C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe`.

**Comment by dlaub123** [comment]
Thanks - hopefully this will be my silver bullet!
