### ISSUE TITLE
PowerShell Inline Tasks

### ISSUE THREAD

**Issue by SamuelEnglard** [Microsoft/msbuild#673]
Right now you can create inline tasks using C# and VB.NET. I propose also allowing PowerShell. The advantage PowerShell has over C# and VB.NET is that it has a lot of built in functionality that C# and VB.NET don't have built in.

**Comment by rainersigwald** [comment]
Stumbled across https://blogs.msdn.microsoft.com/visualstudio/2010/02/20/msbuild-task-factories-guest-starring-windows-powershell/ today--does that suit your needs?

**Comment by SamuelEnglard** [comment]
It would, but sadly MSDN Code isn't up anymore :(

**Comment by rainersigwald** [comment]
That could be a little bit of a problem! I hadn't clicked through.

I asked around a bit and it looks like there's one in the open-source MSBuildExtensionPack: http://www.msbuildextensionpack.com/help/4.0.5.0/html/6a9ca4a5-ff2d-8493-8046-8de21bb0f4e9.htm

**Comment by SamuelEnglard** [comment]
That looks like it could work! Go community!
