### ISSUE TITLE
Assembly search path in UsingTask

### ISSUE THREAD

**Issue by AndyGerlicher** [Microsoft/msbuild#674]
Consider the following case:
```XML
<UsingTask TaskName="Foo" AssemblyFile="$(foo)\task.dll" />
```
`task.dll` depends on `reference.dll`.

Currently all of the dependencies of `task.dll` will need to be in the same folder as task.dll (standard .NET loader). This generally works well, but may not always ideal for deployment of multiple components. This was encountered internally when the `reference.dll` was removed from the GAC.

I propose that we add an additional attribute to specify search paths for assemblies. For example:
```XML
<UsingTask TaskName="Foo" AssemblyFile="$(foo)\task.dll" AssemblySearchPaths="$(foo2)"/>
```

**Comment by AndyGerlicher** [comment]
Closing this. This is a breaking change in the schema and shouldn't be necessary. In many cases using this pattern would leave a task dll in a non-working state and requires additional knowledge to use. This is akin to deploying an exe and requiring path(s) to dependencies to be passed in that you might not know where they are. In some cases this would be good (perhaps NuGet with target + dll), but in many cases not. If anyone feels strongly against this feel free to discuss.

**Comment by Snoopy-hub** [comment]
I wish to controll the search pathes of the UsingTask as i am building my custom MSBuild task wich depends on other NuGet packages, my task is packaed inside its own NuGet package, so all other dependencies are out of the folder with my assembly.
Currently i did a trick with copying all referenced assemblies of the project which is using my task to the folder with my assembly and in the .targets file i call UsingTask from that folder.
But copying all the files is kinda heavy operation...
`<PropertyGroup> 
 <Libs>$([MSBuild]::NormalizeDirectory($([System.IO.Path]::GetDirectoryName($([System.IO.Path]::GetDirectoryName($([MSBuild]::NormalizeDirectory($(MSBuildThisFileDirectory)))))))\lib\$(TargetFramework)))</Libs>
</PropertyGroup>
<Copy SourceFiles="@(ReferencePathWithRefAssemblies)" DestinationFolder="$(Libs)" />`
Might be there is another workaround with this?

**Comment by rainersigwald** [comment]
@Snoopy-hub no, copying assemblies to the task location is the best current solution. #5037 would make it possible in a future .NET (Core) release.
