### ISSUE TITLE
Overwrite Platform and Configuration in ProjectReference

### ISSUE THREAD

**Issue by jozefizso** [Microsoft/msbuild#689]
We have a single solution with WIX projects to create our installers. We must create two MSI files for x86 and x64 platform from a single project and use them in a single bootstrapper project that creates one EXE for x86 platform.

I tried to create this reference to MSI projects in the `Bootstrapper.wixproj` file:

```
<ItemGroup>
  <ProjectReference Include="..\Installer\Installer.wixproj">
    <Name>Installer_x86</Name>
    <Project>{fa09964d-5d91-46ca-adc4-fe023cf1bd48}</Project>
    <Platform>x86</Platform>
  </ProjectReference>
  <ProjectReference Include="..\Installer\Installer.wixproj">
    <Name>Installer_x64</Name>
    <Project>{fa09964d-5d91-46ca-adc4-fe023cf1bd48}</Project>
    <Platform>x64</Platform>
  </ProjectReference>
</ItemGroup>
```

The idea is to have two references to a single `Installer.wixproj` file that would reference the x86 and x64 platforms.

Unfortunatelly MSBuild will resolve both references as x86 platform and does not build the one as x64.

```
SolutionConfigurationContents=<SolutionConfiguration>
	<ProjectConfiguration Project="{fa09964d-5d91-46ca-adc4-fe023cf1bd48}" AbsolutePath="c:\dev\Installer\Installer.wixproj" BuildProjectInSolution="True">Release|x86</ProjectConfiguration>
	<ProjectConfiguration Project="{d85c3c21-ee88-439d-af12-363939a03b38}" AbsolutePath="c:\dev\Bootstrapper\Bootstrapper.wixproj" BuildProjectInSolution="True">Release|x86</ProjectConfiguration>
	</SolutionConfiguration>

AssignProjectConfiguration: (TargetId:15)
  Output Item(s): 
      _ProjectReferenceWithConfiguration=
          ..\Installer\Installer.wixproj
                  Configuration=Release
                  DoNotHarvest=True
                  FullConfiguration=Release|x86
                  Name=Installer_x86
                  Platform=x86
                  Private=True
                  Project={fa09964d-5d91-46ca-adc4-fe023cf1bd48}
                  RefProjectOutputGroups=Binaries;Content;Satellites
                  RefTargetDir=INSTALLFOLDER
                  SetConfiguration=Configuration=Release
                  SetPlatform=Platform=x86
          ..\Installer\Installer.wixproj
                  Configuration=Release
                  DoNotHarvest=True
                  FullConfiguration=Release|x86
                  Name=Installer_x64
                  Platform=x86
                  Private=True
                  Project={fa09964d-5d91-46ca-adc4-fe023cf1bd48}
                  RefProjectOutputGroups=Binaries;Content;Satellites
                  RefTargetDir=INSTALLFOLDER
                  SetConfiguration=Configuration=Release
                  SetPlatform=Platform=x86
```

Can we overwrite the Platform value in the ProjectReference metadata? If not, is there some other solution to building a single project that depends on output from two different platforms?

**Comment by rainersigwald** [comment]
Can you share out the parts of the solution that refer to `Installer.wixproj` (including by its GUID which seems to be `fa09964d-5d91-46ca-adc4-fe023cf1bd48`)? I'm curious to see whether the problem is that the `.sln` doesn't know that it can be built multiple ways, or whether MSBuild is misinterpreting that.

What happens if you remove `Installer.wixproj` from the solution? Does that work correctly? Also, what happens if you build `Bootstrapper.wixproj` *directly* from the command line (without building the solution)?

Worst case, you could probably roll your own project references by writing a new target that calls the MSBuild task on `Installer.wixproj`. But hopefully there's a better solution.

**Comment by Sarabeth-Jaffe-Microsoft** [comment]
We're going to close this issue due to lack of response. @jozefizso If you respond with the information listed by @rainersigwald or a small repro solution, we'd be happy to take another look.

Thanks!
- MSBuild Team
