### ISSUE TITLE
Ensure versioning works for all host runtimes

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#694]
In master, we're using Nerdbank.GitVersioning, which works great on full framework. It should support running on .NET Core soon, and we should move to that version and make sure it works everywhere.

**Comment by rainersigwald** [comment]
This one's interesting in xplat. Right now it's only working because of a confluence of bugs.

When I merged the adoption of GitVersioning in, I accidentally broke the restore-build-time-packages code, so that it never runs (because it's [still looking for the old packages.config](https://github.com/Microsoft/msbuild/blob/2001dcb8afab050d017acdf411bcc82e0a952c82/src/.nuget/packageLoad.targets#L41)).

That keeps the target file from ever existing and made the fix from 5fd4249 equivalent to just disabling it--which is fine for now, since this issue is to track making sure it works everywhere.

The reason this didn't break in CI is because xplat only builds for netcore in CI, and the "standard" build uses an old netcore MSBuild to bootstrap, so the old condition always evaluates to "don't bother with GitVersioning".

**Comment by rainersigwald** [comment]
For ease of future checks, this is dependent on https://github.com/AArnott/Nerdbank.GitVersioning/issues/56

**Comment by rainersigwald** [comment]
Removing from the great-merge milestone: it's sufficient for now to produce nicely-versioned packages on Windows. Our official build will run only on Windows for the foreseeable future (because we need Microsoft-internal signing steps), so we can wait indefinitely for the nice-to-have "also version correctly on other OSes".

**Comment by AArnott** [comment]
Nerdbank.GitVersioning has a 'dotnet' compatible version now. [Details here](https://github.com/AArnott/Nerdbank.GitVersioning/issues/56#issuecomment-280549760)
