### ISSUE TITLE
CancelledBuildWithDelay{2,4}0 test is flaky

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#696]
This test at https://github.com/Microsoft/msbuild/blob/323f7c0a43679d9c2b7b2ce6746c20c65a68b0e7/src/XMakeBuildEngine/UnitTests/BackEnd/BuildManager_Tests.cs#L1369 is super flaky and fails a bunch of our CI builds. From inspection, it looks like it's because it derives timing from `Sleep` calls. It should be rewritten to be robust.

**Comment by Sarabeth-Jaffe-Microsoft** [comment]
**Possible solution:**

Task needs to wait until the test cancels the build. Right now this is done using a delay. It would be more robust if it used the file system as a locking mechanism; the task could sleep until a file exists & the test could cancel the build & write to the file.
