### ISSUE TITLE
Remove boilerplate XML

### ISSUE THREAD

**Issue by Sarabeth-Jaffe-Microsoft** [Microsoft/msbuild#699]
**This issue is in the open design phase and is a part of the [project.json -> csproj](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) conversion effort.**

### Terser MSBuild syntax - Make the syntax less verbose (more compressed XML). 

**Can we remove:**
- [ ] XML tag (assume UTF8 unless specified)
- [ ] XML Namespace 

**Open Issues**
- There may be impact to XML parsing/editing tools

Note: there is much improvement to be done in the default template for MSBuild projects that does not involve Core MSBuild changes.

See: [roslyn-project-system feature](https://github.com/dotnet/roslyn-project-system/issues?q=is%3Aissue+is%3Aopen+label%3A%22Feature+-+Project+File+Cleanup%22)

**Comment by rainersigwald** [comment]
Another thing we can do here is demote this message

```
Project file contains ToolsVersion="". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="15.0". For
 more information, please see http://go.microsoft.com/fwlink/?LinkId=293424.
```

To a much lower verbosity.

**Comment by mhutch** [comment]
Or remove the ToolsVersion warning entirely.

**Comment by davkean** [comment]
What point is the ToolsVersion warning, when you ignore it now?

**Comment by rainersigwald** [comment]
Yeah, I'm convinced that we should get rid of it entirely.

**Comment by Sarabeth-Jaffe-Microsoft** [comment]
@AndyGerlicher thoughts? ^

**Comment by wjk** [comment]
Just a quick 2¢ on this issue: I highly suggest _not_ removing the XML namespace, as that is what enables Visual Studio’s excellent XML IntelliSense support. Whenever I hand-edit MSBuild, I rely on this IntelliSense to keep me sane and highly productive. (Hard-coding `*.csproj` et al in VS to enable this IntelliSense is also a bad idea, by the way, because MSBuild files don’t always have a "recognized" extension, or even follow the `*.*proj` naming convention.)

**Comment by mhutch** [comment]
FWIW, I'm not sure I've ever found the IntelliSense with the XSD to be useful as it only works for the elements defined in the XSD, which is a pretty tiny subset of what's actually available, and very rarely what I need.

I actually ended up writing my own code completion engine for Xamarin Studio :)

**Comment by mfilippov** [comment]
If I open page with xmlns: http://schemas.microsoft.com/developer/msbuild/2003 I get error:

**Comment by wjk** [comment]
@mhutch True, but it’s better than nothing. Interestingly, the MSBuild schema is split over three files (the "core" MSBuild items, the items provided by in-box VS extensions, and a third that is mostly empty). This mostly empty schema is there so you can add your own properties/items and have them picked up by Visual Studio. Unfortunately, this file is machine-global and requires Administrator privileges to edit (not to mention it could be overwritten at any time by a VS update), so it’s not an ideal solution. I suppose if you add the MSBuild schemas from this repo locally, you could edit them without any problems, but Visual Studio might give you grief regarding which schema to use (the one in the solution or the one installed by VS).

@mfilippov That is to be expected. XML namespaces very rarely point to actual Web resources, even though they almost always look like they would. There is a file installed by Visual Studio that maps XML namespace strings to the XSD schema files that define the valid syntax for that namespace.

**Comment by mhutch** [comment]
Right, but the best way is to scan the targets and build completion from that :)

![MSBuild expression completion](https://pbs.twimg.com/media/Ciy0PGjWgAE-wlx.jpg:large)

**Comment by darrelmiller** [comment]
The JSON editor in Visual Studio provides a pretty reasonable approach to mapping schemas to instance documents without namespaces.
![image](https://cloud.githubusercontent.com/assets/447694/18892122/41ec36f8-84d6-11e6-96ce-432c5ab47d2f.png)

It seems to sniff the document and detect the schema and if it can't, you can pick from a list of schemas VS knows about.

**Comment by RichiCoder1** [comment]
MSBuild should arguably have support in a class of it's own either way. That's something that's been lacking for a while.

**Comment by davkean** [comment]
We planning on addressing this so that you can still get IntelliSense, https://github.com/dotnet/roslyn-project-system/issues/516 is tracking it.
