### ISSUE TITLE
Enhance OM to support first class treatment of globs

### ISSUE THREAD

**Issue by Sarabeth-Jaffe-Microsoft** [Microsoft/msbuild#700]
**This issue is in the open design phase and is a part of the [project.json -> csproj ](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) conversion effort.**

MSBuild has long supported including items via glob patterns, but that has been difficult to use for a variety of reasons. 

### Object model/programmatic editing support
- Track down the history of what happened to an item (did come from glob, where was it update, where was it exclude, etc)
  - Project.GetItemProvenance: #732
- Know what globs exist in a project (To set-up FileWatchers)
  - Project.GetAllGlobs: #735
- Non-exploding APIs (current behaviour is to explode item tag if it resolves to multiple items).
 - Multiple APIs tracker here: #736 
- Support for modifying metadata of a file that was included via glob
  - new Update attribute for static / dynamic item tags: #733
  - new Remove attribute for static item tags: #734 
- Global exclude
  - Exclude in item definition groups: #748

**Comment by cdmihai** [comment]
Test comment
