### ISSUE TITLE
SecurityUtilities.SignFile: NullReferenceException when the supplied certificate has no private key.

### ISSUE THREAD

**Issue by davecluderay** [Microsoft/msbuild#71]
Calls to _SecurityUtilities.SignFile_ referencing a certificate that does not include a private key result in a very non-specific _NullReferenceException_. This would be easier for the caller to fix if a more useful message were provided.

Based on what's already thrown from that method, I would suggest something like an _InvalidOperationException_ with the message: "MSB3487: The signing certificate does not include private key information."

**Comment by ValMenn** [comment]
MSBuild triage: sounds good
