### ISSUE TITLE
Support Reference in external msbuild target file

### ISSUE THREAD

**Issue by enricosada** [Microsoft/msbuild#714]
So when i want to add a reference to an assembly

``` xml
    <Reference Include="nunit.framework">
        <HintPath>..\..\..\packages\NUnit.3.0.0\lib\net46\nunit.framework.dll</HintPath>
    </Reference>
```

i need to specify the path. **That OK, easy do understand**

The problem is: I cannot (like other properties), add reference from an imported msbuild target file.

It's possibile to add an extensibility to (or):
- define `<Reference` in imported msbuild targets
- or (dont know if work well with ides), add programmatically with task the references.

an example

references.msbuild

``` xml
    <Reference Include="nunit.framework">
        <HintPath>..\..\..\packages\NUnit.3.0.0\lib\net46\nunit.framework.dll</HintPath>
    </Reference>
```

in my csproj/fsproj:

``` xml
  <Import Project="references.msbuild" />
  <!-- the assembly is imported -->
```

**why?**

it help to share common references, or external tool can programmatically generate the expected references.
the file with references can be .gitignore and regenerated at will.
Otherwise i need to update the csproj/fsproj files, that's bad, because is it's the project file and changes should be committed each time.

**Comment by rainersigwald** [comment]
You should be able to do this. What errors are you seeing when you try?

Guesses:
* is `references.msbuild` a well-formed project?
* Is the `<Reference>` tag in the imported project inside an `<ItemGroup>`?

**Comment by jeffkl** [comment]
This should work, please re-open if you're still in need of help
