### ISSUE TITLE
Cannot find download / install the latest instruction

### ISSUE THREAD

**Issue by vors** [Microsoft/msbuild#725]
I see the docs about building from source, but I don't see anything about "where to download the latest and greatest artifacts". On the build server in artifacts I see just logs.

**Comment by vors** [comment]
Releases don't have attached downloads besides the source code.

**Comment by rainersigwald** [comment]
We're still in an awkward transition: our only official releases (so far) are from our internal repo. Links to the official installers corresponding to them are in each release tag.

NuGet packages built from the xplat branch are available from the https://dotnet.myget.org/gallery/dotnet-buildtools MyGet feed. If you just want some cross-platform bits to try out, there are instructions at https://github.com/Microsoft/msbuild/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild#unofficial-getting-net-core-msbuild-binaries-without-building-the-code

This is all vastly more complicated than it should be and we're working toward fixing it. It'd help to know what you hoped for when you started looking.

**Comment by jeffkl** [comment]
We now have NuGet packages for prerelease versions on NuGet.org and MSBuild is part of the [dotnet CLI](https://github.com/dotnet/cli#installers-and-binaries) which has install-able drops for trying out new stuff.
