### ISSUE TITLE
Can we have a room on Gitter?

### ISSUE THREAD

**Issue by xied75** [Microsoft/msbuild#738]
So that MSBuild can join the rest of the family. :)

**Comment by akoeplinger** [comment]
It's been there for quite a while already: https://gitter.im/Microsoft/msbuild :)

**Comment by xied75** [comment]
It wasn't suggested to me on the left hand side so I thought it doesn't exist. :)

Sorry.

**Comment by Sarabeth-Jaffe-Microsoft** [comment]
Gitter badge added to our README again. Thanks!
