### ISSUE TITLE
Microsoft Build Tools 2015 Update 3

### ISSUE THREAD

**Issue by afscrome** [Microsoft/msbuild#740]
Where can I download update 3 of the build tools.

It seems to be listed at https://www.visualstudio.com/downloads/download-visual-studio-vs ( Tools for Visual Studio 2015 > Microsoft Build Tools 2015) , however clicking the download link actually downloads the c++ build tools.

**Comment by rainersigwald** [comment]
It sure does! Thanks for reporting, I'll see if we can get the link fixed.

**Comment by rainersigwald** [comment]
@afscrome It looks like the link is just swapped with the C++ build tools. I'm getting it fixed internally, but you should be able to get Microsoft Build Tools 2015 Update 3 from http://go.microsoft.com/fwlink/?LinkId=691126.

**Comment by rainersigwald** [comment]
Some folks internally fixed the site, and it should have had enough time to propagate through all the appropriate caches. It works on my machine, anyway! Please let us know if you see anything different.

Thanks for catching and filing this, @afscrome!

**Comment by afscrome** [comment]
Cheers

btw, can you edit your link above - looks like they fixed it by swapping the fwlinks, so your link above now points to the c++ tools.

**Comment by rainersigwald** [comment]
> your link above now points to the c++ tools

Naturally! :persevere:

Fixed, thanks.

**Comment by akoeplinger** [comment]
This makes me wonder if other places now point to the wrong thing?
