### ISSUE TITLE
TaskParser probably has a bug in switch de-duplication logic.

### ISSUE THREAD

**Issue by serjic** [microsoft/msbuild#75]
this class operates with two collections:
_switchesAdded
_switchOrderList

In ParseParameter method _switchesAdded map is used under condition. I think the intent was to filter duplicates in _switchOrderList list but _switchesAdded map is never updated.

**Comment by livarcocc** [comment]
This is the piece of code being referred to in TaskParser:

```
            if (!_switchesAdded.Contains(propertyToAdd.Name))
            {
                _switchOrderList.Add(propertyToAdd.Name);
            }
```

If the intent is to de-dup, it is not clear to me why two lists is even necessary.
