### ISSUE TITLE
MSB3277 warning should include the assembly name

### ISSUE THREAD

**Issue by jaredpar** [Microsoft/msbuild#753]
Working on a build change this morning and got the following error (typical of large build changes):

``` 
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3277: Found conflicts between different versions of the sam e dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [some project name]
```

This is a frustrating error because the solution and reference sets are very large.  I can't just glance at the project and know what the problem is.  Using a detailed output build takes a considerable amount of time to complete (plenty in fact to write this issue report).  

Can we change this warning to include the DLL for which there is an issue?  Would make it so much easier to track down the problem.

**Comment by drub0y** [comment]
I haven't had this in a while (luckily), but I know if you turn up the level to detailed you can figure this out, but it's quite a dig. Shouldn't have to be that way, the warning should definitely list it out.

**Comment by rainersigwald** [comment]
Yup, this is a great idea. We're tracking it at #608.
