### ISSUE TITLE
.nuget.props and .nuget.targets files are not loaded in MSBuild on .NET Core

### ISSUE THREAD

**Issue by eerhardt** [Microsoft/msbuild#774]
After https://github.com/NuGet/Home/issues/3102 is fixed.  The next issue that the CLI will be blocked on is that the generated $(ProjectName).nuget.props and $(ProjectName).nuget.targets files are not loaded when using MSBuild on .NET Core.

From my preliminary debugging, it appears that the Common.props/targets files are not loading up the Microsoft.NuGet.props/.targets when on .NET Core.

Normally on desktop builds, these NuGet .props and .targets files are loaded because they are installed to the "ImportBefore"/"ImportAfter" folders in Program Files.  However, these folder locations are not applicable on .NET Core.

This is blocking the CLI using MSBuild to build .csprojs for .NET Core cross-plat.

**Comment by rainersigwald** [comment]
To get this going we'll need `Microsoft.NuGet.ImportAfter.targets` and friends in a NuGet package that we can unpack into an MSBuild directory, or to incorporate that functionality directly into common targets.

Workaround for now: you can get past this by copying the nuget files from `C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.Targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets` to {msbuildlocation}`\Extensions\15.0\Microsoft.Common.targets\ImportAfter\` (and so on for props).

**Comment by cdmihai** [comment]
Being designed in #784
