### ISSUE TITLE
Common TimeoutException when creating nodes

### ISSUE THREAD

**Issue by KirillOsenkov** [microsoft/msbuild#782]
I'm seeing a common TimeoutException when creating nodes during build start:

```
    System.IO.Pipes.NamedPipeClientStream.Connect Line 1234 C#
>   Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.TryConnectToProcess Line 302  C#
    Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.GetNode Line 211  C#
    Microsoft.Build.BackEnd.NodeProviderOutOfProc.CreateNode Line 132   C#
    Microsoft.Build.BackEnd.NodeManager.AttemptCreateNode Line 359  C#
    Microsoft.Build.BackEnd.NodeManager.CreateNode Line 116 C#
    Microsoft.Build.Execution.BuildManager.PerformSchedulingActions Line 1497   C#
    Microsoft.Build.Execution.BuildManager.HandleNewRequest Line 1320   C#
    Microsoft.Build.Execution.BuildManager.IssueRequestToScheduler Line 1094    C#
    Microsoft.Build.Execution.BuildManager.ExecuteSubmission.AnonymousMethod__0 Line 853    C#
    Microsoft.Build.Execution.BuildManager.ProcessWorkQueue Line 968    C#
    Microsoft.Build.Execution.BuildManager.BeginBuild.AnonymousMethod__48_0 Line 443    C#
```

Here, we pass 0 for timeout:
https://github.com/Microsoft/msbuild/blob/master/src/XMakeBuildEngine/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs#L206

and here we throw if the first attempt failed:
https://github.com/Microsoft/msbuild/blob/master/src/XMakeBuildEngine/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs#L289

and here is the actual throw statement:
http://referencesource.microsoft.com/#System.Core/System/IO/Pipes/Pipe.cs,1230

Maybe if we investigate why some of these things fail (and maybe provide a non-zero timeout, say 20ms), we can greatly increase the chance of successful connections to new nodes, thus avoiding spawning unnecessary msbuild.exe processes.

This may be related to https://github.com/Microsoft/msbuild/issues/521

Tip: when debugging these exceptions, set COMPLUS_ZapDisable=1 to see better what's happening under debugger. It'd be nice to understand what are the common reasons for node connection failures (if we only try once due to timeout == 0).

**Comment by rainersigwald** [comment]
This doesn't seem to have been a particularly big problem in the last few years so I'm going to declare by fiat that it's not worth investigating right now.
