### ISSUE TITLE
TargetResult has potential issue with synchronization.

### ISSUE THREAD

**Issue by serjic** [Microsoft/msbuild#80]
Please take a look at its INodePacketTranslatable.Translate method. It calls to InternalTranslate method which modifies '_itemsStore' field. This field is also accessed in other methods and locks are used to ensure synchronized access. But INodePacketTranslatable.Translate method is not called under lock.

**Comment by AndyGerlicher** [comment]
Team Triage: Up-for-grabs, but we would want to see an analysis of the issue and a trace of the issue that would cause a race before accepting a PR.

**Comment by AndyGerlicher** [comment]
Closing. This is very old and there have been no reports of issues. Looking over the code I don't see anything obviously wrong. Please re-open with line numbers (from xplat branch). Or we would likely accept a PR for this if it's just a single lock you think is needed.
