### ISSUE TITLE
Error: Cannot dispose the build manager because it is not idle

### ISSUE THREAD

**Issue by vasiliy-vdovichenko** [microsoft/msbuild#810]
I am using BuildManager in my project in following way:

```
        using (var buildManager = new BuildManager())
        {
            var buildRequestData = new BuildRequestData(_projectPath, globalProperty, null, new[] { "Build" }, null);
            BuildResult buildResult = buildManager.Build(new BuildParameters(pc) { Loggers = new List<ILogger> { logger } }, buildRequestData);
            return buildResult.OverallResult == BuildResultCode.Success; 
        }
```

And sometime it throws following errors;

System.InvalidOperationException: Cannot dispose the build manager because it is not idle.
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInvalidOperation(String resourceName, Object[] args)
   at Microsoft.Build.Execution.BuildManager.Dispose(Boolean disposing)
   at Microsoft.Build.Execution.BuildManager.Dispose()

Accordingly to documentation to Build method:

   Convenience method.  Submits a lone build request and blocks until results are available.

it should block thread until build is finished but it looks like Build method is finished when build process is still in progress.

**Comment by rainersigwald** [comment]
Team triage: there have been many changes in the last few years that could have resolved this; if you're still seeing it please let us know (a repro project would be amazing) and we can reactivate and investigate.
