### ISSUE TITLE
%(Directory) should always be unrooted

### ISSUE THREAD

**Issue by piotrpMSFT** [Microsoft/msbuild#813]
When working with an ItemGroup on Linux one can get a fully qualified path to a resource via `@(IG->'%(Directory)')`. This results in a rooted path e.g. `/path/to/my/item`.

On Windows, the same expression would result in `path\to\my\item` without the leading drive qualifier, therefore providing a non-fully-qualified path to a resource. Obtaining a fully qualified path on Windows requires `@(IG->'%(RootDir)%(Directory)')`.

I'm not familiar with the intention of `%(Directory)` omitting the drive specifier, but the discrepancy was a bit jarring when building a build script on OS X and expecting it to work. I'm fairly familiar with MSBuild so I knew to look at the MSDN documentation for well-known metadata and to identify a fix, but folks less familiar are likely to spend considerable time understanding what went awry. 

It seems that parity might mean that Windows `%(Directory)` values should lead with a `\` to specify that the path is relative to the drive root, with `%(RootDir)` specifying the drive `X:` only. This should provide an equivalent experience between Windows and non-Windows platforms. If that is not possible because it is a breaking change then we may want to consider also requiring `%(RootDir)` on non-Windows platforms as well so that folks are faced with this challenge consistently across all platforms.

**Comment by rainersigwald** [comment]
> I'm not familiar with the intention of %(Directory) omitting the drive specifier

Me either, but I bet it's by analogy to `cmd.exe` shell's `%~p` [parameter extension](http://ss64.com/nt/syntax-args.html). The comment in the source [doesn't explain why](https://github.com/Microsoft/msbuild/blob/70db3602ec75e0e4c50b613eb6588e158d5dfd9f/src/Shared/Modifiers.cs#L359), even though it has to [jump through hoops](https://github.com/Microsoft/msbuild/blob/70db3602ec75e0e4c50b613eb6588e158d5dfd9f/src/Shared/Modifiers.cs#L466-L482) to get that behavior.

I lean toward requiring (or at least allowing) `%(RootDir)` everywhere. I see two options:

1. Change `Directory` behavior: `RootDir` is always `/`, and `%(Directory)` is always relative, like it is on Windows. This would require `%(RootDir)%(Directory)` on all OSes.
1. Change `RootDir` behavior: always expand `RootDir` to the empty string, and keep `%(Directory)` as-is. This would allow `%(RootDir)%(Directory)` everywhere, but if you started on *nix you might break when running on Windows.

**Comment by rainersigwald** [comment]
It looks like Mono `xbuild` went with option 1, which seems like a better idea to me:

```ShellSession
$ cat rootdir.proj 
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <Something Include="$(MSBuildThisFile)" />
  </ItemGroup>
  <Target Name="Print">
    <Warning Text="@(Something)" />
    <Warning Text="@(Something->'RootDir: %(RootDir)')" />
    <Warning Text="@(Something->'Directory: %(Directory)')" />
  </Target>
</Project>
$ ./bin/Debug-NetCore/OSX_Deployment/dotnet ./bin/Debug-NetCore/OSX_Deployment/MSBuild.exe /v:q rootdir.proj
Microsoft (R) Build Engine version 0.0.0.0
Copyright (C) Microsoft Corporation. All rights reserved.

/Users/raines/src/msbuild/rootdir.proj(6,5): warning : rootdir.proj
/Users/raines/src/msbuild/rootdir.proj(7,5): warning : RootDir: /
/Users/raines/src/msbuild/rootdir.proj(8,5): warning : Directory: /Users/raines/src/msbuild/
$ /Library/Frameworks/Mono.framework/Versions/4.4.0/bin/xbuild /v:q rootdir.proj
XBuild Engine Version 14.0
Mono, Version 4.4.0.0
Copyright (C) 2005-2013 Various Mono authors
/Users/raines/src/msbuild/rootdir.proj:  warning : rootdir.proj
/Users/raines/src/msbuild/rootdir.proj:  warning : RootDir: /
/Users/raines/src/msbuild/rootdir.proj:  warning : Directory: Users/raines/src/msbuild/
```

I think we should do that. Any dissent? @radical do you know if that design has caused any problems?

**Comment by radical** [comment]
@rainersigwald I haven't seen any issues with this.

**Comment by rainersigwald** [comment]
Great! Then let's do that.
