### ISSUE TITLE
Support for Ubuntu 16.04

### ISSUE THREAD

**Issue by JunielKatarn** [Microsoft/msbuild#833]
Hi. It's been a few week since .NET Core was released, and it works fine on Ubuntu 16.04.
Therefore, it should be possible to update MSBuild to also support it.

Currently, installing libunwind8 on this version of Ubuntu does not seem to solve the problem.
Sample run:
```
$ uname -a
Linux jurocha-pad 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ sudo apt install libunwind8
$ git clone https://github.com/Microsoft/msbuild.git --branch xplat
$ cd msbuild
$ ./cibuild.sh 
Unsupported target detected: . Configuring as if for CoreCLR
Unsupported host detected: . Configuring as if for CoreCLR
Installing dotnet cli...
Restoring BuildTools version 1.0.25-prerelease-00410-01...
Failed to initialize CoreCLR, HRESULT: 0x80131500
$ cat init-tools.log 
Running: /home/jurocha/Desktop/msbuild/init-tools.sh
Installing 'https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/1.0.0-rc2-002547/dotnet-dev-ubuntu-x64.1.0.0-rc2-002547.tar.gz' to '/home/jurocha/Desktop/msbuild/Tools/dotnetcli/dotnet.tar'
Running: /home/jurocha/Desktop/msbuild/Tools/dotnetcli/dotnet restore "/home/jurocha/Desktop/msbuild/Tools/1.0.25-prerelease-00410-01/project.json" --packages /home/jurocha/Desktop/msbuild/packages --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json
```

Maybe the .NET Core dependency can be bumped to the same version as the official release?

**Comment by rainersigwald** [comment]
I think the problem is that we're downloading and using a fairly old version of the dotnet CLI as the initial bootstrapper to build us the first time. I bet MSBuild would work after bootstrapping.

Conveniently, we will be updating our Build Tools dependency in the not-too-distant future for another reason (fixes to NuGet packaging). @jeffkl when you're done with that can you briefly see if my guess is correct and that fixes our build on 16.04? If it doesn't we'll need to investigate further.

**Comment by jeffkl** [comment]
Okay here's the problem, we're statically setting the Runtime Identifier (RID) to `ubuntu.14.04` [here](https://github.com/Microsoft/msbuild/blob/xplat/dir.props#L192).  We really should be detecting the RID via the [RuntimeEnvironment](https://github.com/dotnet/core-setup/blob/master/src/Microsoft.DotNet.PlatformAbstractions/RuntimeEnvironment.cs#L9) class in .NET Core.

We can also get the correct RID in our `cibuild.sh` in the same way that `init-tools.sh` does [here](https://github.com/Microsoft/msbuild/blob/xplat/init-tools.sh#L20).

The second option would be a lot easier to implement but the first option is a better long term solution.  There is no MSBuild task for getting the RuntimeEnvironment so we'd either have to write our own or expose a static method.

**Comment by rainersigwald** [comment]
I vote go the second way and then let the magic of the CLI solve this for us long-term.

**Comment by JunielKatarn** [comment]
Greetings. I just tried this change, but it still fails. Here are the init-tools.log contents:
```
Running: /home/user/ws/msbuild/init-tools.sh
Installing 'https://dotnetcli.blob.core.windows.net/dotnet/Sdk/1.0.0-preview3-003686/dotnet-dev-ubuntu.16.04-x64.1.0.0-preview3-003686.tar.gz' to '/home/user/ws/msbuild/Tools/dotnetcli/dotnet.tar'
Running: /home/user/ws/msbuild/Tools/dotnetcli/dotnet restore "/home/user/ws/msbuild/Tools/1.0.26-prerelease-00826-05/project.json" --no-cache --packages /home/user/ws/msbuild/packages --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json --legacy-packages-directory
log  : Restoring packages for /home/user/ws/msbuild/Tools/1.0.26-prerelease-00826-05/project.json...
error: Unable to load the service index for source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json.
error:   The type initializer for 'System.Net.Http.CurlHandler' threw an exception.
error:   The type initializer for 'Http' threw an exception.
error:   The type initializer for 'HttpInitializer' threw an exception.
error:   Unable to load DLL 'System.Net.Http.Native': The specified module could not be found.
error:    (Exception from HRESULT: 0x8007007E)
Running: /home/user/ws/msbuild/packages/Microsoft.DotNet.BuildTools/1.0.26-prerelease-00826-05/lib/init-tools.sh /home/user/ws/msbuild /home/user/ws/msbuild/Tools/dotnetcli/dotnet /home/user/ws/msbuild/Tools
```

(Note: Using a standard Ubuntu 16.04, x64 installation).

Please reopen this issue.

**Comment by jeffkl** [comment]
@emgarten or @eerhardt do either of you know what could cause this or who would know?  It's working fine in [our CI](https://ci.dot.net/job/Microsoft_msbuild/job/master/job/_Ubuntu16.04_CoreCLR_prtest/8/console) and on my local machine.

**Comment by eerhardt** [comment]
@JunielKatarn - Do you have all the prereqs installed on the machine?  See https://github.com/dotnet/core/blob/master/Documentation/prereqs.md

**Comment by JunielKatarn** [comment]
I didn't know about the full dependency list (was only aware of libunwind8*).
It builds successfully after installing all the list.
Thanks!

**Comment by anotherbugmaster** [comment]
Please mention full dependencies list here:

https://github.com/Microsoft/msbuild/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild

**Comment by rainersigwald** [comment]
@anotherbugmaster Good catch; I [updated the instructions](https://github.com/Microsoft/msbuild/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild/86f39a42156c5a7d3538412f6f0146e9b5c2a6f0). The easiest way to get going now is to just install the .NET Core SDK, which brings in the appropriate dependencies.
