### ISSUE TITLE
3 tests fail when VS 2010 is installed

### ISSUE THREAD

**Issue by ctaggart** [Microsoft/msbuild#85]
If any of the Visual Studio 2010 products are installed, three tests fail. 

The failed tests are listed here:
https://github.com/Microsoft/msbuild/pull/61#issuecomment-98394867

Detailed troubleshooting of the issue is here:
https://github.com/ctaggart/msbuild/issues/1

**Comment by jeffkl** [comment]
I'm closing this for now as we don't hit it directly.  We are going to improve the unit tests as soon as the new .NET Core SDK is ready.
