### ISSUE TITLE
ur-Target

### ISSUE THREAD

**Issue by kingces95** [microsoft/msbuild#851]
I've got a problem that would benefit from the ability to define an "ur-target" (a target which would execute if no named target matches the target passed at the command line) and the ability to reflect over the current target (e.g. MSBuildTarget). 

My project defines a "tree of platforms" and, given a platform that represents a node in the tree, will recursively walk the tree and, upon reaching a leaf, will execute a target against one of the projects types I am aggregating. I implement this by including a different target files depending on the type of platform. For platforms representing nodes in the tree I include a "stubs targets file" which defines stub targets for a set of well known targets (e.g. Build, Clean, Rebuild, Compile, etc) which implement the recursive step. For platforms representing leaves I include the targets file for the aggregated platform. The problem is the "stubs targets file" needs a stub target for all possible targets and it's there I'd like to define an ur-target.

For example, if I am aggregating Android, iOS and Windows mobile projects, then I would define a platform "mobile" which would be the root of a tree with three leafs -- one for each aggregated project. When I pass `/p:platform=mobile /t:build` then all three sub projects build. Similarly, when I pass `/p:platform=mobile /t:clean` all three projects are cleaned. Each target requires a stub that preforms the recursion and I'd like to replace all those targets with the ur target.

One possible implementation might be to have a reserved target name, say `*`. Then I could write something like the following:

```
<PropertyGroup>
    <ProjPath>$(MSBuildProjectFullPath)</ProjPath>
    <CurTarget>$(MSBuildTarget)</CurTarget>
</PropertyGroup>

<Target Name="*" Condition="'$(Platform)'=='mobile' >
    <MSBuild Projects="$(ProjPath)" Properties="platform=ios" Targets="$(CurTarget)" />
    <MSBuild Projects="$(ProjPath)" Properties="platform=android" Targets="$(CurTarget)" />
    <MSBuild Projects="$(ProjPath)" Properties="platform=windows" Targets="$(CurTarget)" />
</Target>
```

Warm regards,
Chris

**Comment by rainersigwald** [comment]
Team triage: since this hasn't gotten much attention over the years we're not likely to implement it. Closing as won't-fix.
