### ISSUE TITLE
Builds fail when SDK installed to non-default path

### ISSUE THREAD

**Issue by AndyGerlicher** [microsoft/msbuild#855]
Customer reported issue building project that use SDKs installed to non-standard location. For example from [Microsoft.Common.CurrentVersion.targets](https://github.com/Microsoft/msbuild/blob/master/src/XMakeTasks/Microsoft.Common.CurrentVersion.targets#L1949)

``` XML
<PropertyGroup>
  <SDKExtensionDirectoryRoot>$(MSBuildProgramFiles32)\Microsoft SDKs\Windows Kits\10</SDKExtensionDirectoryRoot>
<PropertyGroup>
```

The only workaround is to override this property in your build or reinstall the SDK to the expected location.

**Comment by rainersigwald** [comment]
Team triage: No additional traffic on this in 3 years. Closing.
