### ISSUE TITLE
Rebuild target cleans project reference even if it is not selected to build. Different from Visual Studio.

### ISSUE THREAD

**Issue by cosmic-cosmo** [microsoft/msbuild#865]
MSBuild will call clean on project references when executing the rebuild target even if the project is not selected to be built in the configuration. For example, suppose you have a solution with two projects: _PrjA_ and _PrjB_. _PrjB_ references _PrjA_. Now suppose _PrjA_ is configured not to be built through the configuration manager. Maybe it is already built as part of another solution. Assume _PrjA_ is already built through whatever means. In Visual Studio, rebuilding the solution succeeds. If you try to build the solution with MSBuild, calling the **rebuild** target, clean gets called on _PrjA_ making it unavailable for _PrjB_, which will fail to build.

**Comment by rainersigwald** [comment]
Team triage: This is unfortunate but doesn't seem to be hitting too many people; we'll invest elsewhere.
[solution-dependency-rebuild.zip](https://github.com/microsoft/msbuild/files/3752916/solution-dependency-rebuild.zip)
