### ISSUE TITLE
MSBuild package doesn't contain MSBuild.exe.config

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#872]
Since toolsets are defined in `MSBuild.exe.config`, it's required for successful use of MSBuild. But none of our current NuGet packages contain it.

**Comment by rainersigwald** [comment]
Note that after #883 MSBuild for .NET Core won't look for this file, so it's not required that we ship it. If we change that we should revisit this.

**Comment by jeffkl** [comment]
Fixed in #1080
