### ISSUE TITLE
msbuild should integrate with Maestro so downstream teams can automate taking a new version

### ISSUE THREAD

**Issue by eerhardt** [microsoft/msbuild#878]
In order to automate taking new msbuild builds, msbuild should write a build info file to https://github.com/dotnet/versions/tree/master/build-info/.  This allows any team to get notifications when a new build is available, and the team can write automation that creates an automatic PR for their repo to take the new msbuild build.

See the documentation https://github.com/dotnet/versions#net-versions and https://github.com/dotnet/versions/tree/master/Maestro#maestro.

See https://github.com/dotnet/versions/blob/master/build-info/dotnet/roslyn/netcore1.0/Latest_Packages.txt as an example.

There are two options available in dotnet/buildtools that allow an easy way to write these files:
- an MSBuild task: https://github.com/dotnet/buildtools/blob/fix-unix-runner-verbosity/src/Microsoft.DotNet.Build.Tasks/PackageFiles/VersionTools.targets
- a .NET Core library: https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.VersionTools/Automation/VersionsRepoUpdater.cs

During an official build, you can invoke this code that will write out a new build-info file to dotnet/versions.  Talk to @eerhardt or @dagood for more information.

**Comment by livarcocc** [comment]
MSBuild is now integrated with DARC. The newer version of Maestro.
