### ISSUE TITLE
Microsoft.Common.props should be contained in a "15.0" directory

### ISSUE THREAD

**Issue by eerhardt** [Microsoft/msbuild#882]
The nuget package at:  https://dotnet.myget.org/feed/dotnet-buildtools/package/nuget/Microsoft.Build.Targets/0.1.0-preview-00029-160805  contains the Microsoft.Common.props file in a "14.1" directory.

However, the latest MSBuild expects this file to be contained in a "15.0" directory.

We need to update the nuget package to place this file in a directory named "15.0".

@rainersigwald @jeffkl @AndyGerlicher

**Comment by jeffkl** [comment]
I fixed this in cbcc30378a574e8c0bd2828839f0510035fdc08e.  We're working on a signing issue and I'll get new packages posted.

**Comment by jeffkl** [comment]
This is fixed and the package is available at https://dotnet.myget.org/feed/msbuild/package/nuget/Microsoft.Build.Runtime/15.1.262-preview5
