### ISSUE TITLE
Build spew for Windows NT CoreCLR says "File not found (2)"

### ISSUE THREAD

**Issue by jasonwilliams200OK** [Microsoft/msbuild#887]
Here is one example: http://dotnet-ci.cloudapp.net/job/Microsoft_msbuild/job/_Windows_NT_CoreCLR_prtest/92/consoleText

There are 1387 occurrences of "File not found (2)", and this is only happening in Windows NT with --target CoreCLR build.

**Comment by rainersigwald** [comment]
This was fixed by #756 (thanks @anurse!). As soon as we get an updated known-good MSBuild into Build Tools, it'll go away entirely.
