### ISSUE TITLE
Empty item allowed in targets but not outside of targets

### ISSUE THREAD

**Issue by cdmihai** [microsoft/msbuild#900]
This snippet fails with `error MSB4035: The re
quired attribute "Include" is empty or missing from the element <i>.`

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <ItemGroup>
        <i/>
    </ItemGroup>
</Project>
```

This snippet does not fail:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Target Name="build">
        <ItemGroup>
            <i/>
        </ItemGroup>
    </Target>
</Project>
```

The test for this case only checks out of target items: https://github.com/Microsoft/msbuild/blob/master/src/XMakeBuildEngine/UnitTestsPublicOM/Construction/ProjectItemElement_Tests.cs#L43-L59

This looks more like a bug rather than a feature.

**Comment by cdmihai** [comment]
This test on the other hand says this is OK: https://github.com/Microsoft/msbuild/blob/master/src/XMakeBuildEngine/UnitTestsPublicOM/Construction/ConstructionEditing_Tests.cs#L716-L737

**Comment by DoCode** [comment]
Any news here?

**Comment by cdmihai** [comment]
Closed as duplicate of #955

@DoCode, #955 shows a workaround for out of targets items.

**Comment by DoCode** [comment]
@cdmihai and what's the workaround for outside of targets? 
This here:
```xml
<ItemGroup>
  <Compile Update="@(Compile)" />
</ItemGroup>
```

**Comment by cdmihai** [comment]
Yes
