### ISSUE TITLE
Allow RemoveProperty to be specified as metadata on Projects passed to msbuild

### ISSUE THREAD

**Issue by kingces95** [Microsoft/msbuild#902]
Can we allow RemoveProperty to be specified as metadata on the Project passed to msbuild in addition to being an attribute on msbuild? 

For example:

```
<ItemGroup>
    <Project Include="my.csproj">
        <RemoveProperty>Foo</RemoveProperty>
    </Project>
</ItemGroup>
<MsBuild Projects="@(Project)" />
```

**Comment by rainersigwald** [comment]
There is such a metadatum: `UndefineProperties`. It's used [here](https://github.com/Microsoft/msbuild/blob/90dd899b25ee2da71a5440f3d2b6f61123d2a14f/src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/MSBuild.cs#L780).

(I discovered this when looking for something else. It was news to me!)
