### ISSUE TITLE
Tests fail when run in Visual Studio

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#909]
@maddin2016 first pointed this out in #742, but I see it too when running tests in Visual Studio--many tests fail with

```
Message: System.TypeInitializationException : The type initializer for 'BuildEnvironmentHelperSingleton' threw an exception.
---- System.InvalidOperationException : Could not determine a valid location to MSBuild. Try running this process from the Developer Command Prompt for Visual Studio.
```

**Comment by maddin2016** [comment]
Hi @rainersigwald, current workaround for me is to add `MSBUILD_EXE_PATH` to environment variables. But i think main problem is the logic to check for a possible location of msbuild.exe
https://github.com/Microsoft/msbuild/blob/master/src/Shared/BuildEnvironmentHelper.cs#L64

**Comment by jeffkl** [comment]
I think this is fixed.  I can run tests in Visual Studio if I copy xunit assemblies out of Windows_NT_Deployment_Test into Output.  When we convert the projects to the new SDK, we'll make sure the tests run in VS.
