### ISSUE TITLE
Ignoring multiple imports

### ISSUE THREAD

**Issue by mhutch** [Microsoft/msbuild#910]
Importing a target/props file multiple times causes a MSB4011 warning. The only mechanism to avoid it is to condition the import to happen only when some property is empty. This places the burden on the importer, and cannot be done for transitive imports.

I propose that a mechanism is added for project files to suppress this warning:

```
<Project DefaultTargets="Build" ToolsVersion="15.0" IgnoreMultipleImport="true">
```

**Comment by rainersigwald** [comment]
Do you envision this having an effect other than silencing the warning `MSB4011 : "{0}" cannot be imported again. It was already imported at "{1}". This is most likely a build authoring error. This subsequent import will be ignored.`?

**Comment by mhutch** [comment]
Ah, my bad, `xbuild` does not have that warning and after the mailing list post I assumed msbuild had the same issue.

So yes, it would just silence the warning.

**Comment by radical** [comment]
`xbuild` does emit that warning:

`/Users/ankit/test/msbuild/time.proj:  warning : Cannot import project 'time2.proj' again. It was already imported by '/Users/ankit/test/msbuild/time.proj'. Ignoring.`

**Comment by mhutch** [comment]
Sorry, guess I misremembered :)

**Comment by jeffkl** [comment]
You will be able to at least suppress this when I close #68 😄
