### ISSUE TITLE
Exceptions thrown by ToolTask aren't diagnosable

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#911]
We got a report of an internal build that failed with this error:

```
Microsoft.CppCommon.targets(356,5): error MSB6003: The specified task executable "CL.EXE" could not be run. Access to the path 'F:\REDACTED\x86\CL.read.1.tlog' is denied.
```

That's thrown from [`ToolTask`](https://github.com/Microsoft/msbuild/blob/204cfd215fdc1c92322b0b22165cc8c4c3259e02/src/Utilities/ToolTask.cs#L1676), which uses this method:

``` C#
/// <summary>
/// This method takes in an exception and if MSBuildDiagnostics is set then it will display the stack trace
/// if it is not set only the message will be displayed, this is to fix the problem where the user was getting
/// stack trace when a shorter message was better
/// </summary>
/// <returns>exception message</returns>
private string GetErrorMessageWithDiagnosticsCheck(Exception e)
{
    // If MSBuildDiagnostics is set show stack trace information
    if (Environment.GetEnvironmentVariable("MSBuildDiagnostics") != null)
    {
        // Includes stack trace
        return e.ToString();
    }
    else
    {
        // does not include stack trace
        return e.Message;
    }
}
```

This was clearly intentionally added (it looks like it was in the Orcas/VS2008 time frame), but it seems like a bad idea--it makes the error above basically undiagnosable, because you have no idea what's complaining about permissions.

MSBuild should at least log the stack to the higher logging verbosities, though it might be better to just roll back to including the whole stack trace all the time.

**Comment by akoeplinger** [comment]
There's similar code in TaskLogginHelper.LogErrorFromException().

**Comment by jaredpar** [comment]
> MSBuild should at least log the stack to the higher logging verbosities, though it might be better to just roll back to including the whole stack trace all the time.

Which higher level verbosities were you considering?

**Comment by cdmihai** [comment]
Since the environment variable that enables the stack dump is `"MSBuildDiagnostics"`, then Diagnostic level sounds like a good place.

**Comment by jaredpar** [comment]
@cdmihai 

I'd argue for it being lower.  My (possibly incorrect) view of diagnostics is to discover why MSBuild is behaving the way it did.  Generally this is used to track down bugs in my build definitions / tasks.  Basically helping me diagnose the bad things I did in my build files. 

Exceptions in build tasks are the opposite.  I've asked the task to do what should be a valid operation and it's failing due to an unanticipated scenario.  My build tasks are valid here, the task is wrong.  Hence this should show up during normal execution of MSBuild.

**Comment by rainersigwald** [comment]
I think I agree, and would prefer to just log the stack trace all the time (in this exceptional circumstance).
