### ISSUE TITLE
Dev versions of MSBuild should put the version with commit ID in the logo

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#918]
We get banners like

```
Microsoft (R) Build Engine version 15.1.188.30335
Copyright (C) Microsoft Corporation. All rights reserved.
```

But it'd be really nice (for like 8 people) if that had the full form of the version that includes the git commit ID for easy checkout.

**Comment by jasonwilliams200OK** [comment]
> for like 8 people

Heh, I think many people are interested in git SHA-1 hashes these days and tend to do creative stuff (like using node.js to download the source of some project and compile it on the fly for some weird reasons..)

**Comment by jeffkl** [comment]
This doesn't quite work yet because only official builds have the assembly informational version for full framework and .NET core.  I'm going to defer this to when we are using the new SDK.

**Comment by rainersigwald** [comment]
Note that you can get a commit from just our version, though, using a script in one of the NuGet packages we use:

```
s:\msbuild>powershell packages\nerdbank.gitversioning\1.5.46\tools\Get-CommitId.ps1 15.3.124.61808
70f1aaadd4eb5cb4cdf123f7b735c9ffe11ed206
```
