### ISSUE TITLE
Add extensibility to solution metaproj

### ISSUE THREAD

**Issue by emgarten** [Microsoft/msbuild#920]
NuGet restores are typically done at the solution level. With the move to msbuild there needs to be a way to run *msbuild /t:restore Solution.sln*

Today this can work when adding Before.{sln}.targets to add restore to the metaproj. However this isn't an option for the dotnet restore/NuGet tools. 

To support this it looks like the restore target needs to be added into the default metaproj, or a generic hook that could be used to load targets without having to use Before.{sln}.targets.

The current restore target is part of ImportsAfter for the CLI and allows projects to be restored using *msbuild /t:restore project.csproj*

https://github.com/NuGet/NuGet.Client/blob/792f2b197f097fe4a0993912b0e7d6ec50cfc5e5/src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets

**Comment by rainersigwald** [comment]
@emgarten Just looked at this again and we do import `$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\SolutionFile\ImportAfter\*` as well as the local version. Is that sufficient, or do you want a property-valued import that you can set from the outside?

**Comment by rrelyea** [comment]
Yes, this worked for @emgarten  - thx.

**Comment by rainersigwald** [comment]
Great. I'm going to close this since it looks good for y'all. Please let us know if a more specific need arises.
