### ISSUE TITLE
Create NuGet packages for MSBuild 14.0

### ISSUE THREAD

**Issue by jeffkl** [Microsoft/msbuild#926]
Package should contain the following assemblies:

* ref
 * netstandard1.3
 * net45
* lib
 * net45

1. Check in stuff under build\pkg
2. Ensure everything is signed correctly.
3. Package version will be 14.3.0 where 3 is the VS update number.  Will use -prerelease tag until everything is tested and signed off.  Will rev the build number when we service the package.
4. Push packages to NuGet.org 

Related to #490

**Comment by jasonwilliams200OK** [comment]
@jeffkl, is it published? Can this and #490 issues be closed?

**Comment by jeffkl** [comment]
Yes, I've just pushed them to NuGet.org.  I'll leave them as -prerelease until probably next week when enough people have tried them out and then I'll remove the tag.

https://www.nuget.org/packages/Microsoft.Build/
https://www.nuget.org/packages/Microsoft.Build.Framework/
https://www.nuget.org/packages/Microsoft.Build.Utilities.Core/
https://www.nuget.org/packages/Microsoft.Build.Tasks.Core/
https://www.nuget.org/packages/Microsoft.Build.Conversion/
https://www.nuget.org/packages/Microsoft.Build.Engine/

**Comment by jasonwilliams200OK** [comment]
Great! Thank you! :tada:

**Comment by jasonwilliams200OK** [comment]
@jeffkl,

https://www.nuget.org/packages/Microsoft.Build.Conversion/ is actually https://www.nuget.org/packages/Microsoft.Build.Conversion.Core/

And both https://www.nuget.org/packages/Microsoft.Build.Conversion.Core/ and https://www.nuget.org/packages/Microsoft.Build.Engine/ are only supported for net45 TFM. Are they coming to netstandard1.3 like rest of the packages? Is there an issue tracking their port to .NET Core?

**Comment by jeffkl** [comment]
Thanks I've updated my comment with the correct link to Microsoft.Build.Conversion.Core.  I was told that both Microsoft.Build.Engine and Microsoft.Build.Conversion.Core are considered "legacy" and we don't really want people to consume them anymore.  Do you need to reference them for anything where you want to compile something against .NET Core?

**Comment by jasonwilliams200OK** [comment]
Thanks @jeffkl. I just found out that `StrongNameKeyPair` was not exposed in `System.Reflection` from BCL, and yet the features are guarded by `#if FEATURE_STRONG_NAMES` in MSBuild. I was under the impression that Engine has it defined somewhere. But I guess we will have to wait for 1.2.0: https://github.com/dotnet/corefx/issues/10530 then remove that guard in `StrongNameHelpers.cs:` (with define constant in `dir.prop`). :)
