### ISSUE TITLE
Toolset validation runs when not necessary

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/msbuild#927]
Related to #881, @brthor saw some problems running unit tests for an app that uses MSBuild's construction APIs, but _doesn't_ run builds.

Ideally, we could disambiguate between scenarios: if the user is using our code but doesn't need a toolset, we shouldn't error that we can't find a valid toolset. But if they're starting a build, we need to whine when we can't find a copy of MSBuild.exe to start our multiproc build.

**Comment by piotrpMSFT** [comment]
@rainersigwald any thoughts on when this will be fixed?

**Comment by rainersigwald** [comment]
Team triage: we don't think this is worth the time.
