### ISSUE TITLE
Exclude not working with escaped characters

### ISSUE THREAD

**Issue by cdmihai** [Microsoft/msbuild#931]
It appears there is a regression with Exclude and Remove tags not excluding escaped names. `<Compile Include=”a?b.my” Exclude=”a%27b.my” />` (or with a `<Compile Remove=”a%27b.my” />` still includes `a’b.my`. This worked with previous builds.

**Comment by cdmihai** [comment]
@jviau I created this from your email, for tracking purposes.

**Comment by rainersigwald** [comment]
This might also be related to #724.
