### ISSUE TITLE
WriteCodeFragment fails in .NET Core MSBuild if input has braces

### ISSUE THREAD

**Issue by nguerrera** [microsoft/msbuild#937]
### Repro steps
``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <Description>There's a bug {here}</Description>
  </PropertyGroup>
</Project>
```

`dotnet build`

### Expected

Builds successfully

### Actual

```
error MSB4018: The "WriteCodeFragment" task failed unexpectedly.
error MSB4018: System.FormatException: Input string was not in a correct format.
error MSB4018:    at System.Text.StringBuilder.FormatError()
error MSB4018:    at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
error MSB4018:    at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
error MSB4018:    at System.String.Format(String format, Object[] args)
error MSB4018:    at Microsoft.Build.Tasks.WriteCodeFragment.GenerateCodeCoreClr(String& extension)
error MSB4018:    at Microsoft.Build.Tasks.WriteCodeFragment.Execute()
```

The best fix for this would be to remove the CODEDOM ifdefs and use the same code as .NET Framework in .NET Core msbuild. A regression test should also be added.

### Original bug description, focusing more on code inspection than scenario

By code inspection, it appears that the inputs to WriteCodeFragment inputs aren't escaped in the xplat (non-CodeDOM) implementation.

See https://github.com/nguerrera/msbuild/blob/71bf8112fbb1ec2115631c9d2e8db3412004ff5e/src/XMakeTasks/WriteCodeFragment.cs#L360

I believe this will fail if _ParameterN has text that needs to be escaped. (e.g. imagine if there are embedded quotes in the value.) **EDIT:** Quotes and other things were fixed in #1369, but braces are still a problem as they throw off String.Format.

I also don't understand the non-string side of that `?:` expression because the CodeDOM equivalent casts unconditionally to string and why do we expect non-strings to be quoted in their ToString() output?

Spotted while investigating #935

**Comment by rainersigwald** [comment]
At this point I think we should remove the non-CodeCOM implementation; we should be able to use CodeDOM everywhere now, right?

**Comment by nguerrera** [comment]
Yes, do we already use the CodeDom implementation everywhere? Should this track removing the dead code or do we have something else tracking that?

**Comment by rainersigwald** [comment]
Ah, fat-fingered the button. Yeah, we should track removing the ifdef here.

**Comment by rainersigwald** [comment]
This turns out to not be trivial:

```
WriteCodeFragment.cs(142,41): error CS0234: The type or namespace name 'ConfigurationException' does not exist in the namespace 'System.Configuration' (are you missing an assembly reference?) [S:\msbuild\src\Tasks\Microsoft.Build.Tasks.csproj]
GenerateResource.cs(3471,35): error CS0103: The name 'StronglyTypedResourceBuilder' does not exist in the current context [S:\msbuild\src\Tasks\Microsoft.Build.Tasks.csproj]
```

For the latter, I think we might need to resurrect #3819.

I think we should do it. There's joy and security in deleting code. Penciling in for 16.4.

**Comment by nguerrera** [comment]
Triage note: a customer hit this in https://github.com/dotnet/core/issues/3205

**Comment by nguerrera** [comment]
Changing title back to customer visible impact. The fix will be to use CodeDOM everywhere and remove ifdefs, but that's not the bug.

**Comment by nguerrera** [comment]
Looks like #1369 fixed the escaping for the most part. Embedded quotes now work, but the remaining bug is when there are braces.

**Comment by nguerrera** [comment]
Fixed the title once more, and added repro steps.

**Comment by nguerrera** [comment]
@rainersigwald Am I following right that this should become easy once https://github.com/microsoft/msbuild/pull/4588 is in?

**Comment by rainersigwald** [comment]
Yeah, I think so. I will have already seen a bunch of the same errors and know how to deal with them.

**Comment by HarkinsDave** [comment]
Nice! Thanks @nguerrera !  I didn't realize it was an escaping issue.
