### ISSUE TITLE
Checking the Source Code of MSBuild with PVS-Studio

### ISSUE THREAD

**Issue by skhrenov** [Microsoft/msbuild#940]
Developers of PVS-Studio C/C++/C# static analyzer present their check report of the source code of 'MSBuild' in the article, containing the review of the most suspicious code fragments they discovered.

You can read article at the official site:
http://www.viva64.com/en/b/0424/

**Comment by NicoJuicy** [comment]
This looks more like an ad then an actual bug report, have you found actual bugs or errors? Please mention that instead of linking to a list of warnings.

**Comment by KindDragon** [comment]
It's hard to tell from most compiler or static analyzer warnings will it cause actual bugs or errors

**Comment by NicoJuicy** [comment]
He also doesn't know github https://github.com/skhrenov 1 contribution ( this one) ever :)

**Comment by KindDragon** [comment]
Please be friendly

**Comment by nigurr** [comment]
https://medium.com/@sofiafateeva93/checking-the-source-code-of-msbuild-with-pvs-studio-36d71762d705

**Comment by rainersigwald** [comment]
We're interested in bugs or errors found in the code, regardless of the source, but not in adopting a specific static analysis tool. Feel free to file specific bugs for problems (or send PRs with fixes!).
