### ISSUE TITLE
Update NuGet packages to include symbols

### ISSUE THREAD

**Issue by jeffkl** [Microsoft/msbuild#969]
Symbols are already uploaded to symweb by MicroBuild but we'll also need to create separate packages containing symbols and upload them to MyGet and NuGet

Related to #926 
- It looks like [BuildTools](https://github.com/dotnet/buildtools/blob/9043737bb296857f3333732a6582ef116ec735f3/src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetPack.cs#L175) requires that the package also includes source code.

**Comment by jeffkl** [comment]
Our symbols are available so no need to have them in a NuGet package

**Comment by rainersigwald** [comment]
Have we validated that external symbol servers ship the unmangled symbols with source server support?

**Comment by jeffkl** [comment]
I thought PdbGit was our solution?
