### ISSUE TITLE
Error building when project has percent '%' char in the path

### ISSUE THREAD

**Issue by TioLuiso** [Microsoft/msbuild#985]
We work with mercurial and hgflow
When a feature branch is created in hgflow, by default the branch will be named like 'feature/[FEATURENAME]'
When Jenkins wants to build that branch, creates a folder with the branch name. But it escapes the slash, resulting in something like 'feature%2F[FEATURENAME]'
Then when Jenkins launches MSBuild, the build will fail because it unescapes paths, and tries to find everything inside 'feature/[FEATURENAME]'. But that folder does not exist.

Why does MSBuild try to Unescape the path always?

**Comment by rainersigwald** [comment]
@TioLuiso What is the exact error message that you see? I just talked to @cdmihai about this and we suspect that the fix might be to escape the values we feed into `$(MSBuildThisFileDirectory)` and friends, but it would depend on exactly what's failing.

**Comment by cdmihai** [comment]
@rainersigwald looked over it and the exception is thrown here:https://github.com/Microsoft/msbuild/blob/master/src/XMakeBuildEngine/Construction/ProjectRootElement.cs#L1946

I guess we'll have to read the file ourselves and pass it into `XmlTextReader` as a string

**Comment by rainersigwald** [comment]
We also peeked into the internals of `XmlTextReader` and it looks like this is because it treats any call to its string constructor as a "UriString". I guess it doesn't escape it properly there.

I don't think we'll have to read + pass a string--we should be able to pass a `Stream`.

**Comment by TioLuiso** [comment]
@rainersigwald hmmmm. The tricky thing is that path-wise could be very well that both unescaped and escaped paths correspond to two valid and different folders. In my example above:
Unescaped : 'feature/[FEATURENAME]' is a valid folder name
Escaped: 'feature%2F[FEATURENAME]' is a valid folder name different from the one above.

So I believe the trick is not to escape or unescape the Project folder, but keep it as it is.

I ignore whether this is practic or even feasible. So I beg your pardon in case my suggestion is aberrant

**Comment by TioLuiso** [comment]
@cdmihai That's it

**Comment by rainersigwald** [comment]
Escaping the path wouldn't affect the `feature/[FEATURENAME]` versus `feature%2F[FEATURENAME]` case, because escaping the first string wouldn't change it--we'd only escape URL characters. But that might cause its own problems (for example with spaces, which are legal path characters but become `%20` in a URL).

I think the best thing to do here is to work around the `XmlTextReader` issue and see if that fixes everything (we can only hope), or if there are lingering issues.
