### ISSUE TITLE
Documentation error: call dotnet command instead of corerun

### ISSUE THREAD

**Issue by muojp** [Microsoft/msbuild#991]
Hi. I gave a shot on xplat msbuild today and noticed a tiny issue on the wiki page: https://github.com/Microsoft/msbuild/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild

On the page, it says you can invoke msbuild by calling

> ./Tools/corerun ./Tools/MSBuild.exe /path/to/project

but `corerun` is not called any longer on xplat branch starting at https://github.com/Microsoft/msbuild/commit/51f6d763bdcaf3bdd24c0e0bca352141a94b378 commit as you know.

I tried to create a pull-req on the wiki page but GitHub still doesn't support sending pull-reqs against wiki pages. So, it'd be great if somebody have access rights modify the command example to:

> $ ./Tools/dotnetcli/dotnet ./Tools/MSBuild.exe /path/to/project

Maybe creating a simple wrapper(e.g. msbuild.sh / msbuild.cmd) could be a way to avoid confusion, but it's a different problem.

**Comment by Sarabeth-Jaffe-Microsoft** [comment]
Hi @muojp thanks for pointing this out! I've corrected the command in the wiki.
